### ISSUE TITLE
Queries with a "length" column break results table and can cause the page to hang

### ISSUE THREAD

**Issue by tsibley** [getredash/redash#1001]
For example, `SELECT 10 as length` will result in an empty results table despite the row count being 1.  If the values of the length column are large, for example, then the page will hang as the JS loops practically endlessly.  For example, `SELECT 1e9 as length`.

I tracked down the problem to [the `_.each(row, function(v,k) { … })` call in resources.js](https://github.com/getredash/redash/blob/master/rd_ui/app/scripts/services/resources.js#L39-L55).  Underscore's `each` function duck types Objects with a numeric `length` property as Array-likes and iterates from 0–N.  This is warned against in the [Underscore docs for each](http://underscorejs.org/#each).  It's worth noting that the problematic code in resources.js is already commented as being error-prone and slated for removal... :-)

**Comment by arikfr** [comment]
Nice find and thanks for the detailed report!

**Comment by fhoffa** [comment]
just noticed the same, re:dash breaks when a column is called 'length'

http://demo.redash.io/queries/3570/source

**Comment by arikfr** [comment]
Due to the complete rewrite of the table visualization, it's fixed in the master version (v1.0).
