### ISSUE TITLE
X axis labels get truncated when long enough in visualization/dashboard view

### ISSUE THREAD

**Issue by staritza** [getredash/redash#1006]
We created [this visualization ](https://demo.redash.io/embed/query/1545/visualization/2060?api_key=27990352780ec9339a6c6b3e4d643599e5239a71) in demo.redash.io which has the latest plotly.js update.

Downloaded images also have the labels truncated.

What we would like to see is that the visualization has room to show full labels for items on the x-axis (scrollbar, adjustable graph, etc...).

**Comment by arikfr** [comment]
Yeah, I'm aware of this. I thought that maybe if I let Plot.ly autosize the chart it will solve it, but looks like not. Seems like there is no automatic solution, so I'm thinking of letting the user control the margin size so they can decide how much space to give and if truncation is important to them.

**Comment by arikfr** [comment]
Fixed in #1007.
