### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by tjwudi** [getredash/redash#1010]
Have seen the awesome UI update and many more new features, I feel really excited about it! :) I was trying to setting up redash instance via docker, only to find older version was running inside container. Maybe it's time for a new build.

**Comment by arikfr** [comment]
The `latest` tag on Docker points to the latest release we mark as stable/latest which is currently `0.9.2`. But each build is also published as a tag on Docker. If you want to try out v0.10.0, just use the `0.10.0.b1767` tag.

0.10.0 will become latest next week.
