### ISSUE TITLE
OperationalError: could not connect to server:

### ISSUE THREAD

**Issue by HeyLynne** [getredash/redash#1011]
Hi I am connecting to the PostgreSql with redash. However when I run the excute queries, I got the error:
redash_1        | OperationalError: could not connect to server: No such file or directory
redash_1        |       Is the server running locally and accepting
redash_1        |       connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

I don't know how to deal with it. Please help me .

**Comment by arikfr** [comment]
Really hard to help without seeing full stacktrace and some more background on how you setup Redash.

Just to make sure: Redash's UI loads for you and this is what you get when trying to run a query, or this is an error you get when trying to start Redash?

**Comment by HeyLynne** [comment]
Hello,
Thank for your help soooooo much.I have solved this problem~
