### ISSUE TITLE
Reorganize the docs

### ISSUE THREAD

**Issue by jeffwidman** [getredash/redash#1012]
I was starting to put together a few PRs for the docs, and realized the overall organization feels a bit scattered:
1. It's not always clear when new docs are added which section they go in. 
2. Currently there's no place that I can point users with our organization toward when they ask me how to create/modify queries/dashboards.
3. When I eventually hand off managing our Re:dash instance, I want a section I can point the new admin at that will help him quickly come up to speed. 

What do you think of the following organization? 

It's certainly not perfect, but it feels like a step in the right direction, and certainly more organized than the current state of affairs. 

For the individual subsections, they don't have to be dedicated pages... if the sections are small enough, they can just go on a single page. 

Sphinx supports general section headings, so I organized it into documentation for users, admins, and developers. You can see an example of what the section headings look like here: http://read-the-docs.readthedocs.org/en/latest/faq.html

Once this is hashed out, I am willing to move the existing docs around to match.

---

---
1. Introduction
   
   a. brief overview of redash, and points folks towards either admin or user docs depending on whether redash is already setup

---
## User Docs
1. Writing Queries
   a. Basic example
   b. Adding visualizations
   c. Query params
   d. Filters
   e. Exporting results
   f. Scheduling queries
2. Creating Dashboards
   a. Assembled by grouping queries
   b. Query params are supported
   c. Using concatenation + query params to create tables of links to sub-dashboards
   d. Use ':' to group dashboards
3. Embedding
4. Notifications & Alerts
5. Moar?

---
## Admin Documentation
1. Overview for Administrators
   a. Mention /admin endpoint
2. Installing Redash
   a. Docker Compose
   b. Using pre-built AWS/Google Cloud images
   c. Manual provisioning script
3. Upgrading
   a. Docker
   b. Fabric script
4. Adding Datasources
   a. General instructions for adding datasources, for specifics of each datasource, point to datasource section 
5. Managing Users
   a. [manually creating them]
   b. [Google Oauth]
   c. [Understanding / using Groups]
     i. Limiting a user to only viewing certain data
6. Additional configuration
   a. Configuring Mail Server
   b. Setting up SSL
   c. Changing the number of workers
7. Maintenance
   a. Backups
   b. Logs

---
## Data Sources
1. Detailed docs on each datasource
   a. Configuring
   b. Querying
2. ElasticSearch
   a. Configuring
   b. Querying
3. etc

---
## Developer Documentation
1. Setting up a Vagrant Dev Environment
2. Redash Architecture
   - Explain overall architecture of flask + celery + angular
   - explain user/query data is stored in local postgres instance
   - query execution model
3. [something about using browser dev tools to view internal APIs]
4. Data Source Results Format

**Comment by jeffwidman** [comment]
Not sure of the best format for discussing this, alternatively I can put this into a text file in a PR and then people could comment on individual lines.

**Comment by arikfr** [comment]
👍 

I like this layout. Looks much clearer to me than what we have today.

Two things I would change:
- Add a dedicated section for "Installing Redash", to make it easy to find.
- I think that the "Querying" sections of the different data sources belong under User Docs. As this is where the people writing queries will look first, no?

Also, you have a few sections/subsections there that we currently don't have content for. I would keep the subsection headings for them, as pointer for documentation that is missing to invite others to fill the gaps.

**Comment by arikfr** [comment]
Check out the new documentation:

https://redash.io/help/ ([repo](github.com/getredash/website))

**Comment by jeffwidman** [comment]
Repo link in your comment is broken.

**Comment by arikfr** [comment]
Fixed.

**Comment by jeffwidman** [comment]
Thanks. Looks nice. Might modify the readme on that repo to make it more clear how it's laid out/how to contribute fixes. 

Afraid I haven't had much time to work on Redash as my day job prioritized working on another project lately.

**Comment by arikfr** [comment]
👍 It was an early release and for sure going to add a proper README.
