### ISSUE TITLE
Apache ReverseProxy in front of docker fails

### ISSUE THREAD

**Issue by thomas-barthelemy** [getredash/redash#1015]
I've setup latest master using docker-compose.
The server IP running the docker containers is `192.168.0.2`

Accessing directly `192.168.0.2`, `192.168.0.2:80` (duh), and `192.168.0.2:5000` all load properly.
Another Server is running **apache2** in order to ReverseProxy towards the different apps with the following regarding redash:

    <VirtualHost *:80>
        ServerName my.test.domain

        ProxyRequests off
        ProxyPreserveHost on
        ProxyPass / http://192.168.0.2/
        ProxyPassReverse / http://192.168.0.2/
    </VirtualHost>

Accessing `my.test.domain` loads, it's possible to login, but the angular app doesn't load and the main page ends up being empty (no user name in the top bar, no page content, links not working).

It seems to work the very first time a user is logged in on never-visited-before domain, after any link and logging out/in again gives that problem again.

Any idea on what I missed in my apache2 config?

**Comment by arikfr** [comment]
Check the browser console to see if there are any errors/clues to what might be amiss.

**Comment by thomas-barthelemy** [comment]
```
GET http://my.test.domain/ [HTTP/1.1 200 OK 31ms]
GET http://my.test.domain/styles/A.main.c2f315bd.css.pagespeed.cf.2cD-XFwV2z.css [HTTP/1.1 200 OK 30ms]
GET http://my.test.domain/scripts/plugins.9cfd2af7.js.pagespeed.jm.jJa1Exp9SI.js [HTTP/1.1 200 OK 248ms]
GET http://my.test.domain/scripts/scripts.863c5361.js.pagespeed.jm.hLG09lxSkm.js [HTTP/1.1 200 OK 42ms]
GET http://my.test.domain/images/redash_icon_small.png.pagespeed.ce.GfA6d35GIu.png [HTTP/1.1 200 OK 30ms]
GET http://my.test.domain/fonts/fontawesome-webfont.woff [HTTP/1.1 200 OK 23ms]
GET http://my.test.domain/fonts/glyphicons-halflings-regular.woff [HTTP/1.1 200 OK 24ms]
SyntaxError: nothing to repeat plugins.9cfd2af7.js.pagespeed.jm.jJa1Exp9SI.js:1:812060
ReferenceError: angular is not defined
```

**Comment by arikfr** [comment]
Maybe the pagespeed thing messes up the minified Javascript file, and it fails to load?

**Comment by thomas-barthelemy** [comment]
Added the following to my conf, will look into it later as for why this apache mod mess things up here
```
<VirtualHost *:80>
    ServerName my.test.domain
    ModPagespeed off

    ProxyRequests off
    ProxyPreserveHost on
    ProxyPass / http://192.168.0.2/
    ProxyPassReverse / http://192.168.0.2/
</VirtualHost>

Thanks for pointing in the right direction, for some reason I though this really came from re:dash #shame

**Comment by arikfr** [comment]
If it makes you feel better, it still might be an issue with Redash's minifed Javascript ;-)
