### ISSUE TITLE
Feature request: S3 connector

### ISSUE THREAD

**Issue by astewart-twist** [getredash/redash#1019]
S3 would be nice to use as both a data source and as a destination.  It would be very useful to be able to write a database query out to a file and then upload that file into S3 through redash.  Maybe this is already possible using the python data source?

**Comment by arikfr** [comment]
It is possible with the Python data source. You just need the right packages available and allowed in the source settings.

**Comment by astewart-twist** [comment]
Thanks, I'll give that a try.  I think the following sounds like good strategy:

1. setup postgres data source 
2. setup python data source with `requests`, `StringIO` and `boto3` modules
3. setup a redshift data source
4. setup a postgres query against a database
5. get the API url and key for the query (ie `http://localhost/api/queries/1/results/1.csv?api_key=xxx`
6. setup a python query that requests the api url into a StringIO object and stores the contents into an S3 object
7. setup a redshift query that tells redshift to `COPY` the csv from s3 into a table

That's pretty slick.

One more question if you don't mind:
* If I'm using the docker-compose deployment straight out of the box (that pulls the existing redash docker image), what would you recommend as the best way to install the additional python modules in the redash container?  I suppose I could tell docker-compose to build the Dockerfile with the python modules added, or possibly just create a new Dockerfile that extends the prebuilt one.  Just wondering if you have a better idea.  I'd prefer not to rebuild the image if possible.

**Comment by arikfr** [comment]
This is the kind of things you might do with Spotify's Luigi or AirBnB's Airflow. For simple use case, I can see the benefit of doing it with Redash though.

Re. setup no. 5: the Python query runner has a helper method (`get_query_result`) to get results of an existing query.

docker-compose: I think the easiest thing to do is to have a Dockerfile that extends `redash/redash`.

**Comment by astewart-twist** [comment]
Yeah, the line between a query/reporting platform like redash and a full fledged data pipeline orchestration framework like luigi or airplay is a bit grey.  I think the most relevant and simplest use case is just pushing csv/json data into S3 so that Redshift can ingest it via `COPY`.

**Comment by arikfr** [comment]
Redash supports Athena now which is very close to an S3 connector.
