### ISSUE TITLE
Upgrade to latest Plotly.js

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#1020]
Review their updates to see if there is native support for things we implemented ourselves, like ordering of category X axis.

**Comment by jhollowayj** [comment]
Have you looked into adding the ScatterGL option to the chart types?

**Comment by arikfr** [comment]
Not really. To support large data sets?

**Comment by jhollowayj** [comment]
Yeah.  I had a graph that I was trying to write and wrote the query wrong.  It came back trying to plot ~ 200K points and killed the tab.  ScatterGL seems to do just fine, and I think its a pretty simple thing to add (if I'm reading the code right) (here)[https://github.com/getredash/redash/blob/e20a00566afb7f0cb1dc82dad082967a9646f2e0/rd_ui/app/scripts/directives/plotly.js#L155] and (here)[https://github.com/getredash/redash/blob/e20a00566afb7f0cb1dc82dad082967a9646f2e0/rd_ui/app/scripts/visualizations/chart.js#L88].
