### ISSUE TITLE
Forgot my admin password

### ISSUE THREAD

**Issue by jeff1026j** [getredash/redash#1022]
Hi, is there a way to override my admin password ?

**Comment by arikfr** [comment]
Yes, with the CLI (`manage.py`). How did you install Redash?

**Comment by jeff1026j** [comment]
I create an Amazon instance, I can't find any docs regarding using the mange.py to change password, where it it ??

tsk

**Comment by arikfr** [comment]
From `/opt/redash/current` run:

`sudo -u redash bin/run ./manage.py users password email-of-admin new-password`

You can get help by running:

`sudo -u redash bin/run ./manage.py users --help`

**Comment by jeff1026j** [comment]
Got it!
