### ISSUE TITLE
Can't Connect to Mysql

### ISSUE THREAD

**Issue by jeff1026j** [getredash/redash#1023]
Hi, I'm using EC2 Instance with Mysql ( RDS )

I try to run a query and keep getting:
`Error running query: Can't connect to MySQL server on 'xxxx' (110)`

so I check the Security Group both in EC2 and RDS, and make sure to grant the account in MYSQL to access from anywhere 

`grant all on xxx.* to xxx@'%' identified by 'xxx';`

but when I use 
`apt-get install mysql-python` 

it said `Unable to locate package mysql-python` ?

**Comment by arikfr** [comment]
If you're getting "Can't connect..." message, then you already have the needed Python package.

How did you configure the security group? Did you use a security group as the source or an IP address?

**Comment by jeff1026j** [comment]
In RDS, I add the EC2 IP Source to the Security Group
In EC2,  I open the port 3306 ?

**Comment by arikfr** [comment]
And did you use the internal IP or the external one?

**Comment by jeff1026j** [comment]
I use the Public IP on the EC2 Instance Panel

**Comment by arikfr** [comment]
If they're in the same network, you probably need to use the internal IP.

**Comment by jeff1026j** [comment]
no luck, I add internal and external public IP to the RDS Security Group, but it still don't work

**Comment by jeff1026j** [comment]
ok I got it

I need to edit the RDS Security Group from RDS Instance, not from the left side of RDS menu, tks!
