### ISSUE TITLE
Upgrade to 0.10.0.b1774 erased all Dashboards

### ISSUE THREAD

**Issue by jasonshah** [getredash/redash#1025]
We upgraded from 0.9.2.b1536 to 0.10.0.b1774 this morning, and the 5 Dashboards we had in place got lost in the upgrade.
This is not a terribly big deal, as they can be rebuilt, in our case. It would have been worse if it was Queries. But, for other organizations that have more Dashboards or complex rules, this would have been disastrous.

We upgraded by building a new image using the base image hosted on Docker hub, and switched over to that new image.

**Comment by arikfr** [comment]
I don't think they were deleted. 

Did you run migrations after updating the image?

**Comment by karlgrz** [comment]
@arikfr that was the issue, after running the 3 migrations necessary our dashboards appear as expected.

**Comment by jasonshah** [comment]
Thanks @arikfr and @karlgrz .
