### ISSUE TITLE
Ability to schedule reports to be sent by email

### ISSUE THREAD

**Issue by devsprint** [getredash/redash#1026]
I think that it will be a great addition to the tool if there will be an option to schedule emails to be sent out  with results of queries.

**Comment by szsiddiq** [comment]
Looks like a duplicate of: https://github.com/getredash/redash/issues/14

**Comment by arikfr** [comment]
Duplicate of #14.
(and indeed it will be a great addition)

**Comment by shahneil88** [comment]
+1
