### ISSUE TITLE
Allow others to edit your Dashboard

### ISSUE THREAD

**Issue by rohanpd** [getredash/redash#1028]
Add the ability to have others change or contribute to your dashboard.

**Comment by arikfr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;9LvJzgXG&#x2F;64-allow-others-to-edit-your-dashboards"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Allow others to edit your dashboards</a>

**Comment by arikfr** [comment]
Something like Google Docs sharing options (set read/write access permissions to dashboard based on individual users and/or groups).

**Comment by arikfr** [comment]
This was implemented and part of 0.12. Although in 0.12 this is behind a feature flag.
