### ISSUE TITLE
MySQL support

### ISSUE THREAD

**Issue by Ethreal** [getredash/redash#1031]
Hey

It's Bookmate team on the phone. We started to use re-dash at http://analytics.bookmate.com/
Are you planning MySQL support? Since we have MySQL in our environment, it's strange to add postgre for one analytical dashboard. What would you say?

Thanks in advance.

**Comment by arikfr** [comment]
No plans for MySQL support. We actually plan to use more of PostgreSQL's features (like FTS) so the code won't be as portable.

Considering that Redash doesn't require much resources, and you can run the whole thing, including the DB, on a single instance I don't see why this is an issue.
