### ISSUE TITLE
There is no data in my Query Queue monitor

### ISSUE THREAD

**Issue by simzen85** [getredash/redash#1041]
I checked out the new Query Queue monitor but see no info here while my Redash instance still works properly and I probably have ~100+ queries there, I also have admin rights.

![redash-query-status-bug](https://cloud.githubusercontent.com/assets/710654/15103983/fa898c0c-15db-11e6-9321-ab12cc3cdc6e.png)

**Comment by arikfr** [comment]
Do you see any errors in your browser console when opening this page?

**Comment by simzen85** [comment]
@arikfr yes, there is a bunch of 403 ...

![redash-query-status-bug-2](https://cloud.githubusercontent.com/assets/710654/15119224/19fed8cc-163a-11e6-9c42-e2a5afaab159.png)

**Comment by arikfr** [comment]
Is your user a member of the admin group? 

If it is:
1. Did you apply the last migrations when upgrading?
2. Does the admin group has the `super_admin` permission?

**Comment by simzen85** [comment]
tks @arikfr 

You're correct, my user belongs to an "Administrator" group, but that group doesn't have "super_admin" permission. It's strange because this is the first time I know about that permission, is it something new ?

Once I added it, I can view the Queue monitor with data

**Comment by arikfr** [comment]
Not new at all, but the super_admin permission is new. We had a migration that applied it to the admin group, but yours has a different name so it was skipped.
