### ISSUE TITLE
Counter for "Done" queries in the new Query monitor seems to stuck at 50

### ISSUE THREAD

**Issue by simzen85** [getredash/redash#1047]
![redash-query-status-bug-counter](https://cloud.githubusercontent.com/assets/710654/15135709/a18e7f7c-16a3-11e6-8c37-3722d513679a.png)

**Comment by rohanpd** [comment]
I believe that this is just a rolling last 50 queries.

**Comment by simzen85** [comment]
@rohanpd got your point. I guess this is feature not bug :) I'm closing this

**Comment by arikfr** [comment]
I'm not sure if it is a bug or feature, but it is confusing... I think we should remove the counter there. WDYT?

**Comment by rohanpd** [comment]
Yeah I don't think the counter is useful here.
