### ISSUE TITLE
Bar chart - Issues with x axis

### ISSUE THREAD

**Issue by feedesam** [getredash/redash#1048]
I'm plotting a bar chart with three different series, one that has data for the entire period (let's say 30 dyas) and two that have data for half of the period each (let's say 15 days).  When I try to plot them in the automatic order everything looks fine, but when I try to switch the order between them, in order to make the chart readable, a blank space is created between some of the bars. Y axis: sum, X axis: date.

Automatic sorting: 
<img width="496" alt="screen shot 2016-05-10 at 10 11 19" src="https://cloud.githubusercontent.com/assets/8792069/15139881/d383ed9c-1698-11e6-9b21-63c651372567.png">

Custom sorting with random white space on the left:
<img width="465" alt="screen shot 2016-05-10 at 10 11 06" src="https://cloud.githubusercontent.com/assets/8792069/15139882/d387c2aa-1698-11e6-8c56-b9103543618a.png">

System details: OS X 10.11.4 / Chrome 49.0.2623.110

**Comment by feedesam** [comment]
Related bug on bar and line charts: when applying multi filter, the figures are not grouped.

**Comment by arikfr** [comment]
Can you provide a sample dataset which we can use to reproduce?

**Comment by arikfr** [comment]
Please reopen with steps to reproduce / sample dataset.
