### ISSUE TITLE
Error installing redash: ImportError no module named fancy

### ISSUE THREAD

**Issue by shardick** [getredash/redash#1051]
Hi,

i'm installing redash on Ubuntu using the bootstrap.sh script but i'm getting this error

Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages
The system user `redash' already exists. Exiting.
psql (PostgreSQL) 9.3.12
redis-cli 2.8.17
Traceback (most recent call last):
  File "/opt/redash/redash.0.10.0.b1774/manage.py", line 9, in <module>
    from redash import settings, models, __version__
  File "/opt/redash/redash.0.10.0.b1774/redash/__init__.py", line 11, in <module>
    from redash import settings
  File "/opt/redash/redash.0.10.0.b1774/redash/settings.py", line 4, in <module>
    from funcy import distinct, remove
ImportError: No module named funcy

Distribution:
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial

Thanks for your help

Regards

Francesco

**Comment by arikfr** [comment]
It looks like you're running the script for a second time. What happened
the first time?

**Comment by shardick** [comment]
I got an error regarding Pip regarding no access to .cache and that the versione of Pip was old. So i've updated Pip to latest version and executed the bootstrap.sh with sudo -H .

Can i recover for this?

**Comment by shardick** [comment]
I removed /opt/redash and retried installation from bootrasp.sh

Got this error:

Running setup.py bdist_wheel for cryptography ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ylbyOS/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpc6bT1Epip-wheel- --python-tag cp27:
  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory

So installed libffi-dev via apt, removed /opt/redash and ran the script, it worked :)

**Comment by arikfr** [comment]
Great. In general, the script isn't idempotent and designed to once. If it fails, it's better to understand why it failed and plan the subsequent run accordingly.

Also it wasn't tested on Ubuntu 16.04 until now so it might explain why it failed the first time.

Can we close this now?

**Comment by shardick** [comment]
Yes, thanks.

**Comment by dfisla** [comment]
Hi, I have the same issue, ubuntu 16.04 LTS as well. I understand that this version of ubuntu is unsupported, but would it be possible to dump the database SQL (DDL+DML) for the postgres redash database in an SQL script.

I manually re-run all the commands in the bootstrap.sh script, managed to get everything working except the database creation which is currently generated using python calls. It would be much easier to create the redash database using a single DB SQL script. I am more familiar with MySQL than Postgres, but would it be possible to do the equivalent of mysqldump and export the initial database into a SQL file?

Many thanks.

**Comment by dfisla** [comment]
Resolved! My bad, after reconstructing the bootstrap steps I forgot to run 'pip install -r requirements.txt' hence the missing funcy 1.5 module

after that './bin/run ./manage.py database create_tables' ran just fine.

**Comment by arikfr** [comment]
@dfisla cool, glad you got it working.

**Comment by dfisla** [comment]
Yes, can confirm that the latest code runs without issues on ubuntu 16.04 LTS.
