### ISSUE TITLE
Filter not showing all the result after selection

### ISSUE THREAD

**Issue by ChiragKParmar** [getredash/redash#1052]
### Issue Summary

Filter option.

### Steps to Reproduce

Please take a look at https://demo.redash.io/queries/1699 query

Expected behaviour was when one selects date, UI should show all the records for that day which is not happening. 

<img width="471" alt="screen shot 2016-05-12 at 5 10 27 pm" src="https://cloud.githubusercontent.com/assets/15158968/15230678/e3b564b6-1864-11e6-86cc-a8c06a3d5ae4.png">
<img width="1130" alt="screen shot 2016-05-12 at 5 14 00 pm" src="https://cloud.githubusercontent.com/assets/15158968/15230685/f127d002-1864-11e6-8a15-815c02c4d8ac.png">

**Comment by arikfr** [comment]
For some reason it doesn't group the same dates. Need to check how it does the comparison.

**Comment by Harshit-Delhivery** [comment]
Hi,

I am facing the same issue and this happens only with the date field. I also tried to convert my date object to CHAR (string) but still doesn't work. Please respond if solved.
