### ISSUE TITLE
Friendly Name not Being applied to Results

### ISSUE THREAD

**Issue by seigel** [getredash/redash#1055]
### Issue Summary

When specifying a "friendly_name" in the add_result_column of the python query runner interface the friendly name isn't being used to relabel the result columns
### Steps to Reproduce
1. Create a new python query runner
2. Pull data from two queries
3. Add a new result column to one of the query results
4. Specify a Friendly name: add_result_column(result, u'item_name', u'Item Name', u'string')
5. Run your query.  The name will be the column name, not the friendly name.
### Technical details:
- Redash Version: Re:dash 0.10.0+b1774
- Browser/OS: Chrome OSX
- How did you install Redash: Packages on AWS
  ![copy_of___39__top_sellers__re_dash_and_log___logentries](https://cloud.githubusercontent.com/assets/15181/15263808/7c89c6d0-192a-11e6-8311-8442edeed694.png)

**Comment by arikfr** [comment]
Thank you for the detailed description.

The `friendly_name` field was added to be used in the future, and we never got to actually using it... In theory it should be used in the [`getColumnFriendlyNames` function](https://github.com/getredash/redash/blob/master/rd_ui/app/scripts/services/resources.js#L313). We can check for a value in the `friendly_name` field and fallback to the current implementation if there is none.

**Comment by seigel** [comment]
Excellent.  If I find some time before you do, I'll see if I can figure out a pull request for that.

**Comment by seigel** [comment]
Would this be the right location to be doing something? In the [```getColumnFriendlyName```](https://github.com/getredash/redash/blob/fec0d5feccf8012c8b4cd718c0b80f9bd3d6c75e/rd_ui/app/scripts/services/resources.js#L302) function?  I'm pretty new to this codebase.

**Comment by arikfr** [comment]
Not exactly, because this function gets just the column name, and doesn't have reference to the column object.

To do it properly, you will need to understand how the different column related functions are used and probably do some cleanup there. From a quick look it seems that the code there accumulated some cruft.

**Comment by deecay** [comment]
Did refactoring for rc1 make things easier for friendly_names?
I am eager to see this feature to be added.

**Comment by arikfr** [comment]
It didn't change anything about that.. but it's not a hard task, just need to track down all the uses and do some house order.
