### ISSUE TITLE
PostgreSQL passwords with spaces are not supported

### ISSUE THREAD

**Issue by jhollowayj** [getredash/redash#1056]
The connection info string on line /opt/redash/current/redash/query_runner/pg.py cant contain spaces, so something like `host=hostname password=my secret password dbname=awesome_db_name user=postgres` will throw the error `OperationalError: missing "=" after "secret" in connection info string`.

Error happens at [pg.py#L117](https://github.com/getredash/redash/blob/fbb81b62d6c79f8e9381ac8973ac34739bfa6b41/redash/query_runner/pg.py#L117), but the connection string is built [pg.py#L87](https://github.com/getredash/redash/blob/fbb81b62d6c79f8e9381ac8973ac34739bfa6b41/redash/query_runner/pg.py#L87).

According the [psycopg2 docs](http://initd.org/psycopg/docs/module.html), you could use:
`conn = psycopg2.connect("dbname=test user=postgres password=secret")`
or 
`conn = psycopg2.connect(database="test", user="postgres", password="secret")`
Currently the first is being used.

**Comment by jhollowayj** [comment]
According the [psycopg2 docs](http://initd.org/psycopg/docs/module.html), you could use:
```conn = psycopg2.connect("dbname=test user=postgres password=secret")```
or 
```conn = psycopg2.connect(database="test", user="postgres", password="secret")```
Currently the first is being used.

**Comment by arikfr** [comment]
As you suggest, we should switch to using the dictionary format of the `connect` method.

**Comment by jhollowayj** [comment]
On Monday, I'll try to write up a quick fix and see if there are any other places I see the same error and let you know.

**Comment by arikfr** [comment]
Thanks!

**Comment by jhollowayj** [comment]
I tried to check things out by switching to a dictionary but I wasn't seeing the logs print out any more.  So I'm not sure what happened, but I've spent all the time I could on it today and ended up just changing the password.

**Comment by arikfr** [comment]
No worries. Whenever you get the chance, it will be appreciated.

Ping on me on chat, when you get to work on it again if you stumble at issues with logging.

**Comment by jiphex** [comment]
I've noticed a related problem with this - if the password field is blank (represented as an empty string in the Redash postgreSQL DB) then Redash seems to try and also confuse the fields, it seemed to mess up the selection of the database.

In my case I'm using SSL client cert authentication so the password isn't used, with a blank field Redash tried to connect to a database with the same name as the username field, rather than the one specified in the dbname
