### ISSUE TITLE
Using a template ready for dashboards, for example adminlte.

### ISSUE THREAD

**Issue by joaoleite** [getredash/redash#1068]
There are some very interesting bootstrap templates for dashboards. I think you should know. Have you thought of using them?

Example of an amazing dashboard, allowing drag and drop and reduce / expand the boxes of the charts, and place them on a grid of 12 columns.

link: https://almsaeedstudio.com/themes/AdminLTE/index.html

Any? Idea of applying a template? Until I contemplated the idea of a fork and then with that line. What do you think?

Hugs,

**Comment by arikfr** [comment]
The ability to change position or size of widgets isn't a property of the theme, but rather some library they use.This is covered by #335.
