### ISSUE TITLE
Visualisations not taking up the full width

### ISSUE THREAD

**Issue by rohanpd** [getredash/redash#1071]
### Issue Summary

Visualisations don't take up the full width until you show the query source.

### Steps to Reproduce

1. Click on a query with a visualisation
The visualisation will only take up half the width:
![image](https://cloud.githubusercontent.com/assets/7199904/15457614/dc43e266-20cf-11e6-9394-77422151c42a.png)

2. Click on "Show Source"
The visualisation will now show in the full width:
![image](https://cloud.githubusercontent.com/assets/7199904/15457620/00ac1470-20d0-11e6-97ec-1fe3610f64c6.png)

If you now hide the source the visualisation will remain in full width. I'd expect that the visualisation should be full width throughout the whole experience.

### Technical details:

* Redash Version: 0.10.1+b1836
* Browser/OS: Chrome
* How did you install Redash: Amazon AMI

**Comment by arikfr** [comment]
It was fixed in #1040 by not rendering them in the background.

**Comment by rohanpd** [comment]
Hey @arikfr, I am running the latest commit 0.10.1+b1836.

Could a recent commit regressed your recent fix?

**Comment by arikfr** [comment]
0.10.1 is 0.10.0 and the memory leak fix. #1040 is part of 0.11.0 (which isn't the latest yet, as it's still being developed).
