### ISSUE TITLE
Redash service can't start if REDASH_MAIL_USE_TLS is in .env file

### ISSUE THREAD

**Issue by yershalom** [getredash/redash#1073]
### Issue Summary

After upgrade from 0.9 to 0.10, I got a massage to fix mail settings.
I added my mail setting as describe in [this doc](https://github.com/getredash/redash/blob/master/docs/setup.rst#mail-configuration)

After that i got an error in /opt/redash/logs/celery_error.log
`File "/opt/redash/redash.0.10.1.b1834/redash/settings.py", line 133, in <module>
    MAIL_USE_TLS = parse_boolean(os.environ.get('REDASH_MAIL_USE_TLS', 'false'))
    MAIL_USE_TLS = parse_boolean(os.environ.get('REDASH_MAIL_USE_TLS', 'false'))
  File "/opt/redash/redash.0.10.1.b1834/redash/settings.py", line 41, in parse_boolean
    return json.loads(str.lower())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
  File "/opt/redash/redash.0.10.1.b1834/redash/settings.py", line 41, in parse_boolean
    return json.loads(str.lower())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError    raise ValueError("No JSON object could be decoded")
ValueError: Couldn't import u'redash.worker': No JSON object could be decoded
: Couldn't import u'redash.worker': No JSON object could be decoded`

### Steps to Reproduce

1. Just add `export REDASH_MAIL_USE_TLS` to the .env file
2. Start the redash_supervisor service.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* OS: Ubuntu 14.04.4 LTS
* How did you install Redash: Via script, upgraded via fabric

**Comment by arikfr** [comment]
This is not a bug (although the error message can be friendlier). The `REDASH_MAIL_USE_TLS` setting (and the SSL setting too) expects either `false` or `true` as values.

**Comment by yershalom** [comment]
Tnx for the enlightenment
