### ISSUE TITLE
NameError: global name 'hive' is not defined

### ISSUE THREAD

**Issue by nabilblk** [getredash/redash#1076]
### Issue Summary
I configure a Hive dataSource and try to execute a simple query 
and i got this error : 
redash_1       | [2016-05-25 14:52:33,854: ERROR/Worker-27] global name 'hive' is not defined
redash_1       | Traceback (most recent call last):
redash_1       |   File "/opt/redash/current/redash/query_runner/hive_ds.py", line 94, in run_query
redash_1       |     connection = hive.connect(**self.configuration.to_dict())
redash_1       | NameError: global name 'hive' is not defined
redash_1       | [2016-05-25 14:52:33,855: ERROR/Worker-27] redash.tasks.refresh_schemas[aae957b8-1c51-428b-8f56-9a058be6cdc9]: Failed refreshing schema for the data source: My Cluster 
redash_1       | Traceback (most recent call last):
redash_1       |   File "/opt/redash/current/redash/tasks/queries.py", line 349, in refresh_schemas

### Technical details:
* Redash Version: latest
* Browser/OS: docker 
* How did you install Redash: with the latest docker-compose-example.yml

**Comment by arikfr** [comment]
You're missing the pyhive package and its dependencies. It's not installed by default with the `redash/redash` Docker image. You will need to build one yourself (based on it). If you happen to do, please share the Dockerfile, as we might add it to the main one.

**Comment by nabilblk** [comment]
Hi , 
Thanks for your response . 
I try to install the PyHive dependencies , and i got this : 

root@6418db1e8d50:/opt/redash/current# pip install pyhive      
Requirement already satisfied (use --upgrade to upgrade): pyhive in /usr/local/lib/python2.7/dist-packages
Cleaning up...

is this mean that pyhive is correctly installed ?

**Comment by nabilblk** [comment]
Any help on this .
 
I think the latest docker image contains the pyhive and it's dependencies installed but it still showing the same error .

Thanks in advance .

**Comment by nabilblk** [comment]
I add the additional dependencies and i build a new docker image : 

`root@e9553522137a:/opt/redash/current#` pip install pyhive
Requirement already satisfied (use --upgrade to upgrade): pyhive in /usr/local/lib/python2.7/dist-packages
Cleaning up...
root@e9553522137a:/opt/redash/current# pip install pyhive[hive]
Requirement already satisfied (use --upgrade to upgrade): pyhive[hive] in /usr/local/lib/python2.7/dist-packages
  Installing extra requirements: 'hive'
Requirement already satisfied (use --upgrade to upgrade): sasl>=0.1.3 in /usr/local/lib/python2.7/dist-packages (from pyhive[hive])
Requirement already satisfied (use --upgrade to upgrade): thrift>=0.8.0 in /usr/local/lib/python2.7/dist-packages (from pyhive[hive])
Requirement already satisfied (use --upgrade to upgrade): six in /usr/local/lib/python2.7/dist-packages (from sasl>=0.1.3->pyhive[hive])
Cleaning up...`

But still having the same error . 

@arikfr Did i miss something ?

**Comment by arikfr** [comment]
Can you try running "from pyhive import hive" in a Python interpreter
inside the container and see if you get an error?
