### ISSUE TITLE
Lost data sources and dashboards after update

### ISSUE THREAD

**Issue by eamonnfaherty** [getredash/redash#1079]
I was running re:dash 0.9.2+b1390 via docker and I changed my docker container version to 0.11.0.b1848 and bounced the app.  I am using the same db.

Now my data sources and dashboards have disappeared. I have tried to readd them and it fails saying the source exists already.

Am I missing something?

**Comment by arikfr** [comment]
Did you run migrations after upgrading?

In the future, please follow the instructions, and open a thread in the support forum for such questions: https://discuss.redash.io/c/support.

**Comment by eamonnfaherty** [comment]
Thanks for the reply.

I did not run the migrations.  I could not see any instructions on how to upgrade docker container versions.  I thought some of the first run of the container may do it for me.

Do you know how I can run the migrations please?  I cannot see this from the docs.

**Comment by eamonnfaherty** [comment]
I can only see this for migrations in the docs: 
http://docs.redash.io/en/latest/search.html?q=migrations&check_keywords=yes&area=default

There is a fabric script that can work out which migrations based on old and new version folders but there is no old version in the new docker container.  Also, the most recent migration is over 2 months old so I am guessing it is not needed.

Will it cause any issues if I run the migration if it is not needed?

**Comment by arikfr** [comment]
Because there is no documented process for running migrations (and upgrade) for Docker, we don't recommend it "officially" for usage and assuming that those who still want to use Docker will figure it out.

You should compare the list of migrations between the old image and your current one to see which ones you need to run. 

How to run them depends on your Docker setup. Do you use Docker compose?

But in general it's something along the lines of: `PYTHONPATH=. python migrations/<migration filename>` from `/opt/redash/current` for each migration file.

**Comment by arikfr** [comment]
And once this process will be automated, we will make Docker the recommended deployment method and have it run on container startup...

**Comment by eamonnfaherty** [comment]
Thanks for your help.  I diffed the source code and found the migrations.  I had to recreate my .env file again and run:
    PYTHONPATH=. bin/run python migrations/0021_create_api_keys_table.py
    PYTHONPATH=. bin/run python migrations/0022_add_new_permissions.py
    PYTHONPATH=. bin/run python migrations/0023_make_sure_correct_group_type.py
from /opt/redash/current

**Comment by arikfr** [comment]
👍

**Comment by omeryar** [comment]
Hey @eamonnfaherty would you mind giving some more details on how you got the migrations to run?
I'm stuck in a similar situation and haven't been able to work it out.
The migration script tries connecting to Redis (as part of the version_check.py) but doesn't manage to and throws this out:

>   File "migrations/0025_add_query_snippets_table.py", line 1, in <module>
    from redash.models import db, QuerySnippet
  File "/opt/redash/current/redash/__init__.py", line 60, in <module>
    reset_new_version_status()
  File "/opt/redash/current/redash/version_check.py", line 34, in reset_new_version_status
    latest_version = get_latest_version()
  File "/opt/redash/current/redash/version_check.py", line 40, in get_latest_version
    return redis_connection.get(REDIS_KEY)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 880, in get
    return self.execute_command('GET', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

**Comment by omeryar** [comment]
Nevermind.

In case someone ever encounters this, this is what worked for me:
(I didn't bother with a .env. It does raise a warning but seems to work anyway)
- shut down redash
- configure the redis container to open up port 6379 (modify the redis section in docker-compose.yml to include:
```yml
ports:
  - "6379:6379"
```
)
- start redash
- log on to the redash container
- cd to /opt/redash/current (if not already there)
- run the relevant migration scripts as described above (e.g. `PYTHONPATH=. bin/run python migrations/00...py`)

That should be it.
You'll probably want to remove the port mapping in docker-compose once you're done.
