### ISSUE TITLE
Error: Run error when DataSource-name contains non Ascii chars

### ISSUE THREAD

**Issue by ebertti** [getredash/redash#1094]
### Steps to Reproduce

1. Create a Datasource with non Ascii chars
2. Run query

### Log

```[2016-06-03 17:14:17,060: ERROR/MainProcess] Task redash.tasks.refresh_schemas[3df43113-6087-4698-ad54-d1eebe47c83a] raised unexpected: UnicodeEncodeError('ascii', u'Indicadores Avalia\xe7\xe3o', 18, 20, 'ordinal not in range(128)')```

This DataSource name is `Indicadores Avaliação`

### Technical details:

* Redash Version: docker:lastest
* Browser/OS: Chrome
* How did you install Redash: docker

**Comment by arikfr** [comment]
This was fixed in #1085 and will be part of the 0.11 release. Latest Docker image points to 0.10.1 which is the latest stable release.
