### ISSUE TITLE
It does not work or Firefox or Edge

### ISSUE THREAD

**Issue by matbott** [getredash/redash#1107]
If I open redash from firefox or Edge does not load the graphics, but if top bar.

**Comment by arikfr** [comment]
I think it's an issue with how the Bitnami image is setup the PageSpeed Apache plugin breaks the Javascript. Until this is fixed you can use a different browser.

Same here, please use the forum for support questions.

**Comment by arikfr** [comment]
For reference see: https://community.bitnami.com/t/re-dash-vm-image-not-working-under-firefox/42129

**Comment by matbott** [comment]
thanks, had seen the documentation but it has not helped me, in the end the problem was in the certificate, solve it using https.
Greetings.
