### ISSUE TITLE
Mixed view_only in multiple data_source_groups blocks query executions

### ISSUE THREAD

**Issue by yanenok** [getredash/redash#1109]
A user belonging to multiple groups that have access to one data source but with different access levels can not execute queries on that data source.

For example, if a user belongs to built-in `default` group and you have set `view_only` for all data sources in this group to true, adding this user to a new group to allow full access to one of the data sources will not work.

This is caused by `group_level` definition in `def has_access()` in [permissions.py](https://github.com/getredash/redash/blob/master/redash/permissions.py):

    required_level = 1 if need_view_only else 2
    group_level = 1 if any(flatten([object_groups[group] for group in matching_groups])) else 2
    
    return required_level <= group_level

**Comment by arikfr** [comment]
Thanks!
Fixed in #1110.
