### ISSUE TITLE
Upgrade Flask to 0.11.1

### ISSUE THREAD

**Issue by jeffwidman** [getredash/redash#1112]
- [ ] Upgrade all Flask extensions
- [ ] Upgrade to latest Flask 0.11 release
- [ ] Bonus: replace Flask-Script with Click

**Comment by arikfr** [comment]
Is it a "simple" upgrade or there are some backward incompatible behaviors?

**Comment by jeffwidman** [comment]
Most of it should be fairly straightforward. The tricky part is redash is currently using older versions of several Flask extensions, so those may need to be upgraded as well, I'm not sure.

There are a couple of niceties:
 - Allowing arrays again in top-level JSON: https://github.com/pallets/flask/pull/1671
- Switching to a Click-based integration. You can continue to use Flask-Script, but Click (currently) seems to be the long-term way forward.

**Comment by arikfr** [comment]
I've updated the issue description with the steps (upgrade extensions -> upgrade Flask -> replace Flask-Script).

**Comment by jeffwidman** [comment]
Hooray! Thanks @washort!
