### ISSUE TITLE
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes

### ISSUE THREAD

**Issue by FedericoPonzi** [getredash/redash#1114]
### Issue Summary
I was trying to compile redash ui with bower, and i get:

    bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes

The offending name was:

    "name": "rdUi",

Setting lowercase U resolved the issue.

**Comment by arikfr** [comment]
Fixed a few days ago in cbbfc4e9318eefd4e7080fac3e35be2cbc38bf22. Make sure you have latest master.
