### ISSUE TITLE
Upgrade frontend stack

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#1125]
Our frontend stack is becoming more and more outdated which makes keeping up with best practices harder. Once we start actually working on this, we should probably split this into multiple steps.
1. Upgrade to Angular 1.5 (we're on 1.2 at the moment...).
2. Switch to using npm and Webpack instead of Bower & Gulp. We can consider using SystemJS, but looks like Webpack is industry standard, so probably better to stick to it.
3. Implement [latest style guide](https://github.com/toddmotto/angular-styleguide/blob/master/README.md) -- mainly rewrite all our directives as components, remove controllers, etc.
4. Reduce dependency on Angular specific stuff (`angular.module`, `service`, etc) by using regular Javascript modules.
5. ... significant time later ... Rewrite all components as React components 😝 .

**Comment by ninneko** [comment]
I feel it hard to understand frontend codes, so I will be happy when refactor frontend codes.

**Comment by arikfr** [comment]
Might be useful: http://ngmigrate.telerik.com/from-ng-controller-to-component-classes?utm_source=javascriptweekly&utm_medium=email

**Comment by eiso** [comment]
@arikfr I saw you're about to work on this, out of curiosity are you switching to yarn instead of npm?

**Comment by arikfr** [comment]
@eiso not sure. I might give it a try and if it just works will try to use it, but it's less of a priority right now.

**Comment by danlg** [comment]
@arikfr ... Rewrite all components as React components.. at least one so that people who want to contribute and add react component in a plugin manner like grafana in redash can do it. You should reopen this issue as this is not finished.

**Comment by oliviertassinari** [comment]
> ... significant time later ... Rewrite all components as React components stuck_out_tongue_closed_eyes .

It's never too late to use React 👌.

**Comment by kravets-levko** [comment]
> It's never too late to use React

@oliviertassinari It's already in progress :wink:
