### ISSUE TITLE
Bug: User can't run a query if he is in a group with view_only permission on a given datasource

### ISSUE THREAD

**Issue by WesleyBatista** [getredash/redash#1132]
### Issue Summary

I think that I found a bug within the permissions system that we have today. We are ignoring the permissions of a group with FULL access to a datasource.

### Steps to Reproduce

1. Create "group-1-FULL" group and add "**datasource-X**" datasource with "FULL" permission;
2. Create "group-1-VIEW" group and add "**datasource-X**" datasource with "VIEW" permission;
3. Add the user X to **group-1-FULL** and **group-1-VIEW**
4. Try to run a query which access the **datasource-X**

The buttons are inactivated. I expect to be able to run the query.

### Technical details:

* Redash Version: Re:dash 0.10.1+b1836
* Browser/OS: Chrome/Mac
* How did you install Redash: docker-compose

**Comment by arikfr** [comment]
Fixed in #1110.
