### ISSUE TITLE
Feature - grid-style spreadsheet

### ISSUE THREAD

**Issue by matbott** [getredash/redash#1134]
add data source xls files or have agrid-style spreadsheet to sort the data and plot them.
like this
![captura](https://cloud.githubusercontent.com/assets/6383365/16134316/df9b7f74-33f2-11e6-8484-3e72cba26988.PNG)

**Comment by arikfr** [comment]
Please use the [discussion forum](https://discuss.redash.io) for feature requests/suggestions.
