### ISSUE TITLE
AMI in ap-northeast-2 (Seoul)

### ISSUE THREAD

**Issue by angdev** [getredash/redash#1135]
Hi, Could I use redash ami in ap-northeast-2 (Seoul)? There is only ami for ap-northeast-1 (redash-0101b1834.1-ap-northeast-1, ami-78967519).

FYI, ap-northeast-2 (Seoul) is new region of AWS launched at January 7th, 2016.

Thanks.

**Comment by arikfr** [comment]
Sure! When I create an AMI for 0.11 I will also create one in ap-northeast-2.

**Comment by arikfr** [comment]
It's finally here: [ami-8f29e3e1](https://console.aws.amazon.com/ec2/home?region=ap-northeast-2#LaunchInstanceWizard:ami=ami-8f29e3e1).
