### ISSUE TITLE
Table name stuck in cache

### ISSUE THREAD

**Issue by tothandor** [getredash/redash#1137]
### Issue Summary

_A summary of the issue and the browser/OS environment in which it occurs._
I have installed a Docker instance for evaluation based on [your description](http://docs.redash.io/en/latest/setup.html#docker-compose). For first I gave the wrong database for the data source, and failed to connect a few times. Then I've created a query, and tried to add a line chart to it, but as seen in the stack trace on the console, reDash was querying the wrong table's schema.

### Steps to Reproduce

1. Create a Docker instance
2. Add an Impala data source, with beeswax 
3. Create a query for that data source
4. Realize that you have set a different database name, than you need
5. Change the database name to the correct value
5. Return to the query
6. Try to add a line chart to it
7. You won't be able to do so, because reDash tries to get schema for a different table

_Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?_
Because without charts reDash is not that useful. :). 
The error persists after restart. Postgres contains correct values for everything. I have cleared the Redis database (after stopping it), and the problem still holds. Created new queries, different datasources for the same host, and still.

### Technical details:

* Redash Version: 0.8.3+b1192 
* Browser/OS: CentOS 7.2 64-bit
* How did you install Redash: Docker

Stack trace from console:

> redash_1        | [2016-06-16 21:03:29,977][PID:24][ERROR][redash.wsgi] Internal Error
> redash_1        | Traceback (most recent call last):
> redash_1        |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
> redash_1        |     rv = self.dispatch_request()
> redash_1        |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
> redash_1        |     return self.view_functions[rule.endpoint](**req.view_args)
> redash_1        |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 384, in wrapper
> redash_1        |     resp = resource(*args, **kwargs)
> redash_1        |   File "/usr/local/lib/python2.7/dist-packages/flask_login.py", line 758, in decorated_view
> redash_1        |     return func(*args, **kwargs)
> redash_1        |   File "/usr/local/lib/python2.7/dist-packages/flask/views.py", line 84, in view
> redash_1        |     return self.dispatch_request(*args, **kwargs)
> redash_1        |   File "/opt/redash/current/redash/handlers/base.py", line 21, in dispatch_request
> redash_1        |     response = super(BaseResource, self).dispatch_request(*args, **kwargs)
> redash_1        |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 474, in dispatch_request
> redash_1        |     resp = meth(*args, **kwargs)
> redash_1        |   File "/opt/redash/current/redash/handlers/data_sources.py", line 79, in get
> redash_1        |     schema = data_source.get_schema()
> redash_1        |   File "/opt/redash/current/redash/models.py", line 323, in get_schema
> redash_1        |     schema = sorted(query_runner.get_schema(), key=lambda t: t['name'])
> redash_1        |   File "/opt/redash/current/redash/query_runner/impala_ds.py", line 91, in get_schema
> redash_1        |     columns = map(lambda a: a['Column'], self._run_query_internal(columns_query % table_name))
> redash_1        |   File "/opt/redash/current/redash/query_runner/__init__.py", line 99, in _run_query_internal
> redash_1        |     raise Exception("Failed running query [%s]." % query)
> redash_1        | Exception: Failed running query [show column stats MISTYPED_TABLE_NAME;].

**Comment by arikfr** [comment]
How failing to load the schema prevents you from creating the chart? Does it block the UI?

Are you sure the error is due to bad database name? Because if all the values are correct in PG, then where does it come from?
