### ISSUE TITLE
Gmail is merging [OK] and [Triggered] alert emails

### ISSUE THREAD

**Issue by tpatel** [getredash/redash#1144]
### Issue Summary

In Gmail the alert emails from redash are merged on the same thread, which makes it hard to know if an alert was triggered or solved.

Here is the explanation of the behavior of Gmail:
https://www.quora.com/Why-when-I-edit-subject-in-email-and-add-the-symbols-at-the-beginning-of-the-current-subject-to-keep-email-in-the-same-thread-the-email-sometimes-get-divided-in-a-new-thread-and-sometimes-doesnt/answer/Vineet-Chawla

### Steps to Reproduce

1. Setup an alert, register to receive email updates on a gmail address
2. Trigger the alert
3. Change the query and re-run it so that redash sends the email starting with [OK]
4. In gmail you will see the two emails under the subject starting with [Triggered] like this screenshot: ![screenshot from 2016-06-19 14 24 07](https://cloud.githubusercontent.com/assets/494686/16177359/7c8ddc8a-362a-11e6-8d80-f13202143ea2.png)
5. The expectation is to have two threads, or to have the information about whether the alert was triggered or solved in the body of the email

### Technical details:

* Redash Version: 0.9.2+b1536

**Comment by arikfr** [comment]
I think there is a way to pass some message id header to prevent grouping. Will look into it.

**Comment by tpatel** [comment]
I've given a quick look at the source, and I think that another quick fix would be to change the email subject define there: https://github.com/getredash/redash/blob/8b73a2b135aed8fcbca139380a959b9222ae0080/redash/destinations/email.py#L37 to be:
"{0} - {1}". What do you think about that ?

**Comment by arikfr** [comment]
I changed the default subject template not to use square brackets and also added the option to change the template in case it doesn't work for you.
