### ISSUE TITLE
Dashboard should surface error messages from queries

### ISSUE THREAD

**Issue by jeffwidman** [getredash/redash#1161]
When dashboard queries report an error, that error should be displayed on the associated database. 

This is particularly useful when using url parameters in dashboards that are passed to the underlying queries. It would have saved me an hour debugging this: https://discuss.redash.io/t/dashboard-not-updating-when-queries-include-url-parameters/96

**Comment by arikfr** [comment]
This was implemented in 0.11.

On Tuesday, 28 June 2016, Jeff Widman <notifications@github.com> wrote:

> When dashboard queries report an error, that error should be displayed on
> the associated database.
>
> This is particularly useful when using url parameters in dashboards that
> are passed to the underlying queries. It would have saved me an hour
> debugging this:
> https://discuss.redash.io/t/dashboard-not-updating-when-queries-include-url-parameters/96
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/getredash/redash/issues/1161>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAEXLNfw9Q7QmWQBEVWVSY75MFuA_sSUks5qQYdagaJpZM4JAhAV>
> .
>


-- 
-- 
Arik Fraimovich

**Comment by arikfr** [comment]
Implemented in #1069.
