### ISSUE TITLE
Changing a parameter value in the UI causes an alert() when you haven't saved the query

### ISSUE THREAD

**Issue by tsibley** [getredash/redash#1174]
Open up a query's source and modify it.  If it doesn't have a parameter already, add one.  Without saving, modify the parameter's value in the input field.  The real-time location updating while typing into the parameter input field triggers the "If you leave this page you'll lose your changes" alert.  Save the query and then try typing in the parameter's input field.  It updates the location without triggering an `alert()`.

**Comment by arikfr** [comment]
I've tried to reproduce it here: http://demo.redash.io/queries/2081/source and couldn't. Are you running the latest version the `0.11` release?

If not, can you upgrade and see if you still experience this?
If you're running the latest, can you add more details on your browser/OS?

**Comment by tsibley** [comment]
Hmm, apologies for not including my version in the initial report.  I observed this running `v0.12.0-rc`.

**Comment by tsibley** [comment]
Browser is Chrome 51.0.2704.103, OS X.

**Comment by tsibley** [comment]
I can reproduce it on demo.redash.io.  Try this:

1. Create a new query
2. Enter `select '{{foo}}'` and save the query
3. Modify the query to `select '{{foo}}' || 'bar'`, but _don't_ save it
4. Type something in the parameter input for "foo"

If the query is completely new and never been saved, it doesn't happen for me.

**Comment by arikfr** [comment]
Ok, now I see what's going on. :-(
