### ISSUE TITLE
Is it possible to label pie charts after grouping?

### ISSUE THREAD

**Issue by fredthedead** [getredash/redash#1180]
After grouping the data based on a column and having 2 pie charts side by side there is no labeling on top of each pie chart saying to which group value is matches... I didn't notice a way to enable this - is it possible?

**Comment by arikfr** [comment]
Can you create an example on demo.redash.io (login with any Google account) or at least attach a screenshot?

**Comment by fredthedead** [comment]
![screen_shot_2016-07-14_at_5_54_19_pm](https://cloud.githubusercontent.com/assets/19219041/16832455/a69e7d46-49ed-11e6-8e8d-81f2fee36c97.png)

(Sorry had to blur labels)

![screen_shot_2016-07-14_at_5_55_03_pm](https://cloud.githubusercontent.com/assets/19219041/16832440/96322fde-49ed-11e6-8b49-90a0450ce6e3.png)

**Comment by dpreuss** [comment]
Any update on this issue? I appear to have run into the same problem...

**Comment by arikfr** [comment]
Implemented in #2082.
