### ISSUE TITLE
Dashboard refresh not working

### ISSUE THREAD

**Issue by loskultos** [getredash/redash#1184]
### Issue Summary

The dashboard auto refresh of the widgets doesn't work (a complete browser refresh is needed). The refresh functionality is enabled.

Redash Version: 0.10.1+b1836
Browser/OS: Mac OS X both Safari and Chrome
Vagrant/VirtualBox Ubuntu Box 14.04 following these steps:
* Make sure you have a Docker machine up and running.
* Make sure your current working directory is the root of this GitHub repository.
* Run docker-compose up postgres.
* Run ./setup/docker/create_database.sh. This will access the postgres container and set up the database.
* Run docker-compose up

**Comment by arikfr** [comment]
What is the refresh interval you set to the queries on this dashboard?

**Comment by loskultos** [comment]
At the moment I only have one query and one visualization.
The query is scheduled for every minute: Refresh Schedule Every 1m

**Comment by arikfr** [comment]
Do you see any errors in browser console? How long did you wait for it to refresh? Does any of queries have parameters?

**Comment by arikfr** [comment]
Found the bug, will push a fix as part of the coming release.

**Comment by ellemayo** [comment]
Is there a commit for this fix? 

I've had the same problem and would love to get the fix integrated into my copy as soon as possible...
