### ISSUE TITLE
Does it seem to be possible to execute DDLs in Re:dash metadata?

### ISSUE THREAD

**Issue by kitsuyui** [getredash/redash#1189]
### Issue Summary

It seems to be possible to create / delete tables in Re:dash metadata.

### Steps to Reproduce

1. Open "New Query"
2. Write create/drop SQL

![create table](https://cloud.githubusercontent.com/assets/2596972/16871597/c87574c6-4ac2-11e6-8cf9-29015269f38f.png)

#### It was created!
<img width="358" alt="it is created" src="https://cloud.githubusercontent.com/assets/2596972/16871610/d698631a-4ac2-11e6-894d-15866cad6c2b.png">

#### And also ...

deletable.

<img width="660" alt="drop" src="https://cloud.githubusercontent.com/assets/2596972/16871642/08c2f404-4ac3-11e6-9016-8b47a5e2a3c9.png">

Is it safe?
I think that non-administrator users also can do this.

`DROP TABLE dashboards`, `DROP TABLE queries` ...

### Technical details:

* Redash Version: v0.10.1.b1834, 0.11.0 - RC
* Browser/OS: Google Chrome / OSX / Server: Ubuntu Linux 16.04 LTS
* How did you install Redash: used setup/ubuntu/bootstrap.sh

**Comment by arikfr** [comment]
It's good to remember that Redash allows whatever you allow the database user you supply it with.

In this case the `redash_reader` user can create new tables and delete tables it created, but it can't touch (delete) the metadata tables. That's apparently the default behavior in Postgres.

I don't mind changing the bootstrap script to prevent this though by basically adding the following:

```
revoke create on schema public from public;
grant create on schema public to redash;
```

**Comment by kitsuyui** [comment]
@arikfr Oh! I see.
I'm relieved to hear that.

> In this case the redash_reader user can create new tables and delete tables it created, but it can't touch (delete) the metadata tables. That's apparently the default behavior in Postgres.
