### ISSUE TITLE
Shared dashboard crashes if one of the queries has no results yet

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#1194]
When loading a shared dashboard, if one of the queries doesn't have results yet, the dashboard won't load.

**Comment by NicWagenaar** [comment]
Having the same issue, this is the error message:
`QueryResultDoesNotExist: Instance matching query does not exist:`
`SQL: SELECT "t1"."id", "t1"."org_id", "t1"."data_source_id", "t1"."query_hash", "t1"."query", "t1"."data", "t1"."runtime
", "t1"."retrieved_at" FROM "query_results" AS t1 WHERE ("t1"."id" IS %s)`

**Comment by lab79** [comment]
Empirically noticed the error when the name of dashboard contains ".", " ", etc.
