### ISSUE TITLE
Bug: Duplicated Query

### ISSUE THREAD

**Issue by ngrygs** [getredash/redash#1196]
I just noticed that I have a query which has 2 duplicates (3 total identical queries) all of which have a creation timestamp of the exact same time. I'm not sure what exactly caused it, as they were created a month ago, but I only just noticed the duplicates.

I'm using version 0.10.0+b1774, and the query would have been created on chrome.

**Comment by arikfr** [comment]
I couldn't reproduce this one. Feel free to reopen if you have more details. 👍
