### ISSUE TITLE
using function in redash

### ISSUE THREAD

**Issue by WutStudent** [getredash/redash#1202]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by WutStudent** [comment]
How can I acces function created in pgadmin in re:dash?
I have created function and it is visible in database tree in pgadmin, but I don't know how to ues it in re:dash.

**Comment by arikfr** [comment]
Please use the [support forum](https://discuss.redash.io/c/support) for usage questions.
