### ISSUE TITLE
Add description to embed

### ISSUE THREAD

**Issue by LeonidSergeev** [getredash/redash#1208]
### Issue Summary

It would be quite convenient to add description row in embed (currently I see only query title)

* Redash Version: 0.12.0+b2033
* Browser/OS: Google Chrome 51.0.2704.103 m

**Comment by arikfr** [comment]
We try to keep the issue tracker for actionable issues only. This is why we ask to use [the forum](discuss.redash.io) for feature requests like this one. I'm closing this issue, but you're welcome to start a thread and we will continue the discussion over there.

Thanks.
