### ISSUE TITLE
Re:Dash Upgrade Issue(column t1.org_id does not exist)

### ISSUE THREAD

**Issue by myungK** [getredash/redash#1210]
### Issue Summary
i found some issue when i upgrade my re:dash service.(0.6.1.b857 → 0.11.0.b2016)
when i try to upgrade using Fabric script.

[Page Error Info]
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

[API ERROR Log Info]
Requested: sudo sudo -u redash PYTHONPATH=. bin/run python migrations/0009_add_api_key_to_user.py
Executed: /bin/bash -l -c "cd /opt/redash/redash.0.11.0.b2016 >/dev/null && sudo sudo -u redash PYTHONPATH=. bin/run python migrations/0009_add_api_key_to_user.py"

### Technical details:

* Redash Version: 0.6.1.b857 → 0.11.0.b2016
* Browser/OS:    Chrome / Ubuntu 14.04.4 LTS
* How did you install Redash: Using AMI and Upgrade by  Fabric script

**Comment by arikfr** [comment]
It's not clear from the details above if the migrations run successfully during the upgrade? Considering the old version you were using, it probably didn't :-\ You need to review your upgrade run log to see where it stopped and continue manually.

I'm closing this issue, as it's not an issue with Redash itself, but you're welcome to continue the discussion. Also in the future please use the [Support Forum](https://discuss.redash.io/c/support) for questions like this one.
