### ISSUE TITLE
Quotation Mark is Not Replaced Correctly When Inserted Using Query Parameters

### ISSUE THREAD

**Issue by yotammanor** [getredash/redash#1211]
### Issue Summary

For some reason, when a string is introduced through a parameter, it does not replace a single quotation mark ("'". Not to be confused with "`", which works well).
### Steps to Reproduce
1. (select replace(replace('ג''מאל זחאלקה','''',''),'`','') from_db, replace(replace('{{name}}','''',''),'`','') from_parameter)
2. /query/5/?p_name=ג'מאל זחאלקה
3. the results will show that the "from_db" quotation mark was removed, while the "from_parameter" was not.
### Technical details:
- Redash Version: Re:dash 0.10.1+b1836
- Browser/OS:
  {
  "ua": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "51.0.2704.103",
    "major": "51"
  },
  "engine": {
    "version": "537.36",
    "name": "WebKit"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
  }
- How did you install Redash: I did not do it myself, so I'm not sure.

**Comment by arikfr** [comment]
The quote sign is being replaced by a HTML escaping code, hence the replace doesn't work. If you change the param to be `{{{name}}}` it will not do the HTML escaping, but then you will need to manually escape the quote for PostgreSQL... We should handle better by using the database's query parameter support. The current solution was easy as it worked for any database but these issues are a major down side.

**Comment by yotammanor** [comment]
Cool, I'll try that :)

Thanks!
