### ISSUE TITLE
Email notification not working

### ISSUE THREAD

**Issue by danielerapati** [getredash/redash#1212]
Hi Arik,

thank you for re:dash, it is really amazing.

### Issue Summary

Redash 0.11.0+b1995 (and similar versions including 0.12RC I guess)

### Steps to Reproduce

1. Set an alert on a query that will trigger
2. Register to the alert with your user (email)
3. Refresh the query

### Technical details:

From the logs I get 
`celery_error.log:[2016-06-26 13:30:46,312: WARNING/Worker-11] redash.tasks.check_alerts_for_query[5bb71f82-ec70-4893-bb12-5d665f7f9a05]: Exception: 'str' object has no attribute 'get'`

I'm not really sure (*) but I think it is bubbling up in [redash/tasks/alerts.py:43](https://github.com/getredash/redash/blob/master/redash/tasks/alerts.py#L43)
from [redash/destinations/email.py:27](https://github.com/getredash/redash/blob/8b73a2b135aed8fcbca139380a959b9222ae0080/redash/destinations/email.py#L27)

(*) ConfigurationContainer may be doing something more than merely passing the dict along but I'm not sure ...

The root cause may be in [redash/models.py:1192](https://github.com/getredash/redash/blob/master/redash/models.py#L1192)
where it could be solved by:
`config = {'addresses': self.user.email}`

Hopefully this evening I will have a pull request.

**Comment by arikfr** [comment]
You analyzed it correctly and I will push the fix later today myself (already have the fix, just didn't have the chance to make a pull request).
