### ISSUE TITLE
Error when running mongodb query

### ISSUE THREAD

**Issue by ichkautzar** [getredash/redash#1228]
My query executed perfectly using Robomongo 
Redash gave me error message : 
"Error running query: Invalid query format. The query is not a valid JSON."

I am using Ubuntu 16.04, Google Chrome.

**Comment by arikfr** [comment]
Looks like you didn't structure your query as a valid JSON. Please refer to the [documentation](http://docs.redash.io/en/latest/usage/mongodb_querying.html) to see how valid queries should look like.

Also please follow the instructions, and use the [forum](https://discuss.redash.io/c/support) for further support questions.

**Comment by ichkautzar** [comment]
I didn't that I have to use pyMongo format. Thanks before @arikfr
