### ISSUE TITLE
Support for Netezza(IBM Pure Data Analytics)

### ISSUE THREAD

**Issue by ashishbahuguna** [getredash/redash#1235]
Welcome to Redash's GitHub repo! 👋🎉

Hi Team,

Can you please confirm if the Re:Dash can be used to make connection to Netezza system?
Do you have any configuration to connect via ODBC or JDBC driver?

**Comment by ashishbahuguna** [comment]
Hi Team,

Can you please confirm if we can tweak it to support IBM Netezza? Or if we can connect via JDBC url or ODBC url?

**Comment by arikfr** [comment]
Redash does not have any "generic" ODBC/JDBC connectors. It should be possible to create a query runner (connector) for IBM Netezza if it has some Python driver.

**Comment by ashishbahuguna** [comment]
Thank You!!
