### ISSUE TITLE
Download Dataset does not work when not logged in

### ISSUE THREAD

**Issue by yairwein** [getredash/redash#1247]
### Issue Summary

Using a query public URL, trying to download the dataset as a CSV when not logged in fails
### Steps to Reproduce
1. Create a query that returns a table
2. Create a public link using "embed" (use the src argument)
3. Open the link from an **anonymous** browser window
4. Click Download Dataset CSV

Getting 
![image](https://cloud.githubusercontent.com/assets/106487/17824986/fee1e108-6619-11e6-9f55-4e3c99a8f633.png)
### Technical details:
- Redash Version:  0.11.1+b2095
- Browser/OS: Chrome / Mac

**Comment by lukas-wu** [comment]
Issue replicable also on:
Technical details:

Redash Version: 0.11.0+b2016
Browser/OS: Chrome / Windows 10

**Comment by phpcodecrafting** [comment]
It also fails for Excel. Looks to me like the issue is that the download links do not contains the `api_key`. If you add the `api_key` to the download links, they then work. Hopefully that's not too difficult to fix in the code.
