### ISSUE TITLE
Option for Bar/line chart to always show labels

### ISSUE THREAD

**Issue by shahneil88** [getredash/redash#1254]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.
Currently on redash, when we create a bar/line chart, there is no option to always display Y axis labels.
### Steps to Reproduce
1. Create a bar chart or a line chart
2. Hover over to the chart to see values of Y axis.

You will always need to hover over on the chart to see the values.
There should be an option where we do not need to hover over chart to see the values.

I found a example on plot.ly to implement this.
https://plot.ly/python/bar-charts/ . Check "Styled Bar Chart with Direct Labels" section for bar chart

For Line chart, I was not able to find the exact solution. Closest what we have is
https://plot.ly/python/line-charts/ . Check "Label Lines with Annotations" section for line chart.

There should  be an option, like a "checkbox", where you can enable /disable display of labels, because not everybody would want to display labels all the time.

**Comment by arikfr** [comment]
Resolved in #2156 (part of the v4 release).
