### ISSUE TITLE
Issues when upgrading to Python 2.7.12 as per 16.04.1 LTS (Xenial Xerus)

### ISSUE THREAD

**Issue by pcolazurdo** [getredash/redash#1258]
### Issue Summary

After installing latest release to Debian I've found issues with the following libraries
* requests (error was AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3')
* kombu (ImportError: cannot import name _uuid_generate_random )

Solution was to run:
* sudo pip install -U requests
* sudo pip install -U kombu

Please note that running an upgrade based on fab fails as requirements.txt are pointing to old library versions.

reDash version is: redash.0.11.1.b2095

### Steps to Reproduce

Upgrade debian box to latest version

### Technical details:

* Redash Version: redash.0.11.1.b2095
* OS: 16.04.1 LTS (Xenial Xerus)
* How did you install Redash: Amzn AMI upgraded to latest Debian and reDash updated via fab.py

**Comment by arikfr** [comment]
I want to upgrade all our dependencies to their latest version, but need to find the time to test side effects. 

Did you encounter any issues so far with these versions of Kombu/requests?

**Comment by pcolazurdo** [comment]
I haven't found any issue so far.
