### ISSUE TITLE
Celery config - set `CELERY_ACCEPT_CONTENT`

### ISSUE THREAD

**Issue by glarrain** [getredash/redash#1260]
### Issue Summary

For a security improvement plus avoiding unnecessary warnings and be prepared for Celery 3.2, `CELERY_ACCEPT_CONTENT` should be specified.

In `celery_error.log`:

```
[2016-08-26 17:55:39,927: WARNING/MainProcess] /usr/local/lib/python2.7/dist-packages/celery/apps/worker.py:161: CDeprecationWarning: 
Starting from version 3.2 Celery will refuse to accept pickle by default.

The pickle serializer is a security concern as it may give attackers
the ability to execute any command.  It's important to secure
your broker from unauthorized access when using pickle, so we think
that enabling pickle should require a deliberate action and not be
the default choice.

If you depend on pickle then you should set a setting to disable this
warning and to be sure that everything will continue working
when you upgrade to Celery 3.2::

    CELERY_ACCEPT_CONTENT = ['pickle', 'json', 'msgpack', 'yaml']

You must only enable the serializers that you will actually use.
```

Resources:
- http://docs.celeryproject.org/en/latest/configuration.html#std:setting-CELERY_ACCEPT_CONTENT
- http://docs.celeryproject.org/en/latest/userguide/security.html#serializers
### Steps to Reproduce

Inspect file `/opt/redash/logs/celery_error.log`
### Technical details:
- Redash Version: [commit 7598048](https://github.com/getredash/redash/commit/7598048)
- Browser/OS: Chrome/Ubuntu desktop 14.04 (irrelevant)
- How did you install Redash: vanilla AWS EC2 instance using AMI ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20160627 (ami-2d39803a)
- Celery: 3.1.11 (according to `redash/requirements.txt`)

**Comment by arikfr** [comment]
We no longer use Celery...
