### ISSUE TITLE
Unusual behaviour in schema browser

### ISSUE THREAD

**Issue by rohanpd** [getredash/redash#1261]
### Issue Summary

When expanding a table in the schema browser and scrolling to the bottom of the table the schema browser resets to the top.

### Steps to Reproduce

1. Identify a table with many columns
2. Expand the table and witness odd behaviour when scrolling to the bottom of the table columns
![schemabrowser](https://cloud.githubusercontent.com/assets/7199904/18049777/a1b9ba16-6e2d-11e6-96f6-98505c94f52e.gif)

NOTE: I can reproduce this on my instance and on demo.redash.io

### Technical details:

* Redash Version: 0.12.0+b2163
* Browser/OS: Chrome/Mac OS
* How did you install Redash: Amazon AMI

**Comment by arikfr** [comment]
Probably related to #1246.
