### ISSUE TITLE
Modifying the schedule for a new query breaks the schedule modal

### ISSUE THREAD

**Issue by d-ray** [getredash/redash#1263]
### Issue Summary

Saving a new query by modifying its refresh schedule breaks the javascript handlers on the schedule form modal.

### Steps to Reproduce

1. Open a new query.  Don't save it.
2. Open the refresh schedule modal and make a change (thus causing the query to be saved for the first time).
3. Observe that all of the javascript handlers on the modal no longer work: additional updates do not trigger saves, both radio buttons can be selected simultaneously, and clicking the 'X' in the top right does not close the modal (however, clicking outside of the modal will close it).

### Technical details:

Observed on demo.redash.io in Chrome and on an EC2 instance using the latest AMI (v0.11.1) in Chrome, Safari, and Firefox.  Using OSX 10.11.4.

**Comment by arikfr** [comment]
Thank you for reporting.
