### ISSUE TITLE
Password Authentication Failed

### ISSUE THREAD

**Issue by sks-369** [getredash/redash#1266]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary
I am getting the below error while building pkg

[ERROR/MainProcess] Task redash.tasks.refresh_queries raised unexpected: ProgrammingError('FATAL', 'xxxxx', 'password authentication failed for user "redash"', 'auth.c', 'xxx', 'auth_failed', u'', u'')

But the user name i configured is redash_reader not sure where this user"redash" coming from? how to fix this? 

Thanks.

**Comment by arikfr** [comment]
Maybe it's a failure of Redash itself to connect to its own DB? In the default setup we don't use password authentication though. Is there a stack trace?

Anyway, in the issue template, if you notice the instructions, we ask to file support question in the forum: https://discuss.redash.io/c/support. So let's continue the conversation there.
