### ISSUE TITLE
Feature Request: Add support to change the application root

### ISSUE THREAD

**Issue by evilNullPointer** [getredash/redash#1278]
We are using Apache as a reverse proxy for several docker containers. Currently, we cannot change the application root of our Redash instance to be serve from a prefixed url (/web). All requests always refer to /. The Flask **APPLICATION_ROOT** or the **url_prefix** of the blueprint cannot be updated from the settings.py (docker env var in our case).

### Our setup
https://metrics.mycompany.com/api
https://metrics.mycompany.com/web   => ProxyPass to the redash container

### Technical details
Redash Version: 0.11.1
Browser/OS: Chrome
How did you install Redash: docker

**Comment by arikfr** [comment]
I don't mind exposing `APPLICATION_ROOT` via `settings.py`, although I'm not sure if that's all it takes to make this work. We have a few places where we create URLs (like the alerts), that might need to be updated too.

Also see [this discussion](https://discuss.redash.io/t/hosting-redash-not-under-root/135/5).

You're welcome to make a pull request to expose this setting, but I'm closing this issue as there is nothing actionable "for the project".

**Comment by BeezyT** [comment]
We had the same requirement and implemented the requested feature.
What has to be done is:

* Set the Flask APPLICATION_ROOT
* Set base href in all templates
* Make all URLs in the frontend relative (e.g. api/session instead of /api/session)
* Forward the original request URL through the proxy and use it to generate the next parameter for the login page

Our solution consists of the changes above, a new setting REDASH_PROXY_PUBLIC_BASE_HREF and a sample nginx config.

We're still based on version 1.0.3. If you're interested in the pull request @arikfr, I'll port it to the current master and send it via GitHub. Are you interested? And would you expect major problems, i.e., were there big structural changes since 1.0.3.?

**Comment by phillipjohnson** [comment]
@BeezyT Just curious if you're still happy with your solution or if you had to make changes with new updates? We're currently experimenting with Redash 5 and are going down the path of doing a lot of rewrites in the reverse proxy to fix the URLs.

@arikfr Has there been any movement on getting Redash to work behind a reverse proxy?

**Comment by arikfr** [comment]
@BeezyT I missed your offer the previous time you offered it, and I have to admit that I'm a bit reluctant to merge something like this into the codebase. The usefulness of it to the general population of Redash users is very limited, while the maintenance burden can be significant.

Are your changes public so I can see what's actually involved in making this work?

Also would love to hear why you and @phillipjohnson need this?

**Comment by phillipjohnson** [comment]
@arikfr In our environment we have several web applications running inside of docker containers on one host. We have an nginx instance that sits in front of those containers so we can provide user-friendly URLs such as `https://company.com/app1`, `https://company.com/app2`, etc. We then reverse proxy those URLs to `http://docker-container-1:5000`, `http://docker-container-2:8080`, etc.

We're exploring adding redash to our offering of tools, but without the ability to easily reverse proxy, we might have to go down the path of subdomains. (Using nginx's `sub_filter` gets close, but it is not perfect.)

**Comment by cosmocracy** [comment]
@BeezyT I'm curious about your statement questioning the usefulness of having an option besides giving Redash an entire HTTP server instance for itself.  There are many many organizations that tuck more than one app onto a server/hostname and it's rare to find a serious application--which Redash is, thank you it's awesome!--that doesn't play nice with setting the base URL.

Also means users need to purchase an additional SSL certificate for the dedicate Redash HTTP server...

**Comment by cosmocracy** [comment]
@BeezyT I'm also not sure what additional maintenance burden there is.  Leveraging Angular's router properly makes this a breeze, right?  No additional Javascript but more just using the built-in ability to not assume a top-level URI-space.  There would be some tweaks to the HTML/template but I think you'd find volunteers (including us) to help with that boilerplate refactoring if you'd like.

**Comment by arikfr** [comment]
@phillipjohnson ,

> We're exploring adding redash to our offering of tools, but without the ability to easily reverse proxy, we might have to go down the path of subdomains. (Using nginx's sub_filter gets close, but it is not perfect.)

Reverse proxying with subdomains is as easy as reverse proxying with subfolders. You can have multiple site defined in nginx (`server` blocks), just make sure to set the correct `server_name` for each one and set one of them as the default (probably the one that already serves all your current apps). Then nginx will direct the traffic to the correct one.

**Comment by arikfr** [comment]
@cosmocracy I'm assuming your questions were directed to me and not @BeezyT.

> I'm curious about your statement questioning the usefulness of having an option besides giving Redash an entire HTTP server instance for itself.

I'm making this statement based on the low number of requests for this feature.

> There are many many organizations that tuck more than one app onto a server/hostname and it's rare to find a serious application--which Redash is, thank you it's awesome!--that doesn't play nice with setting the base URL.

Requiring its own (sub)domain doesn't block you from reusing the same server (see my comment above).

> Also means users need to purchase an additional SSL certificate for the dedicate Redash HTTP server...

When using LetsEncrypt this becomes a non issue.

> I'm also not sure what additional maintenance burden there is. Leveraging Angular's router properly makes this a breeze, right? 

We're actually moving away from Angular (#3071). But this change has effect not only in the frontend, but also in the backend in how we generate URLs. Maybe there are other implications. Fact is that this is something we will have to test in every release and make sure that we don't break.

And if we mention the React migration, if we were supporting this already we had to research on how to implement this with React Router.

> I think you'd find volunteers (including us) to help with that boilerplate refactoring if you'd like.

I appreciate the good will, but it's not a one time effort. Anything that goes into the codebase is something that we make a commitment to support and maintain.

**Comment by cosmocracy** [comment]
(Sorry, @arikfr my goof, yes those were meant for you)

**Comment by mleonardom** [comment]
> @phillipjohnson ,
> 
> > We're exploring adding redash to our offering of tools, but without the ability to easily reverse proxy, we might have to go down the path of subdomains. (Using nginx's sub_filter gets close, but it is not perfect.)
> 
> Reverse proxying with subdomains is as easy as reverse proxying with subfolders. You can have multiple site defined in nginx (`server` blocks), just make sure to set the correct `server_name` for each one and set one of them as the default (probably the one that already serves all your current apps). Then nginx will direct the traffic to the correct one.

But what about the AWS Application Load Balancers or an external reverse proxy based on URL prefixes? If you can't change the redash root you must change your current reverse proxy or your Load Balancer or put an entire host, just to make it works with redash.
