### ISSUE TITLE
User without execute_query permission can't refresh dashboard widgets

### ISSUE THREAD

**Issue by yanenok** [getredash/redash#1286]
### Issue Summary

When a user who doesn't have an execute_query permission presses the refresh button on a widget, widget shows an update spinner but returns 403, causing the spinner to show infinitely (or until page update).  

It is also not possible to refresh a widget with execute_query permission and read_only access to the data source - similar to and for the same reasons as in [Issue #1163](https://github.com/getredash/redash/issues/1163).
### Steps to Reproduce
1. Create a test user with no 'execute_query' permission. 
2. Log in as that user.
3. Open any dashboard with a widget on it.
4. Click refresh button on a widget.
### Technical details:
- Redash Version: v.0.11.1.b2095
- Browser/OS: Chrome/OS X
- How did you install Redash: provisioning script + fabric update

**Comment by arikfr** [comment]
> It is also not possible to refresh a widget with execute_query permission and read_only access to the data source - similar to and for the same reasons as in Issue #1163.

Actually this should be possible. Are you referring to widgets with parameters or any widget?

**Comment by yanenok** [comment]
Any widget. I believe it is due to the 'execute_query' permission required when getting QueryResultListResource with post request.

**Comment by yanenok** [comment]
Sorry about closing and reopening - must have misclicked at some point.

**Comment by arikfr** [comment]
We've started a project to redo permissions in Redash, which will also address this use case. To follow along you can watch #3284.
