### ISSUE TITLE
Schema not refreshing in browser

### ISSUE THREAD

**Issue by esquire900** [getredash/redash#1287]
We are experiencing similar problems as issue [#880](https://github.com/getredash/redash/issues/880), where the tables from a Redshift database are not updated in the browser (on the left when creating a table).

Tables are definitely accessible by the user, redash just doesn't show them (it looks like a refresh hasn't been run in weeks). Perhaps any suggestions on how to fix this? :)

**Comment by arikfr** [comment]
What version of Redash do you have?

**Comment by esquire900** [comment]
0.11.1+b2095 

Manually trying to invoke redash.tasks.refresh_schemas doesn't appear to work either.

**Comment by ChrisLocus** [comment]
We have this issue sporadically and we are on version `.10`.  It seemed to have went away after  manually executing the query below (directly - not in Redash). It makes no sense to me but I wanted to share what we saw/ did w/ you. Maybe that will lead you in the right direction.

Excerpt from our GitHub issue:


> I found the query thats causing it. Taken from https://github.com/getredash/redash/blob/master/redash/query_runner/pg.py line 91
> 
>         SELECT table_schema, table_name, column_name
>         FROM information_schema.columns
>         WHERE table_schema NOT IN ('pg_catalog', 'information_schema');
> I ran this query against Redshift and the very 1st time I got the "Relation with OID.." error. Then the next 10 times it ran fine. So this is something wonky with the information_schema system tables on Redshift and it does not happen all the time.
> 
> We are going to live w/ this one. The only effect is that the schema info (tables, columns list in UI) will sometimes be stale. It does not fail everytime so it does get updated.

**Comment by esquire900** [comment]
Thank you for your suggestion @ChrisLocus.

I however suspect the problem to be in redash: we've made several groups with seperate redshift connections (as each connection has different permissions). On for instance the admin account with the administrator connection the tables do refresh, though not some of the other accounts (some strangely do, some dont).

**Comment by ChrisLocus** [comment]
We have 3 redshift users we would connect to the datasource with and 2 out of 3 had the issue. Like I said, I reproduced the query failure with redash out of the picture. So seems like  that's a redshift issue to me. Good luck.

**Comment by esquire900** [comment]
Ah excuse me, I misunderstood your comment. That indeed seem to do the trick, thank you very much for your help!

**Comment by ChrisLocus** [comment]
😃did executing it manually fix it for you?

**Comment by arvind-iflix** [comment]
What is the solution , facing same issue on redash

**Comment by nasmithan** [comment]
I was able to fix this issue by making the following edit. I suggest everyone else having issues play with this query as well. You can test it by running it in Presto until you get a good output. Only downside is you don't get specific column names.

If you also need MySQL information schema, just union it with this query making sure it has the same 3 columns.

redash/query_runner/presto.py
`
query = """
        SELECT table_schema, table_name, '' as column_name
        FROM information_schema.tables
        WHERE table_schema NOT IN ('pg_catalog', 'information_schema')
        """
`
(pull from information_schema.tables instead of information_schema.columns)
