### ISSUE TITLE
Add certifi package to requirements to support MongoDB SSL connections

### ISSUE THREAD

**Issue by sathishc** [getredash/redash#1288]
More of a feature request than an issue.

### Issue Summary

We recently migrated from and Mlab hosted MongoDB to MongoDB Atlas. Atlas requires connection to pass through ssl and requires ability to provide CA or self signed certificates. This is not provided by Redash today.

We are now unable to use Redash since there is no way now to connect to our prouction.

**Comment by arikfr** [comment]
You need to install the [certifi](https://pypi.python.org/pypi/certifi) Python package and use the [`ssl`](https://docs.mongodb.com/manual/reference/connection-string/#connection-options) connection option in your connection string.

I'm keeping this issue open until we add `certifi` to requirements.txt.

**Comment by arikfr** [comment]
Implemented in #1314 .

**Comment by mderazon** [comment]
I'm trying to connect with ssl
> mongodb://user:pass@some.address.com:port,some.address.com:port/dbname**?ssl=true**

And getting:
![screen shot 2016-10-24 at 15 05 10](https://cloud.githubusercontent.com/assets/717076/19645234/6bf77116-99fc-11e6-8f2e-706bd672c8c2.png)

I'm running mongodb on GCP via Compose.io

**Comment by arikfr** [comment]
What version of Redash do you run?

**Comment by mderazon** [comment]
@arikfr wrote here before our correspondence and this: #1361

**Comment by arikfr** [comment]
👍 yeah, once you reached out on Intercom I figured out it was you.
