### ISSUE TITLE
Ability to force a refresh before fetching results

### ISSUE THREAD

**Issue by sreynen** [getredash/redash#1293]
### Issue Summary

I'd like to use the API, outside the context of an active login session, to get the latest results of a given query, in fewer than 3 HTTP requests. Currently I can call /refresh with API key to trigger a refresh of results, then repeatedly call /jobs/<jobid> until the job is done, and when the refresh job is done, I can call /results.json with API key to get those results. That's at least 3 HTTP requests, potentially many more.

Some potential solutions:

A) Make results.json take an optional parameter to trigger a refresh and not return results until the refresh job is complete.
B) Make /refresh take an option parameter to not return a response until refresh job is complete.
C) Make /refresh take a callback URL, which get's pinged when the job is done.
### Issue Summary

I'd like to use the API, outside the context of an active login session, to get the latest results of a given query. Currently I can call /refresh with API key to trigger a refresh of results, and when the refresh job is done, I can call /results.json with API key to get those results. The problem is I don't know when the job is done.

Some potential solutions:

A) Make results.json take an optional parameter to trigger a refresh and not return results until the refresh job is complete.
B) Make /refresh take an option parameter to not return a response until refresh job is complete.
C) Make /jobs/<jobid> callable via API key, or maybe even without auth at all, since it doesn't really reveal much information unless you already know what the job is.

I prefer A, since it would mean the fewest API calls to get fresh results.
### Steps to Reproduce
1. Write a query that takes a few seconds to complete.
2. Call /refresh on that query.
3. Immediately call /results.json on that query.
4. Note that you aren't getting the latest results.
### Technical details:
- Redash Version: 0.11.1+b2095

**Comment by ChrisLocus** [comment]
Jobs are callable via api. You have to use the admin api key.

**Comment by arikfr** [comment]
As @ChrisLocus mentioned `/jobs` is callable via the API. You need a user API key (any user, not necessarily an admin). You can see an example here: https://gist.github.com/arikfr/9e93251a18ff7de649faf50bfaca8944

As for the other suggestions, I agree that being able to call `/refresh` and wait for response is the friendliest API, it's not something we can do with current setup as it will block the web server. While usually you would have >1 processes for the web server, it's still easy to choke the server this way.

Once we switch to a non blocking web server, we can revisit this.

**Comment by sreynen** [comment]
Thanks for the info. I updated the request to ask for a better way to do this, but great to have even a non-ideal way to do it.

**Comment by arikfr** [comment]
Thank you for opening this and providing the details. The needed functionality is better explained in #2825 . Closing this one now.
