### ISSUE TITLE
Cant choose table as visualization

### ISSUE THREAD

**Issue by delapecci** [getredash/redash#1296]
Hi, guys

I setup Redash 0.11.1+b2095 in **docker**, just according to the installation guide of [http://docs.redash.io/en/latest/setup.html#docker-compose](http://docs.redash.io/en/latest/setup.html#docker-compose), everything got done successfully.

Then I created some queries,  fetched the results and made some charts successfully;
but when I wanted to add the result table onto the dashboard, I found it is impossible to choose table as visualization

![a](https://cloud.githubusercontent.com/assets/2783025/18817344/9759615c-8390-11e6-9405-a88b093a47f6.jpg)

I appreciate any help for that! Thanks

**Comment by arikfr** [comment]
The table visualization is created by default for every new query. Can you check if you see any errors in the browser console or in the server logs when saving a query?

**Comment by delapecci** [comment]
@arikfr Thanks for you response. I try re-run the query and got error log in the browser console, pls check the attached capture
![snip20160926_1](https://cloud.githubusercontent.com/assets/2783025/18821357/e3c6da96-83d7-11e6-8e34-4984386e7669.png)

**Comment by delapecci** [comment]
@arikfr sorry, I know why I got such problem, because I import the queries data from another Redash instance without copying the visualization datas.
