### ISSUE TITLE
[Feature Request] Rolling Averages

### ISSUE THREAD

**Issue by janurag** [getredash/redash#1320]
Optionally see rolling average of data for last n days in graphs having datetime on x axis

**Comment by arikfr** [comment]
As with the other feature -- showing an average based on average value per day might not be the right thing for every scenario. It's usually impossible to calculate a rolling average without the raw numbers.

(as with the other one - closing, but you're welcome to continue the discussion)

**Comment by janurag** [comment]
@arikfr I want don't want this thing always but i should have the option to do it. Like i can have it while creating graphs.
