### ISSUE TITLE
[Feature Request] Percentages in line graph

### ISSUE THREAD

**Issue by janurag** [getredash/redash#1321]
![github_redash](https://cloud.githubusercontent.com/assets/8142234/19150927/61fb484a-8be7-11e6-858e-cee6df77b962.jpg)

Please refer the screen shot.

**Comment by arikfr** [comment]
When opening a feature request, unless it's really obvious, please provide more details. For example, percentage of what?

I would assume that the percentages will be of the total, but then your example doesn't make sense (as it amounts to >100%).

**Comment by janurag** [comment]
@arikfr basically in the graph the biggest item is the  Total, so it will be 100%, calculation for other values are done based on the biggest value.
I'll give the scenario:
Let just say i want some delivery Kpi's for that i am looking into graph where i have a line graph with total order deliveries, out of slot orders deliveries, and Inside slot deliveries. Here if i have percentage of things than it will help me to make direct decisions. 

There are lot of scenarios like this.

**Comment by arikfr** [comment]
I think this logic is too specific. While it will cover many cases there will be others were it won't fit. For example: you might return only the different delivery KPIs without the total number of deliveries. In this case it will take the largest KPI and use it as baseline, which is wrong.

Here's a real example: http://demo.redash.io/queries/2768/source#3697
This query shows number of actions per action type. It doesn't have a total number of actions.

We do plan to support ability to customize the tooltip, so you might be able to use that to achieve what you want (see #728).

I'm closing this, but I don't mind continuing the discussion (and reopening) in case you think I missed something.
