### ISSUE TITLE
Problems with Vagrant

### ISSUE THREAD

**Issue by TonyStarkBy** [getredash/redash#1322]
After executing `./bin/vagrant_ctl.sh test`
I'm getting error: `ERROR: Failure: ImportError (No module named oauthlib.oauth1)`

I double check that OAuthLib is installed:
`vagrant@vagrant-ubuntu-trusty-64:/opt/redash/current$ sudo pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): Flask-OAuthLib==0.9.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6))`

Any ideas how to fix this?

**Comment by arikfr** [comment]
See #1290. For some reason on Vagrant it seems not to install oauthlib or install the wrong version of it.

**Comment by urig** [comment]
Running on Windows 10 via Git Bash, I'm getting a very similar error:
> ERROR: Failure: ImportError (No module named flask_sslify)

Is there any chance that this might be related to VirtualBox complaining about "guest additions" the first time I ran the `./bin/vagrant_ctl.sh test`? 

>Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'redash/dev' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'redash/dev'
    default: URL: https://atlas.hashicorp.com/redash/dev
==> default: Adding box 'redash/dev' (v0.1.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/redash/boxes/dev/versions/0.1.0/providers/virtualbox.box
    default: Progress: 100% (Rate: 427k/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'redash/dev' (v0.1.0) for 'virtualbox'!
==> default: Importing base box 'redash/dev'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'redash/dev' is up to date...
==> default: Setting the name of the VM: redash_default_1476389512684_97542
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 5000 (guest) => 9001 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default:
    default: Guest Additions Version: 4.3.10
    default: VirtualBox Version: 5.1
==> default: Mounting shared folders...
    default: /vagrant => C:/dev/urig/redash
    default: /opt/redash/current => C:/dev/urig/redash
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: /usr/bin/env:
==> default: bash
==> default: : No such file or directory
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by arikfr** [comment]
Opened #1480 to track the work on the dev guide. Keeping this one open until I'm done.

**Comment by arikfr** [comment]
The developer guide has been updated along with new documentation on how to use Docker for  easy setup of your dev environment (instead of Vagrant).

https://redash.io/help-onpremise/dev/guide.html

Thank you for all your feedback!
Your feedback on the new guide & flow is always welcomed.
