### ISSUE TITLE
date type parameters were calculated when it

### ISSUE THREAD

**Issue by idalin** [getredash/redash#1340]
### Issue Summary

Mysql query. when I tried to compare a datetime field with a date type parameter, it failed because the parameter was calculated.

### Steps to Reproduce

1. select a mysql datasource
2.   try this sql
`select date(datetime_field), {{start_date}},{{end_date}} from mytable `
3. set the start_date and end_date type to date.
4. set the start_date to 2016-10-06 and end_date to 2016-10-10
5. get the result like this:

> DATE(CREATETIME)	2016-10-06	2016-10-10
04/01/16	2,000	1,996

6. what i really want is 
`select count(0), date(datetime_field) from mytable where date(datetime_field) between {{start_date}} and {{end_date}} group by 2`
7. but i got nothing

### Technical details:

* Redash Version: Re:dash 0.11.1+b2095
* Browser/OS: chromium/archlinux
* How did you install Redash: docker

**Comment by arikfr** [comment]
You probably need to quote the parameters, i.e. '{{start_date}}'.

**Comment by idalin** [comment]
thank you. quote the parameters solved.
