### ISSUE TITLE
Cyrillic labels are overlapping the pie chart

### ISSUE THREAD

**Issue by D2112** [getredash/redash#1352]
### Issue Summary

When legend's labels are written in cyrillic they are overlapping the pie chart
### Steps to Reproduce
1. Create a query returning labels in cyrillic, for example:
   
   select 21223 as x, 'В рамках допустимого' as y
   union all
   select 11223 as x, 'Нет полной информации о ценах сотрудников' as y
2. Visualize it as a pie chart

![untitled](https://cloud.githubusercontent.com/assets/7814578/19472901/f7247556-954a-11e6-88e9-bcdd5e28b68e.jpg)
### Technical details:
- Redash Version: 0.11.1+b2095 (0.12.0+b2275 still has this problem)
- Browser/OS: Google Chrome 53
- How did you install Redash: Installed on Ubuntu 14.04 via the script

**Comment by arikfr** [comment]
Looks like it was fixed in one of the Plotly upgrades. See here for a demo: http://demo.redash.io/queries/5346/source#7903.
