### ISSUE TITLE
ability to define colors for pie charts

### ISSUE THREAD

**Issue by dncpax** [getredash/redash#1354]
Colors are given from a pallete and seems to respect order of records in table: 1st record=1st corlor, 2nd record=2nd color, etc.

Problem is when we want that CatA to have the same color in all graphics so it is easily identifiable across graphics. As it is now graphs where it is not the first record it will be given a arbitrary color by the system... sometimes it's blue sometimes it's red.

Ideally in all charts "CatA"/"CatB" would get the same color. We can start with giving the user the ability to change colors for the pie charts.

Discussion here: [https://discuss.redash.io/t/pie-chart-order-by-colors/237](https://discuss.redash.io/t/pie-chart-order-by-colors/237)

**Comment by fbassy** [comment]
Any news on that one ?

Would be great to present reports and visualization.

**Comment by arikfr** [comment]
Implemented in #2616.
