### ISSUE TITLE
Allow uploading SSL certificate to enable working with self signed certificate

### ISSUE THREAD

**Issue by mderazon** [getredash/redash#1361]
I use a service [Compose](http://compose.io/) as my mongodb host provider.

Currently, they are [self signing](https://www.compose.com/articles/connecting-to-the-new-mongodb-at-compose/) their SSL certificates.
After adding the `?ssl=true` param in the mongodb source connection string in Redash, I am getting the following error message in my queries:

> SSL handshake failed

![screen shot 2016-10-24 at 15 05 10](https://cloud.githubusercontent.com/assets/717076/19679615/2047effc-9aab-11e6-8d7c-f352e509e2e8.png)

It appears Redash mongo driver doesn't trust Compose's certificate (rightly so).
Mongodb allows you to connect to specify a `sslAllowInvalidCertificates` flag when connecting via shell but it's not an option when using a connection string.

Compose allows you to download their certificate public key.
It would be nice to add an option in Redash source creation screen to paste a certificate that will be used whenever connecting to that source.

**Comment by AntoineAugusti** [comment]
In the meantime, you can just add the self signed SSL certificate as a trusted one on your server by following this procedure: http://unix.stackexchange.com/questions/90450/adding-a-self-signed-certificate-to-the-trusted-list

**Comment by mderazon** [comment]
Thanks, @arikfr partially solved this for me. I have added `&ssl_cert_reqs=CERT_NONE` to the connection string to ignore the certificate and it's all working fine now.
