### ISSUE TITLE
Mongodb query error when aggregate with 'new Date()'

### ISSUE THREAD

**Issue by delapecci** [getredash/redash#1367]
Hi, 
we deploy redash latest version and try to query from our mongodb, the original script in mongo shell is : 
![image](https://cloud.githubusercontent.com/assets/2783025/19768553/85487ad0-9c8a-11e6-8bbd-3a842a47ed62.png)

but when we create query in redash, got error unfortunately:
![image](https://cloud.githubusercontent.com/assets/2783025/19768568/9c85e200-9c8a-11e6-8e53-5f99cb43c9b0.png)

Would you like determine whether our query format is right? or redash could not support such query?

**Comment by arikfr** [comment]
"new Date()" is just a string when passed via Redash. You need to use Extended JSON to pass in a string - either using the standard `$date` or our own extension - `$humanTime`. See the [docs](http://docs.redash.io/en/latest/usage/mongodb_querying.html#mongodb-extended-json-support) for more information.

**Comment by stableShip** [comment]
@arikfr $date not work, error:  valid json results in not a valid JSON error
issue: https://github.com/getredash/redash/issues/1923
