### ISSUE TITLE
Feature Request: Sorting on Multiple Columns

### ISSUE THREAD

**Issue by r-kells** [getredash/redash#1370]
Feature Request: Provide ability to sort on multiple columns. This makes it much easier to gain insight from tables with multiple numeric fields. 

Example here using datatables.js (shift click to multi sort)
http://codepen.io/anon/pen/NRbkzN

**Comment by tmozgach** [comment]
Hello, just want to be sure, do you need this feature in the following part of system, for example?
![2](https://cloud.githubusercontent.com/assets/26471428/24088187/c4d52e8a-0ce4-11e7-90e3-e533ad7c3dae.png)

**Comment by arikfr** [comment]
@tmozgach I think the original issue was about sorting query results.

**Comment by tmozgach** [comment]
Hello, I see. One question more, I am new with this system, if it is possible could you navigate me and tell which file is a major one and I can add js code there, which will influence on all table in the project? Thanks!

**Comment by arikfr** [comment]
Implemented in v4.
