### ISSUE TITLE
Heroku with custom DNS - max number of Redis clients reached

### ISSUE THREAD

**Issue by mika0x56** [getredash/redash#1372]
This only happens when using an alternative DNS on Heroku:

1. Follow steps on http://docs.redash.io/en/latest/setup.html for Heroku
2. Add a new DNS for your app: `heroku domains:add www.example.com`
3. Go to www.example.com.
4. When logging in, you will get an Internal Server Error.
5. Issue "heroku logs" command, which gives this information:

> 2016-11-02T07:51:10.378267+00:00 app[web.1]: [2016-11-02 07:51:10,374][PID:3][ERROR][redash] Exception on /login [POST]
> 2016-11-02T07:51:10.378283+00:00 app[web.1]: Traceback (most recent call last):
> 2016-11-02T07:51:10.378284+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
> 2016-11-02T07:51:10.378285+00:00 app[web.1]:     response = self.full_dispatch_request()
> 2016-11-02T07:51:10.378286+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
> 2016-11-02T07:51:10.378286+00:00 app[web.1]:     rv = self.handle_user_exception(e)
> 2016-11-02T07:51:10.378287+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_restful/__init__.py", line 271, in error_router
> 2016-11-02T07:51:10.378288+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)
> 2016-11-02T07:51:10.378288+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
> 2016-11-02T07:51:10.378287+00:00 app[web.1]:     return original_handler(e)
> 2016-11-02T07:51:10.378289+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
> 2016-11-02T07:51:10.378289+00:00 app[web.1]:     rv = self.dispatch_request()
> 2016-11-02T07:51:10.378290+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
> 2016-11-02T07:51:10.378291+00:00 app[web.1]:   File "/app/redash/handlers/authentication.py", line 104, in login
> 2016-11-02T07:51:10.378291+00:00 app[web.1]:     login_user(user, remember=remember)
> 2016-11-02T07:51:10.378292+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask_login.py", line 721, in login_user
> 2016-11-02T07:51:10.378290+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)
> 2016-11-02T07:51:10.378292+00:00 app[web.1]:     user_logged_in.send(current_app._get_current_object(), user=_get_user())
> 2016-11-02T07:51:10.378292+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/blinker/base.py", line 267, in send
> 2016-11-02T07:51:10.378293+00:00 app[web.1]:     for receiver in self.receivers_for(sender)]
> 2016-11-02T07:51:10.378293+00:00 app[web.1]:   File "/app/redash/authentication/__init__.py", line 124, in log_user_logged_in
> 2016-11-02T07:51:10.378294+00:00 app[web.1]:     record_event.delay(event)
> 2016-11-02T07:51:10.378294+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/task.py", line 453, in delay
> 2016-11-02T07:51:10.378294+00:00 app[web.1]:     return self.apply_async(args, kwargs)
> 2016-11-02T07:51:10.378295+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/task.py", line 565, in apply_async
> 2016-11-02T07:51:10.378295+00:00 app[web.1]:     **dict(self._get_exec_options(), **options)
> 2016-11-02T07:51:10.378296+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/base.py", line 354, in send_task
> 2016-11-02T07:51:10.378296+00:00 app[web.1]:     reply_to=reply_to or self.oid, **options
> 2016-11-02T07:51:10.378296+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/celery/app/amqp.py", line 310, in publish_task
> 2016-11-02T07:51:10.378297+00:00 app[web.1]:     **kwargs
> 2016-11-02T07:51:10.378297+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 172, in publish
> 2016-11-02T07:51:10.378298+00:00 app[web.1]:     routing_key, mandatory, immediate, exchange, declare)
> 2016-11-02T07:51:10.378298+00:00 app[web.1]:     return fun(*args, **kwargs)
> 2016-11-02T07:51:10.378313+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 184, in _publish
> 2016-11-02T07:51:10.378313+00:00 app[web.1]:     [maybe_declare(entity) for entity in declare]
> 2016-11-02T07:51:10.378298+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/connection.py", line 449, in _ensured
> 2016-11-02T07:51:10.378313+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/messaging.py", line 111, in maybe_declare
> 2016-11-02T07:51:10.378314+00:00 app[web.1]:     return maybe_declare(entity, self.channel, retry, **retry_policy)
> 2016-11-02T07:51:10.378315+00:00 app[web.1]:     return _maybe_declare(entity, declared, ident, channel)
> 2016-11-02T07:51:10.378314+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/common.py", line 120, in maybe_declare
> 2016-11-02T07:51:10.378315+00:00 app[web.1]:     entity.declare()
> 2016-11-02T07:51:10.378315+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/common.py", line 127, in _maybe_declare
> 2016-11-02T07:51:10.378317+00:00 app[web.1]:     nowait=nowait)
> 2016-11-02T07:51:10.378316+00:00 app[web.1]:     self.queue_declare(nowait, passive=False)
> 2016-11-02T07:51:10.378316+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/entity.py", line 522, in declare
> 2016-11-02T07:51:10.378316+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/entity.py", line 548, in queue_declare
> 2016-11-02T07:51:10.378319+00:00 app[web.1]:     sizes = pipe.execute()
> 2016-11-02T07:51:10.378317+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/virtual/__init__.py", line 447, in queue_declare
> 2016-11-02T07:51:10.378318+00:00 app[web.1]:     return queue_declare_ok_t(queue, self._size(queue), 0)
> 2016-11-02T07:51:10.378319+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/kombu/transport/redis.py", line 690, in _size
> 2016-11-02T07:51:10.378319+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 2641, in execute
> 2016-11-02T07:51:10.378320+00:00 app[web.1]:     return execute(conn, stack, raise_on_error)
> 2016-11-02T07:51:10.378320+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/client.py", line 2495, in _execute_transaction
> 2016-11-02T07:51:10.378320+00:00 app[web.1]:     connection.send_packed_command(all_cmds)
> 2016-11-02T07:51:10.378321+00:00 app[web.1]:     self.connect()
> 2016-11-02T07:51:10.378321+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
> 2016-11-02T07:51:10.378321+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 446, in connect
> 2016-11-02T07:51:10.378322+00:00 app[web.1]:     self.on_connect()
> 2016-11-02T07:51:10.378325+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 514, in on_connect
> 2016-11-02T07:51:10.378326+00:00 app[web.1]:     if nativestr(self.read_response()) != 'OK':
> 2016-11-02T07:51:10.378326+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 577, in read_response
> 2016-11-02T07:51:10.378326+00:00 app[web.1]:     response = self._parser.read_response()
> 2016-11-02T07:51:10.378327+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/redis/connection.py", line 255, in read_response
> 2016-11-02T07:51:10.378327+00:00 app[web.1]:     raise error
> 2016-11-02T07:51:10.378328+00:00 app[web.1]: ConnectionError: max number of clients reached

**Comment by arikfr** [comment]
Issues like this is why I wasn't thrilled about bringing back the Heroku support :-( It seems that by default Celery keeps a lot of connections open, and the dev plan's 20 limit isn't enough.

You can try to reduce the number of workers or increase the Redis plan. Although at this point paying $15/mo just for Redis seems silly, as you can run the whole thing on a $5/mo DigitalOcean droplet or similar priced small instance on AWS.

**Comment by mika0x56** [comment]
Thanks for the quick reply.

Initially I had the same thought as you, but this is not the case. I know this because the same installation works just fine when accessed through the Heroku given DNS. This issue *only* happens when accessed through custom DNS.

Perhaps there is some kind of infinite redirection causing all Redis connections to be used up?

**Comment by arikfr** [comment]
I don't think redirects would affect number of connections to Redis. If you try right now it still works fine via Heroku's given DNS?

**Comment by mika0x56** [comment]
Yes, I am using it right now at http://dooify-clarity.herokuapp.com/
And it is still broken at https://clarity.dooify.com

clarity.dooify.com is a simple CNAME to dooify-clarity.herokuapp.com

**Comment by arikfr** [comment]
With the Heroku URL you can get past the login screen and with the other you can't?

**Comment by mika0x56** [comment]
Yes.

**Comment by arikfr** [comment]
That's super strange. Can you try logging out and logging in again?

**Comment by mika0x56** [comment]
Oh my... think I found the issue. Didn't mention the DNS is funneled through CloudFlare which adds SSL towards the client. So we have:

Client <==HTTP/SSL==> CloudFlare <==HTTP==> Heroku

Redash is redirecting to HTTP urls, but CloudFlare will do 301 on those to HTTPS.

Also on the client side we get lots of mixed-content errors:
![image](https://cloud.githubusercontent.com/assets/1054229/19924293/9f4e5462-a0eb-11e6-8367-ddf2136d4740.png)

**Comment by arikfr** [comment]
I saw similar issues in the past, when people were using ELB and didn't configure nginx to properly forward the protocol header.

I'm not sure how this is fixed on Heroku, but can you configure CloudFlare to communicate over HTTPS with the Heroku backend? This will also increase security.

If it's not possible, maybe define the custom domain directly on Heroku? Last I heard, they started to support free SSL on custom domains.

**Comment by arikfr** [comment]
And btw, the HTTPS issue might be preventing you from logging in, but you will still have the issue with Redis connections. 

I really recommend you migrate away from Heroku for this or use higher tier Redis addon.

**Comment by mika0x56** [comment]
All good workarounds! I'll pick one and let it be settled for now.

Other ways of solving it would be to implement the X-FORWARDED-PROTO header (set by CloudFlare).
Also as for client-requested resources, omitting the protocol will pick the correct one. So using "://" instead of "http://"

(as a side-note, Heroku SSL is free for paid plans and I'm currently running on the free one).

**Comment by arikfr** [comment]
I'm pretty sure we support the X-FORWARDED-PROTO header, as this is how it works with nginx. Maybe Heroku "swallows" it?

And we actually don't set the port or URL at all:

```
    <link rel="stylesheet" href="/styles/superflat_redash.css">
```

**Comment by mika0x56** [comment]
Can't say for sure about whether or not Heroku swallows that header. Can look into if necessary.

As for the links, you don't set the origin in the urls but you do specify a different base:

`<base href="http://clarity.dooify.com/">`

**Comment by arikfr** [comment]
Oh, right. Forgot about the base thing. Yep, that's the problem.
