### ISSUE TITLE
Docker Compose install error - docs or me failing?

### ISSUE THREAD

**Issue by antgel** [getredash/redash#1377]
Originally posted at https://discuss.redash.io/t/docker-compose-install-error-docs-or-me-failing/262, but perhaps I should have come straight here as it looks like a bug:

Hi all, I'm following the Docker Compose section at http://docs.redash.io/en/latest/setup.html1. Sadly, I fail at step 5:

> (default) ￼ ~/src/git/redash/setup/ubuntu_docker/files [master|￼] 
> 17:12 $ docker-compose up 
> files_redis_1 is up-to-date
> files_postgres_1 is up-to-date
> files_redash_1 is up-to-date
> Starting files_nginx_1
> 
> ERROR: for nginx Cannot start service nginx: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\"rootfs_linux.go:53: mounting \\\\"/opt/redash-docker/nginx/nginx.conf\\\\" to rootfs \\\\"/var/lib/docker/devicemapper/mnt/2d2b8288e6e3189c817e0762202732229ff901536fe0553ec47f16318e53dcf2/rootfs\\\\" at \\\\"/var/lib/docker/devicemapper/mnt/2d2b8288e6e3189c817e0762202732229ff901536fe0553ec47f16318e53dcf2/rootfs/etc/nginx/conf.d/default.conf\\\\" caused \\\\"not a directory\\\\"\\"\"\n"
> ERROR: Encountered errors while bringing up the project.
> (default) ✘-1 ~/src/git/redash/setup/ubuntu_docker/files [master|￼]

Any clues? Ubuntu Xenial, Docker 1.12.3.

I have some documentation patches ready to submit, but first I'd like to get a working install. ￼

**Comment by arikfr** [comment]
Have you seen my reply on your forum post?

**Comment by antgel** [comment]
Hey, no I didn't see that, and I still don't see it. Strange...

**Comment by arikfr** [comment]
apparently I didn't hit the "publish" button... luckily Discourse save drafts :)

**Comment by antgel** [comment]
I hope PR #1380 will be useful in this matter. :)
