### ISSUE TITLE
execute a sql  click onetime not over and waiting not over no result

### ISSUE THREAD

**Issue by woisnow** [getredash/redash#1379]
when i execute a sql once , i will be waiting lang time and there is no result , the execute will be not over ,server is printing log again and again ... why ? (even a very simple sql, the data source is mysql)

**Comment by arikfr** [comment]
Hi 👋 

It's hard to tell what's going as there might be many different reasons for this behavior. I would make sure that the Celery workers are running. If they are, check the logs and the browser console.

As we keep the issues only for reproducible and confirmed bugs, if it still doesn't work, please follow up with a message in the [forum](discuss.redash.io) and include:

- What version of Redash are you using.
- How you set it up.
- Your browser/OS versions.
- Any relevant log output.
