### ISSUE TITLE
Share access permissions for add/remove widgets

### ISSUE THREAD

**Issue by whummer** [getredash/redash#1383]
Hi @arikfr ,

in our PR #1113 we focused primarily on sharing access permissions for queries, and for dashboards we currently only allow to modify basic info of the dashboard. What is still missing is ability to allow other users to add and remove widgets. Is that something you are planning to add, or should we give it a shot?

Another thing that came up - we're currently enforcing `require_admin_or_owner(...)` for managing access permissions (e.g., https://github.com/getredash/redash/blob/master/redash/handlers/permissions.py#L42). This is actually a very restrictive limitation, and we believe that anybody with permissions (owner, admin, other permitted users) should be able to add/remove users. For instance, if you consider person A creating a dashboard, then giving access to persons B and C who are actively maintaining that dashboard. Then, if person A leaves the company, B and C would not be able to make the required changes to add another person D. What do you think?

/cc @rohanpd

**Comment by adamlwgriffiths** [comment]
This is what the role of an admin is. The ability to administrate an account.
As part of someone leaving a company, they would delegate their admin access to someone else / hand over their account.

I think perhaps what you're asking for instead, is a more 'per-action' style permission system.
Ie, create / add user, created / edit widget, create / add query, create / edit dashboard, etc.

**Comment by arikfr** [comment]
For the first thing: I think that we should allow managing widgets. At least on my part, it wasn't intentional and just an overlook.

For the second issue: in general I agree with @adamlwgriffiths, that this is what the other admins are for. But I do think we should have the ability to handover ownership of objects to someone else. Opened #1387 to track this.
