### ISSUE TITLE
vagrant up than default: : No such file or directory

### ISSUE THREAD

**Issue by Ive4** [getredash/redash#1384]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

vagrant up than default: : No such file or directory

### Steps to Reproduce

1. vagrant up

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: git version 058b6bc
* Browser/OS: vagrant
* How did you install Redash: vagrant up

**Comment by arikfr** [comment]
It's not clear where do you get the "No such file or directory" message. Anyway we're working on new developer guide (and Vagrant box or alternative). You can follow #1480 for updates.
