### ISSUE TITLE
Sorting of Queries view not working

### ISSUE THREAD

**Issue by fakob** [getredash/redash#1386]
### Issue Summary
Alphabetical sorting of queries in the queries view by clicking on the column title is not possible anymore. It had worked in 0.11.

### Steps to Reproduce

1. Go to Menu Queries > Queries
2. Click on NAME (header of column)
3. Nothing happens

### Technical details:

* Redash Version: Re:dash 0.12.0+b2388
* Browser/OS: Chrome 54 and Safari 10 on OSX 10.11
* How did you install Redash: AWS

**Comment by arikfr** [comment]
As we load queries in chunks now, it's no longer possible to sort them in the UI and we need to implement support for this on the backend.
