### ISSUE TITLE
Release new user guide

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#1390]
- [x] Fix link in the footer.
- [x] Review open issues with docs changes.
- [x] Setup redirect from docs.redash.io.

**Comment by antgel** [comment]
Hey, does this issue cover things like:
- Arrive at https://github.com/getredash/redash
- Click on "Setting up Redash instance"
- Arrive at https://redash.io/help-onpremise/setup/setting-up-redash-instance.html
- Click on "here" in the "How to upgrade?" section
- 404

**Comment by arikfr** [comment]
@antgel thanks! Will be fixed.
