### ISSUE TITLE
postgre data tables not create

### ISSUE THREAD

**Issue by Ive4** [getredash/redash#1391]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. docker-compose up
2. not found any tables

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: v0.11.1.b2095
* Browser/OS: CentOS7
* How did you install Redash: docker-compose

**Comment by arikfr** [comment]
Please read the docs. It's mentions how to create the tables.

https://redash.io/help-onpremise/setup/setting-up-redash-instance.html
