### ISSUE TITLE
Create a page with all the dashboards and assign tags to dashboards

### ISSUE THREAD

**Issue by luke14free** [getredash/redash#1393]
As many people have issues displaying all the dashboards using the current UI it would be nice to have a page similar to that of the queries for the dashboards. Also the current system of <group:dashboard> could be replaced by a system of tags.

Todos:
- [x] Create the dashboards page
- [x] Add search features / pagination
- [x] Create the tagging system
- [x] Make dashboards searchable by tag #

**Comment by arikfr** [comment]
I'm not sure what you were planning but to develop in shorter cycles, I would use a convention for tags instead of deploying a "proper" tagging system. I.e. convert "#tag" in dashboard name into tags (along with the "group:" thing for legacy support).

**Comment by luke14free** [comment]
👍 that's exactly my plan. I will try to replicate what we have for queries. are you sure we want to keep support for <tag:>? it could become a bit counterintuitive to have two ways to input tags

**Comment by arikfr** [comment]
what do we have for queries? :)

**Comment by luke14free** [comment]
the `/queries` page, but for dashboards. also I am not super sure that info about when a dashboard was created/updated is very useful. it just makes the page heavier to read and navigate imho.

**Comment by arikfr** [comment]
Got it, I mixed your two sentences... I thought that by two ways you meant some way in queries to input tags.

Yes - let's replicate what we have for queries. As for what to show - I agree that the created/updated is not that important.

> are you sure we want to keep support for ? it could become a bit counterintuitive to have two ways to input tags

It's either that or have a migration to translate it into the new format. I just prefer not to mess with people's content.

**Comment by luke14free** [comment]
@arikfr  check https://github.com/getredash/redash/pull/1399

**Comment by arikfr** [comment]
Implemented 👍
