### ISSUE TITLE
Schedule dialog not updated between queries

### ISSUE THREAD

**Issue by adamlwgriffiths** [getredash/redash#1397]
When updating multiple queries refresh times, I've found that the refresh dialog doesn't update and displays the selected refresh value of the last query.

Steps:
1. select query
2. change refresh time
3. select another query with a different refresh time
4. open refresh dialog

Result:
The previous queries refresh interval is shown.

Expected:
The current queries refresh interval to be shown.

Impact:
If the desired refresh period for the current query is the same as the previous, another refresh interval must be selected first, otherwise the dialog will detect no change and the interval is not changed.

**Comment by adamlwgriffiths** [comment]
This seems to have triggered after the second query I looked at. It then "resolved itself" after modifying 10 queries.

**Comment by arikfr** [comment]
I'm failing to reproduce this or to understand how it's even possible, as the schedule form uses the query view's scope. Do you see the wrong schedule time in the query page as well?

By "select another query" you mean go back to the queries page and click on another linked query?

**Comment by adamlwgriffiths** [comment]
The schedule time on the query page is correct, but the dialog wasn't updated and had the old value, hence changing it to the incorrectly selected value requires 2 changes - one to a new value, one back again.

Correct, to select another query I was going via the 'queries' page.

I had this occur for about 5 minutes, and then it stopped and I couldn't reproduce it.
Not sure what was going on, since the queries themselves loaded correctly.

**Comment by arikfr** [comment]
Did you change anything in your version of Redash that relates to the frontend code?

**Comment by adamlwgriffiths** [comment]
Nothing that should affect this.
I think because I can't reproduce it we should close this issue, but I'll keep an eye out for it occurring again.
