### ISSUE TITLE
Add to status page the size of Redash's DB

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#1411]
```sql
SELECT pg_size_pretty(pg_total_relation_size('query_results'));
```

```sql
SELECT pg_size_pretty(pg_database_size('redash'));
```

**Comment by alison985** [comment]
@arikfr  Happy to work on this one but I'm not seeing how status.json gets populated, or even where it is. Could you provide a pointer please?

**Comment by arikfr** [comment]
Here:

https://github.com/getredash/redash/blob/2a22b98c77757f378d3a4ed1ec8eceb99f0a8b35/redash/handlers/__init__.py#L15-L20

And it uses the `get_status` method from here:

https://github.com/getredash/redash/blob/2a22b98c77757f378d3a4ed1ec8eceb99f0a8b35/redash/monitor.py#L4

Thanks!
