### ISSUE TITLE
Allow administrators to set the allowed refresh intervals for dashboards and queries

### ISSUE THREAD

**Issue by rohanpd** [getredash/redash#1412]
Redash administrators should be allowed to set the minimum refresh frequency for both dashboards and queries as there may be some databases that cannot handle large queries hitting them on short intervals.

**Comment by arikfr** [comment]
Implemented in v4.

**Comment by rohanpd** [comment]
Thanks for this @arikfr!

Is this applied to both Dashboard and query refreshes or just dashboards?

**Comment by samarthkeeptruckin** [comment]
@arikfr thanks for this. How do we tweak this setting being an Admin?
