### ISSUE TITLE
Word Cloud visualization improvements

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#1414]
Additional configuration options:

* Limit on words
* Ability to pass the word frequency

**Comment by dermatou** [comment]
Not quite sure how the word cloud is supposed to be working:
here, with 20 results, word cloud is not properly counting or showing the results: https://demo.redash.io/queries/4263
Same query, with 15 results, all fine: https://demo.redash.io/queries/4262

Is this a current limitation or would this be a bug?

**Comment by satheeshravir** [comment]
Any plan to implement this feature?

**Comment by diegodorgam** [comment]
hey, I'm currently trying to get keywords and frequency count from a mongodb database, returning a dataset with a [count , tag] columns, is that correct?

**Comment by mohamagdy** [comment]
@arikfr one of the configuration options is implemented as part of https://github.com/getredash/redash/pull/3668. 

The bug @dermatou addressed most probably fixed also as part of https://github.com/getredash/redash/pull/3668 by setting a max value for the size of the texts in the Word Cloud.

**Comment by mosheka** [comment]
> Not quite sure how the word cloud is supposed to be working:
> here, with 20 results, word cloud is not properly counting or showing the results: https://demo.redash.io/queries/4263
> Same query, with 15 results, all fine: https://demo.redash.io/queries/4262
> 
> Is this a current limitation or would this be a bug?

We face the same issues. Word count works with 75 lines (5 unique values).
When we have 100 lines (same 5 unique values) only a single random word is presented.

**Comment by mosheka** [comment]
Was accepted as a Redash issue: https://github.com/getredash/redash/issues/3730
