### ISSUE TITLE
NameError: global name 'cassandra' is not defined

### ISSUE THREAD

**Issue by chemipot** [getredash/redash#1422]
Hey,

### Issue Summary
I added `export REDASH_ADDITIONAL_QUERY_RUNNERS=redash.query_runner.cass` to `opt/redash/.env`. After that, I was able to create a new cassandra datasource but when querying is failing and displaying: **global name 'cassandra' is not defined** 

I have installed the DataStax Cassandra driver `sudo pip install cassandra-driver` and using Python 2.7.6. 

These are the traces of `/opt/redash/logs/celery_error.log`

```
2016-11-23 02:09:15,625: WARNING/Worker-5] Unexpected error while running query:
Traceback (most recent call last):
  File "/opt/redash/redash.0.12.0.b2449/redash/tasks/queries.py", line 410, in run
    data, error = query_runner.run_query(annotated_query, self.user)
  File "/opt/redash/redash.0.12.0.b2449/redash/query_runner/cass.py", line 90, in run_query
    except cassandra.cluster.Error, e:
NameError: global name 'cassandra' is not defined
```
### Technical details

* Redash version 0.12.0+b2449
* OS Ubuntu 3.13.0-88-generic / Browser: Chrome.
* How did you install Redash: running the provisioning script

Thanks

**Comment by arikfr** [comment]
If you run `python -c "import cassandra"` is it working?

**Comment by chemipot** [comment]
> If you run python -c "import cassandra" is it working?

Yes

**Comment by arikfr** [comment]
#1423 fixes this. The problem was that the `cassandra.cluster.Error` exception wasn't imported. You can replace your `/opt/redash/current/redash/query_runner/cass.py` file with the one from the pull request or just add the relevant import statement (I did several other small structure fixes in this pull request).

**Comment by arikfr** [comment]
(this issue only happens if you have an exception while connecting/running the query)

**Comment by sivasankar95** [comment]
I too have the same issue after running  **python -c "import cassandra"** then too its showing the same error. 
Connection Test Failed:
global name 'cassandra' is not defined
[2016-12-19 15:47:43,817: WARNING/Worker-11] Unexpected error while running query:
Traceback (most recent call last):
  File "/opt/redash/redash.0.12.0.b2449/redash/tasks/queries.py", line 410, in run
    data, error = query_runner.run_query(annotated_query, self.user)
  File "/opt/redash/redash.0.12.0.b2449/redash/query_runner/cass.py", line 90, in run_query
    except cassandra.cluster.Error, e:
NameError: global name 'cassandra' is not defined
