### ISSUE TITLE
Delete visualization with many series fails with '414 Request-URI Too Long'

### ISSUE THREAD

**Issue by deecay** [getredash/redash#1432]
### Issue Summary

Delete visualization fails with '414 Request-URI Too Long' when the visualization has a lot (100+) of series.

apache log shows:

> DELETE /api/visualizations/7?created_at=2016-11-23T15:32:17.259565%2B09:00&description=&name=Time&options=%7B%22showlegend%22:false,%22yAxis%22:%5B%7B%22title%22:%7B%22text%22:%22%22%7D,%22rangeMax%22:1499999999999,%22type%22:%22datetime%22,%22rangeMin%22:1471000000000,%22series%22:%7B%22stacking%22:null%7D,%22globalSeriesType%22:%22line%22,%22sortX%22:true,%22seriesOptions%22:%7B%221%22:%7B%22zIndex%22:0,%22index%22:0,%22type%22:%22line%22,%22yAxis%22:0%7D,%222%22:%7B%22zIndex%22:1,%22index%22:0,%22type%22:%22line%22,%22yAxis%22:0%7D,%223%22:%7B%22zIndex%22:2,%22index%22:0,%22type%22:%22line%22,..........

Do we need all the `options` in GET parameter?

### Technical details:

* Redash Version: 12.0
* Browser/OS: Chrome/Win8
* How did you install Redash: Bitnami+git clone

**Comment by arikfr** [comment]
Not at all. It's a bug.
