### ISSUE TITLE
Table View Adding Commas

### ISSUE THREAD

**Issue by Charg** [getredash/redash#1437]
The table view is adding commas to numbers. See below:

![image](https://cloud.githubusercontent.com/assets/1368872/20732549/2633fbae-b644-11e6-9c3f-7e4a1f33beed.png)

Is there any way to disable this? It's useful to quickly be able to copy an ID and use it in another query.

Thanks!

**Comment by Charg** [comment]
For the time being I have gone ahead and removed `numbers` from the **DefaultFilter** in redash. While this isn't a good long term solution it will suffice for our needs. All queried results should be represented unmolested.

**Comment by arikfr** [comment]
Resolved in V4.

**Comment by mattdiamond** [comment]
@arikfr How was this resolved? It's 2026 and there's still no way to fix this at a global level. See http://github.com/getredash/redash/discussions/7139
