### ISSUE TITLE
Cassandra not selectable in Datasource type drop down

### ISSUE THREAD

**Issue by muglar** [getredash/redash#1443]
Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

Fresh install of Re:dash 0.12.0+b2449 on Ubuntu 14.04 server using bootstrap.sh.  After installation is completed, unable to select Cassandra as a datasource in the type drop down menu.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: Re:dash 0.12.0+b2449
* Browser/OS: Chrome/Windows10
* How did you install Redash: bootstrap.sh on fresh ubuntu 14.04 server

![image](https://cloud.githubusercontent.com/assets/17802517/20852789/c46fb948-b8b5-11e6-8663-23203dcb7723.png)

**Comment by sivasankar95** [comment]
did you find a solution for this issue???? I am too facing the same issue

**Comment by dioptre** [comment]
Is the Cassandra support fake? It's still not an option in the latest docker.
