### ISSUE TITLE
Cassandra Keyspace - Test Connection Error

### ISSUE THREAD

**Issue by muglar** [getredash/redash#1444]
### Issue Summary

Issue with the keyspace connection.  Also does not work in a query.

![image](https://cloud.githubusercontent.com/assets/17802517/20855080/47eefe76-b8c7-11e6-8248-882e66addce1.png)

### Technical details:

* Redash Version: Re:dash 0.12.0+b2449 w/ updated cass.py file
* Browser/OS: Chrome/Windows 10
* How did you install Redash: bootstrap.sh on fresh ubuntu 14.04 server

**Comment by arikfr** [comment]
What error do you get when running a query? Same one?

**Comment by muglar** [comment]
When running a query you need to fully specify the keyspace and table name,
rather than just the table name.  It seems that the keyspace that is
entered in the configuration settings isn't being used.

select * from scadadata.historian where tag_id = 'TIT87102' limit 600; will
work

select * from historian where tag_id = 'TIT87102' limit 600; will not work.

**Comment by yershalom** [comment]
Hi @muglar ,
I pushed the fix for this.

**Comment by arikfr** [comment]
Fixed with #1474.

**Comment by arikfr** [comment]
Actually #1474 fixes only the test connection issue. @yershalom is there anything to do about the need to specify the keyspace in each query?

**Comment by yershalom** [comment]
Yep. Pushing it now.
I had to restart the redash_celery process though
