### ISSUE TITLE
AMI needed for ap-south-1 (Mumbai AWS Datacenter)

### ISSUE THREAD

**Issue by atishaykumar** [getredash/redash#1445]
### Issue Summary

There is no AMI for re:dash in AWS Mumbai data center (ap-south-1). ap-southeast-1 is AWS Singapore and the shotname can be confusing.

Thank you very much for taking this up.

### Steps to Reproduce

Self-explanatory

### Technical details:

Not applicable

**Comment by atishaykumar** [comment]
Hello - v1.0.0 doesn't have a due date so I am curious when will this be done. Thank you.

**Comment by arikfr** [comment]
[ami-47403328](https://console.aws.amazon.com/ec2/home?region=ap-south-1#LaunchInstanceWizard:ami=ami-47403328)

(this AMI is for v1.0.1)
