### ISSUE TITLE
Table listing frame size should be adjustable on new query page

### ISSUE THREAD

**Issue by prabh-me** [getredash/redash#1446]
Table listing frame that displays the list of all tables on the new query page is not able to display tables with long names. There is no way to adjust the size of the frame as per the requirement.
It is very difficult to select the correct table, checking out schemas, copy/paste table names. 
![screen shot 2016-12-04 at 21 06 48](https://cloud.githubusercontent.com/assets/3313345/20867222/65eef5ee-ba65-11e6-865a-be802a085efb.png)

**Comment by arikfr** [comment]
Implemented in v4.
