### ISSUE TITLE
Angular dependency injection issues after minification

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#1455]
("Unkonwn provider eProvider" errors)

- groups page

**Comment by denisov-vlad** [comment]
dashboard page -> add widget menu

**Comment by denisov-vlad** [comment]
query page -> visualisation editor

**Comment by denisov-vlad** [comment]
groups page -> new group

**Comment by denisov-vlad** [comment]
alerts -> add notification

**Comment by denisov-vlad** [comment]
embed code popup

**Comment by denisov-vlad** [comment]
query page also
