### ISSUE TITLE
Wrong sort for Date column

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#1457]
It happens if sort by date column with UI.

Screenshot shows everything. 

<img width="544" alt="2016-12-06 14 37 07" src="https://cloud.githubusercontent.com/assets/7091907/20924299/dea511b4-bbc1-11e6-8ffd-2bdda4bcbbd8.png">

**Comment by WesleyBatista** [comment]
Sorry, didn't get the problem. 

It seems to be a descendent sort. 
**2016-12-06** is greater than **2016-11-07**, right?

**Comment by denisov-vlad** [comment]
@WesleyBatista but it's ascending sort. Looks like it sorts strings 'DD/MM/YYYY' but not dates 'YYYY-MM-DD'
