### ISSUE TITLE
pip install not running on vagrant box

### ISSUE THREAD

**Issue by majofi** [getredash/redash#1462]
### Issue Summary

I'm trying the vagrant box on the current master and it's failing during provisioning. 
To be exactly during:
"Running setup.py install for cryptography"
...
"ImportError: No module named setuptools_ext"
the following rollback seems to mess up the pip installation itself on that box.

### Steps to Reproduce

1. checkout current redash master from github
2. run "./bin/vagrant_ctl.sh test" (obviously the same happens with ./bin/vagrant_ctl.sh start)

### Next Steps?

I'm totally new to redash and thinking about developing / contributing. So I'm curious if the recommended way to run redash on my dev machine is a) with the vagrant image, b) "native" or c) with the docker image? 
If the vagrant is in fact still supported I could also have a look on fixing this, just want to be sure I'm not reviving some no longer supported legacy.

**Comment by 44px** [comment]
Yes, should upvote this. I use Redash at work and really like it.

I'm frontend developer and there are plenty of issues with "Frontend" label. Maybe I can help with some. But I'm not familiar with python and its tools, so it seems I can't easily set up development environment.

It seems there are many developers who are willing to help, but stuck on `vagrant up` =(

**Comment by arikfr** [comment]
@44px You're so right :-( I will update the Vagrant box along with 1.0 release. I'm just wondering -- what will be more helpful: a new Vagrant box or just proper documentation on how to setup dev environment on Linux and OS/X?

**Comment by 44px** [comment]
It's good news. Thank you for response!

Vagrant box looks like more universal solution since it can be used on any OS and provides isolated environment (no need to install anything on host OS).

**Comment by arikfr** [comment]
Opened #1480 to track the work on the dev guide. Keeping this one open until I'm done.

**Comment by arikfr** [comment]
The developer guide has been updated along with new documentation on how to use Docker for  easy setup of your dev environment (instead of Vagrant).

https://redash.io/help-onpremise/dev/guide.html

Thank you for all your feedback!
Your feedback on the new guide & flow is always welcomed.

**Comment by 44px** [comment]
Thank you for your work on this!
New docker dev env is easier to setup and works fine.

**Comment by arikfr** [comment]
Thanks for the feedback!
