### ISSUE TITLE
Support for geocoding addresses to show on a map visualization

### ISSUE THREAD

**Issue by ryanmerolle** [getredash/redash#1469]
I could not find this in an existing feature request

I have a data that has the full address of a office.  I would like to be able to just pull from said table and display on a map without need to convert an address to coordinates.

**Comment by ryanmerolle** [comment]
Being 4 years old, should we just close this?

**Comment by arikfr** [comment]
Since then we switched to having the issues mostly for actionable stuff (either planned to work on or bugs) and moved feature requests like this one to the [forum](discuss.redash.io).

Probably makes sense to close it...

Thanks.
