### ISSUE TITLE
Missing step for docker setup

### ISSUE THREAD

**Issue by DALDEI** [getredash/redash#1472]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

Missing step for docker setup in https://redash.io/help-onpremise/setup/setting-up-redash-instance.html

### Steps to Reproduce

Read the steps
run them
dont work

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:
Missing step is  0.

cp docker-compose-example.yml docker-compose.yml

**Comment by arikfr** [comment]
Being addressed here: https://github.com/getredash/website/pull/21.
