### ISSUE TITLE
Move all possible events to serverside

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#1501]
Currently we log some events from the client and some events from the server. We should log all possible events from the server and leave on the client only those that we can't.

**Comment by alison985** [comment]
@arikfr I did 2 examples of this in case to start out with in case you want to review: https://github.com/alison985/mozilla-redash/commit/5d8b2083c5debd9f7d2fad1f21cbeb8b6355c5a1

**Comment by alison985** [comment]
For all of the ones I could find a way to do server-side: https://github.com/mozilla/redash/pull/246

**Comment by arikfr** [comment]
Thanks! Commented on the commit.
