### ISSUE TITLE
Can't delete blank dashboard (not sure why its blank).

### ISSUE THREAD

**Issue by lovelady** [getredash/redash#1506]
Fresh install using one of the images provided for AWS. Everything installed great...this morning though I was fiddling around with a test dashboard, adding some modules until it seems to all freeze up. Specifically, I was using the popup that allows you to move around the sections of the dashboard when it frove/crashed.

Reloading the dashboard rendered a blank page (redash nav and credits exist but nothing on the dashboard). Archiving the dashboard results in a error saying "could no archive dashboard" and while attempting to add a widget to the now blank dashboard results in an error that says "widget could not be added". 

Everything else works great and I love what you have done!! New dashboards seem to work fine. 

Note I updated to the most recent version and it hasn't helped.

**Comment by arikfr** [comment]
I think that if you inspect this dashboard's layout property (via `/admin/dashboard` or by querying the metadata tables), you will find null values in there. This is why the dashboard fails to render and seem blank.

If you remove the nulls from the layout string, it will render again.

What version of Redash do you use?

**Comment by arikfr** [comment]
Please reopen if it's not the issue I mentioned and have additional details on how to reproduce. Thanks 👍
