### ISSUE TITLE
Switch Layout of Visualisation widgets in dashboards

### ISSUE THREAD

**Issue by atharvai** [getredash/redash#1511]
### Issue Summary

Visualisation widgets in dashboards have Query name for title and visualisation name is small. I feel like on a dashbaord the title of the widget should be the visualisation name. the query name and description should be smaller

![image](https://cloud.githubusercontent.com/assets/14027470/21771952/5c8a994e-d681-11e6-8982-abab3ec1d279.png)

On a dashboard it is hard to find visualisations if there are multiple charts from same query. the focus should be on visualisation name

**Comment by arikfr** [comment]
From looking at the usage in the SaaS version of Redash, I can see that only 15% of visualizations have a title, _but_ almost 50% of visualizations that get placed on dashboards have a title.

Still it means that in 50% of the cases, we will see "Chart" or "Table" as the main title of the widget...

Maybe the logic should be:
1. If the visualization has a custom name, then use the visualization name and add query as the small title.
2. If the visualization has a default name, then use the query name.

WDYT?

**Comment by atharvai** [comment]
I agree, that makes sense.

**Comment by kocsmy** [comment]
Cross-linking the related forum discussion: https://discuss.redash.io/t/query-title-and-visualisation-title-on-the-dashboard-should-be-switched-in-color/1901/6

**Comment by kocsmy** [comment]
Implemented #2583
