### ISSUE TITLE
Elasticsearch query runner: mappings_data is not defined

### ISSUE THREAD

**Issue by idlefella** [getredash/redash#1519]
### Issue Summary
When executing an elasticsearch query, a message appears that "mappings_data is not defined".

### Steps to Reproduce
1. Clone the latest version (master branch) from github and install the dev environment.
2. Add an elasticsearch instance and try to execute a query, e.g.
`{"query": {'"match_all": {}}`
3. A message appears that the query was not successfull (mappings_data is not defined)

The bug is quite obvious since https://github.com/getredash/redash/blob/3bc98fba5bd2b6b723ba0d0ce3007a651e8c2acb/redash/query_runner/elasticsearch.py#L126 refers to mappings_data, which is nowhere defined in the same file. Unfortunately I didn't find out what this mappings_data should contain.

### Technical details:

* Redash Version: master branch
* Browser/OS: Linux/Chrome

**Comment by arikfr** [comment]
Fixed. Thanks!
