### ISSUE TITLE
presto error messages are hard to read

### ISSUE THREAD

**Issue by cldellow** [getredash/redash#1529]
### Issue Summary

Errors for the presto query runner produce a hard-to-read stringified JSON blob, e.g.:

![presto-error-old](https://cloud.githubusercontent.com/assets/193185/21988913/eed7afda-dbd6-11e6-9294-d7853939ee78.png)

It'd probably be useful to just have the embedded message field instead of the entire thing --  the JSON escaping and and Presto stack trace are rarely relevant to the user.

### Steps to Reproduce

1. Run a query that will fail, e.g. 'SELECT foo FROM bar WHERE baz = 1'

### Technical details:

* Redash Version: 0.12.0+b2449

**Comment by cldellow** [comment]
Note, an easy "fix" is to patch `query_runner/presto.py` and add:

```
if type(error) is dict and 'failureInfo' in error and 'message' in error['failureInfo']:
    error = error['failureInfo']['message']
```

to pull our the error message.

Then you get error messages like:

![presto-error-new](https://cloud.githubusercontent.com/assets/193185/21989016/541a15b8-dbd7-11e6-9fdc-ddc45dbf2eb4.png)

That feels kinda hacky though -- maybe there's a reason the fuller blob is being sent? If not, I can put together a PR that makes this change.

**Comment by arikfr** [comment]
This definitely looks nicer! But I agree that the implementation feels hacky. The snippet you posted on what line in preto.py does it belong?

**Comment by cldellow** [comment]
It would go here: https://github.com/getredash/redash/blob/master/redash/query_runner/presto.py#L117

**Comment by arikfr** [comment]
Maybe to make it less hacky we catch a more specific exception class there rather than just `Exception`?

**Comment by aslotnick** [comment]
@arikfr I think [this](https://github.com/getredash/redash/pull/1601) PR should address this issue - anything I should change? I've provided a default and caught the specific exception (DatabaseError) but the overall effect is the same as what @cldellow has proposed.

**Comment by arikfr** [comment]
Thanks @aslotnick ! Merged.

**Comment by aslotnick** [comment]
Thank you, @arikfr ! Happy to finally contribute.
