### ISSUE TITLE
Error running query: Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by crooy** [getredash/redash#1531]
The error:

```
Error running query: Commands out of sync; you can't run this command now
```

I'm running redash on Ubuntu 14 LTS, latest redash(0.12) against AWS RDS MySQL server 5.6.
I get this error while doing a big query that looks like this:

```
DROP
TEMPORARY TABLE IF EXISTS user_ip_map;


CREATE
TEMPORARY TABLE user_ip_map (INDEX ipidx (ip), INDEX ididx (id))
SELECT DISTINCT a1.id,
                SUBSTRING_INDEX(al1.`where`, ',', 1) AS ip
FROM account a1
JOIN audit_log al1 ON al1.`who` = a1.id
AND al1.`where` rlike ','
AND al1.logged_in_as IS NULL;

DROP
TEMPORARY TABLE IF EXISTS user_ip_user;

CREATE
TEMPORARY TABLE user_ip_user (INDEX ididx1 (id1), INDEX ididx2 (id2))
SELECT ip1.id AS id1,
       ip2.id AS id2
FROM user_ip_map AS ip1
JOIN user_ip_map2 AS ip2 ON ip1.ip = ip2.ip
AND ip1.id <> ip2.id;

SELECT ......

```

**Comment by crooy** [comment]
Never mind, i just ran `apt-get upgrade` and rebooted and now its gone...

**Comment by crooy** [comment]
Sorry closed it too soon, after it is done with creating the first temp table and when it starts on the second it goes wrong again.

**Comment by arikfr** [comment]
This messages comes from MySQL and related to your query / the way the MySQL connector sends queries.

To be able to help I need to see the full query. You can send it to me in private if you want (arik at redash dot io).

**Comment by ozasuke** [comment]
I have a similar one.

`create temporary table test as select * from tags;
select count(*) from test;`

and then 

`Error running query: No data was returned.`

I'm running redash on Ubuntu, latest redash(1.0.3) against AWS RDS MySQL server 5.7.16.

I have sucseeded when I tried this.
```
$ mysql -u username -p databasename -h rdshostname.ap-northeast-1.rds.amazonaws.com
mysql> create temporary table test as select * from tags; select count(*) from test;
Query OK, 86 rows affected (0.09 sec)
Records: 86  Duplicates: 0  Warnings: 0

+----------+
| count(*) |
+----------+
|       86 |
+----------+
1 row in set (0.07 sec)
```

**Comment by arikfr** [comment]
@ozasuke it's a limitation of the MySQL driver or the way we use it (probably the later). Similar queries work with Postgres, but not with MySQL...

**Comment by ozasuke** [comment]
@arikfr Thank you for your reply.
As I ran with Postgres demo, I thought that it should work well with mysql...
I will read the source code firmly...! Thank you very much!

**Comment by AHLinJie** [comment]
can i show debug model info to print my commit sql sentence ?

**Comment by jp-castro** [comment]
@arikfr I am getting this error with redash 7.0.0 with MySQL Amazon RDS. It seems like it's something with the way the driver sends queries- do you have any suggestions to fix? Thanks!
