### ISSUE TITLE
"Share URL" ignore the parameters from the address bar

### ISSUE THREAD

**Issue by lab79** [getredash/redash#1533]
We expected that the initial link (with params) should determine "Share URL"

### Technical details:
* Redash Version: 0.12.0+b2449

**Comment by arikfr** [comment]
That's because shared dashboards don't support parameters. As there is already an open issue for this, I'm closing this one.

**Comment by lab79** [comment]
> As there is already an open issue for this, I'm closing this one.
Thanks! Which ticket is opened?

**Comment by arikfr** [comment]
#1267
