### ISSUE TITLE
User without group causes "Internal Server Error 500"

### ISSUE THREAD

**Issue by superobnu** [getredash/redash#1537]
Hi,
User without a group causes a  "Internal Server Error 500" at logon. This occurs in Redash version 0.12.0 + b2449 with Chrome 55.0.2883.87 m (64-bit) and Microsoft Edge. In Firefox appears "Wrong email or password."
I have a internal deploy of Redash over Ubuntu Server 14.
Thanks.
Ronald

**Comment by arikfr** [comment]
Duplicate of #1083.
