### ISSUE TITLE
KeyError: 'properties' in Elasticsearch query runner

### ISSUE THREAD

**Issue by hgs847825** [getredash/redash#1538]
Hello,

I encount KeyError: 'properties' in Elasticsearch query runner.
I'm using Bitnami version of Re:dash 0.12.0.2449

### Mapping
<pre>
{
    "tmp_index": {
        "mappings": {
            "_default_": {
                "dynamic_templates": [
                    { ... }
                ]
            },
            "tmp_index": {
                "dynamic_templates": [
                    { ... }
                ],
                "properties": {
                    ...
                }
            }
        }
    }
}
</pre>

Mappings of "\_default_" has no "properties" field.

### Work around
<pre>
--- /opt/redash-0.12.0.2449-0/apps/redash/htdocs/redash/query_runner/elasticsearch.py.old	2017-01-22 17:42:18.008000000 -0500
+++ /opt/redash-0.12.0.2449-0/apps/redash/htdocs/redash/query_runner/elasticsearch.py	2017-01-22 16:52:33.448000000 -0500
@@ -108,6 +108,8 @@
         for index_name in mappings_data:
             index_mappings = mappings_data[index_name]
             for m in index_mappings.get("mappings", {}):
+                if "properties" not in index_mappings["mappings"][m]:
+                    continue
                 for property_name in index_mappings["mappings"][m]["properties"]:
                     property_data = index_mappings["mappings"][m]["properties"][property_name]
                     if not property_name in mappings:
</pre>

Thanks.

**Comment by arikfr** [comment]
You're welcome to make a pull request with this change 👍

**Comment by arikfr** [comment]
Fixed in #1545.
