### ISSUE TITLE
Failed to find application: 'redash'

### ISSUE THREAD

**Issue by HNKRijeka** [getredash/redash#1541]
### Issue Summary
I'm trying redash to run on docker 1.13 by docker-compose,
I faced that error messages.

```
server_1   | Failed to find application: 'redash'
server_1   | [2017-01-24 02:31:46 +0000] [15] [INFO] Worker exiting (pid: 15)
server_1   | Failed to find application: 'redash'
server_1   | [2017-01-24 02:31:46 +0000] [15] [INFO] Worker exiting (pid: 10)
server_1   | Failed to find application: 'redash'
server_1   | [2017-01-24 02:31:46 +0000] [15] [INFO] Worker exiting (pid: 17)
Traceback (most recent call last):
(snip)
redash_server_1 exited with code 1
```

### Steps to Reproduce
I'm only doing 'Docker Compose' section at following page:
https://redash.io/help-onpremise/setup/setting-up-redash-instance.html

Is it correct this docs or something wrong with me?

**Comment by arikfr** [comment]
Pull master again, rebuild images and it should work. 

Thank you for reporting this.
