### ISSUE TITLE
Deep linking broken for all non text query parameters

### ISSUE THREAD

**Issue by rockwotj** [getredash/redash#1544]
### Issue Summary

Deep linking to a date/time param will not cause the spinner to pick up the correct time

### Steps to Reproduce

1. Create a query with a date parameter
2. Deep link to it with a parameter for the date
3. The display for the query will not show

### Technical details:

* Redash Version: v12
* Browser/OS: Chrome
* How did you install Redash: From source

**Comment by rockwotj** [comment]
In fact this seems to be broken for all non text parameters

**Comment by arikfr** [comment]
Fixed in #1649.
