### ISSUE TITLE
Trouble running new shiny update script

### ISSUE THREAD

**Issue by wihodges** [getredash/redash#1562]
Getting this error when running on Ubuntu 16.04: 
"The found release is not newer than your current deployed release (0.12.0+b2449). Aborting upgrade."

Is there another step I'm missing?

**Comment by wihodges** [comment]
Ah so digging into update script -- https://version.redash.io/api/releases without channel - returns 0.12 as current branch. I manually added beta to url: https://version.redash.io/api/releases?channel=beta and returns the 1.0 release.

**Comment by arikfr** [comment]
Why change the code and not run the script with `--channel beta`?

It's actually mentioned in the [release notes](https://github.com/getredash/redash/releases/tag/v1.0.0-rc.1).

**Comment by wihodges** [comment]
Oops somehow missed that specific release note document. Script works wonderfully!
