### ISSUE TITLE
Google Analytics Connection Test Connection 

### ISSUE THREAD

**Issue by wihodges** [getredash/redash#1565]
Not sure if its a user issue on my end or a small bug, but when I added JSON file to GA connector, save and then test connection. Test connection always throughs back error in connecting. Ended up creating and recreating several service applications all kept giving me an error.

Finally just went to Query builder and it works just fine.

GA connector is amazing addition btw.

**Comment by arikfr** [comment]
"Test Connection" fails, but just using a query works? What was the error it failed with?

**Comment by youweit** [comment]
Same here, any solutions?

**Comment by arikfr** [comment]
Closing. You're welcome to reopen with additional details.
