### ISSUE TITLE
Draft banner covers title and show source button on shorter width screens

### ISSUE THREAD

**Issue by acmiyaguchi** [getredash/redash#1566]
### Issue Summary

If the width of the browser is relatively short, the orange banner with the text `This query is a draft` will cover the title, description, and `Show Source` button. I erroneously thought I was unable to edit my own drafts, which I ruled out by appending `/source` to the url.

### Steps to Reproduce

1. Create a draft of a query
2. Return to the base url (`/queries/<query id>`)
3. Adjust width until the draft box covers the `Show Source` button

You should end up with something like the below:
![shorter_width_redash](https://cloud.githubusercontent.com/assets/3304040/22577058/5b30fa92-e974-11e6-80cd-bc1df13d22f7.png)

I expect the following to be consistent with all sizes.
![normal_width_redash](https://cloud.githubusercontent.com/assets/3304040/22577054/56e2b3e0-e974-11e6-941c-59778a7ee7b8.png)

### Technical details:
Re:dash 1.0.0, Firefox Nightly 53.0a1

**Comment by arikfr** [comment]
Looks like you're using a very early release of 1.0.0. I recommend upgrading to the [1.0.0-rc.1](https://github.com/getredash/redash/releases/tag/v1.0.0-rc.1), where I fixed this.
