### ISSUE TITLE
Can't delete blank dashboard

### ISSUE THREAD

**Issue by dolch0324** [getredash/redash#1568]
I used "Docker Compose" when setup.
And, "Re:dash" verision is 0.12.0+b2449.

I have error in dashboards.

Process:
1,Browser was freeze When Add widget.
2,Wait a few seconds, i clicked "Archive Dashboard".
3,But widget, title, message were not displayed.

When returned top page,
 that dashboard wasn't deleted.

When access to that dashbord, screen is no widgets, and no titles.
(displayde message "a status of 500 (INTERNAL SERVER ERROR)" at  browser log)

When clicked "Archive Dashboard", ask message "are you shure you archive 'undefined' dashboard?".
Of course, not deleted on the top page.

When clicked "Edit Dashbord", a new dashboard created.

When clicked "Add Widget", displayde message "widget can not be added".

I'd like to delete that dashboard. i hope it.

Note:this message is use  "Google Translation".
Sorry if difficult to read. thanks.

**Comment by SlippingAway** [comment]
@dolch0324 Try doing it from the admin console http://<your_redash>/admin/. I had a similar problem due to a bug that will be solved in the 1.0 release, but could fix it via admin.

**Comment by dolch0324** [comment]
@SlippingAway  Thanks to this, I solved it.
It was very helpful!! I will study more ...
Thank you very much!
