### ISSUE TITLE
docs update for developer guide to installing redash

### ISSUE THREAD

**Issue by omouse** [getredash/redash#1575]
The documentation here https://redash.io/help-onpremise/dev/setup.html doesn't list the versions. All it says is "on OS X use brew!" and for Linux:

>On Linux you can use your package manager, although need to make sure it installs recent enough versions.

What does that mean? Postgres 9.3 but not 9.2?

It also feels like the developer guide to install is hidden away in favour of "just use Docker".

**Comment by arikfr** [comment]
It's probably the fault of the way GitBook builds the index page... as it's mentioned here: https://redash.io/help-onpremise/dev/guide.html, which links to both the Docker guide and the "native" guide. Anyway, added the versions to this page as well: https://github.com/getredash/website/commit/d4701991f163d6a6081de3818b91fc9af8218df9.

**Comment by omouse** [comment]
awesome that was fast, thank you! 💯
