### ISSUE TITLE
Mlab Connections

### ISSUE THREAD

**Issue by puneethnarayana** [getredash/redash#1576]
I provided the uri in the prescribed format.

Connection String:
mongodb://<dbuser>:<dbpassword>@ds168-a0.mlab.com:61168,ds161168-a1.mlab.com:168

DBName
<dbname>

ReplicaSet
<rsname>

But got the following error:
command SON([('saslStart', 1), ('mechanism', 'SCRAM-SHA-1'), ('payload', Binary('n,,n=<name>,r=MTk2ODA2MTQ1NTQx', 0)), ('autoAuthorize', 1)]) on namespace admin.$cmd failed: Authentication failed.

Day 1 on redash, any help appreciated.

**Comment by arikfr** [comment]
You need to add to the URL the database name, i.e. : `mongodb://:@ds168-a0.mlab.com:61168,ds161168-a1.mlab.com:168/dbname` (of course dbname should be the actual dbname).

**Comment by puneethnarayana** [comment]
And where would the authentication details go, the username/password or would I need an unauthenticated mlab db to make it work with redash?

**Comment by arikfr** [comment]
Of course not. It's part of the url, I thought you redacted them... anyway it should be:

`mongodb://username:password@ds168-a0.mlab.com:61168,ds161168-a1.mlab.com:168/dbname`
