### ISSUE TITLE
ATSD query_runner implementation

### ISSUE THREAD

**Issue by rodionos** [getredash/redash#1579]
Greetings, 

I'm with the team that develops [Axibase Time Series Database](https://github.com/axibase/atsd-docs/tree/master/api/sql) which supports SQL.

We are thinking of developing and raising a PR with a query_runner implementation for ATSD taking into account ATSD schema specifics.

Would you be open to merging ATSD query runner PR? ATSD is commercial but has a community edition which is free, which puts us in the same class as vertica, oracle and other systems for which you have integrations.

We'll provide code for review as well as ongoing maintenance of the issues raised either directly to us or via redash.

Regards,

Sergei

**Comment by arikfr** [comment]
Hi 👋 

Such a query runner will be more than welcome. Always happy to support additional data sources :-)

You're also welcome to make a pull request to the [website repo](https://github.com/getredash/website), and add your logo there so I can setup a data source page on https://redash.io/integrations/.

**Comment by rodionos** [comment]
That's great, thanks. We'll be back once we have the query_runner ready and tested.

**Comment by arikfr** [comment]
👍 cool. Don't hesitate to reach out if you need help.
