### ISSUE TITLE
Dokku instructions

### ISSUE THREAD

**Issue by kennyg** [getredash/redash#1583]
I attempted to install redash using dokku and the container failed to start. would you mind adding installation instructions to the README.md?

**Comment by arikfr** [comment]
Can you share what steps you took so far and what errors did you get?

**Comment by kennyg** [comment]
I tried pushing to the dokku master that I configured, and hoped the dockerfile would be enough. that didn't seem to work. I noticed there was a Procfile.heroku, I copied to Procfile, added it to the repo, and tried to push again.  it goes through some dokku setup and here's part of the output.

```
-----> Waiting for 10 seconds ...
remote: App container failed to start!!
=====> redash web container output:
       Redash Docker.
       Usage:
       server -- start Redash server (with gunicorn)
       worker -- start Celery worker
       scheduler -- start Celery worker with a beat (scheduler) process
       shell -- open shell
       dev_server -- start Flask development server with debugger and auto reload
       create_db -- create database tables
=====> end redash web container output
To re-dokku.aws-dev.manheim.com:redash
 ! [remote rejected] master -> master (pre-receive hook declined)
```

**Comment by arikfr** [comment]
Can you detail the whole process you did:
1. Clone repo.
2. Make changes -- which ones? Only the Procfile? Please include contents of the Procfile.
3. Push to Dokku? Did you set anything like buildpacks prior to that?

**Comment by kennyg** [comment]
I cloned the repo. The only change was copying Procfile.heroku to Procfile. I git add Procfile and git push dokku master. I didn't set any buildpacks. I saw a tweet where you said you were running in dokku and thought I might try it. Did you have to do anything special? Can you let me know? I'd be happy to send a PR with the details once I get it going.

**Comment by Skeyelab** [comment]
@kennyg any progress?  I'm trying to get this up and running on Heroku

**Comment by leshik** [comment]
Hey,
If anybody is still interested in how to run it on dokku, I've managed it.
Dokku has an option to deploy with dockerfile. So the process is as simple as these steps:
1. Create dokku app as usual
1. Use dokku plugins to set up PostgreSQL and Redis
1. Link these services to your app
1. Execute dokku config on your app and then create REDASH_DATABASE_URL and REDASH_REDIS_URL variables with exact values of DATABASE_URL and REDIS_URL
1. Set DOKKU_PROXY_PORT_MAP to http:80:5000
1. Set other required variables (take them from docker-compose.production.yml)
1. On your local machine create a folder with empty git repo and put there Dockerfile and Procfile as follows, then add your remote and deploy as usual
#### Dockerfile
```
FROM redash/redash:latest
WORKDIR /app
COPY . ./
```
#### Procfile
```
web: server
worker: scheduler
```

Hope this helps!

**Comment by dennypradipta** [comment]
In case someone looking for the newest tutorial to deploy Redash using Dokku, I created a repository containing a step-by-step tutorial to deploy self-hosted Redash to Dokku [https://github.com/dennypradipta/deploy-redash-using-dokku](https://github.com/dennypradipta/deploy-redash-using-dokku) :grinning:

**Comment by susodapop** [comment]
Hey @dennypradipta can we add your tutorial to our documentation repo?

**Comment by dennypradipta** [comment]
Sure thing @susodapop :grinning:
