### ISSUE TITLE
Mongo Datasource connection failing

### ISSUE THREAD

**Issue by SankarMittapally** [getredash/redash#1585]
Hello,

 I was trying to add mongodb to redash and getting below error. Can you help me to fix this.

 Connection Test Failed:
Couldn't reach any hosts in [(u'172.31.5.121', 27017), (u'ip-172-31-24-83', 27017)]. Replica set is configured with internal hostnames or IPs?

Thanks

**Comment by arikfr** [comment]
The error message is quite clear. Did you check that those addresses reachable from your Redash server?

Also the second address looks like a host name. Does it really resolve on your server to an ip?

I'm closing this now. But you're welcome to follow up and if you still feel it's a bug in the Mongo query runner you're welcome to reopen. Just add more information please.

**Comment by SankarMittapally** [comment]
Able to communicate Mongo server on Public IP's from redash server but interval IP's never communicate each other because both are in different series and different locations also. I am not sure how to fix this.

**Comment by SankarMittapally** [comment]
Connection Test Failed:
command SON([('authenticate', 1), ('user', u'test_read'), ('nonce', u'1jdlq123434'), ('key', u'4161504f65fbc75988ea69bc48d0610a')]) failed: auth failed

Getting above error after fixing the DNS resolution issue. I used the admin user as well as normal user.

**Comment by nobukatsu** [comment]
I have same problem.
I updated pymongo 3.2.1 to 3.4.0 but still failed to connection test.
