### ISSUE TITLE
Error on npm run build

### ISSUE THREAD

**Issue by bb78657** [getredash/redash#1589]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

npm build error output shown below:

Hash: a3850fd98e47e640f777
Version: webpack 1.14.0
Time: 1177ms
                               Asset       Size  Chunks             Chunk Names
      vendor.293fdbfe585a51d91217.js   79 bytes    0, 1  [emitted]  vendor
    manifest.03ae6d6c1ad6ee84c69a.js  798 bytes    1, 0  [emitted]  manifest
  vendor.293fdbfe585a51d91217.js.map  285 bytes    0, 1  [emitted]  vendor
manifest.03ae6d6c1ad6ee84c69a.js.map    8.62 kB    1, 0  [emitted]  manifest
                          index.html  735 bytes          [emitted]  

ERROR in ./client/app/index.js
Module build failed: TypeError: Cannot read property 'length' of undefined
at Controller.traverse (/.../redash/node_modules/estraverse/estraverse.js:411:37)
...
at Object.module.exports (/.../redash/node_modules/eslint-loader/index.js:181:3)
Child html-webpack-plugin for "index.html":
        + 3 hidden modules

### Steps to Reproduce

1. git clone https://github.com/getredash/redash.git
2. npm install
3. npm run build

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I used exactly the same steps ~1 week ago and was working then, tried comparing differences in code base to last week and reverted to older code file by file (client code and webpack.config.js) but could not identify source of error.

### Technical details:

* Redash Version: 1.0.0
* Browser/OS: chrome/Ubuntu14.04, python2.7, Node:v5.0.0, npm: 3.3.6
* How did you install Redash: git cloned on 11/02/2017

**Comment by arikfr** [comment]
I have a feeling it is an issue with one of our dependencies. Did you reinstall the node modules since last time?

**Comment by bb78657** [comment]
Yes was a clean node install

**Comment by bb78657** [comment]
The problem was due to a corrupt node packge. I tried on another box with Node v5 and the current master branch builds fine. I reinstalled Node v6 on main box and now builds fine.
