### ISSUE TITLE
Deploying to Google App Engine

### ISSUE THREAD

**Issue by ajbosco** [getredash/redash#1591]
Are there any instructions or suggestions for how to deploy Redash to GAE?

**Comment by rockwotj** [comment]
You can't run this on AppEngine standard. You might be able to run this on [AppEngine Flex](https://cloud.google.com/appengine/docs/flexible/custom-runtimes/build) by modifying the docker files in the repo, but you'd have to make your own VMs for Postgres and Redis

**Comment by arikfr** [comment]
We try to keep issues for actual issues with the project, so I'm closing this. 

I think it will be simpler to deploy Redash on GCE, but if you still pursue deploying Redash on GAE, you're welcome to continue the conversation in [the forum](discuss.redash.io), [Gitter](https://gitter.im/getredash/redash) or [Slack](https://slack.redash.io). Thanks!
