### ISSUE TITLE
Query cannot be saved or set refresh schedule

### ISSUE THREAD

**Issue by khuongthachtcg** [getredash/redash#1593]
### Issue Summary

When I saved queries or set refresh schedule, I received this message:

> It seems like the query has been modified by another user. Please copy/backup your changes and reload this page.

![image](https://cloud.githubusercontent.com/assets/19263342/22875345/c6083c40-f1fd-11e6-8841-81b06bdadeff.png)

### Technical details:

* Redash Version: 0.12.0+b2449
* Browser/OS: Chrome Version 56.0.2924.87 on Windows 10
* How did you install Redash: https://bitnami.com/stack/redash

**Comment by arikfr** [comment]
Not sure about 0.12.0, but this is fixed in 1.0.
