### ISSUE TITLE
 return to the decoding of the parameters in the query by substituting

### ISSUE THREAD

**Issue by lab79** [getredash/redash#1594]
Please return to the decoding of the parameters in the query by substituting:
* Redash v0.12 - ок
* Redash v1.00 - ERR

Example: 
* https://demo.redash.io/queries/3875/source?p_adhoc_filter=0%3D0
* select * from data_sources where {{adhoc_filter}}
* ERR: Error running query: syntax error at or near "0" LINE 3: where 0&#x3D;0 ^

**Comment by arikfr** [comment]
Just use triple quotes (`{{{adhoc_filter}}}`). I'm almost sure this was always the behavior.

**Comment by lab79** [comment]
@btmc, fyi
