### ISSUE TITLE
Installation bootstrap for CentOS

### ISSUE THREAD

**Issue by joaosp** [getredash/redash#1595]
Is there any bootstrap installation for CentOS ?

If not I would be happy to do it, but I'm not sure if redash and all its dependencies would work fine on CentOS 7.x

Can some one point me in the right direction ?

Thanks

**Comment by rockwotj** [comment]
They work fine on CentOS, I have a redash instance on CentOS, but cannot sure bootstrap scripts. For the most part you can start from the ubuntu script and change the `apt-get` commands to `yum` and there are only a few other changes needed.

**Comment by jaiume** [comment]
I need a bootstrap for Centos 7 too

**Comment by vinodpandey** [comment]
For CentOS 6, this should help http://vinodpandey.com/documentation/redash/introduction.html

**Comment by arikfr** [comment]
In the future please use the forum for support questions, as instructed when opening a new issue. Thanks 🙏
