### ISSUE TITLE
Export to CSV or XLS in Dashboard view disabled since 1.0.0+b2720

### ISSUE THREAD

**Issue by dermatou** [getredash/redash#1599]
### Issue Summary

The download to Excel or CSV is disabled in the dashboard view since the latest RC1 release. How can one enable this again? 

### Steps to Reproduce

Go to your favorite dashboard, example: http://demo.redash.io/dashboard/citi-bikes-ny
Click on the 3 points on the right (...) where 3 options are available: 
  - Download as CSV File
  - Download as Excel File
  - View Query
The 2 "download" options are not linked anymore.
If you go to the query itself, the options are working fine

in the HTML, I can read the following:

`<ul class="dropdown-menu pull-right" uib-dropdown-menu="" style="z-index:1000000">
              <li><a ng-disabled="!$ctrl.queryResult.getData()" query-result-link="" target="_self">Download as CSV File</a></li>
              <li><a ng-disabled="!$ctrl.queryResult.getData()" file-type="xlsx" query-result-link="" target="_self">Download as Excel File</a></li>
              <li><a ng-href="queries/1313#1744" ng-show="$ctrl.canViewQuery" href="queries/1313#1744">View Query</a></li>
              <li><a ng-show="$ctrl.dashboard.canEdit()" ng-click="$ctrl.deleteWidget()" class="ng-hide">Remove From Dashboard</a></li>
            </ul>`

### Technical details:

* Redash Version: 1.0.0+b2720
* Browser/OS: tested on Mac, Windows, Firefox and Chrome
* How did you install Redash: self-hosted, issue on online Demo as well

**Comment by arikfr** [comment]
Fixed in 84ca02be09c0e5ba48e81546a1950011022daf19 (part of [v1.0.0-rc.2](https://github.com/getredash/redash/releases/tag/v1.0.0-rc.2)).
