### ISSUE TITLE
When updating dashboard name, the dashboards list won't be updated until refresh of the page

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#16]

**Comment by alonho** [comment]
I think the suggested solution with an event isn't bad. The other options I can think of:
1. Pass a callback into the directive to be fired upon change: on-change="reloadDashboards()".
2. Trigger the modal from javascript and not html and reload the dashboards upon close of the modal.

**Comment by arikfr** [comment]
Any solution for this problem that relies on communication in the view layer will probably lead to maintenance hell.

It's better to have a "single source of truth" and have the views represent its state. When it mutates, mutate the view. Angular makes it easy, as this is its default behavior - you just need to wire things right.

In this case, I would have a dashboards model. This model holds the list of all dashboards, recent dashboards, etc. And it gets notified when you edit/create/delete a dashboard. And for simplicity, there is no need to have an identity map or similar - just notify it, and reload from the whole list(s) from the server.

**Comment by arikfr** [comment]
I ended up using an event :-\ Binding the list in the template to a function on a service isn't straightforward and introduced its own set of issues. In the spirit of "done is better than perfect", just used an event...
