### ISSUE TITLE
Browser hangs up when ~1000 rows of locations are visualized in Map

### ISSUE THREAD

**Issue by SrihariThalla** [getredash/redash#1603]
Hi!

### Issue Summary

Browser hangs up and will respond after, like, 15 seconds for any click or scroll - when about 1000 rows of locations (latitude, longitude) are visualised in Map!

### Steps to Reproduce

1. Execute a query which returns about 1000 rows with latitude and longitude in separate columns. Make sure the locations are nearby and can be clustered.
2. Create a new visualization of Map type and save. You can now notice the behaviour.

![screenshot 2017-02-15 16 09 32](https://cloud.githubusercontent.com/assets/7479937/22971134/bafa47a0-f39a-11e6-8a42-0e36d59b1a77.png)

### Technical details:

* Redash Version: 0.12.0.b2449
* Browser/OS: Chrome 56.0.2924.87 on macOS Sierra 10.12.2
* How did you install Redash: Docker composer

Thanks!

**Comment by pascalopitz** [comment]
![image](https://cloud.githubusercontent.com/assets/271740/23238146/80f7559a-f9b0-11e6-99c2-5d4abbd0dec1.png)

Yep, positively getting this.

**Comment by pascalopitz** [comment]
To follow this up, this is when it tries to group by a property. Removing the grouping draws lots of markers just fine. That said, it's not easy to get to a view where the browser doesn't crash in order to modify the query. Maybe this can be sand boxed somehow to not bring the whole window down?
