### ISSUE TITLE
Dashboards aren't anymore being grouped

### ISSUE THREAD

**Issue by WesleyBatista** [getredash/redash#1609]
Please take a look at these two images:

[Image 1]
![captura de tela 2017-02-17 as 15 42 08](https://cloud.githubusercontent.com/assets/755254/23076474/c92bcaea-f527-11e6-8b69-30fb410c0eba.png)
*version: [v1.0.0-rc.1](https://github.com/getredash/redash/tree/5716da205e19a2c274104573e2c0464433e6ac7a)*

[Image 2]
![captura de tela 2017-02-17 as 16 21 38](https://cloud.githubusercontent.com/assets/755254/23077829/3a88c724-f52d-11e6-93db-8678c922fc91.png)
*version [v1.0.0-rc](https://github.com/getredash/redash/tree/8a622fb7ca696bab745fc77bc761d1fb329e3baf)*

Comparing the two images we can see the problem. We can't anymore group the dashboards in the main menu.

Some things to notice in the first image:

- the "tag" feature only works with 1 word in the left side.
- if we have more than one word in the dashboard name, the last word in the left side will always be missing with the `:`
- even with '-' separating the words it doesn't work

---
Browser: Chrome 56.0.2924.87 (64-bit)
OS: macOS Sierra 
Redash Version: [v1.0.0-rc.1](https://github.com/getredash/redash/releases/tag/v1.0.0-rc.1)

**Comment by arikfr** [comment]
Because we have a dedicated dashboards page (and due to the issues with long lists), the dropdown now shows only the recent dashboards list instead of all the dashboards. Because it's only a subset now, it makes no sense to group it and therefore we no longer do it.

**Comment by arikfr** [comment]
But actually I noticed in your screenshot a different issue -- that it doesn't recognize multiple words prefixes. I'll look into this.

**Comment by simzen85** [comment]
The ability to group dashboard is actually very useful for us (so many dashboards and user needs to navigate quickly, click on a separate "Dashboard" page seems slow)

Is there any way that we can add it back @arikfr ? Thanks
