### ISSUE TITLE
Can't see dropdown-menu that is beyond the window

### ISSUE THREAD

**Issue by sottar** [getredash/redash#1613]
If the number of dashboards is higher than the height of the window, 
it is impossible to scroll, so I cannot display the dashboards exceeding the height of the window.

In bellowing example, I can not see ``` 09.test15 ``` or later.

<img width="621" alt="2017-02-18 14 26 12" src="https://cloud.githubusercontent.com/assets/8223003/23094025/d6018bca-f634-11e6-8aea-e6542fc298ee.png">

I think that we can solve this by implementing ```overflow: auto;``` and  ``` max-height ``` .

**Comment by arikfr** [comment]
This is duplicate of #578 which was fixed on master.
