### ISSUE TITLE
Unselecting last item in selects does not update graph in editor

### ISSUE THREAD

**Issue by deecay** [getredash/redash#1618]
### Issue Summary

Unselecting a just selected yAxis column does not update the graph in chart-editor. Same is true for "Group by".
If you save the visualization with columns, Edit, and then deselect, then the graph updates.

### Steps to Reproduce

1. Go to visualization then chart editor.
2. Select one column for yAxis. The graph updates.
3. Unselect the column you just selected. The graph is not updated.

### Technical details:

* Redash Version: Pulled from head at Feb. 20th
* Browser/OS: Chrome
* How did you install Redash: Docker developper

**Comment by arikfr** [comment]
Thank you for the detailed report!

**Comment by deecay** [comment]
This issue is gone after plotly revisit.

**Comment by RichardLitt** [comment]
Great. Let's close this, for now, and if we see it again, we can reopen this. 

Thank you, @deecay!
