### ISSUE TITLE
Error running query: <type 'exceptions.ImportError'> No module named pyspark.sql

### ISSUE THREAD

**Issue by markokole** [getredash/redash#1631]
Hi! Amazing tool for visualization!
I am focusing on visualizing data with python. I have a package for reading data from MySql in python and visualizing it.

Now I wanted to take a step further - visualizing data from Spark. I created a small pyspark script that imports pyspark.sql.
I am getting this error message: 
**Error running query: <type 'exceptions.ImportError'> No module named pyspark.sql**

I can run the script from CLI from python (which means I have included the $SPARK_HOME/python to PYTHONPATH), but I cannot do it from redash.
Do you have any idea how I can get redash to read the pyspark libraries?
Is it documented anywhere how to add python libs to redash?

Thank you in advance!

**Comment by deecay** [comment]
Hi,

What do you see when you run

```
import os, sys

print sys.executable

print os.getcwd()

print os.environ['PYTHONPATH']

print sys.path
```

Does the result include the path to pyspark.sql? I am guessing that redash PYTHONPATH is different from your CLI PYTHONPATH. If so, add PYTHONPATH variable to your redash setup.

See https://redash.io/help-onpremise/setup/settings-environment-variables.html
PYTHONPATH and other variables can also be set with the way described there.

**Comment by arikfr** [comment]
Closing. You're welcome to reopen with additional details.
