### ISSUE TITLE
Prevent sending data to plotly - Remove the feature or give ability to disable it.

### ISSUE THREAD

**Issue by r-tock** [getredash/redash#1634]
The chart actions contain a button to save and edit a chart on plotly, which sends private data to a remote thirdparty server and prevents us from deploying redash in our company. Even with training people can accidentally click on it not understand the repercussions.

**Comment by arikfr** [comment]
It was removed in 1.0.0-rc.2 (https://github.com/getredash/redash/commit/902fb44782733f0f1e1639d8602fa4cda32651f8). You can either upgrade to this version (although note that it's not 100% stable) or backport this fix to the current version (0.12).

**Comment by r-tock** [comment]
Awesome, any ETA on when rc2 is being cut?

**Comment by arikfr** [comment]
Actually I already have, while it's not updated on GitHub, the upgrade script will pick it up.
