### ISSUE TITLE
Favicon goes missing in Redash v1.0.0-rc.2

### ISSUE THREAD

**Issue by rohanpd** [getredash/redash#1638]
### Issue Summary

The favicon occasionally goes missing in Redash.

### Steps to Reproduce

1. Go to any page in Redash
2. Open a link on that page in a new tab.
3. Favicon is no longer there on the new tab

### Technical details:

* Redash Version: v1.0.0-rc.2
* Browser/OS: Chrome
* How did you install Redash: AMI

**Comment by arikfr** [comment]
Might be fixed by this one: https://github.com/getredash/redash/pull/1649/commits/23cc632d5aa4e61bcef056fe47d167dc1b02c2bb.
