### ISSUE TITLE
Provide pre-built Docker image

### ISSUE THREAD

**Issue by unixwitch** [getredash/redash#1642]
I'm trying to deploy Redash on Docker with Kubernetes, rather than with docker-compose.   Initially I tried to use the [redash/redash](https://hub.docker.com/r/redash/redash/) image on Docker Hub, but that image doesn't match the current Dockerfile (for example, there's no `/app` directory).  It looks like that image hasn't been updated for three months, which is probably why.

Looking at the existing Docker deployment instructions and the `docker-compose.production.yml`, it seems Redash expects the user to build their own Docker image for deployment.  This makes the deployment process quite a bit more complicated than other applications, which typically provide a pre-built Docker image - instead of just changing the Docker tag to upgrade, we have to manually build and push the image to our own repository on every upgrade.

Since the application is configured entirely from environment variables, there seems to be no particular need for users to build it from the codebase; is there any way you could start providing up-to-date pre-built images again?

(Alternatively, if I'm missing something and there are up-to-date images already, could the documentation be updated to include that, for people not using docker-compose?)

**Comment by arikfr** [comment]
I was planning on updating the `redash/redash` Docker image when v1 gets released. But wasn't planning for the release to take so long... :(

If it will be under a tag will it be ok for you (i.e. `redash/redash:1.0.0` or similar)?

**Comment by unixwitch** [comment]
That's fine - actually, a versioned tag is much better than `latest` for Kubernetes as it makes upgrades easier.

**Comment by arikfr** [comment]
👍 will update this issue once it's ready.

Out of curiosity - how you full deployment on K8s looks like? Are you deploying all the components on K8s or using external Postgres/Redis instances?

**Comment by unixwitch** [comment]
We already have high-availability datastore services for Redis, Postgres, MySQL, file storage (GlusterFS), etc. from our pre-Docker infrastructure, so we re-use that for k8s applications and only deploy the application itself on k8s.  Despite the recent work on StatefulSets, I'm not sure trying to run an HA database on Kubernetes is the right way to do things - or at least, I don't think there's any advantage to it...

It would be fairly simple to run the Redis and Postgres containers as part of the Kubernetes pod (like docker-compose does), but then you lose a lot of features: for example you can't do rolling upgrades, or do any kind of scaling beyond one container, because it would try to start two copies of Postgres.

**Comment by arikfr** [comment]
Master branch builds will push to Docker now and when we will have the next release, I will make an easier tag for it.

For now you can use: `1.0.0.b2802`.

I will keep this open until I update `docker-compose.production.yml`.

**Comment by unixwitch** [comment]
Looks good, thanks.  (I've started testing with this image and it seems to work fine.)
