### ISSUE TITLE
Clicking to save a visualisation multiple times will save multiple visualisations

### ISSUE THREAD

**Issue by MichaelJAndy** [getredash/redash#1644]
### Issue Summary

Clicking to save on a visualisation should only save the visualisation once, not many times.

### Steps to Reproduce

1. Create a "New Visualisation" with a chart of some sort
2. Click the "Save" button as many times as you can in quick succession
3. You now have hundreds of charts

### Technical details:

* Redash Version:  1.0.0+b10
* Browser/OS: Chrome OSX

**Comment by alison985** [comment]
I can not reproduce in this Re:Dash 2.0.

**Comment by kravets-levko** [comment]
This issue is fixed in latest Redash versions, so I'm closing it. Feel free to reopen if needed. Thanks!
