### ISSUE TITLE
Access current user id/details from Python data source 

### ISSUE THREAD

**Issue by YurZ** [getredash/redash#1646]
First of all, thanks to the authors and contributors for a very interesting and promising tool.  
### Question:
Is it possible to access current user id/details from Python data source?
I would like to be able to control access to the viewed data at row level without a need of creating and maintaining multiple (in my case about 80) data sources and dashboards. My desired scenario:
    1. Store A logs into their account and accesses dashboard with KPI/Metrics.
    2. Dashboard calls Python data source(s).
    3. Python code loads data from a db table with all stores, identifies current user and filters out all records where store != Store A.
    4. Dashboard is dynamically loaded with entries for Store A only.

Also if there are any other ways to achieve the above, please advise.   

### Technical details:
* Redash Version: 0.12.0

**Comment by voycey** [comment]
Also interested in something along these lines!
