### ISSUE TITLE
Upgrade to latest RestrictedPython

### ISSUE THREAD

**Issue by ehfeng** [getredash/redash#1647]
You can create a set in the Python runner, but you can't actually use the built-in `set` function. @tseaver [merged my PR](https://github.com/zopefoundation/RestrictedPython/pull/11) to whitelist this built-in, would love to see this merged into latest redash.

**Comment by arikfr** [comment]
👍 why is this an issue and not a pull request with the needed change to `requirements.txt`? :)

**Comment by ehfeng** [comment]
good point
