### ISSUE TITLE
Athena data source is not showing

### ISSUE THREAD

**Issue by SqlAdmin** [getredash/redash#1659]
Hi, I have latest Redash in `ubuntu 14.04`, but I couldn't see the `athena data source`.

**Comment by denniskpw** [comment]
Set the environment variable `REDASH_ADDITIONAL_QUERY_RUNNERS` to see Athena as a data source.
e.g.
```
export REDASH_ADDITIONAL_QUERY_RUNNERS="redash.query_runner.athena"
```

**Comment by arikfr** [comment]
To complete @denniskpw's answer, make sure to set the proxy URL as well (see: https://discuss.redash.io/t/support-for-aws-athena/302/21?u=arikfr). Also in the future please use the forum for support questions.
