### ISSUE TITLE
Missing application icon in Google SSO on demo

### ISSUE THREAD

**Issue by rdoursenaud** [getredash/redash#1661]
This is not an issue in redash per se but a misconfiguration in your Google Cloud (or API) Console.

When trying the demo at http://demo.redash.io/ linked in the ```README.md``` using a Google account to connect (as instructed), the authorization screen is showing a broken image:
![20170309t033509](https://cloud.githubusercontent.com/assets/1210367/23733563/f672026a-0479-11e7-9b3f-2e5c0e5767b1.png)

This looks unprofessional and may scare potential testers/customers.

You want to setup a link to a proper logo into the API Manager > Credentials > Oauth consent screen ;)

**Comment by arikfr** [comment]
Should be good now. Thanks 👍

**Comment by rdoursenaud** [comment]
Fix confirmed :)
