### ISSUE TITLE
Stacking percent bar charts showing incorrect percentages

### ISSUE THREAD

**Issue by robations** [getredash/redash#1663]
### Issue Summary

Stacked percent bar charts are mis-calculating percentages.

### Steps to Reproduce

1. Data source with multiple series e.g.

| Site | Uptime | Downtime |
| ---- | ---- | -----|
| ABC.biz | 0.99 | 0.01 |
| DEF.widgets | 1 | 0 |

2. Create a bar chart with stacking = percent and assign data series correctly.

Expected: to see the Y axis range from 0–100%, tooltips to show (say) "Value: 0.99, Relative: 99%"

Actual: Y axis ranges from 0–0.01, tooltips show "Value: 0.99, Relative: 0.01%"

It seems like the values are being converted to a percentage by dividing by 100 instead of multiplying by 100. This worked as expected in v0.12.0.b2449.

### Technical details:

* Redash Version: v1.0.0-rc.2
* Browser/OS: Chrome latest (OSX)
* How did you install Redash: bash install script, I think.

**Comment by rafrombrc** [comment]
We've been seeing this same issue (see https://github.com/mozilla/redash/issues/41), and have it on our short-list roadmap to tackle, I think we should be digging in to it early next week.

**Comment by arikfr** [comment]
Fixed in #1696.
