### ISSUE TITLE
SAML group assignment doesn't seem to work

### ISSUE THREAD

**Issue by unixwitch** [getredash/redash#1668]
According to the documentation, sending a `RedashGroups` attribute should set the user's groups.  However, this doesn't seem to work.  

Adding `pprint` debugging in `saml_auth.py`, I can see the necessary attribute is being sent:

```
[2017-03-13 14:12:58,516][PID:923][INFO][saml2.response] Subject NameID: <?xml version='1.0' encoding='UTF-8'?>
<ns0:NameID xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" NameQualifier="https://login.torchbox.com/idp/shibboleth" SPNameQualifier="https://redash.torchbox.com/">felicity@torchbox.com</ns0:NameID>
{'FirstName': ['Felicity'],
 'LastName': ['Tarnell'],
 'RedashGroups': ['wagtail',
                  'tech',
                  'developers',
                  'drupal',
                  'admin',
                  'sysadmin'],
 'mail': ['felicity@torchbox.com']}
[2017-03-13 14:13:00,362][PID:923][INFO][metrics] method=POST path=/saml/callback endpoint=saml_auth.idp_initiated status=302 content_type=text/html; charset=utf-8 content_length=209 duration=2076.67 query_count=4 query_duration=1527.05
```

However, while the user is logged in correctly, they are not a member of any groups besides `default`.   (I tried pre-creating a new group called `sysadmin`, which didn't make any difference; the `admin` group already exists anyway.)

**Comment by arikfr** [comment]
It's a bug introduced by the move to SQLAlchemy. There should be a call to `session.commit()` after [this line](https://github.com/getredash/redash/blob/master/redash/authentication/saml_auth.py#L102).

Also need to fix [the tests](https://github.com/getredash/redash/blob/master/tests/models/test_users.py#L5-L17) to catch this.

**Comment by idralyuk** [comment]
+1

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
