### ISSUE TITLE
SAML: Don't require signed assertions

### ISSUE THREAD

**Issue by unixwitch** [getredash/redash#1669]
Currently Redash requires signed SAML assertions.  This is mostly legacy functionality, and isn't needed when the response itself is signed.  Most IdPs will not sign assertions by default (requiring special configuration), but will sign the response, as that's what the vast majority of SPs expect. 

In `saml_auth.py`:

```
                'want_assertions_signed': True,
                'want_response_signed': False,
```

This should probably be reversed:

```
                'want_assertions_signed': False,
                'want_response_signed': True,
```

**Comment by arikfr** [comment]
I'm not familiar enough with this, but your explanation makes sense. How about we move this configuration?

**Comment by deed02392** [comment]
@susodapop I suppose this can be closed when the merged commit gets a tagged release?

**Comment by susodapop** [comment]
SGTM

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
