### ISSUE TITLE
Make HTTP/HTTPS scheme configurable

### ISSUE THREAD

**Issue by mmautner** [getredash/redash#1678]
### Issue Summary

Standing up an AWS EC2 instance behind an ELB that handles HTTPS/SSL termination works fine, however the result of using `url_for(...)` directs users to non-HTTPS versions of 

### Steps to Reproduce

1. Follow the [instructions](https://redash.io/help-onpremise/setup/setting-up-redash-instance.html) to create a Redash instance on EC2
2. Create an Elastic Load Balancer in front of the Redash instance
3. Try to login at `https://elb-hostname/login/`--static files embedded on the login page are not loaded due to browser security policy detecting that the page was loaded over HTTPS however non-HTTPS assets are embedded on the page.

I consider this a bug because I expected there to be away to configure the Redash flask app to use HTTPS as it's scheme in generating external URLs using `url_for(...)` or static assets in templates.

The `ENFORCE_HTTPS` setting (which uses [Flask-SSLify](https://github.com/kennethreitz/flask-sslify)) is not adequate in this case, since the EC2 instance is not handling HTTPS requests--the ELB is.

Relevant SO that I found discussing the issue (not specific to Redash): http://stackoverflow.com/a/34802317

### Technical details:

* Redash Version: 0.11.1+b2095
* Browser/OS: N/A
* How did you install Redash: [AWS EC2](https://redash.io/help-onpremise/setup/setting-up-redash-instance.html)

**Comment by arikfr** [comment]
I'm assuming your setup is `client --(https)--> ELB --(http)--> EC2`, in which case you need to add the following header to your nginx configuration:

```
    proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
```

Which will correctly set the forwarded protocol header to be `https` and then Flask will correctly create the URLs (this is the setup I use).

**Comment by arikfr** [comment]
(closing this now, but you're welcome to follow up with questions)

**Comment by mmautner** [comment]
Thanks @arikfr --I'll give that a shot

**Comment by mmautner** [comment]
Confirmed that worked

**Comment by jitendra-koodo** [comment]
> I'm assuming your setup is `client --(https)--> ELB --(http)--> EC2`, in which case you need to add the following header to your nginx configuration:
> 
> ```
>     proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
> ```

where exactly I need to make this change? Any documentation link would be appreciated.  I see nothing inside /opt/redash and tried creating folder named nginx inside that, tried copying conf file there but did not work.

1. Just upgraded V8 to V10
2. Added ELB 
3.  For some reasons, ELB health checks are failing for /login with allowed 200/302/301/404 status.  While instance is publicly accessible.
4. Could this header thing might be the reason?
