### ISSUE TITLE
Edit TextBox not responding in v. 1.0.0 rc2

### ISSUE THREAD

**Issue by dermatou** [getredash/redash#1679]
### Issue Summary

In a dashboard, once created, the edit TextBox is hanging and not working when you try to edit it.
### Steps to Reproduce

1. Create a new dashboard and add the TextBox widget to the dashboard
2. Try to edit, it will open the pop-up, but from there, you are unable to add text, or save or close. You have to click elsewhere on the screen to have the pop up closed

This worked on previous versions.

### Technical details:

* Redash Version: 1.0.0+b2777
* Browser/OS: Firefox and Chrome on MacOS
* How did you install Redash: on self-hosted infrastructre as well as demo version
![screen shot 2017-03-20 at 19 04 22](https://cloud.githubusercontent.com/assets/25765149/24114334/1e325c6c-0da0-11e7-9c2a-f8777636ae9a.png)

**Comment by arikfr** [comment]
Good timing - fixed this earlier today (a033dc45691feb0403d23d883eeaf08f1c168920).
