### ISSUE TITLE
Docker: make number of Gunicorn workers configurable

### ISSUE THREAD

**Issue by unixwitch** [getredash/redash#1681]
Currently the Docker build always starts 4 Gunicorn workers: https://github.com/getredash/redash/blob/master/bin/docker-entrypoint#L21, each of which uses ~85MB RAM (at least here on amd64).  It would be nice if that was configurable using `${REDASH_WORKERS}`.  (Should be trivial to implement as the same functionality is already in `docker-entrypoint` for `scheduler` and `worker` commands.)

**Comment by arikfr** [comment]
👍 you're welcome to submit a pull request with this change.

**Comment by arikfr** [comment]
Implemented in #1871.
