### ISSUE TITLE
Can't edit owned alert

### ISSUE THREAD

**Issue by k2o** [getredash/redash#1683]
### Issue Summary

I can't edit my own alerts. I can create. But after save, I can't edit alert.

### Steps to Reproduce

1. create alert and save.
2. After save, text boxes are disabled and there are no save and delete buttons .

### Technical details:

* Redash Version:1.0.0+b2777
* Browser/OS: OS X, Firefox and Chrome

**Comment by arikfr** [comment]
Thanks!

**Comment by arikfr** [comment]
(fixed and will be part of the next release)
