### ISSUE TITLE
BigQuery permissions error?

### ISSUE THREAD

**Issue by spencerhakim** [getredash/redash#1684]
### Issue Summary

Not sure if this is a Redash or GCE issue. I have a service account on my project with BigQuery Admin permissions, and created the data source in Redash. However, when I click "Test Connection", I get the following:

```
Connection Test Failed:
{ "error": { "errors": [ { "domain": "global", "reason": "accessDenied", "message": "Access Denied: Project PROJECT_ID: The user SERVICE_ACCOUNT@PROJECT_ID.iam.gserviceaccount.com does not have bigquery.jobs.create permission in project PROJECT_ID." } ], "code": 403, "message": "Access Denied: Project PROJECT_ID: The user SERVICE_ACCOUNT@PROJECT_ID.iam.gserviceaccount.com does not have bigquery.jobs.create permission in project PROJECT_ID." } }
```

I've triple-checked the project ID in the data source settings (side note: why isn't this pulled from the JSON file by default?) and it's correct, plus it's correct in the uncensored error message. I've even tried setting the service account to Owner permissions, but it didn't make a difference. Are [these instructions for setting up BigQuery](https://redash.io/help/data-sources/bigquery.html) out of date or incomplete?

### Technical details:

* Redash Version: 1.0.0.b2815
* Browser/OS: Chrome/Mac
* How did you install Redash: Docker

**Comment by arikfr** [comment]
The instructions look correct and I just tested with these settings:

![image](https://cloud.githubusercontent.com/assets/71468/24329340/27ec3d48-120c-11e7-9354-78f6e791eb27.png)

and it worked fine. I would double check Google's IAM console to make sure the permissions were properly applied.

**Comment by spencerhakim** [comment]
They were definitely correct (like I said, I even tried giving it full Owner permissions), making a new service account, delete the data source and adding it again, but I just couldn't get it working. Eventually gave up. But, since it works for you and the instructions are correct, then I guess the problem isn't with Redash, so I'll close this.

**Comment by Dilem-ma** [comment]
Met this this morning. I solved it by giving the worker: JOB USER permission. This is correct because the error is related to jobs.create. Here's a detailed permission form: https://cloud.google.com/bigquery/docs/access-control.

**Comment by KumariTu270** [comment]
I solved it by setting the same json key path in both environment variable and in the program.

**Comment by nabinkhadka** [comment]
@KumariTu270 What are those environment variables?

**Comment by konumashuri** [comment]
Had a same problem here.
And I solved this by delete IAM role member associated with `BigQuery Admin`.
The member name started with `deleted:`.

Then create a service account for BigQuery and create datasource on redash.

Hope this would help someone.
