### ISSUE TITLE
Multiple Redash users with the same email-id

### ISSUE THREAD

**Issue by ShahSunny** [getredash/redash#1694]
- Currently in the Redash code, It is possible to create multiple users with the same email-id, because email is not case insensitive. 
- For example It is possible to create two users like InFo@reDaSh.io and INFO@REDASH.IO, Now when we try to login through Google Auth, Redash gets email id as info@redash.io which matches with none of the emails ( InFo@reDaSh.io and INFO@REDASH.IO ). This issue has been the source of several login failures at our company.

**Comment by arikfr** [comment]
Fixed in #1985.
