### ISSUE TITLE
Queries list page is slow when some queries has large query result

### ISSUE THREAD

**Issue by shimpeko** [getredash/redash#1697]
### Issue Summary

Queries listing page (`/queries`) is slow when some queries has large query result.
Because it execute admin queries which select all columns from query_results for each queries on the list.

### Steps to Reproduce

1. Create query which will return large result_set
2. Execute it
3. Access `/queries?page=1`

### Technical details:

* Redash Version: 1.0.0-rc2
* Browser/OS: Chrome 56
* How did you install Redash: docker-compose (used default docker-compose.yml for testing)

**Comment by arikfr** [comment]
Thanks! This also uncovers a nasty N+1 queries issue there.
