### ISSUE TITLE
Cannot update Alert Destinations

### ISSUE THREAD

**Issue by JoshKeegan** [getredash/redash#1706]
### Issue Summary

Once an Alert Destination has been created, it can't be updated.
Tested with Type email.

### Steps to Reproduce

1. Go Settings > Alert Destinations
2. Click "New Alert Destination"
3. Change Type to "Email" & fill out other fields
4. Save
5. Change a field (e.g. update email address).
6. Save (will be confirmed with green popup in bottom right).
7. Click "Alert Destinations" tab again
8. Select your new alert destination
9. View details, which won't have updated.

### Technical details:

* Redash Version: 1.0.1+b2833
* Browser/OS: Chrome & Firefox, Windows 10 (client, server is Debian).
* How did you install Redash: Upgrading from previous release (v0.12.x).

**Comment by ssandeep** [comment]
I have faced this issue as well. Let me see if I can fix it.

**Comment by arikfr** [comment]
Fixed in #1847.
