### ISSUE TITLE
slack bot is not working

### ISSUE THREAD

**Issue by yukiyan** [getredash/redash#1708]
### Issue Summary
When I update to 1.0.1, slack bot is not working. Should I downgrade it ?

![image](https://cloud.githubusercontent.com/assets/7304122/24647353/86b9117a-195a-11e7-8494-3d0078bfe51d.png)

### Steps to Reproduce

1. Create an AWS Instance following [this step](https://redash.io/help-onpremise/setup/setting-up-redash-instance.html).
1. Update redash version following [this step](https://github.com/getredash/redash/releases/tag/v1.0.1)
1. Add slack bot followng [this step](https://redash.io/slack)

### Technical details:

* Redash Version: /opt/redash/redash.1.0.1.b2833
* Browser/OS:  ubuntu
* How did you install Redash: I use AMI and update it.

My /opt/redash/.env file is bellow.

```
export REDASH_LOG_LEVEL="INFO"
export REDASH_REDIS_URL=redis://localhost:6379/0
export REDASH_DATABASE_URL="postgresql:///redash"
export REDASH_COOKIE_SECRET=<secret>
export REDASH_GOOGLE_CLIENT_ID=<secret>
export REDASH_GOOGLE_CLIENT_SECRET=<secret>
export REDASH_PASSWORD_LOGIN_ENABLED=false
```

**Comment by arikfr** [comment]
Seems to happen only with charts and might be due to some ES6 APIs we don't polyfill (as they are supported in modern browsers), which are not supported by PhantomJS.

**Comment by 44px** [comment]
Maybe [babel-polyfill](https://babeljs.io/docs/usage/polyfill/) can help? It adds all polyfills needed to use ES6 API in old browsers.

**Comment by arikfr** [comment]
I ended up including the one polyfill we needed (`ArrayBuffer.asView`) instead of all of them to keep package size smaller.

Did few more fixes on the way, so renders should look better.
