### ISSUE TITLE
Bug: query page freezes during frontend results processing

### ISSUE THREAD

**Issue by savanto** [getredash/redash#1711]
### Issue Summary

Results with a large number of rows freeze the page while some kind of frontend processing takes place. The freeze is most noticeable on results with several thousand rows (**very roughly** 5-10 seconds per 1000 rows) during which the page is completely unresponsive, and even occasionally results in "unresponsive script: kill/wait?" messages from the browser. It is less of an issue but still noticeable as a momentary lock-up for results of several hundred rows.

### Steps to Reproduce

1. Create new query that will return > 1000 rows
2. Execute query
3. The freeze appears to happen only after results are returned from the database, during the render phase, or during some post-processing step
4. The freeze happens even on queries that have already run recently and that return cached results
5. The freeze happens on various interactions with the page, eg. showing/hiding the source

Example of bug manifestation on demo site: https://demo.redash.io/queries/4291

This was not present on v1.0.0-rc1 (our previous version). Queries returning many thousands of rows displayed near-instantaneously.

### Technical details:

* Redash Version: v1.0.1 (previously v1.0.0-rc1 with no issues)
* Browser/OS:
  - Chromium v56.0.2924.76, Ubuntu 16.04
  - Firefox v52.0.2, Ubuntu 16.04
  - Chrome, Ubuntu 14.04
  - Chrome, OSX 
* How did you install Redash:
  - Installed via modified provisioning script on Ubuntu 14.04
  - But also reproduced on demo site installation

I can provide CPU/memory profiles of the page taken with Chromium developer tools, Redash logs, more testing, etc., if any of that would help!

**Comment by arikfr** [comment]
Thank you for the detailed report!

It's definitely a regression in this version.

**Comment by arikfr** [comment]
For those who have been waiting for a fix for this, it's been release. Just run `sudo bin/upgrade` from `/opt/redash/current` (assuming you're on `1.0.1`).

**Comment by arikfr** [comment]
Please wait with upgrading to 1.0.2 because of #1726 :( I will release another update today.

**Comment by arikfr** [comment]
Safe to upgrade again 👍
