### ISSUE TITLE
Assets not in client/dist

### ISSUE THREAD

**Issue by yanenok** [getredash/redash#1719]
### Issue Summary

Default static path is client/dist/, but the assets are not exported from client/app/assets/ resulting in 404 error.

### Technical details:

* Redash Version: v1.0.1
* How did you install Redash: upgrade script

**Comment by arikfr** [comment]
Did you apply the changes to the `.env` file described in the release notes? 
https://github.com/getredash/redash/releases/tag/v1.0.1

**Comment by yanenok** [comment]
Yes, and it's also reproduced at demo.redash.io.

**Comment by yanenok** [comment]
After trying to reproduce this I no longer see errors relating to images (although following a link from source code still results in 404). I do see fonts-related errors on login page though.

**Comment by arikfr** [comment]
Thanks for reporting!
