### ISSUE TITLE
Scheduled queries continue to run 1h+ are executed duplicatively

### ISSUE THREAD

**Issue by shimpeko** [getredash/redash#1724]
### Issue Summary

I found my scheduled queries are executed duplicatively.
Those queries are relatively long running ones which takes more than 1 hour.

After some investigation, I came to think `CELERY_TASK_RESULT_EXPIRES` is the cause.
`CELERY_TASK_RESULT_EXPIRES` is now set as `3600` sec which is shorter than default value 1 day.
This means an `AsyncResult` is deleted after 1 hour it created, and I *THINK* it includes an `AsyncResult` with `STARTED`  state, or `AsyncResult` with running query in another word.

In scheduler log, I found a task was cancelled after 1 hour it had been started and then new task was created after the cancellation. While the query related to the cancelled task is still running. This cause duplicated queries running on our DB.

This may be not a bug, but I'm not sure this behavior is expected. And also IMO 1 hour is too short for default value.

#### Scheduler log
```
2017/04/17 20:00 Created: ec87fac9-cae6-4070-b1ba-2b5ba8cd61b3
"{\"username\": \"Scheduled\", \"retries\": 0, \"started_at\": 1492459209.55685, \"task_id\": \"ec87fac9-cae6-4070-b1ba-2b5ba8cd61b3\", \"created_at\": 1492459209.53251, \"updated_at\": 1492494826.952597, \"state\": \"finished\", \"query_id\": 1732, \"run_time\": 35617.35370802879, \"error\": null, \"scheduled\": true, \"scheduled_retries\": 0, \"data_source_id\": 13, \"query_hash\": \"d6c7c4a76f63f391c8c82a30c409687f\"}"

2017/04/17 20:00 Started: ec87fac9-cae6-4070-b1ba-2b5ba8cd61b3

2017/04/17 21:00 [2017-04-17 21:00:52,010: INFO/Worker-2910] In progress tracker for d6c7c4a76f63f391c8c82a30c409687f is no longer enqueued, cancelling (task: ec87fac9-cae6-4070-b1ba-2b5ba8cd61b3).

2017/04/17 21:01 Created: 5086eefe-2594-4b3a-8e64-7a2231aa73d1
"{\"username\": \"Scheduled\", \"retries\": 0, \"started_at\": 1492462961.313905, \"task_id\": \"5086eefe-2594-4b3a-8e64-7a2231aa73d1\", \"created_at\": 1492462871.348128, \"updated_at\": 1492474428.593589, \"state\": \"failed\", \"query_id\": 1732, \"run_time\": 11467.265868902206, \"error\": \"Query (5529638) cancelled on user's request\\n\", \"scheduled\": true, \"scheduled_retries\": 0, \"data_source_id\": 13, \"query_hash\": \"d6c7c4a76f63f391c8c82a30c409687f\"}"

2017/04/17 21:01 Started: 5086eefe-2594-4b3a-8e64-7a2231aa73d1

2017/04/17 22:05 [2017-04-17 22:05:52,014: INFO/Worker-2926] In progress tracker for d6c7c4a76f63f391c8c82a30c409687f is no longer enqueued, cancelling (task: 5086eefe-2594-4b3a-8e64-7a2231aa73d1).

2017/04/17 22:06 Created: ea4e3e9c-5f0f-41c8-b201-3af5afffc549
"{\"username\": \"Scheduled\", \"retries\": 0, \"started_at\": 1492474497.635736, \"task_id\": \"ea4e3e9c-5f0f-41c8-b201-3af5afffc549\", \"created_at\": 1492466773.140668, \"updated_at\": 1492479689.698292, \"state\": \"failed\", \"query_id\": 1732, \"run_time\": 5192.048290967941, \"error\": \"Query (5536396) cancelled on user's request\\n\", \"scheduled\": true, \"scheduled_retries\": 0, \"data_source_id\": 13, \"query_hash\": \"d6c7c4a76f63f391c8c82a30c409687f\"}"
```

#### CELERY_TASK_RESULT_EXPIRES setting
https://github.com/getredash/redash/blob/master/redash/settings.py#L75

Note:
I think the `JOB_EXPIRY_TIME` setting, which now set as `3600 * 6`, may also cause duplicated query execution and inconsistent state between `QueryTask` and `QueryTaskTracker` if we have queries continues to run for more than 6 hours (yes we have...).

### Steps to Reproduce

1. Create scheduled query which continues to run 1h+.
2. Confirm your scheduler log or DB's log.

### Technical details:

* Redash Version: 1.0.1
* Browser/OS: Chrome
* How did you install Redash: Docker

**Comment by arikfr** [comment]
76470b9f094dd93ad549629eb9eae7ac65f7ec52 should partially help here: because we were removing locks on queries with status of PENDING, once the the celery job object was expired we were removing the lock and the scheduler was scheduling the query again.

Also #1774 will help, as it tracks when the query was last executed - including unfinished or errored executions, it means that if the query is still running it won't be scheduled again (unless its refresh rate < runtime).

**Comment by shimpeko** [comment]
https://github.com/getredash/redash/commit/76470b9f094dd93ad549629eb9eae7ac65f7ec52 seems good!

**Comment by shimpeko** [comment]
With https://github.com/getredash/redash/issues/1724#issuecomment-302383130 and https://github.com/getredash/redash/pull/1736 this issue should be solved.
