### ISSUE TITLE
Unable to Sort with Column Headers

### ISSUE THREAD

**Issue by RobinDarrah** [getredash/redash#1726]
### Issue Summary

Unable to sort tables by clicking on column headers. Worked on version 1.0.1. 
Can be seen on the demo: [Example Query](https://demo.redash.io/queries/4220#table)

### Technical details:

* Redash Version: 1.0.2+b2849
* Browser/OS: Chrome or Firefox / Windows
* How did you install Redash: ami on t2.medium in early 2016, updated by script since then.

**Comment by arikfr** [comment]
OK, I see the issue. Stupid overlook on my part :( will release another fix later today.

**Comment by arikfr** [comment]
Released 1.0.3 with a fix for this. Sorry for the trouble.
