### ISSUE TITLE
change  http://xxx.com/login  to http://xxx.com/redash/login

### ISSUE THREAD

**Issue by guzhenping** [getredash/redash#1729]
Hi, l meet a trouble problem.

Beause of some things, l must use the abstract word "redash" in the end of my domains , like this http://xxx.com/redash/.  

Could you give me some advice？

**Comment by arikfr** [comment]
We keep the issue tracker for actionable (confirmed) bug reports and feature requests. Please use the _Support_ category in our [discussion forum](https://discuss.redash.io/c/support) for other questions.

Question about putting Redash in a "sub folder" was already asked on the forum with some advice on how to achieve this (although I recommend not doing it, as it will cause other issues).
