### ISSUE TITLE
Error rendering results within < >

### ISSUE THREAD

**Issue by dfrnswrth** [getredash/redash#1731]
### Issue Summary

The results view interprets results wrapped in `<>` as angular tags.

Related: query results within `<>` containing `@` cause a javascript error:
```
Error: [$sanitize:badparse] The sanitizer was unable to parse the following block of html: <@>
http://errors.angularjs.org/1.2.18/$sanitize/badparse?p0=%3C%40%3E
    at plugins.c6ff35c7.js:16
    at a (plugins.c6ff35c7.js:19)
    at plugins.c6ff35c7.js:19
    at s (plugins.c6ff35c7.js:51)
    at Object.fn (plugins.c6ff35c7.js:51)
    at u.$digest (plugins.c6ff35c7.js:18)
    at u.$apply (plugins.c6ff35c7.js:18)
    at l (plugins.c6ff35c7.js:17)
    at v (plugins.c6ff35c7.js:17)
    at XMLHttpRequest.w.onreadystatechange (plugins.c6ff35c7.js:17)
```

This is a problem when querying data containing email addresses:
```
<a@b.c>
```

### Steps to Reproduce

* Postgres / Redshift:
```sql
-- no text rendered:
select '<a>';

-- no text rendered and parsing error:
select '<@>';
```

* MySQL
In MySQL results, if you do not use `as`, the text is rendered as a colun header, and no error occurs. To reproduce in MySQL:
```sql
# no text rendered:
select '<a>' as display_err;

# no text rendered and parsing error:
select '<@>' as parse_err;
```

### Technical details:

* Redash Version: v0.12.0+b3e5e4f5
* Browser/OS:
  * Chrome 57
  * Firefox 52
* How did you install Redash: we use the SAAS version.

Please let me know if I can supply any additional info or hep in any way. We love Redash!

**Comment by tonyjiangh** [comment]
Just took a little check
* only `'<a>'` display error problem exists on [Redash 3.0.0+b3134](http://demo.redash.io/queries/6235/source) (postgresql)
* `select '<a>' as display_err, '<@>' as parse_err;` display everything OK on v4.0.0 (the newest master branch & postgresql)

![image](https://user-images.githubusercontent.com/16881036/35709943-3f116664-07f8-11e8-89ad-7d8a923b0ae1.png)
