### ISSUE TITLE
Wrong data display

### ISSUE THREAD

**Issue by lakhan000** [getredash/redash#1733]
Welcome to Redash's GitHub repo! 👋🎉

### Issue Summary

The text string displayed on redash is different from which has been saved in database

1. Saved the data as 'se' which has datatype varchar in psql database 
2. Then fetch data from redash, it will show it as HE instead of se

### Technical details:

* Redash Version: 1.0.1+b2833
* Browser/OS: Chrome Version 52.0.2743.116 (64-bit)

**Comment by arikfr** [comment]
Redash does very little to the data and strings are displayed as is.

Can you give more details on:
1. How you query looks like?
2. How the row in the database look like?
3. Screenshot + CSV output of the result in Redash?

**Comment by arikfr** [comment]
Closing for unresponsiveness. You're welcome to reopen with more details.
