### ISSUE TITLE
i want to ask something about config.devServer.host

### ISSUE THREAD

**Issue by oyosc** [getredash/redash#1734]
in the webpack.config.js, i set config.devServer.host= '0.0.0.0',but when i open the remote ip + port:8080,it occurs Invalid Host header; please tell me what happen? and what should i do?

**Comment by arikfr** [comment]
You might want to check your network setup to make sure you're getting to your webserver via the external IP. Without more details, I have no idea what happened, but this seems to be an issue with Webpack, so you might have better luck with their support channels.
