### ISSUE TITLE
If website adopt saml authentication, the user can't logout.

### ISSUE THREAD

**Issue by guzhenping** [getredash/redash#1735]
Recently, l studied redash, because my company used redash to query data.  And l found a bug.

If website only adopt saml authentication, the user can't logout. It should be redirect saml authentication page.

So, l read the source code. The logout function was:
```
@routes.route(org_scoped_rule('/logout'))

def logout(org_slug=None):

    logout_user()

    return redirect(get_login_url(next=None))
```
In this case, Redash would redirect the root url, "/", because of "next=None".

l think the function logout_user() don't work.

**Comment by guzhenping** [comment]
In the last days, l found that saml need to use its own logout function, like this : [](http://pythonhosted.org/python-saml/library/_modules/saml2/logout_response.html)
 
but redash don't have this function.

**Comment by guzhenping** [comment]
The solution is that redash send logout signal to your email service provider, like azure office 365.

If you are using  saml by  azure 365 email, you can change the source code to send logout signal, like this:

```python

@routes.route(org_scoped_rule('/logout'))
def logout(org_slug=None):
    logout_user()     # it can only clear the local session and cookie , but not remote login information
    return redirect('https://login.partner.microsoftonline.cn/logout.srf')

```

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
