### ISSUE TITLE
Refresh when changing (global) parameters

### ISSUE THREAD

**Issue by vanillechai** [getredash/redash#1737]
When I change a parameter (at Dashboard Level), I have to click "refresh" before seeing any changes. That's not very intuitive (everyone here stumbled over this).
Is it possible to refresh the Dashboard queries with the new parameter by hitting "Enter" in the input field or simply by leaving it (focus lost)? Did I miss something? Wrong browser?

**Comment by arikfr** [comment]
You didn't miss anything. Adding support for `Enter` is a good idea.

**Comment by seenivasanp** [comment]
@vanillechai This pull will help your use case.https://github.com/getredash/redash/pull/1919

**Comment by arikfr** [comment]
Closing in favor of #2316.
