### ISSUE TITLE
First Time Login: Missing Credentials?

### ISSUE THREAD

**Issue by Raz12** [getredash/redash#1739]
### Issue Summary

Hi, I installed Re:dash on Heroku with this one click deployment:
https://github.com/mtsmfm/redash

Maybe I missed something but I what are the credentials for the first time login?

Do I need to create them?

Thanks,
Raz

**Comment by arikfr** [comment]
I have no idea, you might have better luck opening an issue on that repo or just reviewing what it does.

Note that the version in that repo is 8 months old -- we had 3 large releases since then. Also it will probably never update...
