### ISSUE TITLE
Issue with grouping

### ISSUE THREAD

**Issue by indupulikkot** [getredash/redash#1740]
Would like to know if 2 grouping is possible in Redash. I am selecting count as Yaxis , Status as Group by and Month in X axis. I need one more groupingn which is a sub groupin for Month

So basically

1) For Jan ,Category 1,Category2,Category 3 ,for Feb same.
For each of these scetions count for each status (serieS).

Please let me know if this is possible

**Comment by arikfr** [comment]
https://discuss.redash.io/t/issue-with-grouping/607
