### ISSUE TITLE
Issue with grouping . Data splitting to Pivot

### ISSUE THREAD

**Issue by indupulikkot** [getredash/redash#1741]
### Issue Summary
I am pulling data from Elasticsearch and I need to do 2 aggregations. First aggregation is Day/Month . After Day aggregation, I am aggrgating by category . So for each Day for each category I want the count. Problem is that If I do 2 aggregations, category is splitting to pivot format to columns,. Ideally it shluld come under a field called Count, along with Date and Category.
This is the output
### Steps to Reproduce
![image](https://cloud.githubusercontent.com/assets/27469731/25515379/c6e21b2a-2c01-11e7-8a1b-140f6401cce4.png)

Code is here.
{
    "index": "index1",
    "aggs":  @{
         @"Month": {
            "date_histogram": {
                "field": "date",
                "interval": "month",
                "format": "MMM"
            },
            "aggs": {
                "Category": {
                    "terms": {
                        "field": "category"
                    }
                }
            }
        }
    }
}

**Expected output:**
![image](https://cloud.githubusercontent.com/assets/27469731/25515434/2d0f89c8-2c02-11e7-9db2-b0ecfce8eb11.png)

**Comment by arikfr** [comment]
https://discuss.redash.io/t/issue-with-grouping-data-splitting-to-pivot/608
