### ISSUE TITLE
problem canceling running queries

### ISSUE THREAD

**Issue by DanielBrCi** [getredash/redash#1743]
Hello, Redash's GitHub team

I'm having a problem with my queries.
I have a series of queries stucked in my queries queue and it seems impossible to cancel them.
There's a cancel button for the queries in progress, but it doesn't do anything.

I've read in a Redash help center that you can do something called sudo (https://redash.io/help-onpremise/maintenance/ongoing-maintenance-and-basic-operations.html)

But I'm on the same level as a child when it comes to programming. I get that I can somehow access the Redash admin to foce stop the running queries, I just don't really understand how.

**Comment by oyosc** [comment]
i want to know do you have solved it? i think i have the same issue;when i excute, it occurs Query in queue and don't return result, and i can't cancel it .

**Comment by DanielBrCi** [comment]
@oyosc , luckly I have a friend who's an expert on these matters. I couldn't really explain what the solution, was, but basically he guided me on how to open the terminal and manually stop the queries. But i was basically copy and pasting his instructions. What I can tell you is you've got to be able to "edit" the redash page. Otherwise, the administrator must give you permission to do so before you can force shut the queries from your site

**Comment by oyosc** [comment]
thanks,but the role is administrator,when i run the server and excute ,it occurs Query in queue… , i can't cancel it,i sure the data source is correct,and i can get schema,so whether you can help me solve it?
![image](https://cloud.githubusercontent.com/assets/13896491/25646890/753ffe26-2fef-11e7-94e9-12b7b0a172a4.png)

**Comment by oyosc** [comment]
as you can see, it just send the request to the backend one by one,and no result return

**Comment by ileibovich** [comment]
Hi, I am experiencing the same issue.

**Comment by oyosc** [comment]
Celery: ./bin/run celery worker --app=redash.worker --beat -Qscheduled_queries,queries,celery -c2
you have to excute it!

**Comment by ileibovich** [comment]
Run it where? On what machine? @oyosc

**Comment by jolly7481** [comment]
hi! does anyone already resolved this issue? also have the same problem. i'm running redash on docker how can i clear queries queue?

**Comment by killerdejavu** [comment]
`sudo supervisorctl stop redash_celery`
`sudo supervisorctl start redash_celery`
 This solved the problem for me

**Comment by johnstoecker** [comment]
I had to run the above steps from @killerdejavu twice to clear the queries 👍

**Comment by arikfr** [comment]
Closing this now as this is a very old issue and a lot has changed since.
