### ISSUE TITLE
anyone has the bootstrap script on centos 6.5?

### ISSUE THREAD

**Issue by wikithink** [getredash/redash#1745]
How to install Redash on CentOS 6.5? thanks

**Comment by vinodpandey** [comment]
This should help http://vinodpandey.com/documentation/redash/introduction.html

**Comment by arikfr** [comment]
Thanks, @vinodpandey.

@wikithink: In the future please use the [forum](discuss.redash.io) for support questions, as instructed when opening a new issue. Thanks :pray:
