### ISSUE TITLE
Parameters with the same name cause a conflict in dashboards

### ISSUE THREAD

**Issue by caseycrogers** [getredash/redash#1750]
### Issue Summary

If you have a dashboard that references two or more queries that each have a non-global parameter with the same name one parameter's value will overwrite the others'.

### Steps to Reproduce

1. Create Query1 and Query2 each with a non-global template named "a_parameter".
2. Set "a_parameter" to 1 in Query1 and 2 in Query2.
3. Add both queries as tables to the same dashboard.
One query's "a_parameter" value will overwrite the other query's.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
I consider this to be a bug. I expect that, if a parameter is set to non-local, it will not interact with any other parameter in a given dashboard.

**Comment by arikfr** [comment]
By template you mean parameter?

**Comment by caseycrogers** [comment]
Yes-my bad-parameter. Updated initial issue.
