### ISSUE TITLE
api_key should open a dialog and not browser alert

### ISSUE THREAD

**Issue by atharvai** [getredash/redash#1752]
### Issue Summary

clicking "Show API Key" in a query returns a browser alert with the key. This means it can't be selected and copied. Tested this in Chrome and redash version `0.12.0+b2354`

This should open a modal similar to "Manage Permissions" modal to allow the key to be selected and copied. Alternatively it could be copied straight to clipboard if allowed by browser.

### Steps to Reproduce

1. Open Query and show source
1. click on elipses and select "Show API key"
1. browser alert box is raised.

### Technical details:

* Redash Version: 0.12.0+b2354
* Browser/OS:Chrome 57.0.2987.133 (64-bit) Windows 10

**Comment by arikfr** [comment]
Implemented in #1771.
