### ISSUE TITLE
Releases for docker images

### ISSUE THREAD

**Issue by alexpekurovsky** [getredash/redash#1755]
Hi, whenever new version of Redash is released, it would be great if corresponding tag is set on DockerHub. Currently it's quite hard to understand which tag corresponds with release and which tags are just development builds.

Thank you.

**Comment by arikfr** [comment]
There is the `latest` tag, but you're right that we should have a proper tag for the final build of each version. Will do starting from the next release.

**Comment by alexpekurovsky** [comment]
Great, thanks
