### ISSUE TITLE
Refresh schedule time calculation are wrong when the server's timezone is not set to UTC

### ISSUE THREAD

**Issue by ysk24ok** [getredash/redash#1757]
### Issue Summary

Refresh schedule does not run on the designated time.
I intended to run on the time of my timezone, but the refresh somehow run on the time of UTC.

* Redash Version: v1.0.3+b2850
* Browser/OS: Chrome 58.0.3029.96 (64-bit) / OS X 10.11.6

### Issue Details

The time configuration of my server is as follows. The timezone is JST (=Asia/Tokyo).

```sh
$ date
Tue May  9 13:54:07 JST 2017
```

When I set the refresh schedule of a query with '9:00' (intended to run on 9:00 at Asia/Tokyo),
the time is saved as follows.

```sql
redash=> select schedule from queries where id = 28;
 schedule
----------
 0:00
(1 row)
```

This seems to make sense, '9:00' I set is converted to UTC and saved in this column.

Although the time saved in the column is UTC, 
it is expected the refresh run on the time of Asia/Tokyo
(I mean the refresh will run on 9:00, not 0:00).
However, the refresh does not run on 9:00. Somehow it runs on 0:00.
That means if I'm going to run on 9:00 of Asia/Tokyo, I have to set 18:00 from Web UI.

First I think this is due to the timezone setting of celery, 
so I tried fixing https://github.com/getredash/redash/blob/v1.0.3/redash/worker.py#L48
from `CELERY_TIMEZONE='UTC'` to `CELERY_TIMEZONE='Asia/Tokyo'`
and restart celery worker, but this didn't fix the problem
(I confirmed the celery timezone changed to Asia/Tokyo
 because `/opt/redash/logs/celery_error.log` says
 `[2017-05-09 13:44:14,197: WARNING/Beat] Reset: Timezone changed from 'JST' to 'Asia/Tokyo'`).

### Steps to Reproduce

If you have a server whose timezone is not UTC,

1. set the refresh schedule (e.x. 9:00) of a query 
2. confirm the refresh properly run on the time in your timezone (maybe not... it runs on the time of UTC)

### Technical details:

* Redash Version: v1.0.3+b2850
* Browser/OS: Chrome 58.0.3029.96 (64-bit) / OS X 10.11.6
* How did you install Redash: from source, updated from v1.0.1

**Comment by arikfr** [comment]
The code currently assumes the server is using UTC as its timezone. If it doesn't things will fail as you describe.

We should probably fix this at some point, but it's easier if you just change your server's configuration.

**Comment by ysk24ok** [comment]
Thank you for the reply. I will try changing the server's timezone.
