### ISSUE TITLE
Remove markdown filter by environment variable or option

### ISSUE THREAD

**Issue by shohu** [getredash/redash#1758]
re:dash 1.X

It seems that javascript of TextBox Widget does not work due to the effect of markdown filter.

https://discuss.redash.io/t/i-cant-use-javascript-in-text-box/637/2

Please remove markdown filter by environment variable or option.
Behavior was variously restricted, it became difficult to use redash very much.

**Comment by arikfr** [comment]
The purpose of the text box widget is to show text, hence the markdown filter. If you would like to implement this configuration option, you're welcome to do so and make a pull request. 

As I prefer not to keep around issues with no actionable value, I'm closing this.
