### ISSUE TITLE
SAML Setup not successful 

### ISSUE THREAD

**Issue by vinothkumarsi** [getredash/redash#1761]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by vinothkumarsi** [comment]
We are facing issues in set up in saml we have followed all steps as mentioned in the document. It will be great if you share the sample metadata file. We are facing this issue in the log file. "return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/redash/redash.1.0.1.b2833/redash/authentication/saml_auth.py", line 93, in idp_initiated
    n**ame = "%s %s" % (authn_response.ava['FirstName'][0], authn_response.ava['LastName'][0])
KeyError: 'FirstName'**
[2017-05-04 07:10:55,676][PID:11793][ERROR][redash] Exception on /saml/callback [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    respo". Please find attached document  for your reference

**Comment by pl0th** [comment]
Hi vinothkumarsi,
please ensure that you added the 'FirstName' and 'LastName' claim? Which SAML idp are you using?

**Comment by arikfr** [comment]
Please don't use GitHub issues for support questions, this is what the forum is for.

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
