### ISSUE TITLE
PostgreSQL queries returning a tsrange fail

### ISSUE THREAD

**Issue by wichert** [getredash/redash#1764]
### Issue Summary

Running a query which includes a tsrange column fail with a JSON error like this:

```
DateTimeRange(datetime.datetime(2016, 8, 25, 15, 21, 45, 760521), datetime.datetime(2016, 10, 14, 5, 56, 52, 452297), '[)') is not JSON serializable
```

### Steps to Reproduce

1. Create a table with a tsrange column
2. Insert some data into it
3. Create a `SELECT * FROM table` query
4. Run the query

This is turning out to be confusing for our users - I'm getting regular complaints about queries failing with this error because some of our tables have range columns.

### Technical details:

* Redash Version: 1.0.1+b2845
* Browser/OS: Linux
* How did you install Redash: Docker image

**Comment by arikfr** [comment]
We need to implement a custom JSON encoder, as we did for MongoDB and other data sources, that will properly handle this class type.
