### ISSUE TITLE
Users with view only access to the data source are unable to view query results/dashboards

### ISSUE THREAD

**Issue by narsariamanu** [getredash/redash#1784]
### Issue Summary

For the group of users having view only access to the database, they are no longer able to run queries and view results. In versions before v1.0, it was possible to view existing queries without authorised to write queries

### Steps to Reproduce

1. Assign View Only Access to a Datasource for a particular group of users.
2. Log in as a user in that group and try to run any of the existing queries or view the dashboard for that data source. It shows unauthorised. Screenshot attached below/

The expected behaviour being the users with view only access can see the data by running the queries that exist on the platform, but the cannot create a new query.

### Technical details:

* Redash Version: 1.0.3+b2850 (Upgraded from 0.12)
* Browser/OS: Chrome, Mac
* How did you install Redash: Install 0.12 using the provisioning script long time back. Upgraded using the new upgrade script that has been added to the platform.

![screen shot 2017-05-23 at 12 09 39 pm copy](https://cloud.githubusercontent.com/assets/6467478/26342048/1d3a59cc-3fb4-11e7-9447-709f6314de03.jpg)
![screen shot 2017-05-23 at 12 09 50 pm copy](https://cloud.githubusercontent.com/assets/6467478/26342049/1d3abd90-3fb4-11e7-803b-3e710278e5de.jpg)

**Comment by ZumZoom** [comment]
See the same behaviour. It is related to template resolving in queries. Queries without templates run fine, as usual.

**Comment by alexpekurovsky** [comment]
Basically need to review all read-only way. I can understand current behavior. When you don't have any templates - readonly user get results of previous run. User is not running, he get snapshot of results. When you do have templates - user is required to run query. Query may be heavy, may delete things, may do any damage to database. So here comes moral question - should readonly users be able to run queries?

We workarounded it in another way - we create two datasources for each database we need - with full-access DB user and read-only DB user. We grant read-only Redash user Full Access on DataSource with read-only DB user.

**Comment by narsariamanu** [comment]
@alexpekurovsky Even when we don't have any templates, the read-only user will not be able to refresh queries because that leads to running the query again by the logic. 

We have also linked the database with read-only access to redash, but the users with read-only access should be able to run read queries via redash which is the expected behaviour according to us.

**Comment by goodwill** [comment]
This is seriously a very bad issue, I want to restrict my data view for customer and this basically makes it impossible

**Comment by RichardLitt** [comment]
@goodwill As I said elsewhere: PRs accepted. :)

**Comment by arikfr** [comment]
This was resolved in v7.
