### ISSUE TITLE
LDAP/Basic Auth Support for the Redash itself

### ISSUE THREAD

**Issue by Civil** [getredash/redash#1790]
This is a feature request. Maybe I've missed that in documentation, but I'd like to see either LDAP or at least Basic Auth support in Redash (e.x. if nginx sends user parameters, assume and autocreate a user with some default rights and also override current internal authorization).

**Comment by yuokada** [comment]
Duplicated?
https://github.com/getredash/redash/issues/633

**Comment by Civil** [comment]
Yeah, thx.

**Comment by arikfr** [comment]
@amarjayr's #1836 was just merged 🙌
