### ISSUE TITLE
Visualizations doesn't work on Mozilla

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#1791]
### Issue Summary

Visualizations doesn't work on Mozilla.

`XML Parsing Error: undefined entity
Location: http://redash.trbna.com/queries/136
Line Number 1, Column 94:
Error: n.querySelector(...) is null
d.selection.prototype.appendSVG@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:152:31985
n@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:153:537
t.convertToTspans@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:153:2176
n@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:168:2760
Ea.call@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:147:7630
r@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:168:3522
Ea.call@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:147:7630
e.exports/<@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:168:8760
Ea.each/<@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:147:7555
G@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:144:28940
Ea.each@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:147:7532
e.exports@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:168:8599
l@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:157:14488
i.syncOrAsync@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:150:11004
y.plot@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:157:17480
y.redraw@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:157:17796
PlotlyChart/<.link/<@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:144:23402
Mn/this.$get</p.prototype.$digest@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:8:11180
Mn/this.$get</p.prototype.$apply@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:8:12680
Qt/this.$get</<@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:7:28041
Ge@http://redash.trbna.com/app.8c5636b7d1a908bf04c2.js:6:17479
`

<img width="686" alt="2017-05-29 15 15 13" src="https://cloud.githubusercontent.com/assets/7091907/26549427/aef34262-4481-11e7-919e-f9aa6e8a14e6.png">

### Technical details:

* Redash Version: Master
* Browser/OS: Mozilla

**Comment by arikfr** [comment]
But works on Chrome? Can be reproduced on demo.redash.io?

**Comment by denisov-vlad** [comment]
It's ok on Chrome and Safari.

I can't reproduce it on demo.redash.io because the bug in cyrillic symbols and Python query runner.

**Comment by arikfr** [comment]
Are you sure that type of query runner is related?

**Comment by denisov-vlad** [comment]
@arikfr nope. The same error I see in all visualizations with cyrillic letters.

**Comment by arikfr** [comment]
Is this still an issue?

**Comment by denisov-vlad** [comment]
It's OK now.
