### ISSUE TITLE
Upgrade error - No such file or directory: '../rd_ui/dist/index.html'

### ISSUE THREAD

**Issue by brightsparc** [getredash/redash#1805]
Hi,

I created a new EC2 instance from us-east-1 AMI `ami-9ea12788`.

I was able to use this version as is without issue, but when I went to upgrade the application, I was no longer unable to user the app despite the apparent success of multiple upgrades - see below.

```
wget https://raw.githubusercontent.com/getredash/redash/master/bin/upgrade
chmod +x upgrade
sudo ./upgrade --channel legacy # upgrade from 0.11.1+b2095 to redash.0.12.0.b2449...
export REDASH_DATABASE_URL="postgresql:///redash" # add additional slash
sudo ./upgrade # upgrade to redash.1.0.3.b2850
```

Once I started the application, the login screen appeared, but I got on error on re-direct see log below.

```
[2017-06-03 05:26:12,268][PID:1729][INFO][metrics] method=POST path=/login endpoint=redash.login status=302 content_type=text/html; charset=utf-8 content_length=305 duration=92.43 query_count=2 query_duration=3.24
[2017-06-03 05:26:12,618] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/opt/redash/redash.1.0.3.b2850/redash/handlers/static.py", line 30, in index
    return send_file(full_path, **dict(cache_timeout=0, conditional=True))
  File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 536, in send_file
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/opt/redash/redash.1.0.3.b2850/redash/../rd_ui/dist/index.html'
```

I'm not sure where I am supposed to get this rd_ui folder from.

Cheers,
Julian.

**Comment by arikfr** [comment]
Did you follow the instructions that show up before you confirm the upgrade and did the needed updates to the .env file?

**Comment by brightsparc** [comment]
Hi @arikfr, Thanks for the reply I tried again to repeat this process and in the meantime, it appears that AMI has been updated to the `redash.1.0.3.b2850` version, which does away with my issues.  (I did see the comments in the upgrade path which I may have missed at the time)

**Comment by brightsparc** [comment]
I was expecting this latest version to have Athena data source, but this doesn't appear in my list
![no_athena_datasource](https://cloud.githubusercontent.com/assets/360368/26751460/586aa048-487d-11e7-9644-807d6bb50d09.png)

I had a look at the changelog, and it was introduced in v1.0 so i'm a bit puzzled, any ideas @arikfr?
https://github.com/getredash/redash/blob/master/CHANGELOG.md

**Comment by arikfr** [comment]
Athena isn't enabled by default, because until #1777 is implemented it requires the JDBC proxy. See [this thread](https://discuss.redash.io/t/support-for-aws-athena/302/20) for more details.

**Comment by contactcuong** [comment]
hi @brightsparc would you please share how can you deal with the error you posted above? looks like I am experiencing the same problem with yours, very much appreciated.
```
IOError: [Errno 2] No such file or directory: '/opt/redash/redash.1.0.3.b2850/redash/../rd_ui/dist/index.html'
```

**Comment by edycop** [comment]
I have tha same problem, but in v4.0.4
IOError: [Errno 2] No such file or directory: '/opt/redash/redash-v4.0.1/redash/settings/../../client/dist/index.html'

**Comment by lanshuofeng** [comment]
@edycop @contactcuong hi I met the same problem when I set up and found IO Error, would you please tell me how to deal with this problem? I build redash in docker 
IOError: [Errno 2] No such file or directory: '/app/redash/settings/../../client/dist/index.html'`

**Comment by lanshuofeng** [comment]
It seems that 'npm run build' didn't work so I run 'docker-compose build server' to rebuild server image now it works. Thanks and sorry to trouble you
