### ISSUE TITLE
Query refresh for text parameter

### ISSUE THREAD

**Issue by indupulikkot** [getredash/redash#1811]
Hi,

When I add a text paramter for query filter condition, entire query is executing again and fetching output is extremely slow , unlike dropdown filter where values are already coming from executed output.
What can we do to improve the performance or fetching the query from cached data when we use text parameter filter.

Regards
Indu

**Comment by arikfr** [comment]
Please stop using issues for support questions.

**Comment by indupulikkot** [comment]
Kindly reply to these links, if issues cant be posted in github

https://discuss.redash.io/t/nested-filter-in-redash/706/2

-posted 5 days ago

https://discuss.redash.io/t/query-refresh-for-text-parameter/725



Regards

Indu

This e-mail and any files transmitted with it are for the sole use of the intended recipient(s) and may contain confidential and privileged information. If you are not the intended recipient(s), please reply to the sender and destroy all copies of the original message. Any unauthorized review, use, disclosure, dissemination, forwarding, printing or copying of this email, and/or any action taken in reliance on the contents of this e-mail is strictly prohibited and may be unlawful. Where permitted by applicable law, this e-mail and other e-mail communications sent to and from Cognizant e-mail addresses may be monitored.
