### ISSUE TITLE
.env file does not found 

### ISSUE THREAD

**Issue by mich779** [getredash/redash#1823]
Hey ,
im trying to set mail setting in .env file (redash 1.0.0) in the redash server container and i cannot find him ..

**Comment by alison985** [comment]
@mich779 The .gitignore file removes the .env file from the repository on purpose because it contains information that should be kept secure. You can create a .env file in the root redash directory yourself and add whatever settings you want.

**Comment by arikfr** [comment]
When using a Docker based setup we don't use a `.env` file. You can pass the environment variables using the Docker Compose configuration file or whatever other method your orchestrator using. 

Also, please use [the forum](discuss.redash.io) for support questions.

**Comment by previa** [comment]
They use it on purpose  to make it hard to deploy so you might buy their service.

**Comment by arikfr** [comment]
@previa We go beyond what required of us to make it simple to deploy Redash, invest countless hours in making Redash stable before every release and help when we can on the forum.

I will appreciate if you don't spread your lies around here.
