### ISSUE TITLE
An unauthorized (read only) user can create queries 

### ISSUE THREAD

**Issue by calebeoliveira** [getredash/redash#1825]
### Issue Summary

I created a user on the default group and set the data source capabilities to "Read only" on that group. Accessing as this brand new user, I really can't create a new query, but I can fork a existing one, and modify it as I want. I think this could be a security flaw.

### Steps to Reproduce

1. Installed with docker, connect to a data source (I created a MySQL one);
2. Create a few queries;
3. Create a user and assign him to the "default" group;
4. Set the permissions of the data source for the default group to read only;
5. Do login with the brand new user and click to list the queries;
6. Choice one of the queries and fork it.

I expect that a "read only" role should really be read only.

### Technical details:

* Redash Version: 1.0.3+b2850
* Browser/OS: Google Chrome 59/Fedora 25
* How did you install Redash: Docker with the suggested `docker-compose.production.yml`

**Comment by mracter** [comment]
Confirming that this issue exists on Redash Version: 1.0.3+b2866. Although the `Execute Query` and `Refresh Query` buttons are disabled, a read-only user can fork an existing query to create a new API key, and alter the refresh interval for the forked query. However, it does not appear that the altered query is executed, even when the refresh interval has elapsed.

Browser/OS: Google Chrome 59/Ubuntu 17.04
How did you install Redash: Docker with the suggested `docker-compose.production.yml`
