### ISSUE TITLE
Auto-Maximum does not work in stacking graph

### ISSUE THREAD

**Issue by vladimirbaranov** [getredash/redash#1832]
### Issue Summary

Auto-Maximum does not work in stacking graph. (Chrome)

### Steps to Reproduce

1. Select stacking chart
2. Choose Y-axis minimum
3. Leave Y-axis maximum at Auto
4. The top of the chart gets cut off and auto-maximum does not get set.

![image](https://user-images.githubusercontent.com/6749278/27264417-d1fa6e3c-544b-11e7-87eb-6d8040cc0024.png)

### Technical details:

* Redash Version: 1.0.3+b2850
* Browser/OS: Chrome
* How did you install Redash: Command Line

**Comment by alexmuller** [comment]
I can reproduce this in Redash 1.0.0+b2815 with Firefox 55.

**Comment by arikfr** [comment]
Resolved in #2156 (part of the v4 release).
