### ISSUE TITLE
Docker: install xmlsec1

### ISSUE THREAD

**Issue by unixwitch** [getredash/redash#1837]
Hello,

Please install `xmlsec1` in the Docker image, since SAML doesn't work without it.

**Comment by arikfr** [comment]
Resolved in https://github.com/getredash/docker/issues/1. Future releases will include it.

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
