### ISSUE TITLE
Allow multiple values to be visualised on same graph

### ISSUE THREAD

**Issue by nickw-hailo** [getredash/redash#184]
BACKGROUND
Right now, when I create a query with multiple measures, I can only graph one measure in the widget beneath the query. Ie. I can only specify a singly y value at a time. If I change the y value, it changes all the graphs. I can also not graph multiple y values on the same graph (perhaps with different axes eg. % vs. absolute numbers).

USER STORY
As a Data Analyst, I want to write one query (which references one series variable (eg. city) and one time variable (eg. week)) and then draw multiple graphs on multiple measures from the same query, so that I don't need to create and save multiple "new" queries, each time I want a new graph. And so I can see multiple measures on the same graph and see how they trend together over time.

ACCEPTANCE CRITERIA
• Can draw multiple graphs showing different measures in each graph all from same, single query
• Can add multiple lines for different measures on the same graph (Eg. orders vs. customers vs. cart abandonments over time)
• Don't need to save same query multiple times with minor changes to achieve multiple graphs
• Nor do I need to save multiple smaller queries to then create a dashboard (which the current model invite users to do)

POTENTIAL SOLUTION
• Create new reference such as "Value 1::y1", "Value 2::y2", Value3::y3"..."ValueA::yA"
• Then for each graph widget specify WHICH y value(s?) it should look for when drawing the graph

**Comment by camerongrace** [comment]
@arikfr Sorry to revive such an old issue, but have there been any subsequent UI developments with respect to filtering (or multi-filtering) at the dashboard level (instead of the query level)? 

I just wanted to check with you before investing time/energy in an antiquated approach. Thanks!

**Comment by arikfr** [comment]
@camerongrace I posted some additional information on Gitter: https://gitter.im/getredash/redash?at=56c02f07fa79226456fa430f

But specifically about filter/multi-filters, it is possible to enable them for a dashboard. You can do this from the admin page for dashboards (/admin/dashboard), find the dashboard you want and check "Dashboard Filters Enabled".
