### ISSUE TITLE
Security: List of users returned instead of cassandra response

### ISSUE THREAD

**Issue by synox** [getredash/redash#1844]
### Issue Summary

Using Firefox on Windows 7, we use the Cassandra Datasource to load a list of IDs. Instead we receive a list of users of the internal users table. On an other occasion we receive a list of queries. 

This is security relevent. 

See attachments:
![wrong-response](https://user-images.githubusercontent.com/2250964/27585279-de4f9184-5b3b-11e7-9b32-71531f6c7d56.PNG)
 ![2](https://user-images.githubusercontent.com/2250964/27585280-de507c2a-5b3b-11e7-8934-4fe1de7c8707.PNG)

### Steps to Reproduce

1. Install based on the following Dockerfile:

```
FROM redash/redash:2.0.0.b2924
USER root
RUN pip install -Iv cassandra-driver==3.10
EXPOSE 5000
ENTRYPOINT ["/app/bin/docker-entrypoint"]
CMD ["server"]
```

2. Set ENV:

            -
              name: PYTHONUNBUFFERED
              value: '0'
            -
              name: REDASH_LOG_LEVEL
              value: INFO
            -
              name: REDASH_REDIS_URL
              value: 'redis://redis:6379/0'
            -
              name: REDASH_DATABASE_URL
              value: 'postgresql://postgres1:postgres@postgresql/postgres1'
            -
              name: REDASH_COOKIE_SECRET
              value: veryverysecret
            -
              name: REDASH_ADDITIONAL_QUERY_RUNNERS
              value: 'redash.query_runner.cass'

3. Run Cassandra Queries that take long to process (120k Entries, LIMIT 1000)

### Technical details:

* Redash Version: 2.0.0.b2924
* Browser/OS: Docker
* How did you install Redash: Dockerfile on Openshift 3.3

**Comment by arikfr** [comment]
Check your setup: you probably have query runners (workers) that use a different database than your frontend servers. When they return the query result id the frontend loads a different result from its database that uses the same id.

To verify this theory: open the API representation of the query result (`/api/queries/1/results.json`) and check the `query` field to see if it matches the query you sent. You can also check the `retrieved_at` timestamp value.

**Comment by arikfr** [comment]
Closing for unresponsiveness.
