### ISSUE TITLE
can't execute query to get value

### ISSUE THREAD

**Issue by huangpeide** [getredash/redash#1845]
![image](https://user-images.githubusercontent.com/7991283/27626560-1886aba0-5c1b-11e7-9702-9c70633cb98f.png)
------------------------------
![image](https://user-images.githubusercontent.com/7991283/27626570-235341d8-5c1b-11e7-9f7d-fb79d6bb8458.png)
---------------------------------
![image](https://user-images.githubusercontent.com/7991283/27626583-31f22b46-5c1b-11e7-90fa-82dc19ef56f9.png)
------------------------------
![image](https://user-images.githubusercontent.com/7991283/27626630-52a269c8-5c1b-11e7-9d28-660b7e4785a1.png)
------------------------------
![image](https://user-images.githubusercontent.com/7991283/27626658-6700a902-5c1b-11e7-9402-6952f3219c49.png)
-------------------------------

any body know!

**Comment by huangpeide** [comment]
any body help?@arikfr

**Comment by BroManDudeGuyPhD** [comment]
Similar issue. Bump

**Comment by arikfr** [comment]
Your worker container exited and hence no queries are being executed.

In the future please use the [forum](discuss.redash.io) for support questions, as instructed when opening a new issue. Thanks :pray:
