### ISSUE TITLE
Redash Permissions not working for some use cases

### ISSUE THREAD

**Issue by rohanpd** [getredash/redash#1854]
### Issue Summary

Currently, when query owner grants permission to another user for a query, the user is still unable to perform the following tasks:

* change data source
* schedule the query
* add and save new visualisation

I believe the user should have the ability to do all the things that the owner could do once permission has been granted.

### Technical details:

* Redash Version: 1.0.3
* Browser/OS: Chrome
* How did you install Redash: AWS using the AMI

**Comment by arikfr** [comment]
The last two totally make sense, the "change data source" presents a possible issue: if one of the other editors has access to more data sources than the owner, then he might switch the query to a data source the owner doesn't have access to.

Will it be OK if for now we keep this restricted?

**Comment by BruceAtlas** [comment]
@arikfr That's a fair point. I think we could live with "change data source" remain restricted. 

Meanwhile, is there an existing ticket or in the roadmap of Redash to have a configurable group level security policy? i.e. admin can allow all users belong to the same group can edit each other's query without the need of query owner to grant permission for each query.

cc: @rohanpd

**Comment by alison985** [comment]
How do you grant permissions to another user for a query? For example, http://demo.redash.io/queries/5272/source#table ?

**Comment by kyoshidajp** [comment]
@alison985 Hi. To grant permissions, you should specify `REDASH_FEATURE_SHOW_PERMISSIONS_CONTROL` is `true` in your management Redash. Probably, you can't grant it in demo site.
