### ISSUE TITLE
Redash sends html-encoded parameters to a database

### ISSUE THREAD

**Issue by vkuptcov** [getredash/redash#1861]
### Issue Summary

Redash sends html-encoded parameters to a database. So, it "brakes" the transfered value.

### Steps to Reproduce

1. Create a MySQL datasource
2. Create the next query
```
SELECT TO_BASE64("{{test}}")
```
3. Execute the query with the `test` parameter `/#<>`
4. Redash sends a result back `JiN4MkY7IyZsdDsmZ3Q7`
5. Decode the result
```
$ echo 'JiN4MkY7IyZsdDsmZ3Q7' | base64 --decode
&#x2F;#&lt;&gt;
```

### Technical details:

* Redash Version: 1.0.3+b2850
* Browser/OS:  Google Chrome Version 59.0.3071.109 (Official Build) (64-bit) / Ubuntu 16.04
* How did you install Redash: standalone version

**Comment by RobinDarrah** [comment]
I haven't tried it with MySQL, but I'm pretty sure if you use tripe brackets for the parameter you'll get the desired result.
ie:
```sql
SELECT TO_BASE64("{{{test}}}")
```

**Comment by vkuptcov** [comment]
@RobinDarrah  thanks a lot! It works perfectly.
