### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by alexpekurovsky** [getredash/redash#1872]
Hi,

Thanks for Redash, we're using it a lot and very happy with it.

I'm constantly tracking if new versions are available and see a log of builds in DockerHub, but still no release of 2.0.0 version. So I have an idea - how about creating milestones for releases? It gives much more visibility about plans, features and term of next release. I see that you've used milestones up to version 1.0.0, but not after.

Thank you

**Comment by arikfr** [comment]
👍  I'm wrapping up v2 now and opened a milestone for v3.
