### ISSUE TITLE
Error attempting to archive/delete query

### ISSUE THREAD

**Issue by jasonshah** [getredash/redash#1875]
### Issue Summary

I receive an error when attempting to either archive (via normal UI) or delete (via admin UI) a query.

### Steps to Reproduce

1. I attempt to archive a query, and receive "Query could not be archived" red toast message in lower right of screen.
2. I then attempt to trashcan the same query from the admin UI, and receive a red notification:
> Failed to delete record. (psycopg2.ProgrammingError) column alerts.rearm does not exist LINE 1: ...ts.last_triggered_at AS alerts_last_triggered_at, alerts.rea... ^ [SQL: 'SELECT alerts.updated_at AS alerts_updated_at, alerts.created_at AS alerts_created_at, alerts.id AS alerts_id, alerts.name AS alerts_name, alerts.query_id AS alerts_query_id, alerts.user_id AS alerts_user_id, alerts.options AS alerts_options, alerts.state AS alerts_state, alerts.last_triggered_at AS alerts_last_triggered_at, alerts.rearm AS alerts_rearm \nFROM alerts \nWHERE %(param_1)s = alerts.query_id'] [parameters: {'param_1': 114}]

I expect my query to be archived/deleted.

### Technical details:

* Redash Version: 1.0.3+b2896
* Browser/OS: Chrome Mac
* How did you install Redash: Self-hosted within a Docker container, with database hosted on AWS RDS

**Comment by arikfr** [comment]
Seems like an issue with your database schema -- the alerts table should have the rearm column. Has nothing to do with the archiving functionality...

Closing. You're welcome to reopen with additional details.
