### ISSUE TITLE
Format Integers with commas

### ISSUE THREAD

**Issue by mfouilleul** [getredash/redash#1877]
Hello,

Our users complains about the integers are shown with comma.

Example
```
SELECT id FROM test;
```

Where id is `INT(11) unsigned`

Result is `21,668`

Do you know if we can fix it quickly?

Thanks

Max.

**Comment by dersphere** [comment]
Maybe a little late but I ran into the same issue and solved it by casting the id-column to char.
In your case: `SELECT CAST(id as CHAR(8)) as id FROM test;`
Hacky "but it works" ;)

**Comment by arikfr** [comment]
V4 includes the ability to configure how each column is rendered, so you can control whether you want the commas in integers or not.

**Comment by chgxtony** [comment]
@arikfr how to configure how each column is rendered

**Comment by rohit-conn** [comment]
Currently we are using V5 but I cant seem to find the parameter to check rendering.
Could you please point me to the right direction.

**Comment by deed02392** [comment]
Bump. Where do we configure this?

**Comment by masterlittle** [comment]
So, maybe a lot late but sharing my two cents. It's in client/app/visualizations/table/index.js .

```
const numberFormat = {
    integer: clientConfig.integerFormat || '00',
    float: clientConfig.floatFormat || '00.00',
  };
```

Will have to change the source code but it works after that.

**Comment by faridskyman** [comment]
> Maybe a little late but I ran into the same issue and solved it by casting the id-column to char.
> In your case: `SELECT CAST(id as CHAR(8)) as id FROM test;`
> Hacky "but it works" ;)

this solves my problem.. thx!

**Comment by eradman** [comment]
@faridskyman: as @masterlittle suggested you can update the `organizations` table to make change the number format

```sql
UPDATE organizations SET settings = jsonb_set(settings::jsonb, '{settings,float_format}', '"0.0"', true);
UPDATE organizations SET settings = jsonb_set(settings::jsonb, '{settings,integer_format}', '"0"', true);
```
