### ISSUE TITLE
Redash EC2 instance behind ELB or CloudFront distribution

### ISSUE THREAD

**Issue by hernangarcia** [getredash/redash#1901]
### Issue Summary

I have a redash EC2 instance running well on its public IP address. I want to place it behind an Elastic Load Balancer or CloudFront Distribution but the health check keeps failing since nginx is always returning a 302 redirect instead 200.

HTTP/1.1 302 FOUND
Server: nginx
Date: Wed, 02 Aug 2017 01:29:39 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 347
Connection: keep-alive

Have anyone tried this setup? Any idea on why is the redirect happening?

Thanks a lot in advance.

**Comment by arikfr** [comment]
How your nginx configuration looks like?

Btw, in the future please use [the forum](discuss.redash.io) for support questions.

**Comment by hernangarcia** [comment]
Hey @arikfr , my bad. Moving it to the forums. Thanks.

**Comment by arikfr** [comment]
Thanks!

**Comment by aashishvanand** [comment]
I had the same issue. 
Fix: In ELB, set the health check endpoint to /ping. It's an undocumented health check API in Redash
