### ISSUE TITLE
Wrong column display when stacking with negative values

### ISSUE THREAD

**Issue by grzlybear** [getredash/redash#1902]
### Issue Summary
I'm trying to create a column chart with series values that contain both positive and negative values.
For example, the number of new users is shown as positive while the number of churned users is shown as negative. They both have the same X value (same time frame).

When selecting the stacking option I expect the positive values to be above the X line and the negative values to be below the X line.

### Technical details:

* Redash Version: 1.0.3
* Browser/OS: Chrome / OSX
* How did you install Redash: self hosted on google cloud

reality
![screen shot 2017-08-02 at 14 43 09](https://user-images.githubusercontent.com/4466323/28872287-36a95c18-7791-11e7-8c32-7f2e64e060f2.png)

expected
![screen shot 2017-08-02 at 14 45 42](https://user-images.githubusercontent.com/4466323/28872313-4bfc7c3a-7791-11e7-95bc-af0fac63c168.png)

**Comment by deecay** [comment]
@arikfr 
Introduce barmode ['stack', 'overlay', 'group', 'relative'] somewhere in the editor-ui?
Since the list of options is not too long, maybe radio control is better that dropdown, which would require more clicks. Any preference or thoughts?

Example:
[https://codepen.io/etpinard/pen/mPGLrY](https://codepen.io/etpinard/pen/mPGLrY)

**Comment by arikfr** [comment]
We already have some of those options implemented with custom code, so it's nice we might be able to drop it and use their implementation. 

But looks like they have a bug with "stack" too (in your example) or did I misunderstand how it supposed to work?

**Comment by deecay** [comment]
Related Plotly community discussion [here](https://community.plot.ly/t/stacked-bar-with-positive-and-negative-values/920/2).
So the behavior of "stack" seems intentional?
