### ISSUE TITLE
Error running query: execute_query() takes exactly 4 arguments (6 given)

### ISSUE THREAD

**Issue by postster** [getredash/redash#1903]
### Issue Summary

When running queries on our (fairly loaded) redash server, I quite often get this error:
Error running query: execute_query() takes exactly 4 arguments (6 given)
The query does not run.

### Steps to Reproduce

Click 'Execute Query' on any query.  Error rate is quite high; I get this error typically 3-4 times before the query starts running.

### Technical details:

* Redash Version: 1.0.3+b2850
* Browser/OS: Chrom 59.0.3071.115 (Official Build) (64-bit) on OSX
* How did you install Redash: upgraded from prior version using upgrade script; original was installed by booting up an ami

**Comment by arikfr** [comment]
Check if any of the workers you have still runs an old version of the code and hence the parameter mismatch.

**Comment by arikfr** [comment]
Closing. You're welcome to reopen with additional details.
