### ISSUE TITLE
Unable to build cryptography on Ubuntu 16.04.2

### ISSUE THREAD

**Issue by nilesuan** [getredash/redash#1908]
Here's the whole log:
[https://pastebin.com/ExaWUcUR](https://pastebin.com/ExaWUcUR)

OS: Ubuntu 16.04.2 LTS

`λ ~/ sudo apt-get install build-essential libssl-dev libffi-dev python-dev  
Reading package lists... Done  
Building dependency tree         
Reading state information... Done  
build-essential is already the newest version (12.1ubuntu2).  
libffi-dev is already the newest version (3.2.1-4).  
python-dev is already the newest version (2.7.11-1).  
libssl-dev is already the newest version (1.1.0f-2~ubuntu16.04.1+deb.sury.org+1).  
0 upgraded, 0 newly installed, 0 to remove and 35 not upgraded.  
λ ~/ pip install cryptography  
Requirement already satisfied: cryptography in /usr/local/lib/python2.7/dist-packages  
Requirement already satisfied: ipaddress in /usr/local/lib/python2.7/dist-packages (from cryptography)  
Requirement already satisfied: six>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)  
Requirement already satisfied: idna>=2.1 in /usr/local/lib/python2.7/dist-packages (from cryptography)  
Requirement already satisfied: asn1crypto>=0.21.0 in /usr/local/lib/python2.7/dist-packages (from cryptography)  
Requirement already satisfied: enum34 in /usr/local/lib/python2.7/dist-packages (from cryptography)  
Requirement already satisfied: cffi>=1.7 in /usr/local/lib/python2.7/dist-packages (from cryptography)  
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.7->cryptography)  
λ ~/  `

**Comment by arikfr** [comment]
You can refer to Cryptography's [installation guide](https://cryptography.io/en/latest/installation/). If it still doesn't help, try their support channels.
