### ISSUE TITLE
Release v2 🎉

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#1918]
- [x] Bump version of the master branch to the next version.
- [x] Edit latest RC release:
  - [x] Give the tag a new name, with full version prefixed with a "v" (e.g. v0.8.0.b1058).
  - [x] Update title.
  - [x] Update release notes.
  - [x] Uncheck "This is a pre-release".
- [x] Mark latest on Docker Hub.
- [x] Update version.redash.io.
- [x] Update bootrstrap.sh files.
- [x] Prepare AWS and GCE images:
  - [x] Create: `packer build -var 'redash_version=0.8.0.b1058' -var 'image_version=080b1058' -var 'aws_access_key=' -var 'aws_secret_key=' -only=redash-eu-west-1 packer.json`
  - [x] Make it public: `python copy.py make_public {image} eu-west-1`
  - [x] If the EC2 AMI is outdated, you need to get a new one from: https://cloud-images.ubuntu.com/trusty/current/ (HVM SSD)
  - [x] Copy to all other regions: `python copy.py copy_image {image} eu-west-1`
  - [x] Test instance: `python copy.py start_test_instance {image} eu-west-13.`
- [x] Update documentation links.
- [x] Announcement:
  - [x] Gitter + Slack.
  - [x] Blog post.
  - [x] Newsletter.
  - [x] Tweet.

**Comment by synhershko** [comment]
Amazing! looking forward to the AWS AMI :)

**Comment by synhershko** [comment]
@arikfr is this released? trying to run the bootstrap script (manual and via packer as well) and hitting a 403. This boils down to the following:

```
synhershko@synhershko-mint ~/code/redash/setup $ wget https://s3.amazonaws.com/redash-releases/redash.2.0.0.tar.gz
--2017-08-13 21:21:39--  https://s3.amazonaws.com/redash-releases/redash.2.0.0.tar.gz
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.216.160.237
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.216.160.237|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-08-13 21:21:41 ERROR 403: Forbidden.
```

Would it be possible please to finalize the release?...

**Comment by arikfr** [comment]
The correct URL is https://s3.amazonaws.com/redash-releases/redash.2.0.0.b2990.tar.gz.

**Comment by synhershko** [comment]
Thanks, that worked!

**Comment by rohithmenon** [comment]
@arikfr While you are at this, it would be good to bump up plotly.js to >= 1.29.0. Hover text in graphs get truncated when your text length is > 15 characters. I can send a PR to use namelength which is a configuration available in plotly.js >= 1.29.0 (https://github.com/plotly/plotly.js/pull/1822/commits)
