### ISSUE TITLE
A Bug in redash/client/app/pages/admin/tasks/tasks.html

### ISSUE THREAD

**Issue by wu123456** [getredash/redash#1926]
In the line 45 of 'redash/client/app/pages/admin/tasks/tasks.html', the variable dataRow is not defined.

cancel-query-button query-id="dataRow.query_id" task-id="dataRow.task_id"></cancel-query-button
change into 
cancel-query-button query-id="row.query_id" task-id="row.task_id"></cancel-query-button

**Comment by arikfr** [comment]
Thanks!
