### ISSUE TITLE
Create data source programmatically

### ISSUE THREAD

**Issue by synhershko** [getredash/redash#1927]
To allow for replacing redash instances or creating several for redundancy, it would be very helpful to allow to launch an instance with preconfigured data sources. I wasn't able to find instructions on how to do that - and if that's not possible for now it'd be a very nice feature to have..

**Comment by alexpekurovsky** [comment]
Maybe better to create datasources using API while creating instance?

**Comment by synhershko** [comment]
Is that currently supported?

**Comment by alexpekurovsky** [comment]
Not sure :)

**Comment by fjkfwz** [comment]
you can using `./manage.py ds` command do it

**Comment by arikfr** [comment]
Anything you can do from the web UI you can do with the API. It's not really documented, but you can either look at the code or just check the `Network` tab in your browser console and see the requests it makes.

You will need to use a user API key, which you can find in your user profile page.
