### ISSUE TITLE
Pandas cannot be imported in Python data source.

### ISSUE THREAD

**Issue by Samemura** [getredash/redash#1929]
### Issue Summary

I tried to use Pandas module in Python data source but module could not be found as below error.
Someone help me to use Pandas ???

```
Error running query: <type 'exceptions.ImportError'> No module named pandas
```

Executed scipt:
```
import pandas as pd
```

### Steps to Reproduce

1. Running redash with docker-compose as installation guide.
    https://redash.io/help-onpremise/setup/setting-up-redash-instance.html
1. pip install pandas on redash server container
1. Enable python datasource with pandas module

### Technical details:

* Redash Version: 2.0.0+b2990
* Browser/OS: Chrome / Ubuntu 16.04
* How did you install Redash: Docker-compose

**Comment by arikfr** [comment]
You need to install pandas in the worker container, which actually runs the query.

**Comment by Samemura** [comment]
@arikfr thank you so much for your answer. It works fine to me!

**Comment by Amirashaker** [comment]
same error appear when using mysql.connector also i add 'pip install mysql.connector' in worker container in docker-compose.yml file 
how to solve it
