### ISSUE TITLE
Crash after connection to the db unexpectedly break

### ISSUE THREAD

**Issue by hhschu** [getredash/redash#1938]
Hi,

While the following `_wait()` function did catch a selector error, however, if a connection is unexpectedly cut off, an Operation Error of server closed will be raised and crash the whole process. Maybe a re-connect should be implemented here?

https://github.com/getredash/redash/blob/89de5f2a18288645fa5ee9c247bde5464dfb4b5a/redash/query_runner/pg.py#L43

**Comment by rueian** [comment]
![image](https://user-images.githubusercontent.com/2727535/29759885-05e6f7fa-8bf2-11e7-9849-d50c04251e63.png)

**Comment by arikfr** [comment]
We never implemented reconnect in any of the query runners. I can see both pros and cons, but anyway no immediate plans for it.

If someone wants to implement this, he's welcome although I guess a more general retry implementation in the upper level (in QueryExecutor) makes more sense.
