### ISSUE TITLE
Implement Schema Browser for Athena connection

### ISSUE THREAD

**Issue by tdawber** [getredash/redash#1939]
### Issue Summary

We no longer see the Schema Browser for Athena connections since upgrading to the latest version of redash.  This is an important feature for us, and we would appreciate it being added back in.

### Steps to Reproduce

1. Set up a connection to Athena
2. Attempt to use the Schema Browser
3. Be unable to see the Schema Browser

**Comment by arikfr** [comment]
I don't think this is a general issue with the query runner, as it supports loading the schema and I saw it working.

Try loading the schema manually: `/api/data_sources/<id>/schema` and see what it returns. If it returns an error, can you check the logs for relevant messages?

**Comment by arikfr** [comment]
Closing. You're welcome to reopen with additional details.
