### ISSUE TITLE
JS exception on parsing columns with integer col.name

### ISSUE THREAD

**Issue by rgovindji** [getredash/redash#1960]
Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

In query-result.js line 354 if col.name is returned as a long i.e '404' then exception is thrown. 
angular.js:13920 TypeError: n.split is not a function

### Steps to Reproduce

1. Make an elastic search query which returns a list of buckets that have integers as the key names
2. When the response is returned, you will see the exception

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: v2.0.0
* Browser/OS: Mac / Chrome
* How did you install Redash: Docker

**Comment by arikfr** [comment]
At first I thought that we should handle this in the client code, but on second thought I think that the column name should be a string and the fix should be in the query runner.

**Comment by rgovindji** [comment]
The issue we have is that Kibana automatically names this column "2" by
default. It's not much of an issue to change it to a string but the issue
is not obvious unless you debug it so I can see other users running into
this problem often.
