### ISSUE TITLE
Queries using other queries as a data source

### ISSUE THREAD

**Issue by ziahamza** [getredash/redash#1977]
I couldnt find an existing ticket for this so made this one. 

Redash seems to advertise that it supports adding queries as first class data sources here: https://redash.io/help/queries/using-datasets-as-data-sources.html

It would be really cool to have this functionality land in redash. @arikfr any plans on open sourcing the preview, or would you accept any PRs that add this functionality directly into redash?

**Comment by arikfr** [comment]
It will be part of the v3 release.
