### ISSUE TITLE
Docker Stack

### ISSUE THREAD

**Issue by doddjc21** [getredash/redash#1982]
### Issue Summary

trying to run Redash in swarm I get an error with starting nginx container. I used the docker-compose.production.yml for running "docker stack deploy". I ran the same file using compose and it ran fine.  so is there a way to deploy redash using swarm or not? 
bwt I'm not getting any useful error from nginx failure. running docker stack ps redash I get "task: non-zero exit (1)" 

### Steps to Reproduce
1. change compose version from 2 to 3 in docker-compose.production.ym
2.  run "docker stack deploy -c docker-compose.production.yml -c redash" 

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:  v.2.0.0
* OS: centos 7
* How did you install Redash: trying to deploy it using latest docker-compose.production.yml

**Comment by arikfr** [comment]
This is not a Redash specific issue, but something to do with your setup. You might have better luck in Docker Swarm specific forums.
