### ISSUE TITLE
Chart not include all the rows from results.

### ISSUE THREAD

**Issue by youfenman** [getredash/redash#1996]
Hi there 
I am new to redash, I run the query get 46 row from database. In the table it looks right, but when I create a chart, it only include the first, sometime the last row of each category. Here is the data: 

CATEGORY .\ | UNIT_PRICE | UNIT_COST
-- | -- | --
Apparel | 59.99 | 42.97
Apparel | 59.99 | 35.03
Apparel | 25.48 | 17.96
Apparel | 17.98 | 13.38
Apparel | 19.42 | 11.94
Accessories | 70.43 | 35.91
Accessories | 29.98 | 20.29
Accessories | 44.98 | 31.04
...total 46 rows ...

![image](https://user-images.githubusercontent.com/32332880/31184315-112df272-a8f7-11e7-99a2-bec8f63002b0.png)

Notice the first row of unit price in accessories category is 70.43 and unit cost is 35.91(didn’t show up in the table) this chart only include one row data in each category. when create a pie, only the last row in each category included.  Anyone can tell me why? 

Thanks a lot.

**Comment by youfenman** [comment]
![newplot 3](https://user-images.githubusercontent.com/32332880/31186471-b74a10dc-a8fc-11e7-98a7-cbec5d9b8ba5.png)
this is the chart

**Comment by youfenman** [comment]
I am new to redash, anyone can help me? please.

**Comment by arikfr** [comment]
Redash visualizes the data you give it. In this case, I assume you want to see total of unit price/cost per category -- your query needs to return this. Redash won't sum the data for you.

**Comment by youfenman** [comment]
it is working now, thans
