### ISSUE TITLE
Black linking rectangle when chosing dashboard widget

### ISSUE THREAD

**Issue by truekonrads** [getredash/redash#2002]
### Issue Summary
When I click add widget to dashboard and then click inside the query search input control, it gets this ugly black border and blinks:

![image](https://user-images.githubusercontent.com/1421150/31294721-ee65edb0-aad3-11e7-9ac6-f3a887a38da3.png)

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. Create some query, save it
2. Create a new dashboard
3. Click "Add Widget"

### Technical details:

* Redash Version: redash.2.0.0.b2990
* Browser/OS: 61.0.3163.100 (Official Build) (64-bit) on Windows 7
* How did you install Redash: using boostrap.sh

**Comment by arikfr** [comment]
The browser is Chrome?

**Comment by truekonrads** [comment]
Correct.  Chrome

**Comment by ranbena** [comment]
Doesn't seem like an issue anymore.
If still relevant @truekonrads, plz reopen.
