### ISSUE TITLE
[Feature] Tunnel support in default Docker image

### ISSUE THREAD

**Issue by Slind14** [getredash/redash#2013]
Hi there,
it would be great if the default docker image would feature tunnel support. Meaning preinstalled autossh and loading a configuration with the hostname, port and authentication key.

**Comment by jezdez** [comment]
This seems quite out of scope and can be easily achieved with a custom Dockerfile based on the Redash Docker image. Closing as wontfix, feel free to reopen @arikfr if you disagree.
