### ISSUE TITLE
Pie Chart - Decimal Places on Chart

### ISSUE THREAD

**Issue by George-D-S** [getredash/redash#2020]
Redash 2.0.0+b2990

On a pie chart I've created the numbers on the chart itself vary between 1 and 2 decimal places depending on the fraction. I would like to force everything to be a single decimal place but can't see an option to do this.

This looks like it might be related to #1356

**Comment by kravets-levko** [comment]
Hi @George-D-S! Your issue seems to be fixed in latest Redash version. Can you check it please? Thanks!

**Comment by arikfr** [comment]
@George-D-S if you can reproduce this in the latest version, please re-open. Thanks!
