### ISSUE TITLE
Can I embed chart only have the graphic part without white space around it?

### ISSUE THREAD

**Issue by youfenman** [getredash/redash#2022]
I am embed a chart in my web page, it works great. The only problem I have is when I click embed button, I got a ifream which contains a chart and large area of white space like show as bellow, it take lot of space in the web page. I have seen some talk about the resize of the widget. But I am only using the image from visualization page. When edit the chart, I can change the size of the chart but, seem not able to change the rectangle of the where the chart is displayed which is area embed tag taken. Anyone can help me? 

Thanks in advance. 

![chart](https://user-images.githubusercontent.com/32332880/31506213-cf23fd6e-af44-11e7-9641-e9276e0f509d.png)

**Comment by arikfr** [comment]
Currently there is no way to change the whitespace. 

In the future please please use the [forum](https://discuss.redash.io) for similar questions.

Thanks.
