### ISSUE TITLE
Search schema for Presto is not showing on UI in AWS EC2 or docker instance redash instance

### ISSUE THREAD

**Issue by tomarv2** [getredash/redash#2023]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary
I tried deploying redash on aws ec2 using provided images and I dont see the search schema option.

Tried on Chrome and Firefox
A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce
1. Login to redash UI
2. Add database (in my case Presto)
3. Select queries and option is not available

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 2.0.0
* Browser/OS: Firefox/Chrome
* How did you install Redash: AWS EC2 and Docker image

**Comment by arnoldad** [comment]
+1 Also seeing this for Redshift

**Comment by arikfr** [comment]
This is usually a setup issue rather than issue with Redash, but regardless a lot has changed since this was open...

If this is still relevant, please reopen with relevant log information (from when you refresh the schema, to see if there is an error raised).

Thanks.
