### ISSUE TITLE
Unable to connect to Redshift data source

### ISSUE THREAD

**Issue by vnktsh** [getredash/redash#2047]
### Issue Summary

Unable to connect to Redshift data source.

### Steps to Reproduce

Installed Redash (Redash 2.0.0+b2990) from recent AMI (us-west-2 | ami-2325c85b)
Made sure my EC2 instance is allowing all types of traffic. My security group on the instance allows all the traffic inbound/outbound (Triple checked this)
I can ping to Redash EC2 from my local terminal and I can access the Redash server through browser.
Added Redshift data source through Redash UI.
Double checked the properties. I used same connection details on DBeaver and everything works fine and I can connect to Redshift through it.

However once I 'save' the details of DB connection properties and click 'Test Connection', I get error
" Unknown error occurred while performing connection test. Please try again later"

### Technical details:

* Redash Version: 2.0.0+b2990
* Browser/OS: Google Chrome Version 60.0.3112.90 (Official Build) (64-bit)
* How did you install Redash: AMI

I'm 99.99% sure this is not a bug, but somewhere something went wrong. I'm ready to actively debug, can you please help me in debugging it?
I checked logs on the instance at /var/logs/supervisor -- they doesn't seem to help.

Screenshot:
[https://imgur.com/a/FKskx](https://imgur.com/a/FKskx)

**Comment by kyoshidajp** [comment]
Hello, I suspect that the connection to Redshift cluster from EC2 instance is not good.

How about checking like this in your EC2 instance?

```
$ nc -zv <your-cluster-host> 3389
```

If the result is like this, then it is OK, and the cause is another one. It might be wrong user, password or port.

```
Connection to XXXXXXXX.redshift.amazonaws.com 3389 port [tcp/*] succeeded!
```

However, can't get the response or timeout, you should check Security Group in your Redshift cluster.

**Comment by vnktsh** [comment]
Thanks Kyoshidajp for the tip. It works now. The problem was in the company firewall. Sorry for the trouble. Closing now.
