### ISSUE TITLE
User query logging 

### ISSUE THREAD

**Issue by doddjc21** [getredash/redash#2052]
## Logging user queries and query output 

Hey Arikfr, didn't know if there was already a solution for this or if this is a feature that can be added to redash for future scope but: 

I was wondering if there is a way to log user  #queries that aren't saved.  I know you can return a saved query with https://<redash_url>/api/queries/<query_id>/results.(csv|json)?api_key=<your_api_key> but this requires that the user saves his/her query in order to use an API-key to access the results.  Is there any workaround for this type of feature or is this something where I could modify the redash/redash/query_runner/__init__.py  code to output every execution to a log file? Thanks for your help!

**Comment by arikfr** [comment]
Check the `events` table search for rows with `action` = `execute_query`.
