### ISSUE TITLE
No options to set HEADERS for URL queries 

### ISSUE THREAD

**Issue by IdanFridman** [getredash/redash#2058]
We have http endpoint that we want to query via redash.
After creating new URL datasource on redash I couldnt find a place where we can set HEADERS to the HTTP request as we must have authentication (using JWT)

Isnt it possible?
Thanks.

**Comment by arikfr** [comment]
No, it's not possible.

Also please take the time to read the instructions when opening an issue. For support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.
