### ISSUE TITLE
Move config to use the python-dotenv or python-decouple library

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2064]
Switch our own set of helper functions in `redash.settings` to use [Decouple](https://github.com/henriquebastos/python-decouple/). This will have the following benefits:

- Less custom code to cast configuration values.
- Built in support for loading values from a `.env` file. No more need to prefix commands with `bin/run`. (<- this is the real win here)

**Comment by vvanarasi** [comment]
@arikfr , Can i work on this change

**Comment by arikfr** [comment]
@vvanarasi sure!

**Comment by arikfr** [comment]
It might be easier to switch to [python-dotenv](https://github.com/theskumar/python-dotenv). Seems like as almost no changes will be required in our codebase.

**Comment by arikfr** [comment]
And it actually supported in Flask 1.0 natively: https://www.palletsprojects.com/blog/flask-1-0-released/

![image](https://user-images.githubusercontent.com/71468/39371446-67cbd6fe-4a4a-11e8-8961-707db3b653d6.png)
