### ISSUE TITLE
Druid and HBase data source

### ISSUE THREAD

**Issue by jonatasfreitasv** [getredash/redash#2065]
Have any implementation for this databases ?

**Comment by akashdeep01** [comment]
+1

**Comment by arikfr** [comment]
We're always happy to accept pull requests for new data sources. In many cases adding support for a new database is quite easy. You can see more details on the process here:

https://discuss.redash.io/t/creating-a-new-query-runner-data-source-in-redash/347

I'm trying to keep open issues actionable, so I'm closing this one. But that not to say that Druid or HBase support won't be welcomed.

Thanks!
