### ISSUE TITLE
Refactoring: merge `dashboard` and `public-dashboard`

### ISSUE THREAD

**Issue by kravets-levko** [getredash/redash#2076]
Currently there are two pages to display dashboard: `dashboard` and `public-dashboard`. First one is an extended version of the second, but with additional controls (editing, sharing, etc.). Since there is a lot of duplicated code, the idea is to merge that two pages (via extracting common code into components, services, etc.) and keep all logic related to dashboards in the single place.

**Comment by deecay** [comment]
+1 for this. And by doing that, I would like to see dashboard level filters available in public dashboards. This is a key feature for me.

**Comment by s1moe2** [comment]
+1 here for the exact same reasons that @deecay mentioned. Having the dashboard level filters available in public dashboards is super useful, specially because having individual filters on each visualisation completely breaks the user experience, in my opinion (if you have multiple visualisations)

**Comment by kravets-levko** [comment]
@gabrieldutra Please close this issue after getredash/redash#4228 and getredash/redash#4203 merged. Thanks!

**Comment by gabrieldutra** [comment]
Yeah, I'm kind of solving this issue in those PRs. Thanks for pointing this @kravets-levko! :)
