### ISSUE TITLE
redash with Google Compute Engine

### ISSUE THREAD

**Issue by PKostya** [getredash/redash#2085]
### Issue Summary

I am trying run redash on Google Compute Engine. After copying the image and launching instance I have several errors about Currently used ports(5000, 80) 
Error:
Error starting userland proxy: listen tcp 0.0.0.0:5000: bind: address already in use
### Steps to Reproduce

1. gcloud compute images create "redash-2-0-0" --source-uri gs://redash-images/redash.2.0.0.b2990.tar.gz
2. launch instance 
3. docker-compose -f docker-compose.production.yml run --rm server create_db
4.docker-compose -f docker-compose.production.yml up

**Comment by PKostya** [comment]
Solution wich help me: 
1. change ip mapping in docker-compose.production.yml 
2. open ports in GCE

**Comment by arikfr** [comment]
You don't need the Docker containers when using the image we provide. You get the port conflict error because you have two Redash instance running -- when on the host and one in a Docker container.
