### ISSUE TITLE
Problem with "docker-compose up"

### ISSUE THREAD

**Issue by luisnunezsalgado** [getredash/redash#2093]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

Agregar a linkedin. 

https://bitnami.com/stack/redash

0.- Cloning de git project
git clone https://github.com/getredash/redash

1.- Starting up the compose
nunez@lnunez-HP-ProBook-430-G2:~/redash$ docker-compose up
Building server
Step 1/8 : FROM redash/base:latest
 ---> 9d04584f371a
Step 2/8 : COPY requirements.txt requirements_dev.txt requirements_all_ds.txt ./
 ---> Using cache
 ---> a37cce7478ce
Step 3/8 : RUN pip install -r requirements.txt -r requirements_dev.txt -r requirements_all_ds.txt
 ---> Running in a2a96fe7b86b
Collecting Flask==0.11.1 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement Flask==0.11.1 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for Flask==0.11.1 (from -r requirements.txt (line 1))

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: latest
* Browser/OS: Ubuntu
* How did you install Redash: docker-compose up

**Comment by arikfr** [comment]
The image gets build regularly without any such issues. Maybe this is some proxy issue in your network?

**Comment by luisnunezsalgado** [comment]
Thanks Arik for your answer, in fact there was an issue related with a firewall, but I solved the issue incorporating the certificates into the image. Just to document that. I leave the Dockerfile with the modification that I did (I also incorporated the oracle libraries on this docker file in case someone else needed that information): 

Thanks for all ...

---Dockerfile: 
FROM redash/redash:latest

USER root

#dado que tenemos un firewall que altera las conexiones ssl, necesitamos incorporar los certificados al bash. 
COPY ca.crt /usr/local/share/ca-certificates/
COPY fortigate.crt /usr/local/share/ca-certificates/

RUN chmod 644 /usr/local/share/ca-certificates/*

RUN update-ca-certificates

# Oracle instantclient
ADD oracle/instantclient-basic-linux.x64-11.2.0.4.0.zip /tmp/instantclient-basic-linux.x64-11.2.0.4.0.zip
ADD oracle/instantclient-sdk-linux.x64-11.2.0.4.0.zip /tmp/instantclient-sdk-linux.x64-11.2.0.4.0.zip
ADD oracle/instantclient-sqlplus-linux.x64-11.2.0.4.0.zip /tmp/instantclient-sqlplus-linux.x64-11.2.0.4.0.zip

RUN apt-get update  -y
RUN apt-get install -y unzip

RUN unzip /tmp/instantclient-basic-linux.x64-11.2.0.4.0.zip -d /usr/local/
RUN unzip /tmp/instantclient-sdk-linux.x64-11.2.0.4.0.zip -d /usr/local/
RUN unzip /tmp/instantclient-sqlplus-linux.x64-11.2.0.4.0.zip -d /usr/local/
RUN ln -s /usr/local/instantclient_11_2 /usr/local/instantclient
RUN ln -s /usr/local/instantclient/libclntsh.so.11.1 /usr/local/instantclient/libclntsh.so
RUN ln -s /usr/local/instantclient/sqlplus /usr/bin/sqlplus

RUN apt-get install libaio-dev -y
RUN apt-get clean -y

#Parametros añadidos para poder descargar los paquetes desde la red de metro valparaiso.
ENV PIP_CERT /usr/local/share/ca-certificates/ca.crt
ENV DEFAULT_CA_BUNDLE_PATH /usr/local/share/ca-certificates/ca.crt
ENV PYTHONHTTPSVERIFY 0
ENV NODE_EXTRA_CA_CERTS /usr/local/share/ca-certificates/ca.crt

ENV ORACLE_HOME=/usr/local/instantclient
ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/instantclient

RUN pip install cx_Oracle==5.2.1

USER redash
#Add REDASH ENV to add Oracle Query Runner 
ENV REDASH_ADDITIONAL_QUERY_RUNNERS=redash.query_runner.oracle
