### ISSUE TITLE
Redesign issues for widgets with filters

### ISSUE THREAD

**Issue by deecay** [getredash/redash#2103]
I see a horizontal scrollbar for chart widget in dashboards, when a query has "::filter". I guess it is a CSS style issue of the filter control. Changing `margin-right` of `.row` in `filters` from `-15px` to `-5px` seem to fix the issue. 

![redash-dashboard-widget-width-scrollbar](https://user-images.githubusercontent.com/1698635/33251022-cae6c96e-d377-11e7-8fde-0df5995161ba.png)

Chrome 62.0.3202.94 with current HEAD of master branch.

**Comment by deecay** [comment]
In addition, counter visualization widget with filter control has issues. Counter value is shown overlapped with filter control.

**Comment by deecay** [comment]
I see no widget-level filter control for chart visualization. I do see them for Tables and Counters.
@kravets-levko

**Comment by kravets-levko** [comment]
Thanks @deecay, will take a look ASAP

**Comment by kravets-levko** [comment]
Hi @deecay, can you please review my fix? Thanks!

**Comment by deecay** [comment]
Hi @kravets-levko, I have confirmed that all points I've mentioned have been fixed.

before:
![snapcrab_noname_2017-11-28_22-33-13_no-00](https://user-images.githubusercontent.com/1698635/33322691-74db028a-d48d-11e7-806d-f9b8c3559b8d.png)

after:
![snapcrab_noname_2017-11-28_22-39-50_no-00](https://user-images.githubusercontent.com/1698635/33322713-7bfed726-d48d-11e7-9f80-65e683cf76ef.png)
