### ISSUE TITLE
Visualizations - Pivot Table - Provision for excel like derived columns and running totals

### ISSUE THREAD

**Issue by sankirnajoshi** [getredash/redash#2106]
A good example is that of taking a cumulative sum(running total) over some column of a pivot table after slicing it. This scenario is fairly common with sales data. Also, the task is dynamic  and not possible to manually code in sql.

**Comment by arikfr** [comment]
Please read the instructions and use the the [forum](https://discuss.redash.io) for feature requests.

There is actually already a discussion about this: https://discuss.redash.io/t/calculated-field-and-additional-value-fields-in-pivot-table/888.
