### ISSUE TITLE
Dashboard issues

### ISSUE THREAD

**Issue by vabanin** [getredash/redash#2108]
Hi guys,

I very excited about your work for refinement dashboard displaying and layout management in v4. 
Thank you!

I found following little issues:

- pivot table visualizations can't be scrolled now in widgets of dashboards. This is very inconvenient for wide or long pivot tables. In my fork of Redash I fixed it by commenting all lines in method this.getWidgetStyles in client/app/components/dashboards/widget.js

- it seems that there was appeared some length-limit for dashboard page - I place more than 10 full-wide visualizations in one dashboard and can't make a correct place for last visualizations, they are overlapped.

Thank you.

**Comment by arikfr** [comment]
Did you try deploying a more recent build of v4 and checking if this is still an issue?
