### ISSUE TITLE
HTML link in Plotly chart not working anymore

### ISSUE THREAD

**Issue by deecay** [getredash/redash#2114]
HTML link in chart viz as xaxis category is not working anymore.

Create a bar chart with xaxis as a categorical axis of an HTML-linked column. Clicking the category name in the xaxis used to jump to the desired page, but now it doesn't.

`xtick` tag in Plotly@codepen:
```
<a xlink:show="new" target="_blank" xlink:href="https://codepen.io/plotly/pen/aa" style="cursor:pointer">aa</a></text>
```
Current Plotly viz:
```
<a style="cursor:pointer">Category1</a></text>
```

As you can see, attribures xlink:show, target, xlink:href are stripped.
It used to work in 3.0.0. 
@kravets-levko This may be related to design change. Sorry if I'm wrong!

**Comment by arikfr** [comment]
Can you check if v3 had different Plotly version? If it has, maybe it's a change in Plotly?

**Comment by deecay** [comment]
v3 uses Plotly v1.30.1. This is PR 85da5fc, which was merged on Oct. 4th. Current HEAD uses the same version, but the link doesn't work.

In addition, I confirmed that it does work in demo.redash. See https://demo.redash.io/queries/3942#8727

**Comment by kravets-levko** [comment]
Hi @deecay!

I checked this, and seems that it works in master:

![image](https://user-images.githubusercontent.com/12139186/35618723-75f6aaba-0684-11e8-9cbf-5dc28902439e.png)

Can you please check it and confirm that it's solved or still does not work? Thanks!

**Comment by deecay** [comment]
Yup. It's gone now. Thanks!
