### ISSUE TITLE
Multiple redash servers should use single DB

### ISSUE THREAD

**Issue by sunilkumarvytla** [getredash/redash#2115]
Hello All,

We are using single Redash server as a Analytics tool and We all know each redash server should comes with its own db i.e postgres . So now I want to create a multiple redash servers and all the remaining servers should connect to single db within any one of the redash server ..? Inshort. SingleDb should be shared across multiple servers . I mean I will have multiple redash servers , suppose I have 3 redash servers, one of the redash server should store all the information in the db and other two servers should connect to that server DB. Is there anything I can set it in env file ..?

I think I have to configure other instances to use the same database by changing the db host and of course I need to allow the db to accept requests from other machines for this to work but I am unable to achieve it bcoz there is nothing found in Redash documentation .
Could you guys please help me out ..?

I am using Redash 2.0.1 version and Ubuntu 16.04 OS.

Thanks,
Sunil

**Comment by arikfr** [comment]
There is a configuration value for the database (`REDASH_DATABASE_URL`). You just need to make sure all of them use the same one.

Also for support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.
