### ISSUE TITLE
Percentage stacking doesn't work for line charts

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2116]

**Comment by arikfr** [comment]
Resolved in #2156 (part of the v4 release).

**Comment by kravets-levko** [comment]
@innovia Please add screenshots of settings for this chart. Thanks!

**Comment by kravets-levko** [comment]
@innovia it's strange. anyway - thanks for this report, I'll try to reproduce it. if there is a bug - we definitely should fix it :wink:
