### ISSUE TITLE
How to install redash in Debian9?

### ISSUE THREAD

**Issue by bobos008** [getredash/redash#2119]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by bobos008** [comment]
您输入的可能是: 英语

In the reddish/setup/ubuntu/bootstrap.sh, installed by the SH bootstrap.sh system, I used debian9, error: Command "/usr/bin/python -u -c" import setuptools, tokenize; __file__='/tmp/pip-build-NmmWnX/cryptography/setup.py'; f=getattr (tokenize,'open', open) (__file__); code=f.read (.Replace) ('\r\n','\n'); (f.close); exec (compile (code, __file__ "install --record,'exec')) /tmp/pip-Rruk9B-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-NmmWnX/cryptography/

**Comment by arikfr** [comment]
It seems like an issue with Pip's version. Try upgrading it. 

Also for support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.
