### ISSUE TITLE
Can't find google spreadsheet data source under data sources.

### ISSUE THREAD

**Issue by rajsharma1612** [getredash/redash#2121]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary
I'm trying to create a data source using google spreadsheet, but can't fund under data source. It used to be under data sources but now I'm unable to fund that.

A summary of the issue and the browser/OS environment in which it occurs.
Amazon Linxu
### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by arikfr** [comment]
For support and usage questions, please use the [forum](https://discuss.redash.io). There was already a discussion about this there, just search for Google Spreadsheets or something similar.

Thanks.
