### ISSUE TITLE
Redash Upgrade Error

### ISSUE THREAD

**Issue by malinc854** [getredash/redash#2125]
### Issue Summary

after upgrading, I am trying to restart supervisor service and getting this

Failed to stop supervisor.service: Unit supervisor.service not loaded.

**Comment by malinc854** [comment]
I found it in troubleshoot guide

**Comment by malinc854** [comment]
I upgraded pyOpenSSL to required version as mentioned in troubleshoot but still facing same issue

**Comment by arikfr** [comment]
For support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.
