### ISSUE TITLE
Table looks empty at first when querying for a single number

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2128]
![image](https://user-images.githubusercontent.com/71468/33655517-e9cf31b2-da7b-11e7-8443-40db3662525e.png)

At first I thought there is a bug and I got an empty result, but then I noticed the column on the right...

Any ideas on how to address this?

@kravets-levko @kocsmy

**Comment by arikfr** [comment]
(to reproduce on your own just run a query like `SELECT 1`)

**Comment by kravets-levko** [comment]
1. make table auto-width instead of 100%-width.
2. show results count above the table.

**Comment by arikfr** [comment]
Can you elaborate on #1?

**Comment by kravets-levko** [comment]
I don't thins it's a great idea actually, but one of possible options. Currently table has `width: 100%`; we can make it `width: auto` so it will take a smallest possible width, so in example in this issue, it will have width about 100-150px, so user will see that there are some data.

**Comment by arikfr** [comment]
I'm not sure it's that bad. This:

![image](https://user-images.githubusercontent.com/71468/33656252-251fdfc6-da7e-11e7-9939-0446f28a1fa7.png)

Becomes this:
![image](https://user-images.githubusercontent.com/71468/33656259-2b7221cc-da7e-11e7-9ee1-e56c5f35faba.png)

The only change this will require is to align the pagination to the left too.

As an alternative is it possible to set the table to 100%, but the columns to `auto` and take the smallest needed space?

**Comment by arikfr** [comment]
Here's another example for the issue:
![image](https://user-images.githubusercontent.com/71468/33656328-6f0c8d28-da7e-11e7-80c1-95c7aa8b92dd.png)

Here you can see all the data, but it's hard to connect the count with the action. So you need to either move the count column or realign it. But out of the box, the data is not readable.

**Comment by kravets-levko** [comment]
In general - yes, it's possible, but with "hack": we need to add a column at the end and set it's width to `auto`; and set width for other columns to something very small - like `0.0001%`. But I'm not sure about the case with a lot of columns - that extra column may behave strangely.

**Comment by arikfr** [comment]
Yeah, this feels like too much of a hack.

So who's in favor of `width: auto` for the whole table? :-) (you can vote on this comment)

**Comment by kravets-levko** [comment]
I will wait a bit - maybe @kocsmy will have other (better :-) ) ideas

**Comment by kocsmy** [comment]
If we have only 1 column to show, that should be aligned to the left by default (and I guess the user can still customise and move it to the right if she like).

**Comment by kocsmy** [comment]
For 2 columns, one very much on the left and the other one on the right: I'd keep it as it is for now. We still have hover to highlight the row, and the user can align the right column content to the left so it gets closer.

Or a slight improvement would be to maximise the column width in its content, but that'll lead to the same hack that @kravets-levko just mentioned. 

An ultimate solution would be a more comprehensive spreadsheet table where you can resize the columns.

**Comment by kocsmy** [comment]
If you'd rather go width: auto, this is how it looks like if we properly align:
<img width="1400" alt="screenshot 2017-12-06 12 55 37" src="https://user-images.githubusercontent.com/2378022/33660671-f069aa26-da84-11e7-97bf-0ba443f15c0d.png">
<img width="1409" alt="screenshot 2017-12-06 12 56 21" src="https://user-images.githubusercontent.com/2378022/33660672-f2a4b556-da84-11e7-8200-ec0697b91454.png">

**Comment by kravets-levko** [comment]
I like how it looks with `width: auto`
