### ISSUE TITLE
On upgrade to 3.0 flask==0.11.1 isn't found

### ISSUE THREAD

**Issue by ddimmich** [getredash/redash#2131]
Could be due to pypi getting updated to the new warehouse system?

When I follow the upgrade instructions as below I get:

cd /opt/redash/current
sudo bin/upgrade

Starting Redash upgrade:
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Found version: 3.0.0
Current version: 2.0.1+b3080
* Before doing an upgrade, please make sure you have a backup.
* If you have any issues, please refer to the troubleshooting section in the upgrade guide:
  https://redash.io/help-onpremise/maintenance/how-to-upgrade-redash.html
* If the upgrade guide doesn't help, you can ask for help on the forum (https://discuss.redash.io).

Full CHANGELOG for this release: https://github.com/getredash/redash/blob/master/CHANGELOG.md
Continue with upgrade? (y/n): y
Downloading release tarball...
Unpacking to: redash.3.0.0.b3134...
Changing ownership to redash...
Linking .env file...
Installing new Python packages (if needed)...
Failed running: sudo pip install -r /opt/redash/redash.3.0.0.b3134/requirements.txt
Exit status: 1
Output:
Downloading/unpacking Flask==0.11.1 (from -r /opt/redash/redash.3.0.0.b3134/requirements.txt (line 1))
  Cannot fetch index base URL http://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement Flask==0.11.1 (from -r /opt/redash/redash.3.0.0.b3134/requirements.txt (line 1))
No distributions at all found for Flask==0.11.1 (from -r /opt/redash/redash.3.0.0.b3134/requirements.txt (line 1))

**Comment by arikfr** [comment]
Did you try upgrading `pip` itself?

**Comment by ddimmich** [comment]
Humm - might be the python ecosystem in general 

/opt/redash$ sudo pip install -U pip
Cannot fetch index base URL http://pypi.python.org/simple/
Could not find any downloads that satisfy the requirement pip in /usr/lib/python2.7/dist-packages
No distributions at all found for pip in /usr/lib/python2.7/dist-packages


Thanks.

**Comment by ddimmich** [comment]
Was due to an older pip install as @arikfr suggested (default debian 8 version) - to fix you need to :
pip install --index-url=https://pypi.python.org/simple/ --upgrade pip

As the http version doesn't exist any more.
