### ISSUE TITLE
Table pagination overlapping header line in dashboard

### ISSUE THREAD

**Issue by tonyjiangh** [getredash/redash#2132]
### Issue Summary
Not sure if it's just me or what.
I found that pagination's displayed on the top of the table in dashboard, overlapping the header line.
Guessing query view is the right one?

**Table in query:**
<img width="889" alt="image" src="https://user-images.githubusercontent.com/16881036/33662980-6d38070e-dad1-11e7-8833-7e6663b3e147.png">

**Table in dashboard:**
<img width="460" alt="image" src="https://user-images.githubusercontent.com/16881036/33662997-85907480-dad1-11e7-8b67-033e34103f9a.png">

### Technical details:

* Redash Version: 4.0.0
   * Commit: 868f334471a03f0f4fac721dca4744af377d1726
* Browser/OS: Firefox / Chrome
* How did you install Redash: development env with docker

**Comment by arikfr** [comment]
Fixed in f02c0e0b9ce55f5f3b5a41231d74691d2c90d23f and will be merged to master once #2126 is merged.
