### ISSUE TITLE
Case insensitive parameters in Redash query result cache

### ISSUE THREAD

**Issue by albrycht** [getredash/redash#2137]
### Issue Summary

Redash may display wrong results for query with case sensitive parameter. It looks like results cache is ignoring param letters size.

### Steps to Reproduce

1. Create a query with global text parameter.
2. Create dashboard with visualization for this query.
3. Open dashboard with parameter set to lowercase letter for example 'test'
4. Open dashboard on a new tab with parameter 'TEST'. 

In the last step you should receive visualization for parameter 'test' even when parameter value is set to 'TEST'

I have been able to reproduce this scenario on demo.redash.io. To reproduce do:

1. Open link: http://demo.redash.io/dashboard/ma_dashboard?p_dashboard_name=test
You should see rows from dashboard table with name `test`
2. Open link: http://demo.redash.io/dashboard/ma_dashboard?p_dashboard_name=Test
You should see rows from dashboard table with name `test` even when parameter `dashboard_name` is set to `Test`. After refreshing visualization result changed to proper one.

### Technical details:

* Redash Version: 3.0.0+b3134
* Browser/OS: Chrome/Firefox/Opera
* How did you install Redash: used demo.redash.io

**Comment by arikfr** [comment]
The problem is in the [`redash.utils.gen_query_hash`](https://github.com/getredash/redash/blob/073db37cfda27a33570339b6f4e34d69ff6032bf/redash/utils/__init__.py#L47-L57) method. And it's actually documented there as a TODO item 😳 

I think we can stop lower casing the query in this method. We don't need to dedup that aggressively.

**Comment by ClaudioDavi** [comment]
Hi, I've looked around at the code, reproduced the error and I think this can be my first PR.
@arikfr your suggestion is to remove the .lower() when we're creating the hash?

**Comment by arikfr** [comment]
@ClaudioDavi yes, but also need a migration to recalculate the query hash for all existing queries.

**Comment by ClaudioDavi** [comment]
Ok, thanks @arikfr ! Do you have any migration examples for me to have a look and follow through?

**Comment by Ceaustin117** [comment]
Hey was this fixed? I am using redash and the issue still seems to exist
