### ISSUE TITLE
Add a new column type for images

### ISSUE THREAD

**Issue by yalisassoon** [getredash/redash#2138]
In table visualizations there are a number of use cases where it is nice to embed images in a column e.g.:

1. In retail, for product reports, having a visualization of the product
2. Having a logo or a map if you're reporting by brand or greography
3. Having a "flag" if e.g. a metric is above or below a certain threshold

I believe that embedding images is possible now via a hack - it would be nice to make this feature "official"

**Comment by arikfr** [comment]
Here's an example for the current workaround: http://demo.redash.io/queries/1896/source#table.

**Comment by kravets-levko** [comment]
Hi @yalisassoon! I started working on your request, and here is my PR: getredash/redash/pull/2283 It's in progress, but if you have any notices or ideas - feel free to comment there. Thanks!

**Comment by RichardLitt** [comment]
Thanks @kravets-levko! This was merged a couple of days ago, and should be all set now.

**Comment by kravets-levko** [comment]
You're right @RichardLitt, it was merged few days ago, but also few day after my invitation to discuss it :smiley:
