### ISSUE TITLE
about saml authentification

### ISSUE THREAD

**Issue by apetitdev** [getredash/redash#2142]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary
I am brand new with SAML authentification but I can't get it work with my single sign on server.
At least not with the here https://redash.io/help-onpremise/setup/saml-authentication-and-authorization.html.
I have implemented saml auth on my server, let's say http://mysinglesignonserver.com
so I have this endpoint available on my server:
http://mysinglesignonserver.com/auth/sam
http://mysinglesignonserver.com/auth/saml/metadata
http://mysinglesignonserver.com/auth/saml/callback?SAMLResponse=
Now I update my .env file in redash
REDASH_SAML_METADATA_URL=https://mysinglesignonserver/auth/saml/metadata
REDASH_SAML_LOGIN_ENABLED=True
when I go to http://my_redashserver.com/saml/login
it will always trigger the error
IdpUnspecified: No IdP to send to given the premises
which is from pysaml here 
https://github.com/rohe/pysaml2/blob/master/src/saml2/client_base.py#L176
Indeed metada doesn't have idpsso item because this seems to be missing 
https://github.com/getredash/redash/blob/master/redash/authentication/saml_auth.py#L46
So I was wondering what I am missing. 
Is the idpsso need to be return in the metada here 
https://mysinglesignonserver/auth/saml/metadata ? (found this here https://stackoverflow.com/questions/18868497/djangosaml2-cannot-serialize-idpunspecifiedno-idp-to-send-to-given-the-premis)
My best guess is yes but just to be confirmed
Did I missed one variable in the .env?
Also I wonder how to force system to only use my single sign on server to log into my redash server.
Thanks for help and for this great tool.

### Steps to Reproduce

1. use saml for authentification
- update .env file with:
```
REDASH_SAML_METADATA_URL=https://mysinglesignonserver/auth/saml/metadata
REDASH_SAML_LOGIN_ENABLED=True
```
2. Update my server to have 
https://mysinglesignonserver/auth/saml/metadata
https://mysinglesignonserver/auth/saml/auth

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
To be able to use single sign on on the 
http://my_redashserver.com/saml/login

### Technical details:

* Redash Version: v2.0.1
* Browser/OS: All Browsers / Mac Os High Sierra
* How did you install Redash:  https://redash.io/help-onpremise/dev/setup.html with virtualenv

**Comment by arikfr** [comment]
> Also I wonder how to force system to only use my single sign on server to log into my redash server.

Just disable password login (`REDASH_PASSWORD_LOGIN_ENABLED` env variable).

As for the SAML issues: I'm not sure if it's an issue in Redash implementation, missing configuration or something else. Please post similar question in [our forum](discuss.redash.io).

I'm closing this now, but please post it on the forum and follow up here in case you find an issue with our implementation.

Thanks.

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
