### ISSUE TITLE
docker-compose installation stop with SQL errors

### ISSUE THREAD

**Issue by Stephane-Thales** [getredash/redash#2149]
Hi All,

I'm trying to install redash using docker-compose on Linux Ubuntu 16.04.
I've installed docker, docker-compose, nodejs npm
I unziped the full GIT in a dedicated folder.
then from this folder I started
`docker-compose up`

the install start and run for few minutes, then 

first error :

`
worker_1    | [2017-12-11 01:49:01,392][PID:11][INFO][Worker-3] Current version: 4.0.0
worker_1    | [2017-12-11 01:49:01,392][PID:10][INFO][Worker-2] task_name=redash.tasks.refresh_schemas task_id=f7f34432-7a57-4be6-b2d5-01ba56e54e44 task=refresh_schemas state=start
worker_1    | [2017-12-11 01:49:01,393][PID:1][INFO][MainProcess] Received task: redash.tasks.cleanup_tasks[2972f10c-7a17-41da-ab5b-1288176cf45e]
worker_1    | [2017-12-11 01:49:01,396][PID:1][INFO][MainProcess] Received task: redash.tasks.refresh_queries[f73de587-681d-4820-9f33-b1083ba6cc83]
worker_1    | [2017-12-11 01:49:01,397][PID:1][INFO][MainProcess] Received task: redash.tasks.cleanup_query_results[f63116ca-1258-409f-a78d-0993b30af2ae]
postgres_1  | ERROR:  relation "data_sources" does not exist at character 395
postgres_1  | STATEMENT:  SELECT data_sources.id AS data_sources_id, data_sources.org_id AS data_sources_org_id, data_sources.name AS data_sources_name, data_sources.type AS data_sources_type, data_sources.options AS data_sources_options, data_sources.queue_name AS data_sources_queue_name, data_sources.scheduled_queue_name AS data_sources_scheduled_queue_name, data_sources.created_at AS data_sources_created_at 
postgres_1  | 	FROM data_sources
worker_1    | [2017-12-11 01:49:01,420][PID:1][ERROR][MainProcess] Task redash.tasks.refresh_schemas[f7f34432-7a57-4be6-b2d5-01ba56e54e44] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) relation "data_sources" does not exist\nLINE 2: FROM data_sources\n             ^\n',)
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
`

Many SQL error in between

last error
`
ProgrammingError: (psycopg2.ProgrammingError) relation "queries" does not exist
worker_1    | LINE 2: FROM queries LEFT OUTER JOIN query_results AS query_results_...
`
Here the install freeze.

I run manualy after that :
`docker-compose run --rm server create_db`
that look like working

but with 
`http://localhost:5000/`
I can display the initial login page to setup the admin access, but upon submission I have a web error and i'm stuck.

==> any idea how to fix the install process ?

Best Regards,
Stephane

**Comment by arikfr** [comment]
Hi,

Running `create_db` is one of the required steps to make it work, until you run the application will indeed complain about missing columns.

Did you run the setup phase after running `create_db`? If you have, what is the current server error you're getting?

**Comment by Stephane-Thales** [comment]
Hi,

I've the following error message on the web page just after submitting the admin access:
`Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application`

What are the setup phase ?

**Comment by arikfr** [comment]
setup phase -- the dialog that asks you for name, email and account name.

Anyway by current server error I meant what do you see in the logs...

**Comment by Stephane-Thales** [comment]
Hi,

Noted Arikfr, (logs of the last error at the end of this message)
I've rerun the full install once again.

My understanding is that there is an error with the initial setting up of the docker-compose environnement.
the whole install run smoothly until that step : 

`
server_1    | [2017-12-13 01:47:43,044][PID:1][INFO][werkzeug]  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
server_1    | [2017-12-13 01:47:43,047][PID:1][INFO][werkzeug]  * Restarting with stat
worker_1    | [2017-12-13 01:47:43,138][PID:1][INFO][MainProcess] Connected to redis://redis:6379/0
worker_1    | [2017-12-13 01:47:43,152][PID:1][INFO][MainProcess] mingle: searching for neighbors
worker_1    | [2017-12-13 01:47:43,306][PID:13][INFO][Beat] beat: Starting...
worker_1    | [2017-12-13 01:47:43,572][PID:13][INFO][Beat] Scheduler: Sending due task cleanup_query_results (redash.tasks.cleanup_query_results)
worker_1    | [2017-12-13 01:47:43,628][PID:13][INFO][Beat] Scheduler: Sending due task refresh_queries (redash.tasks.refresh_queries)
worker_1    | [2017-12-13 01:47:43,630][PID:13][INFO][Beat] Scheduler: Sending due task cleanup_tasks (redash.tasks.cleanup_tasks)
worker_1    | [2017-12-13 01:47:43,632][PID:13][INFO][Beat] Scheduler: Sending due task refresh_schemas (redash.tasks.refresh_schemas)
server_1    | [2017-12-13 01:47:43,824][PID:12][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
server_1    | [2017-12-13 01:47:43,845][PID:12][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
worker_1    | [2017-12-13 01:47:44,159][PID:1][INFO][MainProcess] mingle: all alone
worker_1    | [2017-12-13 01:47:44,221][PID:1][WARNING][MainProcess] celery@d8f5345f3ba7 ready.
worker_1    | [2017-12-13 01:47:44,225][PID:1][INFO][MainProcess] Received task: redash.tasks.cleanup_query_results[fcbace08-71b9-40f8-a87f-03cec876a3cd]
worker_1    | [2017-12-13 01:47:44,227][PID:1][INFO][MainProcess] Received task: redash.tasks.refresh_queries[4322247f-a019-4f79-b730-c8f25f7ee065]
worker_1    | [2017-12-13 01:47:44,228][PID:11][INFO][Worker-2] Running query results clean up (removing maximum of 100 unused results, that are 7 days old or more)
worker_1    | [2017-12-13 01:47:44,228][PID:12][INFO][Worker-3] task_name=redash.tasks.refresh_queries task_id=4322247f-a019-4f79-b730-c8f25f7ee065 Refreshing queries...
worker_1    | [2017-12-13 01:47:44,229][PID:1][INFO][MainProcess] Received task: redash.tasks.cleanup_tasks[1037d4ba-ef01-4535-acb3-8f48085fe4bd]
worker_1    | [2017-12-13 01:47:44,231][PID:1][INFO][MainProcess] Received task: redash.tasks.refresh_schemas[b099d691-a3ab-420b-b8ff-072aeb1ad17c]
postgres_1  | ERROR:  relation "query_results" does not exist at character 13
postgres_1  | STATEMENT:  DELETE FROM query_results WHERE query_results.id IN (SELECT query_results.id 
postgres_1  | 	FROM query_results LEFT OUTER JOIN queries ON query_results.id = queries.latest_query_data_id 
postgres_1  | 	WHERE queries.id IS NULL AND query_results.retrieved_at < '2017-12-06T01:47:44.228953'::timestamp 
postgres_1  | 	 LIMIT 100)
postgres_1  | ERROR:  relation "queries" does not exist at character 901
postgres_1  | STATEMENT:  SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, query_results_1.id AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at 
postgres_1  | 	FROM queries LEFT OUTER JOIN query_results AS query_results_1 ON query_results_1.id = queries.latest_query_data_id 
postgres_1  | 	WHERE queries.schedule IS NOT NULL ORDER BY queries.id
worker_1    | [2017-12-13 01:47:44,336][PID:1][ERROR][MainProcess] Task redash.tasks.refresh_queries[4322247f-a019-4f79-b730-c8f25f7ee065] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) relation "queries" does not exist\nLINE 2: FROM queries LEFT OUTER JOIN query_results AS query_results_...\n             ^\n',)
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
worker_1    |     R = retval = fun(*args, **kwargs)
worker_1    |   File "/app/redash/worker.py", line 71, in __call__
worker_1    |     return TaskBase.__call__(self, *args, **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
worker_1    |     return self.run(*args, **kwargs)
worker_1    |   File "/app/redash/tasks/queries.py", line 275, in refresh_queries
worker_1    |     for query in models.Query.outdated_queries():
worker_1    |   File "/app/redash/models.py", line 933, in outdated_queries
worker_1    |     for query in queries:
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2797, in __iter__
worker_1    |     return self._execute_and_instances(context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2820, in _execute_and_instances
worker_1    |     result = conn.execute(querycontext.statement, self._params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
worker_1    |     return meth(self, multiparams, params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
worker_1    |     return connection._execute_clauseelement(self, multiparams, params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
worker_1    |     compiled_sql, distilled_params
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
worker_1    |     context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
worker_1    |     exc_info
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
worker_1    |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
worker_1    |     context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 469, in do_execute
worker_1    |     cursor.execute(statement, parameters)
worker_1    | ProgrammingError: (psycopg2.ProgrammingError) relation "queries" does not exist
worker_1    | LINE 2: FROM queries LEFT OUTER JOIN query_results AS query_results_...
worker_1    |              ^
worker_1    |  [SQL: 'SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, query_results_1.id AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at \nFROM queries LEFT OUTER JOIN query_results AS query_results_1 ON query_results_1.id = queries.latest_query_data_id \nWHERE queries.schedule IS NOT NULL ORDER BY queries.id']
server_1    | [2017-12-13 01:47:44,340][PID:12][WARNING][werkzeug]  * Debugger is active!
worker_1    | [2017-12-13 01:47:44,341][PID:1][ERROR][MainProcess] Task redash.tasks.cleanup_query_results[fcbace08-71b9-40f8-a87f-03cec876a3cd] raised unexpected: ProgrammingError('(psycopg2.ProgrammingError) relation "query_results" does not exist\nLINE 1: DELETE FROM query_results WHERE query_results.id IN (SELECT ...\n                    ^\n',)
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
worker_1    |     R = retval = fun(*args, **kwargs)
worker_1    |   File "/app/redash/worker.py", line 71, in __call__
worker_1    |     return TaskBase.__call__(self, *args, **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
worker_1    |     return self.run(*args, **kwargs)
worker_1    |   File "/app/redash/tasks/queries.py", line 357, in cleanup_query_results
worker_1    |     ).delete(synchronize_session=False)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 3155, in delete
worker_1    |     delete_op.exec_()
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1168, in exec_
worker_1    |     self._do_exec()
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/persistence.py", line 1352, in _do_exec
worker_1    |     mapper=self.mapper)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1107, in execute
worker_1    |     bind, close_with_result=True).execute(clause, params or {})
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 945, in execute
worker_1    |     return meth(self, multiparams, params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
worker_1    |     return connection._execute_clauseelement(self, multiparams, params)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
worker_1    |     compiled_sql, distilled_params
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
worker_1    |     context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1393, in _handle_dbapi_exception
worker_1    |     exc_info
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 202, in raise_from_cause
worker_1    |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
worker_1    |     context)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 469, in do_execute
worker_1    |     cursor.execute(statement, parameters)
worker_1    | ProgrammingError: (psycopg2.ProgrammingError) relation "query_results" does not exist
worker_1    | LINE 1: DELETE FROM query_results WHERE query_results.id IN (SELECT ...
....
`
 
after few more error like that, I stop the docker,
run `docker-compose run --rm server create_db`
then restart the docker-compose
from then I can access the setup phase in a browser (name, email and account name)
upon submit I've the error in the browser, and the log show : 

`worker_1    | [2017-12-13 01:58:33,856][PID:1][INFO][MainProcess] Received task: redash.tasks.subscribe[d88aa662-0440-49a7-b224-f0d2ca1baf29]
worker_1    | [2017-12-13 01:58:33,858][PID:12][INFO][Worker-3] task_name=redash.tasks.subscribe task_id=d88aa662-0440-49a7-b224-f0d2ca1baf29 Subscribing to: [security notifications=True], [newsletter=True]
server_1    | [2017-12-13 01:58:33,859][PID:12][INFO][werkzeug] 172.19.0.1 - - [13/Dec/2017 01:58:33] "POST /setup HTTP/1.1" 302 -
worker_1    | [2017-12-13 01:58:33,863][PID:1][INFO][MainProcess] Task redash.tasks.record_event[590a1b18-fe52-4711-8cab-7fe6e8f00ce3] succeeded in 0.0106684769999s: None
server_1    | [2017-12-13 01:58:33,904] ERROR in app: Exception on / [GET]
server_1    | Traceback (most recent call last):
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
server_1    |     response = self.full_dispatch_request()
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
server_1    |     rv = self.handle_user_exception(e)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
server_1    |     return original_handler(e)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
server_1    |     reraise(exc_type, exc_value, tb)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
server_1    |     rv = self.dispatch_request()
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
server_1    |     return self.view_functions[rule.endpoint](**req.view_args)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
server_1    |     return func(*args, **kwargs)
server_1    |   File "/app/redash/handlers/static.py", line 41, in index
server_1    |     return render_index()
server_1    |   File "/app/redash/handlers/static.py", line 34, in render_index
server_1    |     response = send_file(full_path, **dict(cache_timeout=0, conditional=True))
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 536, in send_file
server_1    |     file = open(filename, 'rb')
server_1    | IOError: [Errno 2] No such file or directory: '/app/redash/../client/dist/index.html'
server_1    | [2017-12-13 01:58:33,904][PID:12][ERROR][redash] Exception on / [GET]
server_1    | Traceback (most recent call last):
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
server_1    |     response = self.full_dispatch_request()
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1641, in full_dispatch_request
server_1    |     rv = self.handle_user_exception(e)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask_restful/__init__.py", line 271, in error_router
server_1    |     return original_handler(e)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1544, in handle_user_exception
server_1    |     reraise(exc_type, exc_value, tb)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
server_1    |     rv = self.dispatch_request()
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
server_1    |     return self.view_functions[rule.endpoint](**req.view_args)
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
server_1    |     return func(*args, **kwargs)
server_1    |   File "/app/redash/handlers/static.py", line 41, in index
server_1    |     return render_index()
server_1    |   File "/app/redash/handlers/static.py", line 34, in render_index
server_1    |     response = send_file(full_path, **dict(cache_timeout=0, conditional=True))
server_1    |   File "/usr/local/lib/python2.7/dist-packages/flask/helpers.py", line 536, in send_file
server_1    |     file = open(filename, 'rb')
server_1    | IOError: [Errno 2] No such file or directory: '/app/redash/../client/dist/index.html'
server_1    | [2017-12-13 01:58:33,921][PID:12][INFO][metrics] method=GET path=/ endpoint=redash_index status=500 content_type=? content_length=-1 duration=57.02 query_count=2 query_duration=4.46
server_1    | [2017-12-13 01:58:33,922][PID:12][INFO][werkzeug] 172.19.0.1 - - [13/Dec/2017 01:58:33] "GET / HTTP/1.1" 500 -
worker_1    | [2017-12-13 01:58:35,455][PID:1][INFO][MainProcess] Task redash.tasks.subscribe[d88aa662-0440-49a7-b224-f0d2ca1baf29] succeeded in 1.597558767s: None
worker_1    | [2017-12-13 01:58:58,633][PID:13][INFO][Beat] Scheduler: Sending due task refresh_queries (redash.tasks.refresh_queries)
worker_1    | [2017-12-13 01:58:58,638][PID:1][INFO][MainProcess] Received task: redash.tasks.refresh_queries[855465db-bd81-47de-b2c3-c1627baba81f]
worker_1    | [2017-12-13 01:58:58,640][PID:12][INFO][Worker-3] task_name=redash.tasks.refresh_queries task_id=855465db-bd81-47de-b2c3-c1627baba81f Refreshing queries...
worker_1    | [2017-12-13 01:58:58,647][PID:12][INFO][Worker-3] task_name=redash.tasks.refresh_queries task_id=855465db-bd81-47de-b2c3-c1627baba81f Done refreshing queries. Found 0 outdated queries: []
worker_1    | [2017-12-13 01:58:58,648][PID:1][INFO][MainProcess] Task redash.tasks.refresh_queries[855465db-bd81-47de-b2c3-c1627baba81f] succeeded in 0.00869242100453s: None

`

**Comment by Stephane-Thales** [comment]
Hi,  
in complement I run
`docker-compose run --rm server tests`
and the end message is : ` 360 failed, 69 passed in 257.35 seconds`

that don't look good...

**Comment by arikfr** [comment]
Looks like you skipped the `npm install` step (see [here](https://redash.io/help-onpremise/dev/docker.html)).

**Comment by Stephane-Thales** [comment]
Hi I followed the procedure, but npm install is also failing  :

`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.3
npm ERR! Linux 4.10.0-42-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script 'node lib/post_install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the uglifyjs-webpack-plugin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/post_install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs uglifyjs-webpack-plugin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls uglifyjs-webpack-plugin
npm ERR! There is likely additional logging output above.

`

**Comment by arikfr** [comment]
You probably need a newer version of Node.js and npm.

**Comment by Stephane-Thales** [comment]
Hi 
Thank you !
You are correct I had the versions :

$nodejs --version
v4.2.6
$ npm --version
3.5.2

I've updated to

$nodejs --version
v9.3.0
$ npm --version
5.5.1

and the install run much better.
Now I can access the interface.
thank-you
