### ISSUE TITLE
Redshift schema browser not showing late-binding view

### ISSUE THREAD

**Issue by tonyjiangh** [getredash/redash#2151]
### Issue Summary
SSIA
**Not requesting any code change for now** (reasons followed)

Further notes:
- It's not access right problem. I can query the views.
- I can see that we're using [SVV_COLUMNS](http://docs.aws.amazon.com/redshift/latest/dg/r_SVV_COLUMNS.html) here for Redshift's schema, which should contain information for late-binding views.

It seems like a redshift-side's bug, though I'm not sure if It's global or only happens in Tokyo region.

### Current state
I've submitted an issue regarding this problem to AWS support desk. I guess it's better to wait for the answer first.

### Technical details:

* Redash Version: Redash 3.0.0+b3134
* Browser/OS: Both chrome / firefox
* How did you install Redash: Docker

**Comment by arikfr** [comment]
Thank you for the detailed report. Looking forward for AWS's reply :)

**Comment by tonyjiangh** [comment]
Update:
- The reply from AWS says the document was wrong: SVV_COLUMNS should not contain information for late binding view. 👎 
- They had already changed document of SVV_COLUMNS and removed contents about late binding view.
- I'll submit a PR regarding this issue later.
