### ISSUE TITLE
Remove loading indicator when updating query parameter value (before executing)

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2161]
Pace gets triggered whenever History pushState is called. We actually need to trigger only when there is an HTTP request.

We can either configure Pace to ignore pushState or switch to: https://github.com/chieffancypants/angular-loading-bar.

**Comment by kocsmy** [comment]
Yes, please! I believe this is massively disturbing. Also we'll need a Run/Execute button next to the parameter so users don't need spend time figuring out how it works (current Execute button is far from this element and very much disconnected so it's hard to figure out).
