### ISSUE TITLE
Cohort adds extra columns

### ISSUE THREAD

**Issue by Gromph** [getredash/redash#2163]
### Issue Summary
I wanted to have an asymmetrical cohort chart go further back in time, ie have 30 days of rows, but each row be 7 days wide. The problem is the generated Cohort graph is 30 days wide, so it basically added 23 extra columns full of 0.00%'s
In the example below I used 5 days of rows, and 2 days wide for brevity.

### Steps to Reproduce

1.  Here is the query:
WITH days as (	SELECT seq as day_number FROM seq_1_to_2	)
SELECT DATE(date_joined) AS date, day_number, sum(DATEDIFF(DATE(last_login), DATE(date_joined)) >= day_number) as value, count(distinct id) as total
FROM auth_user, days
WHERE DATE(date_joined) > NOW() - interval 5 day
GROUP BY  date, day_number

2. Here is the data set it generates:
date,day_number,value,total
2017-12-10,1,215.0,637
2017-12-10,2,168.0,637
2017-12-11,1,195.0,566
2017-12-11,2,133.0,566
2017-12-12,1,159.0,528
2017-12-12,2,75.0,528
2017-12-13,1,113.0,519
2017-12-13,2,0.0,519
2017-12-14,1,0.0,301
2017-12-14,2,0.0,301

3. Which results in this chart:
![redashcohort](https://user-images.githubusercontent.com/361560/34018880-eb7d2a76-e0e0-11e7-8029-422285e36dfc.png)

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
Columns for day 3 and 4 shouldn't be there. There is no 3 or 4 in the day_number column in the data set.  This gets very ugly when I tried to make a table 30 days long by 7 days wide.

### Technical details:

* Redash Version: 3.0.0+b3134
* Browser/OS: Firefox 57.0.2
* How did you install Redash: AWS AMI

**Comment by Gromph** [comment]
Also I tried to skip columns, ie out of 30 days only show 1, 2, 3, 14, 30, but it filled in all the missing days with columns full of 0.00%, ie here is how I generated the days:
SELECT seq as day_number FROM seq_1_to_3 union select seq as day_number from seq_14_to_14 union select seq as day_number from seq_30_to_30

**Comment by arikfr** [comment]
@kravets-levko can you please upload a screenshot of how the cohort looks like following the work you did in #2281, so @Gromph can confirm this fixes his issue?

**Comment by kravets-levko** [comment]
Sure:

![image](https://user-images.githubusercontent.com/12139186/35966921-f532c252-0cc7-11e8-9d33-73b7a64727e0.png)
![image](https://user-images.githubusercontent.com/12139186/35966935-0068bd5c-0cc8-11e8-9215-844f951b92b9.png)

**Comment by Gromph** [comment]
Yup looks good, thanks.

**Comment by arikfr** [comment]
Super. Thank you for reporting and verifying, @Gromph.
