### ISSUE TITLE
Missing Release v3.0.0 in releases and setup docs

### ISSUE THREAD

**Issue by victorbrin-adroll** [getredash/redash#2169]
### Issue Summary

Latest Release v3.0.0 - 2017-11-13
https://github.com/getredash/redash/blob/master/CHANGELOG.md

Missing Release v3.0.0 in both:
https://github.com/getredash/redash/releases
https://redash.io/help-onpremise/setup/setting-up-redash-instance.html

### Steps to Reproduce

1. visit https://github.com/getredash/redash/blob/master/CHANGELOG.md
2. visit https://github.com/getredash/redash/releases
3. visit https://redash.io/help-onpremise/setup/setting-up-redash-instance.html

They all should have v3.0.0, but only first list have v3.0.0 as Latest Release

**Comment by arikfr** [comment]
Thank you for the reminder. 

I updated the GitHub releases page. There won't be updated images for v3. The next images will be for v4.
