### ISSUE TITLE
Runtime is inaccurate on active queries list

### ISSUE THREAD

**Issue by vagelim** [getredash/redash#2173]
### Issue Summary
Runtime in active queries list does not reflect actual runtime.

### Steps to Reproduce

1. Go to the list of running queries: https://redash.prod.aws.pbinfra.com/admin/queries/tasks
2. Runtime is never updated from 0s

This differs from my expectations of a constantly incrementing runtime counter.

### Technical details:

Browser: Firefox Quantum 57.0.1 (64-bit)
Redash Version: Redash 4.0.0+b3169
How did you install Redash: Deployed as an ECS service

**Comment by arikfr** [comment]
Is it 0s for all queries? Are those queries with parameters?
