### ISSUE TITLE
UI- filter headers mixed

### ISSUE THREAD

**Issue by galgoogle** [getredash/redash#2183]
When using more than 2 multi-filters, the headers are being shown on the first 2 rows, and not attached to their boxes.

![image](https://user-images.githubusercontent.com/29460916/34327369-25ee68ae-e8cb-11e7-9a07-6673b99977f8.png)

* Redash Version: 3.0.0+b3134
* Browser/OS: Chrome

**Comment by kocsmy** [comment]
It's the [filters.html](https://github.com/getredash/redash/blob/master/client/app/components/filters.html) here:

`<div class="container bg-white p-b-15" ng-show="$ctrl.filters | notEmpty">
  <div class="row">
    <div class="col-sm-6 p-l-0" ng-repeat="filter in $ctrl.filters">
      <label>{{filter.friendlyName}}</label>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 p-l-0" ng-repeat="filter in $ctrl.filters">
      <ui-select ng-model="filter.current" ng-if="!filter.multiple" on-select="$ctrl.filterChangeListener(filter, $model)" on-remove="$ctrl.filterChangeListener(filter, $model)"
        remove-selected="false">
        <ui-select-match placeholder="Select value for {{filter.friendlyName}}...">{{$select.selected | filterValue:filter}}</ui-select-match>
        <ui-select-choices repeat="value in filter.values | filter: $select.search">
          {{value | filterValue:filter }}
        </ui-select-choices>
      </ui-select>

      <ui-select ng-model="filter.current" multiple ng-if="filter.multiple" on-select="$ctrl.filterChangeListener(filter, $model)"
        on-remove="$ctrl.filterChangeListener(filter, $model)" remove-selected="false">
        <ui-select-match placeholder="Select value for {{filter.friendlyName}}...">{{$item | filterValue:filter}}</ui-select-match>
        <ui-select-choices repeat="value in filter.values | filter: $select.search" group-by="$ctrl.itemGroup">
          <span ng-if="value == '*'">
            Select All
          </span>
          <span ng-if="value == '-'">
            Clear
          </span>
          <span ng-if="value != '*' && value != '-'">
            {{value | filterValue:filter }}
          </span>
        </ui-select-choices>
      </ui-select>
    </div>
  </div>
</div>
`

**Comment by galgoogle** [comment]
@kocsmy is it an easy fix?

**Comment by kocsmy** [comment]
I'm checking this today and see if I can fix.

**Comment by kocsmy** [comment]
@galgoogle there you go, just submitted the fix which will make this right.

**Comment by galgoogle** [comment]
@kocsmy thanks a lot! I'll try it on Sunday. Appreciate your quick help!
