### ISSUE TITLE
User can't download dataset - Internal Server Error

### ISSUE THREAD

**Issue by malinc854** [getredash/redash#2191]
Hi,

when ever there a big large number of records, users can't download dataset. It was working perfectly fine for millions of records in previous version. I am on version 2. Please help

**Comment by arikfr** [comment]
Is this a saved query?

**Comment by malinc854** [comment]
Yes. but I found CPU utilization got 100% after every two days. I have to kill the redash processes using below command

sudo kill -9 `ps -ef|grep 'redash' | awk '{print $2}'`

Then for a day CPU stays around 50% and then again to 100% in a day or two.

Please help.

**Comment by arikfr** [comment]
We need more details to understand this better:

* What's your setup looks like in terms of CPU/memory on the server? How much is free?
* What is the size of the dataset you're having problem with?
* Are you trying to download it in JSON, CSV or Excel format?

The CPU utilization issue might be related to Celery workers getting stuck. What kind of data sources are you using?

This looks more like a setup/support issue. You're welcome to follow up and share the extra information in our [forum](https://discuss.redash.io/c/support). If in the discussion there we find an actual actionable issue to fix in Redash, we can open a GitHub issue.

Thanks.

**Comment by malinc854** [comment]
I have setup redash on a pretty good server. It is on EC2 instance having 32 GB RAM with 16 core processor.

It depends on the utilization. If utilization is around 50 then I am having issues while downloading data around 100,000 but with utilization above 95%, I'll face this for hundreds of records.

CSV and excel.. both throwing this exception.

Yes, when I flush my queue, utilization gets down for some time. I can see mysql queries are being stuck mostly in 'saving_result' status. Presto is working fine.

**Comment by RichardLitt** [comment]
Thanks, @malinc854. Can you put this on the forum? We can open a new issue in the future here - for now, it's not clear that this is more than a setup and support issue. Thank you!
