### ISSUE TITLE
Impossible to find supervisord.conf after upgrade

### ISSUE THREAD

**Issue by giansegato** [getredash/redash#2192]
### Issue Summary

I need to get access to the Redash log files, and [here](https://redash.io/help-onpremise/maintenance/ongoing-maintenance-and-basic-operations.html) it says that their location is defined here: `/opt/redash/supervisord/supervisord.conf`.

I've ReDash self-hosted on an AWS machine EC2 machine. It was version 2.0. I upgraded Redash in this way:

```
wget https://raw.githubusercontent.com/getredash/redash/master/bin/upgrade
chmod +x upgrade
sudo pip install -U pyopenssl
sudo ./upgrade
```

Now, if I list the content of `/opt/redash`, what I get is:

> .  ..  current  .env  redash.2.0.0.b2990  redash.3.0.0.b3134  redash.3.0.0.b3134.tar.gz

No `supervisord` folder, nor a `logs` folder.
Inside `current`, there's no `supervisord.conf` file, and ultimately (that is what I'm truly interested in), no log files.

### Steps to Reproduce

`sudo nano /opt/redash/supervisord/supervisord.conf`

that yields:

> [ Directory '/opt/redash/supervisord' does not exist ]

### Technical details:

* Redash Version: 3.0
* Browser/OS: Ubuntu
* How did you install Redash: Amazon image

**Comment by arikfr** [comment]
New images install Supervisor with a system package whose configuration is at a different location (`/etc/supervisor/conf.d/redash.conf`).

We should update the documentation to reflect this.

**Comment by RichardLitt** [comment]
@giansegato Any chance you'd like to help by updating the docs as @arikfr suggests? You have the context already needed for this issue, and that will help others in the future with the same problem. :)

**Comment by giansegato** [comment]
@RichardLitt I'd be happy to! Looks like though that "http://help.redash.io/" (ie. where I can edit the docs) is different than "https://redash.io/help-onpremise/", that is where I should update the docs.

@arikfr How do you suggest I should move forward?

(never contributed to an open project – my question may look trivial)

**Comment by arikfr** [comment]
Currently `help.redash.io` can be updated by the team only, as it's served via HelpScout. But this will change in the near future, when we move the documentation sources back to GitHub.

Luckily `help-onpremise` is still on GitHub, and to update it you just make a pull request to the relevant page source. The source of the page you originally is here: https://github.com/getredash/website/blob/master/onpremise/maintenance/ongoing-maintenance-and-basic-operations.md

Just click on the edit button in GitHub and make the needed changes. 🙏

**Comment by giansegato** [comment]
Done.
