### ISSUE TITLE
Incorrect REDASH_VERSION in ubuntu bootstrap.sh for 3.0.0 tag?

### ISSUE THREAD

**Issue by svloginov** [getredash/redash#2197]
### Issue Summary

REDASH_VERSION variable in v3.0.0 [setup/ubuntu/bootstrap.sh](https://github.com/getredash/redash/blob/v3.0.0/setup/ubuntu/bootstrap.sh) is incorrect (it's REDASH_VERSION-2.0.1.b3080).

**Comment by darylerwin** [comment]
Looks fine to me in the master branch.

**Comment by svloginov** [comment]
Master is correct, right (it was updated 2 days after I've opened the issue). v3.0.0 tag still has incorrect version though. The tag should probably be re-set.

**Comment by arikfr** [comment]
Due to how the release process works the tag is created before the bootstrap script is updated.

Considering the effort required to update the tag vs. how easy it is to pass the version you need as an environment variable (or just update the script), we won't update it.
