### ISSUE TITLE
Redash vs Superset?

### ISSUE THREAD

**Issue by dclong** [getredash/redash#2207]
Both of the 2 products look great and and they seem to have very similar functionalities. Can one give a fair comparison of the two products? Is there any reason that I should choose redash over superset?

**Comment by imbroglioj** [comment]
I tried Superset first. In a graph with YEAR on the X axis and quantities on the y axis, years (x) were ordered by magnitude of y value descending, not by any (alpha, numeric) sort order on x, so the years would be out of order. ISSUES showed the problem was longstanding and not resolved. Finally, Superset did not appear to support multiple users at the same time.
Then I tried Kibana graphing and converted my data to ElasticSearch for a trial.  In addition to the indexing cost, there were some annoying issues with Kibana's treatment of dates and date display (UT vs. local) and an opaque graphing interface. So I tried grafana which was impenetrable due to lack of setup documentation.
I have now settled on Redash, because it gives the graphic control that Superset lacked, along with connectors to a large number of data sources (including ElasticSearch). Additionally, Redash is the easiest to work with (SQL and a few minimal guidelines).
For me there's no question that Redash is the best open-source choice of those I tried.

**Comment by darylerwin** [comment]
Well superset doesnt work with BigQuery. That might be the deciding factor.

**Comment by brylie** [comment]
Here are *some* additional 'dimensions' by which to compare Superset and Re:dash, and open-source projects in general.

# Supported databases
A data source compatibility table might be a deciding factor. Caveat emptor, maintaining integrations with multiple databases is likely difficult work and may not have consistent functionality across integrations in a single project, let alone across the two projects.

| Data source | Redash | Superset |
| :---         |     :---:      |     :---:      |
| Amazon Athena   | ✓ | ✓ |
| Amazon Aurora   | ✓ |   |
| Amazon DynamoDB   | ✓ |   |
| Amazon Redshift   | ✓ | ✓ |
| Axibase Time Series Database   | ✓ |   |
| Cassandra   | ✓ |   |
| ClickHouse   | ✓ |   |
| Elasticsearch   | ✓ |   |
| Google BigQuery   | ✓ |   |
| Graphite   | ✓ |   |
| Greenplum   | ✓ | ✓ |
| Hive   | ✓ |   |
| Impala   | ✓ | ✓ |
| InfluxDB   | ✓ |   |
| Microsoft SQL Server   | ✓ |   |
| MongoDB   | ✓ |   |
| MSSQL   |  | ✓  |
| MySQL   | ✓ | ✓  |
| Oracle   | ✓ | ✓ |
| PostgreSQL   | ✓ | ✓ |
| Presto   | ✓ | ✓ |
| ScyllaDB   | ✓ |   |
| SparkSQL  |  | ✓ |
| sqlite  |  | ✓ |
| TreasureData   | ✓ |   |
| Vertica   | ✓ | ✓ |
| Google Analytics   | ✓ |   |
| Google Spreadsheets   | ✓ |   |
| JIRA   | ✓ |   |
| ClickHouse  |  | ✓ |

# Documentation
It is worthwhile to compare documentation of the two projects.

- Is there a user guide?
- Is there an administrator guide?
- How easy is it to find the documentation?
- How easy is it to contribute to the documentation?

# Installation option(s)
- How easy is it to set up an instance on your local computer to 'try-it-out'?
- How easy is it to install a production-ready instance?
- How easy is it to set up a development environment?

# Development activity
- How many active contributors does each project have?
- How quickly do issues and PRs get resolved (on average)?

- Is there a CONTRIBUTING.md?

# Project management
- Is there a ROADMAP?
- Does the project use Continuous Integration?
- How extensive is test coverage?

# Community
- Is there a CODE OF CONDUCT?
- Is there a community discussion forum (e.g. [Discourse](https://www.discourse.org/))?
- Is there a real-time channel for chat?

**Comment by xrmx** [comment]
@brylie found a few inaccuracies in your table:
- Microsoft SQL Server is supported by superset
- you have clickhouse listed twice (supported by superset)
- big query is supported by superset
- hive is supported by superset
- amazon aurora being mysql compatible is supported by superset

As a general rule whatever database can be queried via a sqlalchemy dialect can be accessed by superset

**Comment by darylerwin** [comment]
Not to nitpick but bigquery is not supported. Everyone asks including me
but it doesn't have the sql alchemy hook.

**Comment by dclong** [comment]
And what about Teradata SQL?

**Comment by brylie** [comment]
I am glad to publish the above comparisons to a wiki, so it can be updated by multiple people. Do Re:dash or Superset have a wiki?

**Comment by arikfr** [comment]
@brylie I was about to suggest to move this discussion to our [forum](discuss.redash.io) as it's not really an issue.

Once you make the post, I can (or maybe you too?) convert it into a Wiki post, that others can edit.

**Comment by xrmx** [comment]
@darylerwin AFAIK you can query bigquery via https://github.com/mxmzdlv/pybigquery, discussion here https://github.com/apache/incubator-superset/issues/945

**Comment by brylie** [comment]
I moved my notes to the discussion platform:

https://discuss.redash.io/t/a-comparison-of-re-dash-and-superset/1503

**Comment by arikfr** [comment]
Thanks! Closing this now.

**Comment by christophlingg** [comment]
I recently tried out both and shared my insights in this post https://medium.com/@c.lingg/apache-superset-vs-redash-5951cc2da9d
