### ISSUE TITLE
Blank page issue on Safari (iOS and MacOS)

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2209]
Sometimes Safari caches empty Javascript files, which results in blank pages until the user clears cache.

It might be related to this Webkit issue:
https://bugs.webkit.org/show_bug.cgi?id=32829

(also related: http://bytes.schibsted.com/ios7-bug-shows-white-page-when-getting-304-not-modified-from-server/)

**Comment by elipollak** [comment]
+1
