### ISSUE TITLE
Add Widget Dialog UX Update

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2214]
The Add Widget dialog should always show a list of queries (preferably the last ones you edited) and this list will update when you start searching.

**Comment by arikfr** [comment]
@kravets-levko what are you planning to use to show the initial queries list? recent queries?

**Comment by kravets-levko** [comment]
Yes, it should be the most relevant to user. If no recent queries - I'll try to choose one of:
- show empty list (probably with hint or so);
- show user's queries (few newest);
- show few newest queries (not just users ones).
I will try these variants and choose what looks the best.

**Comment by arikfr** [comment]
Let's start with the recents API and if we feel it's not enough, find alternatives.

**Comment by arikfr** [comment]
(you can see recents usage in the homepage)
