### ISSUE TITLE
Redash 3.0.0, URLs no longer being rendered as hyperlinks on table views

### ISSUE THREAD

**Issue by tomaytotomato** [getredash/redash#2216]
Hi all,

I upgraded to master yesterday and I am loving it.

Just one issue I've discovered is that on one of my table views which has a column containing URLs, it is no longer being rendered as a clickable link on my dashboard.

On version 2.2.2 you could click those links which were default `(target=_blank)`

I see this logic for rendering is handled by `formats.js`, if its ok with you I can create a new type called `link` and make a pull request?

Thanks

**Comment by kravets-levko** [comment]
Hi @tomaytotomato!

Recently we changed table visualization to make it more powerful. Sadly, some new features were not backward-compatible, so now you need to explicitly enable them: open table visualization editor (click "Edit" button under the table), and then choose formatter for your column:

![image](https://user-images.githubusercontent.com/12139186/34720016-d8ebc0ba-f545-11e7-979a-f9cb2a787a4e.png)
![image](https://user-images.githubusercontent.com/12139186/34720021-e56ec1c0-f545-11e7-8ec8-b0dea3f1a5a4.png)

Hope it will solve your issue.

**Comment by arikfr** [comment]
@tomaytotomato are you sure you're using v3 and not the master branch? Because the changes @kravets-levko mentioned were not part of the v3 release.

**Comment by tomaytotomato** [comment]
Sorry it is master

**Comment by arikfr** [comment]
Now it all makes sense. 👍
