### ISSUE TITLE
Input Parameter not taking forward slash /

### ISSUE THREAD

**Issue by sonal1811** [getredash/redash#2227]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by sonal1811** [comment]
I am using Hive database to connect through redash
Following is the query which is written in Redash UI but it is not giving any result

SELECT *
FROM tbl_clientwisestockdetails_922
where asondate like '{{asondate}}%'
and (`client_code`= '{{client_code}}' OR '{{client_code}}' = 'All')
and (`warehouse_code` = '{{warehouse_code}}' OR '{{warehouse_code}}' = 'All')

Following query when given with parameter specified is working but when take warehouse code as input parameter then it is not working as the reason is due to / in the data.
  
SELECT *
FROM tbl_clientwisestockdetails_922
where asondate like '{{asondate}}%'
and (`client_code`= 'ABCD87589')
and (`warehouse_code` = 'AB/CD/EFG/170/MNOP/C20287')


For Debugging I also tried it on MySql table
But in that case specifying the value of the column also did not work

SELECT *
FROM circle
WHERE color="er\eer"

**Comment by RichardLitt** [comment]
Hey @sonal1811, thanks for logging this. It looks like this is a support question, and you haven't filled out the template we provide for these sorts of questions. Can you ask this on the forum? If it is a bug or a feature request, we can reopen this here, but for the moment I think it might be best to bring this question here: discuss.redash.io/c/support

**Comment by arikfr** [comment]
You need to use three sets of braces in such case (`{{{client_code}}}` for example).

**Comment by gregorybrooks** [comment]
For goodness sake please put this magic three-braces feature in the redash documentation about parameters! I wasted hours on this because a value in a parameter drop-down had a slash and so it was never matching my table's value.

**Comment by RichardLitt** [comment]
@gregorybrooks Whoa, super sorry that that happened!

Would you like to add it in a PR? Otherwise, we can open an issue to document this better.

**Comment by gregorybrooks** [comment]
Thanks for your response. I have used a PR to request something yet, but I should learn how. I will do it.
