### ISSUE TITLE
Error running query: 'ascii' codec can't encode characters in position

### ISSUE THREAD

**Issue by rajsharma1612** [getredash/redash#2228]
Welcome to Redash's GitHub repo! 👋🎉

Do you need help or have a question? Checkout the Support category in our discussion forum: https://discuss.redash.io/c/support. 

Got an idea for a new feature? Check if it isn't on the roadmap already: http://bit.ly/redash-roadmap and start a new discussion in the features category: https://discuss.redash.io/c/feature-requests 🌟.

Found a bug? Please fill out the sections below... thank you 👍

### Issue Summary

Browser: Chrome
Env: Mac

I am getting an error on running queries.

`Error running query: 'ascii' codec can't encode characters in position 103-104: ordinal not in range(128)
`
### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by tonyjiangh** [comment]
If you're using v3, and it's about query_result.
Then, the fix is merged: https://github.com/getredash/redash/pull/2165

(I would be much easier for us to understand your situation if you could just fill in the issue template.)

**Comment by tonyjiangh** [comment]
@rajsharma1612 
Can you confirm agian, or please add more information regarding your issue.
I'll be a great help if you can just fill in the issue template.

**Comment by ikazoy** [comment]
@tonyjiangh I have come across to the issue and applied your patch https://github.com/getredash/redash/pull/2165/commits/6e2e2e20604a599141c1b735fd35b72f298c4eeb#diff-358e2979be17b5b73aaf4a5f2d9e9d1e to our self-hosted redash and it solved the error as expected.

My case:

Error: `Error running query: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)`

Redash Version: 3.0.0.b3134

The error happens only when I refer a query result which has Japanese (multiple bytes characters), while the error didn't happen for queries including only single bytes characters.

Anyway, the error has gone and no problem.

I would like to ask what is the best and easy way to apply newer changes which has not been released such as the commit https://github.com/getredash/redash/pull/2165/commits/6e2e2e20604a599141c1b735fd35b72f298c4eeb#diff-358e2979be17b5b73aaf4a5f2d9e9d1e .
In this case, I did most primitive way to fix the codes directly to save my time. Of course, I know it is not the best.

**Comment by tonyjiangh** [comment]
@ikazoy Glad to know that it works for you.
I think upgrade version would be a nice choice.
That being said, we haven't applied any update yet since we started using redash, so I cannot provide any info on how much trouble there's going to be.
BTW, our team decided to stick to the master branch and not apply any local patch.

**Comment by arikfr** [comment]
> I would like to ask what is the best and easy way to apply newer changes which has not been released such as the commit

What you did is probably good enough if you just need a small fix. Otherwise you can either upgrade to the CI version or use a beta release when one is available.

Also I'm closing this now, as @rajsharma1612 never followed up and looks like this is indeed already fixed.
