### ISSUE TITLE
Hive query takes lot of time

### ISSUE THREAD

**Issue by kushNumberTheory** [getredash/redash#2230]
Hi Guys, 
I am using redash to connect to hive and sql server. I am running same query on both the instances. I get result from sql server instance with in 1 minute but from hive it gets to 40 minutes and sometimes doesn't even retrieve data. My table size is same on both data sources and same no of columns. Table has 50000 rows and 80 columns.
Any idea on this??

Debugging
redash store queries and respective data in query_results table in redash. my both queries have same results stored in table, but when i do select data from query_results where id="given something", if the table has huge size it dont show anything. Please guide me on this

**Comment by arikfr** [comment]
Redash passes through the query to Hive, so from your description it sounds like Hive takes 40 minutes to run the query...

Either way, GitHub issues are not for support questions. 
For support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.

**Comment by kushNumberTheory** [comment]
@arikfr raised question over there. Hive doesnt take time to execute that query.. it takes only maximum 2 mins to show the result in hive shell with the same data

**Comment by RichardLitt** [comment]
Thanks @kushNumberTheory. We'll discuss it over there; we try to keep support communications low here to help us focus. Thanks for understanding!
