### ISSUE TITLE
Download dataset for unsaved query causing Internal Server Error

### ISSUE THREAD

**Issue by cyriac** [getredash/redash#2232]
### Issue Summary

A new, unsaved query dataset download responds with 
```
{ message: "Internal Server Error" }
```
Once the query is saved, the error goes away.

### Steps to Reproduce

1. **Open Queries** > **New Query**
2. Select your data source, write your query, hit **Execute**
3. Once you get the response, select **Download Dataset** > **CSV/Excel**

If you closely look at the URL for the downloads you would see an undefined in the URL. This section of the path is normally used for the query id.
<img width="401" alt="screenshot 2018-01-18 17 01 54" src="https://user-images.githubusercontent.com/1846416/35096256-869f7cba-fc71-11e7-912f-08344c867043.png">

### Technical details:

* Redash Version: Redash 3.0.0+b3134
* Browser/OS: Ubuntu 16.04.3 LTS
* How did you install Redash: via [bootstrap.sh](https://raw.githubusercontent.com/getredash/redash/master/setup/ubuntu/bootstrap.sh) at version 2

**Comment by cyriac** [comment]
Looks like #2134 fixes it. Closing the issue.

**Comment by RichardLitt** [comment]
Thank you, @cyriac, for both logging and following up.
