### ISSUE TITLE
Empty states for list pages

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2233]
**First Phase**

- [x] Homepage
- [x] Queries page
- [x] Dashboards
- [x] Alerts page
- [x] Dashboard

**Second Phase**

- [ ] Alert Destinations
- [ ] Query Snippets

https://trello-attachments.s3.amazonaws.com/5a04ab83aa58f65ac369adb6/5a255cd4ba45b4ceb02541f1/bfa41a49fa85090f7e6803c1bfb7b3d9/image.png

http://d.pr/i/SFZqnV

**Comment by arikfr** [comment]
@kocsmy I'm assuming all (most?) the list pages will have a similar structure when empty, so once you create one -> ping me, and let's turn it into a component you can reuse across the other ones.

**Comment by kocsmy** [comment]
Thanks, @arikfr — I'll take a look soon and comment what's needed!

**Comment by kocsmy** [comment]
(adding notes for myself)

## Homepage
- What's Redash + Getting started link: http://help.redash.io/article/32-getting-started
- Connect a Data Source (if not data source is connected yet)
- Write your first query
- Create your first dashboard

## Queries page
- What's a query? Description + link to http://help.redash.io/category/21-querying
- Connect a Data Source (if not data source is connected yet)
- Write your first query

## Dashboards
- What's a dashboard? Description + link to http://help.redash.io/category/22-dashboards
- Connect a Data Source (if not data source is connected yet)
- Write your first query
- Create your first dashboard

## Alerts page
- What's an alert? Description + link to http://help.redash.io/category/23-alerts
- Connect a Data Source (if not data source is connected yet)
- Write your first query
- Create your first alert

## Alert Destinations / Query Snippets
- What's this, link to http://help.redash.io/article/39-query-snippets-shortcuts / http://help.redash.io/article/68-adding-alert-destination-slack
- create your first alert destination / query snippet

**Comment by arikfr** [comment]
Homepage: there should be another task - invite a user.

**Comment by kocsmy** [comment]
PR here: https://github.com/getredash/redash/pull/2252
