### ISSUE TITLE
Further Query Editor Improvements

### ISSUE THREAD

**Issue by kocsmy** [getredash/redash#2234]
- [x] Fix Smaller screen glitches @kocsmy
- [x] Attach refresh schedule and created/edited by to the top, increase the size of schema browser and remove resizer there @kocsmy @kravets-levko 
- [x] Scroll in each region, instead of the entire page scrolling (fixed layout, with body overflow: hidden) @kravets-levko 
- [x] Clickable resizer toggle to quickly open and expand section @kravets-levko

**Comment by kocsmy** [comment]
Current status:
![screenshot 2018-01-19 16 03 51](https://user-images.githubusercontent.com/2378022/35156866-74458854-fd32-11e7-8c6f-2a36051e0690.png)
![screenshot 2018-01-19 16 04 16](https://user-images.githubusercontent.com/2378022/35156874-77a2fdba-fd32-11e7-8a2c-db65c8d31c3d.png)

There are some layout glitches which will be resolved once we add "Scroll in each region, instead of the entire page scrolling".

**Comment by kocsmy** [comment]
Idea: the refresh schedule is kinda alone there. I'd put the action on "Updated an hour ago". For example: Updated an hour ago (Every 12h) and the later one is a link to change that.

**Comment by kocsmy** [comment]
Another idea: Publish button is inside the content, maybe we should move it out, next to the Show Data Only? WDYF @arikfr 
![screenshot 2018-01-19 16 08 15](https://user-images.githubusercontent.com/2378022/35157057-1d9a13de-fd33-11e7-9d4b-ca2229e0ddb0.png)

**Comment by arikfr** [comment]
>Idea: the refresh schedule is kinda alone there. I'd put the action on "Updated an hour ago". For example: Updated an hour ago (Every 12h) and the later one is a link to change that.

Possible, but might make it less discoverable, no?

**Comment by arikfr** [comment]
> Another idea: Publish button is inside the content, maybe we should move it out, next to the Show Data Only? 

Seems ok.

**Comment by kocsmy** [comment]
> Possible, but might make it less discoverable, no?

Not sure, the current position is also out of context. It'd be in context at least.
