### ISSUE TITLE
LDAP Auth /login_auth/login 404

### ISSUE THREAD

**Issue by noahrowland** [getredash/redash#2235]
### Issue Summary

With LDAP auth enabled, app routes url to '/ldap/login' based on ldap_auth.py in authentication.
Template login page redirects to '/ldap_auth/login' which returns a 404 since there is no route pointing to that url. 

### Steps to Reproduce

1. enable LDAP auth
2. navigate to localhost and click link to SSO login page
3. observe 404

Fix: adjust route in /authentication/ldap_auth.py

### Technical details:

* Redash Version: redash.3.0.0.b3134
* Browser/OS: Chrome
* How did you install Redash: ami

**Comment by arikfr** [comment]
I don't think it was fixed in v4, but will try to fix it in one of the next updates of v4.

We won't release a patch release for v3 for this bug, but you can patch your version by replacing `ldap_auth/login` with `ldap/login` in the templates.
