### ISSUE TITLE
Redash 4 doesn't display the version under admin/status

### ISSUE THREAD

**Issue by chriswue** [getredash/redash#2239]
### Issue Summary

Redash has a System Status panel under admin (admin/status) with a General section containing a Version row but this doesn't display any value. I would have expected to see the current version number there.
Not sure if that is an issue with 4.0.0 in general or an issue with the docker images

### Steps to Reproduce

1. Deploy redash from official docker compose file
2. Navigate to to admin/status

### Technical details:

* Redash Version: 4.0.0 (exact build number unknown due to this issue)
* Browser/OS: Redash Ubuntu 17.10 running in docker image, browers is Chrome and Firefox
* How did you install Redash: deployed from official docker compose file

**Comment by arikfr** [comment]
It's just empty or it shows `4.0.0`?

**Comment by chriswue** [comment]
@arikfr It's just empty

**Comment by brylie** [comment]
What is the release timeline for 4.0?

**Comment by darylerwin** [comment]
btw .. it shows up on my upgrade of 3.0 to the latest commit ..
...
0 Unused Query Results Count
4.0.0+b3635 Version
2 Widgets Count
... 
Redash 4.0.0+b3635 • Documentation • Contribute

**Comment by arikfr** [comment]
@chriswue can you share a screenshot of the whole status screen?

**Comment by arikfr** [comment]
@brylie soon :-)

**Comment by arikfr** [comment]
Closing. You're welcome to reopen with additional details.

**Comment by RichardLitt** [comment]
@arikfr Perhaps we should add a `Needed: more information` label for cases like this? I've seen that work well, elsewhere.

**Comment by arikfr** [comment]
@RichardLitt so on Feb 8, when I asked for the screenshot, I would add this label to clearly signal an action is required?

**Comment by RichardLitt** [comment]
Exactly.

**Comment by arikfr** [comment]
@RichardLitt Will keep this in mind next time I use this reply :-)
