### ISSUE TITLE
Missed image for Python datasource

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#2240]
### Issue Summary

New datasource editor hasn't image for python datasource:
<img width="236" alt="2018-01-19 10 27 28" src="https://user-images.githubusercontent.com/7091907/35139314-969af79c-fd03-11e7-8cd7-c9cd652bd611.png">

### Steps to Reproduce

1. Add python query runner
2. Open the datasources page

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: master
* Browser/OS: Safari / MacOS
* How did you install Redash: script

**Comment by kocsmy** [comment]
@denisov-vlad can you right click on the missing image and select Inspect and let me know what's the file name? I don't have the python as an option and not sure how to add it but I can apply a very quick fix once I know the filename :)

**Comment by arikfr** [comment]
@kocsmy it will be `python.png`.

**Comment by kocsmy** [comment]
I could guess that... :)

**Comment by denisov-vlad** [comment]
Yep, `python.png`. :)

**Comment by arikfr** [comment]
(fixed in #2244)
