### ISSUE TITLE
Insert node by click bug

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#2241]
### Issue Summary

After this pull request https://github.com/getredash/redash/pull/2225 it's possible to insert table / column by click. 

Column is inserted in the following format: {schema_name}.{table_name}.{column_name}. It's not suitable for PostgreSQL, for example, and should be like this: {table_name}.{column_name} or {column_name}.

### Steps to Reproduce

1. Open query editor with PostgreSQL datasource.
2. Insert column by click
3. Try to run query.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: master
* Browser/OS: Safari / MacOS
* How did you install Redash: script.

**Comment by kravets-levko** [comment]
@denisov-vlad I checked the code, and it works as expected: it inserts `{table_name}` when you click top-level node (table name) in schema browser, and it inserts `{table_name}.{column_name}` when you click second-level nodes (column names). It work exactly in the same way as auto-completion dropdown.

But at the same time I found another bug that may cause errors during execution - it's already merged (https://github.com/getredash/redash/pull/2275). So I kindly ask you - can you please check that fix and give me some feed back - do you still see your issue, or was it fixed? Thanks a lot!

**Comment by denisov-vlad** [comment]
It's ok now. Thanks.
