### ISSUE TITLE
after updating to 3.0 fail Query Excecution

### ISSUE THREAD

**Issue by HiuNaoki** [getredash/redash#2255]
### Issue Summary

after updating to 3.0   then display below message   if runing query to BigQuery 

"Error running query: cannot instantiate ctype 'EVP_MD_CTX' of unknown size"

### Steps to Reproduce

1. 
undating redash 2.0 to 3.0   
https://redash.io/help-onpremise/maintenance/how-to-upgrade-redash.html

2. 

restart  redash
sudo supervisorctl restart all

3. 
if running query   show below message 
"Error running query: cannot instantiate ctype 'EVP_MD_CTX' of unknown size"

### Technical details:

* Redash Version: 2.0
* Browser/OS: Chrome/ubuntu
* How did you install Redash:  AWS  ami

regurd

**Comment by arikfr** [comment]
You should upgrade pyOpenSSL.

**Comment by HiuNaoki** [comment]
TNX!!!
