### ISSUE TITLE
Cannot download dataset from unsaved Redshift query result

### ISSUE THREAD

**Issue by jbeemster** [getredash/redash#2271]
### Issue Summary

Cannot download dataset from query run against Redshift cluster.  Attempting to download in either CSV or Excel results in a `Failed - Server problem`.  This is with a very small dataset of just 2 rows.

### Steps to Reproduce

1. Connect to a Redshift data-source
2. Run a very simply select query (but do not save it)
3. Attempt to Download as CSV/Excel file

### Technical details:

* Redash Version: 3.0.0+b3134

**Comment by arikfr** [comment]
Fixed in #2134.

**Comment by jbeemster** [comment]
Hey @arikfr - will this fix make it into the v3 or only into v4 once it is released?

**Comment by arikfr** [comment]
Only v4. We try to avoid releasing patch releases of old versions, unless critical.

If you run a fork/have your own build process, I can help with instructions on how to apply this to v3.

**Comment by jbeemster** [comment]
Thats fine - we will wait for v4!
