### ISSUE TITLE
Clicking on "Refresh" dropdown in a dashboard page creates a scrollbar

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2272]
When you click on the "Refresh" dropdown in a dashboard it creates horizontal scrollbar, because the dropdown opens to the right instead of to the left.

**Comment by arikfr** [comment]
@kravets-levko I didn't see an option to open it to the other side. Any idea on how this can be done?

**Comment by kravets-levko** [comment]
@arikfr Just add `pull-right` class to `dropdown-menu` block. Will do it in a minute
