### ISSUE TITLE
Add option to load cached results in Query Results queries

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2285]
Currently when running a query that loads data from another query using the query results data source, we always execute the underlying query. Sometimes it makes sense to use a cached result.

We can start with a way to express it when specifying the query you want to load:

```sql
SELECT *
FROM cached_query_123
```

(instead of `FROM query_123`)

**Comment by whitemark** [comment]
Thumb up!

**Comment by ccwillia** [comment]
This would be a great feature to compare counts between the last time the query ran and the current run to see the percent change

**Comment by chanansh** [comment]
I wish I could query based on another query WITH parameters. This way I can avoid running the same shared logic twice. A->B and A->C where A is the parent query and B and C are child queries and A has parameters.
