### ISSUE TITLE
 Bar chart with second y axis overlaps data series

### ISSUE THREAD

**Issue by dncpax** [getredash/redash#2292]
### Issue Summary
Discussion here: https://discuss.redash.io/t/bar-chart-with-second-y-axis-overlaps/1493/3.
In a bar chart, when choosing to display a data series on the secondary y axis to the right, the data series overlaps all others:
![image](https://user-images.githubusercontent.com/2836636/35824246-2a6fe2e4-0aaa-11e8-9a62-959bab5928f5.png)

It shouldn't. The correct solution is to display all data series side-by-side regardless of y axis.
Example from google sheets:
1 y axis
![image](https://user-images.githubusercontent.com/2836636/35824257-3921a82c-0aaa-11e8-86b4-3b68cc0e918c.png)

2 y axis
![image](https://user-images.githubusercontent.com/2836636/35824266-3f0d3616-0aaa-11e8-8897-389669ecddb6.png)

Occurs on v3.

### Steps to Reproduce

1. Create bar chart with at least 2 data series
2. Configure 1 data series to use a secondary y axis

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
I don’t think that’s the correct behaviour a secondary y axis should have. Why would anyone want a data series to entirely cover up other data series?
The objective of a secondary y axis is to allow very different ranges of values to be plotted on the same graph.

### Technical details:

* Redash Version: 3.0
* Browser/OS: any
* How did you install Redash: ubuntu provision script

**Comment by chuckume** [comment]
I have exactly the same problem.

**Comment by dncpax** [comment]
Just trying to get traction on this. 
Really, a no-brainer and super-strange to explain people redash does not support such a common use-case.

**Comment by dncpax** [comment]
Seems a plotly issue to be resolve in v1.45.0:
https://github.com/plotly/plotly.js/issues/78
PR already merged: https://github.com/plotly/plotly.js/pull/3529

Example here: https://codepen.io/etpinard/pen/yZQYzq?editors=1010

**Comment by dncpax** [comment]
Ok, v1.45 is already out! They're on v1.45.2 already!

Any takers??

**Comment by kravets-levko** [comment]
Hi @dncpax! We're in the middle of React migration, and therefore have some blockers related to that. I think I'll take this after getredash/redash#3493 merged.

**Comment by dncpax** [comment]
Hi @kravets-levko thanks for the update. Been looking forward for the many great things you guys are doing.

**Comment by tharapita** [comment]
Any updates?

**Comment by puneetjindal** [comment]
@kravets-levko 
I have an angular based web app and currently exploring for dashboarding solution. Having dual axis chart is kind of a MVP requirement. Its somehow difficult to locate from the above discussions whether we can build dual Y axis as per the expected behaviour or not? Please help me point towards its implementation!

**Comment by susodapop** [comment]
I reproduced this on the preview instance [here](https://redash-preview.netlify.app/queries/414#745).

**Comment by kravets-levko** [comment]
@susodapop [PR that fixes it](getredash/redash#4150) wasn't merged yet

**Comment by dncpax** [comment]
Wuhu! Good news! Thanks guys!

**Comment by mmbader** [comment]
> Wuhu! Good news! Thanks guys!

Sorry, just to clarify - is this implemented now? How can I enable this functionality? Thanks!

**Comment by kravets-levko** [comment]
@mmbader Yes, it's fixed now, you should just upgrade to latest version

**Comment by mmbader** [comment]
![image](https://user-images.githubusercontent.com/13626375/98533413-3d556980-2283-11eb-9b35-11150261451a.png)

Sorry for the noob question - where can I see which version I am currently using? Is it the one at the bottom of my screenshot? (Version: 4172e048)

Thanks for your help!
