### ISSUE TITLE
Docker images for stable releases

### ISSUE THREAD

**Issue by lkraider** [getredash/redash#2294]
### Issue Summary

Please provide docker images tagged with the stable releases.

Would be great to follow the [Python docker images](https://hub.docker.com/r/library/python/tags/) format:
tags:
  - 3 (updated with every minor/patch release for that major version)
  - 3.6 (updated with every patch release for that minor version)
  - 3.6.1 (fixed to that release)

### Steps to Reproduce

1. Go to https://hub.docker.com/r/redash/redash/tags/
2. Look for 3.0.0
3. Be disappoint 😞 

### Technical details:

* Redash Version: looking for v3 stable
* Browser/OS: any
* How did you install Redash: docker compose

**Comment by arikfr** [comment]
The `latest` tag always pointing at the latest stable version.

**Comment by lkraider** [comment]
Hello, I would like to target a specific stable version, the latest tag for docker works for development, but it's difficult to keep track what version is running when you deploy more images, that is why having the versioned releases tagged is useful.

**Comment by arikfr** [comment]
Following your feedback, started creating tags for the releases (last one is `4.0.0-rc.1`).

**Comment by lkraider** [comment]
Awesome!
