### ISSUE TITLE
Filters dropdown is "trapped" inside the widget area

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2295]
![image](https://user-images.githubusercontent.com/71468/35921962-e1831430-0c24-11e8-8112-f69e9f47f769.png)

(apologies for the blue tint)

**Comment by kravets-levko** [comment]
I already fixed it earlier, when we were implementing new dashboards. Strange that it happens again...

**Comment by arikfr** [comment]
Maybe got lost in one of the bigger merges?

**Comment by kravets-levko** [comment]
Probably yes. Or something happened during re-design. Anyway, it will be fixed ASAP :+1:

**Comment by kravets-levko** [comment]
BTW - which page it that?

**Comment by arikfr** [comment]
`/dashboard/filters-example`

**Comment by kravets-levko** [comment]
Noticed that I was fixing parameters, not filters. So I take my words back - I have never fixed this bug :-)
