### ISSUE TITLE
Make alert's rearm seconds configuration friendly

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2310]
![image](https://user-images.githubusercontent.com/71468/36118455-c527e03e-1045-11e8-9ce0-d5b6d6e9bad3.png)

This is from DataDog. Very clear on what it does. In our case the text should be "renotify if alert is still in triggered state.". Only additional thing to clarify somehow is that this will only work if the query's refresh schedule is <= the interval here.

**Comment by kocsmy** [comment]
What's in the dropdown, by the way?
