### ISSUE TITLE
Choropleth map visualization

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2317]
![image](https://user-images.githubusercontent.com/71468/36198774-3402625a-1180-11e8-9228-cc6d9cae4e10.png)

Possible libraries:

* https://github.com/markmarkoh/datamaps
* http://jvectormap.com/
* Plotly

**Comment by deecay** [comment]
- http://leafletjs.com/examples/choropleth/

**Comment by SylvainMassol** [comment]
Yes leafletjs is a good library, support many formats like GeoJson, and it's already use in Redash.

**Comment by deecay** [comment]
I'm fiddling around with `leaflet-choropleth` module, and found out visualization shown below can be done quite easily.
![image](https://user-images.githubusercontent.com/1698635/36972904-4dcc13a0-20b4-11e8-9c4d-0ea40675efd2.png)

However, I do not have real-life use cases, so I'm not sure what to do from here. 

1. Visualize one property from `"properties"` within geoJSON column in query result. ([geoJSON for above example](https://raw.githubusercontent.com/timwis/leaflet-choropleth/gh-pages/examples/basic/crimes_by_district.geojson)).
2. Query result column "value" has value to visualize and column geoJSON has the polygons.
3. Query result is just a table of columns "id" and "value", and this table should be merged with some other source of geoJSON.

**Comment by arikfr** [comment]
The first use case we want to accomodate is to be able to visualize a dataset the looks like:

Country | Users Count
------------ | -------------
JP | 3201
US | 2912
UK | 215

I.e. take value per country and visualize it on a map.

Later we can expand this to be more granular (zoom in on specific continent, cities, etc).

This is why I feel like Leaflet might not be the try solution as it starts with too much details.

**Comment by arikfr** [comment]
But it has different base maps we can use so maybe one of them is what we need?

**Comment by deecay** [comment]
Yes. There are different base maps. 

The example polygons on the example page just happened to be district-size. Leaflet/geoJSON can have country level polygons too. There are several versions of country level polygons available, so I will try to find suitable one and come back with visual example.

**Comment by arikfr** [comment]
Any "catalog" of those base maps?

**Comment by kravets-levko** [comment]
@deecay FYI -  I'm already on this issue, and will create PR tomorrow (I see you're also experimenting with it, so I decided to tell you)

**Comment by deecay** [comment]
Oh, that's nice. Can't wait to see it!

**Comment by deecay** [comment]
Please allow me to ask one question here. Now that this is merged, how do we go about adding geojson files?

Due to highly individual needs and large file size, I think there should be some kind of way for admin to add their own geojson, and not to include all the country or city geojson in the bundle.

**Comment by arikfr** [comment]
The geojson files are not in the bundle -- they are loaded separately. It probably shouldn't be too complex to add a way to load custom files from a URL.

**Comment by RichardLitt** [comment]
@deecay if it is too complex, let us know! That probably just means we should document it better somewhere.

**Comment by sergikpas** [comment]
@arikfr when you plan release this feature? Any plans for next RC or Release?
