### ISSUE TITLE
Dashboards list goes out of screen

### ISSUE THREAD

**Issue by HimanshPal** [getredash/redash#2321]
### Issue Summary
The dashboard list which can be opened from top menu, tends to go out of screen if there a lot of dashboards. It would be better to show more button instead of showing all dashboard list

Attaching screenshot. 

<img width="731" alt="screen shot 2018-02-16 at 1 40 27 pm" src="https://user-images.githubusercontent.com/1980022/36298805-f35c8e32-131f-11e8-9699-b6aa6398e8ca.png">

ps: I have removed the content due to privacy issues.

**Comment by arikfr** [comment]
This was fixed a long time ago. If I'm not mistaken in v1.0.0, which was released a year ago. Based on the bug report and the screenshot, I can only assume you're using an older version and should upgrade.

In the future, when reporting bugs, please follow the provided template, as without those details it's hard to tell.

I'm closing this now, but feel free to reopen if needed.
