### ISSUE TITLE
Error returns on queries with semi-colon followed by a comment

### ISSUE THREAD

**Issue by WaylonBrown** [getredash/redash#2326]
### Issue Summary

I noticed a very weird particular issue. Comments work on queries, but a query that's formatted in a particular way will always return an error instead of executing. This was not an issue in Redash 0.9 before we upgraded.

### Steps to Reproduce

Create a query like so:

```
select *
from events
limit 1;

-- test comment
```

Including the comment there is important. An error will return in the UI when executed, saying: "Error running query: QueryExecutionError('The query was malformed: query was empty',) is not JSON serializable"

If you do **any** of the following, then the error goes away and it executes correctly:

1) Remove the semi colon
2) Move the comment to be before the query or even on one of the query lines

So this issue is very particular in that it only occurs when you add a semi-colon after the query and follow it (on its own new line) with a comment. Using comments with the

```
/* my comment */
```

format gives the same result.

### Technical details:

* Redash Version: 2.0.1 (we don't currently have a means to upgrade past this, was this issue fixed in a certain commit that can be linked since 2.0.1 perhaps?)
* Browser/OS: Chrome, Mac

**Comment by WaylonBrown** [comment]
Any updates on this?

**Comment by guidopetri** [comment]
I'm unable to reproduce this. @WaylonBrown , is this still occurring on the latest redash? We have a `preview` image on dockerhub you can test with.
