### ISSUE TITLE
Global filter issue-  Global filter not containing all filter values instead taking only 1st chart filter value

### ISSUE THREAD

**Issue by indupulikkot** [getredash/redash#2327]
Found a bug---

### Issue Summary

Global filter is not combining all the values of filters from the charts present in dashboard, instead it is taking values only from first chart of the dashboard. Hence this is a bug from redash side.
### Steps to Reproduce

1. Create a dashboard with 2 or 3 charts and use same field as filter for all the charts. 
2. Restrict the data of first chart in the dashboard using query, so that it will provide only 1 option in the filter.
3. Do not restrict or filter in the 2nd and 3rd chart , so that the filter will reflect more than 1 value.
4. Now check this filter to reflect as global filter.
5. You can observe that the global filter will contain only 1 value which is same as first chart where ideally global filter must contain all the values from all 3 chart filters.( union all of filter values from all the charts).
6. Requesting a fix for this , since customers noticed this as a bug.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:  Please observe that the global filter will contain only 1 value which is same as first chart where ideally global filter must contain all the values from all 3 chart filters.( union all of filter values from all the charts).
 Requesting a fix for this , since customers noticed this  bug. Uploading document to represent this issue.

* Redash Version: 2.0
* Browser/OS: Chrome
* How did you install Redash:  Container
[redash global filter issue.docx](https://github.com/getredash/redash/files/1739237/redash.global.filter.issue.docx)

**Comment by indupulikkot** [comment]
Hi,

Any update on this? We tested 4.0 as well.. Same issue persists

**Comment by RichardLitt** [comment]
Thanks for following up, @indupulikkot. We'll get to this when we can.

**Comment by indupulikkot** [comment]
Any update on this bug? Please let us know

**Comment by arikfr** [comment]
Hi @indupulikkot,

These periodic questions for status as if we're on your payroll are irritating.

**Comment by indupulikkot** [comment]
I was just asking politely if this feature is available so that we can test this. We never expect a rude reply. Lets maintain a friendly and helpful conversations.

**Comment by arikfr** [comment]
I'm sorry that my reply offended you. 

The purpose of a GitHub issue is to reflect status. If there are no updates on a GitHub issue, it's most likely that no progress was made. Of course it's possible that an update was forgotten, but in such case it would be more helpful if you just try yourself rather than expecting us to do it for you.

No explicit effort was made to fix this, so most likely that this issue still exists.

**Comment by arikfr** [comment]
To make it easier for you to test this:

We have https://redash-preview.netlify.com/, which is a preview of the current master frontend code. You can create a dashboard which reproduces this issue there (see instructions on login page on how to login), so you can periodically check this dashboard to see if anything changed.

**Comment by gabrieldutra** [comment]
This was fixed in #3759

**Comment by indupulikkot** [comment]
Hi which version it is available
