### ISSUE TITLE
I can't find oracle support

### ISSUE THREAD

**Issue by gclsoft** [getredash/redash#2332]
![image](https://user-images.githubusercontent.com/1269898/36468596-e74d7478-171e-11e8-883f-130aebd76262.png)
I start the project from docker

**Comment by arikfr** [comment]
Oracle isn't enabled by default. Also you need to install requires system packages for it to work..

For support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.

**Comment by gclsoft** [comment]
@arikfr  Thanks so much for your reply. Can you please help me, how to add oracle support? I start redash from docker:
```
 from docker:

Run docker-compose -f docker-compose.production.yml run --rm server create_db to setup the database.
Run docker-compose -f docker-compose.production.yml up
Run docker-machine ls, take note of the ip for the Docker machine you are using, and open the web browser.
Visit that Docker machine IP at port 80, and you should see a Redash login screen.
```

**Comment by RichardLitt** [comment]
@gclsoft That would be a great question for the forum. Please ask it there. Thanks. :)

**Comment by gclsoft** [comment]
@RichardLitt https://discuss.redash.io/t/docker-oracle-support/1562  Thanks!
