### ISSUE TITLE
connect to ODBC or Access

### ISSUE THREAD

**Issue by jbmcclain** [getredash/redash#2335]
I have had link a couple data sets into on Microsoft Access MS SQL and Sybase.  Any way to have a connection to Microsoft Access.  Or do you recommend using another type of database to link to datasets like access dose so i could connect to redash?

Thank you

**Comment by RichardLitt** [comment]
Hey @jbmcclain. This doesn't sound like a bug, but a general question. As it says in the Issue Template, please put this sort of request on [the forum](https://discuss.redash.io/c/support). Thanks!

**Comment by jbmcclain** [comment]
sorry i will remove and post there

**Comment by RichardLitt** [comment]
Thanks @jbmcclain :) It happens.
