### ISSUE TITLE
Option to set SSO as default login with link to local on login

### ISSUE THREAD

**Issue by ryanmerolle** [getredash/redash#2344]
### Feature Request Summary

When SSO is setup, users are confused about how to login.  Could you setup an option to make SSO login the default and set a link to the side for local login?

**Comment by arikfr** [comment]
I'm a bit confused about what do you mean by "set a link to the side for local login"?

**Comment by wieshka** [comment]
To be honest, the issue might be as little as how plain the login page is when it comes to SAML Login.

I, as a tech-savvy user, opening Login page do understand that clicking on "just-a-button" with name SAML Login will authorize me, whilst user, who has been given link only, might be quite frustrated. 

Perhaps ability to download SSO/SAML provider icon which to be shown aside "Login with <service provider>" would solve the "issue".

I work in a 1000+ employees company - rolling out SSO for everything was quite massive internal campaign and everyone can recognize SSO provider of choice logo/icon. Like everyone recognizes Login with Facebook it any web pages.

**Comment by kocsmy** [comment]
"Perhaps ability to download SSO/SAML provider icon which to be shown aside "Login with " would solve the "issue"."

Yes, I can see why this is an issue. For a non tech-savvy user clicking on a button "Login with SSO/SAML" is definitely an issue and frustrating. 

Adding the provider's icon to the button or explicitly placing the provider's name on it (Login with Onelogin etc) would make this experience much better.

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
