### ISSUE TITLE
cassandra added to env but when i execute some query this error accured

### ISSUE THREAD

**Issue by sadeghebadi** [getredash/redash#2366]
all in latest docker versoin

   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 240, in trace_task
worker_1    |     R = retval = fun(*args, **kwargs)
worker_1    |   File "/app/redash/worker.py", line 71, in __call__
worker_1    |     return TaskBase.__call__(self, *args, **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
worker_1    |     return self.run(*args, **kwargs)
worker_1    |   File "/app/redash/tasks/queries.py", line 522, in execute_query
worker_1    |     scheduled_query).run()
worker_1    |   File "/app/redash/tasks/queries.py", line 444, in run
worker_1    |     annotated_query = self._annotate_query(query_runner)
worker_1    |   File "/app/redash/tasks/queries.py", line 485, in _annotate_query
worker_1    |     if query_runner.annotate_query():
worker_1    | AttributeError: 'NoneType' object has no attribute 'annotate_query'

**Comment by arikfr** [comment]
Looks like you didn't restart your worker container after updating environment variables and/or didn't install needed requirements.

Anyway, this looks like a setup issue and not a problem with Redash. If you still need help with this, I'll appreciate if you open a thread in our forum: https://discuss.redash.io/c/support/support-self-hosted.

Thanks.
