### ISSUE TITLE
Add Finer-grained scheduling

### ISSUE THREAD

**Issue by emtwo** [getredash/redash#2396]
I've started working on this feature that was initially filed here: https://github.com/mozilla/redash/issues/187

I have some thoughts on a slightly new design that might make query scheduling more flexible. The idea was based on how google calendar allows one to schedule an event. Here are some screenshots:

<img width="298" alt="screen shot 2018-03-19 at 3 21 08 pm" src="https://user-images.githubusercontent.com/784781/37617338-44146472-2b89-11e8-9fe7-eea1d3145afd.png">
<img width="295" alt="screen shot 2018-03-19 at 3 25 36 pm" src="https://user-images.githubusercontent.com/784781/37617534-cd42f31c-2b89-11e8-9467-83f6fa058f95.png">
<img width="300" alt="screen shot 2018-03-19 at 3 21 27 pm" src="https://user-images.githubusercontent.com/784781/37617342-46672dfe-2b89-11e8-89ce-98b91949f3d2.png">
<img width="298" alt="screen shot 2018-03-19 at 3 21 40 pm" src="https://user-images.githubusercontent.com/784781/37617345-48a0a64a-2b89-11e8-9c0a-f69a72046036.png">

Essentially the same functionality would still exist with some additional new functionality:
* It would be possible to schedule a query every X days instead of only every 1 day
* It would be possible to schedule a query every X weeks on a specific day

Would love any thoughts you have on this @arikfr @kocsmy. Thanks!

**Comment by arikfr** [comment]
Looks good! There are a few small changes I would apply to the wording and the way the stop date input works, but the overall idea is great.

There was a previous try at adding extra scheduling options and this one is much better, as it adds additional options without making it more complex (on the contrary actually).

@kocsmy what do you think?

**Comment by kocsmy** [comment]
Nice improvements @emtwo thank you!

A few ideas quickly:
- Maybe use "Refresh every" instead of "Repeat empty" in order to stay consistent

- Stop scheduling input format is very complex and uncomfortable to type :) Considering we don't even have that feature now, maybe it'd be enough to just use a simpler (and more limited) 2018-05-28 format or similar. Just an idea, ultimately a proper GUI would be the best.

**Comment by jezdez** [comment]
@ranbena Thank you for merging this!!!
