### ISSUE TITLE
Non blocking widget refresh indicator

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2398]
When refreshing a dashboard widget the previous results are hidden by the refresh animation. This can be an issue when refreshing a dashboard frequently, as you might happen to see the spinner for long period of times.

To solve this we can keep showing the old data until new one is available, while showing some indication that refresh is in progress.

Is the following animation enough?

![](http://g.recordit.co/CyccMD6dFc.gif)

**Comment by arikfr** [comment]
@kocsmy

**Comment by kocsmy** [comment]
Yes @arikfr I think this is great and that animation should be enough. 

I assume the frame rate is low because of the recording/gif and it should be smooth movement.
