### ISSUE TITLE
New query UI issue

### ISSUE THREAD

**Issue by ialeinikov** [getredash/redash#2401]
### Issue Summary
Hi,

After a sequence of steps, parts of Redash's UI disappear.
 
### Steps to Reproduce

1. Create a new query 
2. Enter any data into the editor
3. Navigate to the "System status menu" (it could be that other options affecting UI as well). Redash prompts a warning pop-up:
 "You will lose your changes if you leave

Are you sure you want to leave this page?"
4. Press ESC or Cancel (on the pop-up).

### Technical details:

* Redash Version: Redash 4.0.0-rc.1
* Browser/OS: Chrome/MacOSX
* How did you install Redash: docker

Kind regards,
Ievgen.

**Comment by arikfr** [comment]
Thank you for reporting this. It was fixed in #2451.
