### ISSUE TITLE
Keyboard shortcut to collapse query editor/schema browser

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2402]
To help users take full advantage of the collapsible nature of the areas in the query editor screen, we need to add quick keyboard shortcuts to collapse query editor + schema browser or only the schema browser.

I was thinking about:

* `Alt+D`: hide all
* `Alt+Shift+D`: hide only schema browser

In terms of implementation it looks like we can add this in the `resizable-toggle` directive. It will need to accept a list of keyboard shortcuts, and then bind with them.

**Comment by arikfr** [comment]
@kravets-levko what do you think about the implementation plan?

**Comment by idoDavid** [comment]
Can you add collapsable queries to the editor as well? so if i'm using a lot of `with x as..` I would be able to collapse individual queries.

Also, a full-screen editor mode would be very useful.

**Comment by kocsmy** [comment]
@idoDavid We're improving the max-height of the query editor massively, would this help?

https://discuss.redash.io/t/increase-the-max-height-of-the-query-editor/1861/4

**Comment by arikfr** [comment]
@kocsmy no, it won't :)

@idoDavid that's a nice idea. you can check if Ace Editor (the component we use for code editing) supports collapsable regions and maybe take a stab at implementing? :)

**Comment by arikfr** [comment]
Implemented in #2640.
