### ISSUE TITLE
Add Funnel visualization to documentation

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2404]
* https://redash.io/help/user-guide/visualizations/visualization-types
* Edit Link: https://github.com/getredash/website/edit/master/website/_kb/user-guide/visualizations/visualization-types.md

**Comment by tonyjiangh** [comment]
@arikfr I'll do that.

**Comment by tonyjiangh** [comment]
@arikfr 
PR sent. If something's not right, plz let me know.

**Comment by arikfr** [comment]
Merged. Thanks!

**Comment by Hengjie** [comment]
Those who are like me who landed here because they were looking for Funnel query samples. Here's the link to the content:

https://discuss.redash.io/t/flow-sequence-queries-sankey-and-sunburst-visualizations/1703
