### ISSUE TITLE
Configuration option to show Chart legend at the bottom of the visualization

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2429]
Plot.ly supports showing the chart legend in the bottom of the chart instead on the right, as we show now. It will be great to expose this as an option in our chart editor (`Legend Position`: `Right`, `Bottom`, `Hide`).

**Comment by brylie** [comment]
I would like to help with this issue, once I wrap up the refactoring work in #3837

**Comment by polmonso** [comment]
On two axis plots the legend overlaps the vertical axis and makes it unreadable.

**Comment by susodapop** [comment]
Closed by https://github.com/getredash/redash/pull/4865
