### ISSUE TITLE
Deploy to Heroku button failing 

### ISSUE THREAD

**Issue by mnort9** [getredash/redash#2433]
### Issue Summary
Build fails when using the Deploy to Heroku button

<img width="623" alt="screen shot 2018-04-02 at 11 47 34 am" src="https://user-images.githubusercontent.com/1610579/38203300-c6735480-366c-11e8-86a5-8dd13cd482c5.png">

### Steps to Reproduce

1. Deploy to heroku from https://elements.heroku.com/buttons/mtsmfm/redash

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by arikfr** [comment]
This button was created by @mtsmfm and maintained here: https://github.com/mtsmfm/redash. You better report your issue there.

Although it looks completely unmaintained for the past 18 months... So you might want to look into alternative deployment methods: https://redash.io/help/open-source/setup.

**Comment by mtsmfm** [comment]
Yeah, I have no plan to maintain.
I've removed the repo.

**Comment by paulovitin** [comment]
@mtsmfm do you has a backup of the repo? Maybe I can continue maintain.
