### ISSUE TITLE
Cannot download dataset from unsaved query

### ISSUE THREAD

**Issue by jcsimps** [getredash/redash#2456]
### Issue Summary

Datasets cannot be downloaded unless the query is first saved.

If I try to download a dataset from an unsaved query, I get routed to an error page and I lose the entire dataset and the unsaved query. This is on Windows.

My colleague on Mac at least gets a warning popup about leaving the page and can cancel the request.

I don't necessarily want to save every query. I may just want a one-time data pull. But I have to save the query in order to download the dataset. And then there's no way to delete saved queries.

### Steps to Reproduce

1. Write and execute any query.
2. With the resulting dataset, click the button to "Download Dataset." I don't think it matters whether you attempt to download CSV or Excel.
3. If the query is unsaved, you'll get routed to an error page (Windows, Chrome) or get a popup warning (Mac, Safari). Trying to go back will show that you've lost the query and the resulting data.
4. Now try writing and executing the same query. Save it. Then attempt the download. No problem!

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Downloading datasets should be doable regardless of whether the query has been saved.

### Technical details:

* Redash Version: unknown
* Browser/OS: Chrome/Windows
* How did you install Redash: not installed, using web access

**Comment by ramziyassine** [comment]
We had experienced this [at our organization](https://github.com/hudl/) Thank you for reporting this.

**Comment by kyoshidajp** [comment]
I think this issue is already fixed by #2134. So you will be able to download after v4.0.0.

**Comment by arikfr** [comment]
@kyoshidajp is correct. It was indeed fixed and will be part of the final release.
