### ISSUE TITLE
When viewing a query (not editing), "fork" option is clickable but non-functional

### ISSUE THREAD

**Issue by ben-lantern** [getredash/redash#2459]
Redash 4.0.0-rc.1

1) Open a query without editing its source
2) Click ... on the top-right

Expected:

Either "Fork" is not shown (since I'm not in "edit source" mode, that may be fine), or if it is shown it is functional

Actual:

"Fork" is shown but it is not functional.  When you click on it, the query is not forked. If you look in My Queries and All Queries, no copy is apparent.

**Comment by RichardLitt** [comment]
Thanks, @ben-lantern! Hope this works for you.
