### ISSUE TITLE
Athena queries - Incorrect error message on v4

### ISSUE THREAD

**Issue by rohanpd** [getredash/redash#2461]
### Issue Summary

Athena queries are not returning a reasonable error message when failing in v4 they were returning a correct error message in v2.

v2 experience:
![image](https://user-images.githubusercontent.com/7199904/38777535-f4707ebe-40ec-11e8-8ae1-4a8e25148689.png)

Error message showing that table or a column can not be found

v4 experience:
![image](https://user-images.githubusercontent.com/7199904/38777528-dd5e316c-40ec-11e8-8331-e11640b3126c.png)

Error message showing `"Class '__builtin__.NoneType' is not mapped"`

### Steps to Reproduce

1. Run a query that has a syntax error in a table or column name

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 4.0.0-rc.1
* Browser/OS: Chrome
* How did you install Redash: Docker

**Comment by arikfr** [comment]
I think it was fixed with https://github.com/getredash/redash/commit/193a6cce3facdcbd11ee141e2c07387deefc5c19 (part of `4.0.0` final).

**Comment by arikfr** [comment]
@rohanpd can you confirm if this was fixed by the final release of v4?

**Comment by rohanpd** [comment]
Yes, can confirm that this is working now in the final release.

Thanks!
