### ISSUE TITLE
version.redash.io not updated with v4 release

### ISSUE THREAD

**Issue by jbransen** [getredash/redash#2464]
The v4 release of redash is there, which is great! I'd like to update with the update script, but as https://version.redash.io/ is not updated yet, the script doesn't find a new version. Please update that page (or actually https://version.redash.io/api/releases as well)

**Comment by arikfr** [comment]
`version.redash.io` was updated. Fire up the upgrade scripts ;-)

**Comment by ferhatelmas** [comment]
@arikfr how about 4.0.1 ?

**Comment by arikfr** [comment]
@ferhatelmas that's there too :)

**Comment by ferhatelmas** [comment]
@arikfr upgraded, thank you :heart:

**Comment by ferhatelmas** [comment]
@arikfr can we get it updated ? thanks

**Comment by arikfr** [comment]
@ferhatelmas for v5? Done.

**Comment by ferhatelmas** [comment]
@arikfr yes, it was for v5. Thanks a lot :heart:
