### ISSUE TITLE
Helm chart to deploy Redash on Kubernetes

### ISSUE THREAD

**Issue by grugnog** [getredash/redash#2466]
### Issue Summary

I have developed a Helm chart that deploys Redash on Kubernetes: https://github.com/kubernetes/charts/pull/5071

### Technical details:

* Kubernetes is a popular open source cluster container orchestration system.
* Helm is an open source package manager for Kubernetes: https://helm.sh/
* The Helm community maintains a directory of charts ("packages") that provides "one command deployment" of a wide range of tools: https://github.com/kubernetes/charts

The above PR is a chart I authored for Redash - it has not yet been merged by the charts repo managers but hopefully will be at some point.

The chart will deploy the Redash server as well as separate ad-hoc and queued worker containers. These are configured to use a PostgreSQL and Redis containers which are managed using the existing Helm charts for these tools. A persistent volume claim is created for PostgreSQL and an Ingres controller can be enabled to proxy inbound requests.

For more detail please see the README at https://github.com/grugnog/charts/blob/redash/incubator/redash/README.md

I would love to see if the Redash team has any feedback on this or is interested in co-maintaining this chart :)

**Comment by arikfr** [comment]
Hi 👋 

Apologies it took so long to follow up. Between the V4 release and all the incoming stuff we have, I was a bit behind on GitHub issues/PRs.

Thank you and @valentin2105 for giving a stab at creating a Helm Chart for Redash. I'm sure it will be useful for many! 

I'll be happy to chime in on some things to change (if there are) in how the chart deploys Redash -- should I make my comments here or in https://github.com/kubernetes/charts/pull/5071?

Also, is there a point in having this pull request, given we have one for the official repository?

**Comment by grugnog** [comment]
@arikfr firstly - thanks for making such a great product and thanks for making it FOSS :fireworks: 

If you could make comments on kubernetes/charts#5071 that would be great - if they are more substantive requests we can always spin them out to follow-ups. 

This issue (it's not a PR itself) was just a way to let your team know about the work happening in the official repository. I don't think there is any action needed other than confirming that you are now aware, so you can probably close this :)

**Comment by arikfr** [comment]
👍 

> This issue (it's not a PR itself) was just a way to let your team know about the work happening in the official repository. I don't think there is any action needed other than confirming that you are now aware, so you can probably close this :)

Oops. I was triaging so many issues/PRs yesterday, that I didn't notice. 😅

**Comment by yzorg** [comment]
@arikfr Please consider reopening this issue and moving the helm chart to the getredash org in GitHub.  The PR went stale waiting for contribution agreement and vacations, and now the helm stable is no longer accepting new charts.  Now they prefer external chart repositories that are submitted to Helm Hub.  If @grugnog is no longer working on this I would volunteer.  (And after 18 months I wouldn't blame him.)

They suggest helm chart repos can be hosted as GitHub pages, which can host the documentation on variables and use.
