### ISSUE TITLE
Scroll on viewing data in tables is malfunctioning in safari 

### ISSUE THREAD

**Issue by iel19** [getredash/redash#2471]
### Technical details:

* Redash Version: 4.0.0+b3948
* Browser/OS: High Sierra, 10.13.2. Safari Version 11.0.2 (13604.4.7.1.3)

**Comment by arikfr** [comment]
It's a bit hard to understand what exactly is the problem. Can you add more details and/or screenshots?

Thanks.

**Comment by arikfr** [comment]
Closing. You're welcome to reopen with additional details.
