### ISSUE TITLE
Add custom color option in color picker

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2480]
(when picking a color for a chart series, for example)

We need to make sure that we use a single component for color picking across the application, so we don't have to redo this in every other visualization.

(Related: #2476)

**Comment by arikfr** [comment]
#4136 implemented the component, we just need to make sure to use it everywhere now...

**Comment by arikfr** [comment]
@kravets-levko I guess we can close this now?

**Comment by kravets-levko** [comment]
@arikfr  I think yes - color picker now has an input where user can type any color (in CSS hexadecimal format or predefined CSS constants like `red`/`yellow`/etc.)
