### ISSUE TITLE
Add ability to search table column names in schema browser

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#2484]
### Issue Summary

When using the schema browser to browse tables of data sources with a lot of columns it would be useful to in addition to optionally match the names of the columns in a specific table.

E.g.

In addition to search for "name-of-table" allow "name-of-table:column-name" or similar. Also "name-of-table:mn-n" would match "name-of-table:column-name" as well.

### Steps to Reproduce

1. Use table name to search in schema browser.
2. Try to find the name of a wanted column by continue to type.

A work-around right now is to use the page search on the browser side to find the column name.

Considering the use of a data source agnostic delimiter would be useful to prevent overlap with table names.

### Technical details:

* Redash Version: 4.0.0rc1
* Browser/OS: Firefox/macOS
* How did you install Redash: Docker

**Comment by arikfr** [comment]
Sounds good to me. I like `:` as a delimiter, but BigQuery uses `:` in table names to separate project name from the dataset/table name. 

We can either ignore this fact or maybe we can just use space (` `) as a separator? 

Anyway, you (or anyone else) welcome to submit a pull request 👍

**Comment by kocsmy** [comment]
+1, sounds like a nice improvement to me

**Comment by jezdez** [comment]
Closed via #2681.
