### ISSUE TITLE
Table: sorting breaks for a mix of strings and nulls

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2486]
Using data from the following query as an example:

```SQL
select null as x

union all

select '' || s.a % 2 AS x FROM generate_series(1,14) AS s(a)

union all

select null as x
```

(generates a series of 0,1 values along with two `nulls`)

If you try to sort it, it places the nulls in random places.

**Comment by arikfr** [comment]
@kravets-levko do you know if this was fixed in the React migration?

**Comment by kravets-levko** [comment]
I think it was fixed even before Table migration to React. I'll check it ASAP and will reply in this thread.

**Comment by arikfr** [comment]
:+1: 

(no rush though. just stumbled at this issue and wanted to verify)

**Comment by kravets-levko** [comment]
@arikfr Yes, this was fixed (see screenshots):
https://github.com/getredash/redash/blob/9b290913a6dec8dbed0f91444fb85fe704ee4840/client/app/visualizations/table/utils.js#L187-L191

![image](https://user-images.githubusercontent.com/12139186/66384084-c33f1b00-e9c6-11e9-81e3-e03d330c3aeb.png)
![image](https://user-images.githubusercontent.com/12139186/66384097-c934fc00-e9c6-11e9-9138-edca515bad83.png)
![image](https://user-images.githubusercontent.com/12139186/66384115-d225cd80-e9c6-11e9-8eb3-b722fbf8b588.png)

**Comment by kravets-levko** [comment]
@arikfr I guess we can close the issue as it's already fixed.
