### ISSUE TITLE
we have too many query.getData() watchers

### ISSUE THREAD

**Issue by amirnissim** [getredash/redash#249]
this log show a query page load

![screen shot 2014-07-29 at 1 34 40 pm](https://cloud.githubusercontent.com/assets/1098126/3733812/57942df6-170c-11e4-9fa5-285615009ac1.png)

**Comment by kravets-levko** [comment]
We just migrated entire application to React, so this issue looks not relevant now. I'm closing it, but feel free to reopen if needed. Thanks!
