### ISSUE TITLE
Upgrade from 3.0.0 to 4.0.0 hangs 

### ISSUE THREAD

**Issue by ilanbe** [getredash/redash#2490]
### Issue Summary
Upgrade using the upgrade script to upgrade redash from 3.0 to 4.0. 
Scripts hangs at the migration step, and will not continue or print notification 
need to abort script manually 

Is there any log to the upgrade script to try and look for an answer?
is this a known issue?

#### Tried :

1.Stopping all redash processes via supervisor and run upgrade script again

2. Delete new version; restart and run script again 

### Steps to Reproduce
1. execute the upgrade script

#### expected : 
 Upgrade to be completed 
OR 
error message on why upgrade hangs 

### Technical details:

* Self hosted installation on Ubuntu 16.04
* Existing Redash Version: 3.0.0.b3134
*  upgraded Redash Version: 4.0.0.b3948

**Comment by arikfr** [comment]
This is most likely a usage issue, so I followed up on the forum post: https://discuss.redash.io/t/failed-to-upgrade-from-3-0-0-to-4-0-0/1825.
