### ISSUE TITLE
Boolean nullable field displayed as false when string is empty on reDash 4

### ISSUE THREAD

**Issue by innovia** [getredash/redash#2491]
### Issue Summary
A table with a boolean field is being displayed as "false" when the value that was inserted is null.

source database is Redshift
 
reDash 1 ( works as expected)
![image](https://user-images.githubusercontent.com/112025/39294427-67f532bc-4944-11e8-9ac8-3bf6afef311c.png)

reDash 4 - displays the null field as false

![image](https://user-images.githubusercontent.com/112025/39294475-87083c9e-4944-11e8-84a3-97ad3cba2567.png)
### Steps to Reproduce
1. Create a  new table with a boolean field:
```sql
create table boolean_test (my_field boolean);
```
2. insert values into the table
```sql
INSERT INTO boolean_test VALUES (true);
INSERT INTO boolean_test VALUES (false);
INSERT INTO boolean_test VALUES (null);
```
3. run the query in reDash 4:
```sql
select * from boolean_test
```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
I expect the same results as in reDash v1. querying this type of field does not necessarily should evaluate to false when null - i.e no data was given by this field

### Technical details:

* Redash Version: 4.0.0
* Branch: master
* From PR: https://github.com/getredash/redash/pull/2489
* Browser/OS: chrome
* How did you install Redash: docker.

**Comment by arikfr** [comment]
Good catch. Quick workaround: save the query, edit the visualization and change the column type to `Text` instead of `Boolean`.

**Comment by innovia** [comment]
shouldI submit a PR for the CreateBooleanFormater like in this PR ?https://github.com/getredash/redash/pull/2469/files

**Comment by arikfr** [comment]
> shouldI submit a PR for the CreateBooleanFormater like in this PR ?

Yes, this will be great! Thanks.

**Comment by innovia** [comment]
@arikfr 
#2523
