### ISSUE TITLE
Redash search shows no indication while search is running

### ISSUE THREAD

**Issue by fbertsch** [getredash/redash#2493]
Steps to reproduce:
- Search for something

Expected Results:
- The search is obvious that it's searching

Actual Results:
- The results show no No results found, which is terribly confusing, because it doesn't know if it's found results yet.

Screenshot: https://screenshots.firefox.com/aDlrgDSLp85o7r8f/sql.telemetry.mozilla.org

**Comment by fbertsch** [comment]
We are on version `4.0.0-rc.1`, locally I'm MacOS on Firefox.

**Comment by jezdez** [comment]
This was fixed in #2573.
