### ISSUE TITLE
User select in "Manage Permissions" is slow or not responsive

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#2495]
### Issue Summary

It takes several tries and/or a bit of waiting for a dropdown of users to show up when I click on "Manage Permissions" for a query

### Steps to Reproduce

1. Edit a query and click on "Manage Permissions"
2. Type in search input and see the response being slow

We have around 1000 users and the select pulls a list of all users whenever a character is typed into the ui-select-choices form input.

Looking at the code there seems be a query for the user list API without limiter or more detailed query for server side filtering. Plus `refresh-delay` of the `ui-select-choices` element is set to `0` implying that API requests are done on every keypress which could increase the likelihood of slow responses.

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by arikfr** [comment]
Long term solution:  implement proper search, pagination and backend sorting/filtering for all the resources to avoid such issues. 

Short term solution: make sure it loads users list once and filters on the client.

**Comment by jezdez** [comment]
Makes sense to me.

For the short term solution -- IIUC -- increasing the `refresh-delay` to say `100` would at least reduce the number of queries while typing.

**Comment by arikfr** [comment]
Sounds right to me 👍

**Comment by jezdez** [comment]
Amazing, thank you!
