### ISSUE TITLE
Update latest tag in hub.docker.com at 4.0.0

### ISSUE THREAD

**Issue by arthtux** [getredash/redash#2502]
I try to install redash latest on docker (via docker-compose.production.yml) but the latest version in the docker hub is a 3.0.0 but the last stable version is 4.0.0 you can update this please? 

Thanks 

### Technical details:

* Redash Version: latest
* Browser/OS: Docker
* How did you install Redash: docker-compose docker-compose.production.yml

**Comment by arikfr** [comment]
Done.
