### ISSUE TITLE
Allow disabling password login directly from the settings, with LDAP login enabled.

### ISSUE THREAD

**Issue by bvergnaud** [getredash/redash#2508]
### Issue Summary

Password login cannot be disabled from the options' page with LDAP login enabled.

### Steps to Reproduce

1. Spawn a redash instance with LDAP login enabled, but do not disable password login (for instance with the env variable in your docker-compose).
2. Go in the settings.
3. See that the password login can only be disabled is you enable SAML. No mention is made of LDAP.

It's also worth noting that if you disable password login during `step 1` but someone enables and disables SAML from the settings page, password logins are now enabled and cannot be disabled easily.

I'm also interested in knowing how I could disable password login again without trashing the whole instance that I've started setting up.
I've tried deleting the redash_server_1 container and associated images in docker and rebuilding them (my docker-compose specifically disables password logins), to no avail. I couldn't find anything relevant in the postgres database. And the documentation was of no help with this issue. I'm not sure where to look next

Thank you !

### Technical details:

* Redash Version: 4.0.0
* Browser/OS: Firefox / OSX
* How did you install Redash: Using this repository on tag 4.0.0 and docker-compose

**Comment by arikfr** [comment]
We have no plans to work on this in the near future, but you (or anyone else) are welcome to take a stab at implementing this.

I didn't look into it in much detail, but I believe you can achieve the result you want (disable password login) using the environment variables settings.

As for the Docker question: you should consult Compose's documentation on how to apply env variables changes without replacing the image (should be possible).

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
