### ISSUE TITLE
Upgrade Celery to 4.x

### ISSUE THREAD

**Issue by atharvai** [getredash/redash#2517]
### Issue Summary

Celery 3.x does not allow limiting worker memory usage. This means one worker can use all of host's memory and affect function for other works and processes. Upgrading Celery to 4.x will allow adding `--max-memory-per-child` flag and limit the memory usage.

I understand that Mozilla is using Celery 4 with Redash, we'd like to hear about your experience and what it involved.

There is a discussion on Discourse at https://discuss.redash.io/t/upgrade-celery-to-4-x/1867
Please add your thoughts to that discussion.

@arikfr can you tag the Mozilla folks?

**Comment by jezdez** [comment]
Hey there, Mozilla engineer here, from what I've gathered from the ops folk, Celery 4 has beeen an improvement in terms of stability and responsiveness. But I'll let @robotblake chime in with more details who is on the operations side of our Redash instance.

**Comment by atharvai** [comment]
I've been away for over a week and just got back. 

Before I left had some work completed on [my fork](https://github.com/getredash/redash/compare/master...atharvai:celery_upgrade). I'll start testing but would like input from @robotblake @arikfr.

cc @mashrikt if you have already done some work would be good to get your input too.

**Comment by atharvai** [comment]
@arikfr are you OK with me creating a Work In Progress (WIP) PR to take advantage of automated tests? I've gone tests running locally and passing but there's some funkiness with Celery and Windows. I'll try docker today but I feel more confident with the automated tests than local.

**Comment by arikfr** [comment]
Redash v6 will use Celery v4.
