### ISSUE TITLE
Search is not working in 4.0.1

### ISSUE THREAD

**Issue by boyaq** [getredash/redash#2519]
### Issue Summary

Query search is not working. No error logs in server log

### Steps to Reproduce

1. upgrade 3.0 to 4.0.1 in docker
2. run the server and search a query

### Technical details:

* Redash Version: 4.0.1.b4038
* Browser/OS:  FireFox 59.0.2 (64-bit) / ubuntu 16.04
* How did you install Redash: docker

**Comment by boyaq** [comment]
1. I upgrade it by manually and had problems, then i saw a post on the forum. Then i upgrade it as you said in the post https://discuss.redash.io/t/upgrading-from-v3-to-v4-using-docker/1828/2

2. the `search_vector` column are all `NULL`for the entries.

**Comment by arikfr** [comment]
Something didn't work correctly when you ran the migrations and the search vector wasn't populated, hence the empty search results.

You need to figure out how to run it manually :-\ 
I think it's this migrations: https://github.com/getredash/redash/blob/master/migrations/versions/6b5be7e0a0ef_.py
