### ISSUE TITLE
Refresh all on dashboard does not actually refresh the widget

### ISSUE THREAD

**Issue by goodwill** [getredash/redash#2521]
### Issue Summary

As title, using Chrome hitting refresh button on dashboard does not refresh data at all. The only way to really refresh data is to hit individual buttons under the widget, this is pretty annoying especially when there is good amount of widgets. Note I use global parameters, not sure if this could be the reason.

### Steps to Reproduce

1. Hit Refresh
2. Notice the timestamp for last refresh under which widget doesn't change.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 4.0.0
* Browser/OS: Chrome 66.0.3359.139 (Official Build) (64-bit) on macOS High Sierra
* How did you install Redash:
Docker image based on 4.0.0 source code. I built my own image as the official image is not updated

**Comment by arikfr** [comment]
I remember that at some point the master branch had a bug with dashboard refresh, but it was fixed before the final release of v4. You should try pulling the latest image and checking if it resolves for you.

If you still have this issue after updating to 4.0.1, please re-open.

Thanks.
