### ISSUE TITLE
Postgres MONEY type values are not displayed in data labels on charts

### ISSUE THREAD

**Issue by clayheaton** [getredash/redash#2528]
### Issue Summary

Queries that present values of the [`MONEY`](https://www.postgresql.org/docs/current/static/datatype-money.html) type in Postgres do not display in the data labels when hovering over line charts.

### Steps to Reproduce

1. Here's the top of a query casting to the `MONEY` type:

```
SELECT metric_date,
       CAST(SUM("current year") AS MONEY) AS "current year",
       CAST(SUM("previous year") AS MONEY) AS "previous year"
...
```

It displays like this:

![screen shot 2018-05-11 at 9 12 36 am](https://user-images.githubusercontent.com/205364/39925936-9ae15f3a-54fb-11e8-8df5-a681b54ae011.png)

Here's the same query, casting to `INTEGER` type:

```
SELECT metric_date,
       CAST(SUM("current year") AS INTEGER) AS "current year",
       CAST(SUM("previous year") AS INTEGER) AS "previous year"
...
```

It displays like this:

![screen shot 2018-05-11 at 9 11 07 am](https://user-images.githubusercontent.com/205364/39925986-c3bcbe40-54fb-11e8-913a-01ffda9b2bdb.png)

I would expect the values to appear in the labels when the `MONEY` type is used

### Technical details:

* Redash Version: 4.0.0
* Browser/OS: Chrome / MacOS
* How did you install Redash: Google Cloud Image provided by Redash

**Comment by arikfr** [comment]
This was fixed recently and the fix will be part of v6.
