### ISSUE TITLE
Does redash support oracle database and windows?

### ISSUE THREAD

**Issue by Leedorado** [getredash/redash#2531]
Oracle database and windows system are used in my company,and I consider replacing the old-fashioned BI tool with Redash.So,I wonder if redash support the above both.
THX.

**Comment by kravets-levko** [comment]
hi @Leedorado! Yes, Redash supports Oracle database (see the [list of supported data sources](https://redash.io/help/data-sources/supported-data-sources)). It should be possible to run Redash on a Windows machine, but we don’t know anyone who did this and lived to tell. We recommend using some sort of a virtual machine or Docker in such case.

Also, please note that GitHub is more for a technical issues and bug tracking. Please next time check out [Redash knowledgebase](https://redash.io/help/) or use [our forum](https://discuss.redash.io/) to get a support. Thanks!

**Comment by MakremHammali** [comment]
Hi 
is there anyone who installed  redash on a Windows machine with docker ?

**Comment by kravets-levko** [comment]
Hi @MakremHammali! Please use our [Forum](https://discuss.redash.io/) for support questions. Thanks!
