### ISSUE TITLE
Nginx keeps failing saying host not found in upstream "redash:5000" 

### ISSUE THREAD

**Issue by GaudamThiyagarajan** [getredash/redash#2532]
### Issue Summary
When I try to start the server with `docker-compose -f docker-compose.production.yml up`. Every process starts except nginx where it fails saying 

```
nginx_1     | 2018/05/14 09:22:19 [emerg] 1#1: host not found in upstream "redash:5000" in /etc/nginx/conf.d/default.conf:2
nginx_1     | nginx: [emerg] host not found in upstream "redash:5000" in /etc/nginx/conf.d/default.conf:2
```

### Steps to Reproduce

1.  Install docker
2.  docker-compose -f docker-compose.production.yml run --rm server create_db
3. docker-compose -f docker-compose.production.yml up

### Technical details:

* Redash Version: Latest redash docker image
* OS: Ubuntu 16.04.4 LTS (Xenial Xerus)
* How did you install Redash: through docker-compose

**Comment by arikfr** [comment]
I just ran `docker-compose` with the `docker-compose.production.yml` file and it worked and didn't show the reported error. 

It's hard to tell what exactly wrong in your setup, but I would confirm that your `docker-compose` version supports Version 2 of the docker-compose config file format.
