### ISSUE TITLE
When adding an empty query to a dashboard the dashboard stops rendering

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2534]
1. Create a dashboard
2. Create an empty query (i.e. create a new query, write nothing in it, and save it).
3. Add above query to the dashboard.

Result: you can no longer edit this dashboard and it will no longer render its widgets.
Expected: everything works fine.

The issue seems to happen due to the code trying to load result but there is no query.

**Comment by is2ei** [comment]
Hi @arikfr 
Could I work on this issue?

**Comment by kravets-levko** [comment]
hi @is2ei! of course you can - we appreciate any help from community :+1:
