### ISSUE TITLE
Migrate from Flask-OAuthlib to Authlib

### ISSUE THREAD

**Issue by lepture** [getredash/redash#2548]
I see that you are using Flask-OAuthlib for OAuth authentication [here](https://github.com/getredash/redash/blob/master/redash/authentication/google_oauth.py). It would be better to replace it with [Authlib](https://authlib.org/) since Flask-OAuthlib is deprecated.

Here is a guide: https://blog.authlib.org/2018/migrate-flask-oauthlib-client-to-authlib

And there are many built-in connections in https://github.com/authlib/loginpass which can be used directly. If you'd like, I can send a PR to finish the replacement.

- Checkout Authlib repository: https://github.com/lepture/authlib
- Authlib documentation: https://docs.authlib.org/

**Comment by arikfr** [comment]
Thank you for your work on these libraries and the generous offer of helping with the migration!

My only reservation here is the license you chose for Authlib (AGPL). While I don't mind paying for the commercial license for our hosted platform (app.redash.io), I'm not sure about the implication for future adoption of Redash or how it's compatible with our current license (BSD-2).

**Comment by lepture** [comment]
@arikfr thanks, Sorry, I didn't know this would be a problem until https://github.com/lepture/authlib/issues/59 I didn't even know that would force others to change their licenses.

**Comment by arikfr** [comment]
@lepture thank you for the link. I will try to see if I can come up with any ideas on how to resolve this. If I do I'll share my thoughts in https://github.com/lepture/authlib/issues/59.
