### ISSUE TITLE
aws athena FAILED: ParseException line 1:0 cannot recognize input near '/' '*' 'Username'

### ISSUE THREAD

**Issue by zynbasil** [getredash/redash#2556]
aws athena

run this sql:MSCK REPAIR TABLE tablename

FAILED: ParseException line 1:0 cannot recognize input near '/' '*' 'Username'

**Comment by dmpacheco** [comment]
Think this bug is related to [this closed ticket](https://github.com/getredash/redash/issues/2399).

**Comment by arikfr** [comment]
@dmpacheco is correct. @zynbasil please read the discussion on the linked issue.
