### ISSUE TITLE
Datetime format on CSV is different.

### ISSUE THREAD

**Issue by GitSumito** [getredash/redash#2557]
### Issue Summary

When I download CSV file on the queries page, 
the datetime format that CSV has is not as same as an original data.
is this a bug or a feature?

Original data on MySQL is "2018-01-23 14:00:30"
Redash CSV is "2018-01-23T14:00:30"

I'd like to get rid of "T".

* Redash Version:  redash:4.0.0-rc.1 
* Browser/OS: Chrome
* How did you install Redash: Docker

**Comment by GitSumito** [comment]
@RichardLitt 
thank you for adding Labels on the ticket.

**Comment by ariarijp** [comment]
Hi @GitSumito ,

FYI, here is a simple workaround.

```sql
SELECT DATE_FORMAT(NOW(), '%Y-%m-%d %H:%i:%s') now;
```

it worked on Redash 4.0.1+b4038 and MySQL 5.7.20.

I hope this helps.
