### ISSUE TITLE
Encoding error on alert email : "Mail send error"

### ISSUE THREAD

**Issue by DependencyHell** [getredash/redash#2575]
Hello Arik and the Redash team,

thanks for this awesome open source project!

I just want to submit a small issue

### Issue Summary

Alert is not sending email with characters such as "ô" in the name.

### Steps to Reproduce

1. Create a query
2. Create an alert on this query
3. In the name of the alert, set a character such as "ô"
4. Check the log file of the worker :

```
Mail send error.
Traceback (most recent call last):
  File "/app/redash/destinations/email.py", line 48, in notify
    subject=subject_template.format(alert_name=alert_name, state=state),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 31: ordinal not in range(128)
```

[File "/app/redash/destinations/email.py", line 48](https://github.com/getredash/redash/blob/672c86efaa4eee7ed4295fe021431409e418de57/redash/destinations/email.py#L48)

I think it should be printed encoded into utf-8.

### Technical details:

* Redash Version: Redash 4.0.1+b4038 
* Browser/OS: Chrome/Linux
* How did you install Redash: setup using Docker

**Comment by RichardLitt** [comment]
Thanks for the informative issue, @DependencyHell (nice GitHub name). This sounds like you know what the error is exactly; would you be able to make a PR for this?

**Comment by arikfr** [comment]
@DependencyHell can you confirm if the change in #2605 fixes this?

Thanks!

**Comment by DependencyHell** [comment]
@arikfr @RichardLitt whoops, seems I missed some notifications

The bug is now fixed, thank you!
