### ISSUE TITLE
DynamoDB nested field query returns blank.

### ISSUE THREAD

**Issue by juanjoLenero** [getredash/redash#2577]
### Issue Summary

When querying a nested field with DQL, the field shows blank in the table visualization.

![image](https://user-images.githubusercontent.com/2656008/41178173-17b52686-6b2c-11e8-96c5-d41899858576.png)

### Steps to Reproduce

1. Have a DynamoDB table with a map field. E.g.
![image](https://user-images.githubusercontent.com/2656008/41178304-7a86771a-6b2c-11e8-9f2a-5dd6cec2b3aa.png)

2. Add DynamoDB as a data source and create a query where you try to access a nested field.
E.g. `scan survey.age from surveys;`

### Technical details:

* Redash Version: 4.0.1+b4038
* Browser/OS: Chrome 66.0.3359.181 MacOS High Sierra
* How did you install Redash: AWS us-east-1 AMI (ami-2d3c0a56) then upgrade via ssh.

**Comment by arikfr** [comment]
What version of `dql` do you have? (`pip list | grep dql`)

**Comment by juanjoLenero** [comment]
dql (0.5.16)

**Comment by arikfr** [comment]
You should update to the latest version, as if I remember right it fixes this issue.

Please reopen if you still have this issue after upgrading.
