### ISSUE TITLE
On submitting correct login credentials getting Blank page  

### ISSUE THREAD

**Issue by SarathkumarJ** [getredash/redash#2589]
Pls Find the docker compose log

server_1    | [2018-06-16 18:53:28,811][PID:151][INFO][werkzeug]  * Debugger pin code: 317-177-462
server_1    | [2018-06-16 18:53:30,373][PID:151][INFO][metrics] method=GET path=/ endpoint=redash_index status=304 content_type=text/html; charset=utf-8 content_length=568 duration=1469.89 query_count=2 query_duration=450.11
server_1    | [2018-06-16 18:53:30,376][PID:151][INFO][werkzeug] 172.19.0.1 - - [16/Jun/2018 18:53:30] "GET / HTTP/1.1" 304 -
server_1    | [2018-06-16 18:53:30,594][PID:151][INFO][metrics] method=GET path=/images/favicon-32x32.png endpoint=redash_send_static status=200 content_type=image/png content_length=2005 duration=0.77 query_count=0 query_duration=0.00
server_1    | [2018-06-16 18:53:30,595][PID:151][INFO][werkzeug] 172.19.0.1 - - [16/Jun/2018 18:53:30] "GET /images/favicon-32x32.png HTTP/1.1" 200 -

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by RichardLitt** [comment]
Thanks, @SarathkumarJ. Can you fill out the rest of the information in the template please?

**Comment by arikfr** [comment]
Closing. You're welcome to reopen with additional details.
