### ISSUE TITLE
Widget size selector is not displayed in the Add Widget window

### ISSUE THREAD

**Issue by alison985** [getredash/redash#2595]
Copies https://github.com/mozilla/redash/issues/324

Mozilla's QA person identified that the Widget Size Selector is no longer in the add a widget to a dashboard modal. 

Is this intentional behavior in getredash or a bug?

**Comment by kocsmy** [comment]
Since you have much more control over the widget sizes (you can easily drag and resize widgets), the size selector kinda became irrelevant and it's removed.

**Comment by arikfr** [comment]
As @kocsmy mentioned the size selector was removed on purpose as it's no longer needed.
