### ISSUE TITLE
Widget layout inconsistency when upgrading from 4.0.0+b3387 to 4.0.1+b4038

### ISSUE THREAD

**Issue by Felhamed** [getredash/redash#2599]
### Issue Summary

I have used the provisioning script on a clean install of Ubuntu 16.04, I had first upgraded to 4.0.0 then a few weeks later to 4.0.1. The widget layout after the update to 4.0.1 doesn't center properly as compared to before.

The queries are the exact same, with table components set to be centered.

Please see these 2 images:
[Version 4.0.0](https://i.imgur.com/qDQBM9k.png)

Version 4.0.1:
[Version 4.0.1](https://i.imgur.com/E4got8s.png)

**Comment by arikfr** [comment]
This is the intended behavior. While visually it might looks not as nice, it makes it easier to read the data. As you can resize widgets now, you can simply change the widget width to accommodate the data.
