### ISSUE TITLE
Update Redash 3.0 to 4.0 error

### ISSUE THREAD

**Issue by vinhduy11** [getredash/redash#2600]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

[root@opertool-9-201 bin]# ./upgrade 
Starting Redash upgrade:
Found version: 4.0.1
Current version: 3.0.0+b3134
* Before doing an upgrade, please make sure you have a backup.
* If you have any issues, please refer to the troubleshooting section in the upgrade guide:
  https://redash.io/help/open-source/admin-guide/how-to-upgrade
* If the upgrade guide doesn't help, you can ask for help on the forum (https://discuss.redash.io).   

Full CHANGELOG for this release: https://github.com/getredash/redash/blob/master/CHANGELOG.md
Continue with upgrade? (y/n): y
Downloading release tarball...
Unpacking to: redash.4.0.1.b4038...
Changing ownership to redash...
Linking .env file...
Installing new Python packages (if needed)...
Running migrations (if needed)...
Failed running: sudo -u redash bin/run ./manage.py db upgrade
Exit status: 1
Output:
/usr/lib/python2.7/site-packages/sqlalchemy_searchable/parser.py:107: SyntaxWarning: Cannot combine element of type <type 'NoneType'> with ParserElement
  ).setResultsName('and') |
/usr/lib/python2.7/site-packages/sqlalchemy_searchable/parser.py:108: SyntaxWarning: Cannot combine element of type <type 'NoneType'> with ParserElement
  not_
Traceback (most recent call last):
  File "/opt/redash/redash.4.0.1.b4038/manage.py", line 6, in <module>
    from redash.cli import manager
  File "/opt/redash/redash.4.0.1.b4038/redash/__init__.py", line 72, in <module>
    import_query_runners(settings.QUERY_RUNNERS)
  File "/opt/redash/redash.4.0.1.b4038/redash/query_runner/__init__.py", line 179, in import_query_runners
    __import__(runner_import)
  File "/opt/redash/redash.4.0.1.b4038/redash/query_runner/query_results.py", line 9, in <module>
    from redash import models
  File "/opt/redash/redash.4.0.1.b4038/redash/models.py", line 38, in <module>
    from sqlalchemy_searchable import SearchQueryMixin, make_searchable, vectorizer
  File "/usr/lib/python2.7/site-packages/sqlalchemy_searchable/__init__.py", line 17, in <module>
    parser = SearchQueryParser()
  File "/usr/lib/python2.7/site-packages/sqlalchemy_searchable/parser.py", line 49, in __init__
    self._parser = self.parser()
  File "/usr/lib/python2.7/site-packages/sqlalchemy_searchable/parser.py", line 108, in parser
    not_
  File "/usr/lib/python2.7/site-packages/pyparsing.py", line 2927, in __lshift__
    self.mayReturnEmpty = other.mayReturnEmpty
AttributeError: 'NoneType' object has no attribute 'mayReturnEmpty'

### Technical details:

* Redash Version: redash.3.0.0.b3134
* Browser/OS: CentOS 7 x64
* How did you install Redash: use bootstrap.sh

I can't upgrade to version 3.0 by using CLI.

**Comment by arikfr** [comment]
This looks like a mismatch between the Python dependencies we expect and what you have. The setup process tries to upgrade the dependencies, but maybe something went wrong? Try updating manually and checking that everything is at the correct version.

Anyway, this looks like a setup issue and not a problem with Redash. If you still need help with this, I'll appreciate if you open a thread in our forum: https://discuss.redash.io/c/support/support-self-hosted.

Thanks.
