### ISSUE TITLE
Dashboard shows a spinner when query param has no value

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2602]
Current behavior:
When opening a dashboard with queries that use parameters, that have no default value, it will show the spinner on the widget indefinitely.

The correct behavior:
Show a message saying parameter value is required.

**Comment by arikfr** [comment]
@kravets-levko @kocsmy assigned to you both, as Levko will implement the functionality, but will need Zsolt's help for the UX/UI.

**Comment by kravets-levko** [comment]
It's more generic case: dashboard shows spinner on widgets always when `QueryResults` promise was rejected for this widget.
