### ISSUE TITLE
Error running query: UUID('...') is not JSON serializable

### ISSUE THREAD

**Issue by aiham** [getredash/redash#2623]
### Issue Summary

Querying mongo collection with UUID field fails with error.

### Steps to Reproduce

1. Run query `{ "collection": "myCollection", "query": { "foo": "bar" } }`
2. Observe error `Error running query: UUID('xxx') is not JSON serializable`

### Technical details:

Redash 3.0.0+b3134

**Comment by sibowyer** [comment]
I've encountered a similar error:
`Error running query: NumericRange(150, 1201, '[)') is not JSON serializable`
from a query which includes the line
`int4range(min(capacity), max(capacity), '[]')`

**Comment by aiham** [comment]
@mwvaughn I worked around it by making sure my projection did not include the UUID field.

**Comment by dncpax** [comment]
@sibowyer don't know if it's still useful to you but you can cast your range to text:
`(int4range(min(capacity), max(capacity), '[]'))::text`

**Comment by arikfr** [comment]
I'm pretty sure this was fixed a while ago by switching to simplejson and using our encoder that supports UUID.
