### ISSUE TITLE
ProgrammingError on Queries.search_vector does not exist 

### ISSUE THREAD

**Issue by BouchaaraAdil** [getredash/redash#2627]
hey Redash Team,

i got an error when creating queries on redash plateform,

`Error running query: (psycopg2.ProgrammingError) column queries.search_vector does not exist LINE 1: ...ule_failures, queries.options AS queries_options, queries.se... ^`

i’m using the last version of ` redash 4,`

NS: before, i had also `alembic.util.exc.CommandError: Can't locate revision identified by '78ebf428e6d0'` i resolve it by connecting to redash DB and dropped the alembic_version table, and run db init, and db migrate, db upgrade.

please any suggestions.

**Comment by arikfr** [comment]
It looks like your queries table is missing the `search_vector` column. 

When you run `db init` and the tables already exist, it doesn't touch your tables, but it does "stamp" the database version as the latest one (so further migrations won't apply). `db upgrade` in this case will do nothing either as your database reports to be in the latest version and `db migrate` is just a utility to create new migrations.

You need to figure out which migrations your database is missing, then you have two options --
1. Manually apply the needed changes.
2. Update `alembic_version` table to the migration before the one you need, and run `db upgrade`.

For further support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.
