### ISSUE TITLE
Allow the user to decide how to handle null values in charts

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2629]
When preparing chart data, we convert `null` values to zeros:

https://github.com/getredash/redash/blob/4384959760cad9ccd880c3e9004fd730ddeec035/client/app/services/query-result.js#L278-L280

This is not always what the user needs. The user should have the option to disable this behavior.

**Comment by toph** [comment]
Hi @arikfr ,

That particular line is especially problematic for multi-series charts where the series don't have data on identical x coordinates. For x-values where only one series has data, the others will have null (I believe--unless there is another way to model this?).

```
seconds,y1,y2
1.22,7,<null>
1.48,<null>,8
2.11,<null>,9
3.6,4,<null>
```

Or for category data...

```
day,alice,bob
1,eggs,pancakes
2,eggs,<null>
3,pancakes,<null>
4,<null>,eggs
```

For line charts on the above data, the nulls will be coerced to 0s and show up as points on the chart, even though that series had no y-value for that x-value. For the category data using a Scatter or Bubble, a new "0" category will appear that has an entry for every null value.  This affects other types of charts as well, but these two examples are illustrative.

Example screenshot from this data:
```
time,success,failure,size
1,job1,null,10
2,job2,null,23
3,null,job1,100
4,job2,null,7
```
![fake-category](https://user-images.githubusercontent.com/69527/48358200-44334c80-e668-11e8-94a1-ca79680488b6.png)

Forum post for reference:
https://discuss.redash.io/t/null-y-axis-category-values-being-included-as-0-for-two-series-bubble-chart/2673

**Comment by nick-at** [comment]
+1 on this issue. I have a line chart with measures that end on different dates. It's preferable that the null values are not be plotted rather than showing a nose dive on the chart 
![image](https://user-images.githubusercontent.com/34499982/61191469-69dc8e00-a6ee-11e9-9ee2-da7166fbbc71.png)
