### ISSUE TITLE
Redash metadata issues pulling database info for web UI application

### ISSUE THREAD

**Issue by doddjc21** [getredash/redash#2630]
### Issue Summary ###

Hello all, 
I am currently having the following issue in my personally hosted redash web application

After setting up my redash container and going to settings --> datasources --> +New datasource the following behavior occurs:
![no_datasource](https://user-images.githubusercontent.com/31855728/41935886-55ae8ea6-7959-11e8-8317-a14de02f9bd0.PNG)

As seen in the above example: sometimes the data source will show up and sometimes the data sources that I've configured or added to redash disappear. (shown below) 
![dstest](https://user-images.githubusercontent.com/31855728/41938037-f1681e42-795f-11e8-80fe-7deec9843a87.PNG)

![ds_test2](https://user-images.githubusercontent.com/31855728/41938048-f8da7e0e-795f-11e8-91f1-ee3dbd24009f.PNG)

![test_failed](https://user-images.githubusercontent.com/31855728/41938054-fb921382-795f-11e8-9701-5d5eac1bb7bc.PNG)

Do you have any idea why this behavior might be occurring or could give me more insight into how Redash pulls its data from the postgres database in order to serve the web content?  I will give more info about the environment file I use and other relevant info below in the technical details.

### Steps to Reproduce ###

1. Setup Redash on a CentOS container (more details below)
2. Run **source .env && /usr/local/bin/python2.7 ./manage.py database create_tables**
3. Run the following commands:
    **/usr/local/bin/python2.7 -u /usr/local/bin/gunicorn -b 127.0.0.1:5000 --name redash -w 4 --max-requests 1000 redash.wsgi:app > redash_gunicorn.log 2>&1 &**
    **/usr/local/bin/python2.7 -u /usr/local/bin/celery worker --app=redash.worker --beat -Q queries,celery,scheduled_queries > redash_celery.log 2>&1 &**

I believe this is a bug because the data should be persisting in the Redash application when I go to refresh the page instead of disappearing randomly and then randomly showing up again  

### Technical details: ###

* Redash Version: **Redash version 4.0.0**
* Browser/OS: **Google Chrome Version 67.0.3396.87 (Official Build) (64-bit)** 
* How did you install Redash: I installed Redash in a CentOS container running in a docker swarm environment with a base image containing the required packages and configurations to easily launch and configure Redash from scratch whenever I bring up a new swarm. 

- Redash runs out of a docker container with the services nginx and redis pre-installed, started and running along with all the required dependency packages installed 
- Redash uses an RDS postgres database for the backend 
- I do not use supervisord to control the flask worker processes but instead kick them off with commands and write the outputs to log files.  

Environment file (.env):
#!/usr/bin/env
export REDASH_LOG_LEVEL='DEBUG'
export REDASH_REDIS_URL='redis://localhost:6379/0'
export ORACLE_HOME='/usr/lib/oracle/12.2/client64'
export REDASH_ADDITIONAL_QUERY_RUNNERS='redash.query_runner.oracle'
export LD_LIBRARY_PATH='/usr/lib/oracle/12.2/client64/lib'
export REDASH_COOKIE_SECRET='***redacted***'
export REDASH_DATABASE_URL='postgresql://redash:****@redash-db-rds-24933.c2dytomtgk0k.us-east-1.rds.amazonaws.com/redash_db

Any help or insight is appreciated! Thank you!

**Comment by arikfr** [comment]
From the description and screenshots it looks like you have multiple instances of the process running, and one of them has Oracle support while the other doesn't. Hence sometimes you get an empty screen as it fails to load this data source type.

Also:

* It looks like you're using an old version, while it's not related to the issue you're having, I still recommend upgrading.

* If you're using a container, it's better to have each container handle one task instead of launching multiple commands in a single one. Also, we have the entrypoint script, which makes running commands easier.

Anyway, this looks like a setup issue and not a problem with Redash. If you still need help with this, I'll appreciate if you open a thread in our forum: https://discuss.redash.io/c/support/support-self-hosted.

Thanks.

**Comment by doddjc21** [comment]
Oh wow, did not realize there was an entrypoint script! Looks really solid, thank you.  Also, I only run redash on a single container but I think you are right in saying there are multiple processes running and some probably are not getting the environment information correctly.  I will do some more debugging to see if that is the case.  While I agree using multiple containers usually provides better performance and flexibility, I am avoiding this as I run a lot of other containers so it makes it easier to consolidate most of Redash's services into one.  Thanks again for the insight!
