### ISSUE TITLE
Dashboard Parameters

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2641]
Today to have a parameter at the dashboard level, we use the `global` flag for parameters.

New suggested flow:

* Deprecate the `global` flag.
* When adding a new widget to the dashboard, if the query has parameters we will show them to the user and let him pick what to do with them:
	1. Add the parameter to the dashboard (default option), creating a dashboard parameter.
	2. Map it to existing dashboard parameter (default option, if parameter with the same name exists).
	3. Give the parameter a static value.
	4. (Not sure we need this:) Keep it a standalone parameter at the widget level.

Things to think about:
* How to show if a widget is affected by a parameter? Maybe color code them, and show this color on the widget?

**Comment by kocsmy** [comment]
This is related: https://github.com/getredash/redash/pull/2656

**Comment by kocsmy** [comment]
This is also a great opportunity to improve the Add Widget modal and make it nicer.

**Comment by kocsmy** [comment]
<img width="802" alt="screenshot 2018-07-13 17 44 43" src="https://user-images.githubusercontent.com/2378022/42700574-734abd2c-86c4-11e8-838d-234de9a41f26.png">

I've created this wireframe for the new modal to open the discussion.

- I'm wondering if we should move the "Text box" option to somewhere out of this model. My assumption is that text boxes are not as widely used as query visualizations. (first I was considering using an option to select which one you like on the [top of this modal](https://www.dropbox.com/s/8pz9rfuzadl0cl4/Screenshot%202018-07-13%2017.46.34.png?dl=0))
- The parameters section is the challenge here. I think we need to improve the separation of the parameters and options for the different methods of adding them.

**Comment by arikfr** [comment]
👍 

How about we change the visualization selection from dropdown to multiple "cards" - one for each visualization, and show the parameters section after selecting the visualization?

Maybe even convert it to 3 steps:

1. Pick query (single screen, with recent queries and ability to search).
2. Pick visualization - at this point the query is selected and shown by name.
3. Setup parameters (if needed)

?

**Comment by arikfr** [comment]
>Add text box will get it's own modal and we're adding a separate button in edit dashboard mode:

👍 

> Here's how it looks if we break it down to 3 steps. I'm not 100% convinced we need this, it feels the process gets a bit complicated. I created a quick prototype to demonstrate how this would work: https://marvelapp.com/18514ie6

It's only complex because you made it complex 😅 Why the extra "Next" button? If it submits the action when you pick the query/visualization, it no longer feels that complex, right?

**Comment by kocsmy** [comment]
I think I understood your 3 steps idea too literally :)

https://marvelapp.com/18514ie6

I think you meant this, which works fine and much simpler indeed.

**Comment by kravets-levko** [comment]
@arikfr @kocsmy Can I start to implement it? BTW - what is the dropdown next to each parameter on third step (`Add to dashboard` / `Map to existing parameter`)? Maybe, it could be a sort of checkbox - `Add to dashboard`?

**Comment by arikfr** [comment]
@kravets-levko the reason it's a dropdown is because you have multiple options (Add to dashboard, Map to existing param, use static value).

I think you can start, but @kocsmy can confirm if he wants to do another iteration on the UX/design. Also, @kocsmy I think you should update the issue description with the latest mockup/design.

**Comment by jezdez** [comment]
@kravets-levko For the record, I've merged #2767 which has some overlap with this.
