### ISSUE TITLE
Explicit “Add Parameter” Button in Query Editor

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2644]
Add a button to the interface to add a parameter to the query. This button will open the current parameter definition dialog, but will let you also define the parameter keyword. Once submitted, it will add the `{{parameter}}` string into the query.

* This will help with the date range issue (#2643), as it can define the parameter keyword and then in the query you can use `{{keyword.start}}` and `{{keyword.end}}` to get the start/end of the date range.
* Will help with discoverability of the feature (today there is no hint about the existence of parameters).
* Should be also triggered by a keyboard shortcut.

**Comment by kocsmy** [comment]
Here's the proposed design for this:

- "+ Add Parameter" button added below the query editor.
- This opens the parameter dialog, see screenshot. We can change the form items based on the selected type, just like how it works now.
- The dialog closes and inserts the parameter to the query editor and the UI element for the parameter.

![query parameter](https://user-images.githubusercontent.com/2378022/42137210-a6635828-7d68-11e8-91d4-a8382f0e0c65.png)
![query parameter dialog](https://user-images.githubusercontent.com/2378022/42137211-a96ef96e-7d68-11e8-8596-24a2e68068e0.png)

**Comment by arikfr** [comment]
Some notes:

* Maybe use an icon for the button instead of the long text (something like `{{ }}` maybe?)? While it will require some learning from the user, it will create a more streamlined UI.
* If we already add buttons there, let's mvoe the format button there.
* The Keyword should be the first item in the form, the Title should come after and Type last. Title will be auto filled (with some manipulation to make it human readble) based on Keyword value.
* Enter key in this form should submit it.
* We need a keyboard shortcut to trigger this UI.

**Comment by kocsmy** [comment]
Maybe use an icon for the button instead of the long text (something like {{ }} maybe?)? While it will require some learning from the user, it will create a more streamlined UI.
- I was thinking about this and we could use the same for this: _"How to show if a widget is affected by a parameter? Maybe color code them, and show this color on the widget?"_ of https://github.com/getredash/redash/issues/2641

I'm a bit concerned that {{ }} might look like something is broken on the interface :)

The Keyword should be the first item in the form, the Title should come after and Type last. Title will be auto filled (with some manipulation to make it human readble) based on Keyword value.
- This is exactly what I did first, but then I was thinking what happens if you add a data-range. Then we'll need to add another keyword and it might be strange that something changes not below the type selector but on top of it.

**Comment by arikfr** [comment]
> I'm a bit concerned that {{ }} might look like something is broken on the interface :)

Good point. Let's see how it looks like. We can also use the [filter icon](https://fontawesome.com/icons/filter?style=solid), but this means we need to deprecate the other filters functionality :)

> This is exactly what I did first, but then I was thinking what happens if you add a data-range. Then we'll need to add another keyword and it might be strange that something changes not below the type selector but on top of it.

For a Date Range you still define a single keyword, it just that it has two sub-keywords. I.e., you define `dateRange`, and then use `dateRange.start`/`dateRange.end`.

**Comment by kocsmy** [comment]
Filter icon would be confusion I think. 

How about using this icon instead (it's custom made)? We could use this on the dashboard widgets affected by global parameters.

![query parameter](https://user-images.githubusercontent.com/2378022/42137691-86d45a9e-7d71-11e8-9420-b82501a1b0a3.png)

Regarding the order of items: okay, got it, then we can add a little microcopy guiding the user how to use the parameter 👌 

![query parameter dialog](https://user-images.githubusercontent.com/2378022/42137732-234459c4-7d72-11e8-8ff8-258b716cfb48.png)
![query parameter dialog date range](https://user-images.githubusercontent.com/2378022/42137733-26766b6e-7d72-11e8-8202-038893ab674a.png)

**Comment by kocsmy** [comment]
I'm wondering if there's a nicer way to inform the user. I might improve the design of this modal, it doesn't look great.

**Comment by arikfr** [comment]
> How about using this icon instead (it's custom made)?

Let's continue with `{{}}` :) 

> Regarding the order of items: okay, got it, then we can add a little microcopy guiding the user how to use the parameter 👌

👍

**Comment by kocsmy** [comment]
As discussed, we'll go with the {{ }}: 
![query parameter](https://user-images.githubusercontent.com/2378022/42170063-c38103a8-7e15-11e8-8011-c6a57ea5cc07.png)
