### ISSUE TITLE
Add schedule_until field to queries, to allow expiry

### ISSUE THREAD

**Issue by alison985** [getredash/redash#2662]
Copied https://github.com/mozilla/redash/issues/427 to port Add schedule_until field to queries, to allow expiry (https://github.com/mozilla/redash/issues/15, PR: https://github.com/mozilla/redash/pull/60) to upstream.

Opening issue to submit PR against.

**Comment by arikfr** [comment]
Unless there needs to be some prior discussion before opening the pull request, I think you can skip opening the issue before submitting the pull request. You can just reference the relevant issue in mozilla/redash for context.

Btw, for this specific one, I would wait for the updated schedule query interface to be merged.

Thanks :)

**Comment by arikfr** [comment]
This was already implemented.
