### ISSUE TITLE
docker-compose up error with "You are using pip version 8.1.1, however version 10.0.1 is available"

### ISSUE THREAD

**Issue by jesusslim** [getredash/redash#2673]
docker-compose up error with "You are using pip version 8.1.1, however version 10.0.1 is available"
how can i solve it on my Mac?

**Comment by srinivasreddy** [comment]
If you are on Python2 , then use  `pip install --upgrade pip==9.0.3`  ; On python 3  do  as it says `pip install --upgrade pip==10.0.1`
