### ISSUE TITLE
Google Analytics data source logo isn't shown

### ISSUE THREAD

**Issue by leshik** [getredash/redash#2683]
### Issue Summary

Google Analytics data source logo isn't shown.

### Steps to Reproduce

1. Open **New Data Source** page
2. Input "analyt" into text input area

Only Google Analytics data source name is shown, but not the logo.

![image](https://user-images.githubusercontent.com/443678/42741098-73ada36c-88d9-11e8-91ef-038887ce97b9.png)

### Technical details:

* Redash Version: 4.0.1+b4038
* Browser/OS: Google Chrome for Mac 67.0.3396.99 (Official Build) (64-bit)
* How did you install Redash: Docker

**Comment by arikfr** [comment]
It's probably due to an adblocker running in your browser (they block it based on the file name)...

**Comment by leshik** [comment]
@arikfr omg, you're right – thank you, I didn't realize that!
