### ISSUE TITLE
bad mongodb query support

### ISSUE THREAD

**Issue by jesusslim** [getredash/redash#2684]
version 4.1
it can only support simple query for mongo.
cant support mongodb query "new Date()".(i know there is a key named "human...",but it cant replace new Date,for exp new Date().getFullYear().and it didnt work in aggregate.$match)
cant support mongodb query with my own params.(use {{param_name}} didn't work)
and i think if it cant support these things,it should support user variable or user function to solve it.for example i can define a variable named "now" to get the current timestamp,and use it in my query like "{{now}}",and its type should be int,not string for mongo query.

**Comment by jesusslim** [comment]
finally i use url datasource to solve it,give the mongo data source up .

**Comment by sibelius** [comment]
how did you solved it?

**Comment by jesusslim** [comment]
> how did you solved it?

use url datasource,just like an API,to query mongoDB and return the result
