### ISSUE TITLE
elastic search datasource query error

### ISSUE THREAD

**Issue by jesusslim** [getredash/redash#2689]
redash version 4.1
any query will return error:

Error running query: Failed to execute query. Return Code: 400 Reason: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/app_api_log_2018-07-20/_search] contains unrecognized parameter: [source_content_type]"}],"type":"illegal_argument_exception","reason":"request [/app_api_log_2018-07-20/_search] contains unrecognized parameter: [source_content_type]"},"status":400}

but i never use "source_content_type" in my query.is redash pass this unrecognized param to es? will u guys fix this issue?

**Comment by kyoshidajp** [comment]
Hi @jesusslim. I think #2267 changes this behavior.
