### ISSUE TITLE
Hierarchical dashboard level filters? 

### ISSUE THREAD

**Issue by idoDavid** [getredash/redash#2690]
Hi,

I'm creating cool dashboards with redash, but the filters behaviour really prevennts them from being super.

First of all I've switched from query params to filters in order to not re-run the dashboard queries upon user selection of params. I found that using multiple queries in dashboards, each returning results in different time and with very lacking visual indication of that (small spinning timer at the corner of each widget) really ruins the user trust in the dashboards. Users don't now when a change they made to the input params was effected in all widgets, especially since some queries take long to finish while others finish very quickly, so you get some widgets updated and some not a go figure out which is which. The state of long partial dashboard load is very bad for user experience and trust and makes users walk away from dashboards.

So I've switched to filters, which, together with setting refresh rates on individual queries promises fast and snappy performance, much to the user delight. From my experience, switching to filters boosted the usability of my dashboards very significantly. 

But, there is a problem with the filters as well. each filter holds the distinct values of the entire returned result. So when selecting one filter, In most cases the data vanishes immediately cause the other filters were yet to change.

To give an example,  Imagine a data set containing 2 columns, customer name and account ID. account IDs are distinct. Now I query the data for all the customers and accounts and set two filters, one for each column.

The initial returned data is great, showing the first customer and the first account  to match it. But, if I now select a new customer, the account Id remains the one of the first customer, and since there is no such combo in the data, all table, charts, and graphs get emptied until I'll select a proper account for the new customer selected.

And.. It gets Even worse. Coming to choose an account, we get a drop down of all the ids in the dataset, regardless to whether they fit the already selected customer or not. So good luck guessing the proper Ids out of the who-knows-how-many out there. 

So two problems:
1. Upon selection of non-default filter value, all data is usually gone.
2. No easy way to bring the data back by selecting the second filter values that match the first filter.

Is this currently solvable? If not, I'd like to take a stab at fixing it.

**Comment by idoDavid** [comment]
Sorry, not the proper place for that. If you want to follow up - https://discuss.redash.io/t/hierarchical-dashboard-level-filters/2191

**Comment by arikfr** [comment]
Thank you for the elaborate description. Let's continue the conversation in the forum.
