### ISSUE TITLE
Counter visualization

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#27]
Optional additions:
1. Value change indication (e.g. up by 20%)
2. Distance from desired value (e.g. 50% under, 200% over)

**Comment by shishirsharma** [comment]
If we put a monthly target, There is no point of showing up or down. Monthly targets might be really big/can be hard to achieve. There should be a visualisation like this one here 

http://1.bp.blogspot.com/_XPquV_XKF1c/SSHwj6uuDzI/AAAAAAAAAbc/a5DFj7izu9Q/s400/g1.jpg 

![g1](https://cloud.githubusercontent.com/assets/476201/12559213/c8716d1c-c3b9-11e5-90ce-d7e042734880.jpg)

**Comment by arikfr** [comment]
@shishirsharma makes sense. It's better if you open a new issue for it (or even better: a pull request :wink:).
