### ISSUE TITLE
Update CHANGELOG for v5.0.0-beta

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2700]
The next release is going to be `v5`, and as preparation going to package `v5.0.0-beta`. Before doing so, need to update the CHANGELOG.

Below are all the merged pull requests since v4.0.1 (which should be pretty much all the significant changes). Now we need:

- [x] Sort them into categories: `Added`/`Changed`/`Fixed`/`Other`.
- [x] (NTH) update names to their GitHub nicknames (I pulled the names from the Git log).
- [x] Rephrase the change description to something friendly (when needed).

**Comment by arikfr** [comment]
@jezdez do you want to take a stab at this? :-)

**Comment by arikfr** [comment]
(need to rerun the script, as there were more merged pull requests)

**Comment by jezdez** [comment]
Next time for sure, I was out. Apologies!
