### ISSUE TITLE
Querying Existing Query Results Fail

### ISSUE THREAD

**Issue by jesusslim** [getredash/redash#2701]
version  Redash 4.0.1+b4038

i do as the doc : https://redash.io/help/user-guide/querying/query-results-data-source

i create the database "Query Results",and a new mysql query http://0.0.0.0:5000/queries/20/source

and to use it,my another query is :

SELECT s.sid 
FROM users s 
INNER JOIN query_20 d ON d.user_name = s.mobile

but i got error:

Error running query: Table 'mydb.query_20' doesn't exist

could u tell me why it didn't work?

**Comment by arikfr** [comment]
You need to run this query with the new Query Results data source you created and not the MySQL one. Also, you can't reference the `users` table in it directly -- you can only query other queries.

Also, as requested in the guidelines when opening an issue, please don't use GitHub issues for support questions like this. For this we have the [forum](https://discuss.redash.io).
