### ISSUE TITLE
Schema for impala is not work

### ISSUE THREAD

**Issue by BigFF** [getredash/redash#2704]
I am using Impala data source with Hiveserver2
I found the schema could not work but query could by excute and return results
the /api/data_sources/1/schema url returns an error json: {"error": {"message": "Error retrieving schema.", "code": 2}}

Technical details:
Redash Version: 4.0.1.b4038
Browser/OS: Centos7 With Python 2.7.12 also tried in Ubuntu 16.04 with Python 2.7.12
How did you install Redash: bootstrap.sh from github 
Impala Version: 2.1.5 and 2.12.0 are both wrong

**Comment by arikfr** [comment]
You should check the logs (probably in `/opt/redash/logs`) to see what the error might be.

**Comment by BigFF** [comment]
Thanks~ I try to find the log and solve this problem

**Comment by sunyaf** [comment]
I have the same problem. How do you solve it

**Comment by TaylorHere** [comment]
reach this problem in my use case
