### ISSUE TITLE
Fix alert message links

### ISSUE THREAD

**Issue by lockyStar** [getredash/redash#2705]
### Summary

I've set up couple of alerts, but links are just "http://queries/{id}" and "http://alerts/{id}". They have to be fixed, by including correct domain name and path.

Also it would be great, if there will be an option to add triggered value to the message sending via email.

### Technical details

Redash version: 5.0.0-beta

**Comment by arikfr** [comment]
Did you set the `REDASH_HOST` environment variable?

**Comment by lockyStar** [comment]
That worked, thank you! 

But message customisation via query result would be very useful!
