### ISSUE TITLE
Charts shouldn't have "X" (to delete them) while not in "Edit Source" mode

### ISSUE THREAD

**Issue by fbertsch** [getredash/redash#2706]
### Issue Summary

When viewing a query chart (or charts) in non-source mode (i.e. `/queries/10#11` instead of `/queries/10/source#11`), the "X" button to delete charts doesn't do anything.

### Steps to Reproduce

1. Go to a query with a chart in non-source mode
2. Press the "X" next to the chart name (see [0])

Nothing happens. This is probably a good thing in non-source mode, but probably the "X" just shouldn't be there at all when it's not clickable.

### Technical details:

* Redash Version: 4.0.1
* Browser/OS: FF 63, MacOS 10.13
* How did you install Redash: Fork

[0] 
![image](https://user-images.githubusercontent.com/20819040/43401502-f139a7f2-93d5-11e8-8916-03f39a418e54.png)

**Comment by kravets-levko** [comment]
Hi @fbertsch ! This is fixed in latest master ([line with fix](https://github.com/getredash/redash/blob/master/client/app/pages/queries/view.js#L334); this button now works) and will be available in next release. Currently you can update your fork and deploy Redash from `master` branch.

**Comment by fbertsch** [comment]
That is great news, thank you!
