### ISSUE TITLE
How to set the intervals for workers and number of workers in redash?

### ISSUE THREAD

**Issue by YuaShizuki** [getredash/redash#2725]
How can I reduce the load on my server by reducing the workers and their intervals. Or how can I set a interval for the worker to be larger than 10min. I am assuming this would reduce the load on my server.

**Comment by YuaShizuki** [comment]
^^bump

**Comment by arikfr** [comment]
You should review the Knowledge Base:
https://redash.io/help/open-source/admin-guide/maintenance
https://redash.io/help/user-guide/querying/scheduling-a-query

If you still have questions, use the [forum](https://discuss.redash.io).
