### ISSUE TITLE
Add open source alternative to HighCharts

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#273]
Possible candidates:
1. http://c3js.org/examples.html

**Comment by arikfr** [comment]
http://www.chartjs.org/

**Comment by arikfr** [comment]
Site comparing all the JS graph libraries: http://www.jsgraphs.com/

**Comment by shenyubao** [comment]
https://github.com/ecomfe/echarts

**Comment by alonho** [comment]
c3js looks great (it's interactive which most aren't).
dimple has a good variety of features but isn't interactive.
chartjs doesn't have a lot of features and is practically a one-person project.
echarts has the best variety of the bunch.

Adding another option: nvd3 http://nvd3.org/examples/index.html 
I personally used it and it works great but isn't very rich in features.

We also need to look how well these options are maintained whether they have angular directives or we need to implement them.

**Comment by alonho** [comment]
c3js has one maintainer that isn't very active.
echarts is well maintained but looks intimidating in terms of documentation. the angular binding isn't very popular (in terms of github stars)
nvd3 is maintained by several people and is active. the angular bindings area also popular and mature: http://krispo.github.io/angular-nvd3/#/

**Comment by alonho** [comment]
The final two contenders are nvd3 and plotly. nvd3 has cool animations but plotly seems to have a lot of features and would be a better investment for the future.

Plotly was just open sourced so I've created the angular-plotly library in its [own repo](https://github.com/alonho/angular-plotly).

I'm considering several options: 
1. Merging #610 while I'm refactoring this area.
2. Using the ui-select widget for better multi select.

**Comment by arikfr** [comment]
HighCharts are no more in v0.9.0 and replaced by Plotly.js.
