### ISSUE TITLE
Date time with seconds not working as global param

### ISSUE THREAD

**Issue by wieshka** [getredash/redash#2730]
### Issue Summary

Whilst in Query editor, custom parameter with type Date and Time (with seconds) works like expected, further this field is ignored when Visualization is added to any Dashboard as widget. 

### Steps to Reproduce

1. Create a query which expects data time with seconds input and chose it as Global param;
2. Run it within Query editor (execute) and you will get expected result;
3. Create a dashboard and add visualization of Query to Dashboard;

### Expected result:
- changing date param with selector would apply to particular visualization via either Dashboard Refresh or Widget refresh;

### Actual result:
- graph stays unchanged, uses param value from saved query;

### Additional debug info:
- if you alter date time Param in URL query string on open Dashboard, it will work just fine;
- if you combine this param with other params of different type (tried with drop-down), the rest of Global params except data time type will work.
- Unfortunately had n time to test with other date time options (without seconds, etc)

### Technical details:

* Redash 5.0.0-beta+b4476
* Chrome Version 67.0.3396.99 (Official Build) (64-bit):
* How did you install Redash: AWS AMI image + /bin/upgrade --channel beta

**Comment by arikfr** [comment]
@kravets-levko is this what you fixed in #2712 (trigger the digest cycle)?

**Comment by kravets-levko** [comment]
@arikfr Seems so

**Comment by arikfr** [comment]
@kravets-levko did you manage to reproduce using his steps?

**Comment by kravets-levko** [comment]
@arikfr There was another bug (actually, two bugs), please review PR referenced above. Thanks!

**Comment by arikfr** [comment]
Fixed in #2730. Thank you for the report @wieshka .
