### ISSUE TITLE
Change preferred sorting type

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#2731]
### Issue Summary

Now Redash has ascending sort by creation time in dashboards / queries lists. Maybe descending could be better?

### Technical details:

* Redash Version: #1cafcc1

**Comment by jezdez** [comment]
Woops, good catch. Also slightly related to #2757.

**Comment by jezdez** [comment]
This was fixed in #2759 and I opened #2771 to track adding the dashboard sorting separately.
