### ISSUE TITLE
Chart is not displayed when a column with a 'length' name exists

### ISSUE THREAD

**Issue by Yossi-a** [getredash/redash#2733]
### Issue Summary

When the query has a field called 'length', the chart visualisation shows empty chart.

### Steps to Reproduce

1. Create mongo query which has fields called 'length', 'a', 'b'
2. Create a chart with 'a' as X and 'b' as Y
3. The chart is empty
4. Remove the 'length' field from the query result and the chart appears

### Technical details:

* Redash Version: 4.0.1 and 5.0.0 beta
* Browser/OS: Chrome
* How did you install Redash: docker-compose

**Comment by arikfr** [comment]
Fixed in #2734.
