### ISSUE TITLE
Page navigation should not be included in the query results table

### ISSUE THREAD

**Issue by madalincm** [getredash/redash#2749]
### Issue Summary
The navigation menu is displayed inside the query result set and users need to use the scroll bars to be able to use it. 

### Steps to Reproduce
1. Execute a query which will produce more than 10 results.
2. Observe the result set and the navigation menu.

### Expected results:
The user does not need to use the scroll bars to see the navigation menu.

### Actual results:
The user needs to scroll down through the result set to see the navigation menu

### Technical details:
* Redash Version: 5.0.0-beta
* Browser/OS: FF61 - Win7(x64)

This was originally open here https://github.com/mozilla/redash/issues/322

Please view this screencast: 
![43460848-8b79d1d4-94da-11e8-8c34-282735020755](https://user-images.githubusercontent.com/15685441/44208178-5a646600-a168-11e8-829e-11b415690533.gif)

**Comment by arikfr** [comment]
@jezdez @alison985 wasn't this implemented in one of your pull requests?

**Comment by arikfr** [comment]
This is fixed (at least in the upcoming v9).
