### ISSUE TITLE
redash nginx configuration

### ISSUE THREAD

**Issue by panda403** [getredash/redash#2758]
redash use / in nginx to access by default,but i want to change the root access directory '/' to '/redash',so other can use ip:port/redash to access redash,what should i do? @arikfr

**Comment by arikfr** [comment]
You should start by reading the issue template and understand that for support questions you should use the [forum](http://discuss.redash.io). Then you can use the search function in the forum to find this thread about the issue: https://discuss.redash.io/t/hosting-redash-not-under-root/135/5.

I think that at least one of the participants managed to get this working, although as before, I don't recommend this.
