### ISSUE TITLE
Amazon Athena's view does not displayed in the table list

### ISSUE THREAD

**Issue by gh8a** [getredash/redash#2772]
### Issue Summary
The view created by Athena is not displayed in the table list.

The problem seems to be due to the fact that `information_schema.columns` does not contain information about the view.

### Steps to Reproduce
none

### Technical details:

* Redash Version: 4.0.1+b4038
* Browser/OS: Google Chrome/Mac
* How did you install Redash: ?

**Comment by markshilton** [comment]
Also seeing the same issue here.  

Redash Version: 4.0.1+b4038
Browser/OS: Google Chrome/Mac
How did you install Redash: AWS AMI eu-west-1

**Comment by gh8a** [comment]
When I checked with v8.0.0+b32245 (a16f551e), Athena's view is displayed in the table list. 
This issue will be closed.

Redash Version:  8.0.0+b32245 (a16f551e)
Browser/OS: Google Chrome/Mac
How did you install Redash: Docker ap-northeast-1
