### ISSUE TITLE
Table Query Result Adding Commas

### ISSUE THREAD

**Issue by chgxtony** [getredash/redash#2778]
![image](https://user-images.githubusercontent.com/8702825/44896055-7e5ba600-ad29-11e8-8618-86fce5d6c4f5.png)

table query result add the comma and treat some int type as double , add '.00'

how to configure in redash v4.0.1

* Redash Version: v4.0.1
* Browser/OS:  client: chrome/mac , server: ubuntu 
* How did you install Redash: bootsrap script shell

**Comment by kravets-levko** [comment]
@chgxtony Please don't ask such questions on GitHub - use [forum](https://discuss.redash.io/) instead. Thanks!

![image](https://user-images.githubusercontent.com/12139186/44903815-3aab7100-ad16-11e8-8b85-ec4f871a3426.png)

![image](https://user-images.githubusercontent.com/12139186/44903901-66c6f200-ad16-11e8-8184-ab66e41c1402.png)
