### ISSUE TITLE
Remove wsgiref  in requirements

### ISSUE THREAD

**Issue by BigFF** [getredash/redash#2782]
### Issue Summary

We may do not need wsgiref lib in requirements.txt
I am using Python3 to run redash,I found we can remove the lib in requirements so wo can install it in Python3 and I do not find any code to use this lib

### Steps to Reproduce

remove line wsgiref == 0.1.2

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:5.0 Beta
* Browser/OS:Centos7
* How did you install Redash:Git Clone

**Comment by arikfr** [comment]
It's not used by Flask or Werkzeug?

**Comment by BigFF** [comment]
yep
we can check it on http://py3readiness.org/
and from this notes
"
Since version 0.9, Werkzeug supports Python 3.3+ in addition to versions 2.6 and 2.7. Older Python 3 versions such as 3.2 or 3.1 are not supported.
"
from:
http://werkzeug.pocoo.org/docs/0.14/python3
