### ISSUE TITLE
Improve Alerts documentation

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2788]
We should add definitions for Value and Reference:

> Value: the current value in the selected column in the query you picked (note that the alert uses only the first row).
> Reference: the value to compare with (using the operation you picked in Op). 

Along with clarifying _Rearm_ behavior.

(Documentation page: https://github.com/getredash/website/blob/master/website/_kb/user-guide/alerts/setting-up-an-alert.md)

**Comment by tjengel** [comment]
I've created a pr for this https://github.com/getredash/website/pull/139
