### ISSUE TITLE
webpack server not starting

### ISSUE THREAD

**Issue by jrbenny35** [getredash/redash#2793]
### Issue Summary

Using command ```dev_server``` it appears the webpack server doesn't start. The login page shows no styling for example.

Logs:
```
--------------------------------------------------------------------------------
server_1    | ERROR in webpack [/app/redash/handlers/webpack.py:19]:
server_1    | Unable to load webpack manifest
server_1    | --------------------------------------------------------------------------------
server_1    | Traceback (most recent call last):
server_1    |   File "/app/redash/handlers/webpack.py", line 16, in get_asset
server_1    |     with open(WEBPACK_MANIFEST_PATH) as fp:
server_1    | IOError: [Errno 2] No such file or directory: '/app/redash/handlers/../../client/dist/asset-manifest.json'
server_1    | [2018-09-06 15:40:01,409][PID:17][ERROR][redash] Unable to load webpack manifest
server_1    | Traceback (most recent call last):
server_1    |   File "/app/redash/handlers/webpack.py", line 16, in get_asset
server_1    |     with open(WEBPACK_MANIFEST_PATH) as fp:
server_1    | IOError: [Errno 2] No such file or directory: '/app/redash/handlers/../../client/dist/asset-manifest.json'
```

### Technical details:

* Redash Version: current master
* Browser/OS: Firefox MacOS
* How did you install Redash: docker-compose

**Comment by jrbenny35** [comment]
Looking inside the docker container, there is no ```client/dist``` folder.

**Comment by jrbenny35** [comment]
Looks like I just need to run ```npm run build``` after the docker images start.

**Comment by palashkulsh** [comment]
do we have to install node separately before running npm run build or is it installed in server image? because i am not able to find it inside server image

**Comment by palashkulsh** [comment]
found it, in docker-compose.yml comment out skip skip_frontend_build and args line just above it. then run docker-compose build and then docker-compose up
