### ISSUE TITLE
dashboard date range filter not working 

### ISSUE THREAD

**Issue by peaksnail** [getredash/redash#2805]
### Issue Summary

dashboard date range filter not woking, I have try dropdown list and date range ,the dropdown list works ,but the date range failed, if the date range is not global ,it works.

### Steps to Reproduce

1.  set date range parameters global and the add to a dashboard
2. set "Use Dashboard Level Filters" true
3. change date range and not working,see the pictures

### Technical details:

* Redash Version: v5.0.0-beta
* Browser/OS: mac os , chrome
* How did you install Redash:
install in centos

**Comment by kravets-levko** [comment]
@arikfr Yes, seems so - reproduced on `v5.0.0-beta` and didn't reproduce on `master`

**Comment by rasapetter** [comment]
I just upgraded to `5.0.2` and it seems like this issue is gone(?)

**Comment by kravets-levko** [comment]
Thanks for a feedback, @rasapetter! Please check it carefully, and, if issue is gone, feel free to close this issue.

**Comment by rasapetter** [comment]
@peaksnail have you had time to check whether a more recent version is working better?

**Comment by peaksnail** [comment]
great! It works now(5.0.2)
