### ISSUE TITLE
AMI build process via Packer is apparently broken?

### ISSUE THREAD

**Issue by tobilg** [getredash/redash#2806]
### Issue Summary

We are trying to do a local build of the ReDash AMI images via Packer. As it turns out, the code below https://github.com/getredash/redash/tree/master/setup/ubuntu doesn't seem to be able to build the AMI image correctly.

### Steps to Reproduce

1. Check out the source code
2. Try to build the AMI image via Packer
3. Build fails

What is the actual process that the official AMI image is built with?

### Technical details:

* Redash Version: 2.0.1
* Browser/OS: Ubuntu base AMI

**Comment by arikfr** [comment]
Since then we replaced the setup script with a new one. Closing this as no longer relevant.

**Comment by tobilg** [comment]
Well, it’d be nice to give me a hint where the new process can be found @arikfr Thanks
