### ISSUE TITLE
Consistently use simplejson for speed/memory improvements

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#2807]
### Issue Summary

At the moment Redash uses the Python json module except for one area where it [recently started to use the also installed simplejson](https://github.com/getredash/redash/pull/2783) to be able to use the `ignore_nan` parameter. Simplejson is the original package that became the json stdlib module but which also has been further developed since then.

The standalone [simplejson](https://pypi.org/project/simplejson/) is faster and more effective in using memory on Python 2.7 according to a [set of benchmarks](https://blog.ionelmc.ro/2015/11/22/memory-use-and-speed-of-json-parsers/#lots-off-small-objects).

Once we switch to Python 3 we can revert to using the stdlib json module again as it seems to be very optimized there again. I'll make sure the patch uses a central `json_loads` and `json_dumps` function so we won't have to do another big patch to revert to json.

### Technical details:

* Redash Version: 5.0beta
* Browser/OS: Firefox
* How did you install Redash: Docker

**Comment by kravets-levko** [comment]
@jezdez Please note that we use `simplejson` not because it's faster or more effective; the main reason is `ignore_nan` option which is not available in stdlib json.

**Comment by jezdez** [comment]
@kravets-levko Yeah, I updated the description above, thanks for the notice. Moving to a consistent use of one library has an *additional* benefit of performance and memory improvements.

One minor detail of my plan to move to the json library again once we're on Python 3.x is indeed that it also misses the `ignore_nan` parameter there. The original commit seems to have added that feature to the C portion of simplejson, so it'll be hard to customize this in an own JSON encoder.
