### ISSUE TITLE
query against Clickhouse, format button autocapitalizes column names

### ISSUE THREAD

**Issue by The-Alchemist** [getredash/redash#2811]
### Steps to Reproduce

1. Create a Clickhouse data source
2. Create a query against that data source, like:
```
SELECT time
FROM my_data
LIMIT 10
```
3. Click the "Format" button
4. The query becomes:

```
SELECT TIME
FROM my_data
LIMIT 10
```
Notice that `time` got capitalized as `TIME`.  But Clickhouse is case-sensitive, so the following query will fail:

```
Error running query: Code: 47, e.displayText() = DB::Exception: Unknown identifier: TIME, e.what() = DB::Exception

```

### Technical details:

* Redash Version: Redash 4.0.1+b4038 
* Browser/OS: Chrome Version 69.0.3497.92 (Official Build) (64-bit)
* How did you install Redash: Docker image from Docker hub

If someone points me in the right direction, I can submit a PR!

**Comment by konnectr** [comment]
Not reproducible in last master
