### ISSUE TITLE
Unable to create an alert in 5.0.0-beta+b4476

### ISSUE THREAD

**Issue by dbravender** [getredash/redash#2814]
### Issue Summary

Unable to create an alert

### Steps to Reproduce

1. Go to `/alerts/new`
2. Select a query
3. Enter a name for the alert

**Expected**: I can click the save button
**Actual**: I cannot click the save button

I see this error in the JS console:

```
TypeError: "e.getQueryResultPromise is not a function"
```

### Technical details:

* Redash Version: 5.0.0-beta+b4476
* Browser/OS: Ubuntu, Firefox 62.0+build2-0ubuntu0.16.04.3
* How did you install Redash: Used provisioning script

**Comment by kravets-levko** [comment]
Hi @dbravender! This bug is already fixed in `master`. You can update your installation, or wait for v5 release. Thanks!
