### ISSUE TITLE
Show tag list on "my queries" page

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#2828]
The tag list isn't shown on the "my queries" page.

This has been previously filed downstream: https://github.com/mozilla/redash/issues/475

### Steps to Reproduce:

1. Open all queries page
2. Select My Queries from the right side menu
3. Observe tags section

### Expected results:
Tags are displayed. The user is able to filter own queries by tags

### Actual results:
The tags section is not displayed.

### Technical details:

* Redash Version: 5.0beta
* Browser/OS: Firefox 62, macOS 10.13
* How did you install Redash: Docker

**Comment by kravets-levko** [comment]
Seems it's fixed now (not sure in which Redash version). I'm closing this issue, feel free to reopen it if needed. Thanks!

![image](https://user-images.githubusercontent.com/12139186/72758207-d45d1200-3bda-11ea-9659-43d47dd391bf.png)
