### ISSUE TITLE
Long tags cause page layout issues

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#2829]
### Steps to Reproduce:
- Create a long tag and add it to a query
and
- Create a long tag and add it to a dashboard
- Open all dashboards page and observe the page layout
- Open all queries page and observe the page layout

This was originally reported downstream (https://github.com/mozilla/redash/issues/476) and is also related to https://github.com/getredash/redash/pull/2803

### Expected results:
There are no page layout issues

### Actual results:
The page is not correctly displayed

### Notes/Issues:
Verified in FF61(Win7).  Issue can be reproduced in STMO-stage
Please view this screencast:
![dashboardslongtags](https://user-images.githubusercontent.com/15685441/43467297-185c47f8-94ea-11e8-80b0-121b08940f0b.png)
![querieslongtags](https://user-images.githubusercontent.com/15685441/43467334-2c259f32-94ea-11e8-865f-9c6eb109e31e.png)

### Technical details:

* Redash Version: 5.0beta
* Browser/OS: Firefox 62, macOS 10.13
* How did you install Redash: Docker

**Comment by arikfr** [comment]
I think a solution for this issue and #2831 is to put a limit on the size of the tag HTML element?

**Comment by kocsmy** [comment]
PR open at #3006

**Comment by jezdez** [comment]
Thanks @kocsmy!
