### ISSUE TITLE
Show "results not available" on public dashboard when not available yet

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#2844]
### Issue Summary

As a short term fix for #1194 as stated by @arikfr in https://github.com/getredash/redash/pull/2823#pullrequestreview-155734950 we should show a message on public dashboard widgets that don't have any results on the server side yet.

The long term solution of getting fresh results on public dashboards requires solving #2825 first.

### Steps to Reproduce

1. Go to a public dashboard with a widget whose query results haven't been processed yet
2. See the dashboard crash as documented in #1194.

This ticket is about providing a short term solution so the dashboard doesn't return a 500 error. 

### Technical details:

* Redash Version: 5.0.0
* Browser/OS: Firefox 62/macOS 10.13
* How did you install Redash: Docker

**Comment by arikfr** [comment]
#3659 solves this.

**Comment by jezdez** [comment]
@arikfr OMG!!
