### ISSUE TITLE
Pivot table filters by field stopped working

### ISSUE THREAD

**Issue by lockyStar** [getredash/redash#2845]
### Pivot table filters by field stopped working

Apply button doesn't change table. 
![image](https://user-images.githubusercontent.com/15424203/45948024-15e9a700-bfff-11e8-9704-c918f76f5294.png)

### Technical details:

* Redash Version: 5.0.0-beta
* Browser/OS: Chrome/Mac OSX

**Comment by gabrieldutra** [comment]
Hi,

This seems to be working properly in [redash preview](https://redash-preview.netlify.com/queries/74/source#152) and in Redash v8 (can also be working other recent versions, but I didn't check them):


![image](https://user-images.githubusercontent.com/3356951/66317443-e5b23500-e8ef-11e9-82d1-66ecc5e43837.png)
