### ISSUE TITLE
Dashboard or query filter ux is really confusing

### ISSUE THREAD

**Issue by r-tock** [getredash/redash#2846]
The general tendency is to press enter or press a button to apply a filter, or the filter applies on deblur. None of those happen for text filters.

In a query you have to press execute button to apply the filter
In a dashboard you have to refresh the page to apply the filter.

Can someone fix this, this is driving me nuts

**Comment by r-tock** [comment]
I am using version 5.0.0

**Comment by arikfr** [comment]
You probably mean [Query Parameters](https://redash.io/help/user-guide/querying/query-parameters) (Filters is [a different concept in Redash](https://redash.io/help/user-guide/querying/query-filters)).

If you do, you should check out https://github.com/getredash/redash/issues/2316, which addresses exactly this.
