### ISSUE TITLE
Document how to persist redis container data between creations

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#2860]
### Issue Summary

Currently the Redis container doesn't persist the data when the container is removed and recreated. It would be useful to document how to do that in production (at least) to be able to restore Celery queues.

This came up in #2781 where it was considered to use Redis as a cache for the information which users were last active.

### Technical details:

* Redash Version: 5.0.0
* Browser/OS: Firefox 63.0/macOS 10.14
* How did you install Redash: Docker

**Comment by guidopetri** [comment]
I think we defer here to the [Redis docker image docs](https://hub.docker.com/_/redis/):

> start with persistent storage
> $ docker run --name some-redis -d redis redis-server --save 60 1 --loglevel warning
> There are several different persistence strategies to choose from. This one will save a snapshot of the DB every 60 seconds if at least 1 write operation was performed (it will also lead to more logs, so the loglevel option may be desirable). If persistence is enabled, data is stored in the VOLUME /data, which can be used with --volumes-from some-volume-container or -v /docker/host/dir:/data (see [docs.docker volumes](https://docs.docker.com/engine/tutorials/dockervolumes/)).
> 
> For more about Redis Persistence, see http://redis.io/topics/persistence.

Closing since this seems out of scope for redash, but feel free to reopen if you think otherwise.
