### ISSUE TITLE
LDAP settings for Microsoft Active Directory

### ISSUE THREAD

**Issue by cjpit** [getredash/redash#2863]
### Issue Summary

Followed docs for LDAP/AD Auth, but was unable to authenticate - This is a 2008 R2 Microsoft Active Directory Environment.

### Steps to Reproduce

1. Follow Docs

### Technical details:

To fix I did the following:
REDASH_LDAP_SEARCH_DN="dc=ORG,dc=local"
REDASH_LDAP_SEARCH_TEMPLATE="(&(objectclass=user)(sAMAccountName=%(username)s))"

**Comment by epineda** [comment]
here I saw an example:

https://discuss.redash.io/t/ldap-ad-authentication-example/1996

**Comment by susodapop** [comment]
@epineda The example you found was written by the OP 😃 

I'm tagging this to be added to our documentation.
