### ISSUE TITLE
How do I bind hostname or 0.0.0.0 to port 8080 ,not localhost?

### ISSUE THREAD

**Issue by wind1211** [getredash/redash#2864]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by arikfr** [comment]
This looks like a setup issue/question. If you still need help with this, I'll appreciate if you open a thread in our forum: https://discuss.redash.io/c/support/support-self-hosted.

Thanks.
