### ISSUE TITLE
Fix Yandex Metrica name

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2874]
Should be Yandex Metrica. Need to apply a fix, but keep the type name with a `k` to avoid breaking existing deployments.

**Comment by jezdez** [comment]
FWIW, it seems it has been rebranded for the global market, e.g. see https://metrika.yandex.ru/promo.

**Comment by jezdez** [comment]
The API URL is also specified as [`api-metrica.yandex.com`](https://tech.yandex.com/metrika/doc/api2/api_v1/examples-docpage/) (instead of our `api-metrika.yandex.ru`) now, I think we should update that as well.

**Comment by arikfr** [comment]
🤔this is so confusing.

**Comment by denisov-vlad** [comment]
I've just seen this issue. 

The main url of the service is https://metrika.yandex.ru/ I don't think that Metrica is right name. I'll ask them directly.

**Comment by jezdez** [comment]
@denisov-vlad It seems as if the service is being renamed to Metrcia, see the logo and headline text on the site you linked. I'm not sure *why* this is being done, but my guess is it's to position itself for the a global audience and not only to the Russian market. As far as I understand the API URLs all point to the same servers, so I hope this is a non-issue and keeps Redash in line with current development of Metri[c|k]a.

<img width="1462" alt="screen-shot-2018-10-04-20-46-05 48" src="https://user-images.githubusercontent.com/1610/46495762-92a62d80-c816-11e8-9704-afa30ff4254c.png">
