### ISSUE TITLE
Charts with long legend break when switching to horizontal legend

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2875]
See gif:

![](https://cl.ly/77b748b27f71/Screen%252520Recording%2525202018-09-28%252520at%25252006.03%252520PM.gif)

Here's an example query to use to reproduce this:

```sql
select created_at::Date, action, count(0)
from events
group by 1,2
```

**Comment by kravets-levko** [comment]
@arikfr Thanks, will check this ASAP
