### ISSUE TITLE
Shared dashboards don't auto refresh

### ISSUE THREAD

**Issue by pvnick** [getredash/redash#2882]
I installed version 5.0 using the docker image, and have created a test query that pulls data from a URL. The data initially display correctly; however, even though I have specified a scheduled refresh schedule of 1 minute, the published dashboard never refreshed unless I manually refresh the web browser. 

<img width="637" alt="auto refresh" src="https://user-images.githubusercontent.com/713737/46290423-d0c2f900-c559-11e8-821b-eb34fbfea0c3.PNG">

**Comment by arikfr** [comment]
Shared dashboards currently have no support for auto refresh. We will soon add the option to trigger reload of the data on schedule. I will keep this issue open until this is pushed.

**Comment by arikfr** [comment]
Just to clarify: it has nothing to do with type of data source. It just how shared dashboards work.

**Comment by pvnick** [comment]
Ok, thank you for the information.

**Comment by vaibhavmagon** [comment]
Is this resolved?

**Comment by NickStarlight** [comment]
This feature is not yet implemented, i suggest the re-opening of the issue.

**Comment by gabrieldutra** [comment]
Hi @NickStarlight, auto refresh is available for Public Dashboard for now following the `refresh` url parameter ([documented here](https://redash.io/help/user-guide/dashboards/dashboard-editing#Dashboard-Refresh)).

So, if you want to use it in a Public Dashboard just add a `refresh=[time-in-seconds]` to the url, e.g: 
https://redash-preview.netlify.com/public/dashboards/I3e8mcarbtK0QRNQ6nPLS87izI6maEAURQ8oPImj?org_slug=default&refresh=60 will make this dashboard refresh every minute :slightly_smiling_face:

**Comment by HoannvRelipa** [comment]
This feature has been implemented, but when used, sometimes it works and sometimes it doesn't.

**Comment by PhilippeAccorsi** [comment]
We have the same problem. Sometime refresh work but generally not.

Thanks @gabrieldutra for your tip.

**Comment by morepowerfull** [comment]
What worked for me was modifying client/app/pages/dashboards/hooks/useDashboard.js:130 and set code to:
`forceRefresh = true`
