### ISSUE TITLE
Query names are used as visualization title in sharing mode

### ISSUE THREAD

**Issue by ralphilius** [getredash/redash#2889]
### Issue Summary

Query names are used as visualization title in sharing mode

### Steps to Reproduce

1. Create a query
2. Create a visualization and name it
3. Add a widget with above visualization into a dashboard
4. Share the dashboard then browse it with public URL

Below is current behavior
https://imgur.com/a/sEEmyVS

### Technical details:

* Redash Version: Redash 5.0.0+b4754
* Browser/OS: Chrome 69
* How did you install Redash: Docker

**Comment by kravets-levko** [comment]
Hi @ralphilius! Isn't this the same issue that we fixed in getredash/redash#2870 ?

**Comment by ralphilius** [comment]
@kravets-levko I think so. Is it available for Docker yet?

**Comment by kravets-levko** [comment]
@arikfr ^

**Comment by arikfr** [comment]
No, it will be part of the next release.
