### ISSUE TITLE
Percentage as Number format not matched with NumeralJS for Table visualization

### ISSUE THREAD

**Issue by ralphilius** [getredash/redash#2901]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. Write a script that return a column with value: 0 < value < 1
2. Add a Table visualization
3. Choose display as "Number" for that column
4. Enter Number format as '0.0%'

It should render as in https://jsfiddle.net/o0td3cyw/

Right now, it just keep the value and add % sign. For example, 0.18 will render as 0.18% 
![image](https://user-images.githubusercontent.com/4253551/46515514-7514aa80-c88e-11e8-8773-4b7febd0dca9.png)

### Technical details:

* Redash Version: Redash 5.0.0+b4754
* Browser/OS: Chrome 69
* How did you install Redash: Docker

**Comment by kravets-levko** [comment]
Hi @ralphilius! Sorry for this inconvenience. `numeral` has an option that controls that behavior - by default `numeral` will multiply values by 100, but we decided to disable this: range `0..100` looks more natural for non-tech people than `0..1`. Our fault is that we didn't reflect this in the docs.

I opened a [PR](https://github.com/getredash/website/pull/126) to add that docs - please note that examples for percentages were fixed. A bit later I'll fix links to the docs in app.
