### ISSUE TITLE
Move parameters merging to the backend and make it safe

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2904]
Currently the way parameters work in Redash is that we use the query text as a [Mustache template](http://mustache.github.io/) and merge the parameter values with it before running the query.

This very simple implementation has one major issue: it's open to SQL injections. It's a non issue when a "regular" Redash user uses parameters, as they can run any query anyway. But it limits the use of parameters to users with full access to the data source.

To provide any user with the ability to use parameters, we need to change our implementation to make it safe and SQL injections proof. 

The idea is:
1. Change the API to handle all parameters merging in the backend (today we send the final query from frontend).
2. Make the API safe.

While every database driver we use (that supports DB-API) has its own way of taking query text with parameters, it's better that we find a single way that is DB agnostic. Also need to remember that some of our datasources take queries as JSON/YAML.

It's also preferable that we can support current parameters syntax (`{{ parameter }}`), but we don't have to support the full range of Mustache functions (although it can be nice).

---

Some "prior art" that might be useful:

1. https://github.com/hashedin/jinjasql
2. [sqlalchemy.sql.expression.text](https://docs.sqlalchemy.org/en/latest/core/sqlelement.html#sqlalchemy.sql.expression.text)
3. [psycopg2.sql](https://github.com/psycopg/psycopg2/blob/master/lib/sql.py) module
4. https://github.com/deadpixi/dpdb

**Comment by arikfr** [comment]
(I added another prior art reference I stumbled at today)

**Comment by Jakdaw** [comment]
Is the intention that this would be optional?

Given the current behaviour I'm sure there are plenty of people who are using parameters not only for SQL-parameters but also for selecting tables, group by columns, order by fields etc. It's not going to be possible to avoid the SQL injection possibilities in these situations but do we really want redash to prevent such use-cases altogether?

**Comment by arikfr** [comment]
@Jakdaw that's a good comment. There is no intention to prevent such scenarios. The idea is only to prevent SQL injections.

**Comment by rauchy** [comment]
Are you referring to injections via the WHERE clause only? Because I think all the other clauses are susceptible to SQL injection. (`select 1; drop table midgets`)

**Comment by rauchy** [comment]
Oh yeah, if we go down the JinjaSQL path, [we're on our own](https://github.com/hashedin/jinjasql#sql-safe-strings) for anything that can't be bound.

**Comment by susodapop** [comment]
I'd highly recommend using SQLAlchemy where possible. That team has expended a great deal of energy to unify the abstraction of binding parameters to datatypes through regardless of the underlying DBAPI. For a non-technical user of Redash, this won't matter. But anyone writing their own query_runner in Python will most likely have worked with SQLAlchemy in the past. That makes the massive level of documentation for SQLAlchemy a huge bonus.

**Comment by susodapop** [comment]
For reference: #2377 should be much easier to address once this issue is closed.

**Comment by shinsuke-nara** [comment]
Would anyone tell me the state of this issue?

I'm interested in preventing SQL injection.

Even if you adopt pre-templating or post-templating, I consider we need to update QueryRunner's `run_query` to accept parameters.
I'd love to fix `run_query` to accept parameters if anyone is not working about it yet.

Would you accept the fix if I make a PR?

**Comment by arikfr** [comment]
@shinsuke-nara we ended up implementing validation of parameters on the backend. Read only users can now use parameters except for the text parameter type, which isn't safe as we can't validate it at the moment.

Once we are done with enabling parameters in various scenarios, we will get back to allowing the use of text parameters. Either by passing them to the query runner or sanitizing them ourselves.

**Comment by leocavalcante** [comment]
It's really missing. There is a workaround where we can expose dashboards with params by our own risk?

**Comment by arikfr** [comment]
Closing this issue as it's already implemented.
