### ISSUE TITLE
replace MySQL-python with pymysql

### ISSUE THREAD

**Issue by BigFF** [getredash/redash#2918]
### Issue Summary

Can we replace MySQL-python with pymysql ?
MySQL-python do not support Python 3 and charset='utf8mb4'
we may use pymysql in the future

### Steps to Reproduce

remove MySQL-python==1.2.5 in requirements_all_ds.txt
add pymysql in it
change import MySQLdb in "redash/redash/query_runner/mysql.py"

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:latest version
* Browser/OS: Chrome
* How did you install Redash:git clone from https://github.com/getredash/redash

**Comment by arikfr** [comment]
#2739

**Comment by BigFF** [comment]
https://github.com/getredash/redash/pull/2739
were not successful still needs to change it

**Comment by Jakdaw** [comment]
If MySQLdb is going to be replaced then can it be checked that this doesn't break functionality for putting mulitple statements in a redash query or using MariaDB's new Compound Statements Outside of Store Programs feature? The patch that was put forward to pymysql breaks many queries that work great using MySQLdb.

**Comment by arikfr** [comment]
We ended up adopting `mysqlclient`. It supports Python 3 and I hope it also solves the other issue you had.
