### ISSUE TITLE
URL query runner: URL base path doesn't need to be a required field

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2919]

**Comment by jezdez** [comment]
Seems like a regression from #2318.

**Comment by jezdez** [comment]
Wait, hm, there is no other field to build the URL to request though, https://github.com/getredash/redash/blob/c2429e92d2a5dd58cbe378b9cc06f3be969f747e/redash/query_runner/__init__.py#L146-L176

The field is kind of badly named, it's not really the "URL base path" but the actual "URL" that the field contains.

**Comment by arikfr** [comment]
I had a feeling using a generic base class will come back to bite us here :)

You pass the URL you want to query as the query text. The idea of using a base path was to allow limiting the URLs the end user might use and/or save some typing if you happen to load many URLs from the same base path.
