### ISSUE TITLE
Better icon for "Source View"

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2926]
We currently use the same icon for source view and show embed code.

We need a better icon for source view.

**Comment by arikfr** [comment]
OK, sorry. They are not the same, just very similar :)

**Comment by kocsmy** [comment]
:) Ok, but it's maybe too similar if you didn't spot the difference. How about using this one for the embed instead: https://fontawesome.com/v4.7.0/icon/file-code-o

**Comment by arikfr** [comment]
No, the embed icon seems right. It's the source view that feels out of place. 

The current icon is an icon of HTML code (hence the angular brackets), and less fits for something which is mostly SQL. 

Some alternatives:

1. https://fontawesome.com/v4.7.0/icon/terminal
2. https://thenounproject.com/term/coding/1818816/

What do you think?

**Comment by deecay** [comment]
https://fontawesome.com/v4.7.0/icon/pencil-square-o ?

**Comment by kocsmy** [comment]
@arikfr I think @deecay suggestion with the pencil edit icon makes the most sense. I'm adding this to #2926
