### ISSUE TITLE
Uptycs Query_runner for Redash

### ISSUE THREAD

**Issue by vibhorkum** [getredash/redash#2932]
Hi Team, 

I want to add new query_runner for Uptycs in Redash. 
I did some testing with query_runner for Uptycs. However before I share the code, please let me know the process of posting the query_runner.

Thanks,
Vibhor

**Comment by arikfr** [comment]
The process is to create a pull request with the new query runner and whatever other changes are needed.

**Comment by arikfr** [comment]
Are you familiar with Pull Requests and GitHub?

**Comment by vibhorkum** [comment]
Yes. Will create a pull request and will include the changes for Uptycs. 
Thank you @arikfr !

**Comment by vibhorkum** [comment]
Hi @arikfr ,

Can you please help to create a new PR for Uptycs Query runner? I can share the query_runner with you
