### ISSUE TITLE
After upgrade to 5.0 (with docker-compose): failed to connect to server

### ISSUE THREAD

**Issue by SebC99** [getredash/redash#2954]
Everything was working fine and we upgraded form v3 to v4 to v5 with the docker-compose upgrade command, and the redash UI is loading fine, but cannot execute any query.

The UI displays an error: `Error running query: (psycopg2.OperationalError) could not connect to server: No such file or directory Is the server running locally and accepting connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?`

And the docker-compose logs shows the following:
```
redash-worker | [2018-10-15 10:40:30,331][PID:46][INFO][Worker-13] waiting tracker 14a3e1bd6ffb17fda50f3ef34071f77f finished
redash-worker | [2018-10-15 10:40:30,332][PID:46][INFO][Worker-13] waiting tracker e321600e578ecd0d5e4bbfd0cb7eb0a7 finished
redash-worker | [2018-10-15 10:40:30,333][PID:1][INFO][MainProcess] Task redash.tasks.cleanup_tasks[bd77acf9-104f-45f6-a037-b54e64f638fd] succeeded in 0.0124485739998s: None
redash-worker | [2018-10-15 10:40:30,377][PID:14][INFO][Beat] Scheduler: Sending due task refresh_queries (redash.tasks.refresh_queries)
redash-worker | [2018-10-15 10:40:30,380][PID:1][INFO][MainProcess] Received task: redash.tasks.refresh_queries[29fcf6b1-9873-425d-ac6e-0972299e6bd3]
redash-worker | [2018-10-15 10:40:30,381][PID:49][INFO][Worker-14] task_name=redash.tasks.refresh_queries task_id=29fcf6b1-9873-425d-ac6e-0972299e6bd3 Refreshing queries...
redash-worker | [2018-10-15 10:40:30,390][PID:1][ERROR][MainProcess] Task redash.tasks.refresh_queries[29fcf6b1-9873-425d-ac6e-0972299e6bd3] raised unexpected: OperationalError('(psycopg2.OperationalError) could not connect to server: No such file or directory\n\tIs the server running locally and accepting\n\tconnections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?\n',)
```
Any ideas?
Thank you so much

**Comment by arikfr** [comment]
Considering that the app works, I assume this errors comes from the query runner. Check the data source settings, to make sure they make sense and have a host setup.

**Comment by SebC99** [comment]
Data source is MongoDB and the "test connexion" results with a success

**Comment by arikfr** [comment]
You have a typo in your `REDASH_DATABASE_URL` value for the `worker` container: `postgresql:///...` (note 3 times `/` instead of 2). I guess this is why it tries to connect to a socket file.

**Comment by SebC99** [comment]
Sorry I'm always trying to change that between `postgresql://postgres@postgres/postgress` which leads to `(psycopg2.OperationalError) fe_sendauth: no password supplied` issues and `postgresql:///postgress` which leads to `could not connect to server`

When I remove the 3 `/` to put `//` instead it just fails to instantiate and even the UI crashes with an Interval Server Error

**Comment by arikfr** [comment]
At least in the comment you have another type: `.../postgress` instead of `../postgres` (double `s`). You should use the exact same value that you used for the `server` container.

**Comment by SebC99** [comment]
Just a typo here, it's correct in the docker-compose file.
I have `REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"` in the `server` container and `REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"` in the `worker` container, and the result of the `docker-compose up -d` command is: 
`OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied`

**Comment by SebC99** [comment]
(I'm guessing we have no password for the postgres user, and when I add one in the postgress sql it just ends up with a failed authentication error)
