### ISSUE TITLE
Query editor duplicates keystrokes

### ISSUE THREAD

**Issue by pthm** [getredash/redash#2972]
### Issue Summary

When typing in the query editor seemingly random keystrokes are duplicated, this makes it almost impossible to use.

![Imgur](https://i.imgur.com/154a9GE.gif)

### Technical details:

* Redash Version: 5.0.0+b4754
* Browser/OS: Chrome Version 69.0.3497.100 (Official Build) (64-bit) & Firefox 62.0.3 (64-bit). Windows 10 Pro
* How did you install Redash: Self hosted running on Kubernetes

**Comment by arikfr** [comment]
Can you reproduce this on v6?

**Comment by DawerRafi** [comment]
I see this issue again in v6.0.0 and also in latest master branch.

I notice this happens when Live Autocomplete is enabled (which is the default). When its turned off, the problem goes away.

**Comment by arikfr** [comment]
@DawerRafi can you reproduce it here: https://redash-preview.netlify.com/queries/new? Also, what browser are you using?

**Comment by DawerRafi** [comment]
I can't reproduce here, this instance does not have a Python Datasource. Even on my instance the issue is not reproduceable on BigQuery Datasource. It only occurs in Python Datasource.

I am using Google Chrome: Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by arikfr** [comment]
@DawerRafi does it reproduce with the "Gists" data source on the preview instance?

**Comment by DawerRafi** [comment]
No, its fine there too.

**Comment by arikfr** [comment]
The Python data source supposed to behave like Gists (it has no schema, which was triggering the issue here).

How did you setup Redash?

**Comment by DawerRafi** [comment]
I am running Redash in docker. Used the dockerfile inside the repository.
