### ISSUE TITLE
Cassandra/Elassandra support is broken and missing Client Encryption

### ISSUE THREAD

**Issue by dioptre** [getredash/redash#2976]
To get started I first had to fix the docker compose file (#1443).

Then I had to disable encryption on the cluster to get it to work which is pretty janky.

Then all queries I wrote did this:
![image](https://user-images.githubusercontent.com/760216/47079212-bb84d600-d1b9-11e8-96c9-7df4f4ef435d.png)

Code completion for Elastic was also missing (as advertised). Didn't check client encryption, but it seemed that was also not supported. Looks like re-dash is a no go for me for Elassandra right now due to its maturity. Looking forward to coming back in 12 months. Choosing Metabase or Superset for now.

Hope this helps others not waste a couple of hours.

**Comment by arikfr** [comment]
I'm doing a clean up of Elasticsearch related issues and got to this one.

It's probably no longer relevant, but anyway: based on the error message, it's likely that your Celery workers run an older version of your Docker container that didn't have the Cassandra query runner enabled.
