### ISSUE TITLE
setup.sh fails with error "PS1: unbound variable"

### ISSUE THREAD

**Issue by eric-brechemier** [getredash/redash#2979]
### Issue Summary

On a Digital Ocean VPS running Ubuntu 18.04, the latest version of the script setup.sh fails with the following error:

```
/root/.bashrc: line 6: PS1: unbound variable
```

### Steps to Reproduce

1. I created a new VPS running Ubuntu 18.04 x64 on Digital Ocean (with 2 GB RAM / 1 CPU)
2. I connected to the server as `root` using SSH
3. I used `git` (already installed) to clone [redash repository](https://github.com/getredash/redash), which contains [setup scripts](https://github.com/getredash/redash/tree/master/setup)
4. for some reason, the `setup.sh` script in redash repository is not executable... I made it executable (`chmod +x setup.sh`) then ran the script
5. the script installed various things, then failed with the error:

```
/root/.bashrc: line 6: PS1: unbound variable
```

I instrumented the script with `echo` to determine where it fails:

* in `setup_compose()`
* in `source ~/.profile`

The file `/root/.profile` reads:

```
# ~/.profile: executed by Bourne-compatible login shells.

if [ "$BASH" ]; then
  if [ -f ~/.bashrc ]; then
    . ~/.bashrc
  fi
fi

mesg n || true
export COMPOSE_PROJECT_NAME=redash
export COMPOSE_FILE=/opt/redash/docker-compose.yml
export COMPOSE_PROJECT_NAME=redash
export COMPOSE_FILE=/opt/redash/docker-compose.yml
export COMPOSE_PROJECT_NAME=redash
export COMPOSE_FILE=/opt/redash/docker-compose.yml
export COMPOSE_PROJECT_NAME=redash
export COMPOSE_FILE=/opt/redash/docker-compose.yml
```

It sources the file `/root/.bashrc`, which reads:

```
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

(...)
```

The error occurs on line 6 in `/root/.bashrc`

```
[ -z "$PS1" ] && return
```

It is caused by the flag `-u` of `set` at the beginning of `setup.sh`,

https://github.com/getredash/redash/blob/c71f722552144cf73c38438ad45982b509fa3d6b/setup/setup.sh#L3

which requires to `Treat unset variables as an error when substituting.`.

### Technical details:

* Redash Version: `master` (c71f722552144cf73)
* Browser/OS: Ubuntu 18.04 x64
* How did you install Redash: `setup/setup.sh`

**Comment by arikfr** [comment]
Thank you for the report! Fixed in #2996.
