### ISSUE TITLE
Improve Autocomplete toggle

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#2984]
Currently it's not very clear if the toggle is active or not. We should improve its visual representation.

Also:

- [ ] The tooltip should represent the current state (say if it's active or not)
- [ ] Store the last state of the toggle
- [ ] If Live autocomplete is disabled because of number of tokens, the toggle should be disabled

**Comment by kocsmy** [comment]
We need to implement that changes its class based on state so I can change the design accordingly.

**Comment by arikfr** [comment]
I think the reason it doesn't change in your case is because you're using a data source that doesn't support autocomplete in the first place. Somewhat related to my third point there :)

Try a different data source that actually has a schema in your setup.

But we can discuss possible solutions even without making it work in your setup. Here's screenshots of current implementation:

When enabled:
![Enabled](https://user-images.githubusercontent.com/71468/47266326-8079fe00-d53d-11e8-94e9-4aea7b1be2fb.png)

When disabled:
![Disabled](https://user-images.githubusercontent.com/71468/47266329-8ec81a00-d53d-11e8-8efa-4e65db4ab959.png)

**Comment by kocsmy** [comment]
Oh true, indeed my data source doesn't support schema. In the meanwhile, I though it'll still give me autocomplete for SQL commands :)

**Comment by jezdez** [comment]
Personally I'd prefer the [Ant switch](https://ant.design/components/switch/) since the checkbox looked always kind of out of place in our fork (where we implemented this feature as a checkbox).

**Comment by arikfr** [comment]
My concern with a switch or checkbox (I too prefer switch btw), is that it takes a lot of space.

**Comment by jezdez** [comment]
The small switch is 28 px wide, but the "Autocomplete" word is annoyingly long, you're right. Could we use "Complete" or "Suggest"?

Alternatively, a hamburger menu with more options for the query?

**Comment by gabrieldutra** [comment]
The settings screen seems something that will eventually be necessary. Other options could be added at some point, e.g.: Format Query on save.

In case this is the chosen option, I would suggest to have an indicator that Autocomplete is enabled and working for that specific query (unsupported data sources excluded), something like the gif below:

![autocomplete-enabled](https://user-images.githubusercontent.com/3356951/47368696-77fa0280-d6b8-11e8-9c71-fcf5f58cec76.gif)

**Comment by arikfr** [comment]
Gave it some more thought -- how about we move it to some global user setting screen and persist this setting for the user? This way the user will know its state, because they set it.

As for data sources which don't support it -- we should show a clear message in the schema area that schema is not supported for this data source (which will imply no autocomplete).

**Comment by kocsmy** [comment]
Interesting thought, Arik. I was thinking about the same and moving it to a global user setting under Settings/Account maybe?

**Comment by arikfr** [comment]
![](https://cl.ly/2908e123556c/Screen%252520Recording%2525202018-11-14%252520at%25252004.11%252520PM.gif)

What do you think?

**Comment by kocsmy** [comment]
It looks foreign to me but most importantly, I don't think this is something that'll be changed very often. Therefore it doesn't make sense to put there in such a prominent way.

**Comment by kocsmy** [comment]
#3079 Will introduce a basic auto-complete (I assume SQL commands will autocomplete always) and this will only toggle the db schema auto-complete, if I got this right. 

If this is correct, we could move this on the left side, next to the schema editor. (Maybe it would look less foreign there)
