### ISSUE TITLE
special words '%' can not in query when using query result datasource

### ISSUE THREAD

**Issue by BigFF** [getredash/redash#2997]
### Issue Summary

1. create a query using any data source like
'''
select 1/3 as 'test%'
'''
then save it as query/1

create a query using query result data source
'''
select *
from query_1
'''
then return "Error running query: near "%": syntax error"

### Steps to Reproduce

1. avoid % this word or try to find the type of query,it should be a string?

### Technical details:

* Redash Version:5.0.2+b5486
* Browser/OS:Centos7 X64
* How did you install Redash:Docker

**Comment by kravets-levko** [comment]
Hi @BigFF! This issue is already fixed (PR: getredash/redash#2969). It will be available in the next release.
