### ISSUE TITLE
Dashboard filters

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3]
User should be able to add a filter to the dashboard that will be applied to all the queries of the widgets displayed.

Such filters can be:
-  date selection
-  values selection

TBD: explain about the two possible implementation strategies.

**Comment by indupulikkot** [comment]
HI arik,
As you said these filters are not working as expected.
'the values for the filter are the union of all relevant filter values in the dashboard.'

I our case, the global filter is taking first chart's filter value even if there are more values in the filter for second chart. So basically it is not doing union.

Please suggest

**Comment by RichardLitt** [comment]
Thanks for logging that, @indupulikkot. Can you provide a minimal example that we can look at to fix this?

**Comment by indupulikkot** [comment]
Iam attaching a screenshot with the issue description. Please review and suggest a fix for this. Our project is already live and this persists as an issue for us.
[redash global filter issue.docx](https://github.com/getredash/redash/files/1645442/redash.global.filter.issue.docx)

**Comment by RichardLitt** [comment]
@indupulikkot Thanks for attaching a screenshot, and for letting us know that this is potentially urgent for you. 

Redash is mostly volunteer run, and we not provide support. We'll fix this issue when we can, but other issues have a higher priority. The fastest way for this to be fixed would most likely be for you to suggest a pull request, which would really be great. Let us know if that's something you need help with, and we'd be able to review a PR and help you land it.

**Comment by arikfr** [comment]
@RichardLitt I updated your comment to better reflect the actual situation (saying Redash is mostly volunteer run is not accurate).

@indupulikkot FYI.

**Comment by arikfr** [comment]
I'm closing this, as most of what described here can be achieved with parameters.

If there are specific issues with filters or parameters on dashboards, we should open more granular issues.

**Comment by RichardLitt** [comment]
Thanks @arikfr!

**Comment by indupulikkot** [comment]
May I know why this issue is closed? C ould you please help us to fix this as we do not require parameters.
