### ISSUE TITLE
v6 Release Plan

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3015]
Time to start aiming at releasing v6! I created the [v6 milestone](https://github.com/getredash/redash/milestone/14) to track any remaining work and this issue for tasks related to the release.

I hope that we can have a beta version by next week and a final release 2-3 weeks after.

- [x] Fix all issues and merge pull requests in the milestone
- [x] Update CHANGELOG ([diff](https://github.com/getredash/redash/compare/v5.0.0...master), @jezdez): #3112  
- [x] Sanity tests for the current master

When all issues are done:

- [x] Create a release branch
- [x] Create GitHub release and update `version.redash.io`
- [ ] Announce beta version
  - [x] Forum
  - [ ] Twitter
  - [ ] Facebook
- [x] Need to mention in upgrade notes:
   - [x] The need to upgrade first to v5.0.2, for smooth Celery migration
   - [x] The need to clear out the Celery queue (because by default v4 uses JSON instead of Pickle)

After the beta is stable:

- [ ] TBD.

**Comment by jezdez** [comment]
@arikfr I'll do the changelog update!

**Comment by arikfr** [comment]
@jezdez 👍 thanks.

**Comment by jezdez** [comment]
@arikfr See #3112. I haven't added a blurb about the high level changes, or a summary. But generally speaking there are lots of UI/UX related changes and plenty of fixes and new additions of data sources. It's up-to-date up to babbeb79f0c9d7f8fe5a9f4e6b51c740b23e1e38.

**Comment by arikfr** [comment]
Thanks, @jezdez. I will add the summary before wrapping it up.

**Comment by jezdez** [comment]
I've asked @washort and @emtwo to test-drive master and see if anything obvious sticks out.

**Comment by emtwo** [comment]
I've tried it out. Looks solid! Nothing obvious seems to stand out. Looking forward to the the release!

**Comment by washort** [comment]
When editing a dashboard, changing the dashboard title results in the visualizations being replaced by the loading markers,

**Comment by washort** [comment]
All new tags have "(create new tag)" appended to them,

**Comment by arikfr** [comment]
The tags issue is something we’re aware of and @kravets-levko is working on a fix.

But the dashboard edit issue is nice find. 👍🏻

**Comment by jezdez** [comment]
@arikfr Huzzah for the beta!

**Comment by arikfr** [comment]
From what I seen so far the only open issue we should address before releasing the final version is #3181.

**Comment by arikfr** [comment]
v6 was released. I will follow up with announcements in the different channels later on.

**Comment by jezdez** [comment]
@arikfr Yay!!!! 😍
