### ISSUE TITLE
UI Feature flag for "show permissions control"

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3016]
It's time we graduate this feature, as a first step we should show an option to easily enable it from the UI.

Need to:

- [x] Make sure it still works as intended
- [ ] Queries log changes

**Comment by jezdez** [comment]
@arikfr Can you elaborate what the second TODO item is about?

**Comment by arikfr** [comment]
When we moved to SQLAlchemy, we broke the change tracking functionality (log all changes to query/dashboard models to `changes` table). This todo is about introducing this again.

But I don't think I'll wait for this for the beta release.

**Comment by arikfr** [comment]
#3136
