### ISSUE TITLE
Results size picker in list pages is empty

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3018]
![image](https://user-images.githubusercontent.com/71468/47619929-a3338600-daec-11e8-9dcb-591dc71c04ce.png)

**Comment by arikfr** [comment]
Apparently it doesn't render tags either. 🤔

**Comment by jezdez** [comment]
Huh?

**Comment by jezdez** [comment]
Hm, I can't reproduce this with current master, both via running a static build with `npm run build` as well as with the watch build (via `npm run start`).

<img width="1135" alt="screen-shot-2018-11-01-11-42-03 66" src="https://user-images.githubusercontent.com/1610/47847517-c5b6ef00-ddcb-11e8-84b7-64d60a7f4681.png">

<img width="1135" alt="screen-shot-2018-11-01-11-46-49 94" src="https://user-images.githubusercontent.com/1610/47847539-d5cece80-ddcb-11e8-88b5-4348214d52f1.png">

**Comment by jezdez** [comment]
FWIW, the option to specify the list of option for the dropdown was recently added in https://github.com/getredash/redash/pull/2993.

**Comment by arikfr** [comment]
OK, I see why it's working: the frontend version is newer than the backend version. I did experience the same issue locally, so I will double check again with an updated backend and update the issue per the findings.

**Comment by arikfr** [comment]
🤦‍♂️ my bad. Although I did experience this locally as well, where there shouldn't be an issue of backend/frontend version, but it's probably not a bug either. Sorry for the false alarm.

**Comment by jezdez** [comment]
No worries @arikfr!
