### ISSUE TITLE
Additional query's actions isn't visible

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#3025]
### Issue Summary

<img width="323" alt="2018-10-29 19 24 13" src="https://user-images.githubusercontent.com/7091907/47664648-8e202b00-dbb0-11e8-841f-681bc7da56a3.png">

### Steps to Reproduce

1. Open query
2. Try to download results

### Technical details:

* Redash Version: master
* Browser/OS: chrome / mac os x
* How did you install Redash: script

**Comment by arikfr** [comment]
@denisov-vlad thanks!
@kravets-levko z-index issue?

**Comment by kravets-levko** [comment]
@arikfr It's the issue that @kocsmy fixed recently (PR getredash/redash#2980)

**Comment by arikfr** [comment]
#2980 is merged now. @denisov-vlad can you confirm this is fixed?

**Comment by denisov-vlad** [comment]
It's ok now.
