### ISSUE TITLE
"mac docker install redash" sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postres" to address: Name or service not known

### ISSUE THREAD

**Issue by liugaohua** [getredash/redash#3030]
### Issue Summary

mac Mojave 10.14 (18A391)

### Steps to Reproduce

1. git clone https://github.com/getredash/redash.git
2. (env2.7.1) ➜  redash git:(master) ✗ docker-compose -f docker-compose.production.yml run --rm server create_db

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postres" to address: Name or service not known
 (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by kyoshidajp** [comment]
Please check the error message again. Probably "postres" is typo.

Otherwise, how about running `docker ps -a | grep postgres` to check postgres container status?

**Comment by arikfr** [comment]
Closing. You're welcome to reopen with additional details.
