### ISSUE TITLE
redash chokes on `select 'NaN'::double precision`

### ISSUE THREAD

**Issue by tsl-karlp** [getredash/redash#3034]
### Steps to Reproduce

Try running this query against a Postgres datasource:

```
select 'NaN'::double precision
```

It'll take about 15 seconds or so, and eventually you'll get:

```
Error running query: failed communicating with server. Please check your Internet connection and try again.
```

The javascript console in Chrome says:
```
SyntaxError: Unexpected token N in JSON at position 226
    at JSON.parse (<anonymous>)
    at Y (angular.js:1345)
    at Mt (angular.js:10878)
    at angular.js:10969
    at i (angular.js:325)
    at Tt (angular.js:10968)
    at l (angular.js:11828)
    at s (angular.js:16696)
    at angular.js:16712
    at f.$eval (angular.js:17994)
```

### Technical details:

* Redash Version: 5.0.1
* Browser/OS: Chrome
* How did you install Redash: Docker image

### Workaround

```
select 'NaN'::double precision::text
```

**Comment by tsl-karlp** [comment]
If someone points me in the right direction, I can send a PR. :)

**Comment by kravets-levko** [comment]
Hi @tsl-karlp! Thank you for the bug report. It's already fixed in `master` branch and will be available in the next release.
