### ISSUE TITLE
aggregates query can't correctly executed using elasticsearch datasource

### ISSUE THREAD

**Issue by oliverzzj** [getredash/redash#3043]
### Issue Summary

I post a simple aggregates query getting max value of column "orderNumber" in redash using elasticsearch datasource, but got no result.
Then I excecute the same query in elasticsearch, a proper aggregate value of 51 returned

### Technical details:

* Redash Version: latest release, installed last week
* Browser/OS: installed on centos, browsed in chrome
* How did you install Redash: docker-compse

**Comment by arikfr** [comment]
Duplicate of #2789.
