### ISSUE TITLE
Pull #2038 has an annoying side effect

### ISSUE THREAD

**Issue by zachliu** [getredash/redash#3045]
### Issue Summary

Pull request #2038 enables data sources to see the Redshift Spectrum external tables. However, now the data sources can also see the tables they are not allowed to see per their user/group privileges (they can see the tables but still got `permission denied` error when querying them).

### Steps to Reproduce

1. Create an a new schema named `schema_test` in your Redshift cluster
2. Grant usage on this schema to user A in Redshift
3. Create a new data source in Redash using user B from Redshift (make sure user B has no privileges on `schema_test`)
4. This data source can see the newly created schema `schema_test` which should only be visible to user A

### Technical details:

* Redash Version: 5.0.2
* Browser/OS: Chrome
* How did you install Redash: local test with docker-compose

**Comment by arikfr** [comment]
Fixed in #2866.
