### ISSUE TITLE
Use Page Object model for Cypress tests

### ISSUE THREAD

**Issue by jrbenny35** [getredash/redash#3055]
## Issue Summary

New cypress tests use locators within the tests to find elements. We should switch to using a Page Object Model to assist with upcoming UI changes, i.e.: react

### Technical details:

Some good information on the concept is found [here](https://medium.com/tech-tajawal/page-object-model-pom-design-pattern-f9588630800b).

**Comment by jrbenny35** [comment]
Here is a test suite I wrote for an example: https://github.com/mozilla/send/tree/vnext/test/integration

**Comment by gabrieldutra** [comment]
Hi @jrbenny35,
This does make tests look really better.  Nice example with your test suite. I also found [this example](https://medium.com/reactbrasil/deep-diving-pageobject-pattern-and-using-it-with-cypress-e60b9d7d0d91) with Cypress.

**Comment by arikfr** [comment]
This was discussed in #3064 and we decided for now to wait until we have more tests before we implement some abstraction.
