### ISSUE TITLE
Redash SAML metadata information 

### ISSUE THREAD

**Issue by kantsuw** [getredash/redash#3070]
Currently I running redash on docker.

I would like to connect redash to SAML 

Could you please help me, where can I find SAML metadata information

**Comment by arikfr** [comment]
For support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
