### ISSUE TITLE
Missing space between the bullet separators in the footer in 5.0.2

### ISSUE THREAD

**Issue by burnash** [getredash/redash#3075]
### Issue Summary

![screenshot 2018-11-13 at 11 19 26](https://user-images.githubusercontent.com/264674/48412695-b62d9380-e745-11e8-807e-7a578f05b421.png)

After upgrade to 5.0.3 from 4.x I noticed that space between the bullet separators in the footer is missing. Probably due to React migration and https://github.com/facebook/react/issues/1643
This a minor UI issue. Let me know if this is intended or there's a plan to redo the footer. Otherwise I'd be happy to submit a fix.

### Steps to Reproduce

1. Login to Redash.
2. See the footer.

### Technical details:

* Redash Version: 5.0.2+b5485
* Browser/OS: Chrome 70.0.3538.77 / macOS 10.14.1
* How did you install Redash: Manual upgrade from 4.x

**Comment by arikfr** [comment]
Thanks!

@kocsmy this wasn't intentional, right?
