### ISSUE TITLE
DataSource is not displayed properly in schema browser when changing

### ISSUE THREAD

**Issue by kyoshidajp** [getredash/redash#3090]
### Issue Summary

DataSource is not displayed properly in the schema browser when changing it in the small data source selector.

### Steps to Reproduce

1. Add some data source
1. Open query editor
1. Select a data source in the small data source selector
1. Spread window size
   - The selected data source is not displayed

### Screenshot

![ds](https://user-images.githubusercontent.com/3317191/48668142-cff61e80-eb29-11e8-91dc-8c0e561750c9.gif)

First, I selected "metadata" as data source. But "python" is selected after spreading browser width.

### Technical details:

* Redash Version: master branch (commit: 0ce7772aa356daebc9fc80f72e95dbb53f03fa9c)
* Browser/OS: Google Chrome Version 70.0.3538.102 (Official Build) (64-bit) on macOS 10.13.5
* How did you install Redash: docker-compose

**Comment by arikfr** [comment]
Good catch!

**Comment by kravets-levko** [comment]
Hi @kyoshidajp! Can you try to reproduce this on `master`? If I understand the issue correctly - it should be fixed now. Thank you!

**Comment by kyoshidajp** [comment]
@kravets-levko Hi, I can't reproduce this. Thank you for telling me, and fixing it.
