### ISSUE TITLE
Incorrect IP address recorded for event when behind proxy

### ISSUE THREAD

**Issue by jbeemster** [getredash/redash#3095]
### Issue Summary

When enabling the WebHooks option the IP Address reported in additional properties is that of the Load Balancer and not of the user.

### Steps to Reproduce

1. Launch Redash v5.0.2 behind an Amazon Load Balancer / Proxy
2. Enable WebHooks pointing to any valid collection point
3. Click around
4. Observe that the IP Address is an internal address rather than the user address

The usage of `request.remote_addr` to populate the IP Address field in [base.py](https://github.com/getredash/redash/blob/af3a1e00c6ccf583da73b37d182a9405ecb5f0ab/redash/handlers/base.py#L65) and [query_results.py](https://github.com/getredash/redash/blob/5e1512e777ec2fe056f227920b0748808f6a632b/redash/handlers/query_results.py#L218) does not currently capture the `X-Forwarded-For` header.  By checking for this header first and setting the IP Address accordingly in the records would allow the correct recording of the source user IP Address.

This StackOverflow post appears to detail several ways to get this detail: https://stackoverflow.com/questions/12770950/flask-request-remote-addr-is-wrong-on-webfaction-and-not-showing-real-user-ip

From a security audit perspective having the correct user address recorded is incredibly useful.

### Technical details:

* Redash Version: 5.0.2
* Browser/OS: Chrome
* How did you install Redash: Official Docker Image

**Comment by arikfr** [comment]
For Redash to use the correct IP address, you need to set the value of `REDASH_PROXIES_COUNT` to the number of proxies in front of it. In your case it's probably 2 (ALB + Nginx).

**Comment by jbeemster** [comment]
Ahhhh amazing!  Will try that now thanks @arikfr!

**Comment by jbeemster** [comment]
@arikfr confirmed that fixes it - sorry for the hassle!
