### ISSUE TITLE
QueryEditor: cursor jumps around

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3107]
I noticed a few weird behavior in the QueryEditor:

1. When you autocomplete a word, the cursor jumps to the beginning of the word:

![](https://cl.ly/f1178303476d/Screen%252520Recording%2525202018-11-21%252520at%25252008.26%252520AM.gif)

2. Sometimes the cursor just jumps around, specially on first load of the editor. In the gif below you will see that I refresh the page and start typing "select" multiple times. In the last time, the cursor jumps around and it results in "slecte" (the second "e" moved to the end).

![](https://cl.ly/1acf3a48bd39/Screen%252520Recording%2525202018-11-21%252520at%25252008.27%252520AM.gif)

**Comment by arikfr** [comment]
Unsurprisingly this seems to be caused by the change to wait for Angular's digest loop to update the value (#3099).

We can either somehow isolate this component from Angular (store the current query text value in the component's state?) or migrate more parts to React so we don't have to interact with Angular here. :)

**Comment by washort** [comment]
Whoops, didn't try typing fast. I think keeping state in the editor component for now is fine.

**Comment by washort** [comment]
This in particular is caused by using `$timeout` to invoke the angular digest loop, I think.

**Comment by DawerRafi** [comment]
I see this issue again in v6.0.0 and also in latest master branch.

I notice this happens when Live Autocomplete is enabled (which is the default). When its turned off, the problem goes away.
