### ISSUE TITLE
Tags count for dashboards is wrong

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3108]
![image](https://user-images.githubusercontent.com/71468/48824355-b395f400-ed6c-11e8-8fcb-7a04d6f2c2a4.png)

**Comment by jezdez** [comment]
Huh!

**Comment by jezdez** [comment]
@arikfr I'll take a look.

**Comment by jezdez** [comment]
Hmm, I can't reproduce this @arikfr locally. But I added #3120 since that was the only difference to the query tags code. Do you mind checking if this fixes the issue for your environment?

**Comment by arikfr** [comment]
I see it happens in the preview instance too. Do you have locally any dashboard with more than one widget?

**Comment by jezdez** [comment]
Ah, my test dashboards only have one each! Thanks, will check..

**Comment by jezdez** [comment]
I tried a bunch of variations of this, and I can't get the count to apply distinct correctly. @washort do you have any ideas how to express this with SQLA?

**Comment by jezdez** [comment]
I'm wondering if this is possible by splitting the query in two separate ones, using a subquery for the tag counts, then one to get the list of dashboards using that subquery.

It'd also be splendid if we would be able to use `Dashboard.all` for the list of dashboards as the base query as well, to not have separate code paths that build the query :-/

**Comment by arikfr** [comment]
> It'd also be splendid if we would be able to use Dashboard.all for the list of dashboards as the base query as well, to not have separate code paths that build the query :-/

I agree. It will also be useful later on to show tags that are relevant to the currently showing dashboards (search results, based on some tag filtering, etc).

> I'm wondering if this is possible by splitting the query in two separate ones, using a subquery for the tag counts, then one to get the list of dashboards using that subquery.

Probably the other way around, right? First get the list of dashboards, then extract tags + counts from it.

**Comment by jezdez** [comment]
> > It'd also be splendid if we would be able to use Dashboard.all for the list of dashboards as the base query as well, to not have separate code paths that build the query :-/
> 
> I agree. It will also be useful later on to show tags that are relevant to the currently showing dashboards (search results, based on some tag filtering, etc).
> 
> > I'm wondering if this is possible by splitting the query in two separate ones, using a subquery for the tag counts, then one to get the list of dashboards using that subquery.
> 
> Probably the other way around, right? First get the list of dashboards, then extract tags + counts from it.

Yep, see the PR, I think that'll do the trick.
