### ISSUE TITLE
Add new visualization type

### ISSUE THREAD

**Issue by NameArtem** [getredash/redash#3129]
How create and add a personal visualization type?

I created a new chart plot as it is necessary for me and added to app/visualization/myfolder. Now I need add it as new type of visualization.

Did anybody do the same? How did you manage that?

**Comment by arikfr** [comment]
You need to rebuild the frontend code after making changes (using either `npm run build`, `npm run watch` or `npm start` -- depending on the kind of setup you're using).

If you need further help with this, please add more context and post your question in the forum:

https://discuss.redash.io/c/development
