### ISSUE TITLE
RuntimeError: Working outside of application context.

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3181]
After deploying v6-beta to demo.redash.io we started seeing this error, which we haven't before:
https://sentry.io/share/issue/08f84c11d6d04474b642b2d1435f9fb8/

By guessing what might be the cause of the issue I commented out the following code:

https://github.com/getredash/redash/blob/cfe12c5a5d37b8ec01c8a26fd9c8c8ad97e12d07/redash/worker.py#L85-L90

Once I have the issue stopped happening. The reason I suspected this code was because we call `create_app` here for the second time during the initialization process of Celery.

I'm not sure why it causes it though or how to fix it (aside from removing this code). 🤔 

@jezdez @emtwo If I'm not mistaken, you were running this code in your env for a long time now. You haven't seen this exception?

**Comment by emtwo** [comment]
Hm, I have personally not come across this and I'm having trouble reproducing it locally in the docker dev environment. Can you reproduce it locally or does this only show up on sentry?

One idea we could try in `add_periodic_tasks()` is similar to what's done here to avoid creating a new context if it's not needed:
https://github.com/getredash/redash/blob/master/redash/cli/__init__.py#L13

`app = current_app or create_app()`

**Comment by arikfr** [comment]
I applied your suggested fix. So far no errors. I hope this truly resolves it. 👍

**Comment by DawerRafi** [comment]
Hi @arikfr,

I am getting this error on my worker.py file when using dockerized deployment.
`
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/app/redash/worker.py", line 70, in __call__
    with current_app.app_context():
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 343, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/local.py", line 302, in _get_current_object
    return self.__local()
  File "/usr/local/lib/python2.7/dist-packages/flask/globals.py", line 51, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
`

I dont know how to debug this further.

**Comment by DawerRafi** [comment]
@arikfr Is it safe to use the same function here as well?

`
class ContextTask(TaskBase):
    abstract = True

    def __call__(self, *args, **kwargs):
        with safe_create_app().app_context():
            return TaskBase.__call__(self, *args, **kwargs)


celery.Task = ContextTask

**Comment by arikfr** [comment]
@DawerRafi it should be, but it's strange that it would be necessary. What version of Redash are you using?

**Comment by DawerRafi** [comment]
version: 6.0.0 (dev)

**Comment by yanenok** [comment]
Same here. Running v6.0.0 (dev) after fix in Docker.

**Comment by arikfr** [comment]
#3465 will probably resolve the issues you had after the previous fix.
