### ISSUE TITLE
Tags input control has confusing keyboard behavior

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3189]
![image](https://user-images.githubusercontent.com/71468/49948619-77cdf480-fefc-11e8-8d07-641ac24139f8.png)

1. When the tag suggestion list is open, I expect the `Esc` key to close it.
2. Also, when the suggestions are closed, I expect the `Enter` key to submit the changes.

What in fact happens is that `Enter` has no effect and `Esc` cancels the dialog. I assume this is in part due to the hybrid of a React control (tags input) and Angular modal. But once we move to only React in this area, we should revisit the UX.

**Comment by ranbena** [comment]
The default ant-design behavior is:
* Press esc -> closes suggestions, press esc again -> closes modal ([demo](https://codesandbox.io/s/3vn7l92pjm)). This is the behavior we want and don't have.
* Press enter -> selects current marked dropdown option. There's no config option to turn it off.
* Press enter when input is not focus -> nothing happens. It's not a keyboard event the modal listens to.

So first off, gotta fix the modal escape hijacking.

Then, for the extra features I can PR the antd project with new attributes:
1. `<Modal onPressEnter={this.onOK} />`
2. `<Select dropdownOnInputOnly={true} />`

Wdyt @arikfr?

**Comment by arikfr** [comment]
I think that making the Modal not hijack the Esc key is 80% of the solution. If you are going to do it by switching to Ant's Modal here, then no further work is required. I noticed in your demo that I can do:

1. Click Esc to close suggestions 👌 
2. Hit Tab , Tab , Enter to submit.

It could be nice to make OK come before Cancel in the Tab order.
