### ISSUE TITLE
Document how to pass parameter values from the URL

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3200]
https://discuss.redash.io/t/query-parameters-via-url/2865

If this happens before #2756 is merged, then need to take into account the changes introduces there.

**Comment by sp1rs** [comment]
Need to `redash` repo, @arikfr can you guide on where to add the doc to?

**Comment by spicypenguin** [comment]
This has already been included in the FAQ here: https://redash.io/help/user-guide/querying/query-parameters#FAQ

I believe this issue can be closed now.
