### ISSUE TITLE
Date range parameters don't serialize correctly in widget titles

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3203]
Check this dashboard:
https://redash-preview.netlify.com/dashboard/date-range

And check the widget URL, it will be something like:

```
https://redash-preview.netlify.com/queries/50?p_date_range=%5Bobject%20Object%5D#table
```

Instead of:

```
https://redash-preview.netlify.com/queries/50?p_date_range.start=2018-12-19&p_date_range.end=2019-01-21
```

**Comment by kravets-levko** [comment]
@arikfr 
![image](https://user-images.githubusercontent.com/12139186/50216391-4dfa4f00-038e-11e9-9c58-83c19e281112.png)

**Comment by arikfr** [comment]
did you open the query from the dashboard?

**Comment by kravets-levko** [comment]
yes

**Comment by kravets-levko** [comment]
@arikfr Reproduced it (not sure how). Will fix ASAP
