### ISSUE TITLE
docker-compose up  command is fails. The node.js version missmatch

### ISSUE THREAD

**Issue by yuua** [getredash/redash#3210]
Hi!! version 6.0.0 release great thankyou 

### Issue Summary

execute  `docker-compose up` command is fails

### Steps to Reproduce

1. git checkout -b v6.0.0 refs/tags/v6.0.0
2. npm install
3. docker-compose up 

### Technical details:

* Redash Version: v6.0.0
* Browser/OS: macOS High Sierra 10.13.6
* How did you install Redash: Docker

### Details

error message

```
> redash-client@6.0.0 bundle /app
> bin/bundle-extensions


> redash-client@6.0.0 build /app
> npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack


> redash-client@6.0.0 clean /app
> rm -rf ./client/dist/

Killed

npm ERR! Linux 4.9.125-linuxkit
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! redash-client@6.0.0 build: `npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the redash-client@6.0.0 build script 'npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redash-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs redash-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls redash-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
ERROR: Service 'server' failed to build: The command '/bin/sh -c npm install && npm run bundle && npm run build && rm -rf node_modules' returned a non-zero code: 1
```

Mismatch between the node version of the redash/base docker image and the version in the package.json.
I think that the node version of the redash/base docker image need to be updated.

in docker redash/base image node version : v6.11.0
in package.json node version :

```
 "engines": {
    "node": "^8.0.0",
....
```

**Comment by arikfr** [comment]
Good catch. I'm surprised this doesn't happen on CI 🤔

**Comment by arikfr** [comment]
Looking at the output again, I think it fails not because of the Node version but because it runs out of memory. Make sure that you assigned enough memory to the Docker VM (if you're using Docker Mac, you can change this from their UI).

We had to update the amount of memory webpack is using during the build. We hope to reduce it when we remove Angular's dependencies.

**Comment by yuua** [comment]
Thank you!!

Memory allocation to Docker VM was 2 GB
Increase allocated memory and try again:bow:

**Comment by yuua** [comment]
I increased memory allocation and succeeded in booting

Thank you
