### ISSUE TITLE
Date/Time Values Format has no effect on Chart X Axis

### ISSUE THREAD

**Issue by kalsolio** [getredash/redash#3215]
![222](https://user-images.githubusercontent.com/14342288/50436259-f9237f00-091f-11e9-95c0-e84e2470d9cb.png)
![111](https://user-images.githubusercontent.com/14342288/50436260-f9bc1580-091f-11e9-86e1-ddac4c556808.png)

**Comment by deecay** [comment]
Hi @kalsolio 

Date/Time setting is for 'data labels' only, and has no effect on 'x-axis labels'.

**Comment by arikfr** [comment]
Maybe we should add a comment mentioning this in the UI?

**Comment by kravets-levko** [comment]
Hi @timc13! It's a technical issue that we currently don't have solution for. We use Plotly.js to render charts, and it's formatting syntax is really weird (probably ok for developer, but definitely not for a regular users). Once we'll find a good way to convert "human-friendly" format (that we use) to ugly one used by Plotly.js - we'll fix this issue.

**Comment by seanmehra** [comment]
I second this request!

**Comment by kimwz** [comment]
please 👍

**Comment by yankeeguyu** [comment]
Thank you all.

**Comment by yankeeguyu** [comment]
This is important to users!

**Comment by yankeeguyu** [comment]
Hi @kravets-levko @arikfr , i found an idea to fix this bug.[]( https://codepen.io/yankeeguyu/pen/KKMwLbe?editors=1010). In layout set `tickformat: %Y %m %d`, it will change x or y axis format. Like this: 
![image](https://user-images.githubusercontent.com/46274612/95812197-6e578280-0d47-11eb-9371-cb206217ffca.png)

Currently I cannot integrate this modification into redash, but it seems to be effective.

**Comment by kravets-levko** [comment]
Hi @yankeeguyu! Yep, we know about this, but please read this comment https://github.com/getredash/redash/issues/3215#issuecomment-460945725 . D3-like syntax (`%Y %m %d`) is not very user-friendly, also, we don't want to introduce second formatting engine (currently we use Moment.js which syntax is more human-oriented: `YYYY MM DD`). Current idea is to somehow convert Moment syntax to D3, but we're still investigating this.

**Comment by yankeeguyu** [comment]
Perhaps this function can be modified as an option, such as scale, we can use Moment.js as an option, but the actual value is a d3 type value, maybe this is a feasible solution. Like this:
![image](https://user-images.githubusercontent.com/46274612/95846337-e476dc00-0d7d-11eb-9041-889d3f6597b7.png)

**Comment by yankeeguyu** [comment]
Now i want to use this solution, but i encountered some problems during development.

**Comment by kravets-levko** [comment]
Value format inputs are not dropdown, it's a text inputs so user may type any valid format string. If we even imagine that we could somehow start using D3 format by default but allowing user to type Moment format string - then we still have to convert between Moment and D3 formats, but in addition we'll have to migrate already created visualizations.

**Comment by yankeeguyu** [comment]
> Value format inputs are not dropdown, it's a text inputs so user may type any valid format string. If we even imagine that we could somehow start using D3 format by default but allowing user to type Moment format string - then we still have to convert between Moment and D3 formats, but in addition we'll have to migrate already created visualizations.

Ok, i see it! Look forward to fixing this bug! Thank you @kravets-levko !

**Comment by litao3rd** [comment]
Hello everyone. Is there any progress on this issue? I meet the same question in version 10.1.0.b50633. Thanks for any reply.

**Comment by eradman** [comment]
The ability to specify a format for X and Y axis was added in commit 0f88a2383572e7a8e8a5958ee7c1d14f88379fa2
