### ISSUE TITLE
Cause warning "Trailing spaces not allowed" when compiling in MacOS  

### ISSUE THREAD

**Issue by qiudaqiang** [getredash/redash#3227]
### Issue Summary

When I compiling in MacOS, I got a "Trailing spaces not allowed" warning, Details are as follows:

WARNING in ./client/app/components/QueryEditor.jsx
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/simon/repository/redash/client/app/components/QueryEditor.jsx
  128:1  error  Trailing spaces not allowed  no-trailing-spaces

✖ 1 problem (1 error, 0 warnings)
  1 error, 0 warnings potentially fixable with the `--fix` option.

### Steps to Reproduce

during "npm run start" command running.

### Technical details:

* Redash Version: 6.0
* Browser/OS: MacOS 10.14.2
* How did you install Redash: Docker

After I deleted line 128 and recompiled again, everything OK, Compiled successfully.

**Comment by kyoshidajp** [comment]
@qiudaqiang Thank you for your report! Already fixed. Please update your source.
