### ISSUE TITLE
Bug: Refresh schedule phrase overlaps title

### ISSUE THREAD

**Issue by ranbena** [getredash/redash#3248]
### Issue Summary
Refresh schedule phrase overlaps title when long enough.

<img width="327" alt="screen shot 2019-01-03 at 18 09 19" src="https://user-images.githubusercontent.com/486954/50648051-db3ec580-0f82-11e9-90c3-30d9a32cece3.png">

(this bug originates from #2426 which has yet to land)

**Comment by arikfr** [comment]
I noticed this too, I think the titles we show should be just a summary: "Weekly schedule"/"Daily schedule"/etc. And then on hover, it will show the full text.

WDYT?

(btw, worth mentioning that this is the behavior once we merge the new scheduler)

**Comment by ranbena** [comment]
Exactly my thoughts
