### ISSUE TITLE
Widget turns into a textbox when a visualization is removed

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3257]
Current behavior: when deleting a visualization in use in some dashboard, the widget using it turns into a text box.

Expected behavior: the widget should be removed.

Bonus behavior: warn the user if the visualization is currently in use before deleting.

**Comment by kravets-levko** [comment]
@arikfr Are you sure that this is frontend-related bug? I think the backend should search for dashboards that use the visualizations and update them. On a frontend we can show a placeholder instead of vis ("Visualization is not available" or something like that) - it's the most we can do with JS.

**Comment by arikfr** [comment]
It's indeed a backend issue, I miscategorized.
