### ISSUE TITLE
Wrong name for "Apache Kylin"

### ISSUE THREAD

**Issue by shaofengshi** [getredash/redash#3264]
Hello, 

In Redash data source page, I see "Kylin by Apache":
https://redash.io/help/data-sources/supported-data-sources

However, the correct name is "Apache Kylin".  Can someone correct it? Thanks!

**Comment by arikfr** [comment]
Thanks for reporting!

Fixed: https://github.com/getredash/website/commit/3da30e8815073f87a4ed09ea5be7a9f7e2273df7
