### ISSUE TITLE
different group show different quries

### ISSUE THREAD

**Issue by panda403** [getredash/redash#3270]
After read the document in user-guide(https://redash.io/help/user-guide/user-management/),It seems that the group is used to control different data sources，but I want to use group to control the quries:different groups shows different quries,users in the same group can see quries by all users in the group,is there has any way to achieve this?Waiting for your reply....

**Comment by arikfr** [comment]
For support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.
