### ISSUE TITLE
Migrate the dashboard grid to React

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3285]
https://github.com/STRML/react-grid-layout might be relevant here.

Part of the React migration (#3071).

Blocked by #3301.

**Comment by ranbena** [comment]
[react-grid-layout](https://github.com/STRML/react-grid-layout) seems like best choice.

@arikfr any functionality improvements you'd like to add?
e.g [Skeleton](https://ant.design/components/skeleton/) widget loading to prevent initial clunkiness (jumpy widget heights).

**Comment by arikfr** [comment]
As with any migration, it's best if we focus on porting current functionality before doing any improvements. If there are some quick wins that can be added on the way, then sure.

Reducing the minimum "step" size could be nice, but it has implications on existing widgets, so not sure about it.

**Comment by ranbena** [comment]
Closes #1775.

**Comment by arikfr** [comment]
@ranbena I think that #1775 is more about widgets in general, like UI components. Anyway, not relevant anymore.
