### ISSUE TITLE
new query - make horizontal scrollbar always visible in results

### ISSUE THREAD

**Issue by araker** [getredash/redash#3290]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. Create a new query
2. Select all fields from a table (make sure the total field width exceeds the screen width)
3. Only a vertical scrollbar appears in the result
4. The horizontal scrollbar is at the bottom of the list 

![screenshot from 2019-01-16 13-38-10_new](https://user-images.githubusercontent.com/430230/51249998-70838600-1995-11e9-9700-a7215876510e.png)

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expect when there are more fields than the result view can hold, a horizontal scrollbar appears, like in the query input view. It would be nice to be able to always scroll horizontally, not only when the bottom of the list is reached.   

![screenshot from 2019-01-17 10-36-51_new](https://user-images.githubusercontent.com/430230/51309463-c105ec80-1a44-11e9-8367-356409e69a0e.png)

### Technical details:

* Redash Version: 6.0.0+b8537
* Browser/OS: chromium 66.0.3359.139 
* How did you install Redash: ami

**Comment by arikfr** [comment]
Thanks, but can you actually scroll horizontally?

**Comment by araker** [comment]
You're right, I see it now, I expected that the scroll bar would always be visible like in the view where the query is defined, but it's at the bottom of the list. 

Then my request would be to make the horizontal scrollbar always visible, I've edited my first post to reflect this.

**Comment by ranbena** [comment]
Fixed by #4101
