### ISSUE TITLE
Exporting to Excel file fails when one of the columns is a dictionary

### ISSUE THREAD

**Issue by wloverine** [getredash/redash#3321]
### Issue Summary

get error when exporting query results to excel file:
![image](https://user-images.githubusercontent.com/33534430/51517880-30217d80-1e57-11e9-9cbf-0ef7ad187218.png)
environment:ec2 on ecs

### Steps to Reproduce

1. create a new query
2. excute the query,save it ,then download it as excel file

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:6.0.0+b8537
* Browser/OS:chrome
* How did you install Redash:run redash by  ecs  on aws

**Comment by kyoshidajp** [comment]
Can you show the error log more detail? And can you download CSV successfully?

**Comment by wloverine** [comment]
> Can you show the error log more detail? And can you download CSV successfully?

![image](https://user-images.githubusercontent.com/33534430/51521827-b7282300-1e62-11e9-9375-d5a119fd29ab.png)
i can download csv successfully,but get error when downloading excel ,and i found that there is a field whose attribute is json.that maybe the cause

**Comment by wloverine** [comment]
> Can you show the error log more detail? And can you download CSV successfully?
I see the similiar problem has benn sloved in issue#2060,is this the same problem?

**Comment by arikfr** [comment]
Indeed it looks like a similar issue.

**Comment by kyoshidajp** [comment]
@wloverine I have submitted #3323. How about converting the field to text as a workaround on your version.

```sql
cast(field as text)
```

**Comment by wloverine** [comment]
@kyoshidajp  thanks !

**Comment by wloverine** [comment]
> Indeed it looks like a similar issue.

will there be a new version of redash on docker hub incoming that fixs this problem? @arikfr

**Comment by arikfr** [comment]
Yes, it will be part of the next release.
