### ISSUE TITLE
Can't connect AWS RDS

### ISSUE THREAD

**Issue by luckymaniac** [getredash/redash#3322]
### Issue Summary

Cannot connect Amazon RDS.
I inputed necessary information to connect RDS(MySQL), but can't connect the database.

### Steps to Reproduce

<img width="1915" alt="screen shot 2019-01-22 at 8 42 34 pm" src="https://user-images.githubusercontent.com/17960970/51533527-7cd07d00-1e86-11e9-9de4-82e567f69ea6.png">

### Technical details:

* Redash Version: 1.0.3+b2850
* Browser/OS: Chrome / MacOS 10.13.6
* How did you install Redash:

**Comment by arikfr** [comment]
There are plenty of reasons you might receive this message, but it's unlikely to be an issue with Redash, but rather with your setup. As instructed, please use [the forum](https://discuss.redash.io) for this type of questions.

Also note that you're using Redash v1.0.3 when we already have Redash v6... You should consider upgrading.
