### ISSUE TITLE
Set filename when calling the /results endpoint directly

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3326]
Probably by using the `Content-Disposition` header.

**Comment by aidarbek** [comment]
Hi! I am new to the project, could you clarify few things? As far as I understood, the [https://github.com/getredash/redash/blob/master/redash/handlers/query_results.py](https://github.com/getredash/redash/blob/master/redash/handlers/query_results.py) file (`QueryResultResource` class) should be changed and `Content-Disposition` header should be added to response containing xlsx, csv and json files. What the name of the file should be? Can it be `query_result_id` or `query_id` variables?

**Comment by arikfr** [comment]
Hi @aidarbek, welcome :)

This is how we generate the filename on the frontend:

https://github.com/getredash/redash/blob/ff42ec2cc6700023e48c85fde387a955700b507a/client/app/components/queries/query-results-link.js#L27-L28

Basically: query name (spaces replaced with `_`) + date of query result execution + file extension.

I guess we can do the same?

**Comment by arikfr** [comment]
Implemented in #3359 by @aidarbek 🙇
