### ISSUE TITLE
Multi axis bar charts are always stacked

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#3336]
### Issue Summary

A bar chart with two sets of data displayed on the left and right axes automatically stacks the data.

![screen shot 2019-01-24 at 1 34 49 pm](https://user-images.githubusercontent.com/17067911/51703790-ebbfea00-1fdc-11e9-83e2-5fd4fd8548d3.png)

In the example shown in this screenshot, every red bar should appear at 6 on the right axis. The blue bars are measured on the left axis. But instead of appearing as two separate bars, they are stacked. So the blue values under 20k are not rendered at all.

### Steps to Reproduce

1. Run a query where each returned record includes a category and number values
2. Make a bar visualization with categories for the X axis and both number fields as the Y axes
3. Configure one number value on the left Y axis and the other on the right

### Technical details:

* Redash Version: 431d6fa
* Browser/OS: Firefox 64 
* How did you install Redash: Saas Version

**Comment by kravets-levko** [comment]
Duplicate getredash/redash#2292
