### ISSUE TITLE
Allow adding Pivot Tables as widgets

### ISSUE THREAD

**Issue by advance512** [getredash/redash#334]

**Comment by eschultze** [comment]
+1 This would be very nice!

**Comment by jnv** [comment]
:+1: I'd love to see this too. Also, the pivot setup would have to be remembered.

**Comment by jdanbrown** [comment]
+1, cc @cngan

**Comment by jdanbrown** [comment]
+1, cc @chrisngan24

**Comment by matiascarazzo** [comment]
+1

**Comment by shenyubao** [comment]
+1

**Comment by leonardmchang** [comment]
+1

**Comment by sromku** [comment]
+1

**Comment by toyama0919** [comment]
+1

**Comment by haimco10** [comment]
+1

**Comment by dudleycarr** [comment]
@arikfr Is this currently unsupported? Issue #183 suggests that this does work. On the latest version, it does not seem to be an option to add a pivot table as a dashboard item.

**Comment by arikfr** [comment]
@dudleycarr not yet. #183 is about dragging and dropping in the pivot itself...

**Comment by amaragrawal** [comment]
+1

**Comment by alepaltri** [comment]
+1

**Comment by arikfr** [comment]
Finally implemented in #827 and will be part of the 0.9.2 release.
