### ISSUE TITLE
NPM config is incorrect / out of date

### ISSUE THREAD

**Issue by bhartvigsen** [getredash/redash#3344]
Running: npm install

Results in:

npm WARN optional Skipping failed optional dependency //fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN optional Skipping failed optional dependency /sane/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.2.7
npm WARN leaflet.markercluster@1.4.1 requires a peer of leaflet@~1.3.1 but none was installed.
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none was installed.
npm ERR! Linux 4.4.0-138-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! webpack-cli@3.2.1 postinstall: `lightercollective`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the webpack-cli@3.2.1 postinstall script 'lightercollective'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lightercollective
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-cli
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
[npm-debug.log](https://github.com/getredash/redash/files/2796375/npm-debug.log)

**Comment by bhartvigsen** [comment]
NPM update resolved this.

**Comment by arikfr** [comment]
Thanks you for the follow up.
