### ISSUE TITLE
Redash worker fails for Presto

### ISSUE THREAD

**Issue by phlash-zero** [getredash/redash#3350]
### Issue Summary

I ran latest redash docker image with seems like it fails on Celery citing security issue.
Result of this being redash cannot reach presto coordinator.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: latest
* Browser/OS:
* How did you install Redash: docker-compose

**Comment by arikfr** [comment]
It will help a lot if you can provide critical information like what docker-compose configuration you used and more important -- what is the log message you're seeing from Celery...

**Comment by arikfr** [comment]
Closing. You're welcome to reopen with additional details.
