### ISSUE TITLE
[Widget Params] Bug: Date value empty in static param input

### ISSUE THREAD

**Issue by ranbena** [getredash/redash#3355]
### Issue Summary

Static date value loads empty when editing parameter.

### Steps to Reproduce

1. Add new widget to dashboard, with date range as static value.
2. Click "edit parameters" on widget

**Expected**: initial value should be preselected in static value input.
**Actual**: input remains empty

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/486954/51801864-e61c0b80-224b-11e9-9a93-c461e3b771cb.gif)

The reason for this is hinted at in the open console

**Comment by arikfr** [comment]
@ranbena does it happen to any static value or only date ranges?

**Comment by ranbena** [comment]
@arikfr yeah it manifests in every value type.
In some scenarios even a `[object Object]` value is prefilled. A date (non-range) generates a js error.

@kravets-levko wdyt?

**Comment by arikfr** [comment]
So strange, I'm pretty sure this was working. One more thing to try: does it reproduce if you pick a new value (different than the default one)?

**Comment by ranbena** [comment]
> does it reproduce if you pick a new value?

Yep, pick a new value, save, click edit params, it's gone.

**Comment by ranbena** [comment]
Fixed by #3357
