### ISSUE TITLE
Add periodic task to clear schedule of queries whose schedule until value is in the past

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3375]
We now have an optional expiry date for the query schedule. We should add a periodic Celery task to clear the schedule on such queries.

**Comment by aidarbek** [comment]
Does it really have to be a separate task? I just saw this line https://github.com/getredash/redash/blob/af168c69b95cf466558c2eaa8a753ffb7ec95805/redash/models/__init__.py#L572
Which is executed when `refresh_queries` celery task is running. Maybe adding schedule clearing inside of this `if` statement could solve this issue?

**Comment by arikfr** [comment]
That's an option too. I wouldn't do the update in-place though, but rather return the list of queries to remove scheduling of from `outdated_queries` call, and then do the schedule removal after doing the queries refresh.
