### ISSUE TITLE
[Widget Params] Bug: widget oblivious to updated static value

### ISSUE THREAD

**Issue by ranbena** [getredash/redash#3379]
Originally reported by @arikfr in https://github.com/getredash/redash/pull/3334#issuecomment-459269626.

STR:
1. Go to widget with static parameter, click "edit parameters".
2. Change value of parameter, click "save".

**Expected** - Widget auto refreshes with new value.
**Actual** - Widget remains with previous value.

Clicking the widget refresh button updates it. Just need to make it automatic on change.

**Comment by ranbena** [comment]
@kravets-levko is this something you have time to fix?

**Comment by ranbena** [comment]
@arikfr @kravets-levko do you think this would do it? https://github.com/getredash/redash/commit/a843b924cd67fe86dc9d0169559bcf5949f4b1ff

**Comment by kravets-levko** [comment]
Indeed it will work. I'm just not sure if it solves described issue - it will refresh widget on any parameter mappings change, not only static values :thinking:

**Comment by kravets-levko** [comment]
> Makes sense anyway, no?

Probably yes :slightly_smiling_face:

**Comment by kravets-levko** [comment]
@arikfr WDYT?

**Comment by arikfr** [comment]
I think it makes sense -- like the case where you change a mapping from one dashboard param to another.

So as long as it runs when mapping changed, I'm good with this.

**Comment by ranbena** [comment]
Right now it refreshes on save button click. Which means, also param label renaming. Would you like to filter that case out?

Is refresh such an expensive action that we'd rather avoid any needless calls to it?

**Comment by arikfr** [comment]
> Is refresh such an expensive action that we'd rather avoid any needless calls to it?

Sometimes it is, sometimes it isn't...

If it's easy to call it only when really needed, let's do it. Otherwise, let's fix the bug.

**Comment by susodapop** [comment]
> In this pr it refreshes on save button click.

In my experience this could be a real dealbreaker for trying out the functionality. Some of my dashboards can take north of a minute to update. It feels weird to make changes to the **title** of a parameter and have it refresh the relevant widgets. Refresh should only happen when absolutely necessary IMO.

**Comment by ranbena** [comment]
Made it so only parameter value changes trigger an automatic refresh.
Title changes won't, even param type change won't.
https://github.com/getredash/redash/pull/3445
