### ISSUE TITLE
Cohort chart has hard coded data label "Users"

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#3392]
### Issue Summary

The settings panel for the cohort chart does not let me select the name for my population column. Instead it always defaults to say "Users". I think it's this line that causes it:

https://github.com/getredash/redash/blob/69e34f048aa2313dc65e9f9a2bffe5c6c9164bc4/client/app/visualizations/cohort/index.js#L176

### Steps to Reproduce

1. Make any Cohort chart
2. Observe that the total population is always labeled "Users"

See my screenshots from Issue #1201. My query in that example specifically calls that field `popsize` but it's labeled **Users** on the visualization.

I expect this column to use the label of the associated column alias in the query. Alternatively, let me type my preferred labels in the visualization settings.

### Technical details:

* Redash Version: c7e0990
* Browser/OS: Safari, Firefox, Chrome on MacOS
* How did you install Redash: Saas

**Comment by ranbena** [comment]
@arikfr this is a bug, yeah?

**Comment by arikfr** [comment]
More like missing feature I would say.
