### ISSUE TITLE
Supporting query templates

### ISSUE THREAD

**Issue by sidazhang** [getredash/redash#340]
Is it possible to add support for templates

```
SELECT
*
FROM
users
WHERE id = {{user_id}}
```

You supply the arguments before rendering the charts.

This allows building admin dashboard to be able to look up the stats of individual users.

**Comment by arikfr** [comment]
Just wanted to give a heads up that this was implemented some time ago. See http://demo.redash.io/queries/146?p_action=create for usage example.

**Comment by akkida746** [comment]
Can i customize redash dashboard ui? I want to create multiple views and other user dashboard of my team. Is this possible in redash? Pls let me know. Thanks !
