### ISSUE TITLE
Improvements to our commit-hook (lint-staged)

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3433]
- [ ] Switch to using `prettier-eslint` for linting and formatting files along with calling `git add` when done.
- [ ] Run Prettier on CSS/Less files as well.
- [ ] Make sure the messaging about what's going on is clear, as it might be confusing to new developers. 
- [ ] Run flake8 when the developer using our Docker setup

**Comment by ranbena** [comment]
You mean `git add` cause you wanna run it with `--fix`?

**Comment by jezdez** [comment]
To echo my question in https://github.com/getredash/redash/pull/3390#issuecomment-463234098, can we add a kill switch to all of these hooks to optionally disable it?

**Comment by ranbena** [comment]
Other than `-n`?

**Comment by jezdez** [comment]
@ranbena Yes.

**Comment by ranbena** [comment]
I think you can just remove the files relevant from `.git/hooks`.

**Comment by jezdez** [comment]
Would that have to happen on individual `npm install` runs?

**Comment by ranbena** [comment]
Indeed. Every husky install would bring em back.

**Comment by arikfr** [comment]
> Indeed. Every husky install would bring em back.

That's not a solution :-)

Although I'm not sure if having a solution that permanently disables this makes sense. 🤔 It's either we think it's necessary or we don't.

**Comment by arikfr** [comment]
@ranbena btw, how about we run tests only on push and linting on commit? Linting should be fast on a few files and almost a no-op, while tests are a bit heavier.

**Comment by jezdez** [comment]
There is the [`HUSKY_SKIP_INSTALL`](https://github.com/typicode/husky/blob/c6b992552b987a7e132f40d2c18a9e697182f78e/src/installer/index.ts#L131-L138) env var that when set during installation prevents the hooks to auto-installed in the .git directory.

There is the `node husky uninstall` command that uninstalls the hooks.

Both things don't really prevent this from persisting between runs of npm install.

**Comment by ranbena** [comment]
> not sure if having a solution that permanently disables this makes sense.

Since it's overridable anyhow, I don't see a problem with allowing devs to disable it comfortably. If there's a technical way I'd be happy to review such a PR.

> we run tests only on push

It's a trade-off. On pre-push the full suite would have to be run which is a waste.

**Comment by jezdez** [comment]
> > Indeed. Every husky install would bring em back.
> 
> That's not a solution :-)
> 
> Although I'm not sure if having a solution that permanently disables this makes sense. 🤔 It's either we think it's necessary or we don't.

I couldn't find an explanation in #3390 why this commit hook is necessary to be honest. Could you elaborate what the advantages are?

**Comment by arikfr** [comment]
@ranbena,

> Since it's overridable anyhow, I don't see a problem with allowing devs to disable it comfortably. If there's a technical way I'd be happy to review such a PR.

The problem is one of the message it sends: it's either we think it's important or we don't. If we don't, then we can just provide instructions to how to setup hooks for whoever interested instead.

@jezdez,

> I couldn't find an explanation in #3390 why this commit hook is necessary to be honest.

1. To make sure we get consistent code in terms of formatting (helps with reviews later on).
2. Provides earlier feedback to the developer about lint errors. It's not uncommon to see lint errors ignored. If the feedback provided early in the process (or fixed automatically) it's easier to handle.

**Comment by jezdez** [comment]
FWIW, to reiterate what I said before: it would be great to have this hook not auto-installed and/or a way disable it easily. And no, remembering how to disable commit validation/verification on every commit isn't enough.

An example for how this breaks things for me, a screenshot of the Tower Git app that I use to commit things when I want to split changes up into individual commits or have to handle the rebases of our fork:

<img width="901" alt="screen-shot-2019-03-05-13-12-38 51" src="https://user-images.githubusercontent.com/1610/53804835-d083bb00-3f48-11e9-89da-f9af83ef1ea7.png">

**Comment by ranbena** [comment]
> An example for how this breaks things for me, a screenshot of the Tower Git app

Yeah Tower Git has [issues with hooks](https://www.git-tower.com/help/mac/faq-and-tips/faq/hook-scripts). Have you tried mitigating this?

**Comment by jezdez** [comment]
> > An example for how this breaks things for me, a screenshot of the Tower Git app
> 
> Yeah Tower Git has [issues with hooks](https://www.git-tower.com/help/mac/faq-and-tips/faq/hook-scripts). Have you tried mitigating this?

This isn't really an issue Tower has, it simply uses a PATH environment variable without the local `node_modules` directory. I don't think it's reasonable to having to maintain a custom, global plist file just to be able to commit to this repo.
