### ISSUE TITLE
Query Editor Cutoff for long queries in chrome

### ISSUE THREAD

**Issue by RobinDarrah** [getredash/redash#3478]
### Issue Summary

 Query box is cutoff for long queries, box must be resized to see all rows.

### Steps to Reproduce

1. Open http://demo.redash.io/queries/12/source#16 in chrome (any long query will do)
2.  Query appears to be 3 rows
3. Resize query box - now shows the rest of the query

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 6.0.0+b8536 (and demo.redash.io)
* Browser/OS: Chrome 72 Windows / Mac
* How did you install Redash: Manual install on ec2, but bug is also present on demo.redash.io

**Comment by jezdez** [comment]
Thanks for opening the issue @RobinDarrah. This is a duplicate of #3353 that got fixed in #3412.
