### ISSUE TITLE
Error running query: Decimal128('0') is not JSON serializable

### ISSUE THREAD

**Issue by CodeFuriate** [getredash/redash#3481]
ANY mongo query for table with Decimal128 field type fails.
Every mongo query must be aggregated and projected to not return Decimal128 fields.
We are using Decimal128 to work with e.g. transaction amounts so its critical to us.

### Technical details:

* Redash Version: Redash 6.0.0+b8537 (4780bd9c)
* Browser/OS: Safari
* How did you install Redash: Cloud

**Comment by arikfr** [comment]
Need to extend the [JSON encoder](https://github.com/getredash/redash/blob/e9c88ea176387cad6b5188ec7c6061eb78d765fd/redash/query_runner/mongodb.py#L35-L42) to support this object type as well.

**Comment by aidarbek** [comment]
Hi! I've fixed the issue with latest PR. I've added the check into JSON encoder for Decimal128 type and tested it locally. But I am converting it into integer data type, is it OK instead of a string?
