### ISSUE TITLE
DynamicForm ignores default value for checkboxes

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3486]
### Issue Summary

Checkbox field might have a default value of true, it seems that DyanmicForm ignores this.

### Steps to Reproduce

1. Open new Data Source form of type BigQuery
2. "Use Standard SQL" should  be checked by default, but it isn't.

### Technical details:

* Redash Version: master

**Comment by gabrieldutra** [comment]
Yep, it seems I've removed the whole `setDefaults` thing after a CR comment :sweat_smile:. ([ref](https://github.com/getredash/redash/pull/3209/commits/8a2016e3cd3e5e9297d9556c9721d2452141db3f)). There were default values to inputs as well, but I guess the best for UX here will be to keep their default values as placeholders and treat checkboxes separately. WDYT?

**Comment by arikfr** [comment]
> but I guess the best for UX here will be to keep their default values as placeholders and treat checkboxes separately. WDYT?

👍
