### ISSUE TITLE
Parameter Dialog UX Issues

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3523]
* When opening the New Parameter dialog it should auto focus on the keyword field.
* Pressing `Enter` should submit the dialog.

The two above are to support keyboard only workflow, where you would hit Cmd+P -> Enter keyword -> Hit Enter, and can continue writing your query.

* "This is the keyword that will be added..." string always being split into two rows: maybe we should just show the keyword (the `{{ ... }}` part) on the second row?

* There should be some indication that we saved the query after hitting OK (when we save).

**Comment by ranbena** [comment]
> There should be some indication that we saved the query after hitting OK (when we save).

There is one when confirming an editing, but when adding a new param I left it as it was - dirty indication. Think we should change that?

**Comment by arikfr** [comment]
> There is one when confirming a param edit, but when adding a new param I left it as it was - dirty indication. Think we should change that?

Nope.

**Comment by ranbena** [comment]
In that case, all issues resolved in #3528.
