### ISSUE TITLE
Error occurred while trying to proxy request /api/session from localhost:8080 to http://localhost:5000/

### ISSUE THREAD

**Issue by baorr** [getredash/redash#3538]
### Issue Summary

[HPM] Error occurred while trying to proxy request /api/session from localhost:8080 to http://localhost:5000/ (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

### Steps to Reproduce

1. npm i
2. npm start
3. type "http://localhost:8080/" in the browser

![image](https://user-images.githubusercontent.com/553038/53851619-2e241000-3ffa-11e9-9036-4e82f21e67c8.png)

### Technical details:

* Redash Version: "7.0.0-beta",
* Browser/OS: Chrome/macOS Mojave
* How did you install Redash:
1. git clone redash
2. cd redash
3. npm i
4. npm start

**Comment by arikfr** [comment]
It looks like you're not running a server. Please make sure you followed the developer setup guide:
https://redash.io/help/open-source/dev-guide/docker

Also, in the future, for support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.
