### ISSUE TITLE
Docker setup failed in worker_1    |   File "/usr/local/lib/python2.7/dist-packages/pymapd/connection.py", line 168

### ISSUE THREAD

**Issue by nptech9806** [getredash/redash#3542]
### Issue Summary

Docker setup failed in worker_1    |   File "/usr/local/lib/python2.7/dist-packages/pymapd/connection.py", line 168

### Steps to Reproduce

1. Follow instructions in https://redash.io/help/open-source/dev-guide/docker

Outcome:
worker_1    | [2019-03-07 03:24:35,096][PID:1][INFO][root] Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
worker_1    | Traceback (most recent call last):
worker_1    |   File "/usr/local/bin/celery", line 11, in <module>
worker_1    |     sys.exit(main())
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/__main__.py", line 16, in main
worker_1    |     _main()
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 322, in main
worker_1    |     cmd.execute_from_commandline(argv)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/celery.py", line 496, in execute_from_commandline
worker_1    |     super(CeleryCommand, self).execute_from_commandline(argv)))
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 273, in execute_from_commandline
worker_1    |     argv = self.setup_app_from_commandline(argv)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 479, in setup_app_from_commandline
worker_1    |     self.app = self.find_app(app)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 501, in find_app
worker_1    |     return find_app(app, symbol_by_name=self.symbol_by_name)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/app/utils.py", line 359, in find_app
worker_1    |     sym = symbol_by_name(app, imp=imp)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/bin/base.py", line 504, in symbol_by_name
worker_1    |     return imports.symbol_by_name(name, imp=imp)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/kombu/utils/imports.py", line 56, in symbol_by_name
worker_1    |     module = imp(module_name, package=package, **kwargs)
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/celery/utils/imports.py", line 104, in import_from_cwd
worker_1    |     return imp(module, package=package)
worker_1    |   File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
worker_1    |     __import__(name)
worker_1    |   File "/app/redash/__init__.py", line 79, in <module>
worker_1    |     import_query_runners(settings.QUERY_RUNNERS)
worker_1    |   File "/app/redash/query_runner/__init__.py", line 271, in import_query_runners
worker_1    |     __import__(runner_import)
worker_1    |   File "/app/redash/query_runner/mapd.py", line 4, in <module>
worker_1    |     import pymapd
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/pymapd/__init__.py", line 19, in <module>
worker_1    |     from .connection import (  # noqa
worker_1    |   File "/usr/local/lib/python2.7/dist-packages/pymapd/connection.py", line 168
worker_1    |     raise err from e
worker_1    |                  ^
worker_1    | SyntaxError: invalid syntax
redash_worker_1 exited with code 1

### Technical details:

* Redash Version:
* Browser/OS:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

* How did you install Redash:
https://redash.io/help/open-source/dev-guide/docker

**Comment by janebaba007** [comment]
I encountered the same issue, the redash version 5.0.2 and 6.0.0 all same issue. Any one can help?

**Comment by arikfr** [comment]
Thank you for reporting this. The version of pymapd wasn't pinned in the requirements file and in a recent release they dropped support for Python 2. #3543 fixes this.
