### ISSUE TITLE
Replace toastr with Ant component

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3547]
- [ ] Pick Ant component to use ([`<Notification>`](https://ant.design/components/notification/) or [`<Message>`](https://ant.design/components/message/), maybe both?).
- [ ] Replace calls to `toastr` with one of the above.
- [ ] Remove `angular-toastr` from dependencies.

**Comment by kravets-levko** [comment]
I think `<Notification>` is a direct replacement for `angular-toastr`. Also, IMO it's less annoying - `Message` is always shown on middle-top part of screen and therefore attracts more attention (especially when there are 2-3 messages at the same time - sometimes it happens in Redash).

**Comment by arikfr** [comment]
It seems that Notification is supposed to be used with lighter messages like "Query Saved" while Notification is for longer stuff, like -- "Test Connection failed, here's the details: ...". 

But if Notification "works" with short content as well, then probably best to have only one.
