### ISSUE TITLE
ElasticSearch: schema refresh failed

### ISSUE THREAD

**Issue by LuisDeHaro** [getredash/redash#3570]
### Issue Summary

When I try to create a new query using a ES data source I get an error: schema refresh failed.

### Steps to Reproduce

1. Created a ES datasource successfully 
2. When creating a new query and selecting the ES data source a message appears: Schema refresh failed. Please try again later.

### Technical details:

* Redash Version: 6.0.0+b8537 (4780bd9c)
* Browser/OS: MacOS 10.14.1, Chrome 72.0.3626.121
* How did you install Redash: Docker
* ElasticSearch version: 5.6.4

**Comment by rauchy** [comment]
Thanks for reporting, @LuisDeHaro.

Given the details you provided, it works fine for me and I can't seem to reproduce the problem. Since this is probably not a general issue with the project, could you please submit this question in [our forums](https://discuss.redash.io/)? Make sure you include server logs that show this error. Also, indicate if you are able to execute queries, regardless of the schema refresh failure.

**Comment by truebit** [comment]
I use Redash 7.0.0 and Elasticsearch 5.6.3
Here below is the debug log from redash:
the elasticsearch _mappings request got success response. but redash UI rejected the response for some reason.
> 
> [2019-04-09 22:07:07,466][PID:724][INFO][sqlalchemy.engine.base.Engine] BEGIN (implicit)
> [2019-04-09 22:07:07,467][PID:724][INFO][sqlalchemy.engine.base.Engine] SELECT organizations.updated_at AS organizations_updated_at, organizations.created_at AS organizations_created_at, organizations.id AS organizations_id, organizations.name AS organizations_name, organizations.slug AS organizations_slug, organizations.settings AS organizations_settings
> FROM organizations
> WHERE organizations.slug = %(slug_1)s
>  LIMIT %(param_1)s
> [2019-04-09 22:07:07,467][PID:724][INFO][sqlalchemy.engine.base.Engine] {'slug_1': 'default', 'param_1': 1}
> [2019-04-09 22:07:07,468][PID:724][DEBUG][metrics] table=organizations query=select duration=2.07
> [2019-04-09 22:07:07,469][PID:724][DEBUG][root] Current organization: TESTORG (1) (slug: default)
> [2019-04-09 22:07:07,472][PID:724][INFO][sqlalchemy.engine.base.Engine] SELECT users.profile_image_url AS users_profile_image_url, users.groups AS users_groups, users.updated_at AS users_updated_at, users.created_at AS users_created_at, users.id AS users_id, users.org_id AS users_org_id, users.name AS users_name, users.email AS users_email, users.password_hash AS users_password_hash, users.api_key AS users_api_key, users.disabled_at AS users_disabled_at, users.details AS users_details
> FROM users
> WHERE users.id = %(id_1)s AND %(param_1)s = users.org_id
> [2019-04-09 22:07:07,472][PID:724][INFO][sqlalchemy.engine.base.Engine] {'id_1': u'1', 'param_1': 1}
> [2019-04-09 22:07:07,473][PID:724][DEBUG][metrics] table=users query=select duration=2.20
> [2019-04-09 22:07:07,476][PID:724][INFO][sqlalchemy.engine.base.Engine] SELECT data_sources.encrypted_options AS data_sources_encrypted_options, data_sources.id AS data_sources_id, data_sources.org_id AS data_sources_org_id, data_sources.name AS data_sources_name, data_sources.type AS data_sources_type, data_sources.queue_name AS data_sources_queue_name, data_sources.scheduled_queue_name AS data_sources_scheduled_queue_name, data_sources.created_at AS data_sources_created_at
> FROM data_sources
> WHERE data_sources.id = %(id_1)s AND %(param_1)s = data_sources.org_id
> [2019-04-09 22:07:07,477][PID:724][INFO][sqlalchemy.engine.base.Engine] {'id_1': u'3', 'param_1': 1}
> [2019-04-09 22:07:07,478][PID:724][DEBUG][metrics] table=data_sources query=select duration=1.96
> [2019-04-09 22:07:07,480][PID:724][INFO][sqlalchemy.engine.base.Engine] SELECT data_source_groups.id AS data_source_groups_id, data_source_groups.data_source_id AS data_source_groups_data_source_id, data_source_groups.group_id AS data_source_groups_group_id, data_source_groups.view_only AS data_source_groups_view_only
> FROM data_source_groups
> WHERE %(param_1)s = data_source_groups.data_source_id
> [2019-04-09 22:07:07,480][PID:724][INFO][sqlalchemy.engine.base.Engine] {'param_1': 3}
> [2019-04-09 22:07:07,481][PID:724][DEBUG][metrics] table=data_source_groups query=select duration=1.51
> [2019-04-09 22:07:07,483][PID:724][INFO][sqlalchemy.engine.base.Engine] SELECT groups.id AS groups_id, groups.org_id AS groups_org_id, groups.type AS groups_type, groups.name AS groups_name, groups.permissions AS groups_permissions, groups.created_at AS groups_created_at
> FROM groups
> WHERE groups.id IN (%(id_1)s, %(id_2)s)
> [2019-04-09 22:07:07,483][PID:724][INFO][sqlalchemy.engine.base.Engine] {'id_2': 2, 'id_1': 1}
> [2019-04-09 22:07:07,484][PID:724][DEBUG][metrics] table=groups query=select duration=1.58
> [2019-04-09 22:07:07,487][PID:724][DEBUG][urllib3.connectionpool] Starting new HTTP connection (1): 10.20.51.96:8080
> **[2019-04-09 22:07:07,492][PID:724][DEBUG][urllib3.connectionpool] http://10.20.51.96:8080 "GET /_mappings HTTP/1.1" 200 1120**
> [2019-04-09 22:07:07,495][PID:724][INFO][metrics] method=GET path=/api/data_sources/3/schema endpoint=datasourceschemaresource status=200 content_type=application/json content_length=61 duration=20.69 query_count=5 query_duration=9.31
> [2019-04-09 22:07:07,496][PID:724][INFO][sqlalchemy.engine.base.Engine] ROLLBACK

**Comment by axelsean** [comment]
I get this also - with a kibana index present - is this issue open or closed ?

**Comment by truebit** [comment]
@axelsean check my PR to fix this issue. my PR is not merged yet. you could support my PR to get it merged.

**Comment by axelsean** [comment]
@truebit I looked at the PR - thanks it certainly identifies the issue - however for me it had a minor problem - I added a comment - I'm using Redash in a docker container, so maybe an issue with Python versions ?

**Comment by ssozonoff** [comment]
Having the same issue with Redash version 7.0 Also running in a docker container. ES connection seems to be fine.

**Comment by YakobovLior** [comment]
I'm experiencing the same issue now with MongoDB datasource, while it did worked before (just tried again a couple of days ago against an existing datasource and suddenly it cannot show the collections in the database).
Any help please? I see this issue is frequently asked online but no helpful resolution.
Thanks,
Lior

**Comment by truebit** [comment]
@YakobovLior you should open a new issue, as this issue is for Elasticsearch.

**Comment by timyilong** [comment]
encountered same issue, still open or closed?
