### ISSUE TITLE
A forked query clones all visualizations except for table visualizations

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#3572]
### Issue Summary

Suppose I have "Query A" that includes two chart visualizations and two table visualizations for a total of **four visualizations**. One of the table visualizations is the default, the other is a custom table visualization that hides certain columns and formats others. I fork "Query A" and call it "Query B".

After the fork, "Query B" is identical to "Query A" except it only has **three total visualizations**: two charts and the default table, but my custom table is not forked.

### Steps to Reproduce

1. Make a query and add a second table visualization in addition to the default
2. Fork the query
3. Notice that the second table visualization is not included

I would expect all the visualizations to come along with the query when it is forked.

### Technical details:

* Redash Version: 7.0.0
* Browser/OS: Chrome, Firefox, Safari
* How did you install Redash: SaaS

**Comment by kravets-levko** [comment]
It's definitely a bug: some time ago table wasn't a real visualization, I think that code that forks queries still does not know that now table is a visualization and should be copied as well :grin:

**Comment by arikfr** [comment]
Exactly. One caveat though: when a query is created we create a table for it by default. When resolving this we need to make sure we don't end up with N+1 tables :)
