### ISSUE TITLE
Show message when trying to load Redash from an unsupported browser

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3579]
Unsupported browsers: IE or old versions of Edge.

Need to update `index.html` to show a message instead of loading broken code.

**Comment by ranbena** [comment]
Discussing redirect page layout here https://discuss.redash.io/t/unsupported-browser-page/3449

**Comment by ranbena** [comment]
@arikfr do you think we should host this page with GH pages?

**Comment by arikfr** [comment]
Why not part of the package?

-- 
Arik Fraimovich

**Comment by ranbena** [comment]
To disconnect it from the Python server. Irrelevant?

**Comment by ranbena** [comment]
I mean, the options we currently have are either Angular/React routing which might fail on unsupported browsers, or python static html which we'd rather avoid to preserve separation of client/server. So, GH pages (or website / help docs) seems like an easy alternative.

**Comment by arikfr** [comment]
No we have a 3rd option: add this logic in [`index.html`](https://github.com/getredash/redash/blob/master/client/app/index.html), which is the file that we serve to the user when they ask for the frontend client. This gets served with the Python server and will be served with any other option we switch to (and Netlify at the moment). Then we can replace the content of index.html with the message or just redirect to the relevant HTML page which will be served by whatever solution we're using.
