### ISSUE TITLE
Sql query is very slow

### ISSUE THREAD

**Issue by Finger5** [getredash/redash#3591]
### Issue Summary

Sql query is very slow,I can't find the result for a long time.

### Steps to Reproduce

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:latest
* Browser/OS:windows
* How did you install Redash:pycharm，used flask server

**Comment by rauchy** [comment]
Hi @Finger5, thanks for reporting. If you need support, please head on to [our forums](https://discuss.redash.io/) and try to provide more information such as server logs, which setup are you using and which queries / data sources you are using.
