### ISSUE TITLE
6.0.0 release breaks on non-docker environment by kombu, redis-py dependency.

### ISSUE THREAD

**Issue by breath103** [getredash/redash#3607]
### Kombu dependency issue
on 6.0.0 release requirements.txt file, kombu is not explicitly pinned with version, so it ended up using "Collecting kombu<5.0,>=4.2.0 (from celery==4.2.1->-r requirements.txt (line 34))"

which is fine if it installs 4.2.0 luckily, but if it installs 4.4.0 (which happened to me) it breaks since it requires redis-py>=3.1.0, which has major changes including zadd syntax. so installing just kombu>4.4.0 && redis>=3.1.0 doesn't fix the problem. since code breaks.

### Steps to Reproduce

1. install 6.0.0 without docker
2. make sure pip installed kombu 4.4.0
3. run query, it will break with Redis Transport requires redis-py>3.1.0 error

### FIx
Pin kombu dependency to 4.2.0 on hotfix release for 6.X. i do know this already been fixed on 7.X

**Comment by arikfr** [comment]
Thank you for bringing this to our attention.

Because the tarball deployment method is deprecated, we will not release another tar ball for v6. You're welcome to use v7's tarball or update `requirements.txt` manually.

**Comment by breath103** [comment]
OK thanks for checking 👍
