### ISSUE TITLE
IOError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by kxiaoba** [getredash/redash#3644]
I git pull the lastst redash.Find the dist directory is lost.
The Progrem has always find the old directroy .
IOError: [Errno 2] No such file or directory:   ../../client/dist/index.html

**Comment by arikfr** [comment]
Please make sure you followed all the steps in the dev guide. Looks like you didn't build the frontend assets.

In the future, for support and usage questions, please use the forum.

Thanks.
