### ISSUE TITLE
Add instructions on how to configure Auth0 to the docs

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3646]
@madAndroid was kind enough to provide instructions on how to configure Redash with Auth0/SAML on the forum: https://discuss.redash.io/t/auth0-integration/586/5.

We should port this over to the Knowledge Base (either as a section in the [Authentication Options page](https://github.com/getredash/website/edit/master/src/pages/kb/user-guide/users/authentication-options.md) or a dedicated one).

**Comment by r0cketr1kky** [comment]
Check out this pr: https://github.com/getredash/website/pull/336

**Comment by spicypenguin** [comment]
The related PR above has been merged, can this issue be closed now?

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
