### ISSUE TITLE
redash7.0 schema refresh failed:get schema from hive(1.2.1000) datasource  error

### ISSUE THREAD

**Issue by xlingit** [getredash/redash#3651]
* Redash Version:7.0
* Browser/OS:chrome
* How did you install Redash:docker on centos 7   
  follow this post：https://computingforgeeks.com/installing-redash-data-visualization-dashboard-on-centos-7-fedora

python:Python 2.7.12

setting the hive datasource is all right，but can't get  hive schema. got error info ,like below:
![image](https://user-images.githubusercontent.com/10951542/55160789-11b16880-519f-11e9-95a5-86de4227a7a7.png)

ps: **we find there is no hive schema data in redis, instead mysql is appeared(mysql datsource is all right)**

error info like this:
{"log":"OperationalError: TExecuteStatementResp(status=TStatus(errorCode=40000, errorMessage=u\"Error while compiling statement: FAILED: ParseException line 1:5 cannot recognize input near 'show' 'schema' '\u003cEOF\u003e' in ddl statement\", sqlState=u'42000', infoMessages=[u\"*org.apache.hive.service.cli.HiveSQLException:Error while compiling statement: FAILED: ParseException line 1:5 cannot recognize input near 'show' 'schema' '\u003cEOF\u003e' in ddl statement:28:27\", u'org.apache.hive.service.cli.operation.Operation:toSQLException:Operation.java:323', u'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:148', u'org.apache.hive.service.cli.operation.SQLOperation:runInternal:SQLOperation.java:226', u'org.apache.hive.service.cli.operation.Operation:run:Operation.java:264', u'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatementInternal:HiveSessionImpl.java:470', u'org.apache.hive.service.cli.session.HiveSessionImpl:executeStatement:HiveSessionImpl.java:445', u'sun.reflect.GeneratedMethodAccessor114:invoke::-1', u'sun.reflect.DelegatingMethodAccessorImpl:invoke:DelegatingMethodAccessorImpl.java:43', u'java.lang.reflect.Method:invoke:Method.java:498', u'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:78', u'org.apache.hive.service.cli.session.HiveSessionProxy:access$000:HiveSessionProxy.java:36', u'org.apache.hive.service.cli.session.HiveSessionProxy$1:run:HiveSessionProxy.java:63', u'java.security.AccessController:doPrivileged:AccessController.java:-2', u'javax.security.auth.Subject:doAs:Subject.java:422', u'org.apache.hadoop.security.UserGroupInformation:doAs:UserGroupInformation.java:1866', u'org.apache.hive.service.cli.session.HiveSessionProxy:invoke:HiveSessionProxy.java:59', u'com.sun.proxy.$Proxy23:executeStatement::-1', u'org.apache.hive.service.cli.CLIService:executeStatement:CLIService.java:283', u'org.apache.hive.service.cli.thrift.ThriftCLIService:ExecuteStatement:ThriftCLIService.java:509', u'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1317', u'org.apache.hive.service.cli.thrift.TCLIService$Processor$ExecuteStatement:getResult:TCLIService.java:1302', u'org.apache.thrift.ProcessFunction:process:ProcessFunction.java:39', u'org.apache.thrift.TBaseProcessor:process:TBaseProcessor.java:39', u'org.apache.hive.service.auth.TSetIpAddressProcessor:process:TSetIpAddressProcessor.java:56', u'org.apache.thrift.server.TThreadPoolServer$WorkerProcess:run:TThreadPoolServer.java:286', u'java.util.concurrent.ThreadPoolExecutor:runWorker:ThreadPoolExecutor.java:1142', u'java.util.concurrent.ThreadPoolExecutor$Worker:run:ThreadPoolExecutor.java:617', u'java.lang.Thread:run:Thread.java:748', u\"*org.apache.hadoop.hive.ql.parse.ParseException:line 1:5 cannot recognize input near 'show' 'schema' '\u003cEOF\u003e' in ddl statement:33:6\", u'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:205', u'org.apache.hadoop.hive.ql.parse.ParseDriver:parse:ParseDriver.java:166', u'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:438', u'org.apache.hadoop.hive.ql.Driver:compile:Driver.java:321', u'org.apache.hadoop.hive.ql.Driver:compileInternal:Driver.java:1221', u'org.apache.hadoop.hive.ql.Driver:compileAndRespond:Driver.java:1215', u'org.apache.hive.service.cli.operation.SQLOperation:prepare:SQLOperation.java:146'], statusCode=3), operationHandle=None)\n","stream":"stderr","time":"2019-03-28T09:51:19.471827939Z"}

**Comment by ranbena** [comment]
Hey @xlingit, as noted in the github issue template, we use GitHub only for bug reports
but for support questions plz use https://discuss.redash.io/c/support, so go ahead and copy this over to there.

Also, plz make sure to read the v7 upgrade notes here https://discuss.redash.io/t/redash-v7-released/3477
