### ISSUE TITLE
Table UI linked to plot

### ISSUE THREAD

**Issue by chanansh** [getredash/redash#3652]
How can I draw a table so when a row is selected it behaves as a filter for a different query for line visualization?

**Comment by ranbena** [comment]
If I understand correctly you're looking for [this kind of feature](https://github.com/getredash/redash/issues/3012) which is not currently available in Redash.

But it could be implemented a bit differently with query parameters, and particularly with the "Query Based Dropdown List" parameter type. [More information in the help doc](https://redash.io/help/user-guide/querying/query-parameters).

-----------------

I'm closing this as it doesn't meet our guidelines (opening issues is for bug reporting), but feel free to use https://discuss.redash.io for assistance with any subject.
