### ISSUE TITLE
Google SSO is not available on fresh redash install

### ISSUE THREAD

**Issue by phdowling** [getredash/redash#3657]
According to https://redash.io/help/user-guide/users/authentication-options, there should be a menu option for google SSO under settings > settings. On a fresh install (using the setup.sh script) this is not the case, as of right now. How can I (re-)enable Google SSO?

**Comment by lboright** [comment]
Hi @phdowling! Did you find a solution? I have the same question.

**Comment by lboright** [comment]
I ended up following the [Google OAuth Setup](https://redash.io/help/open-source/setup) instructions to enable this feature.

**Comment by arikfr** [comment]
To enable SSO, you need to configure the OAuth API keys. Follow the link @lboright provided.
