### ISSUE TITLE
Docker image latest should always be the same as the real latest version

### ISSUE THREAD

**Issue by innovia** [getredash/redash#3663]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

When checking the available docker tags its clear that latest is not the same as the latest version.

```
preview 599 MB
Last update: 3 days ago
latest 585 MB
Last update: 6 days ago
7.0.0.b18042 585 MB
Last update: 8 days ago
```

latest is a textual tag and could cause issues when one is using it and a new "latest" is coming out.

### Steps to Reproduce

1. visit [redash docker hub](https://hub.docker.com/r/redash/redash/tags)

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?
I expect to have the commit
### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by arikfr** [comment]
The `latest` tag points at `7.0.0.b18042`:

```
$ docker pull redash/redash:latest
latest: Pulling from redash/redash
Digest: sha256:505977a414890bc0f7512242c7769050b434042ffff0b4fbd4ced297f0f763b2
Status: Image is up to date for redash/redash:latest
$ docker pull redash/redash:7.0.0.b18042
7.0.0.b18042: Pulling from redash/redash
Digest: sha256:505977a414890bc0f7512242c7769050b434042ffff0b4fbd4ced297f0f763b2
Status: Image is up to date for redash/redash:7.0.0.b18042
```

Note that they have the same digest.

**Comment by innovia** [comment]
I see it was confusing because of the days - sorry that i assumed it was pushed with another version - thanks for the info
