### ISSUE TITLE
Dashboard list resource restful api returning error when using page and page_size

### ISSUE THREAD

**Issue by danix9009** [getredash/redash#3694]
### Issue Summary

When using page and page_size of Dashboard list resource rest api ,it returns error from redash.

### Steps to Reproduce

1. using the restful api  in postman to fetch pagination of  dashboards  with page and page_size params;
2. when page = 1,it returns correct data withour error;
3. while using page =2 and suitable page_szie such as 5 when the count of dashboards is more than 5,it returns error data.

here are the screenshots:
![dashboard_list_1](https://user-images.githubusercontent.com/26785197/55858514-76f35980-5ba2-11e9-963e-d4ccc6ce79d5.png)
![dashboard_list_2](https://user-images.githubusercontent.com/26785197/55858516-76f35980-5ba2-11e9-993c-499d2279d688.png)
![dashboard_list_3](https://user-images.githubusercontent.com/26785197/55858517-76f35980-5ba2-11e9-8348-9c4d87444fa2.png)

and error info file:
[error_information.txt](https://github.com/getredash/redash/files/3062414/error_information.txt)

### Technical details:

* Redash Version: v7.0.0
* Browser/OS:Chrome/Windows 10
* How did you install Redash:as the manual in https://redash.io/help/open-source/dev-guide

**Comment by danix9009** [comment]
If someone else has met with the problem similarly, give me some advice.
That will be grateful.

**Comment by arikfr** [comment]
Based on the stacktrace it looks like one of the dashboards references a non existing `user_id`. Can you confirm this is the case?

**Comment by danix9009** [comment]
> Based on the stacktrace it looks like one of the dashboards references a non existing `user_id`. Can you confirm this is the case?

Thanks, arikfr.
But it may be not the case.I looked up all the dashboards data in the database,and tried to fetch all dashboards by one request from the rest api, and they both returned with the user_id.

**Comment by danix9009** [comment]
I don`t know whether the environment made the case,here are some details about my env :
python version : 2.7.5
docker version : 18.09.1
docker-compose version : 1.23.2
nodejs version : 8.0.0
npm version : 5.0.0

**Comment by arikfr** [comment]
Can you show the result of:

```sql
select distinct user_id from dashboards
```

and:

```sql
select id from users
```

**Comment by danix9009** [comment]
It`s very kind of you to help me, arikfr.
I found the reson a moment ago,
when I use the api with the 'order' parameter with the request, it goes well with nothing error. I don`t understand why made this.

And the two select query results both return 1 row with value 1.

**Comment by arikfr** [comment]
And when you don't use the order parameter it fails?

**Comment by danix9009** [comment]
Yes

**Comment by arikfr** [comment]
About the query, can you try the following as well:

```
select user_id from dashboards
```

Let's make sure all rows actually have a value.

**Comment by danix9009** [comment]
It returns that all rows have a value,  and i use 
    select count(user_id) from public.dashboards;
the value  equals the rows num.
