### ISSUE TITLE
Embedded visualizations with parameters: data loading issues

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3719]
* When one of the parameters is missing a value --
  Current behavior: a generic error message is shown.
  Expected behavior: ~~either~~ show input for missing parameter ~~or show a meaningful error message~~.

* When changing parameter value, it tries to load new results but if they don't exist, it doesn't seem to poll for results.
  Expected behavior: show spinner and poll until there is a result.

~~Unlike parameters in in-app context, here when you change parameter value it tries to load a result. I'm not sure if we should implement this until we have implemented #2316. 🤔 WDYT? (cc: @ranbena)~~ On second thought, let's move on with this and hopefully #2316 will be implemented soon.

**Comment by rauchy** [comment]
@arikfr regarding the second part - are you sure it's wise to proceed with this with #2316 in pretty advanced stages? Perhaps I should branch out of #2316?
