### ISSUE TITLE
Front-end doesn't guess data types

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#3731]
### Issue Summary

After reading through #3553 I expected the front-end to accurately parse an ISO8601 date from a text-field. But it doesn't. If I select a bunch of ISO8601 dates as text fields from the database, Redash should let me reformat them using format codes. 

### Steps to Reproduce

I created an example on the redash demo instance [here](http://demo.redash.io/queries/7971). You can reproduce on your own in Postgres with a query like this:

```SQL
SELECT CAST(any_date_field as VARCHAR(50)) FROM table_of_your_choice
```

If you try to edit the table visualization to render a date field as MMM-YYYY or something similar it will not work.

### Technical details:

* Redash Version: 7.0.0
* Browser/OS: Safari, Chrome, Firefox
* How did you install Redash: SaaS

**Comment by kravets-levko** [comment]
@susodapop Can you please provide data sample? Redash does guess date/time types, but it expects two formats (`d` is for any digit): string that starts with pattern `dddd-dd-ddT` - for date/time, and string that matches pattern `dddd-dd-dd` - for date. `CAST` will convert date/time filed to a bit different format: `2019-01-25 15:40:47+00` - notice that `T` is missing there. If you'll change your SQL to something like

```sql
SELECT REPLACE(CAST(any_date_field AS VARCHAR(50)), ' ', 'T')
FROM table_of_your_choice
```
it will work fine.

**Comment by susodapop** [comment]
Thanks @kravets-levko! Closing this issue as resolved.
