### ISSUE TITLE
Exporting data should returns SQL types and not python types

### ISSUE THREAD

**Issue by lohxx** [getredash/redash#3736]
### Issue Summary

When I export the result of a select, the primitive types returned are those of Python and not those of sql, booleans usually come as False/True rather than false/true.

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. Select data from any table
2. Export the data.

### Technical details:

* Redash Version: 7.0.0+b17535 (15c815fb)
* Browser/OS: Chrome/Ubuntu
* How did you install Redash:

**Comment by arikfr** [comment]
By exporting you mean downloading a CSV?

**Comment by lohxx** [comment]
Yes
