### ISSUE TITLE
How Can i run redash in docker stack ?

### ISSUE THREAD

**Issue by sagarpandav** [getredash/redash#3738]
I am using the same docker-compose.yml file for deploying redash in docker stack. But getting lots of error and unsupported commands warning. Can anyone help ?

**Comment by Feeeenng** [comment]
Please try to read [setup](https://github.com/getredash/redash/tree/master/setup) !

**Comment by arikfr** [comment]
For support and usage questions, please use the [forum](https://discuss.redash.io).

Thanks.
