### ISSUE TITLE
Cassandra support

### ISSUE THREAD

**Issue by jippi** [getredash/redash#375]
Hi,

Is there any plans to add support for Cassandra as a data store? :)

**Comment by arikfr** [comment]
Datastore to query or for re:dash's own metadata?

**Comment by jippi** [comment]
Datastore to query  on :)

Idealy also meta-data

**Comment by arikfr** [comment]
Datastore: no concrete plans, but adding it should be possible and relatively easy. I will keep this issue open in case someone wants to take a stab at it.

But using Cassandra for metadata won't happen, as it will complicate the initial setup of the tool.

**Comment by jethroborsje** [comment]
To  bad this issue is closed.

**Comment by arikfr** [comment]
@jethroborsje I'm not sure why @jippi closed this issue, but I still will be happy to see a query runner for Cassandra.

**Comment by jippi** [comment]
i closed it because I don't need it (not using redash) and was cleaning up old tickets on my account

**Comment by arikfr** [comment]
For anyone following, Cassandra support was implemented in #1236.
