### ISSUE TITLE
Visualization rendering getting cut in editor on first load

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3753]
1. Open this URL: https://redash-preview.netlify.com/queries/36#62
2. Click on "Edit Visualization".

You will see that the visualization in the editor is cut on the left side:

![image](https://user-images.githubusercontent.com/71468/57020673-b1489780-6c32-11e9-820b-baf0510d77a0.png)

If you switch to a different visualization tab and then back to this one, it gets resolved.

**Comment by kravets-levko** [comment]
Thanks! I think it's because of dialog animation :thinking:

**Comment by arikfr** [comment]
@kravets-levko let's try to solve this this week.
