### ISSUE TITLE
Schema refresh failed. Please try again later.

### ISSUE THREAD

**Issue by zouyu1114** [getredash/redash#3779]
I created the data sources of hive and mysql, and found that all the prompt schema refresh failed to query the data. My version is 6.0.0

How to deal with it?

**Comment by wangycc** [comment]
How to solve it?

**Comment by yaoyufa** [comment]
I connected clickhouse today, and the error of "Schema refresh failed" keeps appearing. I am not clear about the problem, can you help me to solve it?

**Comment by dingmy002** [comment]
i have the same problem，how can i fix it

**Comment by susodapop** [comment]
👋 @dingmy002 , we use the issue tracker exclusively for bug reports and planned work. However, this issue appears to be a support request. Please use our [forum](discuss.redash.io) to get help.
