### ISSUE TITLE
Content Security Policy error because of inline script

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#3816]
### Issue Summary

@ranbena @arikfr The change in #3609 leads to a Content Security Policy error when loading any page:

Chrome:

```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-lUaehHefE2UfaxjnDzUj5HBFcQ3z+oaNbFFBqOJn9Ck='), or a nonce ('nonce-...') is required to enable inline execution.
```

Firefox:
```
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).
```

I don't think we should add `unsafe-inline` to the `script-src` directive but instead indeed provide a per-request nonce in the format

```
<script nonce="<random nonce>">
    //...
</script>
```

Flask-Talisman supports rendering a random nonce like [shown in the example here ](https://github.com/GoogleCloudPlatform/flask-talisman#example-6). Sadly we can't just not apply CSP since the templates are used on every page, if I understand correctly.

Right now `multi_org.html` is the only one that is rendered via Jinja2, but I think it's safe to do that for `index.html`, right?

Alternatively, would it suffice to move the `<script>` block into an own script that we can load instead?

Can you think of a way to fix this?

### Steps to Reproduce

1. Open any page.
2. See the browser console.

### Technical details:

* Redash Version: master
* Browser/OS: Firefox/macOS
* How did you install Redash: Docker

**Comment by arikfr** [comment]
Both options are not great:

* Rendering with Jinja -> couples the frontend with the backend, which we want to avoid.
* Moving this script to its own file -> makes page load slower.

What if we move it to its own file, but also move it to the body section? @ranbena

**Comment by jezdez** [comment]
(sorry for the typos)

**Comment by ranbena** [comment]
> What if we move it to its own file, but also move it to the body section? @ranbena

Relocating the script into `body` won't improve perf. Scripts are synchronous by default no matter where in the document they are declared.

Options:
1. We can generate the nonce and use it hardcoded to avoid relying on a server. I don't see us changing this script anytime soon so it might be good enough.
2. We can explicitly set `async` on the script for optimal loading perf but then we won't be able to use the IE conditional comment (it expects `onIE()` to already exist). I think this can be worked around with more useragent parsing.
3. We can explicitly set `defer` on the script, so it loads after document is ready but it may not run if previous scripts generate an error, which is expected if browser is IE. I'm not certain of this though.

**Comment by arikfr** [comment]
> We can generate the nonce (a hash of the script content) and use it hardcoded to avoid relying on a server. I don't see us changing this script anytime soon so it might be good enough.

The nonce should be randomized on every request or otherwise it serves no purpose :) 

Is there some good reference on why having script tags is a security concern?

**Comment by ranbena** [comment]
> The nonce should be randomized on every request or otherwise it serves no purpose :)

I meant "hash-source" `<hash-algorithm>-<base64-value>` which isn't nonce.
```
Content-Security-Policy: script-src 'sha256-B2yPHKaXnvFWtRChIbabYmUBFZdVfKKXHbWtWidDVF8='
```
More info [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src)


> Is there some good reference on why having script tags is a security concern?

I would reckon it has to do with the risk of 3rd party modification like browser extensions.

**Comment by arikfr** [comment]
The `hash-source` option seems as the best one, no?

**Comment by ranbena** [comment]
> The hash-source option seems as the best one, no?

Apparently, his feature ([SRI](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity)) is only available for external file fetches. 

I'll attempt the 2nd option then.

**Comment by jezdez** [comment]
Thanks @ranbena!
