### ISSUE TITLE
Version 7.0.0.b18042  Bar Chat & Pie Chart Display Bug

### ISSUE THREAD

**Issue by ngloom** [getredash/redash#3829]
### Issue Summary

Bar Chat and Pie Chart display Bug. 

### Steps to Reproduce

1. create a bar chat or pie chart, the data label show 0 when it's obviously not 

### Technical details:

* Redash Version: 7.0.0.b18042  Docker Version 
* Browser/OS: Ubuntu18.04
* How did you install Redash: via Docker Setup Script

screen shot:

![bar chat](https://user-images.githubusercontent.com/495831/58301997-6f6ad580-7e1b-11e9-8829-f6cf741ff0cd.png)
![pie chart](https://user-images.githubusercontent.com/495831/58302043-9e814700-7e1b-11e9-85fe-b7792c6da629.png)

Btw, Thanks for the  **Great Work**  guys, really save my time.

**Comment by ranbena** [comment]
@ngloom thanks! :)

It would be really helpful if you could reproduce this on our [Preview instance](http://redash-preview.netlify.com).
Also, do you know if this was ok in a previous Redash version?

**Comment by ngloom** [comment]
@ranbena thanks for your replay

**Comment by ngloom** [comment]
@ranbena Thanks for your reply, 
with some experience I find that when there's 0 value in the Y Value, it will lead to Pie Chart & Bar Chart's data label display bug,  for example , the value of 120  ,124 is 0
![image](https://user-images.githubusercontent.com/495831/58392893-b7ce0180-806e-11e9-9437-e61634f4439f.png)
when i remove the zero value , everything will be ok 
![image](https://user-images.githubusercontent.com/495831/58392967-0a0f2280-806f-11e9-9667-4358320e0663.png)


PS, I didn't reproduce this bug in your Preview Instance, it works well there. 

And I'm a fresh man of Redash,  7.0.0.b18042 is my first try version.
I find that you're using Version 7.0.0+b21390 in the preview instance , maybe I should have a try with that version. 





Thanks

**Comment by arikfr** [comment]
I don't think it's version related. Can you share the query result you're
visualizing in csv form?

**Comment by ngloom** [comment]
hi, @arikfr thanks for your advise, and now I find what's going wrong now.
the database I got has multi-value on some key and that's root case of my problem, i'll go to the data guy to fix it. 
Thanks again for your patient. @arikfr  @ranbena

**Comment by arikfr** [comment]
👍
