### ISSUE TITLE
Alerts won't work for parameterized queries

### ISSUE THREAD

**Issue by rhnasc** [getredash/redash#3833]
### Issue Summary

Alerts created for parameterized queries don't leave the UNKNOWN state.

### Steps to Reproduce

1. Create a query with any parameters

On a local environment, `select * from users where id = {{ user_id }}` should suffice for a data source referring to the redash's own database (`postgresql://postgres@postgres/postgres`).

2. Create an alert

Create an alert pointing to the query you just created, with any name or operation. Short rearm will help for quick debug (1 second).
 
Now, the alert will remain as UNKNOWN, even if you re-run the query multiple times.

### Technical details:

* Redash Version: local environment running on latest release ([v7.0.0](https://github.com/getredash/redash/releases/tag/v7.0.0))
* Browser/OS: Chrome/MacOS
* How did you install Redash: following [docker-based developer installation](https://redash.io/help/open-source/dev-guide/docker)

On a quick debug, we noticed that the problem might be that the [store results method](https://github.com/getredash/redash/blob/af168c69b95cf466558c2eaa8a753ffb7ec95805/redash/models/__init__.py#L296) does not return all the **updated_query_ids**, which would be finally used for reevaluating the alerts on the [check_alerts_for_query method](check_alerts_for_query).

This happens when the query hash being evaluated differs from the hash stored on the database, after parameters have been replaced.

**Comment by arikfr** [comment]
Thank you for reporting this, but it's actually a documented behavior, that parameterized queries are not supported with alerts. This won't be supported until:

1. Alerts have their own schedule.
2. We add the UI to pick parameter values for the alert.

**Comment by rhnasc** [comment]
Hey arikfr, that makes sense! What do you think of adding a notice on the Alerts creation page to prevent the user from falling into this limitation? From my experience both this limitation, and also the fact that only the first row of results is evaluated, are not clear to the end user.

**Comment by arikfr** [comment]
That's definitely a good idea! I would wait until the alert page migrated to React before doing so though.

Arik
