### ISSUE TITLE
When opening a dashboard, each widget uses its own default value

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3849]
### Issue Summary

Current behavior: when opening a dashboard, each widget uses its own default value.

Expected behavior: a single value will be picked and used for all widgets.

### Steps to Reproduce

Visit: https://redash-preview.netlify.com/dashboard/wrong-parameter-example. Note that the parameter value is "value1", but the second widget is actually using "value2":

![image](https://user-images.githubusercontent.com/71468/58582289-13101780-825a-11e9-8e1b-6fba73ddea5f.png)

**Comment by kravets-levko** [comment]
@arikfr I'll take it tomorrow

**Comment by ranbena** [comment]
I fiddled with it and can't reproduce it now :/
@arikfr what's the STR?

**Comment by arikfr** [comment]
@ranbena just open the link in the issue, it will reproduce immediately. Once you opened it, it will update the value in the url, so if you refresh the page it will work properly.
