### ISSUE TITLE
Autoheight widgets miscalculating height

### ISSUE THREAD

**Issue by ranbena** [getredash/redash#3859]
### Issue Summary

Comparing version 7 with current master, it's apparent that autoheight table visualization widgets are higher now by 1 row.

Version 7 | Master branch
----------|---------------
<img width="633" alt="Screen Shot 2019-05-30 at 19 22 17" src="https://user-images.githubusercontent.com/486954/58675760-fa176d00-8312-11e9-8bde-4958f44d52a2.png"> | <img width="633" alt="Screen Shot 2019-05-30 at 19 22 02" src="https://user-images.githubusercontent.com/486954/58675761-fedc2100-8312-11e9-884d-7727a9e1e307.png">

### How come?
#3830 added a 10px bottom padding to tables but with -10px margin to compensate*.
Thing is, autoheight is calculated with `getBoundingClientRect()` which understandably includes padding but not margin, thus adding 10px to the visualization height - resulting in an additional grid row.

\* Mac only - therefore not detected by e2e tests 😓

**Comment by ranbena** [comment]
I'm thinking we should revert #3830 - it's a workaround for a browser bug (btw, happens to me on GH code blocks as well..) and I feel no obligation to keep it.

@arikfr @kravets-levko @gabrieldutra any better ideas?

**Comment by arikfr** [comment]
@ranbena while I agree with your sentiment towards #3830, the problem is that sometimes it really blocks the content and makes it impossible to read. I couldn't reliably reproduce it and in most cases it was fine, but I can see how frustrating it can be when it does happen.
