### ISSUE TITLE
Add  some options to limit ddl action , that's dangerous query role change datas by sql

### ISSUE THREAD

**Issue by Simple701** [getredash/redash#3860]
Add  some options to limit ddl action , that's dangerous query role change datas by sql 
We need this ，very very need 。。。
I plan to add some limit codes by myself when my time is ok

**Comment by arikfr** [comment]
I understand the concern, but you can solve this using your database's ACL - just apply the needed restrictions to the user you use for Redash. 

If you still think it's relevant to have such limits in Redash, you're welcome to open a thread to discuss it in the forum (discuss.redash.io).
