### ISSUE TITLE
Widget menu shows up on public dashboard when it shouldn't

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3862]
### Issue Summary

Current: widget menu shows up on public dashboard.
Expected: it shouldn't be visible on shared dashboards.

### Steps to Reproduce

1. Visit: https://redash-preview.netlify.com/public/dashboards/ArmGcXjgyzjgR4Nq2eOxXVJTKY05cOKkywam6czM
2. Hover over the widget.
3. The top-right menu will show up.

**Comment by kravets-levko** [comment]
@arikfr That menu contains only two items (Download CSV/XLSX), and nothing has changed to it since v4 (at least). Are you sure that this menu should be completely hidden on public dashboards?

**Comment by arikfr** [comment]
@kravets-levko those two items don't work on a public dashboard and we never showed this menu on a public dashboard before (you can see on app.redash.io, which still runs older codebase).
