### ISSUE TITLE
Horizontal legend overlaps chart on small screens

### ISSUE THREAD

**Issue by brylie** [getredash/redash#3879]
When viewing a chart with a small container width (<= 600px perhaps), the chart legend is configured to switch to horizontal mode. When the legend displays in horizontal mode, it can be seen to overlap the chart, particularly when there are several legend items:

![Screenshot_20190605_145026](https://user-images.githubusercontent.com/17307/58954353-a210b880-87a1-11e9-94c4-227ba3640066.png)

## Steps to Reproduce

1. Create a chart (e.g. editing it in the Visualization Editor)
2. Ensure legend is visible
3. resize the chart container to < 600 px (e.g. by resizing the browser screen or opening devtools)

I believe the legend should not overlap the chart, as it can hide information.

### Technical details:

* Redash Version: 6.x
* Browser/OS: Kubuntu 19.04, Firefox 67
* How did you install Redash: Git in development version

**Comment by kravets-levko** [comment]
I reproduced it only in FF, in Chrome/Chromium it works fine (Ubuntu 18.04). Space for legend is reserved under the plot, but legend has wrong position (not sure why).

**Comment by kravets-levko** [comment]
@brylie I submitted a fix for this issue (getredash/redash#3882) - can you please check if the bug has gone? 

P.S. Tip: there is a deploy preview link below the PR.

**Comment by brylie** [comment]
Thanks @kravets-levko!
