### ISSUE TITLE
Datasource is created with empty SSL mode

### ISSUE THREAD

**Issue by rauchy** [getredash/redash#3885]
### Issue Summary

When you create a new PG datasource, modify the default SSL mode and delete it before submission, the SSL mode value sent over is "". It should be absent from the request. This is most likely not specific to this scenario, but since I didn't investigate yet, I'm leaving this issue as concrete as possible and not generalizing.

### Steps to Reproduce

1. Create a new Postgres data source
2. Fill in whatever you'd like as SSL mode
3. Clear the text box
4. Submit the form - the SSL mode sent is "".

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by arikfr** [comment]
I think you're correct that it's not a specific pg issue.

**Comment by rauchy** [comment]
Obviously, this happens on every field. I suspect [this](https://github.com/react-component/form/blob/master/src/createBaseForm.js#L126) as the culprit. Wondering if a backend fix will be easier.

**Comment by arikfr** [comment]
We used to have a solution for this on the frontend. I guess having it on the backend is more robust/future proof?

**Comment by rauchy** [comment]
#3886 also does the trick, but I will leave it to my esteemed colleague @gabrieldutra to judge.

**Comment by gabrieldutra** [comment]
This will do for DynamicForm. However, I guess there are other parts containing Forms with optional input values where this could happen too. I also assume that this is an issue to all those places, so one question: should `null` values also not be sent? (this doesn't seem to happen for DynamicForm, but can happen in other scopes).
