### ISSUE TITLE
redash_adhoc_worker eats CPU massively 

### ISSUE THREAD

**Issue by koooge** [getredash/redash#3891]
### Issue Summary
Hi there. redash_adhoc_worker sometimes becomes CPU eater and redash cannot work normally. When it becomes so, I reboot the machine to recover it, but it would not smart. So, I suppose redash needs to handle something adequately. Do you have any ideas?

```
$ docker stats

CONTAINER ID        NAME                        CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
...
9ab7f894ad7d        redash_adhoc_worker_1       144.48%             400.8MiB / 3.794GiB   10.31%              4.11GB / 2.6GB      370MB / 147kB       3
...
```

![Screen Shot 2019-06-10 at 12 34 34](https://user-images.githubusercontent.com/7419215/59171587-9268e980-8b7e-11e9-81e9-b90d8632c866.png)

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 7.0.0+b18042
* Browser/OS: chrome
* How did you install Redash: EC2 (t3.medium) with AMI

**Comment by arikfr** [comment]
It's probably enough to restart the Docker container instead of the whole machine.

But it's worth understanding what's going on. What types of data sources are you using? How often does this happen?

**Comment by koooge** [comment]
rds_mysql, dynamodb or python (REDASH_ADDITIONAL_QUERY_RUNNERS=redash.query_runner.python). Actually I don't know what query does it cause because some users use this redash;

>  How often does this happen?
maybe 1 per 2week~month

**Comment by ranbena** [comment]
@koooge try this out #3903.

**Comment by koooge** [comment]
Thanks @ranbena ! It's not easy to ensure not to occur this. I close this issue since #3903 was merged. I will reopen this if it reproduces (it would be redash 8).
