### ISSUE TITLE
scheduled query become outdated query

### ISSUE THREAD

**Issue by srajakum** [getredash/redash#3901]
Redash queries that are scheduled to run are going into the "outdated queries". 
![outdated](https://user-images.githubusercontent.com/13073690/59371379-785c1200-8d0a-11e9-9fcb-3f5107841243.JPG)
Then these queries are moved into "Queries waiting" and never got executed. 
![queries-waiting](https://user-images.githubusercontent.com/13073690/59371399-86119780-8d0a-11e9-89ae-bbad82fc6514.JPG)

The same query when executed directly are executed ok.
I am using redash version 2.0.1

**Comment by rauchy** [comment]
Hi @srajakum, thanks for reporting.

Redash 2.0.1 is quite dated, have you tried upgrading? If this problem persists, please reach out in [the forums](https://discuss.redash.io), as we don't use GitHub issues for support.
