### ISSUE TITLE
Save query only when actually updating the schedule and not on OK

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3918]
Currently when you open the query schedule dialog and click on OK, it will save the query - even if no changes were made. This updates the query's `updated_at` timestamp and makes it hard to track when it was really changed.

Expected behavior: if no changes to the schedule were made, don't save the query even if OK was pressed.

**Comment by ranbena** [comment]
Actually, the schedule dialog is already set to save only if changed:

https://github.com/getredash/redash/blob/cfafa972186f3cfc4587987b286231b3afe88869/client/app/components/queries/ScheduleDialog.jsx#L181-L189

But I think it wasn't adapted to `schedule = null` after https://github.com/getredash/redash/issues/3341.
