### ISSUE TITLE
import python library in redash get error

### ISSUE THREAD

**Issue by Amirashaker** [getredash/redash#3926]
after add python as data source in redash when write python code and import mysql.connector module get error 
this is my code that i wrote in redash 
def read_sql(): 
    import mysql.connector
    mydb = mysql.connector.connect(
           host="localhost",
           user="root",
           passwd="123speakol",
           database="testing")
    mycursor = mydb.cursor()
    mycursor.execute("select hour,sum(temperature) as temperature ,sum(wind_speed) as wind_speed from weatherdaat group by hour")
    myresult = mycursor.fetchall()
    for x in myresult: 
       print(x[0],x[1],x[2])
read_sql()

getting me this error:
Error running query: <type 'exceptions.AttributeError'> 'module' object has no attribute 'connector'

**Comment by arikfr** [comment]
I guess it imports `redash.query_runner.mysql` and not what you expect.

Anyway, this looks like a usage issue and not a problem with Redash. If you still need help with this, I'll appreciate if you open a thread in our forum: https://discuss.redash.io/c/support/support-self-hosted.

Thanks.
