### ISSUE TITLE
install on docker has some problem

### ISSUE THREAD

**Issue by ghoiufyia** [getredash/redash#3929]
today is 2019.06.25,i want install redash on docker,it shows exception like last:
Removing intermediate container 39dc41a08956
 ---> 0e2bbccf9bc4
Step 5/18 : COPY client /frontend/client
 ---> de8689b155a6
Step 6/18 : COPY webpack.config.js /frontend/
 ---> 3a22ab9f7bdd
Step 7/18 : RUN npm run build
 ---> Running in 344f249329ba

> redash-client@8.0.0-beta build /frontend
> npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack

> redash-client@8.0.0-beta clean /frontend
> rm -rf ./client/dist/

Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! redash-client@8.0.0-beta build: `npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the redash-client@8.0.0-beta build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-25T10_07_54_402Z-debug.log
ERROR: Service 'server' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 137

but when i set docker's memory to 4 GBit,it go well.
The other one is that i add a datasource ,type is postgresql.the query show some question as below:
Error running query: relation "athm.car_test_drive" does not exist.
thanks!

**Comment by kishandonepudi** [comment]
> 👋 @ghoiufyia, we use the issue tracker exclusively for bug reports and planned work. However, this issue appears to be a support request. Please use [our forum](https://discuss.redash.io) to get help.

IM GETTING SAME ISSUE Can i know where can i get answer in support , can i have any link?

**Comment by ranbena** [comment]
@kishandonepudi here's the link to the support forum https://discuss.redash.io/
