### ISSUE TITLE
Enabling or disabling "Use Dashboard Level Filters" cause widgets to show reload spinner forever

### ISSUE THREAD

**Issue by justinclift** [getredash/redash#3937]
### Issue Summary

When the "Use Dashboard Level Filters" checkbox is turned on, or turned off, the widgets in the dashboard then appear to attempt reloading, showing their spinner.

Unfortunately, this never finishes, with the spinner just keeping going... forever.

![Redash_bug-report-20190628 1](https://user-images.githubusercontent.com/406299/60281670-b2ebbe80-9948-11e9-9a94-ae6fb2dc5ec1.png)

### Steps to Reproduce

1. Create a new dashboard, adding any widget, then save it (Apply Changes).
2. Edit the widget, then enable "Use Dashboard Level Filters".  The bug happens here.

Interestingly, going to another screen and coming back works.  The dashboard appears fine, with the widgets loaded.

Even saving the new "enabled" state of the dashboard (when the widgets are still spinning), then coming back to it doesn't appear to have hurt anything.  The dashboard loads fine, with the widgets showing ok.

The problem appears to be solely something to do with the widget reloading when the checkbox is changed.

### Technical details:

* Redash Version: 7.0.0+b18042 (4a978bad) 
* Browser/OS: 67.0.4 (64-bit), and Firefox 60.7.0esr (64-bit), both on CentOS 7
* How did you install Redash: via Docker in a local VM

**Comment by ranbena** [comment]
10x @justinclift!
Does this repro on master tho? The dashboard has undergone profound changes since v7.

(You can always test master on our Netlify Preview https://redash-preview.netlify.com)

**Comment by justinclift** [comment]
Yep, seems to:

![Redash_bug-report-20190628 2](https://user-images.githubusercontent.com/406299/60285920-fbf44080-9951-11e9-8fb0-dea7dc32afca.png)

**Comment by ranbena** [comment]
I tested on some earlier previews and it repro'd on all (stopped at Jan '19).
So either it's a backend issue, or a long running frontend bug.

@arikfr @kravets-levko any insights?

**Comment by kravets-levko** [comment]
@ranbena This is definitely a bug. I'll take it

**Comment by justinclift** [comment]
Looks good.  The bug is no longer present when testing it on the Netlify Preview instance. :smile:
