### ISSUE TITLE
Cancel on navigation warning borks app

### ISSUE THREAD

**Issue by rauchy** [getredash/redash#3947]
### Issue Summary

After editing the source of a query and navigating elsewhere, a warning dialog pops up to prevent you from losing changes. If you hit Cancel, site becomes pretty much unusable.

### Steps to Reproduce

1. Create a new query
2. Insert some text to it
3. Navigate elsewhere (say, to "Queries")
4. Hit "Cancel" in the warning dialog
5. Cry as everything turns into lava.

![cancel](https://user-images.githubusercontent.com/289488/60576828-d23e7d80-9d86-11e9-9f17-86b928c9529e.gif)

### Technical details:

* Redash Version: 7.0.0+bca4cb0e
* Browser/OS: Chrome 75

**Comment by arikfr** [comment]
I think this is an issue on our SaaS fork and no longer happens in upstream.
