### ISSUE TITLE
Static files not found

### ISSUE THREAD

**Issue by Ozencb** [getredash/redash#3969]
I am having trouble with loading some files like jquery.js and icons. I have followed the instructions on Docker Dev Guide 1 and apart from some problems with CRLF/LF linebreaks it all went smoothly. Server is up and running at port 5000 and webpack is running at port 8080. But, some elements on initial setup page on port 5000 will not load and I am getting the errors below in the attached image; page on port 8080 works just fine. Also, I built with `npm run build` before starting it.

I am pretty new to this whole scene so I might have done something obvious that should not have been done but I have tried everything I knew and this seems like a bug.

I am using Windows 10. Node and npm is up-to-date.

![eedb1d121bf298f2ec10cc2c07d26a9287c552bc](https://user-images.githubusercontent.com/18405305/60968406-a7739c80-a325-11e9-8ec9-ee062f87290d.png)

![77d7e49e302da6edb337a47174b2f249579bdc81](https://user-images.githubusercontent.com/18405305/60968504-e99cde00-a325-11e9-98a1-9d96f2e9142f.png)

**Comment by arikfr** [comment]
As this is a setup issue, let's continue the conversation in the forum thread you created: https://discuss.redash.io/t/static-files-not-found/4140/4

Thanks.
