### ISSUE TITLE
Legend overlaps plot on small screens

### ISSUE THREAD

**Issue by justinclift** [getredash/redash#3975]
## Issue Summary

When a visualisation is displayed in a very small screen size, then clicked upon, the legend moves to overlap the main chart content.

### Chrome 75 (Win 7)
![redash-legend_overlaps_content-chrome 1](https://user-images.githubusercontent.com/406299/61122604-940f2f80-a4e5-11e9-9fa6-519cb63334fa.png)
### Firefox 68 (Linux)
![redash-legend_overlaps_content-firefox 1](https://user-images.githubusercontent.com/406299/61122605-940f2f80-a4e5-11e9-80d1-e0dc2c1dcfd4.png)

Url to try with:  https://app.redash.io/default/embed/query/226021/visualization/384887?api_key=BHrjoUJrFxMCyfRe6M6dZXA1hO5qy7wSeQEVadjo&p_Date=2012-12-14

### Steps to Reproduce

1. Go to https://app.redash.io/default/embed/query/226021/visualization/384887?api_key=BHrjoUJrFxMCyfRe6M6dZXA1hO5qy7wSeQEVadjo&p_Date=2012-12-14
2. Resize the browser window to be extremely small (as per screenshots)
3. Click on the chart.  The legend now moves position, covering the chart.

Covering the chart like this should not happen.

### Technical details:

* Redash Version: Our hosted SaaS version
* Browser/OS: Firefox 68 on Linux, and Chrome 75 on Win 7
* How did you install Redash: n/a

**Comment by justinclift** [comment]
As a data point, this may be related to https://github.com/getredash/redash/pull/3882

**Comment by kravets-levko** [comment]
@justinclift Thanks a lot! Yes, it's the same bug, but it appears under other conditions. I'll try to fix it ASAP.
