### ISSUE TITLE
Docker build failed [Mac]

### ISSUE THREAD

**Issue by tinyms** [getredash/redash#3977]
> redash-client@7.0.0 clean /frontend
> rm -rf ./client/dist/

Killed
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! redash-client@7.0.0 build: `npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack`
npm ERR! Exit status 137
npm ERR! 
npm ERR! Failed at the redash-client@7.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-07-13T04_15_00_242Z-debug.log
ERROR: Service 'server' failed to build: The command '/bin/sh -c npm run build' returned a non-zero code: 137

**Comment by ranbena** [comment]
:wave: @tinyms, we use the issue tracker exclusively for bug reports and planned work. However, this issue appears to be a support request. Please use [our forum](https://discuss.redash.io) to get help.

**Comment by ranbena** [comment]
(you can find similar issues by searching "npm run build error" in the forum)
