### ISSUE TITLE
Shared dashboard footer should be always aligned to the bottom

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#3980]
When loading a public dashboard, before there is content to show, this is what the user sees:

![image](https://user-images.githubusercontent.com/71468/61221161-8b566d80-a720-11e9-9696-84913ff21632.png)

1. We need to align the footer to the bottom, even when there is no content.
2. Add some loading indicator.

**Comment by ranbena** [comment]
Is this happening in current master? How do I repro?

**Comment by arikfr** [comment]
Yes. To reproduce you either add a delay in the time it takes to load a dashboard, or just comment out the following line:

https://github.com/getredash/redash/blob/51d8131db5d10e8bfe2dda8fddb6f970017cb08b/client/app/pages/dashboards/public-dashboard-page.js#L62
