### ISSUE TITLE
SSL : Certificate verify failed

### ISSUE THREAD

**Issue by Michae94** [getredash/redash#3999]
### Issue Summary

Problem while trying to get connexion with Redis : SSL Certificate verify failed (OS : Redhat, Linux)
Redis is on the IBM cloud

### Steps to Reproduce

1. I added in my .env file (I modified username and password):
**REDASH_REDIS_URL = rediss://$USERNAME:$PASSWORD@c7b2fac8-b71e-4936-a9a4-47fa7b461b47.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:30684/0**
2. When I try to use
_bin/run ./manage.py runserver --debugger --reload_
I get the following error when I try to connect to the URL http://127.0.0.1:5000/ 
**ConnectionError: Error 1 connecting to c7b2fac8-b71e-4936-a9a4-47fa7b461b47.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:30684. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726).**

I tried to put ssl_ca_certs="./path_to_cert.pem" in the __init__.py file in redash folder, certificate that I got from my Redis app on IBM cloud. 
I also tried to put ssl to false but it doesn't work (unable to connect).

Any idea?

### Technical details:

* Redash Version: V7
* Browser/OS: Redhat Linux (RHEL 8.0)
* How did you install Redash: on a VM (Virtualbox), developer install

**Comment by arikfr** [comment]
Support for Redis and SSL was implemented in #3848. Which was after the v7 release. It is going to be introduced in the next release of Redash. If you are using Docker, you can use the preview images to run the next release already.

**Comment by Michae94** [comment]
Thank you for your answer. I just pulled the last commit from master branch (which contains the modifications implemented in #3848 ) and I still have the same problem. 
I am not using docker because I try to implement it in the IBM cloud.
