### ISSUE TITLE
Dashboard refresh button doesn't animate on first dashboard load

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4021]
### Issue Summary

When you open a dashboard the refresh button doesn't animate when loading the widgets.

**Comment by ranbena** [comment]
Cause it's not refreshing - it's loading. That's not what the refresh button does.

**Comment by arikfr** [comment]
Tomato, Tomahto :-)

**Comment by ranbena** [comment]
Loading brings up cached responses while refreshing executes all widgets.
It's a profound difference.

**Comment by arikfr** [comment]
This is a good point. Although in some cases it will execute all or some of the widgets on first load a swell. 

It might mean that we need a separate indicator that says "dashboard is currently loading" (either first load or refresh) that is separate from the button?

**Comment by ranbena** [comment]
> It might mean that we need a separate indicator that says "dashboard is currently loading" (either first load or refresh) that is separate from the button?

I don't see a reason to, cause each widget has it's own separate and very prominent loading indicator. The page does not look static and therefore requiring a special indication imho.

**Comment by arikfr** [comment]
> cause each widget has it's own separate and very prominent loading

What if the widgets loading are not in view?

**Comment by ranbena** [comment]
Then I'm not certain that it matters as they are offscreen.
(In the near future, I hope to introduce lazy-loading widgets which makes this even more redundant)

**Comment by arikfr** [comment]
:+1:
