### ISSUE TITLE
Redash cancel button not working

### ISSUE THREAD

**Issue by sarah97** [getredash/redash#4030]
### Issue Summary

Redash runs just fine for us on a kubernetes cluster. We have set up one of our data sources as Athena, and we have given the IAM role for redash full athena permissions, however canceling a query in redash just isn't working. The button just grays out and either query results will come back or someone has to cancel the query in the AWS console.

There are no logged errors which is the frustrating part. 

### Steps to Reproduce

1. Start a Athena query
2. Press cancel in the radash UI

### Technical details:

* Redash Version: version 7.0.0+b18042
* How did you install Redash: docker

**Comment by arikfr** [comment]
In V7 cancel was dependent on Celery's behavior, which if busy, might ignore cancels. In V9 we replaced Celery with RQ, which even if doesn't fix some of the issues we used to have gives us better chance at finding them.
