### ISSUE TITLE
Counter Target Value formatting doesn't match Counter Value

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#4031]
### Issue Summary

Potentially related to #2558. When I configure a number format for a counter, the Target Value doesn't follow the formatting rule.

### Steps to Reproduce

1. Create a counter
2. Format the counter value (two decimal places, `$` prefix
3. Add a Target Value

![image](https://user-images.githubusercontent.com/17067911/62317593-a2ef5f00-b45f-11e9-9e5d-b1cb9e01cfad.png)

### Technical details:

* Redash Version: SaaS
* Browser/OS: Firefox
* How did you install Redash: SaaS

**Comment by djabhe** [comment]
HI ALL,
how to remove brackets in target value?
