### ISSUE TITLE
Visualisation editor crashes out when changing datetype to non-HTML text

### ISSUE THREAD

**Issue by justinclift** [getredash/redash#4036]
### Issue Summary

When editing an example visualisation in our hosted instance, the visualisation editor crashes out (back to the source editing view).

In this crashed-out mode, the buttons (eg Save, Execute) look like they work but don't.  User drop down menu also doesn't work.

### Steps to Reproduce

1. Logging in as Melissa Payne, go to this simple query: https://redash-preview.netlify.com/queries/194/source#346
2. Edit the Table Visualisation
3. Change the first field to be displayed as Text
4. Untick the "Allow HTML content" checkbox.  The crash happens here, with the entire visualization editor crashing out

It looks almost like the Cancel button has been pressed, however (at least) the Save and Execute buttons don't function, the User drop down menu doesn't work, etc.

### Technical details:

* Redash Version: 8.0.0-beta+bea950b0
* Browser/OS: Firefox 68.0.1 on CentOS 7 x64
* How did you install Redash: n/a

**Comment by arikfr** [comment]
@justinclift assuming it's not a SaaS only issue, it's better to recreate the issue on the preview instances which will be available to anyone who is checking the issue.

**Comment by arikfr** [comment]
The Visualization Editor crashes in the scenario you described and then everything fails to work.

**Comment by arikfr** [comment]
I added a simple example from the preview instance: basically it happens with any date typed column.
