### ISSUE TITLE
CSP error when clicking on "Create your first Dashboard"

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#4039]
### Issue Summary

When clicking on the "Create your first Dashboard" link after setup I get a CSP error in the browser console.

### Steps to Reproduce

1. Setup Redash following the Docker dev docs.
2. Setup a data source (e.g. the postgres container)
3. Add a query
4. Try to click on the "Create your first Dashboard"

I believe the change in https://github.com/getredash/redash/commit/9480d89e4c3d87e092e64e2d6c634413e42cf0a0#diff-90812e4fcbcd1df5f887a43bda5953f5R125 resulted in the code that is run when clicking on the link to be considered inline, instead of the separate function before.

### Technical details:

* Redash Version: 8.0.0beta
* Browser/OS: Firefox/macOS 10.14
* How did you install Redash: Docker

**Comment by arikfr** [comment]
What is the message you receive?

**Comment by jezdez** [comment]
In Chrome (😬):

"Refused to run the JavaScript URL because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-...'), or a nonce ('nonce-...') is required to enable inline execution."

<img width="1098" alt="Screen-Shot-2019-08-06-14-49-45 93" src="https://user-images.githubusercontent.com/1610/62541163-81c0b100-b859-11e9-8fb6-5b6e6343df9d.png">

**Comment by jezdez** [comment]
I think this is about the difference between:

```diff
-            onClick={createDashboard}
+            onClick={() => CreateDashboardDialog.showModal()}
```

**Comment by kravets-levko** [comment]
@jezdez I think it may happen because of `javascript:void(0)` in `Step` component :thinking:

**Comment by jezdez** [comment]
Ah, that could be it?

**Comment by kravets-levko** [comment]
I think so. If you can experiment with it - try to remove `javascript:void(0)` there (use `null` or something like that instead), and check if the issue is still present or fixed.

**Comment by arikfr** [comment]
@kravets-levko is correct.  I will fix it.
