### ISSUE TITLE
Patch prorposal: Docker build failed

### ISSUE THREAD

**Issue by corona10** [getredash/redash#4041]
ISSUE
```
Collecting numpy>=1.16 (from pymapd>=0.2.1->-r requirements_all_ds.txt (line 23))
  Downloading https://files.pythonhosted.org/packages/da/32/1b8f2bb5fb50e4db68543eb85ce37b9fa6660cd05b58bddfafafa7ed62da/numpy-1.17.0.zip (6.5MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cATVgI/numpy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cATVgI/numpy/
You are using pip version 8.1.1, however version 19.2.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Docker build failed when installing pymapd since pymaped install numpy1.17 which stop to support python2.

I propose to freeze numpy and pandas latest version which support python2 
If this solution is right, I 'd like to submit the patch for this issue.

It can be easily solved by adding into `requirements_all_ds.txt`
```
numpy==1.16
pandas==0.24.2
```

**Comment by arikfr** [comment]
I think this partially happens because you are using an outdated version of our base Docker image. Our CI regularly builds the image with no such issues, but it uses a newer version of pip.

Can you try pulling for a new version of redash/base image and then try building again?

**Comment by corona10** [comment]
@arikfr 

Yes, you're right. I tried it on 6 version.
I will try on 7.
Thanks

**Comment by tomjohn1028** [comment]
@corona10 were you able to get your build up and running? I'm having the same issue but I've verified my base image is up to date.
