### ISSUE TITLE
Dropdown Parameter Missing Arrow

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4042]
Previous versions:

![image](https://user-images.githubusercontent.com/71468/62536379-8afc4e80-b856-11e9-8151-a4a30f784861.png)

Current version:

![image](https://user-images.githubusercontent.com/71468/62536405-9a7b9780-b856-11e9-936e-91a21a2e4a12.png)

Was this intentional?

**Comment by ranbena** [comment]
Looks like "multiple values" is being checked by default.
@gabrieldutra ?

**Comment by gabrieldutra** [comment]
Yes, this is the default styling for multi-select

**Comment by ranbena** [comment]
Ok, so existing dropdowns are not multi-select by default, yeah?
If so, no bug. All is good.

**Comment by arikfr** [comment]
It looks like a regular input field, while it's a dropdown. I think there should be an indication even in the case of a multi-select.

**Comment by gabrieldutra** [comment]
This is actually pretty simple to do: `<Select showArrow />` forces the arrow. When considering the styling I think it's better without the arrow, but on the other hand it's interesting to differ from Text parameters. Will submit a PR.

**Comment by ranbena** [comment]
Likewise.
PR https://github.com/getredash/redash/pull/4044
