### ISSUE TITLE
[Qubole] Add support to process Quantum query type. 

### ISSUE THREAD

**Issue by SandeepBelagavi** [getredash/redash#4065]
Qubole query runner now supports processing **presto** and **hive** queries. 
Quantum is a serverless interactive service that offers direct SQL access to user's data lake.
Quantum is needs to integrated with query runner.

For more info visit: 
https://docs.qubole.com/en/latest/user-guide/quantum/

**Comment by arikfr** [comment]
Implemented in #4066.
