### ISSUE TITLE
Bold markdown in Dashboard Textbox not rendered correctly

### ISSUE THREAD

**Issue by griffinator76** [getredash/redash#4070]
### Issue Summary
Textbox in Dashboard is supposed to support markdown as per https://www.markdownguide.org/cheat-sheet/#basic-syn (linked to from Textbox editor)

Bold markdown syntax doesn't appear to work though, in preview or in saved Textbox:

![image](https://user-images.githubusercontent.com/31025861/63057579-b1994400-bf3e-11e9-8848-009977a8a861.png)

Bold text is not rendered as bold, also preceding new line is ignored.

### Steps to Reproduce

1. Create a Dashboard
2. Add a Textbox
3. Enter some text and encapsulate in bold markdown syntax e.g. \*\*this is bold text\*\*
4. Save
5. Text is not displayed as bold

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Expected behaviour: using **<text>** markdown produces bold text

### Technical details:

* Redash Version: 7.0.0+b18042 (4a978bad) 
* Browser/OS: Firefox 60.8.0esr (64-bit) / Amazon Linux (Workspace)
* How did you install Redash: Self hosted on Kubernetes

**Comment by gabrieldutra** [comment]
Hi @griffinator76, thanks for reporting, happily this seems to be already fixed in #3686 and should arrive soon in Redash v8 :grin:. You can confirm whether this is working in our [preview environment](https://redash-preview.netlify.com/dashboard/textbox).

**Comment by griffinator76** [comment]
Thanks! Sorry, I searched for existing markdown issues but didn't see that one for some reason.

**Comment by arikfr** [comment]
Btw, this is how your example looks like with v8:

![image](https://user-images.githubusercontent.com/71468/63082281-76067600-bf4e-11e9-8612-d958c248d201.png)

**Comment by gabrieldutra** [comment]
In any case, "also preceding new line is ignored" seems to still be there :confused:.

**Comment by kravets-levko** [comment]
> also preceding new line is ignored

@griffinator76 (cc @gabrieldutra) It's okay: single newline is treat as whitespace. If you want to start a new paragraph, you have to add one more newline before it. So it should look like this:
```markdown
some text
**bold text**

---

*italics*

> blockquote

**more bold**
```

**Comment by arikfr** [comment]
> you have to add one more newline before it. So it should look like this:

That or add two spaces at the end of the line.

**Comment by gabrieldutra** [comment]
Closing as this issue is fixed in Redash v8 :slightly_smiling_face:
