### ISSUE TITLE
Support bubble size adaptation?

### ISSUE THREAD

**Issue by gerry-tan** [getredash/redash#4100]
I can't automatically scale the bubble size, but I can use it when I use plot.

![image](https://user-images.githubusercontent.com/20512878/63761653-1b78fc80-c8f4-11e9-9dc6-14e788d07728.png)

**Comment by kravets-levko** [comment]
Related PR: getredash/redash#3928

**Comment by gerry-tan** [comment]
Related PR: [#3928](https://github.com/getredash/redash/pull/3928)
