### ISSUE TITLE
Defaults for parameters

### ISSUE THREAD

**Issue by washort** [getredash/redash#4102]
PR https://github.com/getredash/redash/pull/3905 was proposed to provide a way for filters to default to 'select all'. Since parameters were suggested instead, let's add a way to set default values for parameters, particularly dropdown list ones.

**Comment by arikfr** [comment]
There is already defaults for parameters: it's the value the parameters have when you save the query. 

Here's an example: https://redash-preview.netlify.com/queries/214/source (it will open with Rock and Metal selected).

Closing this issue, but you're welcome to continue the discussion.
