### ISSUE TITLE
The stacking bar chart renders the wrong value.

### ISSUE THREAD

**Issue by JidapaTH** [getredash/redash#4103]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.
![image](https://user-images.githubusercontent.com/42632714/63888199-49f9e480-c993-11e9-8618-96bf0ea25538.png)

 I used the bar chart, normalized the value to percentage and stacked the value together. The numbers on the label are correct but the graph somehow wrong. After the 9th bar, the total percentage is not 100% which is weird.  

### Steps to Reproduce

I'm not sure how to reproduce this too. Try create a bar chart from a time-series data with a group. I expect all stacking percentage bar chart to be at 100% maximum. 

### Technical details:

* Redash Version: 7.0.0+b18042
* Browser/OS: Google Chrome
* How did you install Redash:

**Comment by kravets-levko** [comment]
Hi @JidapaTH! It's strange that it does not work as expected. My first assumption will be: does your data contain negative values?

**Comment by kravets-levko** [comment]
And another idea: is your data properly aggregated? Try to check values for one of the "wrong" columns - there should be the only Y value for each series.

**Comment by JidapaTH** [comment]
Hi @kravets-levko, thank you for your reply. I don't have negative values in my data and when I filter data just from just August 5th, the graph rendered normally.

**Comment by JidapaTH** [comment]
Hi. I just figured out the reason now. It is about the way I aggregated data. Thank you!
