### ISSUE TITLE
It seems like we encountered an error. Try refreshing this page or contact your administrator

### ISSUE THREAD

**Issue by M-make** [getredash/redash#4126]
### Issue Summary

> when i create query , i got this error `It seems like we encountered an error. Try refreshing this page or contact your administrator.`

### Technical details:

* Redash Version: 7.0.0+b18042 (4a978bad)
* Browser/OS: Chrome/76.0.3809.132 Mac os 10.14.6
* How did you install Redash: docker shell

**Comment by M-make** [comment]
I have created a data source and a query before, are good, but after I delete the physical database, the query will be given an error.

**Comment by ranbena** [comment]
@M-make Plz follow the bug issue report instructions:

1. Steps to Reproduce
2. Why do you consider this to be a bug?
3. What did you expect to happen instead?
