### ISSUE TITLE
Middle click on Create → Dashboard doesn't work

### ISSUE THREAD

**Issue by justinclift** [getredash/redash#4155]
### Issue Summary

Just came across an surprising bug with our latest (v8.0.0-beta.2) code.

When clicking on `Create` → `Dashboard`, but using the middle mouse button for the "Dashboard" click (to open in a new tab), the click is ignored.  No tab opens, and no action is taken.

However, doing the same with `Create` → `Query` and `Create` → `Alert` works as expected.  The click works, new tab is opened, etc.

### Technical details:

* Redash Version: v8.0.0-beta.2
* Browser/OS: Firefox 60.8.0 ESR, on OpenSUSE Leap 15.1
* How did you install Redash: Manually, using the (non-docker) [dev setup guide](https://redash.io/help/open-source/dev-guide/setup)

**Comment by ranbena** [comment]
Technical reason:
Query and Alert are redirections to `/new` pages while Dashboard is a JS invocation that opens up a dialog.

**Comment by arikfr** [comment]
We can either leave the behavior as is or make middle click open the new dashboard dialog (in the same tab) just like a left click would. What do you think will be better?

**Comment by justinclift** [comment]
Probably make it open up in the same tab then?
