### ISSUE TITLE
Queries with parameters API call shows 'No cached result found for this query'

### ISSUE THREAD

**Issue by myonlylonely** [getredash/redash#4191]
### Issue Summary

Queries with parameters API call shows 'No cached result found for this query'

### Steps to Reproduce

1. Create a query with parameter.
2. Show API Key. Visit the url.
3. It returns:

```javascript
{
message: "No cached result found for this query. You have requested this URI [/api/queries/222/results.json] but did you mean /api/queries/<query_id>/results or /api/query_results or /api/queries/<query_id>/refresh ?"
}
```

### Technical details:

* Redash Version: Redash 8.0 Beta 2
* Browser/OS: CentOS 7
* How did you install Redash: Docker

**Comment by sharathbjgowda** [comment]
I am sharing here my experience to similar problem.
I took endpoint with APIKey show in redash dashboard 
http://common-redash.xyz.com/api/queries/2174/results**.json**?api_key=qwertyuiop
problem is the endpoint, we need not have **.json** in endpoint , so once I removed that .json in the endpoint it worked
![image](https://user-images.githubusercontent.com/20763909/93048902-933fd380-f67d-11ea-8a1b-f9915065e9fc.png)

Please follow this [https://redash.io/help/user-guide/integrations-and-api/api/](url)
