### ISSUE TITLE
Failed to install requirement_dev.txt

### ISSUE THREAD

**Issue by yujunz** [getredash/redash#4192]
### Issue Summary

Failed to install `requirements_dev.txt`

### Steps to Reproduce

1. `pip install -r requirements.txt -r requirements_dev.txt`

```
ERROR: boto3 1.9.237 has requirement botocore<1.13.0,>=1.12.237, but you'll have botocore 1.12.220 which is incompatible.
```

### Technical details:

* Redash Version: master
* Browser/OS: N/A
* How did you install Redash: source code

**Comment by yujunz** [comment]
It seems already addressed in #4154

**Comment by ranbena** [comment]
@yujunz can this issue be closed?

**Comment by yujunz** [comment]
We can close it as soon as #4154 is merged

**Comment by justinclift** [comment]
@yujunz That's been merged, so should work now.  In theory. :wink:
