### ISSUE TITLE
Dashboard filters disappear after changing dashboard parameter values

### ISSUE THREAD

**Issue by gabrieldutra** [getredash/redash#4204]
### Issue Summary

My guess is that this was introduced with #3804 

### Steps to Reproduce

1. Create a dashboard with a widget containing a filter and another widget containing a parameter (or use an [existing one](http://localhost:5000/dashboard/test));
2. Map the Widget Parameter to be a Dashboard Parameter and enable Dashboard level filters;
3. Change the Parameter value and verify the filter options disappear

![dashboard-filters-parameter](https://user-images.githubusercontent.com/3356951/65996514-ea996380-e46d-11e9-98f1-2364586b0732.gif)

### Technical details:

* Redash Version: Latest
* Browser/OS: --
* How did you install Redash: --

**Comment by gabrieldutra** [comment]
Code related to the issue:

https://github.com/getredash/redash/blob/a8af968d70825bdc36bbe5512e449cc56e62242c/client/app/pages/dashboards/dashboard.js#L159-L167

This seems to be easily solved by using the code below for the queryResults instead of the Promise results:
```javascript
const queryResults = compact(map(dashboard.widgets, widget => widget.getQueryResult()));
```

Though, I'm also considering to refactor that part of the code along with Dashboard & Public Dashboard migration, e.g: it makes sense for the Refreshing Code to be separated from the Collect Filters Part.

Depending on when this needs to be fixed, we can go with the quick solution.

**Comment by ranbena** [comment]
> it makes sense for the Refreshing Code to be separated from the Collect Filters Part.

I favor this approach.
