### ISSUE TITLE
Use SHOW_COLUMNS to fetch Snowflake's schema

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4217]
### Issue Summary

The current method of refreshing the Snowflake schema is starting a cluster, which is undesired -- specially when doing a background refresh of the schema.

We can alternatively use [`SHOW_COLUMNS`](https://docs.snowflake.net/manuals/sql-reference/sql/show-columns.html) to load the schema without waking a up a cluster.

### Technical details:

* Redash Version: v8

**Comment by monicagangwar** [comment]
@arikfr are there any tests for snowflake with which any change to snowflake query runner can be verified ?

**Comment by arikfr** [comment]
@monicagangwar this is a great question. Sadly, the answer is no :-( Most of the query runners are untested. It's something we do want to address (see #3807), but will take us time to get there.

**Comment by monicagangwar** [comment]
@arikfr alright. Although i've seen there is no pagination handled while refreshing schema. 
A/c to the documentation for SHOW COLUMNS
```
The command returns a maximum of 10K records for the specified object type, as dictated by the access privileges for the role used to execute the command; any records above the 10K limit are not returned, even with a filter applied.
```
Should I handle this in the PR ?

**Comment by arikfr** [comment]
@monicagangwar let's ignore the 10K limit for now. If we get reports of this being an issue will try to think of how to address it.

Thanks!

**Comment by bradleyhurley** [comment]
@arikfr - Can this issue be closed? I was looking for some low hanging fruit I could help out with, but it seems the update was already merged.

**Comment by arikfr** [comment]
@bradleyhurley definitely. Thanks for noticing!
