### ISSUE TITLE
Misleading warning when trying to download results of unsaved query

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4218]
### Issue Summary

When trying to download results of an unsaved (or just new) query, it will warn you about "Leaving the site" with unsaved changes, but in fact it doesn't redirect -- it just downloads the file.

### Steps to Reproduce

1. Create a new query (without saving).
2. Execute.
3. Click on the Download CSV results link.

Expected: it should just download the results without prompting or warning.

### Technical details:

* Redash Version: v8

**Comment by ranbena** [comment]
Can try `<a download={url}>` instead of `href`.
