### ISSUE TITLE
Change PagerDuty's default summary text

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4223]
Currently PagerDuty's Alert destination default summary text uses the query id and name. We should change it to use the alert name as it's usually better explains what the alert is.

While #4153 implements ability to customize the summary text, it's good to have a saner default regardless.

(If #4153 is not merged before implementing, should be implemented based on its branch)

**Comment by frextrite** [comment]
Hi @arikfr 
I believe https://github.com/getredash/redash/blob/74beed80d20d858b51b5560e7984b20d5d2c874e/redash/destinations/pagerduty.py#L15 this needs to be changed. However, I could not find any accessors of `notify()` function (maybe a problem with my IDE), so I was unable to find the `alert` object properties. Can I assume I can get the alert name by `alert.name`?

And also, I would have to change https://github.com/getredash/redash/blob/74beed80d20d858b51b5560e7984b20d5d2c874e/redash/destinations/pagerduty.py#L49 to something like 
```
self.DESCRIPTION_STR.format(alert_name=alert.name)
```

So can I assume, `alert.name` will always be non-null or do I need to involve checks?
Thanks!

**Comment by frextrite** [comment]
So, I dug more and found a few examples of `alert.name` in `redash/destination/`
