### ISSUE TITLE
Allow for forking the query and retaining the schedule

### ISSUE THREAD

**Issue by runa** [getredash/redash#424]
1. Create a new query, set a refresh schedule
2. Fork it: the new query doesn't has the refresh schedule set.

**Comment by arikfr** [comment]
Actually this is by design. I wanted to avoid situation that queries get scheduled by mistake, just because the original one was scheduled.

**Comment by runa** [comment]
mrmr. I'm mostly forking queries to make them execute at another
datasource; so I really want to copy the schedule ;)

does the query results cache works by hashing the query text or it does it
by query-id? if it's in the first case, it wouldn't be a problem if you
duplicated the schedule without noticing it because the query won't be run
again (because of the query cache)

**Comment by arikfr** [comment]
Well, the use case around fork is usually different: you want to fork it to play around with the query or change something. In such cases, caching won't help as the user will end up running a different query (but you're correct that it's done using query text).

I won't change the default behavior of fork, but it's possible to add another fork button that retains the scheduling...

**Comment by runa** [comment]
Super Fork?
Maybe "Clone" ?

**Comment by arikfr** [comment]
It's not a common enough use case to make the UI more complex than it is now.
