### ISSUE TITLE
Counter Visualization: count rows never shows zero

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#4265]
### Issue Summary

If I toggle **Count Rows** and my query returns no results, the visualization disappears. It should show "0". It makes sense for the visualization to disappear if it points at a field and row index. But sometimes the number of rows is actually zero and this should be reflected by the counter.

### Steps to Reproduce

1. Write a query that returns a single row: `SELECT 'foo', 'bar'`
2. Add a counter visualization and toggle **Count Rows**. The counter will show 1.
3. Add a NULL `WHERE` clause to the query ... `where 1 =2`. The counter disappears.

### Technical details:

* Redash Version: 7, 8, 9alpha
* Browser/OS: Firefox / Chrome / Safari
* How did you install Redash: Saas / Docker

**Comment by susodapop** [comment]
Identified on the forum [here](https://discuss.redash.io/t/counter-when-number-rows-returned-is-0/4735/2).

**Comment by kykrueger** [comment]
I'm also experiencing the same issue. It gives the impression that a count on a dashboard has an error in the query when 0 rows returned should be a legitimate result.

**Comment by dmudro** [comment]
I wrote a fix for this including bunch of unit tests for `client/app/visualizations/counter/utils.js`.
Am not able to push my branch and create the PR though, getting 403. Maybe @arikfr can advise?

**Comment by arikfr** [comment]
Thank you for taking a look at this.

You need to create a fork on GitHub, push to your fork and make a pull
request from there.

**Comment by dmudro** [comment]
> It makes sense for the visualisation to disappear if it points at a field and row index.

Ok that part stayed untouched but there is a tiny edge case that might be worth looking into:
![image](https://user-images.githubusercontent.com/1648143/69415434-e6beea80-0d14-11ea-8121-7ab9cd3d225a.png)

The default dropdown item with non existent value could be seen as a small inconvenience from a UX perspective. I've seen a similar behaviour in other dropdowns throughout the app and the user typically cannot revert to the non-existent default value after interacting with the form control (which makes sense).

A suggestion to overcome this particular one would be to merge the _Count Rows_ toggle and the _Counter Value Column Name_ dropdown (the toggle at the bottom is a bit odd IMHO anyway):
![image](https://user-images.githubusercontent.com/1648143/69416413-dad42800-0d16-11ea-9003-16152b966b8d.png)

**Comment by gabrieldutra** [comment]
Hi @dmudro thanks for pointing that out, there is #4366 to allow more aggregate functions in the Counter visualization, so the "Count rows" will probably be merged into a "Counter Type" dropdown soon. Regarding the inconvenient non existent value, that seems a bug, I'll investigate further on that as it should either show a placeholder or select a valid column value by default.
