### ISSUE TITLE
quarterly interval in cohort

### ISSUE THREAD

**Issue by thuanbvv** [getredash/redash#4269]
Please add Quarterly (3 months) cohort group timeInterval in cohort chart UI.

![image](https://user-images.githubusercontent.com/17841056/67176230-68a8b480-f3f3-11e9-9ae7-8c7d1b978e13.png)
![image](https://user-images.githubusercontent.com/17841056/67176277-97bf2600-f3f3-11e9-88f6-cc60b8e463d5.png)

**Comment by kravets-levko** [comment]
Hi @thuanbvv! This issue actually appears to be a feature request :smile: But anyway - we collect feature requests in a dedicated category on our [forum](https://discuss.redash.io/c/feature-requests) - feel free to move this topic there.
