### ISSUE TITLE
Reduce refresh_queries's memory usage

### ISSUE THREAD

**Issue by rauchy** [getredash/redash#4303]
`refresh_queries` looks up all outdated queries and then schedules refresh tasks for each. The lookup can take a while and consume a lot of memory. We could probably do this in batches or yield for each outdated query.

**Comment by arikfr** [comment]
Seems like it might be as simple as calling `yield_per` on the SQLA query object.

**Comment by rauchy** [comment]
I profiled `refresh_queries` with 5k outdated queries and saw that peak memory rose by a mere 10% (~82mb). Also, `yield_per` provided negligible difference here so unless I am missing out on something, I'm not sure we should pursuit any optimization here at the moment.

**Comment by arikfr** [comment]
What if you try 25K queries?

**Comment by rauchy** [comment]
It rises to by 16% (~135mb).

**Comment by arikfr** [comment]
:+1:
