### ISSUE TITLE
Unable to upgrade because of empty "download_url" in json.

### ISSUE THREAD

**Issue by idanh** [getredash/redash#4317]
Hi, please note that:
https://version.redash.io/api/releases

Has an empty "download_url" field which prevents upgrade to work.

**Comment by arikfr** [comment]
From the docs:

>  Starting from the Redash V8 release we’re no longer building the tarball version of a release – only Docker images. This of course doesn’t prevent you from deploying Redash anyway you want, but the bin/upgrade script won’t work with the new releases.
