### ISSUE TITLE
Cohort visualization isn't using the same font as the rest of the application

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4329]
![image](https://user-images.githubusercontent.com/71468/68085483-3e6ee200-fe4a-11e9-82d2-6bc8159d60b4.png)

https://redash-preview.netlify.com/queries/234#427

**Comment by kravets-levko** [comment]
@arikfr Fixed in getredash/redash#4270 - check preview https://deploy-preview-4270--redash-preview.netlify.com/queries/234#427

**Comment by arikfr** [comment]
Oh, cool :-)
