### ISSUE TITLE
Queries with unicode in query name fails downloading result file

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4332]
This just happened on deploy preview. Sentry error:
https://sentry.io/share/issue/b8268b7c97784a30b67c512332a8d779/

Some possible solutions:

1. Implement a solution similar to pallets/flask#2223.
2. Switch to using Flask's `send_file` method instead of handling this on our own (need to make sure that we always have a file-like object at hand and that the behavior consistent with our current one).
3. Try quoting the filename, as suggested here: https://github.com/benoitc/gunicorn/issues/1214#issuecomment-238193505.

3 is the simplest, 2 is probably the most future proof.

**Comment by jezdez** [comment]
+1 on (2)
