### ISSUE TITLE
GoogleSheets: Allow tab selection by name

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#4339]
### Issue Summary

According to [the docs](https://redash.io/help/data-sources/querying/google-spreadsheet) you can only select data from a tab by its integer position in the document. This is inconvenient for users who frequently modify queries to view data from different tabs.

### ~Steps to Reproduce~

Normally I would file this as a feature request on the forum. But the Redash team asked me to file an issue so here it is.

### Technical details:

* Redash Version: v9 alpha
* Browser/OS: Chrome, FF, Safari
* How did you install Redash: SaaS

**Comment by guidopetri** [comment]
Closed via #5334
