### ISSUE TITLE
Widgets API is called when loading a dashboard

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4341]
### Issue Summary

On some dashboards it happens more often than other, but I noticed that in some cases a POST request is made to some of the widgets on a dashboard when loading it.

Here's an example: https://redash-preview.netlify.com/dashboard/now-param

### Technical details:

* Redash Version: v9
* Browser/OS: Chrome

**Comment by gabrieldutra** [comment]
Those POST requests come from the `DashboardGrid` `onLayoutChange`, I think the idea is to save widgets position after they "flow". One issue is that this is currently happening in view and in edit mode, we can change that and then those requests would only happen in edit mode.

**Comment by arikfr** [comment]
But why they happen on every load? Shouldn't it happen once, get updated, and then not happen again until something changes with the layout?

**Comment by gabrieldutra** [comment]
You have a point, the function that seems to be triggering changes in the layout is this one:
https://github.com/getredash/redash/blob/80878abf7b599a16e0799f4d31ab0824e6f2e698/client/app/services/dashboard.js#L36-L78

I'll investigate this further, but so far it seems to be updating the `row` for widgets that are not in the first row.

**Comment by arikfr** [comment]
> You have a point, the function that seems to be triggering changes in the layout is this one:

Maybe we should remove this functionality, because layout might change often when auto-height is used and there is no harm in /not/ preserving it.

**Comment by gabrieldutra** [comment]
Removed it in #4228, there indeed seems to be no harm in removing it and those POST requests stopped.
