### ISSUE TITLE
phoenix does not work with phoenixdb=0.7

### ISSUE THREAD

**Issue by fishre** [getredash/redash#4346]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: redash v8
* Browser/OS: centos7 
* How did you install Redash: docker

change to phoenixdb==0.5, then it worked

**Comment by arikfr** [comment]
Can you share more details on the error you get with `phoenixdb` 0.5 and what version of Pheonix you're using?

**Comment by fishre** [comment]
I fix it by replacing phoenixdb==0.7 as phoenixdb==0.5. my Pheonix version is 4.7-cloudera_labs.

**Comment by fishre** [comment]
![image](https://user-images.githubusercontent.com/22518905/68660901-fd2ab080-0574-11ea-87e1-21d5bb4a0de0.png)

**Comment by arikfr** [comment]
Yes, I was looking at the same. But isn't your version 4.7? So according to this it supposed to be supported, no?

I do see that their CI tests [test only until version 4.8](https://github.com/lalinsky/python-phoenixdb/blob/master/.gitlab-ci.yml). :thinking:

**Comment by fishre** [comment]
Yes, my phoenix version is 4.7. it worked thanks
