### ISSUE TITLE
Delete button is no longer red, but it light gray

### ISSUE THREAD

**Issue by nitinsurana** [getredash/redash#4350]
https://github.com/getredash/redash/blob/master/client/app/assets/less/inc/ant-variables.less#L47 - Overrides the danger button color to gray.

### Technical details:

* Redash Version: master (latest from github)
* Browser/OS: macos
* How did you install Redash: running direct source-code

**Comment by kravets-levko** [comment]
Why you consider this a bug? This was intentional change. Also, danger buttons still have a red text and become red on hover.

**Comment by nitinsurana** [comment]
My apologies. 
I believed redash use antd ui design language (where danger button is red) & hence, thought of it as a bug.
