### ISSUE TITLE
Worker architecture

### ISSUE THREAD

**Issue by ccakes** [getredash/redash#4370]
I've searched the forums at discuss.redash.io but couldn't find anything on this topic. It seems involved enough that I'd like a dev answer though as it's not covered in the docs anywhere.

I'm running Redash 8 and it's all working great. I want to add an Oracle data source, I've built a Docker image and it works however I want to have a specific worker only service the Oracle queries, while the existing workers service the others.

I've deployed the new worker with the following env config
```
REDASH_ENABLED_QUERY_RUNNERS=""
REDASH_ADDITIONAL_QUERY_RUNNERS="redash.query_runner.oracle"
```
and was hoping that would Just Work.

The existing workers don't have the Oracle capability so I was hoping the query queue worked in such a way that the jobs would be pushed on and this new worker would be the only one able to pick up the Oracle queries. Queries towards the Oracle data source hang in "Query in queue" so I'm guessing not.

Is this a supported deployment method and is there something I'm missing? Would be keen to understand how the workers interact. If I can make this function I'm happy to contribute some docs back to the KB 👍

**Comment by arikfr** [comment]
This is possible, but not in the way you described it.

Anyway, this indeed belongs in the forum. Just open a thread in the forum and let's continue the conversation there.

**Comment by ccakes** [comment]
Thanks @arikfr, thread here https://discuss.redash.io/t/worker-architecture-question/5025
