### ISSUE TITLE
Typo at unsupportedRedirect.js

### ISSUE THREAD

**Issue by uncletimmy3** [getredash/redash#4386]
### Issue Summary

Regardless of OS version and browser.
unsupportedRedirect.js:
```
if (
  navigator.appVersion.match('Trident/') || // IE8-11
  'ActiveXObject' in window // IE<11
) {
  window.location.href = '/static/unsupported';
}
```
But:
```
$ls /app/client/dist | grep uns
unsupported.html
unsupportedRedirect.js
```
### Steps to Reproduce

1. HTTP-request to hostname/static/unsupported
2. As result we get 404

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: v8.0.0
* Browser/OS: Firefox/Windows 10
* How did you install Redash: self-hosted

**Comment by gabrieldutra** [comment]
Thanks @uncletimmy3, just curious, what Firefox version did you experience that? Browsers usually assume the `.html` file type :grimacing:

**Comment by uncletimmy3** [comment]
I thought so too
latest Firefox 70.0.1
and i've just checked it at IE 11
![image](https://user-images.githubusercontent.com/34276679/69451852-312a8080-0d82-11ea-8d7f-47a8fdd0025a.png)
![image](https://user-images.githubusercontent.com/34276679/69451928-561ef380-0d82-11ea-8099-d231dd77e58c.png)

**Comment by uncletimmy3** [comment]
Dev tool screenshot
![image](https://user-images.githubusercontent.com/34276679/69452068-aa29d800-0d82-11ea-9227-3b1eb895b25d.png)

**Comment by gabrieldutra** [comment]
On a second thought, that may not depend on browsers, but rather on the Server that's responding the requests :sweat_smile:

**Comment by uncletimmy3** [comment]
In my environment, the http-request goes through a chain : 
nginx <-> web application firewall <-> redash
I will try to check the problem without nginx/web application firewall...
