### ISSUE TITLE
Chart series switch places when picking Y axis

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4404]
Here's a video showing it:
https://www.loom.com/share/4b1536ea162043f68fbc848ca0767ff0

And you can play with it yourself using this query:
https://redash-preview.netlify.com/queries/263/source

Steps to reproduce:

1. Create new chart visualization.
2. Switch to the series tab.
3. Set the Y axis for the first series as the secondary Y axis.

What happens: the series you changed moved to the bottom of the list.
What should happen: series order shouldn't change.

Because the change is quick and subtle, it seems at first as if your change didn't apply, until you notice the series switched places.

**Comment by kravets-levko** [comment]
It the same issue getredash/redash#2292 It could be fixed with newer Plotly version, but the upgrade didn't go smoothly: getredash/redash#4150

**Comment by arikfr** [comment]
@kravets-levko how come it's the same thing? I'm referring to the issue in the visualization editor.

**Comment by kravets-levko** [comment]
@arikfr Yes, you're right - I missed that
