### ISSUE TITLE
Setting up redash for Ubuntu 16.04. Fails due to NPM Build.

### ISSUE THREAD

**Issue by pktiw** [getredash/redash#4405]
npm ERR! Linux 4.15.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! redash-client@9.0.0-alpha build: `npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the redash-client@9.0.0-alpha build script 'npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the redash-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run clean && NODE_ENV=production node --max-old-space-size=4096 node_modules/.bin/webpack

------------------------
[npm-debug.log](https://github.com/getredash/redash/files/3897084/npm-debug.log)

**Comment by kravets-levko** [comment]
Hi @pktiw! Your NodeJS is outdated. Please upgrade NodeJS and NPM to versions required by Redash:

https://github.com/getredash/redash/blob/80f3ec1c993c493f0b96b5504269cfbbc934fcbf/package.json#L26-L28
