### ISSUE TITLE
Test Connection Fails, with Redash, but Grafana says Okay.

### ISSUE THREAD

**Issue by pktiw** [getredash/redash#4409]
From Redash:
Connection Test Failed:
(2006, "Can't connect to MySQL server on '127.0.0.1' (115)")

Grafana: Green

**Comment by arikfr** [comment]
Your description is a bit sparse with details, but I guess that Grafana runs locally while Readsh runs in a Docker container. Try replacing `127.0.0.1` with `host.docker.internal` (which is your host machine). If this isn't the case or doesn't help, please open a thread in the forum with more details.
