### ISSUE TITLE
ClickHouse queries keeps running after cancelling

### ISSUE THREAD

**Issue by WesleyBatista** [getredash/redash#4410]
### Issue Summary

ClickHouse queries doesn't get cancelled when user click the cancel button.

### Steps to Reproduce

1. Submit a long running query for execution on a clickhouse datasource;
2. Try to cancel the query clicking on the **cancel** button;
3. Go to the `clickhouse-client` cli and run `show processlist` to list see the query still running.

The submitted query should not appear on the show processlist. 

### Technical details:

* Redash Version: 8.0.0+b32245 (a16f551e)
* Browser/OS: Chrome/Ubuntu
* How did you install Redash: docker

**Comment by WesleyBatista** [comment]
BTW, if you got here you might be interest on this:
```sql
kill query where query_id = '<query_id_from_show_processlist>'
```

**Comment by konnectr** [comment]
This is Clickhouse's problem. Clickhouse can't always cancel a request. It can only cancel the request at a certain point in time.
