### ISSUE TITLE
FYI: Helm chart

### ISSUE THREAD

**Issue by mikkeschiren** [getredash/redash#4418]
We created a helm chart to deploy Redash to Kubernetes, mostly based on the work done by @grugnog .

The chart lives here: https://github.com/digitalist-se/redash-helm

**Comment by arikfr** [comment]
@mikkeschiren @grugnog is now maintaining his Helm Chart in a repo under our GitHub org: https://github.com/getredash/contrib-helm-chart. Maybe you should join forces?
