### ISSUE TITLE
Box Plot Graph may having wrong calculations

### ISSUE THREAD

**Issue by Rovel** [getredash/redash#4428]
### Issue Summary

Box PLot Graph may be calculating wrong data on Q1, Q3

### Steps to Reproduce

1. I Had a query that produced this dataset to plot on a boxplot:
`x = [3.375, 3.75, 3.875, 3, 3, 3.5, 3.125, 3, 2.625, 3.375, 3]`

2. On numpy, google sheets and Charts.js boxplot extension the Q3 is different from Redash box plot:
Numpy
<img width="645" alt="Screen Shot 2019-12-09 at 15 35 00" src="https://user-images.githubusercontent.com/2469500/70462526-d7bc9400-1a99-11ea-9319-72d5847c5abd.png">
Redash BoxPlot

![Screen Shot 2019-12-09 at 15 33 44](https://user-images.githubusercontent.com/2469500/70462791-60d3cb00-1a9a-11ea-91bc-3691758dd66e.png)

### Technical details:

* Redash Version: 8.0.1+b33387 (cd13c978)
* Browser/OS: Brave (Chrome)
* How did you install Redash: Docker

**Comment by deecay** [comment]
See https://community.plot.ly/t/boxplot-quartile-seems-wrong/2234

**Comment by Rovel** [comment]
ok understtod and thanks for the info, but considering all other major libs are following a pattern, won't be nice to follow a pattern to avoid this kind of issue I'm presenting, I'm sure change plotly behavior is beyond redash reach and convincing you guys to change the entire graph lib to something else is beyond mine.
but just for curiosity, why plotly? isnt their payed product really similar to redash dasboard module?

**Comment by deecay** [comment]
See https://github.com/plotly/plotly.js/issues/4220 for recent discussion within plotly team. PR https://github.com/plotly/plotly.js/pull/4432 has been created.

**Comment by Rovel** [comment]
thx @deecay any chance you guys go for inclusive method in future relases?

**Comment by kravets-levko** [comment]
@Rovel, yes, but no any estimates. Plotly upgrades never go smoothly; we already need to upgrade Plotly in order to fix some other issues (like this getredash/redash#4150), but upgrading Plotly there affected rendering of all visualizations - therefore we do that upgrades so rarely.

**Comment by Rovel** [comment]
can you point to me some file paths so I can play with the source myself? maybe I can help some way . thanks
