### ISSUE TITLE
When in edit mode, user unable to edit widgets

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4477]
> I'm setting up dashboard with queries that have variables in them. If I use a static value for the variable, I'm unable to see the value I've set and edit the parameter again while I'm still in edit mode. Currently I have to leave edit mode, then click on the "..." at the top right of the widget to be able to edit the parameter. Is there an edit parameter entrance I'm not seeing while in edit mode?

> The same goes for editing text boxes as well actually. I have to leave edit mode in order to edit the actual text.

It definitely makes no sense and confusing that you can't edit a widget when editing a dashboard. We should add an edit button next to the delete one, that will allow doing these operations.

**Comment by gabrieldutra** [comment]
The simple option is just to move the existing Dropdown btn when in edit mode (and remove the "Remove Widget" option from it):

![edit-mode-widgets](https://user-images.githubusercontent.com/3356951/74060319-7e54e080-49c8-11ea-8000-390bc892b313.gif)

Did you think of anything beyond that?

**Comment by JSilversun** [comment]
I think this doesn't make sense either, also, I can't change the visualization for a widget, in the dashboard edit mode and I find it really confusing, I have to remove the widget and then add it again to change the visualization mode.
