### ISSUE TITLE
Redshift: add support for IAM users

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4479]
Relevant: https://stackoverflow.com/questions/44243169/connect-to-redshift-using-python-using-iam-role

**Comment by stevebuckingham** [comment]
I'm looking at implementing this. I don't think it should be too complicated.

**Comment by arikfr** [comment]
@stevebuckingham :+1: let us know if you need any help with this.

**Comment by stevebuckingham** [comment]
I'm looking at implementing this. I don't think it should be too complicated.

**Comment by stevebuckingham** [comment]
I've opened a PR - but I am still to complete testing all the options against a Redshift instance as I need to write some Terraform on our own setup. https://github.com/getredash/redash/pull/4532

**Comment by stevebuckingham** [comment]
I think this is merged into master and so assume it can be closed.
