### ISSUE TITLE
Passing all zeroes to the funnel visualization crashes the renderer

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#4529]
### Issue Summary
If all stages of a funnel chart return zero, the funnel chart crashes and takes the renderer with it. Adding this visualization to a dashboard makes the entire dashboard crash on load.

### Steps to Reproduce

1. In postgres use the following SQL:

```
SELECT * FROM (VALUES 
('foo', 0),
('bar', 0),
('baz', 0),
('foobar', 0)) data(stage,value)
```

It produces the following table:

| stage | value |
| ----- | ----- |
| foo    | 0    |
| bar    | 0    |
| baz    | 0    |
| foobar | 0    |

2. Add a funnel visualization with the the `stage` and `value` columns.
3. Observe the chart does not render. 
4. Save the visualization and try clicking the **Edit Visualization** button. It won't work.

This is probably a divide-by-zero error.

### Technical details:

* Redash Version: v9 Alpha
* Browser/OS: FF
* How did you install Redash: SaaS

**Comment by srs231198** [comment]
A simple check before any calculations should solve the issue... Do you still require assistance with this?

**Comment by susodapop** [comment]
Thanks @srs231198. This has been solved already in the migration to React.
