### ISSUE TITLE
Saving a new query creates multiple queries

### ISSUE THREAD

**Issue by kravets-levko** [getredash/redash#4548]
### Issue Summary

In query editor, "Save" button is not locked when saving query, therefore it's possible to click it multiple times during sending previous save requests to backend. If frontend didn't receive a response from previous request(s), it will use the same query object to save. If that query object is new (does not have ID yet) - on each request backend will create a new record in database.

Suggested solution: disable "Save" button until save request completed; show some animation (e.g. "Saving..." with animated dots - like on Dashboard page).

### Steps to Reproduce

1. Create a new query, type something in editor;
2. Click "Save" button quickly few times;
3. Go to queries list and see few new queries, completely equal to created one.

### Technical details:

* Redash Version: master
* Browser/OS: any
* How did you install Redash: docker

**Comment by gabrieldutra** [comment]
> show some animation

The simplest one is the Antd `<Button loading />`
