### ISSUE TITLE
TypeError: Object of type QueryExecutionError is not JSON serializable

### ISSUE THREAD

**Issue by nason** [getredash/redash#4555]
### Issue Summary

While testing the latest `master`, I started noticing this error pop up in our Sentry.

### Steps to Reproduce

1. Run a query that fails to execute
2. View that query's results

### Technical details:

* Redash Version: 9.0.0-alpha
* Browser/OS: Chrome
* How did you install Redash: self-hosted/docker

### Proposal:

I don't think this is limited to `QueryExecutionError`, but rather any `Exception` that is attempted to be serialized here.

I've worked around it locally by making adding another case in the JSONEncoder in `utils/__init__.py`:

```py
elif isinstance(o, Exception):
    result = "".join(traceback.format_exception(etype=type(o), value=o, tb=o.__traceback__))
```

Does this seem like a reasonable change? Would you be open to a PR with this fix, or do you have other suggestions?

**Comment by arikfr** [comment]
#4622 should fix this. I'm closing this now, but please reopen if it reproduces after the fix.

Thanks.
