### ISSUE TITLE
Alerts: possible issue when query result value is a string number

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4561]
Some data sources return only strings, even when the value is a number. One such example is Google Analytics. In this case, it's possible that your value will be `"600"` (i.e. the text representation of 600). Here's some possible scenarios:

* Newly created alerts, will have the threshold as a string. Both values will be compares as strings, and while it won't fail and it will return the wrong alert state.
* For alerts created before the alert page update, the threshold value would be a number. In Python 2, if you compared a number and a string it would be the same as comparing two strings. But in Python 3 it just fails (raises an exception).

I wonder what should we do? Should we cast values to numbers whenever we use the greater than/less than operators? Should we catch the error and ignore it?

**Comment by gabrieldutra** [comment]
> Should we cast values to numbers whenever we use the greater than/less than operators

If string comparisons with those operators never existed/worked before, I think this is a safe way to go. Conceptually, this will make the "<" and ">" operators be associated with Number values, if at some point we decide to add new operators for strings, it's a matter of adding a toggle in UI to disable the casting.

Anyway, I assume the majority of Alert operations are intended to happen as number operations, so this feels like the option that should allow more use cases.

**Comment by kravets-levko** [comment]
For me it looks good if "<" and ">" will work only for numbers (and will cast both operands to number), and "=="/"!=" will work both for string and numbers (cast to type of results column?).
