### ISSUE TITLE
Release a new tag with updated 2019 CA Certificate for AWS RDS 

### ISSUE THREAD

**Issue by Aristatle-Subramaniam** [getredash/redash#4581]
The latest tag redash/redash:8.0.0.b32245 does not include the commit (https://github.com/getredash/redash/pull/4304) which has updated RDS 2019 CA Certificate

The 2015 Certificate will expire on Feb 05 2020. Can you please release with latest certificate immediately.

Thanks,
Aristatle

**Comment by Aristatle-Subramaniam** [comment]
@arikfr  Thanks for you and your team effort on making Redash as success-full project. We are one of the beneficiary of using redash. 

Currently we using Redash to query AWS. We are facing an issue of using existing redash image redash/redash:5.0.2.b5486 which internally bundled with 2015 CA certificate to connect to RDS.

We have upgraded our RDS to use 2019 Certificate. I am looking for an image version which includes 2019 RDS Certificate.

I see a PR https://github.com/getredash/redash/pull/4304 which has 2019 CA Certificate but it is not tagged and released. The latest tag I see on git is 8.0.0. 

I am wondering is there any possibility of releasing new tagged image which includes 2019 certificate changes.

The current 2015 certificate expires on Feb 2020. 

We will be great-full if we get this done sooner.

Thanks,
Aristatle

**Comment by arikfr** [comment]
Did you upgrade your RDS already to use the new certificate?

**Comment by Aristatle-Subramaniam** [comment]
I upgraded RDS to use 2019 certificate but the existing redash image started failing, so reverted RDS to use 2015 certificate. But based on AWS Notification, we should upgrade all RDS to use 2019 certificate.

So wondering is there a way to get this done.

**Comment by arikfr** [comment]
You can create a custom image with the new certificate. I will try to post
instructions later on.

**Comment by Aristatle-Subramaniam** [comment]
Thanks, That would be great help.

**Comment by Aristatle-Subramaniam** [comment]
@arikfr Hope you find some time to help us on this.

**Comment by arikfr** [comment]
The image `redash/redash:8.0.2.b37747` includes the new CA files. It's hot from the oven,so  I didn't have the chance to test it yet. You're welcome to give it a try and let me know.

**Comment by Aristatle-Subramaniam** [comment]
Thanks @arikfr . Let me try and update you the result.

**Comment by arikfr** [comment]
@Aristatle-Subramaniam ping.

**Comment by Aristatle-Subramaniam** [comment]
Thanks  @arikfr . I am able to build and deploy redash/redash:8.0.2.b37747 image with new 2019 SSL certificate., It is working as expected. 

We truly appreciate all the time and effort you have put into release this image to help us.
