### ISSUE TITLE
Visualization Editor: X Column combo box does not accept keyboard input

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#4601]
### Issue Summary

You can search for column names in the Visualization Editor's combo boxes. But this feature is broken for the **X Column**. After I click the widget I don't see a blinking insertion point like on the other boxes.

<img width="605" alt="image" src="https://user-images.githubusercontent.com/17067911/73454610-09343c00-4334-11ea-9526-675d1fe983a0.png">

### Steps to Reproduce

1. Run a query with at least one column
2. Add a new visualization
3. Click the **X Column** combo box and _type_ a column name

I noticed this in my local environment as of 19c6d33. But also reproduced it on SaaS.

### Technical details:

* Redash Version: V9
* Browser/OS: FF
* How did you install Redash: Saas / Docker

**Comment by kravets-levko** [comment]
@susodapop Actually you cannot search any of column inputs, except of **Y Column** (just because it's a different type of input) :smile: So it's rather feature request than a bug :slightly_smiling_face:
