### ISSUE TITLE
Pages with "resolve" don't redirect guests to the login page

### ISSUE THREAD

**Issue by gabrieldutra** [getredash/redash#4605]
### Issue Summary

Currently only the Query Pages use it.

Opening an issue more to discuss how to proceed, since there was discussion regarding not using 'resolve' in pages anymore, I think this is the way we'll go.

One thing to see is that without the "resolve", the Query Pages will now need a Loading State (or just have nothing rendered until finish with loading like the dashboard pages).

### Steps to Reproduce

1. Open any query page logged out (can just open in incognito), like [this one](https://redash-preview.netlify.com/queries/327)
2. Verify that the 404 page takes precedence and it does not redirect to the login page

![resolve-issue](https://user-images.githubusercontent.com/3356951/73704452-eb6b2c00-46d1-11ea-9969-f19afab44918.gif)

### Technical details:

* Redash Version: Latest
* Browser/OS: *
* How did you install Redash: *

**Comment by kravets-levko** [comment]
Good catch @gabrieldutra! Luckily, yesterday I already started working on removing `resolve` feature :smile:
