### ISSUE TITLE
Problem with permissions

### ISSUE THREAD

**Issue by Tri0L** [getredash/redash#4609]
### Issue Summary

User with just `view_query,list_dashboards` permissions can execute query and see all data on dashboards.

### Steps to Reproduce

1. Redash Version: 8.0.0+b32245 (a16f551e)
2. Create group with permissions view_query,list_dashboards
3. Open any dashboard

### Expected
User without `execute_query` permission can't see any data.

**Comment by arikfr** [comment]
It might be a case of confusing naming, but view_query means they can see query and its results. They can also refresh the queries they have access too. 

If you want to limit their access, you can move them to a different group and assign relevant permissions to relevant data sources. 

I'm closing this, but you're welcome to continue conversation.

**Comment by Tri0L** [comment]
Which difference between `execute_query` and `view_query`?

**Comment by arikfr** [comment]
Without `execute_query` you can't execute adhoc queries (only already saved ones).
