### ISSUE TITLE
Dashboard editing permissions not working

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#4612]
### Issue Summary

Suppose user **A** shares dashboard edit permissions with user **B**. When user **B** visits the dashboard, there is no edit button. User **B** also can't make a `POST` api call with changes.

### Steps to Reproduce

1. Ensure the permissions feature flag is ticked.
2. Share dashboard edit permissions with another user
3. Observe the other user does not have an edit button when visiting the dashboard.

### Technical details:

* Redash Version: V9 
* Browser/OS: FF & API client
* How did you install Redash: SaaS

**Comment by gabrieldutra** [comment]
@susodapop, I tested in here, it looks like it's a frontend only issue as I could edit a dashboard with no problems after changing how the check is made on the page (will open a PR, so you can confirm it).
