### ISSUE TITLE
Resend Invitation link is broken when redash is configured to use MULTI_ORG

### ISSUE THREAD

**Issue by drumbsd** [getredash/redash#4619]
### Issue Summary

When create a new user, redash is configured with MULTI_ORG=True and SMTP is not configured, if you try to access to link that is provided by redash to setup the password:

https://foo.bar.com/invite/IjEdcdcd.ER7udscsiCslt-i_RMuScVsdcsdDWtEt9g

You see that in the URL miss the organization name (in this case "default" ) since is the default organization. Indeed you have to transform this URL to have the correct link to create a new passowrd.

https://foo.bar.com/default/invite/IjEdcdcd.ER7udscsiCslt-i_RMuScVsdcsdDWtEt9g

### Steps to Reproduce

1. Configure redash to use multi organizations.
2. Create a new user, under pending invitations, click on the link that is displayed after press the "Resend Invitation". 

### Technical details:

* Redash Version: 8.0.0
* Browser/OS: Chrome
* How did you install Redash: From docker with setup.sh

**Comment by rauchy** [comment]
Thanks for reporting @drumbsd. Can you make sure you have a the name of your host set up in the `REDASH_HOST` environment variable?

**Comment by drumbsd** [comment]
Hello, yes I tried now using REDASH_HOST environment variable set, but the issue still persists.

**Comment by drumbsd** [comment]
Sorry my fault, setting REDASH_HOST problem seems fixed. Many thanks.
