### ISSUE TITLE
Query/Dashboard list pages: clarify how tags are used

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#4628]
> Perhaps adding "AND" or "+" between selected tags in not found message could reduce doubts related with tag filtering. But Anyway thanks for your reply!

_Originally posted by @ptsilva in https://github.com/getredash/redash/issues/4557#issuecomment-582173490_

Let's implement this (add `+` / `AND` between tags)

**Comment by ajkovar** [comment]
Hi there.  Nice project.  Looking to contribute a bit.  Anyone mind if I grab this one?
