### ISSUE TITLE
Add setting to hide Plotly mode bar

### ISSUE THREAD

**Issue by daniellangnet** [getredash/redash#4632]
I find that the "mode bar" on Plotly charts can be confusing to people and doesn't add any value in our use of Redash. Hiding it is as simple as adding `displayModeBar: false` to the Plotly configuration. 

I'm happy to submit a PR and make it a setting on the organization ("Hide Plot.ly mode bar"), but before doing so wanted to check if there was support for this idea?

**Comment by arikfr** [comment]
@daniellangnet definitely don't mind adding this setting. You're welcome to submit this PR 👍
