### ISSUE TITLE
Clickhouse column name encoding problem

### ISSUE THREAD

**Issue by erels** [getredash/redash#4677]
### Issue Summary

Alias column name contains non 'latin-1' characters return encoding  error.
For example : select count(*) as 'כמות'…

**Error message**: 'latin-1' codec can't encode characters in position 285-288: Body ('כמות') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

BTW, This works fine with other data source like mysql.

### Steps to Reproduce

1. This is the first step
Create a query with ClickHouse as the data source

2. This is the second step, etc.
Add a column alias in utf8 chars like : select colum1 as 'ש'

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I expected to see the column alias like I do with mysql data source .
No problem with the 'utf-8' data,  so probably column names should support 'utf-8' charset as well.
This used to work with the older version (v8)
### Technical details:

* Redash Version:
9.0.0-alpha
* Browser/OS:
 Chrome
* How did you install Redash:
Docker Based Developer Installation

**Comment by arikfr** [comment]
I think that #4627 might fix this. What commit are you on?

**Comment by erels** [comment]
Im on 9.0.0-alpha
#4627 looks very similar but its more about the email then the actual data.
Probably, the fix should be similar as well  (but  here encode the sql data that is going to Clickhouse).

**Comment by erels** [comment]
I fixed it in a similar way like #4627
[4677](https://github.com/getredash/redash/compare/master...erels:4677-Clickhouse-column-name-encoding-problem)

**Comment by arikfr** [comment]
Just to confirm, the version you had with the problem, already had `data` sent as is without encoding?

**Comment by erels** [comment]
Correct. I just appended the encoding to the "data" that was there already and tested it.
