### ISSUE TITLE
Test an oracle connection make the application cash

### ISSUE THREAD

**Issue by Yuschow** [getredash/redash#4716]
### Issue Summary

when i test an oracle connection, it failed. Although i don't know the reason, but this behavior make the application to cash.  every page will show 404. 
But this phenomenon will not occur in my local docker environment, very strange.
what's more, when i input an incorrect connection information, it will return error normally, and the app will not crash.

![WechatIMG53](https://user-images.githubusercontent.com/40142872/76182377-a621a900-61ff-11ea-84c5-64ca0bc75a96.png)

<img width="1214" alt="WechatIMG54" src="https://user-images.githubusercontent.com/40142872/76182736-f3524a80-6200-11ea-8a7a-d93daedcfce1.png">

### Steps to Reproduce

1. open an exists oracle datasource
2. click connection button

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:9.0.0
* Browser/OS:mac
* How did you install Redash:docker

**Comment by guidopetri** [comment]
@Yuschow hey! Are you still observing this error with the latest version of redash? We have a `preview` image on dockerhub you can use to test.

**Comment by justinclift** [comment]
We've updated a bunch of the backend Oracle stuff recently too, so it's pretty likely Oracle data sources work ok.

If something does turn out to be wrong, then @snickerjp will probably want to know about it so it can be fixed. :smile:
