### ISSUE TITLE
Users in the same group can copy and paste through the browser for automatic login

### ISSUE THREAD

**Issue by cosunj** [getredash/redash#4719]
Problem Summary
A uses chrome to log in with admin permissions redash, then selects a user B in the group to modify the user name, and then pastes the URL of the current user B into the browser tab to open, and then automatically logs in to B.

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by arikfr** [comment]
What version of Redash are you using?

Arik

**Comment by cosunj** [comment]
It is v6.0.0

**Comment by arikfr** [comment]
It looks like you're using an unreleased version of Redash. This bug was in the master branch after the v6 release and before it was marked as v7. It was fixed in #3396.
