### ISSUE TITLE
Dashboards accessed via public link ignoring static parameter value

### ISSUE THREAD

**Issue by Deshawnz** [getredash/redash#4721]
I seem to have hit an issue with regards to sharing public dashboards with static parameters. 

Redash Version: 8.0.1+b33387 (cd13c978).

When dashboards are accessed via the public link, static parameters are ignored, and default to the last parameter saved to the underlying query/visualization. 

This causes a major issue when trying to restrict the data a user can view when accessing a shared dashboard, as the static parameter value that restricts the data returned is bypassed.

Any workaround, solution, feedback is appreciated.

**Comment by gabrieldutra** [comment]
Hi @Deshawnz, #4038 looks like the same issue, I quickly tested it in our preview environment and this issue does not seem to be happening in there. So, a fix for your problem should arrive with v9 :slightly_smiling_face:

**Comment by Deshawnz** [comment]
Thank you @gabrieldutra.  Is there a release date or estimated release date for v9?
