### ISSUE TITLE
Python query runner cannot use "print" function in 9.0.0-alpha

### ISSUE THREAD

**Issue by bryanyang0528** [getredash/redash#4725]
### Issue Summary

Python version: 3.7.6
Redash version: 9.0.0-a;pha
Python query runner cannot use "print" function in 9.0.0-alpha

### Steps to Reproduce

1. export REDASH_ENABLED_QUERY_RUNNERS=redash.query_runner.python
2. Use python query runner
3. print('x') and execute it

<img width="1079" alt="Screen Shot 2020-03-11 at 12 57 18" src="https://user-images.githubusercontent.com/5171607/76383771-e156e000-6397-11ea-8406-413a579f8cc4.png">

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

* In previous version, if I call `print`, it will be put in the `log` section.

<img width="1356" alt="Screen Shot 2020-03-11 at 12 54 21" src="https://user-images.githubusercontent.com/5171607/76383654-7907fe80-6397-11ea-8fd6-e847091985b1.png">

* But in the current version, `print` will not work
<img width="1440" alt="Screen Shot 2020-03-11 at 12 56 07" src="https://user-images.githubusercontent.com/5171607/76383728-b2406e80-6397-11ea-8506-ee5bfe6a845e.png">

 

### Technical details:

* Redash Version:  9.0.0-a;pha
* Browser/OS: default Docker 
* How did you install Redash: Docker

**Comment by sudarshanbasumatary** [comment]
Exactly the same issue when self-hosting.

We fixed it by updating the CustomPrint class in Python query runner.
Created a pull request for the same: https://github.com/getredash/redash/pull/4730
