### ISSUE TITLE
custom HTML link with "target="_blank"" in column cannot open in new tab

### ISSUE THREAD

**Issue by myonlylonely** [getredash/redash#4728]
### Issue Summary

I want to show several links in a single column, and the links should be opened in new tab. The following example worked in Redash 8.0, but not working in 9.0. This is the link to the deploy preview: https://redash-preview.netlify.com/queries/345/source

### Steps to Reproduce

1. Build a column with mutiple links.

``` sql
SELECT 
       '<a target="_blank" href="https://www.google.com"><font color="red">Google</font></a><br/>
       <a target="_blank" href="https://www.facebook.com/"><font color="green">Facebook</font></a><br/>
       <a target="_blank" href="https://twitter.com/"><font color="orange">Twitter</font></a>' 
AS test ;
```
![image](https://user-images.githubusercontent.com/8188177/76488247-d5365580-645f-11ea-9a67-4943af653143.png)

2. Click the link, it opens in the current window. It ignored the ```target="_blank"``` property. In Redash 8.0, it worked as I expected.

### Technical details:

* Redash Version: 9.0
* Browser/OS: Chrome
* How did you install Redash: Docker

**Comment by kravets-levko** [comment]
Fixed in getredash/redash#4729
