### ISSUE TITLE
Redash fails to start via docker-compose

### ISSUE THREAD

**Issue by ezkl** [getredash/redash#4739]
# Issue Summary
Redash cannot be started from scratch using `docker-compose` due to recent upstream changes to the `postgres` docker image. This issue was also discussed recently on the [redash forums](https://discuss.redash.io/t/unable-to-create-docker-based-development-environment/5595/11).

### Steps to Reproduce
**NOTE:** These steps should be run on a "fresh" install without existing docker images or anonymous volumes. This can be reproduced by using `docker-compose down` with additional flags for removing anonymous volumes and referenced images. I've not included the full command here for fear people will copy and paste and destroy data unintentionally.

1. `git clone git@github.com:getredash/redash.git`
2. `cd redash && docker-compose up -d` 

### Technical details:
After running `docker-compose up`, the `postgres` container prints the following error to the logs and exits before being restarted and repeating the same process again: 
```
postgres_1   | Error: Database is uninitialized and superuser password is not specified.
postgres_1   |        You must specify POSTGRES_PASSWORD to a non-empty value for the
postgres_1   |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
postgres_1   |
postgres_1   |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
postgres_1   |        connections without a password. This is *not* recommended.
postgres_1   |
postgres_1   |        See PostgreSQL documentation about "trust":
postgres_1   |        https://www.postgresql.org/docs/current/auth-trust.html
```

Changes were recently made to the `docker-entrypoint.sh` file packaged with new `postgres` docker images (including `postgresql:9.5-alpine`) that will stop the database from being initialized unless a password is set (via `$POSTGRES_PASSWORD`) or by allowing connections from all hosts (by setting `$POSTGRES_HOST_AUTH_METHOD=trust`.)

You can see the relevant [PR](https://github.com/docker-library/postgres/pull/658) and subsequent [discussion](https://github.com/docker-library/postgres/issues/681) for specifics.

I forked redash and [pushed a branch](https://github.com/getredash/redash/compare/master...ezkl:docker-compose-postgres-fix) including a small change to the `docker-compose.yml` that sets `POSTGRES_HOST_AUTH_METHOD` to `trust`. I'll open a PR momentarily.

**Comment by shnayan** [comment]
Try setting the environment variable - 'POSTGRES_PASSWORD' under postgres. you can keep it empty as well.

**Comment by ezkl** [comment]
> Try setting the environment variable - 'POSTGRES_PASSWORD' under postgres. you can keep it empty as well.

This may have worked in previous builds of the image before the most recent set of upstream changes were made, but [this line](https://github.com/docker-library/postgres/blob/master/9.5/docker-entrypoint.sh#L109) explicitly tests (via [`-z`](https://linux.die.net/man/1/test)) whether the length of `$POSTGRES_PASSWORD` is zero.
