### ISSUE TITLE
Angled brackets' content not displayed on table

### ISSUE THREAD

**Issue by colonelchlorine** [getredash/redash#4745]
### Issue Summary

The issue is that angled bracket pairs & their contents are replaced with an empty string in either the Ant library or in how Redash implements it in `client/app/visualizations/table/Renderer.jsx`.

### Steps to Reproduce

A simple query with a string with an angled bracket demonstrates this bug: `select 'BracketTest1[]{}<>', 'BracketTest2[a]{b}<c>'`

Purely angled brackets with no content `<>` is displayed correctly.

![image](https://user-images.githubusercontent.com/1085938/77168696-a0915200-6a8e-11ea-8671-22882daf4b3e.png)

Redash users obviously don't know that there's missing data there. However it displays fine when rendering visualizations.

Could be something related to Ant library because in Redash master package.json, it's using version 
3.19.7, but on https://codesandbox.io/s/nwqgf (Ant table example) I can add in the brackets used above into the `data` and it works fine. That is running version 4.0.3

### Technical details:

* Redash Version: Version: 7.0.0+b17535 (15c815fb)
* Browser/OS: Chrome 80.0.3987.132 but this has been happening in Chrome for several versions
* How did you install Redash: Not sure ... IT did it :)

**Comment by kravets-levko** [comment]
Hi @colonelchlorine! Please untick "Allow HTML content" checkbox in table editor:

![image](https://user-images.githubusercontent.com/12139186/77171956-e3225100-6ac5-11ea-8043-b664a78f00ec.png)
![image](https://user-images.githubusercontent.com/12139186/77171984-eae1f580-6ac5-11ea-9b96-2d52b1392fcd.png)

or manually html-escape brackets:

![image](https://user-images.githubusercontent.com/12139186/77172041-03521000-6ac6-11ea-8fdc-4258c9fa367c.png)

**Comment by kravets-levko** [comment]
Also a quick explanation why you encounter this "bug": `<c>` is considered an unknown HTML tag, and therefore removed; `<>` is not a tag so it's kept. Very limited set of tags is allowed for table cells in HTML mode, like `<a>`, `<b>`, `<i>`, etc., other tags are removed.

**Comment by colonelchlorine** [comment]
Fantastic @kravets-levko! Completely forgot about that setting. Strange that it's defaulted to true if you ask me - but might just be my company's use case (C# generic method type parameters).

**Comment by kravets-levko** [comment]
It default to `true` because of backward compatibility (before we implemented settings for Table visualization it was the default behavior).
