### ISSUE TITLE
schema can be displayed but execute sql waiting all the time（padding）

### ISSUE THREAD

**Issue by getixin** [getredash/redash#4754]
### Issue Summary

schema can be displayed but execute sql waiting all the time（padding）
win10 chrome 
data source Mysql Mongodb Postgressql all can not work

### Steps to Reproduce

1. Create Query
2. select * from core_log;
3. execute sql

no result，execute sql can`t be cancel,  always “Query in queue… “

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:  8.0.0+b32245 (a16f551e)
* Browser/OS: chrome
* How did you install Redash: docker

**Comment by arikfr** [comment]
It's likely that your workers aren't running or busy with other queries. 

Anyway, this looks like a setup issue and not necessarily a problem with Redash. If you still need help with this, I'll appreciate if you open a thread in our forum: https://discuss.redash.io/c/support/support-self-hosted.

Thanks.

**Comment by getixin** [comment]
Thank you very much. is the workers not run
