### ISSUE TITLE
Scheduled queries not working and queued query count keep increasing after upgrading to latest v9 preview

### ISSUE THREAD

**Issue by myonlylonely** [getredash/redash#4764]
### Issue Summary

Scheduled queries not working and queued query count keep increasing after upgrade to latest v9 preview

### Steps to Reproduce
After upgrading to latest preview image, scheduled queries stopped working any more. Even I change all the scheduled queries to never update, the queued queries count in the system status keep increasing. I tried to flush the redis, the queued query count still keep increasing.

![F4956952-FFA6-47E4-BE42-80CB9CF1A067](https://user-images.githubusercontent.com/8188177/78056520-df40d980-73b7-11ea-9c7e-47390a12d192.jpeg)

Is there any logs that I can provide to you?

### Technical details:

* Redash Version: v9
* Browser/OS: Chrome
* How did you install Redash: Docker

**Comment by lihan** [comment]
@myonlylonely Have you started both scheduler and worker process?

**Comment by myonlylonely** [comment]
> @myonlylonely Have you started both scheduler and worker process?
> There is a change in V9 which you need to start RQ Worker and RQ Scheduler. See more on this page
> https://redash.io/help/open-source/dev-guide/setup

Should the docker-compose.yml file be updated?

**Comment by myonlylonely** [comment]
I managed to make it work.
```
# docker-compose run -d server manage rq schedule
# docker-compose run -d server manage rq worker
```
