### ISSUE TITLE
docker install error

### ISSUE THREAD

**Issue by magix** [getredash/redash#4769]
### Issue Summary
I install latest docker of   redash 

bug  when i use docker-compose up  to start up . this error is come out .

worker_1     | [SQL: SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, queries.id AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, queries.name AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, queries.search_vector AS queries_search_vector, queries.tags AS queries_tags, query_results_1.id AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at 
worker_1     | FROM queries LEFT OUTER JOIN query_results AS query_results_1 ON query_results_1.id = queries.latest_query_data_id 
worker_1     | WHERE queries.schedule IS NOT NULL ORDER BY queries.id]
worker_1     | (Background on this error at: http://sqlalche.me/e/f405)
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
worker_1     |     cursor, statement, parameters, context
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
worker_1     |     cursor.execute(statement, parameters)
worker_1     | psycopg2.errors.UndefinedTable: relation "queries" does not exist
worker_1     | LINE 2: FROM queries LEFT OUTER JOIN query_results AS query_results_...
worker_1     |              ^
worker_1     | 
worker_1     | 
worker_1     | The above exception was the direct cause of the following exception:
worker_1     | 
worker_1     | Traceback (most recent call last):
worker_1     |   File "/usr/local/lib/python3.7/site-packages/rq/worker.py", line 822, in perform_job
worker_1     |     rv = job.perform()
worker_1     |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 605, in perform
worker_1     |     self._result = self._execute()
worker_1     |   File "/usr/local/lib/python3.7/site-packages/rq/job.py", line 611, in _execute
worker_1     |     return self.func(*self.args, **self.kwargs)
worker_1     |   File "/app/redash/tasks/queries/maintenance.py", line 77, in refresh_queries
worker_1     |     for query in models.Query.outdated_queries():
worker_1     |   File "/app/redash/models/__init__.py", line 633, in outdated_queries
worker_1     |     for query in queries:
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3342, in __iter__
worker_1     |     return self._execute_and_instances(context)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3367, in _execute_and_instances
worker_1     |     result = conn.execute(querycontext.statement, self._params)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
worker_1     |     return meth(self, multiparams, params)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
worker_1     |     return connection._execute_clauseelement(self, multiparams, params)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
worker_1     |     distilled_params,
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
worker_1     |     e, statement, parameters, cursor, context
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
worker_1     |     util.raise_from_cause(sqlalchemy_exception, exc_info)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
worker_1     |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
worker_1     |     raise value.with_traceback(tb)
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
worker_1     |     cursor, statement, parameters, context
worker_1     |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
worker_1     |     cursor.execute(statement, parameters)
worker_1     | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "queries" does not exist
worker_1     | LINE 2: FROM queries LEFT OUTER JOIN query_results AS query_results_...
### Steps to Reproduce

1. install 
git clone https://github.com/getredash/redash.git
cd redash
docker-compose run --rm server create_db
npm install
npm run build
docker-compose up

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:Docker version 19.03.8, build afacb8b
* CentOS Linux release 7.7.1908 (Core)

**Comment by koooge** [comment]
It looks like the setup procedure is wrong.
https://redash.io/help/open-source/dev-guide/docker

**Comment by justinclift** [comment]
@magix Since you're running CentOS 7, it's probably easiest to just use my CentOS 7 specific version of the Redash "setup.sh" script:

&nbsp; &nbsp; https://github.com/justinclift/redash/blob/redash-centos7/setup/setup.sh

```
$ curl -OL https://github.com/justinclift/redash/raw/redash-centos7/setup/setup.sh
$ chmod +x setup.sh
$ ./setup.sh
```

I keep it reasonably updated. :smile:

Just tested it in a CentOS 7 VM again now, and confirmed it's (still) working fine.

**Comment by arikfr** [comment]
If you plan on using this setup for usage, then I recommend checking out @justinclift's script. If you plan on using this for development, then it's better to figure out what went wrong.

Can you try running `docker-compose run --rm server create_db` again and then try `up` again? If it still fails, can you share the output of the `create_db` step?

**Comment by yankeeguyu** [comment]
You should run command docker-compose up, if this finish, then run docker-compose run --rm server create_db, it works for me.

**Comment by guidopetri** [comment]
@magix were you able to run the above commands?
