### ISSUE TITLE
JSON with u prefix

### ISSUE THREAD

**Issue by pvanderlinden** [getredash/redash#4806]
If you download a table with json data (postgresql), the CSV contains illegal json, all strings are prefixed with a `u`.

Example:

Content in database:
`{'test': 'json'}`
CSV export:
`{u'test': u'json'}`

### Technical details:

* Redash Version: 8.0.0.b32245
* Browser/OS: Not relevant
* How did you install Redash: docker (kubernetes)

**Comment by susodapop** [comment]
This is fixed in V9.

I duplicated it on our [demo instance](http://demo.redash.io/queries/8658/source) (V7) but could not recreate in the [preview instance](https://redash-preview.netlify.app/queries/364).
