### ISSUE TITLE
Redpush to manage Redash queries as code, has Redash planned to create offical tool?

### ISSUE THREAD

**Issue by stephane-klein** [getredash/redash#4812]
Hi,

I need to manage my Redash queries [as code](https://en.wikipedia.org/wiki/Infrastructure_as_code).

I found this [Redpush](https://github.com/TripElephant/redpush) from this [Discuss Thread](https://discuss.redash.io/t/redpush-a-tool-to-manage-redash-queries-as-code/2324/7).

Questions:

- Are there other tools like Redpush?
- Is there one official tool to manage Redash queries as code?
- If not:
  -  What do you think about add Redash project link in Redash documentation?
  - Have you planned to create official Redash queries as code tool?

Best regards,
Stéphane

**Comment by stephane-klein** [comment]
> Please use our forum to get help.

Posted here: https://discuss.redash.io/t/redpush-to-manage-redash-queries-as-code-has-redash-planned-to-create-offical-tool/6044

**Comment by arikfr** [comment]
@stephane-klein thank you for using the forum.
