### ISSUE TITLE
Public Dashboard with 6 Dropdowns Does Not Update on Selection

### ISSUE THREAD

**Issue by brad-natelborg** [getredash/redash#4818]
### Issue Summary

I have a dashboard with 6 different dropdowns (all dashboard level parameters).  All 6 of these filters apply to 7 different widgets on the dashboard (a couple tables, a few graphs, etc.) The dashboard works great when logged in as a Redash user.  When using the public page, however, I can make selections in the dropdowns and nothing changes in the widgets.  Almost like it just ignores the dropdowns.

I'm not sure if the # of filters is the problem?  Or perhaps the data in the dropdowns (all just text fileds)?

### Steps to Reproduce

I would expect the dashboard to work the same on the public page vs. when I'm logged into the site.

### Technical details:

* Redash Version: 8.0.0
* Browser/OS: Chrome/Windows 10
* How did you install Redash:

**Comment by brad-natelborg** [comment]
Think I found out the real source of the bug:

If your query parameters names don't match EXACTLY in all of your queries, they don't appear to work on a public page as dashboard level parameters.  So the work around is to name them all exactly the same, but this should work without naming them exactly, especially considering it works fine when logged in.

**Comment by susodapop** [comment]
I can't reproduce this behavior on our preview instance unless I use dropdown list type parameters where the values don't match. As shown [here](http://preview-backend.redashapp.com/public/dashboards/ytw1zrzhQFZru1E263mo1XQ6BvzJsLIa5LjDqQ93?org_slug=default&p_parameter1=Foo&p_parameter2=Foo). The second widget has two parameters that are mapped to the dashboard-level widgets. But their values are restricted to "Mickey" and "Mouse". So if I try to set them to "Foo" or "Bar" using the widgets, nothing happens.

If I update the query parameter definitions to permit "Foo" and "Bar" for values then changing the parameter value works as expected whether logged-in or not.

Either way, this behavior is the same for logged-in users and public visitors.

**Comment by brad-natelborg** [comment]
@susodapop Thanks for that info.  Mine were all the same content, but for some reason it wasn't working until I named them all the same as well in each query.  Once I did that, I was able to resolve the issue.

**Comment by susodapop** [comment]
That makes sense. But it *should* work when the names don't match. That's why we have parameter mapping on Dashboards in the first place.

Prior to the parameter mapping workflow we used a "Global" parameter toggle on dashboards. This approach required the parameters share the same name. The mapping workflow was added specifically to make that unnecessary.

**Comment by brad-natelborg** [comment]
Yeah, agreed.  Since I got mine working, I can close this.  I'll leave it up to you if you want to investigate further.  If I see something in future, I'll open a different ticket.
