### ISSUE TITLE
Fix ldap3 authentication raise error "LDAPBindError: None"

### ISSUE THREAD

**Issue by hombin** [getredash/redash#4824]
### Issue Summary:

LDAP authentication with ldap3 requires a conn "bind" after generating ldap server connection.

### Steps to Reproduce：

1. pip install ldap3
2. ADD "conn.bind()" to https://github.com/getredash/redash/blob/cfc82156c2f6c7f4f3d466fa666d882489840762/redash/authentication/ldap_auth.py#L83
3. Restart redash 

### Technical details:

- Redash Version: v8.0.0 
- Browser/OS: Chrome/OSX
- How did you install Redash: docker

**Comment by susodapop** [comment]
Redash uses `auto_bind` for its `ldap3` connections so an explicit call to `.bind()` is not required.

From the `ldap3` [docs](https://ldap3.readthedocs.io/en/latest/tutorial_intro.html):

>  The auto_bind=True parameter forces the Bind operation to execute after creating the Connection object. You have now a full working anonymous session open and bound to the server with a synchronous communication strategy:
