### ISSUE TITLE
How can I change OpenStreetMap for Other source, anybody could gives me some advice

### ISSUE THREAD

**Issue by wenwan1** [getredash/redash#4825]
We use GitHub only for bug reports 🐛

Anything else should be posted to https://discuss.redash.io 👫

🚨For support, help & questions use https://discuss.redash.io/c/support
💡For feature requests & ideas use https://discuss.redash.io/c/feature-requests

Alternatively, check out these resources below. Thanks! 😁.

- [Forum](https://disucss.redash.io)
- [Knowledge Base](https://redash.io/help)

**Comment by susodapop** [comment]
Please post questions like this on our [user forum](discuss.redash.io).

**Comment by wenwan1** [comment]
Sorry for my unintentional behavior., won’t happen. 

发送自 Windows 10 版邮件应用

发件人: Jesse
发送时间: 2020年4月23日 23:44
收件人: getredash/redash
抄送: wenwan1; Author
主题: Re: [getredash/redash] How can I change OpenStreetMap for Othersource, anybody could gives me some advice (#4825)

Please post questions like this on our user forum.
