### ISSUE TITLE
Pie charts display bad data on mouse-over

### ISSUE THREAD

**Issue by jrmuizel** [getredash/redash#4827]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. Mouse over the 41.7% and 44.6% slices of "webrender why not release?" on https://sql.telemetry.mozilla.org/dashboard/webrender

2. The popups say "0.01% (2,341)" "1.14% (529,596)" which makes no sense give the percentages on the actual pie-chart

### Technical details:

* Redash Version: 9.0.0+alpha
* Browser/OS: Firefox + macOS
* How did you install Redash: N/A

**Comment by susodapop** [comment]
Please provide more detail. There's nothing actionable here because we can't see your private Redash instance. Stated another way: how can we reproduce the issue?

**Comment by jrmuizel** [comment]
Ah sorry. I didn't realize it wasn't public. Here's the dashboard: https://sql.telemetry.mozilla.org/public/dashboards/Zo3A3uEtmUIEyhA5hRpSHPFtNXJ0BzPxtTKPUxSJ?org_slug=default

**Comment by susodapop** [comment]
Sorry to be a stickler but that's still not enough. While it's clear something is out of whack it's impossible to tell what that might be. We need to see the _actual data_ behind the chart so we can reproduce it on our end. You can paste the CSV data in your issue description.

**Comment by jrmuizel** [comment]
x-column is count, y-column is wr_qualified
```csv
count,webrender,wr_qualified
31,disabled,blocked-screen-too-large
19471339,opt-in,denied
3,disabled,blocked-vendor-unsupported
14,disabled,blocked-has-battery
10849,unavailable,blocked
20275114,opt-in,blacklisted
2,unavailable,blocked-release-channel-battery
76,disabled,blocked-release-channel-battery
1456,unavailable-no-angle,blocked-has-battery
152,unavailable-no-gpu-process,blacklisted
788,blocked,blocked
260,unavailable-no-gpu-process,denied
5,unavailable,blocked-device-too-old
11,unavailable,blacklisted
552081,opt-in,blocked
1,opt-in,blocked-screen-unknown
141703,unavailable,available
4,unavailable-no-gpu-process,blocked-vendor-unsupported
8,unavailable-no-gpu-process,blocked-has-battery
6,unavailable-no-gpu-process,blocked-device-too-old
11,unavailable-no-gpu-process,blocked-screen-too-large
1224720,opt-in,blocked-device-too-old
4057,unavailable-no-angle,blocked-device-too-old
623682,opt-in,blocked-screen-too-large
15,unavailable-no-gpu-process,blocked-release-channel-battery
1091966,,
2162,disabled,blacklisted
210499,opt-in,blocked-vendor-unsupported
48,disabled,blocked-device-too-old
388,unavailable-no-gpu-process,available
42,unavailable,denied
2341,disabled,denied
5431,disabled,available
1231,unavailable-no-angle,blocked-vendor-unsupported
529596,unavailable-no-angle,blacklisted
2182169,opt-in,blocked-release-channel-battery
87366,opt-in,available
6,disabled,blocked
235547,opt-in,blocked-has-battery
```

**Comment by susodapop** [comment]
This isn't a bug. What's happening is your query returns multiple values per x-axis value which we would expect to cause issues. It's a different version of [this behavior](https://redash.io/help/user-guide/visualizations/chart-visualizations#Multiple-Records-per-X-axis-value).

The solution in our docs applies here:

> You can resolve this by filtering out the doubled entries on the X axis. Or revise the query to include a grouping field...

See the screenshots below.

### Current

<img width="1099" alt="Screen Shot 2020-04-24 at 6 24 52 AM" src="https://user-images.githubusercontent.com/17067911/80207752-5c94ee00-85f4-11ea-8ec9-a99f939c90a8.png">

### Grouping on `wr_qualified` field

<img width="1099" alt="Screen Shot 2020-04-24 at 6 24 44 AM" src="https://user-images.githubusercontent.com/17067911/80207760-5f8fde80-85f4-11ea-809d-a4941c8a9fa9.png">

There was a similar discussion on the [user forum](https://discuss.redash.io/t/wrong-label-view/5237) late last year.

**Comment by jrmuizel** [comment]
Ok, that's sort of surprising behaviour, but thanks for your help.
