### ISSUE TITLE
Filters: selected value not displayed in results

### ISSUE THREAD

**Issue by dasgr** [getredash/redash#4853]
### Issue Summary

The chosen value of a filter is not displayed in the query result table. A zero or blank is shown instead.

### Steps to Reproduce

This has been duplicated on the [preview instance](https://redash-preview.netlify.app/queries/374/source).

#### Step 1
Run this SQL against a query results data source.
```
WITH base(key,value, idx) AS
    (
    SELECT * FROM (
        VALUES
        ("foo", "bar", 1),
        ("foo", "baz", 1),
        ("bar", "foo", 2),
        ("bar", "baz", 2)
        )
    )

SELECT
    key as "key::filter",
    value,
    idx as "idx::filter"
FROM base
```
#### Step 2
Observe that whichever value you select in the filter does not appear on the results table.

#### Screenshots

![4853 demo](https://user-images.githubusercontent.com/17067911/80713044-703ec980-8ab8-11ea-859b-cba60d11ce6b.png)

The filtered value should be displayed as-is in the query result.

### Technical details:

* Redash Version: v9 Alpha
* Browser/OS: FF / MacOS
* How did you install Redash: SaaS / Preview

And also...

* Redash Version: current master branch (f37e3d5)
* Browser/OS: Google Chrome and Firefox.
* How did you install Redash: custom Helm cart

**Comment by susodapop** [comment]
@dasgr I rewrote your issue report to follow our format and reproduced on our end. Also added a screenshot which highlights the specific issues.

**Comment by dasgr** [comment]
@susodapop @susodapop thank you guys for fixing this! And sorry for the long reply :)
