### ISSUE TITLE
Can we support parse multi columns result

### ISSUE THREAD

**Issue by del-zhenwu** [getredash/redash#4875]
### Issue Summary

If there is multi columns query expression with mongodb query runner, it will not return the expected result on web. such as the following query:
```
{
    "collection": "doc",
    "query": {
        "metrics.type": "search_performance",
        "server.value.mode": "GPU",
        "index.index_type": "ivf_sq8",
        "search.nq": 1000,
        "search.topk": 1,
        "search.search_param.nprobe": 8
    },
    "fields": {
        "server.value.build_commit": 1,
        "metrics.value.search_time": 2
    },
    "sort": [{
        "name": "run_id",
        "direction": -1
    }],
    "limit": 10
}
```

### Steps to Reproduce
One PR`<Support multi column results with using mongo query runner #4836>` has been submit to make a workaround, I request some reviews on it.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by susodapop** [comment]
👋 @del-zhenwu we use the issue tracker exclusively for bug reports and planned work. The team will review your pull request when we have time.

**Comment by del-zhenwu** [comment]
The PR:https://github.com/getredash/redash/pull/4836 is still open, why
