### ISSUE TITLE
Help button in header not working

### ISSUE THREAD

**Issue by jezdez** [getredash/redash#4886]
### Issue Summary

When running latest master I can't seem to get the (?) in the header to open the help, could someone verify this on their end?

I'm not seeing errors in the console or terminal.

### Steps to Reproduce

1. Run Redash master (22f0030864af6d20008850de9032bf6f33c537cb)
2. Try to click on the (?) in the header to open the help, nothing happens.

### Technical details:

* Redash Version: 22f0030864af6d20008850de9032bf6f33c537cb
* Browser/OS: Firefox 76.0.1 on macOS 10.15.4
* How did you install Redash: Docker

**Comment by arikfr** [comment]
I noticed this in the vertical nav bar version, but thought we broke it there 😅 

@gabrieldutra related to recent changes to HelpTrigger?
