### ISSUE TITLE
The seconds format specifier is wrong when outputting to CSV

### ISSUE THREAD

**Issue by Blufe** [getredash/redash#4895]
### Issue Summary

The seconds format specifier is wrong when outputting to CSV.

### Steps to Reproduce

1. Specify "HH:mm:ss.SSS" for Time Format.
2. Execute a query that uses Time Format (eg. `SELECT CURRENT_TIMESTAMP()` in BigQuery).
3. Download CSV file.

Seconds will not be printed, unix time of the date-time data will be printed.
For example, "2020-05-15T19:34:36.664" will output "2020-05-15T19:34:1589538876664".

### Technical details:

* Redash Version: 8.0.2
* Browser/OS: `redash/redash:8.0.2.b37747`
* How did you install Redash:

**Comment by susodapop** [comment]
This can probably be fixed along with https://github.com/getredash/redash/issues/4820.

**Comment by arikfr** [comment]
The bug is here:

https://github.com/getredash/redash/blob/b1174855718b46aa6cf933dfbc25b112d21dbba3/redash/serializers/query_result.py#L11-L20

It translates `ss` to `%s`, which seems to be the unix timestamp... It also ignores `.SSS`.

**Comment by chulucninh09** [comment]
Just want to confirm, according to python docs [here](https://docs.python.org/3.7/library/datetime.html?highlight=strftime#strftime-strptime-behavior), the above code should be change to 
```python
 def _convert_format(fmt): 
     return ( 
         fmt.replace("DD", "%d") 
         .replace("MM", "%m") 
         .replace("YYYY", "%Y") 
         .replace("YY", "%y") 
         .replace("HH", "%H") 
         .replace("mm", "%M") 
         .replace("ss", "%S") 
         .replace("SSS", "%f")
     ) 
```

However, the string will be fixed at 6-digit microsecond, not 3-digit millisecond as the following screenshot
![image](https://user-images.githubusercontent.com/43906170/82662324-d94cd380-9c57-11ea-994d-20a7ba9341d5.png)

If you consider this behavior is not harmful to other functions, I can implement it and make PR.

**Comment by arikfr** [comment]
> If you consider this behavior is not harmful to other functions, I can implement it and make PR.

Considering it currently prints the Unix timestamp, having 6 digits instead of 3 should be a great step forward ;-)

A PR will be appreciated. Thanks!

**Comment by kravets-levko** [comment]
> However, the string will be fixed at 6-digit microsecond, not 3-digit millisecond as the following screenshot

I guess you can just cut off last three digits after formatting and it will work just fine

**Comment by arikfr** [comment]
@kravets-levko but then you need to know when microseconds are used or not.. easier to leave as is.

**Comment by chulucninh09** [comment]
> > However, the string will be fixed at 6-digit microsecond, not 3-digit millisecond as the following screenshot
> 
> I guess you can just cut off last three digits after formatting and it will work just fine

cutting a string after formatting needs extra implementation. I don't think we should do that way. I will stick with 6-digit solution and make a PR
