### ISSUE TITLE
Improve simplejson serialization

### ISSUE THREAD

**Issue by chulucninh09** [getredash/redash#4902]
https://github.com/getredash/redash/blob/a2217cc4ecfa5cd916c934c19a93848284cf984b/redash/utils/__init__.py#L71

Hi, I encountered an odd issue when tried to query my MongoDB database, that JSON.parse of axios kept telling me that it cannot parse json. After digging into the payload, it turned out python implements `nan` as float, and serialize it like a number, without double quotes.

![image](https://user-images.githubusercontent.com/43906170/82340603-9e5d5c80-9a19-11ea-932e-c394f328e49e.png)

For this problem, I think the best way is to add more handle to the JSONEncoder class to handle `nan` "float" type.
```python
        elif math.isnan(o):
            result = None
```

I will try first then make a PR

**Comment by kravets-levko** [comment]
I guess getredash/redash#4903 fixes this, so closing. Thank you @chulucninh09!
