### ISSUE TITLE
"Fork Query" is disabled outside of "View Source" mode

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#4923]
### Issue Summary

See screenshots. When viewing a query the fork link is disabled unless a user enters "View Source" mode.

#### Disabled
![first](https://user-images.githubusercontent.com/17067911/83022832-ba509780-9ff1-11ea-8388-728b0506067f.png)

#### Enabled

![second](https://user-images.githubusercontent.com/17067911/83022855-c3416900-9ff1-11ea-8bc9-dca38906c876.png)

### Steps to Reproduce

1. Visit any query
2. Click the `⋮` button to observe the fork option is disabled.
3. Click **Edit Source**
4. Click the `⋮` button to observe that the fork option is now enabled

This is a regression from V8.

### Technical details:

* Redash Version: v9 Alpha
* Browser/OS: Safari / MacOS
* How did you install Redash: SaaS / Preview Instance

**Comment by kravets-levko** [comment]
@susodapop I cannot reproduce this on master (at least on my local setup and on preview instance). Can you please share a link to the query with this issue (if possible), or check query and its datasource options?

**Comment by arikfr** [comment]
Levko, were you trying with an admin user? It happens only to non admins.

Arik

**Comment by susodapop** [comment]
@arikfr Is right. To reproduce it on the preview instance, log in as John Smith and visit any query.

**Comment by kravets-levko** [comment]
Confirmed. @arikfr Why can user list data sources, but cannot get even a minimum amount of info about particular one? This issue happens because to enable Fork button we need to know if query's data source is `view_only` or not. On source page we load all data sources anyway, so there we get DS from the list. On view query page we load DS directly, and API endpoint returns 403

**Comment by arikfr** [comment]
@kravets-levko the main reason is that there was no need for such API for non admins, so it was never implemented :)

**Comment by kravets-levko** [comment]
@arikfr Nevermind :slightly_smiling_face: That was a first question that crossed my mind, but later I thouht about it more and concluded  that it should stay as is, because changing that API may introduce new bugs.
