### ISSUE TITLE
Query doesn't not get queued because redash thinks it is already queued

### ISSUE THREAD

**Issue by pvanderlinden** [getredash/redash#4926]
### Issue Summary

A query will be marked as in queue forever

### Steps to Reproduce

Not exactly sure how to reproduce. This might have come from a redis restart (as redash doesn't support Redis HA with sentinel, a restart may cause some issues). Although the user probably started that query later then the restart. Redash stores that this specific query is queued and won't run it again (I can solve the issue by removing or adding `;` to the end of the query, to get it to create a new task).

### Extra digging
I'm not sure if this happened during redis restart or something else. Basic summary: the job lock still existed (actually for 3 queries, while no query was running at all), after I removed the job lock from redis, I could run the query again by refreshing the page (cancel won't work on these jobs)

### Technical details:

* Redash Version: 8.0.0
* Browser/OS: Chrome, Firefox, etc
* How did you install Redash: kubernetes (docker)

**Comment by arikfr** [comment]
These locks have a timeout, but it's pretty long (a few hours). We are experimenting with a clean up job that unlocks these locks if the job no longer exists. It looks something like this:

```python
def remove_ghost_locks():
    keys = redis_connection.keys("query_hash_job:*")
    locks = {k: redis_connection.get(k) for k in keys}
    jobs = list(rq_job_ids())

    count = 0

    for lock, job_id in locks.items():
        if job_id not in jobs:
            redis_connection.delete(lock)
            count += 1

    logger.info("Locks found: {}, Locks removed: {}".format(len(locks), count))
```

So far it seems good, so maybe makes sense to finally add here as well.

**Comment by pvanderlinden** [comment]
Do the workers send a heartbeat & shutdown message? If they do, the cleanup job could run when a worker shutdowns in an unclean way (crash, kill -9, etc). At least, I'm assuming this is the main reason this happens (main issue I can see are workers using to much memory, which means crash or forced shutdown by kubernetes)?

**Comment by arikfr** [comment]
#5087 added this job to run periodically.

**Comment by zhongjiajie** [comment]
@arikfr  If https://github.com/getredash/redash/pull/5087 fix this issue maybe we should close it
