### ISSUE TITLE
RedashGroups parameter: comma-separated list of groups?

### ISSUE THREAD

**Issue by lcgkm** [getredash/redash#4963]
Hi Guys,
We know it’s possible to configure the SAML provider to pass what groups the user should join by setting the RedashGroups parameter.
But I am no sure that the RedashGroups parameter should be a comma-separated list of groups if there are 2 or more. Or passing each group in separate tags.

- **passing each group in separate tags (see below)**

```
<saml2:Attribute Name=“RedashGroups”
                NameFormat=“urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified”>
                <saml2:AttributeValue xmlns:xs=“http://www.w3.org/2001/XMLSchema”
                    xmlns:xsi=“http://www.w3.org/2001/XMLSchema-instance” xsi:type=“xs:string”>admin</saml2:AttributeValue>
                <saml2:AttributeValue xmlns:xs=“http://www.w3.org/2001/XMLSchema”
                    xmlns:xsi=“http://www.w3.org/2001/XMLSchema-instance” xsi:type=“xs:string”>user</saml2:AttributeValue>
</saml2:Attribute>
```

- **pass groups in the same attribute value tag separated by commas (see below)**

```
<saml2:Attribute Name=“RedashGroups”
                NameFormat=“urn:oasis:names:tc:SAML:2.0:attrname-format:unspecified”>
                <saml2:AttributeValue xmlns:xs=“http://www.w3.org/2001/XMLSchema”
                    xmlns:xsi=“http://www.w3.org/2001/XMLSchema-instance” xsi:type=“xs:string”>admin,user</saml2:AttributeValue>
</saml2:Attribute>
```
Reference:
https://redash.io/help/user-guide/users/authentication-options

**Comment by lcgkm** [comment]
https://discuss.redash.io/t/redashgroups-parameter-comma-separated-list-of-groups/6426

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
