### ISSUE TITLE
Last column of schema overlaps with the next table name when number of columns are high

### ISSUE THREAD

**Issue by masterlittle** [getredash/redash#4987]
### Issue Summary

Sample 1 

![Screenshot 2020-06-22 at 2 01 32 PM](https://user-images.githubusercontent.com/13149023/85266390-6a021380-b491-11ea-89d2-ccb842ae5ba2.png)

Sample 2

![Screenshot 2020-06-22 at 2 02 08 PM](https://user-images.githubusercontent.com/13149023/85266401-6cfd0400-b491-11ea-8e3d-77279aa24189.png)

### Steps to Reproduce

- Add a datasource. I added Athena and Postgres.
- Refresh the schemas.
- Check a table with a lot of columns.
- Either he column is overlapping or the space between the last column and next table name is almost 0.

The should be proper spacing between the column names and next table names in schema view.

### Technical details:

* Redash Version: 9.0-beta
* Browser/OS: Firefox/Ubuntu 18
* How did you install Redash: Docker

**Comment by gabrieldutra** [comment]
I was able to reproduce this one now, but only on Firefox. Will investigate this further, but seems to be related for the font being a bit "thicker" on FF.

**Comment by gabrieldutra** [comment]
Solved in #5024, thanks for reporting @masterlittle! 🙂
