### ISSUE TITLE
连接Druid数据源查出来的结果是0.5但是前端展示1

### ISSUE THREAD

**Issue by 1964305774** [getredash/redash#4993]

**Comment by kravets-levko** [comment]
Hi @1964305774! We would really appreciate if you'll explain your problem in English. Also, please provide more details:

1. What you're trying to do?
2. What you expect to get?
3. What you're getting instead?
4. Why do you consider it's a bug?
5. Other info, like Redash version and installation type, OS type and version, browser version, etc.

Thank you!

**Comment by gabrieldutra** [comment]
I'm closing this for now, @1964305774 feel free to reopen if more information is provided.
