### ISSUE TITLE
Ability to configure analytics code

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#5]
The index.html template should have a place holder for analytics code, so users can plug in their own favourite analytics tool.

**Comment by shishirsharma** [comment]
This was removed in this https://github.com/getredash/redash/commit/fbb81b62d6c79f8e9381ac8973ac34739bfa6b41

What is the alternative of this feature. I want to add google analytics in Redash. What should I do.
 Add a line note

**Comment by shishirsharma** [comment]
For returning people you can put your custom code in ```/opt/redash/current/redash/templates/_includes/tail.html```

**Comment by arikfr** [comment]
Note that there is a way to specify additional path to load static assets from (`REDASH_STATIC_ASSETS_PATH` takes a list), then you can put your custom `tail.html` file there. This way it will be preserved between upgrades.
