### ISSUE TITLE
Stacked bar chart with manually set Y-axis min is cut on top

### ISSUE THREAD

**Issue by kravets-levko** [getredash/redash#5026]
### Steps to Reproduce

1. Create a stacked bar chart with few series
2. Go to Series tab and set some min value for Left Y Axis
3. The chart is cut on top (on a screenshot there is a quite large value for `s3` series (green one))

![image](https://user-images.githubusercontent.com/12139186/86448578-9cc4cb00-bd1f-11ea-9f35-cc9879bc6bde.png)

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

When max not set for Y-axis, it should auto-adjust to ensure that all data are visible.

### Technical details:

* Redash Version: master
* Browser/OS: Chrome 83, FF 78
* How did you install Redash: Docker, hosted Redash

**Comment by kravets-levko** [comment]
After getredash/redash#4904 the issue reproduces on every stacked bar chart.

**Comment by gabrieldutra** [comment]
This is reproducible in [here](https://deploy-preview-5019--redash-preview.netlify.app/queries/36#62) (this branch doesn't have #4904 yet). It looks like for Stacked bars it's computing their values separately when it should sum all of them:

![image](https://user-images.githubusercontent.com/3356951/86472737-06d87280-bd16-11ea-99d8-7b4cdfee501c.png)

(here it considers only the 1297, but should consider the sum of all the stacked values)

**Comment by kravets-levko** [comment]
The problem is in the function that computes Y-axis ranges. When data aren't stacked - it works fine. For line/area charts we implement stacking on our side - we sum values and update series, so in this case it works fine too. But for bar charts it gets non-stacked data, while Plotly stacks bars.

https://github.com/getredash/redash/blob/c6be5758ad07222b8ddde7b59cc3a48df359d6e6/viz-lib/src/visualizations/chart/plotly/utils.js#L27-L41
