### ISSUE TITLE
pivot table cannot be refresh in dashboard

### ISSUE THREAD

**Issue by peterlee0304** [getredash/redash#5028]
I found when I refresh dashboard page, pivot table can`t update data.

**Comment by gabrieldutra** [comment]
Hi @peterlee0304, can you provide more details?

Please try to follow the:
```
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:
```

In the issue description as such informations are very helpful to track the issue origin. You can also try to reproduce it in [our preview environment](http://redash-preview.netlify.app/), which runs our latest code version (the under develop, before release).

I'll close this for now, feel free to reopen when updating. Thanks! 🙂
