### ISSUE TITLE
Stacking breaks when using both left and right axes

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#5032]
### Issue Summary

Under some circumstances a stacked bar chart will hide some of the bars.

### Steps to Reproduce

Reproducing this one is easy but non-obvious. Make a chart visualization with at least three traces. Make two of the traces bars that use the left y-axis. Make the third a line that uses the right y-axis. Then set the visualization to stack. Under certain circumstances, the taller bar will overlap the smaller one making it invisible.

I reproduced it on the [preview instance](https://redash-preview.netlify.app/queries/395/source#683). 

### Working (all traces on the left y-axis)
![image](https://user-images.githubusercontent.com/17067911/86623471-4954b600-bf87-11ea-9186-73aae624ca55.png)

### Broken (bars on left y-axis, line on right y-axis)

![image](https://user-images.githubusercontent.com/17067911/86623588-76a16400-bf87-11ea-96cd-97c09f512620.png)

### Fixed (bars on left y-axis, line on right y-axis, stacking disabled)
![image](https://user-images.githubusercontent.com/17067911/86623916-021af500-bf88-11ea-9d56-b93269f86586.png)

### Technical details:

* Redash Version: V9 Beta
* Browser/OS: FF / Chrome / Safari
* How did you install Redash: SaaS

**Comment by gabrieldutra** [comment]
This seems related to #5026, you can check [here](https://deploy-preview-5029--redash-preview.netlify.app/queries/395/source#683) to see how it's showing after @kravets-levko fix (#5029).

**Comment by susodapop** [comment]
Thanks @gabrieldutra. That preview you shared fixes it. 

I'll update the the description on #5029 to show it fixes this issue.
