### ISSUE TITLE
A healthcheck endpoint not requiring auth

### ISSUE THREAD

**Issue by jakubgs** [getredash/redash#5040]
When self-hosting the service I'd like that have some kind `/api/health` endpoint I could query to check service status.
It could be as simple as a static `200` with `OK` return value, just to verify that the service is up.

Currently I'm using the `/static/unsupportedRedirect.js` endpoint as it returns `200` without authentication and is small.
I skimmed the `redash/handlers` folder and could not find anything fitting my use case. Sorry if I missed it.

**Comment by arikfr** [comment]
That’s what the /ping endpoint is for.

Arik

**Comment by jakubgs** [comment]
Oh, brilliant, thank you! Maybe I'm bling but I don't see it mentioned anywhere in documentation.

**Comment by doublerebel** [comment]
Also mentioned here: https://discuss.redash.io/t/public-health-check-endpoint/6397
Related: #1835

**Comment by guidopetri** [comment]
Closing as completed.
