### ISSUE TITLE
Python takes too much memory and CPU 

### ISSUE THREAD

**Issue by JerryYuanJ** [getredash/redash#5054]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. Clone the project
2. Create virtual env and run install scripts
3. Start running the server

It is normal at first, but after a few mins my Mac starts to become slow and here is the screenshot of the resource use:

![image](https://user-images.githubusercontent.com/26586458/87814490-6e55fc80-c896-11ea-8b59-a1297f3c299e.png)

### Technical details:

* Redash Version: 9.0.0-beta
* Browser/OS: MacOS version 10.14.6
* How did you install Redash: github

**Comment by arikfr** [comment]
Forum post: https://discuss.redash.io/t/why-python-takes-so-much-memery/6787/4
