### ISSUE TITLE
stuck at running 'docker-compose -f docker-compose.yml run --rm server create_db"

### ISSUE THREAD

**Issue by zhengr** [getredash/redash#5059]
### Issue Summary

when I run 

docker-compose -f docker-compose.yml run --rm server create_db 

the shell window stuck there for long time at  ibm-db install.

### Steps to Reproduce

After I comment the **ibm-db>=2.0.9** line in <u>requirements_all_ds.txt</u> and try again, it works fine. 

### Technical details:

* Redash Version:  redash-9.0.0-beta
* Browser/OS: macos
* How did you install Redash: 

cd redash-9.0.0-beta
npm install
npm run build
docker-compose -f docker-compose.yml run --rm server create_db
docker-compose -f docker-compose.yml up

**Comment by kravets-levko** [comment]
@zhengr A quick answer: the first time you run `docker-compose up/run` it has to build docker images, which includes installing dependencies. `ibm-db` is a driver for IBM DB2 database, and as many other drivers it may take some time installing it. When you'll run `docker-compose up/run` next time - it will use existing image and it will be a way much faster
