### ISSUE TITLE
When a query is using a filter, switching visualizations resets the filter value

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#5070]
### Steps to Reproduce

1. Open a query with a filter. Example: https://redash-preview.netlify.app/queries/413/source#742
2. Change filter value and switch to another visualization.

Expected result: you will see data in the other visualization based on the filter from previous one.
Actual: the filter value is being reset.

### Technical details:

* Redash Version: latest master

**Comment by kravets-levko** [comment]
Duplicate of getredash/redash#4944
