### ISSUE TITLE
how to start redash with docker images?

### ISSUE THREAD

**Issue by yankeeguyu** [getredash/redash#5074]
I build redash docker images, but now I don't know how to start it.

docker images like this:
![image](https://user-images.githubusercontent.com/46274612/88795532-c532ce80-d1d2-11ea-8532-c96e04129dd8.png)

so, How to start redash? I don't have Dockerfile and docker-compose.

Technical details:
Redash Version: 8.0.0
Browser/OS: MacOS & Chrome
How did you install Redash: docker images

**Comment by yankeeguyu** [comment]
> 👋 @yankeeguyu, we use the issue tracker exclusively for bug reports and planned work. However, this issue appears to be a support request. Please use [our forum](https://discuss.redash.io) to get help.

I look up https://discuss.redash.io/, it don't have my issue. Please help me, thanks!

**Comment by kravets-levko** [comment]
Hi @yankeeguyu! Create a new topic there and other users will help you. We use the issue tracker exclusively for bug reports and planned work, forum is for everything else. Thanks!

**Comment by yankeeguyu** [comment]
> Hi @yankeeguyu! Create a new topic there and other users will help you. We use the issue tracker exclusively for bug reports and planned work, forum is for everything else. Thanks!

Ok, but I am a fresh man, i don't find forum create a new post button. Thank you!
