### ISSUE TITLE
start redash images Exited(0)

### ISSUE THREAD

**Issue by yankeeguyu** [getredash/redash#5077]
I build redash docker images by myself. 
Like this:
![image](https://user-images.githubusercontent.com/46274612/88901662-a4768180-d283-11ea-8564-ef55157c0481.png)

I start Redash with `docker run -it redash_server /app/bin/docker-entrypoint`
![image](https://user-images.githubusercontent.com/46274612/88901381-4d70ac80-d283-11ea-8da1-de3a473f3308.png)

How to fix it?
Thanks, I look up forum, but i don't find this question. Please help me.

### Technical details:

* Redash Version: 8.0.0
* Browser/OS: MacOS/ chrome
* How did you install Redash: I want to start it in docker images.

**Comment by kravets-levko** [comment]
@yankeeguyu Please register on [our forum](https://discuss.redash.io/) and start a new topic there

![image](https://user-images.githubusercontent.com/12139186/88914519-6a998100-d26b-11ea-980b-49b44f1a83f6.png)

**Comment by yankeeguyu** [comment]
Thank you.

**Comment by yankeeguyu** [comment]
Hi @kravets-levko , this button don't show for me.
![image](https://user-images.githubusercontent.com/46274612/88917536-7f413d80-d29a-11ea-8ae4-a53bb7596d90.png)

**Comment by kravets-levko** [comment]
1. ensure that your browser supports js and it is enabled
2. disable extensions for the site, including ad blockers (there are no ads anyway)
3. log out, clear cookies and try to log in again

if that didn't help - please reach me.

**Comment by yankeeguyu** [comment]
Yes, I login up a new account, it works. Thank you!
