### ISSUE TITLE
Failed Query Alert doesn't show which Query failed 

### ISSUE THREAD

**Issue by ganeshapp** [getredash/redash#5093]
### Issue Summary

In Redash V9.beta when a query fails to execute, the email alert is sent to the owner of the query, but the body is blank and it doesn't have information on which query failed.

### Steps to Reproduce

1. Configure a query with some tables.
2. Save, Publish, Execute, schedule it.
3. Go to db and drop a table that the query uses.
4. Receive email when the scheduled job is executed, but with blank email. 

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

The same query failure in Redash V8, provides details of the Query. Screenshot of both V9 and V8 is attached.

### Technical details:

* Redash Version: V9.beta and multiple versions of Preview Redash V9.beta. 
* Browser/OS: Firefox, Chrome
* How did you install Redash:
setup.sh for V8 and then upgraded to V9.

V8 Alert:
<img width="1071" alt="Redash V8 Query Failure Alert" src="https://user-images.githubusercontent.com/24544974/89598746-88349f00-d898-11ea-8e2e-817c529b4d9a.png">

V9 Alert: 
<img width="1067" alt="Redash V9 Query Failure Alert" src="https://user-images.githubusercontent.com/24544974/89598824-cc27a400-d898-11ea-9522-fa47bd49feba.png">

**Comment by adamzwakk** [comment]
Looks like it was missing return statement, added pull request

**Comment by arikfr** [comment]
This was fixed in @adamzwakk's PR.
