### ISSUE TITLE
Bug: I found redash dashboard page Table widget sort error

### ISSUE THREAD

**Issue by yankeeguyu** [getredash/redash#5107]
I found that the Table Widget in the dashboard page can sort positive numbers, but for negative numbers, floating point numbers, and negative numbers are not supported.
Like this:
![image](https://user-images.githubusercontent.com/46274612/90309173-6ed6c700-df18-11ea-8ea3-81fc19726b8a.png)
![image](https://user-images.githubusercontent.com/46274612/90309180-7bf3b600-df18-11ea-99f8-79b218a30549.png)

I think this feature will still affect the user experience. Is there any way to modify it? Or is there a branch available? If so, please share with me, thank you, I can modify the source code by myself.

### Technical details:

* Redash Version: 8.0.0
* Browser/OS: MacOS & Chrome
* How did you install Redash: npm and python celery build by myself

**Comment by yankeeguyu** [comment]
This is a frontend bug.

**Comment by yankeeguyu** [comment]
@arikfr hi, this bug could be fix?

**Comment by arikfr** [comment]
I couldn't reproduce this here: https://redash-preview.netlify.app/queries/415/source. Maybe we fixed it already in v9? (I have a vague memory that we have, but not sure)

**Comment by yankeeguyu** [comment]
> I couldn't reproduce this here: https://redash-preview.netlify.app/queries/415/source. Maybe we fixed it already in v9? (I have a vague memory that we have, but not sure)


I still want to use version 8.0.0, so is there a PR to fix this bug?

**Comment by arikfr** [comment]
@yankeeguyu there should be a PR, but couldn't find it with a quick search. You can check the history... 

Another thing to confirm in your version: are you sure the database doesn't return strings instead of numbers?

**Comment by yankeeguyu** [comment]
> @yankeeguyu there should be a PR, but couldn't find it with a quick search. You can check the history...
> 
> Another thing to confirm in your version: are you sure the database doesn't return strings instead of numbers?

Yes, i make sure. It seems not, they treat all numbers as text or strings. I find this PR, but can't to find it.

**Comment by yankeeguyu** [comment]
> @yankeeguyu there should be a PR, but couldn't find it with a quick search. You can check the history...
> 
> Another thing to confirm in your version: are you sure the database doesn't return strings instead of numbers?


There are too many closed PRs, are there any good keywords that can let me find this PR? Thank you very much!

**Comment by yankeeguyu** [comment]
> @yankeeguyu there should be a PR, but couldn't find it with a quick search. You can check the history...
> 
> Another thing to confirm in your version: are you sure the database doesn't return strings instead of numbers?

![image](https://user-images.githubusercontent.com/46274612/90368908-68258c80-e09d-11ea-806d-68af6a9ce4f6.png)
The v9.0 this bug already were fixed.

**Comment by yankeeguyu** [comment]
@arikfr @gabrieldutra anyone can lable my issue? I checked PR, but PRs is too many ! Thank you!
