### ISSUE TITLE
order by dashboard name in dashboard list page error

### ISSUE THREAD

**Issue by yankeeguyu** [getredash/redash#5119]
Hi, When i clicked sortable, it error:
cause by:
![image](https://user-images.githubusercontent.com/46274612/90753509-48939b80-e30b-11ea-9ea8-9af9f80b82c5.png)

if i change to page 2, it will error
![image](https://user-images.githubusercontent.com/46274612/90753393-1eda7480-e30b-11ea-8a9c-b9636b1a55f0.png)

My backend error like this:
![image](https://user-images.githubusercontent.com/46274612/90753733-8db7cd80-e30b-11ea-9d9a-d52ea32173a9.png)

Technical details:
Redash Version: 8.0.0
Browser/OS: MacOS & Chrome
How did you install Redash: npm and python celery build by myself

**Comment by kravets-levko** [comment]
Hi @yankeeguyu! Can you please try to pull latest `master` and reproduce this issue there?

**Comment by yankeeguyu** [comment]
I also need a feature, 'Created By' user

> Hi @yankeeguyu! Can you please try to pull latest `master` and reproduce this issue there?

Hi @kravets-levko , thank you, because i use version is 8.0.0. 
Because I want to continue to use 8.0.0, so I want to solve it, the latest PR is not suitable for my version. So this can be fixed?

**Comment by yankeeguyu** [comment]
And if i want to add 'Created By' in dashboard list page, and let it can sort, it will error like this:
![image](https://user-images.githubusercontent.com/46274612/90755047-4c282200-e30d-11ea-8ad3-93ce2672709c.png)

**Comment by kravets-levko** [comment]
Sorry @yankeeguyu, most likely we will not fix it for v8, as we fix only critical and security issues for old versions. If this issue is already fixed in v9/master - try to upgrade your instance. If it's not fixed yet - we'll fix it for the next release. Sorry once more

**Comment by kravets-levko** [comment]
P.S. Also, you're always welcome to fix it yourself and submit a PR

**Comment by yankeeguyu** [comment]
> reproduce this issue there?
  

> P.S. Also, you're always welcome to fix it yourself and submit a PR

When will the official version of 9.0.0 be released? I didn’t upgrade because I was afraid that beta v9 was not stable enough. Thank you, if i fix it, i will submit a PR.

**Comment by yankeeguyu** [comment]
> P.S. Also, you're always welcome to fix it yourself and submit a PR

And someone add feature how to sort in 'Created By'?

**Comment by agutoli** [comment]
Bugfix:
https://github.com/getredash/redash/pull/5645/files

**Comment by gaecoli** [comment]
> Bugfix: https://github.com/getredash/redash/pull/5645/files

Thanks.
