### ISSUE TITLE
npm run watch not compile any changes in viz-lib

### ISSUE THREAD

**Issue by khiemntu** [getredash/redash#5133]
I run npm run watch but when I changed some file in viz-lib such as PlotlyChart.jsx, redash not compile changes automatically, and nothing change, but anything changes in client/app working properly. Anyone meet that issue ?

**Comment by gabrieldutra** [comment]
Did you run `npm run watch` from the base dir or from the `viz-lib` dir? The first is supposed to watch for everything.
