### ISSUE TITLE
sql query limit rows and download limit rows

### ISSUE THREAD

**Issue by yankeeguyu** [getredash/redash#5138]
Hello, everyone, why not add a function to limit the number of rows downloaded by the user and the number of SQL rows returned by the query?
I think this function has a great effect in the query performance and data security of redash. Thanks!

**Comment by kravets-levko** [comment]
Duplicate of getredash/redash#976

**Comment by yankeeguyu** [comment]
> Duplicate of #976

Thank you @kravets-levko , but this just limit sql query rows. Can redash add a feature about download query_result also limit rows?
