### ISSUE TITLE
add uesr issue

### ISSUE THREAD

**Issue by andylee513** [getredash/redash#5167]
I can't new user when build UI page, like the button is unaviable.

**Comment by kravets-levko** [comment]
Hi @andylee513! Please use this template for bug reports:

---------------------------------------------------------------

### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by guidopetri** [comment]
@andylee513 do you have any more info to add to this bug? Without steps on how to reproduce, we won't be able to fix it.
