### ISSUE TITLE
Horizontal scrollbar off-screen in query table view

### ISSUE THREAD

**Issue by brylie** [getredash/redash#5189]
# Issue Summary

When viewing a query result set in table mode, there are sometimes more columns than will fit on the screen. In such cases, the horizontal scrollbar will allow the user to see the remaining columns. However, the horizontal scrollbar may not appear until the user scrolls to the bottom of the resultset.

### Steps to Reproduce

1. Make a query on a table with many columns
2. Try to scroll horizontally to review the columns

### Technical details:

* Redash Version: 7.0.0
* Browser/OS: Chrome, Firefox
* How did you install Redash: Docker

**Comment by kravets-levko** [comment]
Hi @brylie! Does this issue reproduce in v8 or in master?

**Comment by brylie** [comment]
I'm not able to test with version 8 at this time. Our deployment is version 7.0.0 and we are hesitant to update.

**Comment by kravets-levko** [comment]
Can you reproduce this on our preview instance? https://redash-preview.netlify.app/

**Comment by brylie** [comment]
It looks like it's fixed on 8.x. I'll try and upgrade our instance ASAP.

![Screenshot from 2020-09-29 21-35-31](https://user-images.githubusercontent.com/17307/94601200-cbf5c480-029b-11eb-815a-9c9d10748737.png)

**Comment by brylie** [comment]
It looks like it's fixed on 8.x.

By the way, there is at least one data set there that may contain personally identifiable information. It might be worth making sure there is only dummy data on that instance.

**Comment by kravets-levko** [comment]
> By the way, there is at least one data set there that may contain personally identifiable information

Thank you @brylie! Which one did you mean?

**Comment by brylie** [comment]
The *Chinook (admin only)* data set looks like it might contain personal info. I'm not certain, so just wanted to raise concern.

**Comment by kravets-levko** [comment]
Oh, that one it completely safe, it contains only demo data. But thank you anyway 🙂
