### ISSUE TITLE
Impala - Add support for reserved words when retrieving database stats.

### ISSUE THREAD

**Issue by hagaeru3sei** [getredash/redash#5197]
Some tables use Impala's reserved words as their column names causing error.
This commit fixes this issue.

- [commit](https://github.com/hagaeru3sei/redash/commit/55a8eec01ab0642437f267176f45c3259772f9a3)

**Comment by arikfr** [comment]
@hagaeru3sei you're welcome to open a Pull Request with this change. Thanks.
