### ISSUE TITLE
Google Analytics query runner doesn't working currently caused by issue of Google API Discovery

### ISSUE THREAD

**Issue by ariarijp** [getredash/redash#5206]
### Issue Summary

Original issue is googleapis/google-api-python-client#1065

### Steps to Reproduce

1. Run a query on data source of Google Analytics.
2. You'll see `Error running query: 'rootUrl'`

### Technical details:

* Redash Version: 8.0.0+b32245
* Browser/OS: Chrome / Mac
* How did you install Redash: Self-hosted with docker-compose

**Comment by gaaamii** [comment]
It seems to be fixed. 
The data source worked for me after I removed content of its cache file,`/tmp/google-api-python-client-discovery-doc.cache`.

**Comment by ariarijp** [comment]
@gaaamii Great! you saved my day!
