### ISSUE TITLE
Redash V9 Beta Docker Version Queries And Dahboards Seem Very Broken

### ISSUE THREAD

**Issue by Kevinio04** [getredash/redash#5213]
### Issue Summary

Yesterday I followed the developer installation guide from your site -[https://redash.io/help/open-source/dev-guide/docker] - to setup redash on my local machine via docker to do some testing. During the docker-compose phase to initialize docker there were some errors reported regarding incompatible versions between packages however the services were all able to be be started and seem to be operating ok. Then came the web side.  First of all the npm install command caused numerous warnings about vulnerabilities - see attached image.   I then tried to execute the npm run build step - this would not work as I am on a Windows machine. I modified the package.json file very slightly - adding two new script commands to address the problems without breaking or changing commands already present. I then executed the npm run start command. At this point the web site was available as expected on localhost:8080. 

![Redash NPM install warnings](https://user-images.githubusercontent.com/19997732/96098448-067d7500-0eca-11eb-8242-31eadc78ada3.PNG)

This is where the main issues come in. It seems like running queries, and thus creating dashboards is totally broken due to issues with react hooks. I created a new datasource which connects to an Azure SQL database. The connection was setup successfully and the test of the connection works fine. So now I try to create a query. I write a very simple query to test functionality - select userid from users - this is a dev db so there are only 5 records in this table. I press execute and the application fails / breaks. Looking at the developer console the errors are caused by react hooks / render errors - 3 errors reported. This has been tested in the latest firefox and the latest edge chromium with the same results. I tried to publish the query without executing it in the query view but this issue rolls through into the dahboards making the dashboards unusable also

1. Error displayed by the application after pressing execute in query view
![Redash query exceution error](https://user-images.githubusercontent.com/19997732/96099925-b0113600-0ecb-11eb-8a20-bae9dc3cf7aa.PNG)

2. Errors reported in console:
![Redash query exceution error dev console 1](https://user-images.githubusercontent.com/19997732/96099988-c7502380-0ecb-11eb-8a2a-3515a286e343.PNG)
![Redash query exceution error dev console 2](https://user-images.githubusercontent.com/19997732/96099994-c9b27d80-0ecb-11eb-9f8f-dda7250f3ea3.PNG)
![Redash query exceution error dev console 3](https://user-images.githubusercontent.com/19997732/96100002-cae3aa80-0ecb-11eb-8e00-f6b0aa89bf37.PNG)

### Steps to Reproduce

1. Setup the environment as per the instructions [setup](https://redash.io/help/open-source/dev-guide/docker)
2. Create a new data source - in this case it was to Azure SQL
3. Create a new query - in this case a simple select userid from users
4. Click execute

The application should not explode here. If the query is malformed or the db server reports and error it should report that. If the query is successful the results should be displayed

### Technical details:

* Redash Version: 9.0.0 beta (dev)
* Browser/OS: Firefox & Edge Chromium / Windows 10 2004
* How did you install Redash: Docker, This was a brand new install of docker yesterday so the latest version. Using WSL2. Installed docker following the developer guide

**Comment by frozenzj** [comment]
same situation,plz help

**Comment by Kevinio04** [comment]
Erm... ok. Isn't core functionality of the UI being completely broken a pretty major bug - or set of bugs?? I submitted it here for this exact reason - rather than being a simple support request.

**Comment by kravets-levko** [comment]
@Kevinio04 I only asked you to move this discussion to forum, because this looks like a setup issue (considering errors you see - it has be totally messed up), and very likely it's specific to your environment. Basically, if you'll just do `git clone git@github.com:getredash/redash.git` and then `docker-compose up` - you should get a running Redash instance. To be honest, nobody of us use Windows for work, and on the forum there's a better chance that somebody will help you. We'll watch the discussion there, and if it will turn that there's _really_ some bug - only then we'll move back here. Thanks for understanding.

**Comment by Kevinio04** [comment]
@kravets-levko Thanks for the update. I have created a topic on the forum as you asked. As I mentioned in my original opening post though - and just trying to be clear - I basically did exactly what you described - git clone git@github.com:getredash/redash.git and then docker-compose up followed by npm run build and npm run start (as instructed in the documentation) - nothing else. The docker instances / containers are running fine (even though I received some errors during setup when running the compose up step) so what I am seeing / reporting is not related to the docker / redash instance side, just the front end web ui. 
While this may be an environment thing - it would be a strange one. The docker install was a brand new install of docker - the redash image and containers are the only ones running in docker and as stated the docker instance containers all seem to be running fine. I have multiple other web apps running on the machine that are using react / webpack etc and they have no issues. Based on this and given the errors I reported are coming from react itself and not some sub dependency library that may not support windows the problem being the environment seem unlikely.

Just writing all this for clarity and for any forum users that come here and read this - i linked this issue on the forum post. 

@frozenzj - you reported having the same issue. Can you update the forum post [here](https://discuss.redash.io/t/v9-beta-ui-very-broken-docker/7447) with your thoughts as well as your environment etc so we can try to resolve this

**Comment by frozenzj** [comment]
okay,i've figured it out by changing some settings on Dockerfile,docker-compose.yml...and so on.

- Technical details:

1. Redash Version: V9
2. Browser/OS: WSL2 Ubuntu 18.04
3. How did you install Redash: git clone master branch
4. Data Sourse Server: Mysql

- SETUP STEPS:

Here are some STEPs based on the [Developer Installation Guide](https://redash.io/help/open-source/dev-guide/docker):

1. install docker,docker-compose,node,nodejs,npm
2. EDIT the follow file:
  https://github.com/frozenzj/redash/commit/f72874925bc9a358adc3a439b45235a1cc6e1b67
this may take some time:▲
3. ▲`docker-compose up`  ,
4. ▲`npm install` 
5. ▲`npm run build` 
6. ▲`npm run start` 
7. ▲`npm run watch` 
8. `docker-compose run --rm server create_db`
9. `docker-compose start`

IT WORKS!!!
before those steps to setup the redash's docker version ,I've faced:
1. Internal server error  500
2. “OperationalError: server closed the connection unexpectedly” on SQL: ‘SELECT … FROM organizations’
3. Missing Mysql DataSourse Driver
4. The situation as @Kevinio04 said

i hope these can help you .
