### ISSUE TITLE
Tables in Markdown not Working

### ISSUE THREAD

**Issue by brad-natelborg** [getredash/redash#5216]
### Issue Summary

I can't seem to get any tables generating in markdown in Redash when creating a text widget.

### Steps to Reproduce

1) Create a text widget
2) Attempt to create a table in it, using example: https://www.markdownguide.org/cheat-sheet/#basic-syntax

### Technical details:

* Redash Version: 8.0.0
* Browser/OS: Chrome, Windows
* How did you install Redash:

**Comment by kravets-levko** [comment]
Hello @brad-natelborg! That's not a bug, rather missing feature. Let's move this discussion to a [relevant forum section](https://discuss.redash.io/c/feature-requests/5). Thanks!

**Comment by kravets-levko** [comment]
https://discuss.redash.io/t/markdown-support-for-tables/7393
