### ISSUE TITLE
export excel file data type error

### ISSUE THREAD

**Issue by yankeeguyu** [getredash/redash#5218]
In the query results, the data in some columns are all numbers, but when I export these data to excel files, these data are converted to string or None by default, which makes it impossible for me to manipulate the exported excel file. How to fix it?

### Technical details:

* Redash Version: 9.0.0
* Browser/OS: Chrome & MacOS
* How did you install Redash: docker

**Comment by arikfr** [comment]
What data source were you using? Can you try and reproduce this in our
Preview instance? (https://redash-preview.netlify.app)

**Comment by yankeeguyu** [comment]
I can't find in your online redash, but in my redash i can find some sample!
![image](https://user-images.githubusercontent.com/46274612/96418231-04e2e280-1225-11eb-9b20-f67500c1b698.png)

![image](https://user-images.githubusercontent.com/46274612/96418279-1a580c80-1225-11eb-8b9a-92b728b298ef.png)
If i sum these data, it will show 0, like:
![image](https://user-images.githubusercontent.com/46274612/96418366-3f4c7f80-1225-11eb-8d6b-105b07883991.png)

**Comment by yankeeguyu** [comment]
I debug show:
![Uploading image.png…]()

**Comment by yankeeguyu** [comment]
@arikfr I tested this issue! When my data source was postgresql, data type was "guess types", but others data source this wasn't happened! If you can add postgresql, you can try it! I will show my test pics:
![image](https://user-images.githubusercontent.com/46274612/96840336-e1b27000-147c-11eb-9eb0-46c688623c97.png)
![image](https://user-images.githubusercontent.com/46274612/96840392-fa228a80-147c-11eb-828a-23dc40df495f.png)
If you download it as Excel file, column `c` go to show type is string! It just happens in pgsql!
