### ISSUE TITLE
Docker image uses Python2 for python query runner?

### ISSUE THREAD

**Issue by remcoboerma** [getredash/redash#5251]
### Issue Summary

Using a docker install for version 8.0.0+b32245 (a16f551e) python2 seems to be used for the python query runner. 
 
### Steps to Reproduce

1. Install from docker
2. Enable python query runner
3. create new python datasource, allow `sys` as module 
4. create a new query for given datasource: 
```python
import sys
print(sys.version)
```

Results: 
```
[2020-11-01T15:48:36.854996] 2.7.16 (default, Aug 14 2019, 13:44:33) 
[GCC 8.3.0]
```
I expect to see python3, and be able to use python3 libraries and functionality instead of python2. 

### Technical details:

* Redash Version :8.0.0+b32245
* Browser/OS: ubuntu 18.04 LTS
* How did you install Redash: via docker

**Comment by clearnote01** [comment]
Hi @remcoboerma, I faced a similar pitfall while setting up Redash, the py2->py3 migration here was done after release of 8.x, try using the [9.0.0beta release](https://github.com/getredash/redash/releases/tag/v9.0.0-beta).

**Comment by guidopetri** [comment]
@remcoboerma hey! Is this still a problem with the latest version of redash (`preview` image on dockerhub)?
