### ISSUE TITLE
Error: Connect MSSQL read replica with Redash

### ISSUE THREAD

**Issue by ravneet05** [getredash/redash#5252]
I am trying to establish connectivity between MSSQL Server read replica with Redash but getting connection error and it requires to set the property ApplicationIntent=ReadOnly. 

![image](https://user-images.githubusercontent.com/9279979/97912659-1d99df00-1d73-11eb-9afc-14f331e15038.png)

I am not sure how to set this property in Redash. 
Please advice.

**Comment by kravets-levko** [comment]
Hi @ravneet05! Please ask this on the forum (see link in comment above). Thanks!
