### ISSUE TITLE
In  china, when we analyze regional data, we always treat Taiwan as a province.

### ISSUE THREAD

**Issue by xiaodin1** [getredash/redash#5264]
### Issue Summary

when i use redash to show the map of china，finding that Taiwan's data is not included in China leads to the data which we show in the map is error, In our eyes, Taiwan is an indispensable part of China, can we change to another map source，such as echarts. 
![image](https://user-images.githubusercontent.com/5487977/98787065-f8276800-2439-11eb-9e05-0f9de7b74de1.png)
in my opinion，good products are better suited to the needs of every place

thanks~

evn:
* Redash Version:9.0.0-beta
* Browser/OS:centos6.3
* How did you install Redash:manual deploymen

**Comment by xiaodin1** [comment]
How can we report map data that is suitable for our national conditions? Can you provide a solution?

**Comment by susodapop** [comment]
Hi @xiaodin1, thank you very much for bringing this up. We use an external library for visualizing maps. I've added a roadmap item for the engineering team on how to handle situations like this.

**Comment by gaecoli** [comment]
@susodapop  #5539 Taiwan is part of China. Please merge this PR. Thank you.

**Comment by gaecoli** [comment]
![image](https://user-images.githubusercontent.com/46274612/126315591-1850c6ca-2def-4057-8954-5ce3c91e1017.png)

**Comment by gaecoli** [comment]
![image](https://user-images.githubusercontent.com/46274612/126315662-f8b7eace-e49e-4d93-aae9-0d391aa31730.png)

**Comment by guidopetri** [comment]
https://en.wikipedia.org/wiki/China

https://en.wikipedia.org/wiki/Taiwan

Deferring to Wikipedia.
