### ISSUE TITLE
Allow passing additional parameters to google oauth url.

### ISSUE THREAD

**Issue by lomkju** [getredash/redash#5293]
### Issue Summary

Currently, we cannot pass additional parameters to the oauth url for google. 
Parameters like `hd=mydomain.com` can be appended into the oauth url.
This is useful when running redash for an org you would wanna give user the only option to use the org domain account hiding all other non org domain accounts.
https://developers.google.com/identity/protocols/oauth2/openid-connect#hd-param
This would also help in passing other parameters mentioned in the official doc.

If we could just pass additional values here as an env would be great.
https://github.com/getredash/redash/blob/2dff8b9a00d23ef6f7a2d108c8560ec38f8f8960/redash/authentication/google_oauth.py#L28

### Steps to Reproduce

1. Login to redash with google oauth.

### Technical details:

* Redash Version: v9
* Browser/OS: Chrome
* How did you install Redash: Self-Hosted

**Comment by kravets-levko** [comment]
Hi @lomkju! Looks like this is a new feature request. Can you please move this to a new topic in appropriate section on our forum? https://discuss.redash.io/c/feature-requests/5 Thanks!
