### ISSUE TITLE
When a TextBox is added on dashboard it cannot be updated

### ISSUE THREAD

**Issue by matiascarazzo** [getredash/redash#530]
When a TextBox is added on dashboard it cannot be updated

**Comment by satyadeepk** [comment]
Yeah, I feel like having an edit button too on the Text Box.
Looks like this is the PR which added the Text Box. We will probably need to add an edit button with an edit dialog.
https://github.com/EverythingMe/redash/pull/192/files

**Comment by jeffwidman** [comment]
+1 for an edit button on the text box.

**Comment by mathemagica** [comment]
+1 for an edit button

**Comment by JonahTurnquist** [comment]
+1

**Comment by gcasey-atvi** [comment]
+1

**Comment by RichardLitt** [comment]
@gcasey-atvi This should have been fixed; are you still finding this to be an issue?

**Comment by Lpember** [comment]
+1
