### ISSUE TITLE
Set base path

### ISSUE THREAD

**Issue by fcnyp** [getredash/redash#5315]
I am trying to modify the base path (e.g., 127.0.0.1:5000/ -> 127.0.0.1:5000/redash-prefix) without using nginx or apache to rewrite and proxy (seems unstable and prone to error when upgrading due to path changes). I opted to modify app.py and add the prefix in manually and am getting a route error: “It seems like the page you’re looking for cannot be found.” when navigating to redash using the prefix. I feel this is a common use case that should be supported.

```
from werkzeug.routing import Rule

app.url_rule_class = lambda path, **options: Rule("/redash-prefix" + path, **options)
```
Technical details:

Redash Version: 9.0.0-beta
OS: Ubuntu Server 20.04
How did you install Redash: https://redash.io/help/open-source/dev-guide/setup
NPM: 6.14.8
Node: v12.20.0
Python: 3.8.5

**Comment by eladitzhakian** [comment]
@fcnyp @lisfo4ka i'm also interested in the solution
