### ISSUE TITLE
Standard_init_linux.go:219: exec user process caused: no such file or directory

### ISSUE THREAD

**Issue by oguzhan10** [getredash/redash#5331]
I pull Redash latest version in Windows 10. I run docker-compose up -d in powershell. Redis, postgres and redash_email_1 are working but other 3 components are not working. When I check the log I found this error.“standard_init_linux.go:219: exec user process caused: no such file or directory”.

**Comment by Oreilles** [comment]
Same issue.

**Comment by susodapop** [comment]
👋 @oguzhan10 , we use the issue tracker exclusively for bug reports and planned work. However, this issue appears to be a support request. Please use our forum to get help. There's already a discussion of this error [here](https://discuss.redash.io/t/standard-init-linux-go-exec-user-process-caused-no-such-file-or-directory/7754).
