### ISSUE TITLE
conflicting dependency while try to install all data source requirements 

### ISSUE THREAD

**Issue by jzhao62** [getredash/redash#5339]
### Issue Summary

failed to install all datasources inside requirements_all_ds.txt
<img width="1191" alt="Screenshot_20210101_014926" src="https://user-images.githubusercontent.com/25937657/103436843-004b8a80-4bd5-11eb-8724-bf36313cb312.png">

### Steps to Reproduce

1. follow basic guidelines from developer installation guide line (experience developer guide, run flask locally)
2. pip install -r requirements_all_ds.txt

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

I see from the product you are allowed to choose data source from Oracle, hive, presto, mysql, but from the latest build i dont have these options to add from.

### Technical details:

* Redash Version: 9.0.0-beta, 
* Browser/OS: Chrome, Ubuntu 20.04
* How did you install Redash: (https://redash.io/help/open-source/dev-guide/setup)

**Comment by zhongjiajie** [comment]
I think is a bug

**Comment by thainv1202** [comment]
The newest version of pip causes this error. I solved this by adding `RUN pip install pip==20.2.4` before installing python dependencies and the error went away.

**Comment by guidopetri** [comment]
With our new poetry setup, we shouldn't have this issue anymore - feel free to reopen if you still run into it.
