### ISSUE TITLE
Upgrading via deploy_latest_release doesn't seem to run pip

### ISSUE THREAD

**Issue by stanhu** [getredash/redash#534]
The last two times I've upgraded redash, for some reason `pip install -r requirements.txt` wasn't run. Here's the output when I upgraded from 0.6.3.b901 to 0.7.0.b977:

```
$ fab -Hredash -uredash deploy_latest_release
[redash] Executing task 'deploy_latest_release'
Deploying version: redash.0.7.0.b977
Downloading latest version...
Unpacking...
Changing ownership to redash...
Linking .env file...
No new migrations in this version.
[redash] run: sudo ln -nfs /opt/redash/redash.0.7.0.b977 /opt/redash/current
[redash] run: sudo /etc/init.d/redash_supervisord restart
[redash] out:  * Restarting process supervisor supervisord
[redash] out:    ...done.
[redash] out: 
```

It doesn't look like it's attempting to run pip here. I've done some debugging of the script, but everything seems right; I can't seem to figure how this could have happened. It's almost as though `link_to_current` was called before the `diff` check.

Also, is there a reason why `fabfile.py` isn't just checked into the repo?

**Comment by arikfr** [comment]
Strange. You're right that the only way this can happen is if the new version will be already linked. Is it possible the fabric task was run twice somehow?

Also, you're right that the file should be part of the repo. The reason why I didn't commit it yet, was that I wanted to change it to run locally before doing so.
