### ISSUE TITLE
Critical error with npm run build

### ISSUE THREAD

**Issue by huzaifahj** [getredash/redash#5357]
# Issue Summary
error TS2688: Cannot find type definition file for 'jest'.

# The debug log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.11
3 info using node@v12.20.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle redash-client@9.0.0-betaprebuild: redash-client@9.0.0-beta
6 info lifecycle redash-client@9.0.0-betabuild: redash-client@9.0.0-beta
7 verbose lifecycle redash-client@9.0.0-betabuild: unsafe-perm in lifecycle true
8 verbose lifecycle redash-client@9.0.0-betabuild: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/redash/redash-master/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle redash-client@9.0.0-betabuild: CWD: /opt/redash/redash-master
10 silly lifecycle redash-client@9.0.0-betabuild: Args: [
10 silly lifecycle '-c',
10 silly lifecycle 'npm run clean && npm run build:viz && NODE_ENV=production webpack'
10 silly lifecycle ]
11 silly lifecycle redash-client@9.0.0-betabuild: Returned: code: 2 signal: null
12 info lifecycle redash-client@9.0.0-betabuild: Failed to exec build script
13 verbose stack Error: redash-client@9.0.0-beta build: npm run clean && npm run build:viz && NODE_ENV=production webpack
13 verbose stack Exit status 2
13 verbose stack at EventEmitter. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack at EventEmitter.emit (events.js:314:20)
13 verbose stack at ChildProcess. (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:314:20)
13 verbose stack at maybeClose (internal/child_process.js:1022:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid redash-client@9.0.0-beta
15 verbose cwd /opt/redash/redash-master
16 verbose Linux 4.18.0-240.1.1.el8_3.x86_64
17 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v12.20.1
19 verbose npm v6.14.11
20 error code ELIFECYCLE
21 error errno 2
22 error redash-client@9.0.0-beta build: npm run clean && npm run build:viz && NODE_ENV=production webpack
22 error Exit status 2
23 error Failed at the redash-client@9.0.0-beta build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
# Steps to Reproduce
- pip3 install -r requirements.txt -r requirements_dev.txt
- npm install
- npm run build

# Technical details:
Redash Version: the last version
Browser/OS: Ubuntu 18.04
How did you install Redash: Developer Installation Guide

**Comment by florenbai** [comment]
Hi, we are the same problem. you can see the viz-lib/package.json , Whether the dependent files are downloaded to the viz-lib/node_modules folder . if not,  You should copy the dependencies in the ./node_modules directory to the viz-lib/node_modules. so you run "npm run build" , In addition, you also need to fix sql-formatter error[https://discuss.redash.io/t/9-0-0-beta-developer-installation-error-cant-resolve-sql-formatter/7668](url) . good luck！

**Comment by huzaifahj** [comment]
Which exact dependencies did you copy? Why does `npm install` in viz-lib not install them.

**Comment by florenbai** [comment]
I don't know why does npm install in viz-lib not install them. but they can find in the node_modules folder of the root directory .

**Comment by xiaodin1** [comment]
try:
nvm ls-remote --lts
nvm install 12.21.0
nvm use 12.21.0

**Comment by p294960570** [comment]
same question

**Comment by susodapop** [comment]
Can anyone share steps to reproduce this error? When I use the Docker installation on MacOS everything works.

**Comment by rotten** [comment]
Similarly, I get this error if I clone the repo and run `yarn build` (on Ubuntu 20.04):

```
$  yarn build

yarn run v1.22.10
$ yarn clean && yarn build:viz && NODE_ENV=production webpack
$ rm -rf ./client/dist/
$ (cd viz-lib && yarn build:babel)
$ yarn type-gen && yarn build:babel:base
$ tsc --emitDeclarationOnly
error TS2688: Cannot find type definition file for 'jest'.
  The file is in the program because:
    Entry point of type library 'jest' specified in compilerOptions

  tsconfig.json:8:23
    8     "types": ["node", "jest"],
                            ~~~~~~
    File is entry point of type library specified here.

error TS2688: Cannot find type definition file for 'node'.
  The file is in the program because:
    Entry point of type library 'node' specified in compilerOptions

  tsconfig.json:8:15
    8     "types": ["node", "jest"],
                    ~~~~~~
    File is entry point of type library specified here.


Found 2 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Darren-chenchen** [comment]
> viz-lib

yes  !!!   
cd viz-lib
npm i

**Comment by dufferzafar** [comment]
@rotten I'm getting the same error as you. How did you fix it?

**Comment by rotten** [comment]
I'm not sure I did.  I don't remember now. sorry!  I stopped using redash shortly after this.   I'll try again later today if I get time to see if I can reproduce it or whether I managed to fix it and forgot what I did.  I'd like to use redash again some day.

**Comment by susodapop** [comment]
Redash uses yarn now instead of npm. Curious whether you see issues running `yarn install` and `yarn build`

**Comment by dufferzafar** [comment]
@susodapop I first ran `yarn --frozen-lockfile` and then `yarn build` which is when I got the errors mentioned by @rotten

**Comment by susodapop** [comment]
What version of yarn are you using?

**Comment by dufferzafar** [comment]
```
yarn --version
1.22.10
```

Doing `yarn --frozen-lockfile` didn't actually create a `node_modules` folder in the current directory. I'm not sure where it installed the packages.

**Comment by susodapop** [comment]
Bizarre. And which version of Node?

**Comment by dufferzafar** [comment]
```
node --version
v14.17.1
```

**Comment by susodapop** [comment]
And to confirm, which directory are you in when you run these commands?

For clarity, it isn't necessary to run yarn install within the viz-lib folder. The instructions say to run them from the root of the repository.

**Comment by dufferzafar** [comment]
Yes, that is what I'm trying to do. `yarn` was not creating a `node_modules` folder, so I did `npm install` which worked 😓

**Comment by susodapop** [comment]
Which operating system?

**Comment by dufferzafar** [comment]
CentOS 7

**Comment by kingname** [comment]
the same error to me.

My mac is M1 Pro. And I follow this guide: https://redash.io/help/open-source/dev-guide/docker . The previous steps worked, but when I run into `yarn build`, this error occured.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/5440523/183299600-8b521797-219b-438b-af8a-5d204169fc8c.png">

**Comment by kingname** [comment]
I have solved this problem, bros.

cd to the root folder of redash. Run the following command.

```bash
export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
yarn install
yarn build
```

It is work like a charm.

**Comment by mumu1349562746** [comment]
yarn Installation continues to fail，fail usually in step2 or step3，how can i install this project?

**Comment by mumu1349562746** [comment]
computer system : windows 10

**Comment by susodapop** [comment]
@mumu1349562746 none of the core team develops on Windows so we don't have much guidance here. That said, you haven't given any debugging info. Can you share what exact error you receive or what workarounds you have tried?

**Comment by hantmac** [comment]
Similar problem, yarn Installation continues to fail.

**Comment by kingname** [comment]
来信已收到，我会尽快回复。

**Comment by arikfr** [comment]
If stumbling into any of these issues, make sure: 1) you use `yarn` and not `npm`; 2) you use a Node version that is compatible with the `engines` definition in `package.json` (I believe that recent versions of yarn will warn you about this).

I couldn't reproduce this on recent master, but please re-open if this happens again.

**Comment by SlavchoSpasenoski** [comment]
Hello, here again with same error from above...

Trying to install redash-10.0.0 
Ubuntu 20.04
Node 12.0.0 (tried with 14.17.1 as well)
Yarn 1.22.10

followed this guide https://redash.io/help/open-source/dev-guide/setup

Do someone have solution for this?

**Comment by SlavchoSpasenoski** [comment]
Hello @arikfr, 

Error for node 14.17.1 was: **type-gen: failed to exec type-gen script** (Very similar as very first post above)

But I was tried to use master repo instead version 10.0.0, and everything related to Yarn is installed without errors.

My main goal is to deploy redash 10 (or above) without docker (for use it, not develop) (It were explained by Me in discussion [https://github.com/getredash/redash/discussions/5955](url) )

For now I successfully installed and running Redash (from master-repo) without docker on Ubuntu 20.04. works fine with local instances as data sources (tested with MySql 5.7 server)... But now facing error with REDASH_COOKIE_SECRET. It can't read it from env file. I am sure, that env file is correct filled and configured in correct path...

Mine script is following:
`#!/bin/bash

set -eu

REDASH_BASE_PATH=/opt/redash
REDASH_BRANCH="${REDASH_BRANCH:-master}" # Default branch/version to master if not specified in REDASH_BRANCH env var
REDASH_VERSION=${REDASH_VERSION-master}
LATEST_URL=https://github.com/getredash/redash/archive/refs/heads/master.tar.gz
VERSION_DIR="$REDASH_BASE_PATH/redash.${REDASH_VERSION}"
REDASH_TARBALL=/tmp/redash.tar.gz
FILES_BASE_URL=https://raw.githubusercontent.com/getredash/redash/release/4.0.x/setup/ubuntu/files


#Setup virtual environment
sudo apt install python3-virtualenv
virtualenv -p python3 venv
source venv/bin/activate



#Remove redash installation if exist
cd /opt
DIR="/opt/redash"
if [ -d "$DIR" ]; then
    rm -rv redash
else
    cd /tmp/
fi
cd /tmp/



verify_root() {
    # Verify running as root:
    if [ "$(id -u)" != "0" ]; then
        if [ $# -ne 0 ]; then
            echo "Failed running with sudo. Exiting." 1>&2
            exit 1
        fi
        echo "This script must be run as root. Trying to run with sudo."
        sudo bash "$0" --with-sudo
        exit 0
    fi
}

create_redash_user() {
   adduser --system --no-create-home --disabled-login --gecos "" redash
}



install_system_packages() {
    apt-get -y update
    apt-get -y install software-properties-common
    apt-add-repository universe
    # Base packages
    apt install -y python3-pip python3-dev nginx curl build-essential pwgen nodejs npm
    # Data sources dependencies:
    apt install -y libffi-dev libssl-dev libmysqlclient-dev libpq-dev freetds-dev libsasl2-dev
    # SAML dependency
    apt install -y xmlsec1
    apt install python-is-python3
    apt install git
    # Storage servers
    apt install -y postgresql redis-server
    apt install -y supervisor
}



create_directories() {
    mkdir -p $REDASH_BASE_PATH
    chown redash $REDASH_BASE_PATH 
    
    # Default config file
    if [ ! -f "$REDASH_BASE_PATH/.env" ]; then
        sudo -u redash wget "$FILES_BASE_URL/env" -O $REDASH_BASE_PATH/.env
    fi

    COOKIE_SECRET=$(pwgen -1s 32)
    echo "export REDASH_COOKIE_SECRET=$COOKIE_SECRET" >> $REDASH_BASE_PATH/.env
}



create_config() {
    if [[ -e $REDASH_BASE_PATH/env ]]; then
        rm $REDASH_BASE_PATH/env
        touch $REDASH_BASE_PATH/env
    fi
    COOKIE_SECRET=$(pwgen -1s 32)
    SECRET_KEY=$(pwgen -1s 32)
    POSTGRES_PASSWORD=$(pwgen -1s 32)
    REDASH_DATABASE_URL="postgresql://postgres:${POSTGRES_PASSWORD}@postgres/postgres"

    echo "PYTHONUNBUFFERED=0" >> $REDASH_BASE_PATH/env
    echo "REDASH_LOG_LEVEL=INFO" >> $REDASH_BASE_PATH/env
    echo "REDASH_REDIS_URL=redis://redis:6379/0" >> $REDASH_BASE_PATH/env
    echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" >> $REDASH_BASE_PATH/env
    echo "REDASH_COOKIE_SECRET=$COOKIE_SECRET" >> $REDASH_BASE_PATH/env
    echo "REDASH_SECRET_KEY=$SECRET_KEY" >> $REDASH_BASE_PATH/env
    echo "REDASH_DATABASE_URL=$REDASH_DATABASE_URL" >> $REDASH_BASE_PATH/env
}



extract_redash_sources() {
    sudo -u redash wget "$LATEST_URL" -O "$REDASH_TARBALL"
    sudo -u redash mkdir "$VERSION_DIR"
    sudo -u redash tar -C "$VERSION_DIR" -xvf "$REDASH_TARBALL"
    ln -nfs "$VERSION_DIR" $REDASH_BASE_PATH/current
    ln -nfs /opt/redash/.env /opt/redash/current/redash-master/.env
}



install_python_packages() {
 
    cd /opt/redash/current/redash-10.0.0
    npm install -g n
    n 14.17.6  #request node v14 or above
    sudo pip install redis
    sudo pip install python-dotenv
    sudo pip install setproctitle # setproctitle is used by Celery for "pretty" process titles
    sudo pip3 install -r /opt/redash/current/redash-${REDASH_VERSION}/requirements.txt
    sudo pip3 install -r /opt/redash/current/redash-${REDASH_VERSION}/requirements_all_ds.txt

}



create_database() {
    # Create user and database
    sudo -u postgres createuser redash --no-superuser --no-createdb --no-createrole
    sudo -u postgres createdb redash --owner=redash

    cd $REDASH_BASE_PATH/current/redash-${REDASH_VERSION}
    sudo -u redash bin/run ./manage.py database create-tables
}



setup_nginx() {
    rm /etc/nginx/sites-enabled/default
    wget -O /etc/nginx/sites-available/redash https://raw.githubusercontent.com/getredash/redash/release/4.0.x/setup/ubuntu/files/nginx_redash_site
    ln -nfs /etc/nginx/sites-available/redash /etc/nginx/sites-enabled/redash
    service nginx restart
}


install_modules() {


    sudo npm install --global yarn@1.22.10
    sudo yarn --frozen-lockfile
    sudo yarn build
}


run_services() {

    sudo -u redash ./manage.py runserver &
    sudo -u redash ./manage.py rq worker &
    sudo -u redash ./manage.py rq scheduler &
}



verify_root
install_system_packages
create_redash_user
create_directories
create_config
extract_redash_sources
install_python_packages
create_database
setup_nginx
install_modules
run_services`

Error that I have
![image](https://user-images.githubusercontent.com/28984924/230109414-c34ca449-7bb2-4596-af50-28905981ba16.png)

To fix this, I temporary hardcoding COOKIE_SECRET in /redash/settings/__init__.py to successfully run redash server & workers
