### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/app/redash/settings/../../client/dist/index.html'

### ISSUE THREAD

**Issue by javidsch** [getredash/redash#5358]
### Issue Summary

After starting Redash(docker-compose start) and submitting admin details(setup page was broken/no css style), there is "File not found error" page.

![image](https://user-images.githubusercontent.com/28500366/105032725-d4972400-5a5f-11eb-8507-b9d3a14ce022.png)

### Steps to Reproduce

1. https://redash.io/help/open-source/dev-guide/docker
2. http://localhost:5000/ => Setup page is opened without css-style.
3. After entering admin profile info/submit.

NPM install is finished without any red message.
This is the last message:

> _found 5491 vulnerabilities (4088 low, 28 moderate, 1374 high, 1 critical)
>   run `npm audit fix` to fix them, or `npm audit` for details_

And, I got message from **_pip_** also.
> ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
> 
> We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

### Technical details:

* Redash Version:  https://redash.io/help/open-source/dev-guide/docker
* Browser/OS: Chrome/Mac
* How did you install Redash: Docker Compose

**Comment by kravets-levko** [comment]
Have you tried to run `npm run build`?

**Comment by javidsch** [comment]
> Have you tried to run `npm run build`?
Done. Thanks. :)
