### ISSUE TITLE
 QQ email lives matter,isn't it?

### ISSUE THREAD

**Issue by Frank-Smith** [getredash/redash#5368]
redash/handlers/users.py
`
if domain.lower() in blacklist or domain.lower() == "qq.com":
     abort(400, message="Bad email address.")
`
`
if domain.lower() in blacklist or domain.lower() == "qq.com":
    abort(400, message="Bad email address.")
`

QQ email lives matter,isn't it?

**Comment by susodapop** [comment]
You are welcome to modify this on your own installation. The hosted Redash platform has been disproportionately abused by users with `qq.com` domains (mostly automated bots). For us it's easier to ban the domain then individually block users.

**Comment by Frank-Smith** [comment]
> You are welcome to modify this on your own installation. The hosted Redash platform has been disproportionately abused by users with `qq.com` domains (mostly automated bots). For us it's easier to ban the domain then individually block users.

Oh,  I see. Thanks.

**Comment by kravets-levko** [comment]
@Frank-Smith You're welcome to improve this if you have any better ideas (maybe, extract this to some config, etc.), and submit a PR 😉

**Comment by zhongjiajie** [comment]
> @Frank-Smith You're welcome to improve this if you have any better ideas (maybe, extract this to some config, etc.), and submit a PR 😉

@kravets-levko I submit a PR to refactor it, do you have some time to review this PR?
