### ISSUE TITLE
Dashboards page doesn't show the expected amount of entries

### ISSUE THREAD

**Issue by xavier-d** [getredash/redash#5383]
### Issue Summary

When browsing the page Dashboards the amount of entries does not match the expected. Showing only 2 entries while requested 20. It exists and finds more than 20 as it presents 34 pages.

![image](https://user-images.githubusercontent.com/7001183/106492790-a29eac80-64b8-11eb-882a-318fe37766db.png)

### Steps to Reproduce

1. Got to Dashboards page
2. Click on 'All Dashboards' 
3. See that only few as displayed (2 in my case) instead of the 20 default

### Technical details:

* Redash Version: V9.0.0-beta (04edf16e) installed from Docker preview - 10f641019ddb
* Browser/OS: Chrome V88
* How did you install Redash: Self instance on Kubernetes

**Comment by susodapop** [comment]
Thanks for reporting this and apologies for my late reply. This was fixed in https://github.com/getredash/redash/pull/5516 and is included in the V10 release.
