### ISSUE TITLE
Can't save long query

### ISSUE THREAD

**Issue by benjaminsirb** [getredash/redash#5403]
### Issue Summary

When creating a long query (a little under 5000 characters), redash doesn't allow me to save the query. I believe it's limited to redash as the same query works through another BI tool. Viewing the redash logs returns the following error:
`psycopg2.errors.InvalidParameterValue: payload string too long`

### Steps to Reproduce

1. Create a query that is at least 5000 characters long (mine has several CTE's at the start).
2. Try to save -- redash throws an error "Query could not be saved"

### Technical details:

* Redash Version: 9.0.0-beta (264156b)
* Browser/OS: Mac OS Big Sur 11.2.1 / Firefox 85.0.2
* How did you install Redash: Docker

**Comment by kravets-levko** [comment]
I think it may be related to POST requests payload size limit

**Comment by benjaminsirb** [comment]
Update: I just experienced this issue with a shorter query too, one that was "saveable" in our previous version of Redash, but after upgrading redash, I can no longer save. After deleting about a dozen lines from the query, I was able to save.

**Comment by leosantosw** [comment]
I encountered this blockage initially, but upon inspecting the request using developer tools, I found out that it was a response from the Cloudflare WAF.
![image](https://github.com/getredash/redash/assets/92169538/f68c594b-adab-45f1-bce3-22a7b56e2e5b)
![image](https://github.com/getredash/redash/assets/92169538/add79fa0-5f22-4be2-8ced-1b69e0897a7b)

**Comment by justinclift** [comment]
Oh, that's interesting.  You might need to add a rule / exception / something similar to Cloudflare WAF to allow these requests.

AWS's WAF product might have the same behaviour too.

**Comment by guidopetri** [comment]
I'm unable to reproduce this. @benjaminsirb is this still occurring with the latest `preview` image on dockerhub? Could you provide more detailed reproduce instructions?
