### ISSUE TITLE
Oracle datasource is missing

### ISSUE THREAD

**Issue by debabratp** [getredash/redash#5407]
I pulled the latest and build it as per the steps given. While creating a new data source, I found the Oracle is missing.
Can you please take a look?
### Technical details:

* Redash Version: 9.0.0-beta
* Browser/OS: Edge/ Mac
* How did you install Redash: Docker

**Comment by jhult** [comment]
The Oracle Database driver is not built into the [official Redash team published Docker image](https://hub.docker.com/r/redash/redash/tags?page=1&ordering=last_updated).

I have a [branch](https://github.com/jhult/redash/commits/oracle) (just rebased on `master`) which adds the [Oracle Instant client driver](https://www.oracle.com/database/technologies/instant-client/linux-x86-64-downloads.html) and fixes [a bug related to the Oracle Data Source](#5181).

My branch uses [this script](https://bitbucket.org/!api/2.0/snippets/mythics/on5GqE/master/files/oracle_instant_client_installer_debian.sh) (as referenced in the [Dockerfile](https://github.com/jhult/redash/blob/oracle/Dockerfile#L81)) to install the driver. As always, it is recommended to closely inspect remote scripts to ensure they are doing only what they are supposed to (and nothing nefarious).

I don't (publicly) publish my image but you can clone my repository and build it yourself:
```
git clone -b oracle --single-branch https://github.com/jhult/redash.git
docker build -t redash/oracle .
```
