### ISSUE TITLE
API returns "Internal Server Error" for dashboard-slug

### ISSUE THREAD

**Issue by dvandonkelaar** [getredash/redash#5416]
### Issue Summary

An API call to `/api/dashboards/slug` returns in
```
{
  "message": "Internal Server Error"
}
```

### Steps to Reproduce

REST client (Insomnia in my case):
1. Create a GET request with url: http://redash.host/api/dashboards/id
   - with header `Authorization `and value `Key {api}`
2. Data is returned
3. Create a GET request with url: http://redash.host/api/dashboards/slug
   - with the same headers as step 1
4. The error message is returned

Browser:
1. Log into Redash
2. http://redash.host/api/dashboards/id
3. Data is returned
4. http://redash.host/api/dashboards/slug
5. The error message is returned

With docker-image [redash/redash:8.0.2.b37747](https://hub.docker.com/layers/redash/redash/8.0.2.b37747/images/sha256-2dd3ba2df147ef754b153fe01fa9016f493c869221eb9b3dbd7a2242b8c4b95c?context=explore) this feature worked and returned the correct data.
After upgrading the installation to [redash/redash:preview](https://hub.docker.com/layers/redash/redash/8.0.2.b37747/images/sha256-2dd3ba2df147ef754b153fe01fa9016f493c869221eb9b3dbd7a2242b8c4b95c?context=explore) (and executing the upgade commands mentioned in [CHANGELOG.md](https://github.com/getredash/redash/blob/master/CHANGELOG.md#upgrading)) the feature broke.

### Technical details:

* Redash Version: `v9.0-beta (46e97a08)`
* Browser/OS: Windows 10
* How did you install Redash: from Docker

**Comment by susodapop** [comment]
This isn't really a bug. Starting in version 9 the id is used everywhere. The request returns 500 most likely because the slug doesn't include an `id` prefix.

https://github.com/getredash/redash/pull/1009

https://github.com/getredash/redash/pull/1009#pullrequestreview-275321411
