### ISSUE TITLE
Concatenating Sums doesn't work anymore

### ISSUE THREAD

**Issue by hebbet** [getredash/redash#5453]
### Issue Summary

Summing up Cells and then use Concat on them used to work until some Update appearead (i didn't recognize the bug instantly, so i don't know when it broke)

### Steps to Reproduce

```
SELECT 
  concat(SUM(a.nb1), " ,", SUM(a.nb2), " ,", SUM(a.nb3)) AS singl_dg_nb, 
  concat(SUM(a.nb10), " ,", SUM(a.nb11), " ,", SUM(a.nb12)) AS two_dg_nb 
FROM(
SELECT 2 AS nb1, 3 AS nb2, 4 AS nb3, 11 AS nb10, 12 AS nb11, 13 AS nb12
UNION  
SELECT 1 AS nb1, 2 AS nb2, 3 AS nb3, 10 AS nb10, 11 AS nb11, 12 AS nb12) AS a
```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 9.0.0-beta
* Browser/OS: Chrome on Windows 10
* How did you install Redash: via docker

**Comment by kravets-levko** [comment]
@hebbet

1. which data source you use?
2. what do you expect to see?
3. what do you actually see?
