### ISSUE TITLE
Data Source Setup: test connection button is disabled after Save

### ISSUE THREAD

**Issue by susodapop** [getredash/redash#5455]
### Issue Summary

The **Test Connection** on the data source page is disabled after the user clicks "Save". Reloading the browser page enables it again.

![dirty-button](https://user-images.githubusercontent.com/17067911/113299489-8b1a4f00-92c2-11eb-9a00-1c2179bcde34.gif)

### Steps to Reproduce

1. Create a JSON data source and save (test connection button is `enabled`)
2. Add a username or password field and click Save (test connection button is `disabled`)
3. Reload the page (test connection button is `enabled`)

The state of the form should be identical. But without a page reload it's treated as "dirty" even after save. 

Expected behavior: saving the form ought to set `dirty===false`.

### Technical details:

* Redash Version: latest master (6228f4cf714c03e672c45d5f311b0faa0fdbf452)
* Browser/OS: Chrome / MacOS / M1 Macbook
* How did you install Redash: Docker

**Comment by susodapop** [comment]
Thinking about this more: I don't know if the test connection button should be disabled _ever_. 

- When the user is changing parameters it should be enabled
- When the user is not changing parameters it should be enabled

Can we just remove the logic that disables it entirely?

**Comment by susodapop** [comment]
https://github.com/getredash/redash/blob/a61a25dd3224c7ed97da711fe42667f0647d3f20/client/app/pages/data-sources/EditDataSource.jsx#L111

Setting this boolean `false` has no affect on the behavior. Clicking Save still disables the Test button.

**Comment by susodapop** [comment]
Having spoken with @kravets-levko offline I learned two things:

1. We should disable the test button when a user has not saved changes because the Test operation always uses the most recently saved details.
2. This means the current disable behavior is the exact inverse of our need.

**Comment by susodapop** [comment]
Here is where the dirty state is set after the form is saved:

https://github.com/getredash/redash/blob/a61a25dd3224c7ed97da711fe42667f0647d3f20/client/app/components/dynamic-form/DynamicForm.jsx#L168

**Comment by JyothiGandi** [comment]
Hello there @susodapop I'm interested in working on this issue. Can I work on this issue?

**Comment by JyothiGandi** [comment]
@susodapop Raised a PR https://github.com/getredash/redash/pull/5666, please take a look.

_(Note: Ignore first mentioned #7d2d1a2 commit, [#6c71643](https://github.com/JyothiGandi/redash/commit/6c716432c08e5ec9d8c40411da2e41bcaaa88499) is the actual one)_

**Comment by JyothiGandi** [comment]
Hi @susodapop Got a chance to review above PR #5666 :)
