### ISSUE TITLE
Bigquery Runner throws Exception in V9

### ISSUE THREAD

**Issue by masterlittle** [getredash/redash#5493]
### Issue Summary

When running bigquery runner, it doesn't show up as a datasource in redash. On further inspection seems like when initial imports are done it isn't able to import apiclient. On further reading I read that apiclient is deprecated in favor of googleapiclient. 
Can confirm it works after switching the imports to use googleapiclient.

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. Run redash
2. Check datasources. Bigquery is not visible.
3. Switch imports to googleapiclient. Starts working

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

Expectation - On starting redash, the Bigquery datasource should have been visible.

### Technical details:

* Redash Version: v9-beta
* Browser/OS: Mac OS
* How did you install Redash: Running through source code

**Comment by arikfr** [comment]
Would you like to submit a Pull Request with the change you did to make it work?

**Comment by susodapop** [comment]
I can't reproduce this. 

1. Clone repo
2. Checkout master
3. `npm run build && docker-compose up -d`

Big Query data source is available 🤷

**Comment by arikfr** [comment]
I believe this was fixed. Please reopen if it reproduces on v10-beta (about to be released).
