### ISSUE TITLE
LDAP Authorization

### ISSUE THREAD

**Issue by maltiwankhade** [getredash/redash#5503]
Hi there,
Can we implement Group specific authentication in Redash using LDAP? 
LDAP is connecting but wants to restrict users based on Groups they belongs. Can we handle that from helm chart ?Any suggestion?

**Comment by grugnog** [comment]
@maltiwankhade sounds good - I moved this to the Redash project, although I realized that there is a tracker for those at https://discuss.redash.io/c/feature-requests/5 - this is probably a better place for this (unless you are planning to submit a PR yourself!)

**Comment by susodapop** [comment]
Yes please add a feature request for this on the user forum. We use this issue tracker exclusively for bugs.
