### ISSUE TITLE
The csv API Key of query results is diffirent with the SQL execute results

### ISSUE THREAD

**Issue by Ronghefeng** [getredash/redash#5508]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by Ronghefeng** [comment]
The csv API Key of query results is diffirent with the SQL execute results，the file from api key is oldder than the sql execute results

**Comment by susodapop** [comment]
Hi @Ronghefeng please update your issue description with reproduction steps. Currently only the template text appears.

**Comment by susodapop** [comment]
I'm closing this for lack of information. Feel free to reopen if you can provide more detail.
