### ISSUE TITLE
npm run build，Failed to start

### ISSUE THREAD

**Issue by 475cheng** [getredash/redash#5510]
Found 131 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @redash/viz@1.0.0 type-gen: `tsc --emitDeclarationOnly`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @redash/viz@1.0.0 type-gen script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-07T03_28_40_232Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @redash/viz@1.0.0 build:babel: `npm run type-gen && npm run build:babel:base`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @redash/viz@1.0.0 build:babel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-07T03_28_40_263Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! redash-client@9.0.0-beta build:viz: `(cd viz-lib && npm run build:babel)`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the redash-client@9.0.0-beta build:viz script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-07T03_28_40_293Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! redash-client@9.0.0-beta build: `npm run clean && npm run build:viz && NODE_ENV=production webpack`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the redash-client@9.0.0-beta build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-07T03_28_40_338Z-debug.log

**Comment by gaecoli** [comment]
Did you run npm install wrong?

**Comment by 475cheng** [comment]
> 你运行 npm install 错了吗？

没有
