### ISSUE TITLE
Fresh install has forced https redirects when using domain name

### ISSUE THREAD

**Issue by SharpThunder** [getredash/redash#5526]
### Issue Summary

Fresh install has forced https redirects when using domain name. Accessing through IP works fine.
This make usage without SSL impossible.

### Steps to Reproduce

1. Access URL from browser

Expected: Setup page
What happens is 307 internal redirect to https.

### Technical details:

* Redash Version: 8.0.0
* Browser/OS: Chrome
* How did you install Redash: AMI

**Comment by arikfr** [comment]
Do you have MULTI_ORG set to True?

**Comment by SharpThunder** [comment]
No. I used SSL in the end to access Redash for the first time.

**Comment by SharpThunder** [comment]
This was due to .dev domain's hsts requirement. Sorry about that 😐
