### ISSUE TITLE
[MongoDB] Filter by UUID not working

### ISSUE THREAD

**Issue by flibustier7seas** [getredash/redash#5527]
### Issue Summary

Filter by UUID (binary subtype 0x04) for mongodb not working.

### Steps to Reproduce

In mongo shell I can find documents by UUID using BinData:

```sh
> use users
switched to db users

> db.users.insert({ "_id" : ObjectId("60dc2c3a7911f0e60f6dceb2"), "userId" : UUID("1dee688c-9974-4939-ade3-bac9735efffd") })
WriteResult({ "nInserted" : 1 })

> UUID('1dee688c-9974-4939-ade3-bac9735efffd').base64()
He5ojJl0STmt47rJc17//Q==

> db.users.findOne({ "userId": BinData(4, "He5ojJl0STmt47rJc17//Q==" ) } )
{ "_id" : ObjectId("60dc2c3a7911f0e60f6dceb2"), "userId" : UUID("1dee688c-9974-4939-ade3-bac9735efffd") }

> JSON.stringify(db.users.findOne({ "userId": BinData(4, "He5ojJl0STmt47rJc17//Q==" ) } ))
{"_id":{"$oid":"60dc2c3a7911f0e60f6dceb2"},"userId":{"$binary":"He5ojJl0STmt47rJc17//Q==","$type":"04"}}
```

But in redash, same query return empty results:

```json
{
    "collection": "users",
    "query": {
        "userId": {
            "$eq": {
                "$binary": {
                    "base64": "He5ojJl0STmt47rJc17//Q==",
                    "subType": "04"
                }
            }
        }
    },
    "fields": {
        "_id": 1,
        "userId": 2
    }
}
```

**Comment by flibustier7seas** [comment]
I think it is a bug, because redash creates incorrect query to mongodb.

https://discuss.redash.io/t/mongodb-filter-by-uuid-not-working/8688

**Comment by susodapop** [comment]
Thanks for reporting this. It's really not a bug (flaw with existing code). The issue is that our connector doesn't support this column type for MongoDB. You can open a feature request at discuss.redash.io to implement that feature. Or if you can implement it yourself we're happy to review and get it merged ASAP.
