### ISSUE TITLE
Rewording suggestion, as Taiwan is not a country name

### ISSUE THREAD

**Issue by renyuneyun** [getredash/redash#5538]
Not for a fight, but just thought things should be based on **facts**, not just emotions.

Surely, many people are aware of the separated governance of Taiwan and Mainland China (, which is the cause of everything). That's why I suggest using a middle-ground solution to this issue:
- Change "country" to "country/region"; and
- Change the label "China" to "China (Mainland)".

- - - - - -

Facts to support this:
- The name "China' has been used before the 20th century;
- The official country name of the government controlling Taiwan is **the Republic of China** (ROC)
    - It is the (retreated) same government governing mainland China between 1912-1949
- The current government of Taiwan never declared independency nor changed its name to something else
- UN recognizes the People's Republic of China (PRC) as *the only legitimate representative of China to the United Nations* (United Nations General Assembly Resolution 2758)
- Most countries (including US, if you wonder) around the world (with [15 exceptions](https://en.wikipedia.org/wiki/Foreign_relations_of_Taiwan)) has a diplomatic relation to PRC, which has a prerequisite of acknowledging the "One China Principle" (i.e. there can be only one government representing China)

Conclusion:
1. *China* is a cultural country name;
    - ROC and PRC both declared themselves a Chinese government;
2. Taiwan belongs to *China*
    - Not necessarily the PRC at the moment, but surely there is no country named "Taiwan", and Taiwan doesn't belong to other countries (e.g. Filipino);
3. The PRC is recognized as the representative government of China (unless you require unanimity).

Therefore, if acknowledging these facts, one should either conclude that Taiwan belongs to PRC, or (without the One China Principle) the Mainland and Taiwan are both Chinas, under the name of PRC and ROC respectively. In either case, it's incorrect to simply label one of them "China" and the other one something else.

This proposed solution should be acceptable to everyone except the ones dedicated to Taiwan independence. But the current situation is also not acceptable to everyone, e.g. not the ones who do *not* support Taiwan independence (e.g. part of people in Taiwan and the majority of people in the Mainland). Again, **facts** are what should be based on, not personal claims or simply the volume of a particular viewpoint.

If the regime controlling Taiwan declared independency / changed its name and/or above 1/2 world countries recognized it, this would be a different story. But we can have the same story for moon crashed to the Earth -- not facts.

**Comment by arikfr** [comment]
@renyuneyun thank you for the explanation! Would you like to submit a pull request with the change you suggested?

**Comment by gaecoli** [comment]
@arikfr I pushed PR [Taiwan is part of China](https://github.com/getredash/redash/pull/5539), please merge it. I just modified the coordinates of Taiwan to the territory of China, and the coordinates of other countries have not been modified. Thank you!

Map now display:
![wecom-temp-60dd882686206a593b2715b9d6e4d7f2](https://user-images.githubusercontent.com/46274612/126314975-ddddf93f-807f-4421-b817-3f2f11da998a.png)

**Comment by gaecoli** [comment]
> @renyuneyun thank you for the explanation! Would you like to submit a pull request with the change you suggested?

So do what you said, please.

**Comment by arikfr** [comment]
@gaecoli thank you for taking a stab at this, but this seems to be very different than was suggested in this issue?

**Comment by gaecoli** [comment]
> @gaecoli thank you for taking a stab at this, but this seems to be very different than was suggested in this issue?

I will modify this PR to follow @renyuneyun explanation.

**Comment by gaecoli** [comment]
> @gaecoli thank you for taking a stab at this, but this seems to be very different than was suggested in this issue?

I deleted that stabs, and closed PR, i will repush a PR following @renyuneyun explanation.

**Comment by gaecoli** [comment]
> @renyuneyun thank you for the explanation! Would you like to submit a pull request with the change you suggested?

I pushed new PR for this issue.

**Comment by gaecoli** [comment]
@arikfr This new PR i just modified `Country` to `Country/Region`, and `China` to `China (MainLand)`.  I didn't make any others country or region coordinate. Thank you.

**Comment by nathan-protempo** [comment]
The term "country" can apply to any distinct geographical area as there is no agreed definition of a country. 

Per Wikipedia: 
> A country is a distinct territorial body or political entity (i.e. a nation)[clarification needed]. It is often referred to as the land of an individual's birth, residence or citizenship.
> 
> A country may be an independent sovereign state or part of a larger state,[1] as a non-sovereign or formerly sovereign political division, a physical territory with a government, or a geographic region associated with sets of previously independent or differently associated peoples with distinct political characteristics. It is not inherently sovereign.

Collins Dictionary:
> country noun (POLITICAL UNIT)
> an area of land that forms an independent political unit with its own government;

By these definitions Taiwan is indeed a country as are other states with a similar geopolitical status e.g Kosovo, and also Israel (not recognised by 29 UN members) and South Korea (claimed by North Korea).

**Comment by guidopetri** [comment]
https://en.wikipedia.org/wiki/China

https://en.wikipedia.org/wiki/Taiwan

Deferring to Wikipedia.
