### ISSUE TITLE
Test connection data source error

### ISSUE THREAD

**Issue by Jaysonyun** [getredash/redash#5561]
### Issue Summary

The test database connection reports an error. Redash uses the latest version.

### Steps to Reproduce

This is error message:

[2021-08-12 09:59:19,909][PID:5596][ERROR][redash.app] Exception on /api/data_sources/3/test [POST]
Traceback (most recent call last):
  File "D:\python\PycharmProjects\redash\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\python\PycharmProjects\redash\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\python\PycharmProjects\redash\venv\lib\site-packages\flask_restful\__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "D:\python\PycharmProjects\redash\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\python\PycharmProjects\redash\venv\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "D:\python\PycharmProjects\redash\redash\handlers\base.py", line 33, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "D:\python\PycharmProjects\redash\venv\lib\site-packages\flask_restful\__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "D:\python\PycharmProjects\redash\redash\permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "D:\python\PycharmProjects\redash\redash\handlers\data_sources.py", line 263, in post
    job.refresh()
  File "D:\python\PycharmProjects\redash\venv\lib\site-packages\rq\job.py", line 518, in refresh
    raise NoSuchJobError('No such job: {0}'.format(self.key))
rq.exceptions.NoSuchJobError: No such job: b'rq:job:5c967a55-4555-4ebb-b55f-4ddc9ec46dc2'
[2021-08-12 09:59:19,917][PID:5596][INFO][metrics] method=POST path=/api/data_sources/3/test endpoint=datasourcetestresource status=500 content_type=application/json content_length=36 duration=96127.77 query_count=4 query_duration=17.96
[2021-08-12 09:59:19,929][PID:5596][INFO][werkzeug] 127.0.0.1 - - [12/Aug/2021 09:59:19] "POST /api/data_sources/3/test HTTP/1.1" 500 -

### Technical details:

* Redash Version:Latest version
* Browser/OS:Windows10
* How did you install Redash:Local startup，tool is PyCharm 2021.1.1

**Comment by portfield-slash** [comment]
I think it is related to the following matters.

https://discuss.redash.io/t/schema-browser-is-empty-and-error-500-on-data-sources-page/8915/18

It is a failure caused by RQ, and I think it is partly because Celery was replaced with RQ in v9.0.0-beta.
If possible, please downgrade to v8.0.0 and check the operation.

Below are the results of running my environment.

### Steps to Reproduce
1. Redash login
2. Click the [Settings]
3. Click the data source created in [Data Sources]
4. Click the [Test Connection]

### Technical details:

* Redash Version: 10.1.0
* Browser/OS: Chrome v96.0.4664.93, Safari v14.12/Client: MacOS BigSur v11.52
* How did you install Redash: use Cloudron v7.0.4, Ubuntu v20.04.3 on AWS

### Error Message:(Redash Docker Container)

```
Dec 16 23:28:42 [2021-12-16 14:28:42,691][PID:341][ERROR][redash.app] Exception on /api/data_sources/1/test [POST]
Dec 16 23:28:42 Traceback (most recent call last):
Dec 16 23:28:42 File "/app/code/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
Dec 16 23:28:42 rv = self.dispatch_request()
Dec 16 23:28:42 File "/app/code/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
Dec 16 23:28:42 return self.view_functions[rule.endpoint](**req.view_args)
Dec 16 23:28:42 File "/app/code/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
Dec 16 23:28:42 resp = resource(*args, **kwargs)
Dec 16 23:28:42 File "/app/code/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
Dec 16 23:28:42 return func(*args, **kwargs)
Dec 16 23:28:42 File "/app/code/venv/lib/python3.7/site-packages/flask/views.py", line 89, in view
Dec 16 23:28:42 return self.dispatch_request(*args, **kwargs)
Dec 16 23:28:42 File "/app/code/redash/redash/handlers/base.py", line 33, in dispatch_request
Dec 16 23:28:42 return super(BaseResource, self).dispatch_request(*args, **kwargs)
Dec 16 23:28:42 File "/app/code/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
Dec 16 23:28:42 resp = meth(*args, **kwargs)
Dec 16 23:28:42 File "/app/code/redash/redash/permissions.py", line 71, in decorated
Dec 16 23:28:42 return fn(*args, **kwargs)
Dec 16 23:28:42 File "/app/code/redash/redash/handlers/data_sources.py", line 263, in post
Dec 16 23:28:42 job.refresh()
Dec 16 23:28:42 File "/app/code/venv/lib/python3.7/site-packages/rq/job.py", line 518, in refresh
Dec 16 23:28:42 raise NoSuchJobError('No such job: {0}'.format(self.key))
Dec 16 23:28:42 rq.exceptions.NoSuchJobError: No such job: b'rq:job:5b98af99-3bf3-4863-8af0-b86f8da811b5'
Dec 16 23:28:42 [2021-12-16 14:28:42,693][PID:341][INFO][metrics] method=POST path=/api/data_sources/1/test endpoint=datasourcetestresource status=500 content_type=application/json content_length=36 duration=90175.56 query_count=4 query_duration=16.0
```

### Redis Key:

```
127.0.0.1:6379> type rq:job:5b98af99-3bf3-4863-8af0-b86f8da811b5
none
```

**Comment by susodapop** [comment]
Hey @portfield-slash I really wouldn't encourage people to _downgrade_ back to V8. We don't support it any longer. We are actively developing Redash however and if there is a bug here we want to patch it ASAP.

I think this is a result of the API server not having access to any or a correct Redis instance. Can you confirm that all containers in Docker share the same environment variables?

It would also be helpful if we could reproduce this with the standard development setup. Both of the reproductions here use independent tools: Pycharm (not recommended) and Cloudron.

**Comment by portfield-slash** [comment]
@susodapop 
Thank you for your prompt confirmation.

Well, it wasn't appropriate to recommend an older version.
I also strongly want to use Redash with the latest version.

Currently, Redash and Metabase are installed after installing Cloudron. Below is a list of currently operating containers.

The API server is recognized as `cloudron / io.redash.cloudronapp: 20211124-151700-410398dc8` only.

```
CONTAINER ID   IMAGE                                                         COMMAND                CREATED        STATUS        PORTS                                                          NAMES
e18341aa7ba0   cloudron/com.metabase.cloudronapp:20211211-114133-313844f00   "/app/pkg/start.sh"    4 hours ago    Up 2 hours                                                                   afad022b-e4e1-47cc-9ed9-cf26013c0365
0b8fcdcf2579   cloudron/io.redash.cloudronapp:20211124-151700-410398dc8      "/app/pkg/start.sh"    11 hours ago   Up 9 hours                                                                   c15c0373-3323-433b-8b5a-a15ed271d4a1
56b6eeeef701   cloudron/redis:3.0.4                                          "/app/code/start.sh"   11 hours ago   Up 9 hours    3000/tcp, 6379/tcp                                             redis-c15c0373-3323-433b-8b5a-a15ed271d4a1
55b7188fc52b   cloudron/sftp:3.4.2                                           "/app/code/start.sh"   35 hours ago   Up 14 hours   0.0.0.0:222->22/tcp, :::222->22/tcp                            sftp
eb213a2f1717   cloudron/graphite:3.0.1                                       "/app/code/start.sh"   35 hours ago   Up 14 hours   127.0.0.1:2003-2004->2003-2004/tcp, 127.0.0.1:8417->8000/tcp   graphite
4dcbdd0820cf   cloudron/mongodb:4.0.2                                        "/app/code/start.sh"   35 hours ago   Up 14 hours                                                                  mongodb
77f250a37646   cloudron/postgresql:4.1.1                                     "/app/code/start.sh"   35 hours ago   Up 14 hours   3000/tcp, 5432/tcp                                             postgresql
e41c52d4238c   cloudron/mysql:3.0.7                                          "/app/code/start.sh"   35 hours ago   Up 14 hours                                                                  mysql
9f3b3fc815c2   cloudron/turn:1.3.1                                           "/app/code/start.sh"   35 hours ago   Up 14 hours                                                                  turn
18f330566410   cloudron/mail:3.5.0                                           "/app/code/start.sh"   35 hours ago   Up 14 hours                                                                  mail
```

`cloudron / io.redash.cloudronapp: 20211124-151700-410398dc8` Looking at the environment variables inside the container, 
the environment variables related to redis are likely to be:

```
#The password is hidden.
CLOUDRON_REDIS_HOST=redis-c15c0373-3323-433b-8b5a-a15ed271d4a1
CLOUDRON_REDIS_PASSWORD=XXX
CLOUDRON_REDIS_PORT=6379
CLOUDRON_REDIS_URL=redis://redisuser:XXX@redis-c15c0373-3323-433b-8b5a-a15ed271d4a1
```

I was also able to confirm that I can connect to the redis container using environment variables from inside the container.

```
root@c15c0373-3323-433b-8b5a-a15ed271d4a1:/app/code/redash# redis-cli -h $CLOUDRON_REDIS_HOST                      
redis-c15c0373-3323-433b-8b5a-a15ed271d4a1:6379> 
```

**Comment by susodapop** [comment]
The Redash containers only look for environment variables prefixed with `REDASH_`. So for the Redis host it should be `REDASH_REDIS_URL` not `CLOUDRON_REDIS_HOST`.

**Comment by gramakri** [comment]
I am the author of the redash Cloudron package. `REDASH_REDIS_URL` should be set correctly and it is set here - https://git.cloudron.io/cloudron/redash-app/-/blob/master/start.sh#L43

**Comment by susodapop** [comment]
Hey @gramakri thanks for jumping in on this. From the file you shared I think the REDIS_URL is not in the correct format. You can peek at our official [setup script](https://github.com/getredash/setup/blob/master/setup.sh) for how we provision this. Redis doesn't use a password. The format is `redis://host:port/0`.

Based on this I wouldn't expect the current Cloudron Redash package to work successfully. Can you advise if it works for anyone at all?

**Comment by susodapop** [comment]
Note that our setup script has not been configured for V10 yet (it's on the long list of items in the next few months). But the parts specifically relating to Redis have not changed since getredash/setup was last updated.

**Comment by gramakri** [comment]
@susodapop thanks for the info! I think that might be it that redis needs to be configured without a password. I am fixing the package and will test this scenario.

**Comment by gramakri** [comment]
@susodapop I have updated Cloudron package to use redis without password and things seem to work fine

**Comment by portfield-slash** [comment]
@gramakri 
It's not working well.

I reinstalled Redash on Cloudron and confirmed that the Redash and Redis containers are updated.

```
CONTAINER ID   IMAGE                                                         COMMAND                CREATED          STATUS          PORTS                                                          NAMES
fe11271a437a   cloudron/io.redash.cloudronapp:20211224-041048-4734bb4b1      "/app/pkg/start.sh"    26 minutes ago   Up 26 minutes                                                                  0f8dd859-e57a-47f0-82a6-7ba509d55be6
13c3225d3b06   cloudron/redis:3.0.4                                          "/app/code/start.sh"   27 minutes ago   Up 27 minutes   3000/tcp, 6379/tcp                                             redis-0f8dd859-e57a-47f0-82a6-7ba509d55be6
```

I then ran `Test Connection` and got the same error. The error message is as follows.

```
Dec 24 15:51:03 [2021-12-24 06:51:03,716][PID:209][ERROR][redash.app] Exception on /api/data_sources/1/test [POST]
Dec 24 15:51:03 Traceback (most recent call last):
Dec 24 15:51:03 File "/app/code/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
Dec 24 15:51:03 rv = self.dispatch_request()
Dec 24 15:51:03 File "/app/code/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
Dec 24 15:51:03 return self.view_functions[rule.endpoint](**req.view_args)
Dec 24 15:51:03 File "/app/code/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
Dec 24 15:51:03 resp = resource(*args, **kwargs)
Dec 24 15:51:03 File "/app/code/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
Dec 24 15:51:03 return func(*args, **kwargs)
Dec 24 15:51:03 File "/app/code/venv/lib/python3.7/site-packages/flask/views.py", line 89, in view
Dec 24 15:51:03 return self.dispatch_request(*args, **kwargs)
Dec 24 15:51:03 File "/app/code/redash/redash/handlers/base.py", line 33, in dispatch_request
Dec 24 15:51:03 return super(BaseResource, self).dispatch_request(*args, **kwargs)
Dec 24 15:51:03 File "/app/code/venv/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
Dec 24 15:51:03 resp = meth(*args, **kwargs)
Dec 24 15:51:03 File "/app/code/redash/redash/permissions.py", line 71, in decorated
Dec 24 15:51:03 return fn(*args, **kwargs)
Dec 24 15:51:03 File "/app/code/redash/redash/handlers/data_sources.py", line 263, in post
Dec 24 15:51:03 job.refresh()
Dec 24 15:51:03 File "/app/code/venv/lib/python3.7/site-packages/rq/job.py", line 518, in refresh
Dec 24 15:51:03 raise NoSuchJobError('No such job: {0}'.format(self.key))
Dec 24 15:51:03 rq.exceptions.NoSuchJobError: No such job: b'rq:job:9d9a4ab5-9036-49c0-8bcc-fe97886155e9'
```

Is it a problem in my environment?

**Comment by gramakri** [comment]
This can be closed, the Cloudron package is fixed.

**Comment by susodapop** [comment]
Thank you!

**Comment by connectiv-kenichiro-tsuda** [comment]
@susodapop @gramakri 
Thank you for your support.
Everything worked fine.

**Comment by portfield-slash** [comment]
@susodapop @gramakri

Thank you for your support.
Everything worked fine.
