### ISSUE TITLE
ClickHouse source Refresh schema failed！

### ISSUE THREAD

**Issue by NickYang1988** [getredash/redash#5565]
### Issue Summary

Refresh schema failed！

### Steps to Reproduce

1. I add a ClickHousr database source
2. In the query page and dashboard page, there is an error "Refresh schema failed！"

### Technical details:

* Redash Version: 10.0.0-beta.b49597
* Browser/OS: Chrome laster, MacOS 14.5
* How did you install Redash: contrib-helm-charts

**Comment by NickYang1988** [comment]
I tested 9.0.0-beta.b49509

Same problems.

**Comment by denisov-vlad** [comment]
Hi!

Is the issue only with ClickHouse? Could  you try to refresh any other datasource please?

**Comment by kravets-levko** [comment]
Hi! Can you please check if there's anything in logs?

**Comment by AaronSamuelBernal** [comment]
i have the same problem. In test connection have this issue "Connection error to: 102.28.6.9:8123 (InvalidSchema)."

**Comment by NickYang1988** [comment]
Now I use Metabase with ClickHouse Driver.

**Comment by susodapop** [comment]
> t connection have this issue "Con



> i have the same problem. In test connection have this issue "Connection error to: 102.28.6.9:8123 (InvalidSchema)."

@AaronSamuelBernal  can you share any information about your setup? What versino of Redash do you run? How did you install it? Are you able to query clickhouse?

**Comment by vera2pm** [comment]
I have the same problem..

@susodapop Can you share how to pull the schema, please?
