### ISSUE TITLE
Cannot set colors in "classify by" in "map visualization" 

### ISSUE THREAD

**Issue by shyamgopal** [getredash/redash#557]
1) Cannot set color values that I want, for "Classify by column". I set the html color value, the background of that form field turns to appropriate color, but when I hit "Save" (Save visualization) button, all the form fields of "Classify by column" values, turn back to default colors and map shows original default colors.
2) When I login as "admin" and query the "visualization" table of reddash::metadata, the color of appropriate "Classify by column" seems to have got the correct html color code set by me, but this is not reflected in actual map visualization.

**Comment by arikfr** [comment]
When you hit save, do you see the green "Visualization saved" notification (should appear in the bottom-left corner) or an error message?

**Comment by shyamgopal** [comment]
I don't see any error message. I do see the green "Visualization saved" notification, but it appears on bottom right corner. Thank you for responding !

**Comment by arikfr** [comment]
I've just managed to reproduce this, which makes creating a fix much easier. I'll update this issue when I get it fixed.

Thank you for reporting this.

**Comment by ayojimoh** [comment]
Running into this same issue as well. Unable to retain saved changes to the "Classify by Column" selections. I get the "Visualization saved" confirmation but nothing updates on the map and it resets to the default colors. I've tried using hex or implied html colors. Same result.

Any update on the fix? Better, yet, is there a way to change the defaults as I'd be fine with defaults if they weren't so difficult to distinguish from each other.

**Comment by arikfr** [comment]
Yes, looks like the color picking there could use an improvement. Currently it sort of auto generates a color, which might result in similar colors. I think we should switch to using a constant list of colors like we do for charts.

**Comment by arikfr** [comment]
(and fix the bug, of course)
