### ISSUE TITLE
Trino Data Sorce have Schema refresh failed. 

### ISSUE THREAD

**Issue by adp-asilva** [getredash/redash#5573]
### Technical details:

* Redash Version:9.0.0-beta(deve)
* Browser/OS:92.0.4515.131 (Versão oficial) 64 bits
* How did you install Redash: Docker Image
***************************************************

when I click on new query and select my trino Data source I have the follow msg:

Schema refresh failed.
Please try again later.

When I run a Data Source Test Connection I have Success

**Comment by susodapop** [comment]
In case this is still an issue for you: make sure that you designate the `catalog` for the Trino query runner under Redash data source settings. Without this, it defaults to the `hive` catalog. If you don't have a `hive` catalog on your Trino instance then the schema fetch will fail.
