### ISSUE TITLE
Hosted Redash Alternative - Beekeeper Analytics

### ISSUE THREAD

**Issue by rathboma** [getredash/redash#5578]
👋 Hey Redash community.

I'm one of the maintainers of [Beekeeper Studio](https://beekeeperstudio.io), an open source SQL desktop app.

We love Redash and we're sad to see the hosted version shut down, so we're thinking of launching our own version of Hosted Redash and wanted to gauge interest.

If you are interested, please fill out the form [on the Beekeeper Analytics Website](https://dash.beekeeperstudio.io).

We're going to provide a **one-click migration** path and we're focusing on:

* **Full Compatibility** - All Redash features are replicated, nothing is missing.
* **Price Honoring** - Honoring the price you were paying for Hosted Redash.
* **Simple Migration** - A simple guided migration for all Redash data - queries, dashboards, users, and connections. Our migration will maintain query & dashboard ownership and permissions.
* **Encryption** - All data will be encrypted at-rest and encrypted in transit with HTTPS. We will match or exceed existing Redash security practices.
* **Security** - We're committed to maintaining a secure environment by running regular external penetration tests.
* **Investment** - We have dedicated bandwidth to continue investment in Redash features, and the open source Redash community.

Hope to hear from some of you soon.

Matthew & Gregory

**Comment by susodapop** [comment]
It’s great you’re thinking on launching a Redash hosted service. Looking forward to having you part of the community.
We use github issues mostly for actionable things we can work on. Any other content should be in the forum where I see you've posted already [here](https://discuss.redash.io/t/hosted-redash-replacement-beekeeper-analytics/9008).
