### ISSUE TITLE
Counter visualization format is disabled

### ISSUE THREAD

**Issue by lukewest** [getredash/redash#5594]
### Issue Summary

I have an AWS machine which I’m using for redash, taken from one of your AMI's. 
I’m using Google Analytics as a data source. 
I extract e.g. ga:avgSessionDuration which is a decimal number (although I don't know if this is returned as a string through the API call). I want to format the output to 2 decimal places. But it is greyed out. 
I expected it to allow me to format the field

(This is very similar to #5071)

### Steps to Reproduce

1. Build machine on AWS from an AMI, Patch the machine etc
2. Add a new data source of GA following the README
3. Extract data to test
4. Try this query (see <img width="1777" alt="query" src="https://user-images.githubusercontent.com/120023/133995378-efe0cf19-06fb-411d-98d9-a3083cdb73ca.png">):
{
    "ids": "ga:xxxxxxx",
    "start_date": "1daysAgo",
    "end_date": "yesterday",
    "dimensions": "",
    "metrics": "ga:avgSessionDuration",
    "segment": "gaid::-14",
    "max_results": 10
}
This returns e.g. 250.39344262295083 in the table
5.  Create a new visualization of a counter 
6. Try to format the output and it is greyed out (see <img width="1751" alt="format1" src="https://user-images.githubusercontent.com/120023/133995478-e45f63ac-f59b-4ef7-af4b-92842f01792e.png">)
7. Tried changing target value - same result (see <img width="1760" alt="format2" src="https://user-images.githubusercontent.com/120023/133995593-ca4d4713-f786-4a09-9913-9566508e09bc.png">)

### Technical details:

* Redash Version: 8.0.0+b32245
* Browser/OS: Safari or Chrome on macOS Big Sur 11.6
* How did you install Redash: Using the AMI within AWS

**Comment by susodapop** [comment]
For debugging you can see the data type returned by GA with your browser's network inspector. Just find the request to the `query_results` endpoint and look at the response. If the number is wrapped in quotation marks `"` then it's returned as a string.

**Comment by lukewest** [comment]
Looks like its a string. 
` "data": {
            "rows": [
                {
                    "ga:country": "United Arab Emirates",
                    "ga:operatingSystem": "iOS",
                    "ga:users": "36",
                    "ga:sessions": "39",
                    "ga:avgSessionDuration": "344.20512820512823"
                },
                {
                    "ga:country": "United Arab Emirates",
                    "ga:operatingSystem": "Android",
                    "ga:users": "14",
                    "ga:sessions": "13",
                    "ga:avgSessionDuration": "94.6923076923077"
                },`

I can't do much about the results from GA, but could I force the results into a string with QRDS? I've not had the time to play.

**Comment by lukewest** [comment]
@susodapop Thanks for the tip (btw!)

**Comment by susodapop** [comment]
Yes QRDS would be the solution for now.

Something like `select CAST("ga:users" as INT) as "ga:users" from query_xxxx...`

Long term it would be nice if we could cast data types as part of the query runner though...

**Comment by lukewest** [comment]
@susodapop Thanks for that - I will use that approach. Like you, I prefer to be able to cast the variables in flight without having to query a set of results in memory. It means I’m not worried about the query size :-)
