### ISSUE TITLE
Export a large CSV file failed after exactly 30 seconds

### ISSUE THREAD

**Issue by myonlylonely** [getredash/redash#5613]
### Issue Summary

I have created a query that returned about 320M rows. The query successfully executed, and showed the correct result on the page. But when I want to export the result to a csv file. Each time I tried, it failed after exactly 30 seconds, and showed 502 Bad GateWay in the Chrome Dev Tools. Any way to improve exporting large csv file or get around?

### Steps to Reproduce

1. Create a query that returns many rows, and execute it.

![image](https://user-images.githubusercontent.com/8188177/135721108-55204f67-a9fe-4cad-997c-a0396acd38a9.png)

2. Export the file to csv Format.

![image](https://user-images.githubusercontent.com/8188177/135721065-fdc4abef-8884-4ff2-99bf-44e1769cd14a.png)

3. Here are the logs in the nginx and server image.

```bash
2021/10/02 13:39:50 [error] 31#31: *1 upstream prematurely closed connection while reading response header from upstream, client: XXX.XXX.XXX.XXX, server: , request: "GET /api/queries/XXX/results/XXXX961.csv HTTP/1.1", upstream: "http://XXX.XXX.XXX.XXX:5000/api/queries/XXX/results/XXXX961.csv", host: "XXX.XXX.XXX.XXX"
XXX.XXX.XXX.XXX - - [02/Oct/2021:13:39:50 +0000] "GET /api/queries/XXX/results/XXXX961.csv HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36" "-"
```

```bash 
[2021-10-02 13:39:50,388][PID:243][INFO][metrics] method=GET path=/api/queries/XXX/results/XXXX961.csv endpoint=query_result status=500 content_type=? content_length=-1 duration=30300.16 query_count=10 query_duration=1415.56
[2021-10-02 13:39:50 +0000] [243] [INFO] Worker exiting (pid: 243)
```

### Technical details:

* Redash Version: V10 (b50363)
* Browser/OS: Chrome 94
* How did you install Redash: Docker

**Comment by myonlylonely** [comment]
Timeout could be changed via environment variables in docker-compose.yml file.
https://discuss.redash.io/t/csv-xls-export-timing-out/5215
https://ariarijp.hatenablog.com/entry/2019/06/07/234851

**Comment by susodapop** [comment]
This is far, far, far outside the use-case for Redash. You would be better served with a custom API that can serve such large amounts of data. Redash is built for results around 20mb in size.

**Comment by sullerandras** [comment]
Any chance to support exporting what redash can already show in the browser? Theoretically it shouldn't even have to download anything since the data is already in the browser.
In our case the table has only about 130k rows, and the csv export works within a few seconds but the excel export always times out:
```
method=GET path=/api/queries/1780/results/3297799.xlsx endpoint=query_result status=500 content_type=? content_length=-1 duration=30222.10 query_count=10 query_duration=1110.53
method=GET path=/api/queries/1780/results/3297799.xlsx endpoint=query_result status=500 content_type=? content_length=-1 duration=30041.77 query_count=10 query_duration=1111.14
method=GET path=/api/queries/1780/results/3297799.xlsx endpoint=query_result status=500 content_type=? content_length=-1 duration=30047.93 query_count=10 query_duration=1097.14
method=GET path=/api/queries/1780/results/3297799.xlsx endpoint=query_result status=500 content_type=? content_length=-1 duration=30240.46 query_count=10 query_duration=1432.38
method=GET path=/api/queries/1780/results/3297799.xlsx endpoint=query_result status=500 content_type=? content_length=-1 duration=30087.46 query_count=10 query_duration=1121.00
method=GET path=/api/queries/1780/results/3297799.csv endpoint=query_result status=200 content_type=text/csv; charset=UTF-8 content_length=33164012 duration=5258.27 query_count=10 query_duration=1099.66
method=GET path=/api/queries/1780/results/3297799.xlsx endpoint=query_result status=500 content_type=? content_length=-1 duration=30346.48 query_count=10 query_duration=1181.85
method=GET path=/api/queries/1780/results/3297799.xlsx endpoint=query_result status=500 content_type=? content_length=-1 duration=30159.79 query_count=10 query_duration=1131.87
```
