### ISSUE TITLE
Queries stuck after upgrading from v8 to v10

### ISSUE THREAD

**Issue by fosple** [getredash/redash#5620]
### Issue Summary

I upgraded from v8 to v10. For around 7 days the system worked without a problem. Now queries get stuck and don't get executed. The previous install of v8 ran smoothly for around a year without any issues.

### Steps to Reproduce

1. Install v8 (Docker)
2. Setup scheduled queries (run every 1min)
2. Upgrade from v8 to v10
3. Wait around 7 days
4. Queries are stuck in the queue - scheduled queries do not get executed anymore
5. Go to https://www.base-url.com/admin/queries/jobs
6. Switch between "RQ Status" and "Outdated Queries" tab
7. Number of "Queued Jobs" increases without going down

See video:
https://user-images.githubusercontent.com/4522947/136854321-444d94fc-926f-4616-993a-75d806112f39.mov

See image:
![redash_bug_01](https://user-images.githubusercontent.com/4522947/136854063-ef3f7b5b-58e4-4b6c-9f9c-eda3741df617.png)

### Unsuccessful tries to solve the problem

- Restarting the docker container did not help ("cd /opt/redash";"docker-compose stop"; "docker-compose up -d").
- Increasing scheduled_worker count from 1 to 5 did not help (docker-compose.yml -> scheduled_worker -> "WORKERS_COUNT: 5")

### Technical details:

* Redash Version: Docker @ redash/redash:10.0.0.b50363
* Browser/OS: Firefox 92.0.1 (64-bit) / MacOS 11.6
* How did you install Redash: 
     * v8 install: Docker Install (via https://github.com/getredash/setup)
     * v10 upgrade: Followed https://github.com/getredash/redash/releases/tag/v10.0.0 & https://discuss.redash.io/t/v10-beta-is-ready/8633

**Comment by MaxBer** [comment]
We ended up specifying the following queues for the worker scheduled worker. I guess it's also possible to break it out into yet another worker.

QUEUES: "scheduled_queries,schemas,periodic,emails,default"

**Comment by susodapop** [comment]
This jives with what we're seeing when updating a V8 instance in AWS ([see here](https://discuss.redash.io/t/ec2-deployment-instance-size-issue/9271)). We haven't gotten to the bottom of it yet. But productionised V10 seems to consume a lot more memory than V8/V9.

**Comment by awalias** [comment]
our c5.large also becoming unavailable when we try and run any queries after upgrading from v8 to v10, can't find the problem yet

**Comment by fosple** [comment]
@awalias So far redash is running stable for me after adding more RAM. It seems like this solved my problem.

**Comment by awalias** [comment]
this solved my problem, it seems there was a typo in the upgrade instructions: https://discuss.redash.io/t/query-auto-update-does-not-work-redash-v10/9353/11

**Comment by lucasfcnunes** [comment]
Looks like it's solved.

**Comment by KaranpreetAnalytics** [comment]
@awalias the URL you mentioned is not working, can you share the typo here?
