### ISSUE TITLE
Getting `sqlalchemy.exc.ProgrammingError` after bumping to V10

### ISSUE THREAD

**Issue by wtfzambo** [getredash/redash#5624]
### Issue Summary

I have a self-hosted Redash instance on AWS which was installed using the AMI. I want to bump this to V10, and for testing purposes I created locally on my machine a V8 instance and then followed the steps to bump it to V10.

V8 was working normally, whereas after the upgrade to V10, I get the following error after trying to login (as already described [here](https://github.com/getredash/redash/issues/5381)):

```bash
postgres_1          | ERROR:  column dashboards.options does not exist at character 614
postgres_1          | STATEMENT:  SELECT count(*) AS count_1
postgres_1          |   FROM (SELECT dashboards.updated_at AS dashboards_updated_at, dashboards.created_at AS dashboards_created_at, dashboards.id AS dashboards_id, dashboards.version AS dashboards_version, dashboards.org_id AS dashboards_org_id, dashboards.slug AS dashboards_slug, dashboards.name AS dashboards_name, dashboards.user_id AS dashboards_user_id, dashboards.layout AS dashboards_layout, dashboards.dashboard_filters_enabled AS dashboards_dashboard_filters_enabled, dashboards.is_archived AS dashboards_is_archived, dashboards.is_draft AS dashboards_is_draft, dashboards.tags AS dashboards_tags, dashboards.options AS dashboards_options
postgres_1          |   FROM dashboards
postgres_1          |   WHERE 1 = dashboards.org_id AND dashboards.is_archived = false) AS anon_1
server_1            | [2021-10-15 15:41:11,950][PID:46][ERROR][redash.app] Exception on /api/organization/status [GET]
server_1            | Traceback (most recent call last):
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
server_1            |     cursor, statement, parameters, context
server_1            |   File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
server_1            |     cursor.execute(statement, parameters)
server_1            | psycopg2.errors.UndefinedColumn: column dashboards.options does not exist
server_1            | LINE 2: ...rds_is_draft, dashboards.tags AS dashboards_tags, dashboards...


server_1            | The above exception was the direct cause of the following exception:
... some stack-trace
server_1            | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dashboards.options does not exist
server_1            | LINE 2: ...rds_is_draft, dashboards.tags AS dashboards_tags, dashboards...
```

### Steps to Reproduce

1. Install a clean V8 instance:
    - Get docker-compose.yml from [here](https://github.com/getredash/setup/blob/master/data/docker-compose.yml)
    - Make an env file with default values:
      ```bash
      PYTHONUNBUFFERED=0
      REDASH_LOG_LEVEL=INFO
      REDASH_REDIS_URL=redis://redis:6379/0
      POSTGRES_PASSWORD=banana
      REDASH_COOKIE_SECRET=redash-selfhosted
      REDASH_SECRET_KEY=redash-selfhosted
      REDASH_DATABASE_URL=postgresql://postgres:banana@postgres/postgres
      ```
    - docker-compose run --rm server create_db
    - docker-compose up -d
2. Now bump it to V10 following instructions [here](https://github.com/getredash/redash/releases/tag/v10.0.0)
3. Visit localhost:5000 and login
4. See error in terminal

### Technical details:

* Redash Version: V8.0.0.b32245 being upgraded to V10.0.0
* Browser/OS: Ubuntu 18.04
* How did you install Redash: See steps above

**Comment by wtfzambo** [comment]
After some intense google fu I figured out I am also supposed to run `docker-compose run --rm server manage db upgrade` after upgrading.

**Comment by susodapop** [comment]
Thanks for drawing attention to this. I'm sad to hear the google fu was necessary since this command is already part of our official [upgrade instructions](https://redash.io/help/open-source/admin-guide/how-to-upgrade). But if those instructions. I wonder how we can make this easier to surface. Ideally it would be first thing you find when searching for how to upgrade a Redash instance.

**Comment by sankalp7654** [comment]
I am facing the same issue.

`[2022-01-12 19:10:35,977][PID:59][ERROR][redash.app] Exception on /api/organization/status [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column dashboards.options does not exist
LINE 2: ...rds_is_draft, dashboards.tags AS dashboards_tags, dashboards...`

I see, we need to run` docker-compose run --rm server manage db upgrade` command for db upgrade, but I have installed Redash using the Helm Chart https://github.com/getredash/contrib-helm-chart

I am unable to figure out where and what command I need to run in order to migrate the Database.

```
NAME                                          READY   STATUS    RESTARTS   AGE
pod/redash-5c4fd8f4fb-sk69z                   1/1     Running   0          12h
pod/redash-adhocworker-7975579fc4-5lcjf       1/1     Running   0          12h
pod/redash-redis-master-0                     1/1     Running   0          12h
pod/redash-scheduledworker-5c5d6c8b5d-7mp2m   1/1     Running   1          12h

NAME                            TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
service/redash                  NodePort    172.20.138.1     <none>        80:32555/TCP   12h
service/redash-redis-headless   ClusterIP   None             <none>        6379/TCP       12h
service/redash-redis-master     ClusterIP   172.20.103.254   <none>        6379/TCP       12h

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/redash                   1/1     1            1           12h
deployment.apps/redash-adhocworker       1/1     1            1           12h
deployment.apps/redash-scheduledworker   1/1     1            1           12h

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/redash-5c4fd8f4fb                   1         1         1       12h
replicaset.apps/redash-adhocworker-7975579fc4       1         1         1       12h
replicaset.apps/redash-scheduledworker-5c5d6c8b5d   1         1         1       12h

NAME                                   READY   AGE
statefulset.apps/redash-redis-master   1/1     12h
```
