### ISSUE TITLE
Wrong package.json for version 10

### ISSUE THREAD

**Issue by dgomezleon** [getredash/redash#5630]
[Tarball for version 10](https://github.com/getredash/redash/archive/refs/tags/v10.0.0.tar.gz) contains an old version of package.json that uses nodejs 12 and npm.

Will you be releasing a new version fixing it soon?

**Comment by loneil** [comment]
Yeah I too had noticed that if I get 9 from the main branch I can start it up with Node 14.x installed, but when getting version 10 from the release branch it will error on `yarn start` until I switch back to Node 12

![image](https://user-images.githubusercontent.com/17445138/138179755-5bb97bd5-d071-45e0-a44c-c2cfec66e637.png)

**Comment by susodapop** [comment]
Good catch. Will prioritise fixing this.

**Comment by loneil** [comment]
Ah, I see, thanks very much for the explanation.
