### ISSUE TITLE
Docker Images could not work on arm64

### ISSUE THREAD

**Issue by smdmts** [getredash/redash#5635]
### Issue Summary

Currently Redash's docker images are build on default CPU Architecture as x86_64.
https://github.com/getredash/redash/blob/master/.circleci/docker_build

In AWS, latest almost EC2's instance types are arm64 architecture. e.f. C6, M6(except M6i)
Therefore, it could not work on arm64 instance types and use buildx docker's option if respond in this case.

https://docs.docker.com/buildx/working-with-buildx/

```
docker logs foo
standard_init_linux.go:228: exec user process caused: exec format error
```

### Steps to Reproduce

1. Use arm64 Instance types.

### Technical details:

* Redash Version: redash:10.0.0.b50363

**Comment by zhengr** [comment]
Check this:  https://github.com/getredash/redash/pull/5638

**Comment by guidopetri** [comment]
#5765
