### ISSUE TITLE
lastSelectedDataSourceId always reverts to alphabetically first data source

### ISSUE THREAD

**Issue by deed02392** [getredash/redash#5646]
### Issue Summary

Despite the localstorage get `lastSelectedDataSourceId` visibly updating when selecting a different data source, it is subsequently reverted to the ID of the first data source in alphabetical order.

### Steps to Reproduce

1. Create a new query
2. Change to an alternative data source that is NOT alphabetically first
3. Observe `lastSelectedDataSourceId` updates in localstorage
4. Refresh or reload the new query page
5. Observe that `lastSelectedDataSourceId` reverts to the ID of the first alphabetically listed data source

### Technical details:

* Redash Version: 10.0.0-beta (92e5d78d)
* Browser/OS: Chrome macOS
* How did you install Redash: Docker

**Comment by sjwmoveon** [comment]
This issue is also present in the 10.0.0 release b50363 in Firefox on macOS, with a Docker installation.

**Comment by ProkhorovAlexander** [comment]
experiencing exactly the same issue on chrome macos with docker installation
