### ISSUE TITLE
query does not run with too much characters

### ISSUE THREAD

**Issue by marceltn** [getredash/redash#5663]
### Issue Summary

When I try a query more than 1436 characters (spaces included), the query tries to run but the result are blank.

### Steps to Reproduce

1. put any query and add any characters in comments (will be easier than entire SQL) to fill with more than 1436 characters
2. try run the query to check the results (the results will be blank)
3. only remove some characters to be <= 1436 in total
4. try run the query again and the results will come.

follow some screen shots. with `X` at the end of my query has 1437 characters. then I remove the `X` and the query returns data.
![Screenshot_20211202_182425](https://user-images.githubusercontent.com/3443711/144505672-f6dea1f8-e355-4f45-82be-39711b08c3fa.png)
![Screenshot_20211202_182727](https://user-images.githubusercontent.com/3443711/144505806-9175e61f-7fcc-4c15-9069-391e9ae325f1.png)

When i get the same query and execute into another SQL client (in my case, DBeaver or Azure Data Studio) works fine.

### Technical details:

* Redash Version: 10.0.0-beta
* Browser/OS: Brave (V1.32.113) / Manjaro (kernel 5.13.19-2)
* How did you install Redash: self-hosted

**Comment by guidopetri** [comment]
@marceltn sorry, I'm unable to reproduce this - I have queries running with 2750+ characters and they work fine. Could you share more details? What data source are you using? Is this still present on the latest version of redash (`preview` image on dockerhub)? Are you able to share a specific data source (maybe a public one) where this error occurs? Are there any errors in the container logs?
