### ISSUE TITLE
Detect when AdBlock running and ask the user to disable it

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#57]
AdBlock has false alarms on some of the AJAX calls re:dash makes (for example when a dashboard slug begins with "advertising-"). We need to detect if AdBlock runs and show a warning to the user.

**Comment by clarkbw** [comment]
What do you think about using the following solution for this? [code](https://github.com/codepo8/detecting-adblock/blob/master/index.html) via [blog](https://www.christianheilmann.com/2015/12/25/detecting-adblock-without-an-extra-http-overhead/)  I'll need to do some testing that this approach still works with most adblockers.

```js
(function(){
  var test = document.createElement('div');
  test.innerHTML = '&nbsp;';
  test.className = 'adsbox';
  document.body.appendChild(test);
  window.setTimeout(function() {
    if (test.offsetHeight === 0) {
      document.body.classList.add('adblock');
    }
    test.remove();
  }, 100);
```

I was thinking that somewhere in the navbar, `navbar-right`, the test element displays if you have adblock enabled otherwise remains hidden.  This code should all be async and on a timeout so it doesn't block anything.

What do you think about this approach?

**Comment by arikfr** [comment]
If it works, sounds good to me. Need to figure out how to display the message to the user without annoying him. :) But maybe a warning icon in the navbar that when clicked will explain that you he disable AdBlock.

I only wonder if we should allow the user to dismiss the message without disabling adblock? And if we do, how to store this setting?

**Comment by clarkbw** [comment]
> If it works, sounds good to me. Need to figure out how to display the message to the user without annoying him. :) But maybe a warning icon in the navbar that when clicked will explain that you he disable AdBlock.

Do you think a popup or other page is the right solution here?  I don't know what the most consistent system would be here.

> I only wonder if we should allow the user to dismiss the message without disabling adblock? And if we do, how to store this setting?

I was wondering this as well.  If we did some kind of icon with a popup and allowed people to ignore it I think we'd need to save that either in cookies or profile db.

**Comment by arikfr** [comment]
> Do you think a popup or other page is the right solution here? I don't know what the most consistent system would be here.

Popup seemed right to me as you want to explain to the user what's the problem but not take too much screen real estate for it. Also thought about the fact that the user might fix/dismiss it on one browser but have it again in another.

Considering that it's a non issue for most, how about we show a small message in the footer when we detect ad blocking:

> ⚠️ You seem to have ad blocking extension enabled. ❔ 

And when you hover the _?_ it will show a bubble with explanation?

**Comment by clarkbw** [comment]
> Considering that it's a non issue for most, how about we show a small message in the footer when we detect ad blocking:

Sounds good.

**Comment by clarkbw** [comment]
Having trouble getting started with Vagrant on the Mac.  Spent too much time there, will have to come back to this later.  Let me know if there are updated docs somewhere.

**Comment by arikfr** [comment]
Sorry for the issues you had w/ the Vagrant box, I opened #1480 to track the work on the dev guide.

**Comment by arikfr** [comment]
@clarkbw The developer guide has been updated along with new documentation on how to use Docker for easy setup of your dev environment (instead of Vagrant).

https://redash.io/help-onpremise/dev/guide.html

Also, once Mozilla will have recent version of Redash deployed on s.t.m.o, you will be able to use it instead of running things locally: https://redash.io/help-onpremise/dev/remote-server.html (while only having frontend stuff run locally).

**Comment by eradman** [comment]
This issue is old, and almost certainly the world of Ad-blocking has evolved. Closing, but we can re-evaluate if any user starts a ticket with current examples of this problem.

**Comment by justinclift** [comment]
Yep, sounds like a decent plan. :smile:
