### ISSUE TITLE
Redash queries fail when working on small tables(~In KB) in BQ

### ISSUE THREAD

**Issue by ektagrover** [getredash/redash#5704]
### Issue Summary

Redash is browser seems to be executing a query for a very long time when running on small BQ tables (in KB's). This however never happens with Big tables (in MB/GB's) - is this a known issue . Plz note that the same queries(over small tables) will go through if directly triggered over BQ console

We filed a ticket to BQ support and here was their explanation. 

 BigQuery doesn't work well with large numbers of tiny queries, which I think is the root issue here. It is not a database product, but a large data warehouse that feels best with large amount of data and analytical queries. It is specifically documented below

 https://cloud.google.com/bigquery/docs/best-practices-performance-patterns#dml_statements_that_update_or_insert_single_rows 

Also attached is a screenshot of the tables. 

![Screenshot 2022-02-11 at 3 41 19 PM](https://user-images.githubusercontent.com/86303568/153573510-b6ec9a31-ebea-4944-a554-abe969e1a4da.png)

### Steps to Reproduce

Trigger a redash query over a table which has ~250 KB of data.

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by susodapop** [comment]
Sorry to only now see this. 

When you say the queries "fail", do you receive a specific error from Redash? Or do they just take a long time before eventually returning data?

**Comment by guidopetri** [comment]
@ektagrover hey, have you got time to answer susodapop's questions above? Could you also post an example query (maybe with column names redacted for privacy)?
