### ISSUE TITLE
Mysql datasource get an error: Commands out of sync; you can't run this command now

### ISSUE THREAD

**Issue by zhongshaoming1** [getredash/redash#5705]
### Issue Summary

When I use MySQL data source and MySQL database version is MySQL 8(Other versions are not tested), the following error occurs when there is a semicolon concatenation in a query and there are dependencies in the query:
Commands out of sync; you can't run this command now
#

### Steps to Reproduce

1. Add a MySQL 8 data source
2. Write a query based on MySQL8 data source, query contains multiple SQL, multiple SQL dependencies
3. Execute the query

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: v10.1.0
* Browser/OS:Chrome/Centos7
* How did you install Redash: Docker-compose

**Comment by susodapop** [comment]
There's not enough information here to reproduce the issue. What I tried:

1. Connect to mysql 8.0.29
2. Execute this query: `select 1; select 2; select 3;`
3. Outcome: success
