### ISSUE TITLE
Is there a way to fetch all the currently running queries in redash?

### ISSUE THREAD

**Issue by KavyaSaxena** [getredash/redash#5706]
We use GitHub only for bug reports 🐛

Anything else should be posted to https://discuss.redash.io 👫

🚨For support, help & questions use https://discuss.redash.io/c/support
💡For feature requests & ideas use https://discuss.redash.io/c/feature-requests

Alternatively, check out these resources below. Thanks! 😁.

- [Forum](https://disucss.redash.io)
- [Knowledge Base](https://redash.io/help)

**Comment by KavyaSaxena** [comment]
I would like to get all the running queries and when were they last refresed.

**Comment by Garrysofa** [comment]
从redis rq jobs队列中可以看到所有任务和执行时间

**Comment by susodapop** [comment]
This data comes from Redis. The easiest way to see it is from `/admin/queries/jobs#queries`. There's no way to query this with SQL right now because there isn't a 1-to-1 relationship between query execution jobs and query_ids.
