### ISSUE TITLE
Could not edit or show the source again when i save gramatically mistaked SQL source

### ISSUE THREAD

**Issue by NodaYoko** [getredash/redash#5721]
### Issue Summary
if save gramatically mistaked SQL source, could not edit or  show the source again.

browser:Chrome
OS:Windows 10 Ver.21H2

### Steps to Reproduce

1. create a grammatically mistaked SQL,and save on the redash,like
```
~~
AND T_SOME.CLIENT_ID NOT IN ('099999',
000247',
100021')
ORDER BY T_SOME.CREATE_DATE DESC
```

2. reopen this query,any SQL Source was not shown.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

1.Other query shows SQL source normally.
2.in Developer console, some error information was shown.

> react-dom.production.min.js:198 Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
> ~
> verror-handler.js:19 [Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?i…]

### Technical details:

* Redash Version:
Version: 8.0.0+b32245 (a16f551e)

* Browser/OS:
browser:Chrome
OS:Windows 10 Ver.21H2

* How did you install Redash:

**Comment by susodapop** [comment]
Agree this appears to be a bug. But I'm not able to reproduce it in V10. See [here](https://redash-preview.netlify.app/queries/495/source). If it's not present in the latest version I would recommend upgrading as we won't patch this in the previous version.

To fix the case with your current query I'd recommend manually adjusting the query text by connecting to Redash's metadata database directly. This way you can correct the query text and continue editing in V8 as needed without data loss.
