### ISSUE TITLE
500 http status code when using SAML dynamic 

### ISSUE THREAD

**Issue by ashish1099** [getredash/redash#5728]
### Issue Summary

I have setup the SAML dynamic with our internal keycloak server. It works fine but sometime the request ends up with 500.
As soon as I click on the "SAML Login" it hits this url `https://redash.local/saml/login?next=%2F'` and later dies with 502

I'm not sure why this is happening, but I can say that the request never reaches my keycloak

```
curl 'https://redash.local/saml/login?next=%2F' \
  -H 'authority: redash.local' \
  -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'cache-control: no-cache' \
  -H 'cookie: csrf_token=g37S1y0dp4; session=eyabeJbw' \
  -H 'dnt: 1' \
  -H 'pragma: no-cache' \
  -H 'referer: https://redash.local/login?next=https%3A%2F%2Fredash.local%2F' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Linux"' \
  -H 'sec-fetch-dest: document' \
  -H 'sec-fetch-mode: navigate' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-user: ?1' \
  -H 'upgrade-insecure-requests: 1' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36' \
  --compressed
```

redash logs

```
[2022-04-05 06:08:15,486][PID:816][INFO][metrics] method=GET path=/saml/login endpoint=saml_auth_sp_initiated status=500 content_type=? content_length=-1 duration=30244.41 query_count=1 query_duration=0.96
```

in debug mode
```
[2022-04-05 10:12:10,682][PID:10][DEBUG][root] Current organization: default (1) (slug: default)
[2022-04-05 10:12:10,688][PID:10][DEBUG][saml2.httpbase] GET to https://keycloak.local/auth/realms/master/protocol/saml/descriptor
[2022-04-05 10:12:10,691][PID:10][DEBUG][urllib3.connectionpool] Starting new HTTPS connection (1): keycloak.local:443
```
### Steps to Reproduce

1. simply install the redash via helm
2. setup the keycloak saml client
3. hit "SAML login" on the login page.

### Technical details:

* Redash Version: 10.1.0.b50633 (docker tag)
* Browser/OS:  100.0.4896.60 (Google Chrome)
* How did you install Redash: (helm + argocd)

**Comment by smartysam9821** [comment]
hi, how did you solve this problem? I am having same issue.

**Comment by ashish1099** [comment]
The issue was with AWS load balancer which was set to classic and moving it to network load balancer helped in this.
It sound odd but thats what worked for us

**Comment by arikfr** [comment]
This is not related to the issue, but I assume that the issue author or followers might have SAML enabled for their deployment and should be aware of the following Security Advisory: https://github.com/getredash/redash/discussions/5961. This affects *all* Redash versions and should be patched immediately.
