### ISSUE TITLE
MySQL INFORMATION_SCHEMA tables are not ignored

### ISSUE THREAD

**Issue by jsvisa** [getredash/redash#5754]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

MySQL INFORMATION_SCHEMA tables are not ignored in schemas:

<img width="303" alt="image" src="https://user-images.githubusercontent.com/3627395/168710764-79e330a5-9121-46e8-8d22-c0464c50b166.png">

 
Seems to be the problem here,

https://github.com/getredash/redash/blob/46ea3b1f0b263ba310de7c2c17e4a32d3ea4c343/redash/query_runner/mysql.py#L125-L133

MySQL uses uppercase `INFORMATION_SCHEMA`, but filtering by lowercase `information_schema` here

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: v10.1.0
* Browser/OS: Chrome
* How did you install Redash: docker-compose

**Comment by susodapop** [comment]
> MySQL uses uppercase INFORMATION_SCHEMA, but filtering by lowercase information_schema here

mysql is not case-sensitive by default. 

Furthermore I'm not able to reproduce this on mysql:latest or on mariadb:latest. If you continue to experience issues here please open a discussion thread on our [user forum](discuss.redash.io). This appears to be something unique to your environment and not a bug in the Redash code.
