### ISSUE TITLE
Redash no longer remembers the last datasource I used when creating a query

### ISSUE THREAD

**Issue by jdavidheiser** [getredash/redash#5757]
### Issue Summary

In previous versions of Redash, the UI remembered what data source I selected the last time I created a query. Now, it defaults to the first data source every time I create a new query. I was able to replicate this in both Firefox and Chrome.
### Steps to Reproduce

1. Create a query.
2. Save or run the query, or do nothing at all.
3. Navigate anywhere else
4. Create a query again - it will be back to the first data source in the list.

### Technical details:

* Redash Version: 10.1.0.b50633
* Browser/OS: Chrome and Firefox on Mac OS Monterey
* How did you install Redash: From the Docker image, running in Kubernetes

**Comment by ilgwonPark2** [comment]
As it migrates to v10.x, UI code missed this feature. 
I changed UI code for this

**Comment by susodapop** [comment]
@ilgwonPark2 can you share your change here? I'm happy to merge this back into `master`.

**Comment by ilgwonPark2** [comment]
@susodapop sure, I will leave PR in a week.
Code change is nothing, but after finishing my work 🤣

**Comment by ilgwonPark2** [comment]
@susodapop, could you give me a write access for pushing and PR?
Or, please let me know another approach to push my change

**Comment by susodapop** [comment]
Awesome! The way to open a PR is to fork the repository, create new a branch on your fork off of `master`, make your changes, and then open a pull request from your fork back to the main repo.

Github will prompt you anytime you a push a new branch to your fork: "do you want to create a new pull request?" You'll click that prompt and follow the instructions. 

Ping me if you have any trouble with it.

**Comment by ilgwonPark2** [comment]
Thanks for kind explanation :) 
here is the PR for this issue
https://github.com/getredash/redash/pull/5785

**Comment by konnectr** [comment]
https://github.com/getredash/redash/pull/6181

**Comment by jdavidheiser** [comment]
Thank you for the fix! We have noticed that the Redash project hasn't had a release in a pretty long time, which means the official docker images at https://hub.docker.com/r/redash/redash/tags aren't really being released. I know a preview image was pushed for the Databricks outage last month, but I was wondering if there are plans to put out an official release with this new fix in it.

**Comment by justinclift** [comment]
Yeah, we're working through a backlog of fixing outdated dependencies and similar, because there are security alerts on some of the one's we're still using.

Pretty much the same second that's done we'll be releasing an updated image.  Probably going to be at least a few weeks away though.  We've done most of the easy things, and now we're into the more challenging pieces. :smile:
