### ISSUE TITLE
Error in mongodb query

### ISSUE THREAD

**Issue by namepunk** [getredash/redash#5768]
i have redash instance v8 and moving queries to new redash instance v10
my query is 
```
{ 
	"collection": "statistics",
	"query": {
		"failureCauses": {"$exists": false},
		"startingTime": {"$gt" : {"$humanTime": "{{ start }}"}, "$lt" : {"$humanTime": "{{ end }}"}},
		"result" : "FAILURE",
		"projectName": "{{ project }}"
	},
	"fields": {
		"projectName": 1,
		"buildNumber": 2,
		"slaveHostName": 3,
		"startingTime": 4,
		"link": {
        "$concat": ["https://jenkins.example.com/job/", "$projectName", "/", {"$toString": "$buildNumber"}]
     }
	},
	"sort": [{
		"name": "startingTime",
		"direction": -1
	}]
}
```
in redash v8 this query works fine, but in redash v10 i receive error
Error running query: '<' not supported between instances of 'dict' and 'int'
error in sorting fields. When i remove "link" field - no error, and when i remove all fields besides "link" - again no error

**Comment by masayuki038** [comment]
@namepunk @ChrisMagnuson Thanks for your report. Reproduced.

```
Traceback (most recent call last):
  File "/app/redash/tasks/queries/execution.py", line 182, in run
    data, error = query_runner.run_query(annotated_query, self.user)
  File "/app/redash/query_runner/mongodb.py", line 338, in run_query
    for k in sorted(f, key=f.get):
TypeError: '<' not supported between instances of 'dict' and 'int'
```

If you set a non-numeric to the value of the `fields` dict, this error will occur. This seems to be a bug.

**Comment by justinclift** [comment]
@masayuki038 Any idea if this still happens with MongoDB?

**Comment by masayuki038** [comment]
@justinclift Please let me check this week.

**Comment by justinclift** [comment]
Of course.  Thank you. :smile:

**Comment by masayuki038** [comment]
I confirmed that this still happens on master 😢
Will consider how to fix this...

**Comment by masayuki038** [comment]
@justinclift I created the PR for this. Could you check it if you have some time? Thanks always.

**Comment by justinclift** [comment]
Looks good to me, so merged it.

Thanks for getting this done @masayuki038. :smile:
