### ISSUE TITLE
LIMIT 1000 causes sql server data source query to throw error.

### ISSUE THREAD

**Issue by chriseaton** [getredash/redash#5773]
### Issue Summary
Docker deployment - pretty straightforward, in the queries editor, with the "LIMIT 1000" checkbox checked, a Microsoft SQL Server-based query throws an error (maybe because MSSQL doesn't use "LIMIT", it uses "TOP"?). Unchecking the box prevents the issue but of course doesn't limit the results.

### Steps to Reproduce

1. Add a MSSQL connector data source.
2. Make a simple select query with the checkbox checked.
3. Execute, notice the error:
    ![image](https://user-images.githubusercontent.com/5247568/174679721-efe65ee9-0ca1-4179-9eaf-48dd4306517d.png)

Unchecking the checkbox runs the query fine.

My expectation would be that if that LIMIT 1000 checkbox is shown - would be that it would limit the result-set on any supported connector data source.

### Technical details:

* Redash Version: 10.1.0
* Browser/OS: Docker/Linux
* How did you install Redash: Modified setup script.

**Comment by susodapop** [comment]
Thanks for this report. It looks like autolimit has not been implemented for this query runner, but by default Redash assumes it's supported for any query runner that inherits `BaseSQLQueryRunner`. I've opened #5777 explicit mark this feature as not enabled for this query runner.

We'll rely on someone else in the community to properly implement auto-limit for this query runner. I'm happy to provide pointers on how to do this if needed.
