### ISSUE TITLE
Dashboard list not scrollable

### ISSUE THREAD

**Issue by jcox92** [getredash/redash#578]
My team has quite a few dashboards (~40-50) and the ones later in the alphabet aren't visible in the dashboard list because the list can't be scrolled.

This is occurring on OS X in both Chrome and Firefox.

![scrollable](https://cloud.githubusercontent.com/assets/844493/10164045/1381735c-6685-11e5-8770-6d2c90891130.gif)

**Comment by arikfr** [comment]
There is an undocumented feature of dashboards grouping. For example, if you rename all your "Feed Engagement - *" dashboards into "Feed Enagement: *" (i.e. "Feed Engagement - Top 5" -> "Feed Engagement: Top 5"), you will notice that they get grouped in a "folder" (named "Feed Engagement") in the dashboards menu.

Of course we still need to solve the long list issue, but in your case, I guess it will solve the problem.

**Comment by jcox92** [comment]
Thanks @arikfr! That's helpful!

**Comment by alonho** [comment]
There's a conflict between submenu and scroll.. they just don't go together.

**Comment by arikfr** [comment]
@alonho ack. Let's keep this open and just revisit when we do the top menu.

**Comment by zlu** [comment]
We have several hundred dashboards that are grouped already.  Unable to scroll them is causing an operational headache.  Any update on why this is happening?

**Comment by rohanpd** [comment]
+1
This is starting to become a problem for us as well. Our dashboards are already grouped.

I don't think that the dropdown needs to display all dashboards but being able to click through and see the full list (like you can for queries) would be useful.

**Comment by PGuiv** [comment]
I think I found a fix for that issue, using bootstrap3:

Adding "pre-scrollable" to the ul element class fixed it for me.
```
<ul class="dropdown-menu pre-scrollable" dropdown-menu="">
...
```

I only tested it on Chrome, though, since this is what my whole team uses. So, not sure how it will react on other browsers.

**Comment by WesleyBatista** [comment]
@PGuiv, If you have chance to do it, would be good to test with submenus. 
I tried [forking](http://www.bootply.com/mzZvWwPoKG#) a demo of a html code using the **dropdown-submenu pre-scrollable** classes and putting a submenu inside a `li`, and it did not worked :disappointed:

**Comment by PGuiv** [comment]
@WesleyBatista That worked when I tried on http://demo.redash.io/.

I edited the HTML to add more subsections under the Examples link in the dashboard menu, to have enough links to scroll.

Then, I added pre-scrollable to the Examples ul HTML tag:
```
<ul class="dropdown-menu pre-scrollable">
```

Here are two screenshots to illustrate it:
![screen shot 2016-09-29 at 9 31 49 am](https://cloud.githubusercontent.com/assets/3973133/18956080/1db666a2-8628-11e6-99b8-0ce8ab24748a.png)
![screen shot 2016-09-29 at 9 34 29 am](https://cloud.githubusercontent.com/assets/3973133/18956135/5282666a-8628-11e6-9fe1-732f03b7e016.png)

**Comment by arikfr** [comment]
@PGuiv I added the `pre-scrollable` class to the menu and it scrolls, but the sub menus don't open. In your example it seems that you added the class to the sub menu. Have you tried applying it to the main one and seeing what happens?

**Comment by arikfr** [comment]
Oh, I found out what happens - it applies something to the scrolling both vertically and horizontally. so the sub menu opens but you need to scroll to see it...

**Comment by arikfr** [comment]
Will be addressed by #1393.

**Comment by atharvai** [comment]
#1393 is closed. Which version is this implemented in?

**Comment by arikfr** [comment]
@atharvai v1.0 - soon to be released.

**Comment by arikfr** [comment]
[v1.0.1](https://github.com/getredash/redash/releases/tag/v1.0.1) was finally released.
