### ISSUE TITLE
The latest Preview Docker image(f0a390b1) has bug with MySQL query runner that returns unicode characters

### ISSUE THREAD

**Issue by myonlylonely** [getredash/redash#5789]
### Issue Summary

The latest Docker Image(Preview, DIGEST: 0c128bc42044) has a bug when the query result contains non-English characters. This bug does not exist in the previous Docker preview Images.

<img width="607" alt="image" src="https://user-images.githubusercontent.com/8188177/178133240-d8753dbc-e039-4256-92da-be2066546369.png">

### Steps to Reproduce

1. connect to a MySQL database, write a query that the result contains non-English characters.
2. It returns with error: `Error running query: 'Result' object has no attribute 'json_data'`.
3. When write a query that returns all English characters, it returns the result correctly. 

This bug doesn't exist in the previous Docker preview images, and I setup a local non-Docker developer environment, it doesn't occur. So I guess it could be an issue with the dependency update with the Docker Image only?

### Technical details:

* Redash Version: 11.0.0-dev (f0a390b1) 
* Browser/OS: Chrome 103 / MacOS 12.4
* How did you install Redash: Docker

**Comment by susodapop** [comment]
Why did you close? Is this resolved?

**Comment by myonlylonely** [comment]
Sorry, it is not a Redash related issue, the newest MySQL query runner code has some conflicts with my own modification to the MySQL query runner. The official Docker image has no problem.
