### ISSUE TITLE
Add user permissions support

### ISSUE THREAD

**Issue by joaofraga** [getredash/redash#580]
I think user permission would be a great feature.  In our company, we use Redash to put all queries in one place. We're using because we had many users with SQL access and making different queries to the sam purpose with different results.

We want to have only a few users with permissions to create queries and the rest read-only.

I think firstly can be created the following permissions:
- Only administrators can create / edit queries.
- By query, the administrator can revoke any other admin users to edit  his query. I think with a checkbox like: "Only me can edit this query".

What do you think?

**Comment by arikfr** [comment]
Actually re:dash already has support for permissions, but it's not exposed with a user interface.

Each user belongs to a group, and each group has its own set of permissions. By default there are two groups: `admin` and `default`. `default` group has the following permissions: create_dashboard, create_query, edit_dashboard, edit_query, view_query, view_source, execute_query, list_users.

To support the use case you suggest, you can change the default group, and remove the "create_query" and "edit_query" permissions from it. Creating a 3rd group ("power users"?), that has those permissions and apply it only to the users you want. This way, you have a limited set of users who can create and edit queries, but they are not admins.

To edit the groups, create new ones and more you can browse to `/admin/group`. Problem is that currently there is no interface to assign a group to a user, but you can do that by manipulating the database directly... :-\ The API supports updating groups (that's how the "admin" checkbox works), but need to add an interface for it.

**Comment by br1985** [comment]
How about "object-level" permissions? E.g. per data source, per dashboard, per query...?

Here's our use case: We'd like to allow one group of people ("analytics") to create and edit queries or dashboards. Then we'd like them to be able to share their queries and dashboards with some other groups of people ("sales", "hr"...). We want to grant "sales" and "hr" only read-only access and we don't want "sales" to be able to access reports created for "hr".

Is there any way to achive that other than running multiple instances of redash?

**Comment by arikfr** [comment]
@br1985 object-level permission is planned as well, exactly for the use cases you describe.

**Comment by br1985** [comment]
Great! Thank you for update.

**Comment by simzen85** [comment]
@arikfr we're using redash and really looking forward to object-level permission.

My question is that if we want to implement a quick hack (something like specifying the user account and the boards they can view right before the board is rendered) then where can I start ? Thanks.

**Comment by toyama0919** [comment]
Hello.
I also have a problem.

I use group, dev and operation and default and admin.
Checkbox is admin only with Edit user action.

I want all group checkbox can edit.

**Comment by arikfr** [comment]
@toyama0919 once #636 is merged, you will have UI to edit groups.
