### ISSUE TITLE
Docker installation of Redash latest on macOS 

### ISSUE THREAD

**Issue by tasmaniski** [getredash/redash#5815]
### Broken Docker installation for Redash latest version 

I try to set up Redash on my local macOS Monterey. 
I am following the instructions from the website documentation: https://redash.io/help/open-source/dev-guide/docker  
But constantly getting the error for step 6. 

### Steps to Reproduce

I am following the steps: 
1. git clone https://github.com/getredash/redash.git
2. cd redash/
3. touch .env (insert content: REDASH_COOKIE_SECRET=test)
4. docker-compose up -d
5. yarn --frozen-lockfile

So far everything was installed correctly.  
But on the following command I am constantly getting the error: 

6. docker-compose run --rm server create_db
```
Creating redash_server_run ... done
Traceback (most recent call last):
  File "/app/manage.py", line 6, in <module>
    from redash.cli import manager
  File "/app/redash/__init__.py", line 15, in <module>
    from .query_runner import import_query_runners
  File "/app/redash/query_runner/__init__.py", line 16, in <module>
    from redash.utils.requests_session import requests_or_advocate, requests_session, UnacceptableAddressException
  File "/app/redash/utils/requests_session.py", line 3, in <module>
    from advocate.exceptions import UnacceptableAddressException
ModuleNotFoundError: No module named 'advocate'
ERROR: 1
```
### Technical details:

* Redash Version: latest from master branch 
* Environment: Terminal
* Node: v14.16.1
* Docker: v20.10.17

**Comment by tasmaniski** [comment]
Small update, actually the problem is at step: 
`docker-compose up -d`

The 'advocate' is not installed for some reasons, although I can see in  the ./requirements.txt file
`advocate==1.0.0`

**Comment by susodapop** [comment]
Very peculiar. I'm not able to reproduce this locally. What happens if you run `docker-compose build`?

**Comment by tasmaniski** [comment]
Thank you for the replay. 
Right now I first remove everything from the docker, images, and containers. 
Run installation again, and it works now.
