### ISSUE TITLE
Enable a drill-down path with parametrized queries

### ISSUE THREAD

**Issue by arthurpsmith** [getredash/redash#582]
Now that re:dash supports queries with parameters it seems logical to allow a way to link the results of a top-level query to related parametrized queries. For example, say I have a query to fetch a list of most downloaded pages on a site, giving a table with page, total count. I might want to link each of the counts to a second parametrized query showing the counts for that particular page by day. And then the link for a particular day might go to a table listing all the detailed download events on that day for that page, or a query showing IP addresses, etc. Basically a mechanism to drill down from a top-level table or chart to more detailed queries.

I believe there's some work going on regarding formatting options for tables, so the table piece of this at least might be a related issue: add an option in formatting a particular column of a table to link that column to another query that using one or more of the fields of that row as parameters.

**Comment by arikfr** [comment]
This is a good point. Meanwhile, you can already create those links in tables, see this as an example: http://demo.redash.io/queries/520/source#table

It's crude but will work.

**Comment by arthurpsmith** [comment]
I guess that isn't a terrible workaround - thanks...

**Comment by arikfr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tQxDwU4s&#x2F;50-configuration-for-table-visualization"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Configuration for table visualization</a>

**Comment by arikfr** [comment]
Closing in favor of #1356.

**Comment by rywager** [comment]
Need this for graphs/charts as well though.

**Comment by rywager** [comment]
Also, any clue on how to do this with Impala as a datasource?

**Comment by rywager** [comment]
Never mind: select concat('<a href="https://www.iplocation.net/?query=',cast(a.ip as string),'" target="_blank">', cast(a.ip as string), '</a>') as 'IP Link',

**Comment by rywager** [comment]
`select` concat('<a href="https://www.iplocation.net/?query=',cast(a.ip as string),'" target="_blank">', cast(a.ip as string), '</a>') as 'IP `Link',`

**Comment by dharasd03** [comment]
> 
> 
> This is a good point. Meanwhile, you can already create those links in tables, see this as an example: http://demo.redash.io/queries/520/source#table
> 
> It's crude but will work.

Could you please tell me how to do it in MongoDB.
Thanks
