### ISSUE TITLE
Update docker NGINX image to fix security issues

### ISSUE THREAD

**Issue by drAlberT** [getredash/redash#5820]
Please release a new NGINX image with version >=1.16.1

![Screenshot 2022-09-05 at 11 38 04](https://user-images.githubusercontent.com/1442700/188419074-2872aca6-dbbf-4473-b1cf-9a0397eca1a7.png)

Thanks

**Comment by guidopetri** [comment]
@drAlberT hey, thanks for pointing this out! I don't think the `redash/nginx` image is maintained anymore, so you should probably use a standard `nginx` image instead.
