### ISSUE TITLE
discuss.redash.io is NXDOMAIN

### ISSUE THREAD

**Issue by lol768** [getredash/redash#5823]

**Comment by lol768** [comment]
Title describes the problem.

**Comment by flaunderg** [comment]
`; <<>> DiG 9.10.3-P4-Ubuntu <<>> discuss.redash.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 41003
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;discuss.redash.io.		IN	A

;; ANSWER SECTION:
discuss.redash.io.	300	IN	CNAME	redash1.hosted-by-discourse.com.

;; AUTHORITY SECTION:
hosted-by-discourse.com. 900	IN	SOA	ns-104.awsdns-13.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 23 msec
;; SERVER: 10.9.0.51#53(10.9.0.51)
;; WHEN: Sun Sep 11 13:31:25 EDT 2022
;; MSG SIZE  rcvd: 169`

`; <<>> DiG 9.10.3-P4-Ubuntu <<>> redash1.hosted-by-discourse.com.
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 45014
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;redash1.hosted-by-discourse.com. IN	A

;; AUTHORITY SECTION:
hosted-by-discourse.com. 900	IN	SOA	ns-104.awsdns-13.com. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 9 msec
;; SERVER: 10.9.0.51#53(10.9.0.51)
;; WHEN: Sun Sep 11 13:31:31 EDT 2022
;; MSG SIZE  rcvd: 138`

**Comment by lol768** [comment]
For me:

```
; <<>> DiG 9.16.1-Ubuntu <<>> discuss.redash.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 21668
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;discuss.redash.io.		IN	A

;; Query time: 43 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Sun Sep 11 18:42:12 BST 2022
;; MSG SIZE  rcvd: 46
```

Possibly a recent change and still cached my side?

**Comment by flaunderg** [comment]
No, it's a global issue.
Seems like discourse dropped the CNAME for redash1.hosted-by-discourse.com, so discuss.redash.io is pointing no where.

**Comment by lol768** [comment]
```
$ dig discuss.redash.io +short 
redash1.hosted-by-discourse.com.
184.105.176.47
```
