### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__module__'

### ISSUE THREAD

**Issue by jis0324** [getredash/redash#5827]
### Issue Summary

The project was built as well, but when I visit on the browser (localhost:8080), then I got this error.
```AttributeError: 'NoneType' object has no attribute '__module__'```
I am on Ubuntu 20, and ran as `docker-compose up ---build`

### Steps to Reproduce

This is the first step

### Technical details:

* Redash Version: latest current version
* Browser/OS: Firefox / Ubuntu 20
* How did you install Redash: docker-compose up --build

**Comment by techrajdeep** [comment]
Hey @jis0324  , I am looking for an issue for my first contribution . Can you help me here.

**Comment by guidopetri** [comment]
@jis0324 hey, could you provide some more details? How exactly did you deploy redash (did you clone it? did you use the setup repo? did you add it to your docker compose manually?)? What version of Redash are you using? Could you post the full error logs from the docker containers?
