### ISSUE TITLE
How can I start Redash?

### ISSUE THREAD

**Issue by hexiaoting** [getredash/redash#5834]
I try to setup redash but failed.
I download the source code and follow this page: https://redash.io/help/open-source/dev-guide/setup to setup.
And I start the following service on CentOS 7:
* postgres on port 5432
* redis on port 6379
* redash webserver on port 5000
* redash rq work
* redash rq scheduler

But When I access port 5000 on chrome it failed.:
```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
And the web server log shows:
```
  File "/mnt/disk3/hewenting/redash_env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 580, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "organizations" does not exist
LINE 2: FROM organizations
```
What should I do next?  create a table called organizations???  
I want to use the dashboard on redash .

my environment:
```
[he@dell125 redash_env]$ ps aux |grep manage.py
hewenti+ 102279  0.1  0.0 431292 116012 pts/21  S+   14:40   0:02 python ./manage.py rq scheduler
hewenti+ 105256  0.2  0.0 502216 116552 pts/12  S+   14:47   0:02 python ./manage.py runserver -h 0.0.0.0 --debugger --reload
hewenti+ 105274  3.2  0.0 951632 123624 pts/12  Sl+  14:47   0:29 /mnt/disk3/hewenting/redash_env/bin/python /mnt/disk3/hewenting/redash/manage.py runserver -h 0.0.0.0 --debugger --reload
```

**Comment by kravets-levko** [comment]
Hi! You need to create database (https://redash.io/help/open-source/dev-guide/docker):

```bash
# Create tables
docker-compose run --rm server create_db

# Create database for tests (if needed)
docker-compose run --rm postgres psql -h postgres -U postgres -c "create database tests"
```

**Comment by hexiaoting** [comment]
> Hi! You need to create database (https://redash.io/help/open-source/dev-guide/docker):
> 
> ```shell
> # Create tables
> docker-compose run --rm server create_db
> 
> # Create database for tests (if needed)
> docker-compose run --rm postgres psql -h postgres -U postgres -c "create database tests"
> ```

I do not use docker. how can I create tables use redash's commands?

**Comment by hexiaoting** [comment]
OK, that works, thank you. @kravets-levko
