### ISSUE TITLE
For Map Visualization - Bahrain is not available

### ISSUE THREAD

**Issue by piyush-rain** [getredash/redash#5839]
Looks like bahrain was not defined in `viz-lib/src/visualizations/choropleth/maps/countries.geo.json` which has resulted in missing the country from the map.

**Comment by gaecoli** [comment]
> Looks like bahrain was not defined in `viz-lib/src/visualizations/choropleth/maps/countries.geo.json` which has resulted in missing the country from the map.

You are right!

**Comment by gaecoli** [comment]
> Looks like bahrain was not defined in `viz-lib/src/visualizations/choropleth/maps/countries.geo.json` which has resulted in missing the country from the map.

{"type":"Feature","properties":{"abbrev":"B.H","name":"Bahrain","name_long":"Kingdom of Bahrain","iso_a2":"BH","iso_a3":"BHR","iso_n3":"48"},"geometry":{"type":"Polygon","coordinates":[[[50.441498315672,26.079486759594],[50.444990826448,26.155368387131],[50.494398435257,26.240297244012],[50.565645056344,26.252673936522],[50.58600454793,26.247660903832],[50.628002395199,25.943018578555],[50.610418895937,25.857704991003],[50.5840692813,25.815491188858],[50.508839915777,25.868375997347],[50.459210656002,25.954651764437],[50.441498315672,26.079486759594]]]}}

You can add this in `redash/viz-lib/src/visualizations/choropleth/maps/countries.geo.json`

**Comment by gaecoli** [comment]
@kravets-levko This PR can be merged? I found GCC area map no Bahrain. Thank you very much!

**Comment by konnectr** [comment]
@gaecoli Hi, will you create a PR? I think it's important

**Comment by gaecoli** [comment]
#6192

**Comment by gaecoli** [comment]
@justinclift

**Comment by gaecoli** [comment]
@konnectr @piyush-rain The latest version has fixed this problem, you can pull the latest code to view.

**Comment by gaecoli** [comment]
Fixed it! #5864

**Comment by justinclift** [comment]
Good job @gaecoli. :smile:
