### ISSUE TITLE
[Feature Requests] Logarithmic Scaling & Drop Down Chart Filter

### ISSUE THREAD

**Issue by brentonmallen1** [getredash/redash#584]
An option to adjust the y-axis scale to logarithmic would be very helpful.

It would also be nice if you can filter a plot in the dashboard via a selected field in a combo box and the plot would update to show only that data.  A default/initial filter might need to be selected.

Thanks for working on this stuff, it's really incredible and easy to use!

**Comment by arikfr** [comment]
About filters:

1. There is the filter and multi-filter feature: http://demo.redash.io/queries/143 and http://demo.redash.io/queries/144.

2. Also there are parameters: http://demo.redash.io/queries/146/source?p_action=create. The parameters feature is a bit crude, as it has no UI. But I'm working on it now (UI).

**Comment by victoruiz** [comment]
Hi @arikfr , what kind of interface related to query parameters are you working on? Something like a UI showing some "filter" or "search" boxes on top of the queries based on some declared search/filtering criterias?

**Comment by arikfr** [comment]
@victoruiz the basic implementation will be a text box where you can input the value for the parameter. But then I want to extend it with specific interfaces for different types of fields (like date/time picker) and drop down interface for predefined list of values.

**Comment by arikfr** [comment]
Both requests were implemented. Closing.
