### ISSUE TITLE
Sankey graph not displaying

### ISSUE THREAD

**Issue by ZeroParticle** [getredash/redash#5876]
### Issue Summary

Sankey graph (and also Sunburst) does not display. I'm creating the graph using the simple case described in PR #5286 and the result is shown below:
![image](https://user-images.githubusercontent.com/6956181/208227176-34ea0c96-e182-42f7-a21b-611da238ce19.png)

Chrome Version 108.0.5359.125 (Official Build) (64-bit) Windows
Redash Version: 10.1.0 (2589bef1)

### Steps to Reproduce
1. Create and execute the following query:
```
select '0', '1', '2', 10 as value
union
select '0', '0', '3', 5 as value
union
select '1', '3', '0', 20 as value
```
2. Create a Sankey or Sunburst graph.
3. Observe blank graph area.

The following alternative simple case also does not work:
```
with base(stage1,stage2,stage3,value) AS (
SELECT * FROM (VALUES
('a', 'b', 'c', 1),
('a', 'b', 'd', 1),
('z', 'b', 'd', 2),
('z', 'x', 'c',1),
('a', null, 'c', 17)))
SELECT * FROM base
```

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: 10.1.0 (2589bef1)
* Browser/OS: Chrome Version 108.0.5359.125 (Official Build) (64-bit) Windows
* How did you install Redash: Setup script on single host. Migrated to 10.1.0 following migration instructions.

**Comment by konnectr** [comment]
Everything works for me. Last master.

![image](https://github.com/getredash/redash/assets/46676677/168c6203-e35a-4a5d-8e3c-93b38721c3dc)

**Comment by ZeroParticle** [comment]
Upon testing again, it appears to be fixed without any changes to the Redash installation. Possible it was a browser issue.
