### ISSUE TITLE
 AttibuteError: 'EntryPoints' object has no attribute 'get'

### ISSUE THREAD

**Issue by tanamanda13** [getredash/redash#5882]
### Issue Summary

docker-compose up -d fails with  AttibuteError: 'EntryPoints' object has no attribute 'get' for scheduler and worker service.
It seems like a python package causing trouble. 

`  Traceback (most recent call last):
   Fle "./manage.py", line 9, in <module>
    manager()
   Fle "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
   Fle "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
   Fle "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
   Fle "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
   Fle "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
   Fle "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
   Fle "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
   Fle "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
   Fle "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 425, in decorator
    with __ctx.ensure_object(ScriptInfo).load_app().app_context():
   Fle "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 381, in load_app
    app = call_factory(self, self.create_app)
   Fle "/usr/local/lib/python3.7/site-packages/flask/cli.py", line 117, in call_factory
    return app_factory(script_info)
   Fle "/app/redash/cli/__init__.py", line 13, in create
    app = current_app or create_app()
   Fle "/app/redash/app.py", line 57, in create_app
    extensions.init_app(app)
   Fle "/app/redash/extensions.py", line 107, in init_app
    load_extensions(app)
   Fle "/app/redash/extensions.py", line 69, in load_extensions
    entry_point_loader("redash.extensions", extensions, logger=app.logger, app=app)
   Fle "/app/redash/extensions.py", line 30, in entry_point_loader
    for entry_point in entry_points().get(group_name, []):
 AttibuteError: 'EntryPoints' object has no attribute 'get'`

When you open the browser on http://0.0.0.0:5000/
![Capture d’écran 2023-01-13 à 16 41 04](https://user-images.githubusercontent.com/43987446/212361753-b554645e-cf8a-41b6-905d-4837842b7339.png)

### Steps to Reproduce

1. Git clone
2. Set .env 
`PYTHONUNBUFFERED=0
REDASH_HOST
REDASH_WEB_WORKERS
REDASH_RATELIMIT_ENABLED
REDASH_MAIL_SERVER
REDASH_MAIL_USE_TLS
REDASH_MAIL_PORT
REDASH_MAIL_USERNAME
REDASH_MAIL_PASSWORD
REDASH_MAIL_DEFAULT_SENDER
REDASH_COOKIE_SECRET`
4. docker-compose up 

### Technical details:

* Redash Version: 
* Browser/OS: Firefox / Mac M1
* How did you install Redash: 
   - git checkout fix-m1-build
   - docker-compose up  
* Python version : 3.11.1

Thx for your help!

**Comment by Ajith61** [comment]
How you fix this issue? I'm getting the same error.

**Comment by tanamanda13** [comment]
_As importlib-metadata released v5.0.0, it removed the deprecated endpoint. So Use the older version and do not install the latest version._
I added this version `importlib-metadata==4.13.0` in the `requirements_bundles.txt` file.
More info [here](https://stackoverflow.com/questions/73929564/entrypoints-object-has-no-attribute-get-digital-ocean)
