### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by mbrochh** [getredash/redash#5891]
255 pull requests, barely any code changes in years, no releases, twitter account inactive since 2020.

I would kindly like to know if this project still alive? If not, is there a recommended similar project that people should migrate to?

**Comment by timo-klarshift** [comment]
It is dead : https://www.reddit.com/r/dataengineering/comments/wg9m26/is_redash_dead_the_red_arrow_indicates_when/

**Comment by timo-klarshift** [comment]
https://redash.io/help/faq/eol

**Comment by susodapop** [comment]
> https://redash.io/help/faq/eol

I'm not a maintainer on this repo at the moment, but wanted to clarify that the link above refers specifically to the old Hosted Redash platform. It is not reflective of the open source project at all. I'll leave it to @arikfr to comment on the current state of the project, plans for ongoing development etc.

**Comment by bratao** [comment]
This project is in my opinion the best opensource dashboard in the market. I´m up to participate in the maintenance of a fork of redash.

**Comment by arikfr** [comment]
@lucasfcnunes instead of forking, do you want to direct this energy in helping to maintain the project? :-)

**Comment by lucasfcnunes** [comment]
> @lucasfcnunes instead of forking, do you want to direct this energy in helping to maintain the project? :-)

Yes. That's my intention.

**Comment by arikfr** [comment]
Official response on this question: https://github.com/getredash/redash/discussions/5962. Given this I'm closing this issue now. You're all welcome to continue the discussion in the announcement.
