### ISSUE TITLE
Result of cityHash64 is not right

### ISSUE THREAD

**Issue by shfei** [getredash/redash#5906]
### Issue Summary

Result of cityHash64 is not right, the http response in redash seems right, but not the output in table.

### Steps to Reproduce

1. Create redash new query, run sql `select cityHash64('585308601-share_freetime_exp') as num , num % 2`

<img width="1422" alt="image" src="https://user-images.githubusercontent.com/22709606/224654312-b8a2ec2a-b33c-485e-b1f2-7d19ca641e40.png">

And here is cli output:
<img width="888" alt="image" src="https://user-images.githubusercontent.com/22709606/224654579-68e9375f-7e34-4c2d-ae22-c460115bf472.png">

### Technical details:

* Redash Version: Version: 8.0.0+b32245 (a16f551e)
* Browser/OS: MacOS 12.5.1 (21G83)  / Chrome 111.0.5563.64
* How did you install Redash: Docker

**Comment by denisov-vlad** [comment]
@shfei it's a 64-bit integer problem.

Until it is fixed, you can use the `toString()` method in clickhouse or convert to string in the table editor:
<img width="573" alt="Снимок экрана 2023-03-14 в 10 41 03" src="https://user-images.githubusercontent.com/7091907/224929873-f95b1d50-4d9b-4423-974e-104cea735151.png">

**Comment by selfboot** [comment]
> @shfei it's a 64-bit integer problem.
> 
> Until it is fixed, you can use the `toString()` method in clickhouse or convert to string in the table editor: <img alt="Снимок экрана 2023-03-14 в 10 41 03" width="573" src="https://user-images.githubusercontent.com/7091907/224929873-f95b1d50-4d9b-4423-974e-104cea735151.png">

thanks, get it~

**Comment by konnectr** [comment]
it's not just a Clickhouse problem.  https://github.com/getredash/redash/issues/6159

**Comment by konnectr** [comment]
This is not a Clickhouse problem. https://github.com/getredash/redash/issues/6159
