### ISSUE TITLE
New Alembic breaks Redash

### ISSUE THREAD

**Issue by zachliu** [getredash/redash#5907]
### Issue Summary

See here: https://github.com/sqlalchemy/alembic/issues/1196
Alembic's new releases on March 2023 (>=1.10.x) break redash. We either need to pin Alembic's version in requirements.txt or update SQLAlchemy's version from 1.3.10 to 1.3.24

### Steps to Reproduce

1. Build the image after 03/07/2023
2. Run it locally

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by zachliu** [comment]
the server itself couldn't start because when the Alembic (>=1.10.x) tried to do this
```
from sqlalchemy.sql.naming import _NONE_NAME as _NONE_NAME
```
i got the `cannot import name '_NONE_NAME' from 'sqlalchemy.sql.naming` error

![2023-03-22_11-59](https://user-images.githubusercontent.com/14293802/226964827-36902226-6cc1-448d-a43c-cbeeb3f70a24.png)

**Comment by shuklaabhi** [comment]
Should we close this since we are now using updated version of sqlalchemy.
