### ISSUE TITLE
Redash Server Related Issue

### ISSUE THREAD

**Issue by arunbalaji04** [getredash/redash#5947]
I have tried in redash with a CSV database to read the CSV file from Google Drive as per redash help section instructions but still I am getting the error like 'Error running query: Error reading . Invalid URL '': No schema supplied. Perhaps you meant http://?'

Can anyone check on this issue?

![image](https://user-images.githubusercontent.com/125544731/228537477-cbba8718-351c-4354-a36b-9d1a1b9172d5.png)

**Comment by lucasfcnunes** [comment]
The syntax is 
```yaml
url: https://...
```

**Comment by konnectr** [comment]
For a long time there is no continuation. I'm closing the issue
