### ISSUE TITLE
Connection Test Failed: No row was found for one() - Redas Data source error

### ISSUE THREAD

**Issue by SlavchoSpasenoski** [getredash/redash#5960]
Trying to connect to Data source, (Postgres instance, also tried MySql local instance) but I have this error.

**Connection Test Failed:
No row was found for one()**

Is there any suggestions what kind of error is this?

**Comment by SlavchoSpasenoski** [comment]
I found error that it throw worker, and this is following:

![Screenshot_1](https://user-images.githubusercontent.com/28984924/229493294-a5ef44a9-8f2e-46ac-8c1b-06c01914ff65.png)

**Comment by gaecoli** [comment]
> I found error that it throw worker, and this is following:
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/28984924/229493294-a5ef44a9-8f2e-46ac-8c1b-06c01914ff65.png)

I have encountered this situation, it is likely that your worker node and server node did not read your redis address.
You have to check whether redis server is connect.

**Comment by guidopetri** [comment]
@SlavchoSpasenoski could you provide more details on your error? How did you deploy redash, and what steps could one take to reproduce the error?
