### ISSUE TITLE
There is a problem with local packaging, where can I download the official image

### ISSUE THREAD

**Issue by cverdela** [getredash/redash#5984]
We use GitHub only for bug reports 🐛

Anything else should be a discussion: https://github.com/getredash/redash/discussions/ 👫

🚨For support, help & questions use https://github.com/getredash/redash/discussions/categories/q-a
💡For feature requests & ideas use https://github.com/getredash/redash/discussions/categories/ideas

Alternatively, check out these resources below. Thanks! 😁.

- [Discussions](https://github.com/getredash/redash/discussions/)
- [Knowledge Base](https://redash.io/help)

**Comment by cverdela** [comment]
redash/redash:10.1.0.b50633 ? two years?

**Comment by justinclift** [comment]
There is a `redash/redash:preview` from about 3 weeks ago as well. :smile:

**Comment by cverdela** [comment]
Starting dev RQ worker...
/app/bin/docker-entrypoint: line 28: exec: watchmedo: not found

**Comment by cverdela** [comment]
redash-master-worker-1 and  redash-master-scheduler-1 errors

**Comment by tomtom215** [comment]
Docker image is here https://hub.docker.com/r/redash/redash

**Comment by gaecoli** [comment]
+1

**Comment by guidopetri** [comment]
@cverdela as mentioned by Justin above, the `preview` tag on dockerhub is our latest image that gets updated every time we merge to `master`. If you're having further issues with running that image, please open a new issue with more details on:
- what commands you ran to launch redash
- your docker environment (`docker ps -a`)
- any error logs
