### ISSUE TITLE
Add chart type

### ISSUE THREAD

**Issue by Avey777** [getredash/redash#5998]
There are too few icon types in Redash, I hope to add charts.

Users may not always code custom charts

**Comment by bonashen** [comment]
redash chart use `plotly.js` lib. you can choose custom type.
and enter plotly.js chart code as you like.
![image](https://user-images.githubusercontent.com/178377/236446168-910691f1-9ffb-4263-be3b-7d8454ec0023.png)

**Comment by Avey777** [comment]
> redash chart use `plotly.js` lib. you can choose custom type.
> 
> and enter plotly.js chart code as you like.
> 
> ![image](https://user-images.githubusercontent.com/178377/236446168-910691f1-9ffb-4263-be3b-7d8454ec0023.png)
> 
> 

OK thanks

**Comment by gaecoli** [comment]
#6125
