### ISSUE TITLE
Can't save draft queries without publishing them

### ISSUE THREAD

**Issue by yosefw** [getredash/redash#60]
#### Problem

Can’t save draft queries with titles. Once a query gets a title, it becomes public.
#### Solution

An explicit ‘draft’ state for queries, in which they are only visible to their authors. 
Note that re:dash is aimed at sharable data and should prevent private data silos. The UI should encourage the user to get out of ‘draft’ ASAP (maybe with a drafts quota and/or publishing drafts after a set time period).

**Comment by lab79** [comment]
Fork?

**Comment by arikfr** [comment]
Drafts are actually implemented in 1.0.
