### ISSUE TITLE
The API key for one query may be used to retrieve another query's results

### ISSUE THREAD

**Issue by iholoviy** [getredash/redash#6043]
### Issue Summary

The API key for one query may be used to retrieve another query's results

### Steps to Reproduce

1. Create one query and execute it to obtain results (call it query A)
2. Create another query and execute it to obtain different results (call it query B)
3. Get the query's API key for query A (A_API_KEY) and the query number for query A (A_QUERY_NUMBER)
4. Get the result number from query B's most recent run (B_RESULT_NUMBER)
5. Execute the below code and you'll see that the API key for query A can get results from query B
```
`REDASH_DOMAIN='yourdomain.com'
A_QUERY_NUMBER='query number for query A'
A_API_KEY_A='api key for query A'
B_RESULT_NUMBER='query result number for query b'

# this will download query B's results using query A's access key
wget \
  -O query_b_results.csv \
  "https://$REDASH_DOMAIN/api/queries/$A_QUERY_NUMBER/results/$B_RESULT_NUMBER.csv?api_key=$A_API_KEY"
```

# The same issue was reported a while ago: https://github.com/getredash/redash/issues/1979

### Technical details:

* Redash Version: 10
* Browser/OS: Chome
* How did you install Redash: via docker image

**Comment by guidopetri** [comment]
I'm unable to reproduce this error, I get the following result:

```json
{"message": "No cached result found for this query."}
```

@iholoviy are you sure you're on Redash 10? Can you try the `preview` image from Dockerhub and see if it is fixed there?

If I use the API key for B instead:

```sh
wget \
  -O query_b_results.csv \
  "https://$REDASH_DOMAIN/api/queries/$A_QUERY_NUMBER/results/$B_RESULT_NUMBER.csv?api_key=$B_API_KEY"
```

then I do get results for B, but the file is named like A's query name, which is perhaps confusing - but the above is essentially equivalent to

```sh
wget \
  -O query_b_results.csv \
  "https://$REDASH_DOMAIN/api/queries/$B_QUERY_NUMBER/results.csv?api_key=$B_API_KEY"
```

which should be allowed.
