### ISSUE TITLE
redash service restart unexpedetly and logs does not show anything 

### ISSUE THREAD

**Issue by HanumanthaRAON** [getredash/redash#6045]
### Issue Summary

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

1. This is the first step
2. This is the second step, etc.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version:
* Browser/OS:
* How did you install Redash:

**Comment by guidopetri** [comment]
Hi @HanumanthaRAON , could you provide more details? How did you install Redash exactly (which commands, or which instructions did you follow)? What logs are present in the service logs?
