### ISSUE TITLE
front-end errors using docker setup

### ISSUE THREAD

**Issue by htrgouvea** [getredash/redash#6054]
Hi folks, 
I'm trying to use redash with a docker container and some errors are happening:

Basically I tried to do the setup with the following commands:

```bash
docker-compose up -d
docker-compose run --rm server create_db
```

<img width="768" alt="Screenshot 2023-05-19 at 11 21 23" src="https://github.com/getredash/redash/assets/10741284/7695b750-c48a-4a29-ba54-10834c538961">

But the frontend looks like it wasn't set up correctly:

<img width="1437" alt="Screenshot 2023-05-19 at 11 21 40" src="https://github.com/getredash/redash/assets/10741284/44ebc8b3-45c9-4835-b802-3750182541bd">

<img width="1438" alt="Screenshot 2023-05-19 at 11 21 56" src="https://github.com/getredash/redash/assets/10741284/60803295-7eca-4c62-bfee-c87686858062">

**Comment by gabrieldutra** [comment]
Hey, I recommend following https://redash.io/help/open-source/dev-guide/docker if it's for local development, but you should also be running a Frontend loop together with the backend one. (Or at least do `yarn build` prior to Docker)

Iirc there's an arg for Docker that builds the frontend together with the docker build, but I don't remember it right now 😅
