### ISSUE TITLE
Update boto3 to support AWS EC2 IMDSv2

### ISSUE THREAD

**Issue by rodrigost23** [getredash/redash#6081]
### Issue Summary

I'm trying to use the (apparently undocumented) `ATHENA_ASSUME_ROLE` option, but Redash uses an old `boto3` version (< 1.11.0), which does not support IMDSv2: https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide//use-a-supported-sdk-version-for-imdsv2.html

### Steps to Reproduce

1. Setup an EC2 on AWS with IMDS v2-only
2. Try to use "assume role" in an Athena Data Source
3. Get a "credentials not found" error

IMDSv2 is more secure and should work when using EC2 on AWS. Upgrading boto3 to 1.12.6 would be enough.

**Comment by rodrigost23** [comment]
Apparently this has been addressed in #6207

**Comment by justinclift** [comment]
Ahhh yep.  That was a few days ago.  We're very actively updating our old dependencies presently, as well as going through the list of PRs and merging/closing things as makes sense. :smile:

**Comment by shuklaabhi** [comment]
Lets close this PR

**Comment by guidopetri** [comment]
Thanks for pointing out that this is done @shuklaabhi :)
