### ISSUE TITLE
Can't print out the data

### ISSUE THREAD

**Issue by jeff1026j** [getredash/redash#609]
Hi, I just create a new Table and import some data by mysql

but when I use re:dash, I can't print out a simple query like 

select * from Table;

but I'm sure I can get the result printed when I use mysql direct~

and all other Tables are work correctly, I can also see the Table name at the right side

where can I check ??

**Comment by arikfr** [comment]
Did you give the re:dash user permissions to read from this table?

**Comment by arikfr** [comment]
Please re-open if still relevant.
