### ISSUE TITLE
sql 执行后，循环请求后台，未正常响应

### ISSUE THREAD

**Issue by ebrx** [getredash/redash#6090]
我通过docker 部署了redash 成功启动，可以确定一下几点:
  1. 配置了数据源,数据源测试也通过。
  2.在查询页面，选择数据源后，左侧可以正常显示表结构。
  3.我启动的方式是docker run 通过环境变量链接本地的redis 和 postgres ，数据库脚本是在启动后在容器里面执行了manage.py

  问题是: 在右侧输入一个单表查询，点击执行。然后发现系统向后台循环发送请求，得不到响应。除非退出登陆才会停下。我尝试了postgres 和 mysql 数据源，都是一样的效果。哪位老师可以给解惑一下，后台日志也没有报错日志，就是前端发送的/app/job 请求，同一个id 一直发。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Crtrpt** [comment]
貌似没人维护了
