### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by Erko85** [getredash/redash#611]
On http://redash.io/
in navigation pane

Configuration
 -Managing users

the link pointing to
 http://docs.redash.io/en/latest/usage/users.html

is dead

**Comment by arikfr** [comment]
True. This page was removed, after we moved users management into the UI and there wasn't much need for documentation. If you're using an old version, and need this information, you can still find it here: http://docs.redash.io/en/0.7.0/usage/users.html

I'll update the site to remove this link.
