### ISSUE TITLE
chrome browser cache preventing long queries from completing in the front-end

### ISSUE THREAD

**Issue by adammurphy-cc** [getredash/redash#612]
steps to recreate 

 - link to a redshift database
 - run a query from chrome on ubuntu that takes > 5 secs

RESULT: query result doesn't update until the page refreshes

- open network panel in browser dev tools
- click 'disable cache'
- re-run the query

RESULT: query completes correctly

**Comment by arikfr** [comment]
I couldn't reproduce this, can you help with the following questions:
1. Can you try running this query: http://demo.redash.io/queries/644/source, and see if the same happens? 
2. What version of Chrome do you have?

Thanks.

**Comment by arikfr** [comment]
Please reopen if you manage to reproduce this with the demo instance or have more information.

Thanks.
