### ISSUE TITLE
Redash with Docker on Windows isn't working

### ISSUE THREAD

**Issue by maharshi365** [getredash/redash#6151]
### Issue Summary
I am attempting to get redash running on a windows machine. I am following the steps laid out in this page: https://redash.io/help/open-source/dev-guide/docker.

I am getting two issues.
- when running yarn --frozen-lockfile i get the error: No registered package found called "@redash/viz"
- when running the docker-compose up -d 3 of my containers fail to start with the error: exec /app/bin/docker-entrypoint: no such file or directory. redash_server_1, redash_worker_1 and redash_scheduler_1 all fail to start with the same error

A summary of the issue and the browser/OS environment in which it occurs.

### Steps to Reproduce

Follow the guide on https://redash.io/help/open-source/dev-guide/docker on a Win 11 machine

### Technical details:

* Redash Version: 11.0.0-dev
* Browser/OS: Windows 11
* How did you install Redash: Docker (https://redash.io/help/open-source/dev-guide/docker)

**Comment by justinclift** [comment]
Ahhh.  Yeah, there are some significant updates that need to happen with that dev-guide/docker page.

Rather than follow that guide, please try this one:

https://github.com/getredash/redash/wiki/Local-development-setup

That was written using a freshly installed Ubuntu 20.04 Desktop, so it's known to work there.

It shouldn't be *too hard* to adapt to Windows... but I say that without having tried it personally.

Thoughts? :smile:

**Comment by datamike** [comment]
@justinclift Yesterday I tried to install on WSL2 Ubuntu using the docker-compose instructions and got an error.

So today I followed the steps from the wiki page (using a brand new WSL Ubuntu 20.04 instance) and I'm up and running!

**Comment by justinclift** [comment]
> The only small hiccup I ran into was during the 'make compose-build' step (got the error "pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out."). Re-ran the command and the build completed.

Interesting.  Pretty sure I saw something like that earlier on today when doing stuff.  Sounds like some of the Python project infrastructure was having temporary issues of some sort. :smile:

**Comment by justinclift** [comment]
To get it things running under WSL2 Ubuntu, did you have to change much?

**Comment by datamike** [comment]
@justinclift From the Windows Store, I got a brand new WSL Ubuntu 20.04 instance up and running.  Once I fired that up, I ran "sudo apt update." I did not have to change **_anything_** in the wiki steps!

**Comment by justinclift** [comment]
Oh wow.  That's really good news.  Thanks for letting me know. :smile:

**Comment by justinclift** [comment]
@maharshi365 Hopefully you have a chance to try things again as well, but using the wiki guide instead.  In theory (!) it should work. :smile:

**Comment by archanaSRS** [comment]
git clone https://github.com/getredash/redash.git  This clone using and tried to run redash locally on Windows 11 , I got the error that Error occurred while trying to proxy: localhost:8080/login?next=/    . how to solve it?
