### ISSUE TITLE
PSA: Databricks Connector Fails to Connect

### ISSUE THREAD

**Issue by jimsparkman** [getredash/redash#6176]
### Issue Summary

Databricks connector suddenly fails to connect with the following error:

```
[HY000] [Simba][DriverSupport] (1170) Unexpected response received from server. Please ensure the server host and port specified for the connection are correct. (1170) (SQLDriverConnect)
```

### Explanation

I happened to notice the *.cloud.databricks.com SSL cert renewed in the last few weeks. I also discovered the databricks ODBC driver _has its own certificate authority_.

I was able to reproduce the connectivity issue running the following in my redash container, using the databricks driver CA to verify the cert on my databricks instance. Spoiler alert, it fails.

```
/opt/simba/spark/lib/64$ openssl s_client -showcerts -verify_return_error -CAfile cacerts.pem -verifyCAfile cacerts.pem -connect <REDACTED>.cloud.databricks.com:443

CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify error:num=19:self signed certificate in certificate chain
140132234040512:error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1916:
---
no peer certificate available
---
No client certificate CA names sent
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 4589 bytes and written 706 bytes
Verification error: self signed certificate in certificate chain
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 19 (self signed certificate in certificate chain)
---
```

**Verify return code: 19 (self signed certificate in certificate chain)**

### Workaround/Hack

The databricks ODBC driver by Simba contains a parameter `AllowSelfSignedServerCert`.

The redash databricks connector does not expose or allow setting this feature, however, we can use classic injection techniques to get it in anyways.

Host: `****.cloud.databricks.com;AllowSelfSignedServerCert=1`

<img width="660" alt="image" src="https://github.com/getredash/redash/assets/6545560/6b8f6c83-aa40-49f7-81cc-b7086e13853d">

databricks should really release an updated driver/CA but this works for now.

**Comment by justinclift** [comment]
Interesting.  Thanks for the heads up @jimsparkman. :smile:

**Comment by toppratyush007** [comment]
@jimsparkman thanks man! this saved us a day.

**Comment by justinclift** [comment]
@arikfr Is this something someone at Databricks should be pointed at?

**Comment by arikfr** [comment]
@justinclift I'll check.

**Comment by wlach** [comment]
I'm going to close this, feel free to re-open if I'm missing something

**Comment by marinaolina** [comment]
@arikfr @justinclift hello is it possible to update the docker image https://github.com/getredash/redash/releases with the latest fix? thank you
