### ISSUE TITLE
Support for creating public facing dashboards

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#619]
i.e. the ability to generate a link to a dashboard, that is hard to guess (see @erans's first comment) and allows access only to it.

**Comment by erans** [comment]
What Google Photos and others does for this kind of thing is to generate a unique ID (say a GUID or something even larger) that is hard to guess. That would be the "public ID" of that query.

So for item 1 we can easily just add a place where we can say the query is public and update the DB to include a public ID. If there is no public ID you won't be able to see it. If the ID changed, you won't be able to see it.

For item 2 we can also add some kind of a pass key or token that will set a temp cookie to view the data. So if that cookie does not exist the user will be redirected to a page to enter the token/password.

Item 3 - not yet sure how to cover.


Now, if the authentication is a problem we might be able to somehow embed a token on the URL or the Public ID will be some kind of a web token with the access token inside of it encrypted.

What do you think?

**Comment by arikfr** [comment]
Actually supporting this for queries should be very easy because queries already have per-query API access. Supporting for dashboards is a bit trickier, because it involves access to multiple resources (the dashboard and its widgets/visualizations/queries).

I think it will be very simple to implement once we have setup permissions system, that checks on each access if the current user has access to the requested resource. Once we have this, we can generate a "user", which is identified by a token and has access to a predefined set of resources (the dashboard and its derived resources).

**Comment by arikfr** [comment]
(I've updated the issue text to reduce scope, as the other points were either private cases of the first or just a different feature)

**Comment by victoruiz** [comment]
This feature, together with embeddable dashboards + permissions system will be really amazing.
