### ISSUE TITLE
Shared public dashboard: widgets don't reload when changing parameters

### ISSUE THREAD

**Issue by i4nf0x** [getredash/redash#6203]
### Issue Summary

When I publish a dashboard, changing parameters (drop down or free values) does not refresh the table, even after confirming "Apply changes". It works okay with parameters that I recently ran but not with a new set of parameters. It works okay when I use the query or the dashboard from within Redash itself instead of sharing/publishing it.

When I change parameters, 99% of time I'm stuck with a page that seems to be reloading the widgets, but it never reloads. Manual refresh of the page fixes the issue most of the time.

### Steps to Reproduce

1. Create a large random table in postgresql: `create table redash_test as select s, md5(random()::text) from generate_Series(1,2000) s`
2. Create a query with some parameters: `select * from redash_test where s > {{ a }} and s < {{ b }}` 
![image](https://github.com/getredash/redash/assets/54349959/fcfd6a9f-57ff-4baf-b3c4-84a7348ccaac)
4. Publish the query
3. Create a dashboard called "Test", add this query as a widget (table)
5. Publish and share this dashboard.
6. Open the "Secret address" in a new browser window
7. Enter some parameters A and B, confirm the "Apply changes". Nothing happens.

![chrome-capture-2023-6-20](https://github.com/getredash/redash/assets/54349959/8449f885-cd24-4232-89fc-c189ec25ef24)

If we wait a bit (5 seconds) and **then refresh the page manually**, it reloads with correct parameters. However, the correct data will never appear on their own.

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

The shared/public dashboard should refresh after changing the parameters. It should behave the same way as when I use it from Redash itself

### Technical details:

* Redash Version: 10.1.0.b50633
* Browser/OS: Linux, Chromium 114.0.5735.198
* How did you install Redash: Docker

**Comment by gaecoli** [comment]
Don't worry! I will fix it.

**Comment by gaecoli** [comment]
The wrong result here is because you checked the option of Limit 1000 in the query, but the option of Limit 1000 is not passed in by default in the public dashboard, resulting in inconsistent results of the two queries.

**Comment by gaecoli** [comment]
@i4nf0x I fixed it. You can pull master branch to test it.

**Comment by i4nf0x** [comment]
> @i4nf0x I fixed it. You can pull master branch to test it.

Thank you for the fix, now it works as it should!

**Comment by gaecoli** [comment]
> > @i4nf0x I fixed it. You can pull master branch to test it.
> 
> Thank you for the fix, now it works as it should!

Happy to help you!
