### ISSUE TITLE
redash is rounding numeric/float results to two decimal places?

### ISSUE THREAD

**Issue by astewart-twist** [getredash/redash#622]
I think redash is forcing floats/numerics in query results to two decimal places?  The following example should be returning division results to 10 decimal places.

https://demo.redash.io/queries/659/source

Is there a way to override this?

**Comment by arikfr** [comment]
Unfortunately there is no way. I'm hoping to add options for the table visualization, that will allow overriding this and some other options. But that currently only in the planning phase.

**Comment by astewart-twist** [comment]
Glad to know I'm not going crazy on the SQL side at least :)  Could you point me to where in the code that rounding is happening?  I may try to patch a copy for myself.   That or just use percentages.

**Comment by arikfr** [comment]
It's this line:
https://github.com/EverythingMe/redash/blob/master/rd_ui/app/scripts/visualizations/table.js#L71

**Comment by jvyduna** [comment]
We use a temporary hack for this - casting to string. For MySQL:

2 decimals shown: 
`SELECT ROUND(1/9,10);`

10 decimals shown:
`SELECT CAST(ROUND(1/9,10) AS CHAR);`

**Comment by arikfr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tQxDwU4s&#x2F;50-configuration-for-table-visualization"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Configuration for table visualization</a>

**Comment by arikfr** [comment]
Closing in favor of #1356.
