### ISSUE TITLE
Show query details on mobile devices

### ISSUE THREAD

**Issue by twolfson** [getredash/redash#626]
The other day I was trying to write/run a query from my phone in `redash` but couldn't since the database select was hidden and it had defaulted to `redash:metadata`. I started looking into this and there are 4 places where things are hidden via `rd-hidden-xs`.

https://github.com/EverythingMe/redash/blob/9886f5b13bba7762dd24c4eefbaf3c54f455263b/rd_ui/app/views/query.html

- `<query-source-link>`
- `Fork` button
- Query information
- Download dataset button

From my perspective, I see nothing wrong with showing these elements (especially fork/query info). With respect to download, I think downloading things to my phone is fine -- probably not widely used but fine. I was wondering if there was a reason and if we would be open to removing that class.

**Comment by twolfson** [comment]
Here are screenshots so we have a point of reference:

![screen_shot_2015-10-23_at_6_31_18_pm](https://cloud.githubusercontent.com/assets/902488/10707194/74b8cc8c-79b4-11e5-9b94-e8fbde89589e.png)

![screen_shot_2015-10-23_at_6_31_23_pm](https://cloud.githubusercontent.com/assets/902488/10707196/78866c66-79b4-11e5-9b4b-15296aab4ce7.png)

**Comment by twolfson** [comment]
Whoops, that screenshot has a `Fork` button since it was on a dev machine where I removed a `rd-hidden-xs`. However, in the `master` branch it is hidden after `rd-hidden-xs`.

**Comment by twolfson** [comment]
Any thoughts on this?

**Comment by arikfr** [comment]
I don't remember the exact reasoning, but there was some issue with showing this details in a mobile view (something to do with design). So under the assumption, that most users won't try to write queries from a mobile device, we just hid it...

Just like you, I see nothing wrong with showing the details part on a mobile device. It might need some work to make it look properly.

**Comment by twolfson** [comment]
Hm, weird. Well from what I saw everything was more/less good to go on mobile.

One note was that Fork/Save were pretty close together which might be hard to hit accurately on mobile.

I should have some free time on Friday to open a PR for this -- unless you want to commandeer this instead ;)

**Comment by arikfr** [comment]
You're more than welcome to do this :-)

**Comment by twolfson** [comment]
Ah, sorry for not closing this x_x

For reference, this was resolved via https://github.com/getredash/redash/pull/638
