### ISSUE TITLE
We have 3 different config files for `flake8`.  Make it just one.

### ISSUE THREAD

**Issue by justinclift** [getredash/redash#6323]
We use the `flake8` Python utility to check the formatting of our Python source code.

However, we have three different configurations of it at the moment.

It's probably because we run `flake8` from three different places.

Ideally, we should just have a single configuration file that gets used by all of our `flake8` calls instead.

### Existing flake8 configuration files

* https://github.com/getredash/redash/blob/f6ba9501da125b308f8e475b5bb303d709d228b8/bin/flake8_tests.sh
  * This one is used by `make test` and `make lint`.
  * https://github.com/getredash/redash/blob/f6ba9501da125b308f8e475b5bb303d709d228b8/Makefile#L34-L35

* https://github.com/getredash/redash/blob/f6ba9501da125b308f8e475b5bb303d709d228b8/.pre-commit-config.yaml#L11-L14
  * This one is used by our `pre-commit` hook

* https://github.com/getredash/redash/blob/f6ba9501da125b308f8e475b5bb303d709d228b8/setup.cfg#L4-L10
  * I'm not sure where this one is used.

**Comment by TrainedPro** [comment]
Hello, I am interested in working on this issue.

We could start by deciding what flake8 configuration you would actually like for all the files and how many instances i would have to replace. I personally think using the configuration that is most widely used would be the best.

Let me know how to proceed.

**Comment by justinclift** [comment]
@TrainedPro Cool. :smile:

We seem to be using this one the most, as it gets run every time we run our backend lint tests:

https://github.com/getredash/redash/blob/f6ba9501da125b308f8e475b5bb303d709d228b8/bin/flake8_tests.sh

**Comment by justinclift** [comment]
@TrainedPro Oh, I forgot to mention something important.  This is the "local development setup guide" we know works:

https://github.com/getredash/redash/wiki/Local-development-setup

There's older setup information on the official Redash knowledge base, but it's outdated and confusing.

So, please use the above wiki link instead. :smile:

**Comment by TrainedPro** [comment]
Here are the **10** mentions for `flake8` that i found:
```
./setup.cfg:4:[flake8]
./bin/flake8_tests.sh:5:flake8 --version ; pip --version
./bin/flake8_tests.sh:7:flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
./bin/flake8_tests.sh:9:flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
./.pre-commit-config.yaml:11:  - repo: https://github.com/pycqa/flake8
./.pre-commit-config.yaml:14:      - id: flake8
./.github/workflows/ci.yml:19:      - run: sudo pip install flake8==6.1.0 black==23.1.0 isort==5.12.0
./.github/workflows/ci.yml:20:      - run: flake8 .
./Makefile:35:  ./bin/flake8_tests.sh
```

It seems the version being used is the same. I would like to understand what you would require me to do to make their configurations the same too.

**Comment by justinclift** [comment]
They don't seem to all use the same config file, which is the problem that needs fixing. :smile:

For example, when `flake8` is run from the pre-commit hook (aka `make format`), it seems to completely ignore the configuration in `setup.cfg`.

However, that configuration is `setup.cfg` is what gets used when `flake8` is run as a lint test (`make lint`).

--

For the "how to fix it"... I have no idea.  The solution is up to whoever takes up this issue, so er... "Yours!" maybe?  "Tag, you're it..." :wink:

**Comment by konnectr** [comment]
for example here https://github.com/tiangolo/fastapi/blob/master/.github/workflows/test.yml#L35 -> https://github.com/tiangolo/fastapi/blob/master/scripts/lint.sh and config -> https://github.com/tiangolo/fastapi/blob/master/pyproject.toml
AND
https://github.com/tiangolo/fastapi/blob/master/.pre-commit-config.yaml -> https://github.com/tiangolo/fastapi/blob/master/pyproject.toml 
@TrainedPro

**Comment by TrainedPro** [comment]
@justinclift There are exclusions in last 2 configurations that you have mentioned. If we were to overwrite it, you would be unable to retain them. Is that fine?

https://github.com/getredash/redash/blob/9a7d2cdc02106c27cd0662ec39a534efc306ee02/.pre-commit-config.yaml#L13-L15

**Comment by konnectr** [comment]
> @justinclift There are exclusions in last 2 configurations that you have mentioned. If we were to overwrite it, you would be unable to retain them. Is that fine?
> 
> https://github.com/getredash/redash/blob/9a7d2cdc02106c27cd0662ec39a534efc306ee02/.pre-commit-config.yaml#L13-L15

Let's you create a PR with your offer. And there we will continue discussing the solution

**Comment by justinclift** [comment]
Yeah.  Lets get some initial potential code ready to take a look at (eg in a PR), and then we can see what might need changing.

From memory the exclusions are to make sure the formatting doesn't get applied to stuff that makes no sense for it.  For example the "migrations" and "node_modules" folders (etc).

As long as we're excluding the right stuff, the same exclusions for all three callers should be fine.  In theory. :smile:

**Comment by wlach** [comment]
Pretty sure this is obsolete due to https://github.com/getredash/redash/pull/6441
