### ISSUE TITLE
Clickhouse connection error InvalidSchema

### ISSUE THREAD

**Issue by vera2pm** [getredash/redash#6325]
### Issue Summary

Attempt to connect to Clickhouse database. Error occurs: "Connection error to: clickhouse://{host}:8123 (InvalidSchema)."
I have tried different hosts.

Connections to MySQL and Big Query are okay.

### Steps to Reproduce

1. Use docker compose to build container with Redash (tag redash/redash:10.1.0.b50633)
2. Other required services in compose have tags "latest"
3. docker compose run --rm server create_db
4. docker compose up -d
5. Open http://localhost:5000/ and create connection to clickhouse

### Technical details:

* Redash Version: redash/redash:10.1.0.b50633
* Browser/OS: Google Chrome / Windows 10
* How did you install Redash: docker compose tag redash/redash:10.1.0.b50633
I have tried with other tags too: latest, redash/redash:8.0.0.b32245

**Comment by denisov-vlad** [comment]
Now Redash supports only http(s) connection and port 8123 is used for it. Try to change the scheme from `clickhouse` to `https` or `http`.

**Comment by vera2pm** [comment]
@denisov-vlad it worked. Thank you!

**Comment by konnectr** [comment]
I think you got the answer.
