### ISSUE TITLE
Switch the Oracle Driver module from cx_Oracle to python-oracledb

### ISSUE THREAD

**Issue by snickerjp** [getredash/redash#6380]
This is a issue to switch the Oracle Driver module from cx_Oracle to python-oracledb.

Please note the following points with this change.

- The supported Python version is 3.6 or higher.🐍
- The supported Oracle database version is 12c or higher.
  - Thin mode: 12c or higher.
  - Thick mode: 9.2 or higher. (with Oracle Client library)
- In Thin mode, you **do not need the Oracle Client library**💡
- The **ENCODING option has been deprecated**. Please set the NLS_LANG environment variable instead.❌
  - https://python-oracledb.readthedocs.io/en/latest/user_guide/globalization.html#setting-the-client-character-set
- For other considerations from cx_Oracle changes, please refer to the following documents.
  - https://oracle.github.io/python-cx_Oracle/#features
  - https://oracle.github.io/python-oracledb/#features
  
 https://github.com/getredash/redash/pull/6373#issuecomment-1682641246

**Comment by justinclift** [comment]
Cool.  This sounds like a good idea.

It would let us include Oracle database support (for Oracle 12c and above) in our standard builds, without needing to do anything special.

I'm not sure how many of our users would use older Oracle versions, therefore needing the thick mode / Oracle Client library.

My feeling is we should start with the easy approach first, and only consider adding in the Oracle Client library pieces if there is real demand for it.

**Comment by justinclift** [comment]
I *think* that with PR #6389 merged, this issue can be closed now? :smile:

**Comment by snickerjp** [comment]
Of course,
I'll keep it closed.
