### ISSUE TITLE
Add/Verify Greenplum Support

### ISSUE THREAD

**Issue by Xangis** [getredash/redash#640]
The Greenplum database, at https://github.com/greenplum-db/gpdb has recently been open-sourced.

It is based on PostgreSQL and is commonly used in many of the same use cases as Redshift (columnar/sharded Postgres).

The PostgreSQL module may work for Greenplum without modification. Or it might not. It would be great to have official support for it. I'll try redash against a GPDB to see if it works and should be able to report back in a few days.

**Comment by arikfr** [comment]
:+1: supporting Greenplum will be great. I don't use it myself, so can't help much with the testing. But if you have any questions, let me know -- I'll be happy to assist.

**Comment by Xangis** [comment]
I've done a bit of Redash testing against a small Greenplum cluster and it works just fine with the PostgreSQL driver (and doesn't require any special settings). That makes sense, since tools like pgAdmin work with Greenplum.

**Comment by arikfr** [comment]
Closed with #688.
