### ISSUE TITLE
Should we have the latest docker image after each merge

### ISSUE THREAD

**Issue by Avey777** [getredash/redash#6429]
![image](https://github.com/getredash/redash/assets/35259040/c9a2c586-616b-4733-bac7-413f4a9b48a7)

**Comment by justinclift** [comment]
@Avey777 Our existing code is unlikely to be "production quality" at the moment, after the large amount of dependency updates that happened a few weeks ago.

We'll want to have people testing these images (and reporting bugs) for a while first, so we can make sure they're "ok".

**Comment by guidopetri** [comment]
Closing this since the `preview` image auto-updates now.
