### ISSUE TITLE
Larger description textbox

### ISSUE THREAD

**Issue by guidopetri** [getredash/redash#6434]
### Discussed in https://github.com/getredash/redash/discussions/6432

<div type='discussions-op-text'>

<sup>Originally posted by **robosong** September  7, 2023</sup>
In query edit mode, please keep the description text box expanded to fit the contents when I click to edit the description. Currently when I click to edit the description the text box shrinks to display only two lines which clips the contents and makes it very annoying to edit. I always have to manually expand it to see the full contents again.

Thanks.
</div>

**Comment by deathvulture** [comment]
I will try to do this one.

**Comment by deathvulture** [comment]
I think you can close this one @guidopetri

**Comment by guidopetri** [comment]
Thanks for the help @deathvulture :)
