### ISSUE TITLE
MongoDB v6 - Unsupported OP_QUERY command

### ISSUE THREAD

**Issue by lewisstancer** [getredash/redash#6437]
### Issue Summary

Cannot connect to MongoDB v6 database. I am just met with the same error about updating the client:

Unsupported OP_QUERY command: connectionStatus. The client driver may require an upgrade.

I saw a discussion somewhere from July that it had been fixed but even on the latest version it does not work, can you provide a workaround or let me know when this will be available please?

**Comment by justinclift** [comment]
We've updated the MongoDB driver in our development source code, but there's not yet an official release from that source code which you could use.

It'll probably be a few weeks until something fairly solid and tested is ready.

**Comment by lewisstancer** [comment]
Thank you for the response. Is there a temporary workaround I could utilise so I can evaluate the software? I don't mind waiting for an official release but want to test things out

**Comment by justinclift** [comment]
As long as it's for "testing things out" purposes, then you're welcome to try the `preview` Docker image I uploaded here:

https://hub.docker.com/r/pgautoupgrade/tempstuff/tags

Note the temporary repository location, as I just needed somewhere to manually upload it while we work on automatically generating docker images.  Once the official docker images are being automatically built, I'll nuke that "pgautoupgrade/tempstuff" repo. :smile:

**Comment by justinclift** [comment]
Also note that the docker image there *should* mostly work ok, but we haven't yet gone through a period of stabilisation and bug fixing.  So I wouldn't want to try running that image long term as a production thing. :wink:

**Comment by lewisstancer** [comment]
Thank you 😊 I will give it a shot

**Comment by Joseba21** [comment]
Has there been any progress on this issue? I get the same error. Should I test the preview Docker Image mentioned above?

**Comment by justinclift** [comment]
@Joseba21 Yes, please try the `redash/redash:preview` image.  From rough memory, it *should* work for MongoDB 6.x data sources.

**Comment by Joseba21** [comment]
I upgraded redash version from 8 to 10 and it works.

**Comment by justinclift** [comment]
Heh Heh Heh.  Or upgrade to version 10 I guess. :smile:

Good news that you got it working. :grin:

**Comment by justinclift** [comment]
@Joseba21 Are we ok to close this issue?

**Comment by Joseba21** [comment]
@justinclift Yes.

**Comment by christoboucher** [comment]
Is there a way to get Redash v8 to connect to MongoDB v7. There are features in v8 that we are using that does not work in v10, otherwise I would upgraded to v10 long ago.

**Comment by justinclift** [comment]
@christoboucher Technically, yes there is.  You can create a new docker image based on the v8 Redash one, and try updating the MongoDB library to a more recent release.

I have no idea if it would actually work that easily though, as there's every chance the newer MongoDB library will need newer pieces of other libraries, which in turn might need other updated ones.

That being said, it might all just work perfectly the first time around too.  So, probably give it a try and see how you go? :smile:
