### ISSUE TITLE
REDASH GOOGLE AUTH FAILS

### ISSUE THREAD

**Issue by cheekamadu21** [getredash/redash#6456]
Hello there,

I installed Redash via the helm chart redash/redash. I have completed the initial setup and included my Google clientId and ClientSecret, as well as configured authorized domain from the settings page. When I try to login however using Google, I get this response in the web browser "Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."

When I look in the logs of the container, I get the following lines of error:
![Screenshot 2023-09-15 at 03 38 42](https://github.com/getredash/redash/assets/145084642/4de80488-8ed4-48ba-be58-9dbe9da1c482)

We have a stable version installed using Docker compose but running the tag "8.0.0.b32245" rather than the "10.1.0.b50633" which comes with the latest helm chart, so I tried to use that tag, but the issue still persists.

Any advice/help would be highly appreciated.

**Comment by justinclift** [comment]
There is a *potential* fix for this in our very latest source code, however it's not well tested yet and we haven't yet uploaded a preview docker image for testing.

Hopefully you can wait a few days then try out the preview docker image when its ready. :smile:

**Comment by cheekamadu21** [comment]
@justinclift Thank you for your response. I guess I'd have to play the waiting game, although we are using this in our production envrionment, so we would wait until a stable version is released. Thank you
