### ISSUE TITLE
How about tracking access Dashboard Redash

### ISSUE THREAD

**Issue by trantrinhquocviet** [getredash/redash#6461]
We use GitHub only for bug reports 🐛

Anything else should be a discussion: https://github.com/getredash/redash/discussions/ 👫

🚨For support, help & questions use https://github.com/getredash/redash/discussions/categories/q-a
💡For feature requests & ideas use https://github.com/getredash/redash/discussions/categories/ideas

Alternatively, check out these resources below. Thanks! 😁.

- [Discussions](https://github.com/getredash/redash/discussions/)
- [Knowledge Base](https://redash.io/help)

So, I want to track how many people in my organization have access to my dashboard. It's OKR of my BI team. I need to know about the dashboard's frequency access.

**Comment by denisov-vlad** [comment]
Hi @trantrinhquocviet 

You can connect to the Redash metadata source and use `events` table.

Here is a quick example how to write such query:

```
SELECT d.name as dashboard, COUNT(DISTINCT e.user_id) as users
FROM events e
INNER JOIN dashboards d ON e.object_id::int = d.id
WHERE e.object_type = 'dashboard'
AND e.action = 'view'
AND e.created_at BETWEEN '{{ date.start }}' AND '{{ date.end }}'
GROUP BY dashboard
ORDER BY users DESC
```

**Comment by trantrinhquocviet** [comment]
thanks you so much
