### ISSUE TITLE
[Help Needed] Connection Test Failed: (2006, 'Plugin http could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/http.so: cannot open shared object file: No such file or directory')

### ISSUE THREAD

**Issue by DerrickProfilePrint** [getredash/redash#6465]
I have set up redash v10.1.0 using the docker image redash/redash:10.1.0.b50633 according to the instructions on 

I can access redash fine on http://<ip address>.

I have added  a AWS RDS (mySQL version 8.0.33) data source to redash.

However, when testing the connection, i get an error message:
Connection Test Failed: (2006, 'Plugin http could not be loaded: /usr/lib/x86_64-linux-gnu/mariadb19/plugin/http.so: cannot open shared object file: No such file or directory')

Any advice on where I can get this plugin? Thank you very much

**Comment by guidopetri** [comment]
@DerrickProfilePrint were you able to solve the issue? What was the solution?
