### ISSUE TITLE
Document setting up a dev environment on a mac

### ISSUE THREAD

**Issue by alonho** [getredash/redash#648]
### Dependencies

`brew install postgres` - follow invocation instructions
`brew install redis` - follow invocation instructions
### Install a virtualenv

`virtualenv env`
`. env/bin/activate`
`pip install -r requirements.txt`
### Init the database

`createdb redash`
`./bin/run python manage.py database create_tables`
### Create an admin user

`./bin/run python manage.py users create --admin --password admin "Admin" "admin"`

**Comment by arikfr** [comment]
## Troubleshooting

If pip install fails to install cryptography, try the following: (from: https://cryptography.io/en/latest/installation/#building-cryptography-on-os-x)

```
$ brew install openssl
$ env CRYPTOGRAPHY_OSX_NO_LINK_FLAGS=1 LDFLAGS="$(brew --prefix openssl)/lib/libssl.a $(brew --prefix openssl)/lib/libcrypto.a" CFLAGS="-I$(brew --prefix openssl)/include" pip install cryptography
```

**Comment by jeffwidman** [comment]
Isn't Vagrant or Docker-Compose the preferred method for setting up a redash dev environment these days?

**Comment by arikfr** [comment]
Opened #1480 to track the work on the dev guide. Keeping this one open until I'm done.

**Comment by arikfr** [comment]
The developer guide has been updated along with new documentation on how to use Docker for  easy setup of your dev environment (instead of Vagrant).

https://redash.io/help-onpremise/dev/guide.html

Thank you for all your feedback!
Your feedback on the new guide & flow is always welcomed.
