### ISSUE TITLE
QRDS : GA4 seems to not being supported

### ISSUE THREAD

**Issue by bt0r** [getredash/redash#6481]
### Issue Summary

Hi there 👋🏻 
I'm trying to use QRDS to "group by" on a Google Analytics 4 result and it seems it doesnt work.

### Steps to Reproduce

1. CREATE a basic GA4 query (using https://ga-dev-tools.google/ga4/query-explorer/)
2. CREATE a basic QRDS query, example `SELECT * FROM query_XXX` where `XXX` is the redash query's id
3. It should not work
4. DO the same with a Google Analytics query (not GA4) , it works

### Technical details:

* Redash Version: 11.0.0-dev
* Browser/OS: Firefox 118.0b8 (build: 20230912175928) 
* How did you install Redash: Custom docker image

**Comment by justinclift** [comment]
This is a bit confusing to me:

```
2. CREATE a basic QRDS query, example "SELECT * FROM query_XXX" where XXX is the redash query's id
3. It should not work
```

I'm pretty sure the query results are stored into a SQLite database, so when you do the `SELECT * FROM query_XXX` query it's then using SQLite syntax.

Not sure whey you're thinking that shouldn't work?

**Comment by bt0r** [comment]
> Not sure whey you're thinking that shouldn't work?

I dont "think" that shouldn't work, i made an issue because it does not work when i tried it

**Comment by deathvulture** [comment]
I tried to reproduce the error, but in my case it worked with GA4. 
I am using the same version of Redash. 

![image](https://github.com/getredash/redash/assets/2754353/e10a8bd8-67ac-4d31-a8b6-6f842b01f87a)
![image](https://github.com/getredash/redash/assets/2754353/fa1a974a-cbf1-482f-bd54-b368698a7a03)

**Comment by bt0r** [comment]
Hey @deathvulture !
Thanks for trying to reproduce the error, i tried to recreate a GA4 query and a new QRDS one and this time it works ! i did nothing special than mentionned above but it seems to working now... so i'll close this issue.

Thank you guys for your times !
