### ISSUE TITLE
Reset user password by admin?

### ISSUE THREAD

**Issue by tjwudi** [getredash/redash#649]
So after moving user management outside of `/admin` to `/users`, how does admin reset users' password? Are we missing it or not?

**Comment by arikfr** [comment]
When you open a user's profile (as admin), there is a "Password" tab where
you can change his password. Although you need to know the current one.
Maybe I need to remove this restriction for admins.

-- 
Arik Fraimovich

**Comment by tjwudi** [comment]
Yeah ... If I know the current one then I won't ask admin to reset for it, isn't it?  =D   And also it would probably be good to have delete user option. Is there any reason we don't have users management in `/admin` anymore?

**Comment by arikfr** [comment]
I prefer to replace the old `/admin` views with the new ones, as the old ones didn't do proper data validation and could cause issues. 

I'll add both the option to reset password & to delete users to the new views (or you can do that if you have the time :)).

**Comment by hirefrank** [comment]
:+1: In the meantime, what is the safest way to remove a user -- so I can "reset" them and create a new account?

**Comment by arikfr** [comment]
@hirefrank did this user create any queries?

**Comment by arikfr** [comment]
@hirefrank btw, if you only need to reset his password, you can do it from the command line:

```bash
$ cd /opt/redash/current
$ sudo -u redash bin/run ./manage.py users password {user's email} {new password}
```

**Comment by hirefrank** [comment]
Thanks for the tip.

On Sun, Nov 22, 2015 at 1:00 AM, Arik Fraimovich <notifications@github.com>
wrote:

> @hirefrank <https://github.com/hirefrank> btw, if you only need to reset
> his password, you can do it from the command line:
>
> $ cd /opt/redash/current
> $ sudo -u redash bin/run ./manage.py users password {user's email} {new password}
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getredash/redash/issues/649#issuecomment-158715730>.
>



-- 
Frank Harris
hirefrank.com / @hirefrank <http://twitter.com/hirefrank>

**Comment by vitorbaptista** [comment]
@arikfr Sorry for resurrecting an old thread, but any plans on allowing admins to change the users' passwords without knowing the current one? I'd like to avoid setting up an SMTP server, but need a way to reset the users' passwords in case they forget.

**Comment by arikfr** [comment]
@vitorbaptista you don't need to setup an SMTP server, but spend ~10 minutes signing up with a free MailGun account. As we move forward there will be additional features that will work better with working email setup (like notifications to admins in case of issues).

For now your option is to use the CLI. You are welcome to submit a pull request to change it to generate the forgot password link instead of asking the admin to supply a new password for the user.

**Comment by lwx5924** [comment]
> ```shell
> bin/run
> ```

what can I do if I forget the admin's account and password?
