### ISSUE TITLE
Update "Developer Installation Guide" to use poetry

### ISSUE THREAD

**Issue by masayuki038** [getredash/redash#6509]
In "Developer Installation Guide", the instruction is to install a package using pip.
https://redash.io/help/open-source/dev-guide/setup

This project has already migrated to `poetry`, so we should update this page to an instruction that uses it.

![image](https://github.com/getredash/redash/assets/36331/60c8b5b0-01c6-4b4b-b3a6-17cfd0446d1c)

**Comment by justinclift** [comment]
Yeah.  We need to copy the [current developer documentation](https://github.com/getredash/redash/wiki/Local-development-setup) across to [the website](https://github.com/getredash/website).

**Comment by masayuki038** [comment]
@justinclift It is nice. Sorry, I can't find this.
Will it be uploaded soon ? If so, I will close this...

**Comment by justinclift** [comment]
We'd like to get it done, but so far no-one has put it on their ToDo list. :sweat_smile: 

If you want to help out, that'd be a useful update to make. :smile:

**Comment by masayuki038** [comment]
Well, I'm a beginner with Redash Project, so I feel hard... If you have some direction on updating the Document, I think we can help a little.

Will the contents of this wiki be reflected on each web page manually? Or are you planning to make this wiki the main document and discontinue [dev-guide](https://redash.io/help/open-source/dev-guide) ?

**Comment by justinclift** [comment]
> Or are you planning to make this wiki the main document and discontinue dev-guide?

That's a good question.  It's probably better for now, if we update the website to have the old pages point to the wiki.

Doing that would make sure people get the right info, and it would keep things on the wiki where it's easier for us to change when needed. :smile:

**Comment by masayuki038** [comment]
Understood. If no one approaches this issue, I'll create a rough PR later to encourage discussion.
I think the content on the wiki is great. To be honest, I wish I had known sooner 😅

**Comment by justinclift** [comment]
Sounds like a plan, consider this task as "yours". :grin:
