### ISSUE TITLE
Setup docker-compose.yml uses very old versions of docker images

### ISSUE THREAD

**Issue by guidopetri** [getredash/redash#6559]
### Issue Summary

While investigating #5820 , I noticed that we have some very old versions of images on the setup repo - namely, this old nginx container that doesn't seem maintained, and postgres 9.6, as well as redash 8 by default. We should update these.

### Steps to Reproduce

N/A. This is a bug/issue because if people follow the setup docker-compose.yml file, they'll have very old versions of our software.

**Comment by mavencode01** [comment]
@guidopetri Is there a latest build of the docker image ?

**Comment by guidopetri** [comment]
We have an auto-updating `preview` image tag now, but no stable image since the relaunch as community managed. Pre-community, we had redash 10.1

**Comment by mmospanenko** [comment]
seem the project is dead?

**Comment by guidopetri** [comment]
Redash is not dead, but development is obviously not as fast as it was when there was an entire company of full time engineers working on it :) it's also still around the holidays/new year, so not a lot has happened the past month or so.

**Comment by justinclift** [comment]
We updated the versions of Redis, PostgreSQL and Nginx ages ago.  Both PostgreSQL and Nginx now use the `latest` available version, whereas Redis uses version 7 which should be fine for several more years.
