### ISSUE TITLE
AWS DynamoDB in Redash

### ISSUE THREAD

**Issue by ankur-dailype** [getredash/redash#6570]
How to write query in Redash to fetch data from DynamoDB table.
Can we use any other attribute of DynamoDB table except sort and partition key to fetch and filter the data.
Kindly provide the example

**Comment by masayuki038** [comment]
I haven't touched DynamoDB. So, I may not be the best person to reply...
I checked the code and found that Redash uses https://github.com/stevearc/dql/tree/master for querying. Please check it.

**Comment by ankur-dailype** [comment]
Thanks @masayuki038
