### ISSUE TITLE
Display catalog information on the schema pane when connecting to Trino

### ISSUE THREAD

**Issue by masayuki038** [getredash/redash#6574]
## Description
As a result of the discussion at https://github.com/getredash/redash/discussions/6483, we found that it would be better to display catalog information on the schema pane when connecting to Trino.

**Comment by justinclift** [comment]
The title and description here sounds like a PR?

**Comment by masayuki038** [comment]
@justinclift Is it better to focus on the problem rather than the wat to fix?

**Comment by justinclift** [comment]
Not sure what you mean. :wink:

To me, we have #6483 for discussing the problem already.  People with an interest in Trino will already be either subscribed to that, or able to find it easily when searching.

The next step (when you're ready) is to start the PR for fixing the problem. :smile:

**Comment by masayuki038** [comment]
Sorry, I mentioned about this title in my previous comment.

> The next step (when you're ready) is to start the PR for fixing the problem. 😄
OK. Understood.
