### ISSUE TITLE
Error detecting the version of libcrypto

### ISSUE THREAD

**Issue by willvictor** [getredash/redash#6579]
### Issue Summary

I deployed redash/redash:preview and now all queries are hitting the following error: 

``` Error running query: Error detecting the version of libcrypto```

### Steps to Reproduce

1. Deploy redash/redash:preview
2. Log in to redash and try to run any query.

You will hit `Error running query: Error detecting the version of libcrypto`

### Technical details:

* Redash Version: https://hub.docker.com/layers/redash/redash/preview/images/sha256-bb59ad39afc80390335f533f2dce661bcb8cbddea65d18f6664c04aafc079e0f?context=explore
* Browser/OS: chrome
* How did you install Redash: Docker

**Comment by guidopetri** [comment]
@willvictor thanks for the report. Does this happen with every data source? Or which ones did you try?

**Comment by willvictor** [comment]
Hi @guidopetri  and @masayuki038 the datasource is a snowflake datasource

**Comment by willvictor** [comment]
Thank you for the quick responses!

**Comment by masayuki038** [comment]
@willvictor Thanks! This might be it... 
https://community.snowflake.com/s/article/Python-Connector-fails-to-connect-with-LibraryNotFoundError-Error-detecting-the-version-of-libcrypto

**Comment by guidopetri** [comment]
I reached the same conclusion as @masayuki038 , and I just finished merging in their PR (thanks again for that!). @willvictor , would you mind testing the latest `preview` image with a Snowflake data source?

**Comment by willvictor** [comment]
Awesome! I just deployed and it is fixed. Thank you so much!

I did notice what seems to be a breaking change in the latest version:
- for table visualizations that have a percentage display, it seems the formatter now multiplies the value by 100 before displaying the percentage. Previously the formatter did not do this.
- This means if I wanted to display 60% previously, I would write sql that would output 60%, for example `SELECT 100 * 6/10 as perc`, then the format of 0,0.0% would display 60.0%, but now it displays 6000.0%. 

Do you know what might have caused this? Was it intentional?

**Comment by masayuki038** [comment]
I don't know this update...
@justinclift @guidopetri @eradman Do you know this?

**Comment by masayuki038** [comment]
@willvictor I created https://github.com/getredash/redash/issues/6586 to investigate this. Thanks for your report!
Can we close this ('Error detecting the version of libcrypto') ?

**Comment by guidopetri** [comment]
I don't know of any reason why the percentage display might have changed, no, but I agree we should move to #6586 (thanks for creating that @masayuki038 !). Closing since this is complete now, thanks again to both of you!
