### ISSUE TITLE
Custom chart can not generate indicator chart

### ISSUE THREAD

**Issue by viettran97118** [getredash/redash#6597]
We use GitHub only for bug reports 🐛

Anything else should be a discussion: https://github.com/getredash/redash/discussions/ 👫

🚨For support, help & questions use https://github.com/getredash/redash/discussions/categories/q-a
💡For feature requests & ideas use https://github.com/getredash/redash/discussions/categories/ideas

Alternatively, check out these resources below. Thanks! 😁.

- [Discussions](https://github.com/getredash/redash/discussions/)
- [Knowledge Base](https://redash.io/help)
// Available variables are x, ys, element, and Plotly
// Type console.log(x, ys); for more info about x and ys
// To plot your graph call Plotly.plot(element, ...)
// Plotly examples and docs: https://plot.ly/javascript/

var data = [
  {
    type: "indicator",
    mode: "number+gauge+delta",
    value: 220, // Your value here
    domain: { x: x, y: ys },
    delta: { reference: 280, position: "top" },
    title: {
      text: "<b>Profit</b><br><span style='color: gray; font-size:0.8em'>U.S. $</span>",
      font: { size: 14 }
    },
    gauge: {
      shape: "bullet",
      axis: { range: [null, 300] },
      threshold: {
        line: { color: "red", width: 2, gradient: { yanchor: "vertical" } },
        thickness: 0.75,
        value: 270
      },
      bgcolor: "white",
      steps: [{ range: [0, 150], color: "cyan" }],
      bar: { color: "darkblue" }
    }
  }
];
var layout = { width: 400, height: 230 };
Plotly.newPlot(element, data, layout);

Can not result, but dont any error in console.log

**Comment by eradman** [comment]
See also https://github.com/getredash/redash/issues/6600
