### ISSUE TITLE
I can't execute python code with redash.

### ISSUE THREAD

**Issue by kindamu24005** [getredash/redash#6613]
Thank you for checking my question.

I try to execute python code.

It is like this picture.

<img width="1401" alt="スクリーンショット 2023-11-21 16 05 10" src="https://github.com/getredash/redash/assets/107189394/a596de0a-15f9-42a9-a259-b9d1b104ef37">

But about a few second later, I got [error code :5].

It is like this picture.

<img width="1354" alt="スクリーンショット 2023-11-21 16 04 39" src="https://github.com/getredash/redash/assets/107189394/e6f43193-40d6-44f4-8339-4e045e3147e2">

Could you teach me is there any good solution?

I tried "docker-compose down" "docker-compose run --rm server create_db
" and "docker-compose up -d".

And I tried "git clone" again.

But I still got error.

**Comment by viettran97118** [comment]
Really, why can you do that? I'm interesting about that. How to setup python in redash?

**Comment by denisov-vlad** [comment]
@kindamu24005 Looks like a browser crash. Could you try to create a query with simple "SELECT 1" and then use python to fetch its results?

**Comment by denisov-vlad** [comment]
@viettran97118 here is the guide: https://redash.io/help/data-sources/querying/python

**Comment by viettran97118** [comment]
Greate, I did it!

```# print("hello world")

result = {}

schema = [
    {
        "name":"bizzi_id",
        "type": TYPE_INTEGER,
    }
    ]
    
json_data = {
        "bizzi_id": 1,
    }
    
print(json_data)

result["rows"] = [json_data]
result["columns"] = schema 

print(result)

**Comment by denisov-vlad** [comment]
@viettran97118 Also, if you're familiar with pandas, take a look and `dataframe_to_result` function:

```
import pandas as pd

df1 = execute_query("FIRST_SQL_DATABASE", "SELECT 1 as id, 'foo' as table1", "dataframe")
df2 = execute_query("SECOND_SQL_DATABASE", "SELECT 1 as id, 'bar' as table2", "dataframe")

df = df1.merge(df2, on="id")

dataframe_to_result(result, df)
```

I use it regularly and the Python query runner is the killer feature of Redash for me.

**Comment by kindamu24005** [comment]
Thank you for your answer.
I very appriciate.
Now I can execute python code with redash.
This issue will be closed once.
