### ISSUE TITLE
Looking for professional support

### ISSUE THREAD

**Issue by AlfredTallMountain** [getredash/redash#6619]
Hi I'm looking for help for my redash instances:

I have 5 redash installations, created with Digitalocean's docker
and the tasks would be:

1. migrate them to Debian 12 VMs
2. upgrade the version
3. configure auto update of letsencrypt https
4. edit the robots.txt file in order to deny crawling
5. enable auto clean up of the caches (5 days rotation)
6. configure smtp

max bid: 300 usd / euros
can pay with wire transfer, paypal, CC
preferred if you can invoice

Thank you.

**Comment by guidopetri** [comment]
Hey @AlfredTallMountain , I'm sorry, but I don't think this is the right place for this. You might have better luck on platforms specifically for contractors.
