### ISSUE TITLE
Redis url without password

### ISSUE THREAD

**Issue by eugenefeel** [getredash/redash#6623]
Hello, I have a problem
I tried configure readsh with external redis, but can't. I have redis cluster in cloud and have url for connect "tcp://host:26379?auth=pass"
I tried used redis://:pass@hossst:26379 but it isn't work. I got error `redis.exceptions.ResponseError: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?` Can help me?

**Comment by guidopetri** [comment]
This seems to be a misconfiguration of Redis, not of Redash. It sounds like you're trying to use the default user but it doesn't have a password. Maybe double-check the username/password combo?
