### ISSUE TITLE
For self-hosted instance, Google sheet connection test failed, but can't find any logs, how to trouble shooting such cases

### ISSUE THREAD

**Issue by joeyrensh** [getredash/redash#6636]
![image](https://github.com/getredash/redash/assets/39286702/5b480d44-b38d-4035-a68e-49a5bc15220d)

![image](https://github.com/getredash/redash/assets/39286702/6c7a4e14-a7f7-4335-84e2-67eead78e260)

When test connections timeout, can't find any logs on worker/scheduler/server docker logs.
even make sure the log level is debug, can't find any related logs. how to trouble shooting this

**Comment by joeyrensh** [comment]
Thanks masayuki038 for your kindly reply, but actually I have two self-hosted instance, one is OK for the API test, another is not, and from the docker logs, I can't tell any different, and I did the test with the same google sheet API and credential, don't know how to trouble shoot the issue and how to fix the instance

**Comment by joeyrensh** [comment]
By the way, I found some evidence, but not sure what's going wrong.
For the not working instance, in the server logs, can see "[INFO][werkzeug] 10.100.3.61 - - [30/Nov/2023 10:57:56] "GET /api/data_sources/1 HTTP/1.1" 200 -" the IP address is not the IP of server running docker containers.
For the working instance, in the server logs, can see "[INFO][werkzeug] 172.21.0.1 - - [30/Nov/2023 21:50:35] "GET /api/admin/queries/rq_status HTTP/1.1" 200 -" the IP address is the Galway of running docker containers.

how did this happened

**Comment by masayuki038** [comment]
@joeyrensh Could you try these?

1. For the not working instance, create a query with Google Sheets data source and run it even if "Test Connection" failed
2. Check **redash worker log**

You will find a traceback like the one I described in a previous comment. For security reasons, I omitted some parts in it, but they may contain information about the cause of the error. I noticed from this log that Google Sheet API is disabled.

**Comment by joeyrensh** [comment]
Thanks @masayuki038 , follow your steps, I got below trace " HTTPSConnectionPool(host='oauth2.googleapis.com', port=443): Read timed out. (read timeout=120)" , do you know how to resolve it?  From host, I can ping 'oauth2.googleapis.com' with success response.

**Comment by masayuki038** [comment]
@joeyrensh Thanks for your reply. However, sorry, but I don't think we should discuss Docker's network settings here. This is the place to discuss Redash issues.

> 3、when I build the local image, I found that, I need to add "network = host" mode to the docker compose build part, otherwise APT-get can't be updated.

Personally, I think it's best to contact the administrator of your Linux Server hosting Docker.

**Comment by joeyrensh** [comment]
thanks a lot for your help , I have resolve all the issues, can close this ticket

**Comment by masayuki038** [comment]
@joeyrensh Thanks for reporting the result. I'm happy to hear it!
Please keep this issue since I think Redash should log an error on "Test Connection" failure. I will fix this.

Thanks for your contribution!
