### ISSUE TITLE
.env is readonly

### ISSUE THREAD

**Issue by zaret-rocket** [getredash/redash#665]
I'm really excited about getting re:dash up and running for our organization.

I used the AWS (us-west-1: ami-b36babf7) and was able to get it up and write some queries, but I can't edit the .env file. I've tried accessing as root without success. I don't have much system setup experience and googling didn't get me to any solutions. Here are couple of screen shots showing the issue.

![screen shot 2015-11-19 at 5 51 32 pm](https://cloud.githubusercontent.com/assets/13950545/11289927/67112e0c-8ee6-11e5-8a03-3207e729baee.png)
![screen shot 2015-11-19 at 5 54 28 pm](https://cloud.githubusercontent.com/assets/13950545/11289950/a06f4026-8ee6-11e5-8b61-34c5ebc56a5e.png)

Thanks!
Mike

**Comment by arikfr** [comment]
You need to edit it with sudo : `sudo vi. env` (sudo makes you root).

**Comment by zaret-rocket** [comment]
Thanks for the quick response. I must have done something that corrupted that instance (it was still readonly with sudo). I terminated it and started over and now everything is working as expected. Thank you.
