### ISSUE TITLE
Notification template variables seem wrongly interpret

### ISSUE THREAD

**Issue by Krikooo** [getredash/redash#6676]
### Issue Summary

Redash on docker from master (commit 58bf96c2983f385db1053f14fc4ee3a0a16bd010)

### Steps to Reproduce

1. Create a alert with a custom template and custom variable like this:
<img width="537" alt="image" src="https://github.com/getredash/redash/assets/129737743/ddc5cc24-46e1-44fb-9864-0c57dfb98255">
2. In preview everything is working fine
<img width="713" alt="image" src="https://github.com/getredash/redash/assets/129737743/41497718-08ff-4397-bbec-09da0d276e6c">
3. And trigger the alerts to get the true notification in discord:
<img width="394" alt="image" src="https://github.com/getredash/redash/assets/129737743/b243a2bd-075c-40f2-9f72-31bff91e6c10">

### Technical details:

* Redash Version: master (commit 58bf96c2983f385db1053f14fc4ee3a0a16bd010)
* Browser/OS: Chrome

**Comment by guidopetri** [comment]
Closed with #6721 , thanks for the bug report!
