### ISSUE TITLE
The Redash application does not start using the official script

### ISSUE THREAD

**Issue by collex100** [getredash/redash#6680]
### Issue Summary

3 months ago, I launched the Redash 8 using the official script, everything worked well. 
(It still works. Updated to version 10.)
https://github.com/getredash/setup

I tried to run Redash 8 now using the official script and the application gives an error. 

![Screenshot_87](https://github.com/getredash/redash/assets/11208423/b530a2c4-9426-40cc-bc1e-dec43f973b0f)

**Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.**

All containers are running, there are no errors, but the application does not start. 
![Screenshot_86](https://github.com/getredash/redash/assets/11208423/8a3373de-dc4a-43b1-8798-9ffbd53e24d9)

In general, I tried to run the latest working 10. 1.0 version, but the result was exactly the same. I thought that maybe I should run version 8 and then upgrade to version 10. But version 8 gave the same error. Neither version 8 nor 10 is running. 

Tell me please what the problem might be?
Has anyone encountered this problem recently?

### Technical details:

* Redash Version: 8
* Browser/OS: Ubuntu 20.04
* How did you install Redash:
https://github.com/getredash/setup

**Comment by dvandonkelaar** [comment]
The script ([script.sh](https://github.com/getredash/setup/blob/master/setup.sh)) runs fine for me (Windows 10 with Ubuntu 22.04 in WSL), so all seems to work correctly.
Is the server giving an error in the logs?

**Comment by masayuki038** [comment]
@dvandonkelaar Thanks for your confirmation. It shouldn't have been labeled "Bug". I remove it. Sorry.

**Comment by collex100** [comment]
I checked the script again. The script started and Redash started. I confirm that it is working now. 
So there was some kind of glitch, because I checked by running it five times and then there was a problem. 
There is no problem now. Thanks!
