### ISSUE TITLE
connect oracle 11.2.0.3.0 but python-oracledb thick mode without success

### ISSUE THREAD

**Issue by mayou33** [getredash/redash#6695]
#####Time is 2024/01/06T11:05:23
 

docker pull   redash/redash:preview   

 ##
Reference
 https://github.com/getredash/setup/blob/master/data/docker-compose.yml

https://python-oracledb.readthedocs.io/en/latest/user_guide/installation.html#installation

https://python-oracledb.readthedocs.io/en/latest/user_guide/initialization.html#enablingthick

##
docker exec -it --user=root redash-server /bin/bash
 ##
Copy Oracle Client 12.1.0.2.0 (Basic+sdk+sqlplus)

####
unzip /tmp/12.1.0.2.0/instantclient-basic-linux.x64-12.1.0.2.0.zip -d /usr/local/
unzip /tmp/12.1.0.2.0/instantclient-sdk-linux.x64-12.1.0.2.0.zip -d /usr/local/
unzip /tmp/12.1.0.2.0/instantclient-sqlplus-linux.x64-12.1.0.2.0.zip -d /usr/local/
ln -s /usr/local/instantclient_12_1 /usr/local/instantclient
ln -s /usr/local/instantclient/libclntsh.so.12.1 /usr/local/instantclient/libclntsh.so
ln -s /usr/local/instantclient/sqlplus /usr/bin/sqlplus
apt-get install libaio1  libaio-dev -y

echo "export LD_LIBRARY_PATH=/usr/local/instantclient:\\$LD_LIBRARY_PATH" >> /home/redash/.bashrc
echo "export PATH=/usr/local/instantclient:\\$PATH" >> /home/redash/.bashrc
echo "export ORACLE_HOME=/usr/local/instantclient" >> /home/redash/.bashrc
echo "export NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'" >> /home/redash/.bashrc
echo "export NLS_LANG='AMERICAN_AMERICA.AL32UTF8'" >> /home/redash/.bashrc
echo "export DPI_DEBUG_LEVEL=64" >> /home/redash/.bashrc
source /home/redash/.bashrc
###
 sh -c "echo /usr/local/instantclient > /etc/ld.so.conf.d/oracle-instantclient.conf"
 ldconfig
###
 pip install oracledb==2.0.0 
sed -i '/import oracledb/a\    oracledb.init_oracle_client()' /app/redash/query_runner/oracle.py
![图片](https://github.com/getredash/redash/assets/22804372/8b6b96e1-896d-4c98-ac3c-d127576ef77d)

###
docker restart redash-server
####
But the connection still reports an error
Connection Test Failed:
DPY-3010: connections to this database server version are not supported by python-oracledb in thin mode

![图片](https://github.com/getredash/redash/assets/22804372/b3a0fe3d-92c3-4f9d-988b-99e7ffce87d9)

**Comment by justinclift** [comment]
First things first, what version of Redash are you trying this with? :smile:

**Comment by mayou33** [comment]
docker pull redash/redash:preview

![图片](https://github.com/getredash/redash/assets/22804372/84d9b5ea-6616-4289-8d79-732e9949cab3)

**Comment by justinclift** [comment]
Ahhh, that sounds like you're using a recent version.  I would have expected that to work.

Lets ask our resident Oracle expert, @snickerjp. :smile:

@snickerjp Any idea?

[I'm not sure about the Xmas/New Years holidays situation for @snickerjp though]

**Comment by snickerjp** [comment]
I'll try to verify it with Oracle 11g. Please give me some time.

**Comment by snickerjp** [comment]
I tested it and it works.

## The steps are as follows
- Download docker-compose.yml file
    - https://github.com/getredash/setup/blob/master/data/docker-compose.yml
- Edit docker-compose.yml file
  ~~~diff
  @@ -1,6 +1,6 @@
  version: "2"
  x-redash-service: &redash-service
  -  image: redash/redash:8.0.0.b32245
  +  build:
  +    dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
  ~~~
- Docker build for include Oracle Client 12.1.0.2.0 (Basic+sdk+sqlplus)
  ~~~bash
  $ tree
  .
  ├── Dockerfile
  ├── docker-compose.yml
  └── oracle
      ├── instantclient-basic-linux.x64-12.1.0.2.0.zip
      ├── instantclient-sdk-linux.x64-12.1.0.2.0.zip
      └── instantclient-sqlplus-linux.x64-12.1.0.2.0.zip

  1 directory, 5 files
  ~~~
  - Dockerfile(Enable python-oracledb Thick mode)
    ~~~
    FROM redash/redash:preview AS build

    USER root

    # Oracle instantclient
    COPY oracle /tmp/oracle

    RUN apt-get update \
        && apt-get install -y --no-install-recommends \
            unzip \
            libaio-dev \
        && apt-get clean -y \
        && rm -rf /var/lib/apt/lists/* \
        && for i in /tmp/oracle/*.zip ;do unzip "$i" -d /usr/local/ ;done \
        && mv -v /usr/local/instantclient* /usr/local/instantclient \
        && ln -sv /usr/local/instantclient/sqlplus /usr/bin/sqlplus

    USER redash

    # Create Oracle redash
    FROM redash/redash:preview
    COPY --from=build /usr/local/instantclient /usr/local/instantclient
    COPY --from=build /usr/bin/sqlplus /usr/bin/sqlplus

    ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/instantclient

    # install python-oracledb
    RUN pip install oracledb==2.0.0

    # install pkgs
    USER root
    RUN apt-get update \
        && apt-get install -y --no-install-recommends libaio1 curl \
        && apt-get clean -y \
        && rm -rf /var/lib/apt/lists/*

    USER redash

    # enable python-oracledb thick mode.
    RUN sed -i '/import oracledb/a\\n    oracledb.init_oracle_client()' /app/redash/query_runner/oracle.py

    #Add REDASH ENV to add Oracle Query Runner
    ENV REDASH_ADDITIONAL_QUERY_RUNNERS=redash.query_runner.oracle
    ~~~

- Docker Compose up
  ~~~
  docker compose up -d
  ~~~

- Reference
  - https://github.com/snickerjp/redash_oracle

## Test Results

- python-oracledb version
  ~~~
  redash@c81c8d29e6e4:/app$ pip freeze | grep oracle
  oracledb==2.0.0
  ~~~

- Redash Version, Oracle Database Version.
  <img width="791" alt="redash-oracle11g" src="https://github.com/getredash/redash/assets/1247622/b6aa417c-76fc-46b4-8b60-298af2514b25">

**Comment by snickerjp** [comment]
Probably after editing,
```
docker restart redash-server
```
after editing was not enough work.

I think the steps were correct.

**Comment by mayou33** [comment]
@snickerjp 
 Thanks for your help, based on your Dockerfile. I found that the oracle environment variables were missing from my original method.

 Add REDASH_ADDITIONAL_QUERY_RUNNERS to environment in docker-compose.yml will solve my original problem.
for example
###
services:
    server:
      image: redash/redash:preview
      container_name: redash-server
      restart: always
      ports:
        - 5000:5000
      environment:
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/instantclient
        - PATH=$PATH:/usr/local/instantclient
        - ORACLE_HOME=/usr/local/instantclient
        - NLS_DATE_FORMAT='YYYY-MM-DD HH24:MI:SS'
        - NLS_LANG='AMERICAN_AMERICA.AL32UTF8'
        - REDASH_ADDITIONAL_QUERY_RUNNERS=redash.query_runner.oracle
......
###

I also have a question, if I continue to add client files from other databases, how do I fill in the values in REDASH_ADDITIONAL_QUERY_RUNNERS?

**Comment by snickerjp** [comment]
@mayou33 
REDASH_ADDITIONAL_QUERY_RUNNERS can be found at
https://redash.io/help/open-source/admin-guide/env-vars-settings

Also, the past settings were retained this time.
`ENV REDASH_ADDITIONAL_QUERY_RUNNERS=redash.query_runner.oracle`

The current version (redash/redash:preview) is,
We have verified that there is no difference in behavior without this value present.

**Comment by mayou33** [comment]
Okay, thank you again for your help.

**Comment by mayou33** [comment]
@snickerjp    
Okay, thank you again for your help.
