### ISSUE TITLE
Add script to upgrade re:dash on EC2 instance

### ISSUE THREAD

**Issue by tjwudi** [getredash/redash#670]
We are now using re:dash heavily and would like to update re:dash on EC2 instance from time to time. I wrote a simple script to do that. Before putting it on Pull Request, I would like you guys to see if it is a valid idea to have this script.

The reason why we clone the repo instead of downloading tarball from GitHub is, we can then use it with our internal fork on our internal git server. Otherwise it will just works for GitHub repo.

```
REDASH_HOST=the-redash-host-url
TARBALL_NAME="redash.$USER.$(date +%s).tar.gz"
REDASH_DIR_NAME=${TARBALL_NAME%.tar.gz}

# Clone the code
git clone git@github.com:getredash/redash.git redash-release
cd redash-release

# Compile frontend assets
make deps

# Pack code and distribute to server
tar -zcv -f ../$TARBALL_NAME --exclude="optipng*" --exclude=".git*" --exclude="*.pyc" --exclude="*.pyo" --exclude="venv" --exclude="rd_ui/node_modules" --exclude="rd_ui/dist/bower_components" --exclude="rd_ui/app" *
rsync -a -e "ssh" --rsync-path="sudo -u redash rsync" ../$TARBALL_NAME redash1-uswest1cdevc.dev.yelpcorp.com:/opt/redash

ssh -A $REDASH_HOST bash -c "'
sudo -u redash mkdir /opt/redash/${REDASH_DIR_NAME}
sudo -u redash tar zxvf /opt/redash/${TARBALL_NAME} -C /opt/redash/${REDASH_DIR_NAME}
sudo -u redash rm /opt/redash/${TARBALL_NAME}
'"

echo "Congrats! Your code has been distributed to Re:dash server. You can find it at /opt/redash/${REDASH_DIR_NAME}".
echo "Running database migrations (if any)"


# Run database migrations
ssh -A $REDASH_HOST bash -c "'
cd /opt/redash/${REDASH_DIR_NAME}
sudo -u redash cp ../.env .env
sudo -u redash diff -r migrations/ ../current/migrations/ | awk '{print $4}' | grep 00 --null | xargs -I {} bin/run python migrations/{}
'"

# Switch to new instance
echo "Using new instance"
ssh -A $REDASH_HOST bash -c "'
cd /opt/redash
sudo -u redash rm current
sudo -u redash ln -s ${REDASH_DIR_NAME} current

sudo service redash_supervisord restart
'"

echo "Re:dash upgraded. New source code folder is /opt/redash/${TARBALL_NAME%.tar.gz}"
```

**Comment by tjwudi** [comment]
Please don't do code review here. I will submit PR and discuss the code there (like adding prompt or something else). Just want to have an initial discussion on the feasibility.

**Comment by arikfr** [comment]
I think it's better to separate the build process and the deploy process. For the deploy there is already a Fabric script (referenced in the [docs](http://docs.redash.io/en/latest/upgrade.html)). I'm planning to move the script to be part of the repo, after I modify it to run locally on the re:dash server.

Of course this script can be repurposed to use a custom tarball, instead of downloading one from GitHub.
