### ISSUE TITLE
I want to display a large number of rows in a table using mysql.

### ISSUE THREAD

**Issue by kindamu24005** [getredash/redash#6708]
Thank you for checking my question.

I want to display a large number of rows in a table using mysql.

I have confirmed that a table with 341,651 rows and 34 columns can be displayed.

<img width="1426" alt="スクリーンショット 2024-01-16 16 04 49" src="https://github.com/getredash/redash/assets/107189394/d92cc8d9-1451-4eaa-aadd-92517e97f944">

But when I try to display a table with 900,000 rows, nothing is displayed.

like this picture.
There is "0 rows - runtime" below the photo.

<img width="1432" alt="スクリーンショット 2024-01-16 16 08 07" src="https://github.com/getredash/redash/assets/107189394/0f9f72a1-5209-4b33-8d63-a91ba3414b53">

Please give me some answer to solve this problem.

Maybe there is a table display limit for re:dash by row?

**Comment by myonlylonely** [comment]
@justinclift Is it related to https://github.com/getredash/redash/issues/6706? Because query result is also converted to JSONB?

**Comment by justinclift** [comment]
900 ***thousand*** rows in a web page?

You're extremely likely to hit all kinds of limits if you try to do that.  Generally you'd want to process that result set far more to reduce it down to what you're actually looking for, or turn it into a chart (etc).

**Comment by guidopetri** [comment]
As mentioned above, this isn't something we really support at the moment.
