### ISSUE TITLE
Unsupported OP_QUERY command: connectionStatus. The client driver may require an upgrade

### ISSUE THREAD

**Issue by Adityak4201** [getredash/redash#6728]
I have Mongo v6 DB connected to redash and queries and dashboard connected to that DB. It was working fine till 15th Jan 2024 (last I checked). When I opened the dashboard today, it was giving me the error:

```
Connection Test Failed:
Unsupported OP_QUERY command: connectionStatus. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal
```

None of the queries are running now on Mongo v6. It is also not getting connected to the DB now.

Please review the releases and get this fixed

![image](https://github.com/getredash/redash/assets/72034967/ac1ea87b-f1f3-47c9-940a-a9688743d0e1)
![image](https://github.com/getredash/redash/assets/72034967/6f0cbfd6-b362-4a19-b852-64ec95d37495)

**Comment by justinclift** [comment]
Which version of Redash are you using?

**Comment by Adityak4201** [comment]
@justinclift thanks for the help. Somehow, the redash on the server was downgraded to 8.0 which caused the issue. It has been fixed now.

Just FYI, redash 10.1 supports Mongo v6. Below are the links of the PRs that are related to this feature:

https://github.com/getredash/redash/pull/5970
https://github.com/getredash/redash/pull/6114

**Comment by justinclift** [comment]
> Just FYI, redash 10.1 supports Mongo v6.

Ahhh, must have been me misremembering version numbers then.  No worries, glad you got it solved. :smile:
