### ISSUE TITLE
Add UI Warning/Error for Queries which have Alerts configured

### ISSUE THREAD

**Issue by clearnote01** [getredash/redash#6751]
### Issue Summary

When a query has parameters configured, if they are used as alerts, there is no warning that the alerts won't work. By default my assumption is that whatever default value has been configured in the query configuration can be used. If this is by design that alerts will only run for queries without parameters, it would still be good to prevent users from configuring Alerts on those queries or at least show some warning or error on the UI

### Steps to Reproduce

1. I setup a MongoDB query with params
2. Set alert using that query 

### Technical details:

* Redash Version: master
* Browser/OS: chrome
* How did you install Redash: local-dev-setup

**Comment by eradman** [comment]
This was solved in https://github.com/getredash/redash/pull/6683 by allowing queries with parameters to be scheduled.
There is also a proposal to improve this and solve some edge cases in https://github.com/getredash/redash/pull/6960
