### ISSUE TITLE
Can not upgrade redash/base to redash/preview

### ISSUE THREAD

**Issue by trantrinhquocviet** [getredash/redash#6770]
I'm experiencing difficulties when attempting to upgrade the Redash base image from the stable version to the preview version. The problem appears to be related to the database configuration. Despite following the upgrade process outlined in the documentation, I'm encountering errors that hinder the successful migration of the database schema or data.

I've referred to the documentation provided by Redash, but the issue persists. I've also checked for any specific instructions or troubleshooting steps related to database migration in the preview version, but haven't found any definitive solutions.

Could you please provide guidance or assistance on how to resolve this issue? Any insights or recommendations would be greatly appreciated.

I have a problem when upgrade redash/base image from [stable ](https://hub.docker.com/layers/redash/base/latest/images/sha256-4c819e245317823432a4468705112bda9ccdab35f260cc708a5ab58331c66d2a)version

(link: https://hub.docker.com/layers/redash/base/latest/images/sha256-4c819e245317823432a4468705112bda9ccdab35f260cc708a5ab58331c66d2a)

to redash/review: https://hub.docker.com/r/redash/preview

![image](https://github.com/getredash/redash/assets/26039338/17e3fd1f-6172-4281-b036-9e816b748002)

Have problem at database

ERROR:  function jsonb_typeof(text) does not exist at character 1096
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  SELECT queries.query AS queries_query, queries.updated_at AS queries_updated_at, queries.created_at AS queries_created_at, [queries.id](http://queries.id/) AS queries_id, queries.version AS queries_version, queries.org_id AS queries_org_id, queries.data_source_id AS queries_data_source_id, queries.latest_query_data_id AS queries_latest_query_data_id, [queries.name](http://queries.name/) AS queries_name, queries.description AS queries_description, queries.query_hash AS queries_query_hash, queries.api_key AS queries_api_key, queries.user_id AS queries_user_id, queries.last_modified_by_id AS queries_last_modified_by_id, queries.is_archived AS queries_is_archived, queries.is_draft AS queries_is_draft, queries.schedule AS queries_schedule, queries.schedule_failures AS queries_schedule_failures, queries.options AS queries_options, queries.search_vector AS queries_search_vector, queries.tags AS queries_tags, [query_results_1.id](http://query_results_1.id/) AS query_results_1_id, query_results_1.retrieved_at AS query_results_1_retrieved_at
    FROM queries LEFT OUTER JOIN query_results AS query_results_1 ON [query_results_1.id](http://query_results_1.id/) = queries.latest_query_data_id
    WHERE jsonb_typeof(queries.schedule) != 'null' ORDER BY [queries.id](http://queries.id/)
    
**Yaml file setup**

```x-redash-service: &redash-service
  image: redash/redash:preview
  depends_on:
    - postgres
    - redis
  env_file: /opt/redash/env
  restart: always
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 3
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 1
  redis:
    image: redis:5.0-alpine
    restart: always
  postgres:
    image: postgres:9.6-alpine
    env_file: /opt/redash/env
    volumes:
      - /opt/redash/postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: redash/nginx:latest
    ports:
      - "80:80"
    volumes:
      - /opt/redash/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
    links:
      - server:redash
    restart: always```

**Comment by TeXmeijin** [comment]
+1

**Comment by trantrinhquocviet** [comment]
I provide more information about error: 

```
[2024-02-26 07:23:40,586][PID:38][ERROR][redash.app] Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 298, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_limiter/extension.py", line 1191, in __inner
    R, flask.current_app.ensure_sync(cast(Callable[P, R], obj))(*a, **k)
  File "/app/redash/handlers/authentication.py", line 215, in login
    show_password_login=current_org.get_setting("auth_password_login_enabled"),
  File "/app/redash/models/organizations.py", line 69, in get_setting
    if key in self.settings.get("settings", {}):
AttributeError: 'str' object has no attribute 'get'
```

When i started at local, i init database that is not problem. But i migration from redash/redash to redash/preview.

**Comment by trantrinhquocviet** [comment]
I checked redash/preview schemas with any new tables. This cause make it problem.
How to run script migration schema?

![image](https://github.com/getredash/redash/assets/26039338/f683b85b-e85a-4ba3-8d8c-673d9b75acf9)

**Comment by trantrinhquocviet** [comment]
@eradman

**Comment by eradman** [comment]
Try running

```
docker-compose run --rm server manage db upgrade
```

**Comment by trantrinhquocviet** [comment]
I created success, but some problem with data_sources:

```
[2024-02-27 03:03:07,839][PID:33][ERROR][redash.app] Exception on /api/data_sources [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 489, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_login/utils.py", line 277, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/app/redash/handlers/base.py", line 31, in dispatch_request
    return super(BaseResource, self).dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 604, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/app/redash/permissions.py", line 71, in decorated
    return fn(*args, **kwargs)
  File "/app/redash/handlers/data_sources.py", line 115, in get
    d = ds.to_dict()
  File "/app/redash/models/__init__.py", line 145, in to_dict
    "syntax": self.query_runner.syntax,
  File "/app/redash/models/__init__.py", line 277, in query_runner
    query_runner = get_query_runner(self.type, self.options)
  File "/app/redash/query_runner/__init__.py", line 423, in get_query_runner
    return query_runner_class(configuration)
  File "/app/redash/query_runner/big_query.py", line 103, in __init__
    self.should_annotate_query = configuration["useQueryAnnotation"]
  File "/app/redash/utils/configuration.py", line 96, in __getitem__
    raise KeyError(item)
KeyError: 'useQueryAnnotation'
```

**I can not connect to data source:**
![image](https://github.com/getredash/redash/assets/26039338/cda1edd5-1ee3-4fc8-a9a4-929a7f0a85dc)

**Comment by eradman** [comment]
What data source are you using? Are you able to create a second data source of the same type?

**Comment by trantrinhquocviet** [comment]
> What data source are you using? Are you able to create a second data source of the same type?

Yes, I understand, but i can not setup data source.

![image](https://github.com/getredash/redash/assets/26039338/cddc5473-2a35-4969-8c15-76da309620c7)

**Comment by trantrinhquocviet** [comment]
In query, can not load data source.

![image](https://github.com/getredash/redash/assets/26039338/ef02882d-33d7-481e-8e42-95a513db0760)

**Comment by eradman** [comment]
If you can rebuild from source, I'd be curious to see if this fixes the problem

```diff
--- a/redash/query_runner/big_query.py
+++ b/redash/query_runner/big_query.py
@@ -100,7 +100,7 @@ class BigQuery(BaseQueryRunner):

     def __init__(self, configuration):
         super().__init__(configuration)
-        self.should_annotate_query = configuration["useQueryAnnotation"]
+        self.should_annotate_query = configuration.get("useQueryAnnotation", False)

     @classmethod
     def enabled(cls):
```

**Comment by trantrinhquocviet** [comment]
@eradman, 

I fixed this issue by deleting BigQuery in table user_groups vs data source. The issue is fixed.

But, I think you should push the code above to the new version to actually solve the issue.

**Comment by eradman** [comment]
Fix merged. Thanks also @justinclift

**Comment by justinclift** [comment]
@trantrinhquocviet Would you be ok to try the new `redash/preview` image, and confirm it works for you like we're expecting? :smile:
