### ISSUE TITLE
date parameter configuration in redash self hosting.

### ISSUE THREAD

**Issue by srikanthgarimilla1996** [getredash/redash#6795]
query =... wl.workedondate BETWEEN  {{ startDate }} AND {{ endDate }}
![image](https://github.com/getredash/redash/assets/161418213/1e360862-a668-4e59-a698-b6029ce231e8)

I am using postgres as my data source. How can i pass the dates in this format?
![image](https://github.com/getredash/redash/assets/161418213/044b07f9-e51f-4b30-9f14-b4a12ee2bfb7)

In pgadmin, I am passing the dates in the below manner to get data. How can i do this using redash dropdowns:
 BETWEEN '2023-06-01' AND '2023-06-30'

**Comment by gaecoli** [comment]
You should between {{ date.start }} and {{ date.end }}.
The date is your date column.

**Comment by gaecoli** [comment]
<img width="228" alt="image" src="https://github.com/getredash/redash/assets/46274612/e7e8ac75-176e-4ca7-b2ab-ec82259d49a8">
<img width="234" alt="image" src="https://github.com/getredash/redash/assets/46274612/93777530-5f17-4c75-9a4b-43b79322d3ac">

**Comment by srikanthgarimilla1996** [comment]
Thanks @gaecoli . This one worked !!
