### ISSUE TITLE
config request - cleanup_query_results

### ISSUE THREAD

**Issue by gabrielcrowdtilt** [getredash/redash#683]
The cleanup cron is great because it reduces size of redash database. This also allows for smaller quicker backups of its data. If possible, someone can add in a little configuration?

In tasks.py, make it configurable to set a value instead of hardcoded 100. For example, I might want 1000 here:
```
    unused_query_results = models.QueryResult.unused().limit(100)
```

And in models.py, make it configurable on date range instead of hardcoded week_ago. For example, I might only want 1 day here:

```
 week_ago = datetime.datetime.now() - datetime.timedelta(days=7)
```

**Comment by arikfr** [comment]
Implemented in #685. It will soon be added to the 0.8.3 release.
