### ISSUE TITLE
numberFormat and thousandsSep

### ISSUE THREAD

**Issue by mfilin** [getredash/redash#6843]
Hello! Can we change the opt in environment that is call "thousandsSep" (default its ","). For me need " " (backspase)...
I founded in /src **Utilities.js** where is a source code for format in pivotTable...thats it:

var addSeparators = function addSeparators(nStr, thousandsSep, decimalSep) {
  var x = String(nStr).split('.');
  var x1 = x[0];
  var x2 = x.length > 1 ? decimalSep + x[1] : '';
  var rgx = /(\d+)(\d{3})/;
  while (rgx.test(x1)) {
    x1 = x1.replace(rgx, '$1' + thousandsSep + '$2');
  }
  return x1 + x2;
};

Etc thousandsSep come from any opts... How can I change it without rebild all frontend of redash

**Comment by mfilin** [comment]
any ideas ?

**Comment by eradman** [comment]
You can update the default number format by connecting to the Redash database

```sql
UPDATE organizations
SET settings = jsonb_set(settings::jsonb, '{settings,float_format}', '"0.0"', true);

UPDATE organizations
SET settings = jsonb_set(settings::jsonb, '{settings,integer_format}', '"0"', true);
```

To view all organization settings

```sql
SELECT jsonb_pretty(settings::jsonb)
FROM organizations;
```

**Comment by eradman** [comment]
> any ideas ?

Please do not ping tickets, there is no corporation supporting Redash, only individuals who check in to see if they can help.

**Comment by eradman** [comment]
@mfilin did this solution work for you?

**Comment by mfilin** [comment]
no, this solution does not work
on this moment i am edit this js (Utilities.js) by adding " " to default value of thouthands sep...

**Comment by eradman** [comment]
What do your settings look like?

```
SELECT jsonb_pretty(settings) FROM organizations;
```
