### ISSUE TITLE
How to add counter visualization clickable its is possible ?

### ISSUE THREAD

**Issue by annuusom** [getredash/redash#6859]
We use GitHub only for bug reports 🐛

Anything else should be a discussion: https://github.com/getredash/redash/discussions/ 👫

🚨For support, help & questions use https://github.com/getredash/redash/discussions/categories/q-a
💡For feature requests & ideas use https://github.com/getredash/redash/discussions/categories/ideas

Alternatively, check out these resources below. Thanks! 😁.

- [Discussions](https://github.com/getredash/redash/discussions/)
- [Knowledge Base](https://redash.io/help)

**Comment by annuusom** [comment]
please suggest

**Comment by justinclift** [comment]
Closing this issue in favour of #6860.
