### ISSUE TITLE
Front end data type display exception

### ISSUE THREAD

**Issue by wangmiao1002** [getredash/redash#6869]
### Issue Summary

Using the Presto engine to query data exceeding 18 bits returns an exception
### Steps to Reproduce
execute：
select 131813598772907141
return：
131,813,598,772,907,136

### Technical details:

* Redash Version: 10.1.0
* Browser/OS: 
* How did you install Redash: docker

![image](https://github.com/getredash/redash/assets/38424929/5c21e58f-20ea-46bb-89e9-912d13a83eac)

**Comment by mirkan1** [comment]
I think this is expected behaviour for readability

**Comment by wangmiao1002** [comment]
> I think this is expected behaviour for readability

Why is it like this? In my data warehouse, some data subtypes are set to bigint20, and the data displayed when using redash queries is incorrect.

**Comment by justinclift** [comment]
This sounds like another case of this: https://github.com/getredash/redash/issues/6159

@eradman ?

**Comment by justinclift** [comment]
@wangmiao1002 You're accidentally misreading the problem report. :wink:

They're not pointing out the `,` characters being added, they're instead pointing out that the number has changed.

**Comment by wangmiao1002** [comment]
My personal understanding is that the front-end is only used as a display of data. Can we convert this int type to a string to solve this problem.
