### ISSUE TITLE
Redash adds `/redash` prefix if a string starts with `/api`

### ISSUE THREAD

**Issue by marcinbarczynski** [getredash/redash#6898]
### Steps to Reproduce

1. Create the following query `SELECT '/api'`.
2. Run it.

![image](https://github.com/getredash/redash/assets/8135152/5314468d-d576-46dc-a56a-aff5e0027c93)

### Technical details:

* Redash Version: 24.03
* Browser/OS:
* How did you install Redash:

**Comment by marcinbarczynski** [comment]
I'm sorry, it's a specific tweak in my Redash instance.

**Comment by justinclift** [comment]
No worries, glad you got it figured out. :smile:
