### ISSUE TITLE
Charts: when having many series the legend is being cut off and not scrollable

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#692]

**Comment by shyamgopal** [comment]
![screen shot 2015-12-11 at 12 26 17 pm](https://cloud.githubusercontent.com/assets/11750143/11738915/f3c270d6-a00c-11e5-8466-2dece7ae1ff6.png)

**Comment by alonho** [comment]
I created a PR with a fix that makes the entire chart div scrollable. It's not perfect but it works.

**Comment by arikfr** [comment]
@shyamgopal the last 0.9.0 build (1213) has the fix @alonho mentioned. Please let us know if it fixed the issue you were having.

**Comment by shyamgopal** [comment]
@arikfr  , I am having the same problem with 0.9.0b1216. Interestingly, the scrollbars don't show up in visualisation widget. However they do showup in chart part of the query ! Please refer to the following two screenshots:

<img width="1156" alt="screen shot 2015-12-13 at 5 28 29 pm" src="https://cloud.githubusercontent.com/assets/11750143/11766938/06b2031c-a1c2-11e5-9dbb-ed5df5b6e6ae.png">
<img width="911" alt="screen shot 2015-12-13 at 5 29 01 pm" src="https://cloud.githubusercontent.com/assets/11750143/11766939/0ecd0308-a1c2-11e5-82c8-29c4638ffaee.png">

**Comment by alonho** [comment]
Nice catch @shyamgopal. I think I finally fixed it.
