### ISSUE TITLE
Charts: in some cases buttons are blocked by data

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#693]
(when there was too much data, then, apart from the legend, even all the buttons (like save/zoom/pan etc) also disappeared behind the right edge of the graph.)

**Comment by alonho** [comment]
Did you manage to reproduce it on the demo instance?

**Comment by arikfr** [comment]
Didn't try yet. Although this is a similar case to having percent stacking enabled, and then it doesn't overlap. Right?

@shyamgopal can you give an example?

**Comment by shyamgopal** [comment]
This screenshot was taken on 0.9.0+b1206. Now, some of the legend and all buttons  are visible, however the graph looks cramped. @alonho , is it possible to have the legend below the graph (as in Highcharts graph) ? Will that help, in case of long "series" ("Group by") names ?

![screen shot 2015-12-11 at 12 33 50 pm](https://cloud.githubusercontent.com/assets/11750143/11738887/c2b9f612-a00c-11e5-82b6-8ea81e9d81c7.png)

**Comment by alonho** [comment]
Unfortunately plotly doesn't such a configuration.. Meanwhile, you have several options:
1. Hide the legend (there's a new checkbox, not sure you got it in your release), the series name is still available on hover.
2. Edit the name of the series in the table.
3. Shorten the names in the query.

**Comment by shyamgopal** [comment]
1) Yes, according to this link: https://github.com/plotly/plotly.js/issues/53 , there is no way to put the legends below. (They can be put below, but they will still appear one legend below another, instead of one legend next to another legend; as in Highcharts.)
2) Hover doesn't cut it because on hover, legends in the hover are shortened.
3) Thanks !

**Comment by shyamgopal** [comment]
It's weird. My colleagues are still having this problem in 090b1225. But I dont seem to have the same problem. Same os, browser. Scroll-bar is shown, but all legends and buttons are swept beyond the right side of the visualisation widget. All this even after clearing the browser cache.
<img width="1157" alt="screen shot 2015-12-14 at 12 59 45 pm" src="https://cloud.githubusercontent.com/assets/11750143/11780534/9c26c11e-a288-11e5-86c5-20169a18795e.png">

![screen shot 2015-12-14 at 12 58 34 pm](https://cloud.githubusercontent.com/assets/11750143/11780512/7b4e557e-a288-11e5-99fe-b4524568fc96.png)

**Comment by shyamgopal** [comment]
Btw, if this helps you:  Initially when the visualisation widget is loaded, it shows both, horizontal scroll bar as well as vertical scroll bar. But once the page is fully loaded, the horizontal scroll bar disappears, and the legend and buttons disappear behind the right edge of the visualisation widget.

**Comment by shyamgopal** [comment]
Sorry, one more addendum: The buttons are visible. But the legend disappears behind right edge.

**Comment by arikfr** [comment]
@shyamgopal but can't you scroll to see the full legend? Like here: http://demo.redash.io/queries/516#716 ?

**Comment by shyamgopal** [comment]
@arikfr , upgraded to 0.9.0+b1247, this issue seems to be fixed. 
1) Legend is scrollable and 
2) Legend does NOT disappear over the right edge of the visualisation widget.

**Comment by shyamgopal** [comment]
@arikfr , upgraded to 0.9.0+b1247, this issue seems to be fixed. 
1) Legend is scrollable and 
2) Legend does NOT disappear over the right edge of the visualisation widget.
3) Thanks for the fix !!

**Comment by shyamgopal** [comment]
1) Works in "Incognito mode" of Chrome.
2) Legend still disappears behind right edge of the visualisation widget in "Private Window" of Firefox.

**Comment by shyamgopal** [comment]
This issue seems to be resolved as of 0.9.0.b1274

**Comment by arikfr** [comment]
Great. :+1: Closing it now.
