### ISSUE TITLE
How to deploy services through multiple instances

### ISSUE THREAD

**Issue by wangmiao1002** [getredash/redash#6932]
Hello ,I used this configuration to run multiple pod's redash services：
scheduled_worker
server
adhoc_worker
scheduler
redash_woker
https://github.com/getredash/setup/blob/master/data/compose.yaml
version：10.1.0

When users download large files, the server pod may experience lag and affect usage, I have a few questions that I would like to ask for advice

1.Can I limit the number of download lines for users through configuration?
2.Can we only deploy multiple server pods to achieve high availability？
3.Will the scheduled queries set in the system run multiple times when multiple instances of pods are deployed as mentioned above？

**Comment by wangmiao1002** [comment]
> hey @wangmiao1002 compose is not good for HA and High Load setup. you can either use helm chart or if still want to deploy on instances, it's better to run server and workers separately. where do you host your setup?

Hello, I am currently using k8s. The components deployed by Pod are similar to Helm Chart, but each pod is a singleton. Can multiple server pods be started to achieve Ui's load? @AndrewChubatiuk

**Comment by wangmiao1002** [comment]
> > hey @wangmiao1002 compose is not good for HA and High Load setup. you can either use helm chart or if still want to deploy on instances, it's better to run server and workers separately. where do you host your setup?
> 
> Hello, I am currently using Kubernetes. The components deployed by Pod are similar to Helm Chart, but each pod is a singleton. Can multiple server pods be started to achieve Ui's load? @AndrewChubatiuk

**Comment by AndrewChubatiuk** [comment]
what do you mean by singleton? each pod contains scheduler, worker and server?

**Comment by wangmiao1002** [comment]
> what do you mean by singleton? each pod contains scheduler, worker and server?

Only one service was started in a pod, and each service only started one pod. If a service encounters an exception, it will become unavailable

**Comment by dspv** [comment]
I'm making a HA production-grade Redash deployment on AWS with ECS Fargate. I'll post when done

**Comment by wangmiao1002** [comment]
After upgrading the rq schedule to 0.10.0, each service started two pods to implement ha deployment
