### ISSUE TITLE
Error running query: failed communicating with server. Please check your Internet connection and try again.

### ISSUE THREAD

**Issue by eradman** [getredash/redash#6936]
### Issue Summary

This occurs on Redash builds after April 8, 2024. I have not spent the time to bisect the commit that introduced the problem but I have confirmed that this issue does not occur at commit 24dec192eed8c95560ef20f6765d96c67a5bdbbf.

### Steps to Reproduce

1. Build and run Redash from source
2. Create a PostgreSQL data source
3. Create a new query and run it several times

### Related 

https://github.com/getredash/redash/pull/6876

**Comment by AndrewChubatiuk** [comment]
was able to reproduce it, but not with repetitive run actions, but with sql query, which contains an error.
will create a PR with a fix soon
