### ISSUE TITLE
Introduction of VTable - Collaboration Opportunity

### ISSUE THREAD

**Issue by fangsmile** [getredash/redash#6947]
Dear Redash Team,

I hope this message finds you well. My name is fangfang, and I represent a team [VisActor](https://github.com/VisActor) that has developed a high-performance canvas-based table component called [VTable](https://github.com/VisActor/VTable). I am reaching out to you today to introduce VTable and explore potential collaboration opportunities with Redash.

VTable is designed to provide a powerful and efficient solution for displaying and interacting with tabular data. Built on canvas technology, it offers exceptional performance, allowing for seamless rendering and manipulation of large datasets. The component also provides a wide range of features, including sorting, filtering, grouping, and advanced cell customization.

After reviewing Redash and its capabilities, we believe that integrating VTable into the Redash platform could greatly enhance the data visualization and exploration experience. Our goal is to contribute VTable as an open-source component, enabling Redash users to leverage its performance and feature set within the Redash ecosystem.

We would love to discuss the possibility of collaboration further and explore how VTable can align with Redash's vision. We are open to working closely with your team to integrate VTable smoothly and ensure it meets the high standards and requirements of the Redash community.

I would be grateful if we could schedule a brief call or voice meeting to discuss the potential collaboration in more detail. Please let me know a convenient time for you, and I will be happy to accommodate it.

Thank you for your time and consideration. We look forward to the opportunity to contribute to Redash and empower users with our VTable component.

**Comment by justinclift** [comment]
Hmmm, although this *sounds* very spammy, it *might* be worth looking at.

That being said, @fangsmile is clearly approaching multiple projects (ie [echarts as well](https://github.com/apache/echarts/issues/19894)).

So it seems like they're more just fishing for interest rather than being familiar with Redash and knowing it would be a good fit.

**Comment by gaecoli** [comment]
> Hmmm, although this _sounds_ very spammy, it _might_ be worth looking at.
> 
> That being said, @fangsmile is clearly approaching multiple projects (ie [echarts as well](https://github.com/apache/echarts/issues/19894)).
> 
> So it seems like they're more just fishing for interest rather than being familiar with Redash and knowing it would be a good fit.

Import a new chart library is a very large workload. We also need to consider how to build new data struct for the new chart library, so these need to be considered. 
However, I would like to say that unless complex reports are introduced, we should not consider introducing a new chart library for the time being.

**Comment by justinclift** [comment]
@gaecoli Cool.  Sounds like we'd better skip this opportunity then, at least for now. :smile:
