### ISSUE TITLE
Failure to start redash with a local docker install (InFailedSqlTransaction)

### ISSUE THREAD

**Issue by stephendwolff** [getredash/redash#6973]
### Issue Summary

I tried following the developer set up instructions here: 

 - https://github.com/getredash/redash/wiki/Local-development-setup

I did this on an M2 Macbookpro and an Ubuntu 20.04LTS virtual machine.

Bug is that the WSGI app fails to start when trying to fetch the initial "Organisation" with `g.org = Organization.get_by_slug(slug)` (File "/app/redash/authentication/org_resolving.py", line 18, in _get_current_org)

SQLAlchemy returns this error:

```
sqlalchemy.exc.InternalError: (psycopg2.errors.InFailedSqlTransaction) current transaction is aborted, commands ignored until end of transaction block

[SQL: SELECT organizations.updated_at AS organizations_updated_at, organizations.created_at AS organizations_created_at, organizations.id AS organizations_id, organizations.name AS organizations_name, organizations.slug AS organizations_slug, organizations.settings AS organizations_settings
FROM organizations
WHERE organizations.slug = %(slug_1)s
LIMIT %(param_1)s]
[parameters: {'slug_1': 'default', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/2j85)
```

**Comment by stephendwolff** [comment]
I have investigated a bit further, and there are no tables in the postgress database, so it appears that no database migrations have run.

**Comment by stephendwolff** [comment]
and have fixed my issue i think:

`make create_database`

was what was needed to get past this issue

**Comment by justinclift** [comment]
Oh, that's unexpected.  The database initialisation step is supposed to be automatically done these days when it's needed.  That was a recent development though.

Hmmm.  I wonder... we did a rollback of some code over the last few days, so maybe the automatic-database-initialisation thing has been caught up in that somehow?  Will need to take a look at that later on and check.
