### ISSUE TITLE
Typo error in message 

### ISSUE THREAD

**Issue by mdirfan40** [getredash/redash#6978]
I found typo error and lack clarity  in  message  

### Steps to Reproduce

1. Go to file edash/tasks/queries/execution.py line number 58

![Screenshot 2024-05-18 at 12 11 22 PM](https://github.com/getredash/redash/assets/28144895/faaf7744-45a1-4ba6-9027-a9d8557e284f)

**Comment by justinclift** [comment]
Thanks, that's definitely a typo.  I'll make a PR to fix that shortly. :smile:

**Comment by justinclift** [comment]
@mdirfan40 That typo has been fixed.  Thanks for pointing it out. :smile:

**Comment by mdirfan40** [comment]
> @mdirfan40 That typo has been fixed. Thanks for pointing it out. 😄

My pleasure @justinclift 🎊

**Comment by mdirfan40** [comment]
Also I created a PR fix #6409

**Comment by lucydodo** [comment]
This issue apperas to be resolved, so I'm closing the issue.
