### ISSUE TITLE
Chart doesn't show values

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#6996]
### Issue Summary

Chart values always equals 0 on hover.

### Steps to Reproduce

1. Run SQL query:
```
SELECT 5 as atc_count, 7 as qty_users
UNION ALL SELECT 8,1
UNION ALL SELECT 1,290
UNION ALL SELECT 4,11
UNION ALL SELECT 0,763
UNION ALL SELECT 7,1
UNION ALL SELECT 3,25
UNION ALL SELECT 6,4
UNION ALL SELECT 2,68
```
2. Build any chart (i.e. bar) with atc_count on X, qty_users on Y
3. Move pointer to the second bar (X=1)
4. See value = 0

<img width="756" alt="redash_screen" src="https://github.com/getredash/redash/assets/7091907/d0de8687-7753-42fd-a97a-e4e22854ea50">

### Technical details:

* Redash Version: ec051a89398a0c2483ed56a4773509af15bc03f4
* Browser/OS: Chrome 125 / Windows 11
* How did you install Redash: Docker compose (image built from source)

**Comment by eradman** [comment]
@denisov-vlad can you confirm that this problem is resolved in the latest checkout?
