### ISSUE TITLE
ElasticSearch fails on empty Auth/unknown types

### ISSUE THREAD

**Issue by alexanderlz** [getredash/redash#704]
If trying to save ES datasource without auth details it "fails" to save (it saves in the DB, but the ui get's "failed" message), and the datasources (and the whole redash) becomes unusable.

- when ES datasource encounters datatype which is not in the typelist - it throws an exception

**Comment by arikfr** [comment]
Resolved in #680 .

**Comment by sandguardian** [comment]
Hi,

What should I have to input in elasticsearch datasource form?
Elasticsearch is on x.x.x.x:9200 and there is no authentication enabled.

But when I input ip address with/without port in baseurl, test connection is failed.

**Comment by sandguardian** [comment]
@arikfr Any idea on this?
