### ISSUE TITLE
Contents of requirements.txt

### ISSUE THREAD

**Issue by maclynn147** [getredash/redash#7046]
what are the contents of requirements.txt,  requirements_dev.txt and requirements_ds.txt as none of these files are available in your repos

**Comment by lucydodo** [comment]
You can refer to the [pyproject.toml](https://github.com/getredash/redash/blob/master/pyproject.toml) file instead.

**Comment by lucydodo** [comment]
I'm closing this issue because I haven't hear back from author in a long time,
but you can always reopen it later and leave a comment.

**Comment by icoco** [comment]
issue is  the online document: https://www.restack.io/docs/redash-knowledge-redash-backend-insights#Setting_Up_a_Redash_Development_Environment

not been update, it show 
```
Backend Setup
Ensure PostgreSQL and Redis are running.
Install Python dependencies: pip install -r requirements.txt.
Create a .env file with necessary environment variables.


```

but seem the 'requirements.txt' was discard

**Comment by justinclift** [comment]
Ahhh, we should really redirect that page to our wiki which is what we've been using for developer documentation with the relaunched Redash project:

https://github.com/getredash/redash/wiki/

If you're wanting to set up a Redash development environment, then any of the "Local development setup" pages there (ie for Debian, macOS, or Ubuntu) should work properly without any issues. :smile:

**Comment by icoco** [comment]
I follow it 'https://www.restack.io/docs/redash-knowledge-redash-without-docker-setup'

first, I face the problem failed create test connection, after struggle, it solve but face 'Refresh Schema failed' issue now 

maybe my some step not correct,

**Comment by icoco** [comment]
Thanks for reply, I did the test eg:  yarn cypress open > /dev/null 2>&1

it do success,  unit test is fine. 

my question is : 
failed start the instance without docker support, my steps bellows:

1) start redis ( of course, this via docker)
2) python3 manage.py runserver --debugger --reload -h 0.0.0.0 -p 5001 
3) watchmedo auto-restart --directory=./redash/ --pattern=*.py --recursive -- ./manage.py rq worker queries,celery,schemas,default,periodic

open browser with address : http://localhost:5001/queries/new

failed Refresh Schema

**Comment by icoco** [comment]
> I follow it 'https://www.restack.io/docs/redash-knowledge-redash-without-docker-setup'
> 
> first, I face the problem failed create test connection, after struggle, it solve but face 'Refresh Schema failed' issue now
> 
> maybe my some step not correct,

it is out date
