### ISSUE TITLE
Deleting and re-adding widgets to a dashboard breaks it

### ISSUE THREAD

**Issue by jcox92** [getredash/redash#708]
There's a specific set of steps that has messed up some of our users' dashboards:

1. Create a new dashboard
2. Add multiple widgets to it.
3. Remove all those widgets from the dashboard
4. Re-add some widgets
5. Click the "Edit Dashboard (Name/Layout)" button
6. Click Save without changing anything.
7. Refresh the page

This makes none of the widgets appear and causes the "Layout" array in the admin panel to contain one or more "null" values (depending on how many widgets you added/deleted):
![image](https://cloud.githubusercontent.com/assets/844493/11826038/76c749fa-a348-11e5-9f46-bbae43c4b6f6.png)

The only way to recover from this state is to manually delete the "null" values through the admin interface.

This is on re:dash version 0.8.2

**Comment by arikfr** [comment]
**Thanks!** I've been trying to find the steps to reproduce this issue for such a long time.

Expect a fix in v0.9.0.

**Comment by arikfr** [comment]
@jcox92 I fixed it in #716. Should I also add a migration that fixes the already broken dashboards, or it's not necessary?

**Comment by jcox92** [comment]
@arikfr Probably not necessary unless other people are looking for that.

**Comment by arikfr** [comment]
Cool, merged as is. It will be part of the 0.9.0 release.

**Comment by karankurani** [comment]
The same exact situation happened again on the current release - I had to edit the db record on the instance to bring it back. Had to remove the null value. 

Version - 0.11.1.b2095
