### ISSUE TITLE
Queries not refreshing; possibly no background processes running (v10)

### ISSUE THREAD

**Issue by jonahgreenthal** [getredash/redash#7102]
Please see [this discussion](https://github.com/getredash/redash/discussions/7074). It seems like a bug to me. Any support is appreciated.

**Comment by eradman** [comment]
Does this work if you switch to a release candidate, such as `redash/preview:24.08.0-dev`?

This may have been solved in https://github.com/getredash/redash/pull/6683

**Comment by jonahgreenthal** [comment]
I gave up on that entire Redash instance and reinstalled from scratch. It seems to be working now on 10.1.0.

**Comment by justinclift** [comment]
No worries.  We might as well close this issue then, as it'll be impossible to diagnose without a broken instance to prod.  And we have a tonne of other issues to look at anyway. :wink:

**Comment by jonahgreenthal** [comment]
Understandable. Thanks for trying, even if belatedly. I know there's a lot of tech debt here. And I think you know this, but there's also a _ton_ of room for improved documentation, especially for people who aren't really familiar with Docker and other aspects of the Redash architecture, and around the upgrade and migration processes. I think there's a decent chance I could have solved this in place with better documentation.

**Comment by justinclift** [comment]
Yeah, you're definitely right about better documentation being useful. :smile:
