### ISSUE TITLE
Feature Request: Store past Query results for time series analysis

### ISSUE THREAD

**Issue by jeffscott2** [getredash/redash#712]
I'm not sure if this already exists and I'm just not seeing it, sorry if that's the case.  

It would be nice to have redash store the results of queries (perhaps only the first row of a result if need be- that would still work for the timeseries analysis I'd like to see) along with the timestamp of when the query ran.  The use case I'm thinking of is to monitor the number of errors in a table over time.  Logging something fluid like a queue length would also be nice.

To some degree this starts encroaching on nagios type territory, and maybe that's not where you want to go.  But with how easy this gui is to create new queries & alerts, with this one feature redash would really fill a gap in our data monitoring.  Thanks for considering it.

Jeff

**Comment by arikfr** [comment]
Not sure why you closed it, but just wanted to mention that re:dash does store past results. It just that there is no UI for it and really old results are deleted.
