### ISSUE TITLE
Vertical scroll in query results is broken

### ISSUE THREAD

**Issue by denisov-vlad** [getredash/redash#7127]
### Issue Summary

Currently, on the latest commit we cannot scroll down in query results.

### Steps to Reproduce

1. Run query with more than 25 rows in result
2. Save it and try to scroll down

Any other info e.g. Why do you consider this to be a bug? What did you expect to happen instead?

### Technical details:

* Redash Version: #[58a7438](https://github.com/getredash/redash/commit/58a7438cc8054f603f5b061c9864f7855c86496a)
* Browser/OS: Chrome 127.0.6533.120 / Windows 11
* How did you install Redash: self-hosted via docker-compose

**Comment by thiborgesnvs** [comment]
We are facing the same problem 

On developers tool we can see the  overflow-x  frame is being showed as hidden

If you manually change this option on developer tool on chrome the scroll down will appear 

I have no idea how to fix on the code

**Comment by justinclift** [comment]
Ouch, that doesn't sound good at all.

@denisov-vlad It's possible my update of rapidjson broke it yesterday *somehow*, though that's kind of surprising.  Any idea if the commit on `master` before yesterday's one has the same problem?

@thiborgesnvs Which version of Redash are you using?

**Comment by denisov-vlad** [comment]
I suppose this PR has broken it: https://github.com/getredash/redash/pull/7019

We switched to version before that, and everything works fine. Also, that PR was the reason why I decided to update Redash :)

**Comment by justinclift** [comment]
Thanks @denisov-vlad. :smile:

**Comment by eradman** [comment]
I am working on a fix for this regression, I will put up a pull request for review tomorrow.

**Comment by justinclift** [comment]
Thanks heaps @eradman. :smile:

**Comment by justinclift** [comment]
@denisov-vlad We've just merged @eradman's PR which reverts that commit.  That should at least solve the immediate problem and we can follow up later for a better approach to improve fixed column layouts. :smile:
