### ISSUE TITLE
Claims that mailserver is not configured, however test-mail works fine. 

### ISSUE THREAD

**Issue by gr4ssi** [getredash/redash#7129]
### Issue Summary
Redash says, mailserver not configured, also test email works great and it is configured.

### Steps to Reproduce

1. Installed a fresh redash instance on Ubuntu 24 latest in our local network on 192.168.115.69.
2. Set the /opt/redash/env to 

REDASH_HOST=https://192.168.115.69
REDASH_MAIL_SERVER=192.168.115.254
REDASH_MAIL_PORT=25
REDASH_MAIL_USE_TLS=YES
REDASH_MAIL_DEFAULT_SENDER=redash@our.maildomain.com

3. Restartet the linux host and tested sending with 
docker compose run --rm server manage send_test_mail  -> Mail arrives fine, meaning my mailserver works.

4. Trying to invite a new user via email:
Now, on user-invite, the website tells me that my mailserver is not set up. :-(

![grafik](https://github.com/user-attachments/assets/e680f396-7e1e-4c7d-ac5e-700a21487fe2)

I consider this a bug since the test-mail works and the redash server thinks it doesn't.

### Technical details:

* Redash Version: latest as of the setup install script 21. August 2024
* Browser/OS: Firefox latest
* How did you install Redash:
 - fancy setup script that worked okay.

**Comment by justinclift** [comment]
Yeah, that sounds like a bug we should look into.
