### ISSUE TITLE
Add support for default values for query parameters

### ISSUE THREAD

**Issue by superstrong** [getredash/redash#717]
[Feature Request]

While creating or editing a SQL query containing URL parameters, the result breaks unless you put query values in the URL. Having default values would help.

This builds on https://github.com/getredash/redash/issues/285

To keep UI changes to a minimum, this could be done in the query itself, like this:

```SQL
SELECT ...
FROM ...
WHERE date >= NOW() - INTERVAL '{{days,28}}' days
   AND city = '{{city,New York City}}'
```

... or in a separate text area below the query where the user defines the default values for each query parameter, like this:

```
days = 28
city = New York City
```

**Comment by arikfr** [comment]
Parameters enhancement is high on the priority list and the plan is to add a UI for value input, but also UI to define the parameter -- its type (date, dropdown, number, etc) and default value.

I have a branch where I started working on this, but other things took over...

**Comment by toyama0919** [comment]
duplicate issue.
https://github.com/getredash/redash/issues/583

**Comment by arikfr** [comment]
(I've updated #583 and closing this one)
