### ISSUE TITLE
Add the option to refresh a query more frequently

### ISSUE THREAD

**Issue by superstrong** [getredash/redash#718]
[Feature Request]

Currently a query can be refreshed once/day at a specified time. For some queries, especially those tied to alerts, monitoring more frequently (e.g., hourly) would make them more useful.

**Comment by arikfr** [comment]
Why not use the refresh interval (like "Every 1 hour") option then?

**Comment by superstrong** [comment]
Is that something that's configured on the admin side? When I use it, I just see this:

![Refresh Interval](https://cloud.githubusercontent.com/assets/433202/11957988/024e5334-a893-11e5-928e-32ca0f15a190.png)

**Comment by arikfr** [comment]
When you select the radio button next to "No Refresh", you can select other options there.

![image](https://cloud.githubusercontent.com/assets/71468/11958023/fa920416-a8cd-11e5-97d9-e3fa634bc89f.png)

**Comment by superstrong** [comment]
Wow, months of using it and it never occurred to me that "No Refresh" was a dropdown.

**Comment by arikfr** [comment]
I wonder if I should split it to 3 options: "No Refresh", interval, specific hour?

**Comment by superstrong** [comment]
Maybe! I don't think any of us using it knew the interval could be something other than a specific hour.
