### ISSUE TITLE
Scrolling not possible in results anymore

### ISSUE THREAD

**Issue by zpelechova** [getredash/redash#7185]
### Issue Summary
On iOS and chrome when I have a query with 25 results, I can see first 8 but I cannot scroll down to see other results. Checked with a colleague (Windows, Chrome), didnt work for her either.

### Steps to Reproduce

1. This is the first step: create any query which returns lets say 100 result at least.
2. Try scrolling down in the results.

I consider it a bug as 1. I cannot get acces to the rest of the results (if I dont download it) and 2. it worked before.

### Technical details:
on cloud

**Comment by justinclift** [comment]
Ahhh.  Which version of Redash is this happening with.  I could have sworn this bug was fixed a few weeks ago, so should be fixed in the latest monthly tag.

**Comment by robinedwards** [comment]
We are also experiencing the same issue on `redash/preview:24.08.1-dev`

**Comment by justinclift** [comment]
@robinedwards If you update to the most recent build, it should be fixed. :smile:

**Comment by eradman** [comment]
Indeed, the change that caused this issue was reverted on 2024-08-23 (79a4c4c9c9841a75d20c68d5eb19bc9e3ce3b1d4), so this is fixed in 24.09 and later
