### ISSUE TITLE
BigQuery Scanned Data Limit (MB) override

### ISSUE THREAD

**Issue by MaxBer** [getredash/redash#7187]
### Issue Summary

By declaring & setting a parameter which you use in the following query you seem to break out of the Scanned Data Limit on BQ.

### Steps to Reproduce

1. Setup a BigQuery data source.
3. Set Scanned Data Limit to something low. 1000 MB.
4. Write a query which exceeds the Scanned Data Limit with a timestamp filter.
5. Modify the query to declare and set a parameter:

>   DECLARE filter_ts_1 TIMESTAMP;
>   
>   SET filter_ts_1 = (
>     select timestamp_trunc(TIMESTAMP_SUB(current_timestamp, INTERVAL 15 DAY), WEEK)
>   );

6. Use the defined parameter in place of your timestamp -> Get results from query which exceeds the Scanned Data Limit.

I would expect this to throw a: "Error running query: Larger than 1000 MBytes will be processed"

### Technical details:

* Redash Version: 10.1.0 - slightly modified (I am running the same BigQuery code which exists in tag 24.10.0-dev of redash/query_runner/big_query.py )
* Browser/OS: Chrome, MacOS
* How did you install Redash: Running on ECS on AWS.

**Comment by arikfr** [comment]
It's possible that when there are multiple statements it changes the response format and messes up the limit check.

Is the limit working correctly when not using a parameter?

**Comment by MaxBer** [comment]
That might be it.

Yes it works fine when defining but not using the parameter (maybe some optimization on BQs end).

Also seems to work fine with just a generic select statement (select 1 etc.)

**Comment by arikfr** [comment]
We need to run the query runner's code and see the responses from BQ. Probably something simple.

**Comment by MaxBer** [comment]
Closing this, seems to work fine in 24.10
