### ISSUE TITLE
In addition to email, add other ways to be notified of a triggered alert

### ISSUE THREAD

**Issue by superstrong** [getredash/redash#719]
[Feature Request]

POST JSON to a webhook or integrated endpoint when an alert is triggered and when it returns to a normal state.

- Webhook (most generic)
- chat integration (Slack/HipChat)
- Zapier integration

**Comment by arikfr** [comment]
Actually webhook & HipChat are already supported :) 
But definitely Slack & Zapier are high on the priority list.

**Comment by toyama0919** [comment]
@superstrong 
Hello :blush: 

your requests is this pull requets.
https://github.com/getredash/redash/pull/644

**Comment by superstrong** [comment]
@toyama0919 Thanks! (I didn't see it because I only searched through issues, not PRs)

**Comment by superstrong** [comment]
Done in https://github.com/getredash/redash/pull/644
