### ISSUE TITLE
Can we add support for Chinese in SQL?

### ISSUE THREAD

**Issue by sakuracg** [getredash/redash#7235]
This is very important for Chinese developers!!

**Comment by justinclift** [comment]
It's unclear what you're asking for.  Are you asking for a Chinese localisation of our application?

If so, then it's already there.  You should be able to choose from several different language possibilities in the application preferences.

![image](https://github.com/user-attachments/assets/f71a3c1f-2e31-4bf3-bcbd-7b6c8be6d1ff)

**Comment by justinclift** [comment]
Closing this due to lack of response.
