### ISSUE TITLE
ERROR [server frontend-builder 12/12] RUN <<EOF (if [ "xtrue" = "x" ]; then...)  

### ISSUE THREAD

**Issue by hundong2** [getredash/redash#7237]
### Issue Summary

Occur errors that step Build local Redash Docker image.

```sh
ERROR [server frontend-builder 12/12] RUN <<EOF (if [ "xtrue" = "x" ]; then...)  
------
 > [server frontend-builder 12/12] RUN <<EOF (if [ "xtrue" = "x" ]; then...):
0.340 /bin/sh: 8: Syntax error: end of file unexpected (expecting "then")
------
failed to solve: process "/bin/sh -c   if [ \"x$skip_frontend_build\" = \"x\" ]; then\r\n    yarn build\r\n  else\r\n    mkdir -p /frontend/client/dist\r\n    touch /frontend/client/dist/multi_org.html\r\n    touch /frontend/client/dist/index.html\r\n  fi\r\n" did not complete successfully: exit code: 2
make: *** [Makefile:4: compose_build] Error 17
```

### Steps to Reproduce

1. Local development setup start
2. Build local Redash Docker image Step 
3. Error Occur 

### Technical details:

* Redash Version: latest version
* Browser/OS: WSL2(Window)
* How did you install Redash: Using this page ( https://github.com/getredash/redash/wiki/Local-development-setup#install-nodejs-version-18 )

**Comment by eradman** [comment]
@hundong2 if you revert https://github.com/getredash/redash/pull/7210 does the build complete?

**Comment by hundong2** [comment]
@eradman 
thank you. 
The issue has been resolved. However, a new issue has arisen.

https://github.com/getredash/redash/issues/7239
