### ISSUE TITLE
GCE image for 0.9.0-rc?

### ISSUE THREAD

**Issue by john2x** [getredash/redash#734]
Are images available for the latest stable version? Or is it only for 0.8.1-b1110 for now?

**Comment by arikfr** [comment]
Latest stable is [0.8.3.b1992](https://github.com/getredash/redash/releases/tag/v0.8.3.b1192), while there isn't a GCE image for it you can upgrade the 0.8.1 image with the upgrade script: http://docs.redash.io/en/latest/upgrade.html.

Once 0.9.0 becomes stable I will prepare new image for AWS and GCE.
