### ISSUE TITLE
Feature Request: Hide Header on Dashboard

### ISSUE THREAD

**Issue by AdamUnderwood** [getredash/redash#748]
It would be nice to have a header toggle button or a "presentation" mode.  When enabled, it would ideally hide all of the edit buttons, the header, and refresh information.

**Comment by spectr** [comment]
+1

**Comment by arikfr** [comment]
@AdamUnderwood is this for showing dashboards on some TV screen (#117) or for meetings and such?

**Comment by AdamUnderwood** [comment]
@arikfr It's similar, but also requesting to hide other relevant information from the consumer.

**Comment by arikfr** [comment]
I believe the current full screen button does this.
