### ISSUE TITLE
Results containing opening bracket (<) are not displayed

### ISSUE THREAD

**Issue by Xangis** [getredash/redash#755]
I have this query:

SELECT keywords from recent_searches;

Some of these contain HTML tags or quotes. Like so (output from postgres console):

```
 keywords      
```

---

 10916</cite><span
 11576</cite><span
 12739</cite><span
 1506'-'1
 21666</cite><span
 29002</cite><span
 30328</cite><span
 32710</cite><span
 44035</cite><span
 04289+and+1=(select+0)--+-
 04289+and+1=(select+1)--+-
 62244</cite><span
 93201</cite><span

(ok markdown chokes a bit on that... I'm not sure how to convey it better)

In the Redash query results, the "keywords" field shows up as blank for those items (which were search log entries from bots trying to perform SQL injection attacks). Every item listed above shows up as blank. Which is better than breaking something, but if that data can be escaped cleanly and displayed it would be an improvement.

**Comment by arikfr** [comment]
It's probably a matter of configuring the sanitization. Can you share the query results via CSV, so it's easier to debug?

Thanks.

**Comment by Xangis** [comment]
[redash_results.txt](https://github.com/getredash/redash/files/92952/redash_results.txt)

Each of the lines in the file shows up as blank in the table view of the query.

Thank you.

**Comment by subodh-malgonde** [comment]
This still seems to be an issue. Not just html but even strings like `Hi <user>` are shown as blank.

**Comment by matangover** [comment]
Experiencing the same thing. To reproduce, create a new query on re:dash, and type in the following query:
```SQL
select '<Hello>' as test;
```
Expected to see `<Hello>` in the output table, but the cell is empty. In the Inspector there are some Javascript errors that refer to parsing errors in the sanitizer.

**Comment by matangover** [comment]
@arikfr are we doing something wrong? Is there a way to configure the sanitization?

**Comment by arikfr** [comment]
@matangover nope, nothing wrong, but for now you will have to escape the angular brackets -- 

```sql
select '&lt;Hello&gt;' as test;

-- OR:

select replace(replace('<Hello>', '<', '&lt;'), '>', '&gt;') as test;
```

**Comment by arikfr** [comment]
In new releases, to avoid having this issue all the user needs to do is to uncheck the "Allow HTML content" setting for the column.
