### ISSUE TITLE
Cannot list data sources

### ISSUE THREAD

**Issue by christophergutierrez** [getredash/redash#761]
After fresh install I can add a new data source. It saves successfully but does not show anywhere. If I try to recreate it, it fails (I'm guessing because it already exists).

**Comment by arikfr** [comment]
How did you install and what version are you running?

Can you check the logs for errors when trying to list the data sources? (the log location should be: `/opt/redash/logs/api_error.log`)

**Comment by christophergutierrez** [comment]
I can see the error related to the source already existing:
DETAIL:  Key (name)=(presto_prod) already exists.

I can't see the source in the interface however. One thing notice is when I hit the page:
On instance:
    {u'catalog': u'Hive',
     u'host': u'presto://presto.prod.6si.com',
     u'port': 12000,
     u'schema': u'lenovo',
     u'username': u'hadoop'}
What file contains this information, so I can change it manually?
Thanks!

**Comment by arikfr** [comment]
> One thing notice is when I hit the page:
What page do you mean?

When opening the data sources page, do you see any error in the browser console or re:dash server logs?

**Comment by christophergutierrez** [comment]
I found the original problem. It was on my end. My security zone could not see the database. I've fixed that and not I see the data source after I create it.
The problem I have now is that when I connect to a database I don't get the schema on the side. Any query fails because it can't find any objects.

**Comment by arikfr** [comment]
You don't get the schema, because this feature wasn't implemented in the Hive query runner.

"query fails because it can't find any objects" -> is it a Hive error or a Re:dash one?

**Comment by arikfr** [comment]
(please reopen if it's a Re:dash error with more details , like the exact error message)
