### ISSUE TITLE
Flexible Notification Setting

### ISSUE THREAD

**Issue by CzechJiri** [getredash/redash#763]
I feel current implementation of email/webhook/hipchat is very kosher and a bit too deeply integrated into redash .env setting.

What might work better is having datasource-like approach for notification setting (notification setting done similar way datasources are configured) and would include next to email/hipchat also generic python code option.

This way the actual configuration is done in the web interface and users can have multiple webhook endpoints or multiple slack channels or any custom python implementation(s).

**Comment by arikfr** [comment]
I completely agree. The way it's implemented right now was the quickest solution and probably gives some value. But eventually, as you described, there should be definitions per alert with some global defaults.

**Comment by arikfr** [comment]
#842 implements this.
