### ISSUE TITLE
Migration problem

### ISSUE THREAD

**Issue by ariarijp** [getredash/redash#767]
I've got errors on Vagrant VM, like this.

```
$ export PYTHONPATH=. && find migrations/ -type f  | grep 00 --null | xargs -I file bin/run python file
...snip...
Traceback (most recent call last):
  File "migrations/0003_update_data_source_config.py", line 72, in <module>
    for data_source in DataSource.all():
TypeError: all() takes at least 2 arguments (1 given)
```

`DataSource.all` requires Organization. 

https://github.com/getredash/redash/blob/master/redash/models.py#L415

But, couple of migrations are still calling `DataSource.all` without Organization.

```
$ grep -r 'DataSource.all' migrations
migrations/0003_update_data_source_config.py:    for data_source in DataSource.all():
migrations/0011_migrate_bigquery_to_json.py:    for ds in DataSource.all():
migrations/0014_migrate_existing_es_to_kibana.py:    for ds in DataSource.all():
```

**Comment by arikfr** [comment]
All those lines should be replaced with `DataSource.select()`. I should probably build a Vagrant box, so we don't need to support old migrations...

**Comment by ariarijp** [comment]
Okay, got it.

I'm looking forward to the latest build of re:dash Vagrant box.

Thank you.

**Comment by ariarijp** [comment]
ah, Sorry, one more thing.

Should I close this issue?

**Comment by arikfr** [comment]
I closed it now (and fixed). Thanks!
