### ISSUE TITLE
Can't set up an alert

### ISSUE THREAD

**Issue by royzipuff** [getredash/redash#769]
Hey Arik,

It's Roy, from StoreMaven. 

When trying to set up an alert using a saved query i have, after hitting the "Save" button, im getting an error: "Failed Saving Alert". 

Error 500 from server.. 

Do you know anything about it?

**Comment by arikfr** [comment]
At some point we had a broken version that was missing the `alert_subscribers` table. Upgrading to 0.8.3 or 0.9.0 should fix this.

Assuming this is in fact the issue, and you prefer not to upgrade at the moment, you can fix this by running the following:

```
$ cd /opt/redash/current
$ sudo sudo -u redash bin/run python -c  "from redash.models import AlertSubscription; AlertSubscription.create_table()"
```

(the double sudo is not by mistake...)

If it's something else, can you check for relevant errors in the log (`/opt/redash/logs/api_error.log`)?

**Comment by royzipuff** [comment]
Thanks Arik, solved the problem. 

btw, there is no way to delete an existing alert in UI.. would be nice to add this option.

**Comment by arikfr** [comment]
@royzipuff re. deleting alerts, subscribe to #731.
