### ISSUE TITLE
Support for read-only query permission

### ISSUE THREAD

**Issue by MaxPleaner** [getredash/redash#775]
First off, thanks for redash! I looked at a few other db-interface options and am pleased at how easily redash could be set up. The AWS image is very helpful! 

I'm raising this issue about read vs. write permissions.

I don't know how complicated it would be to accept certain SQL queries and reject others.
Basically, I want INSERT, UPDATE, and DELETE calls to throw errors for all users including admin.

I know it'd be better for a pull request, but I'm hoping this can be tagged as a feature request to see if there is widespread interest.

**Comment by arikfr** [comment]
What I recommend doing is giving Re:dash a read only user in the first
place. Any other solution won't be 100% safe anyway and will be replicating
an existing mechanism (the database ACL).

On Tuesday, 19 January 2016, Max Pleaner <notifications@github.com> wrote:

> First off, thanks for redash! I looked at a few other db-interface options
> and am pleased at how easily redash could be set up. The AWS image is very
> helpful!
>
> I'm raising this issue about read vs. write permissions.
>
> I don't know how complicated it would be to accept certain SQL queries and
> reject others.
> Basically, I want INSERT, UPDATE, and DELETE calls to throw errors for all
> users including admin.
>
> I know it'd be better for a pull request, but I'm hoping this can be
> tagged as a feature request to see if there is widespread interest.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getredash/redash/issues/775>.
>


-- 
-- 
Arik Fraimovich

**Comment by MaxPleaner** [comment]
@arikfr thanks for your response. How do you make a read only user? I just launched with the AWS image.

**Comment by arikfr** [comment]
I meant a read only user in your database. I'm not sure which one you're using, but most (all?) of them support creating a user with SELECT only permissions.

**Comment by arikfr** [comment]
Please re-open if still relevant.
