### ISSUE TITLE
set_google_app_domains invalid choice

### ISSUE THREAD

**Issue by dnikolayev** [getredash/redash#778]
From docs:
>Configure the domain(s) you want to allow to use with Google Apps, by running the command:

>cd /opt/redash/current
>sudo -u redash bin/run ./manage.py set_google_apps_domains {{domains}}

So:
>sudo -u redash bin/run ./manage.py set_google_apps_domains SOMEDOMAIN.COM
>...
>usage: manage.py [-h]
               >{status,shell,users,database,send_test_mail,runserver,version,check_settings,org,ds,runworkers}
>               ...
>manage.py: error: invalid choice: 'set_google_apps_domains' (choose from 'status', 'shell', 'users', 'database', 'send_test_mail', 'runserver', 'version', 'check_settings', 'org', 'ds', 'runworkers')

Function is available in the code, but not in manage.py

so this SQL query fixed problem for me with "Your Google Apps domain name isn't allowed.":

>update organizations set settings='{"google_apps_domains":["SOMEDOMAIN.COM"]}';

**Comment by arikfr** [comment]
There is an error in the docs. It needs to be `... ./manage.py org set_google_apps_domains ...` (set_google_apps_domains is a sub command of org).

**Comment by dnikolayev** [comment]
Oh.. ok.. whatever, fixed by SQL :)
