### ISSUE TITLE
regression: some of the bar graphs in plotly sometimes appear as line graphs when ::filter annotation present

### ISSUE THREAD

**Issue by tokenmathguy** [getredash/redash#779]
Example: (visualization tab)

https://demo.redash.io/queries/1050

When selecting options from the second ::filter (drop-down), some of the bar graphs are showing up as line graphs (looks like it's mistakenly using a scatterlayer instead of using a barlayer).

If the above query is lost, here is the example sql. Just make a bar graph using retrieved_at_month as the x-axis, data_length as series/group, and total_runtime as y-axis:

select
    data_source_id as "id::filter",
    cast(trunc(log(length(query) + 1)) as int) as "query_length::filter",
    to_char(retrieved_at, 'YYYY-MM') retrieved_at_month,
    cast(trunc(log(length(data) + 1)) as int) data_length,
    sum(runtime) total_runtime
from query_results
where retrieved_at >= '2015-10-01'
group by 1, 2, 3, 4;

**Comment by arikfr** [comment]
Looks like it doesn't refresh the series list when the filter value changes. Nice catch.

**Comment by tsibley** [comment]
I've noticed this too on some of my dashboards.  A workaround is to go to the query editor for that query, open up the visualization definition, and re-save it.  That prompted a series list update for me.

**Comment by tokenmathguy** [comment]
Yeah, I've done that, too. The problem exhibits itself again, though, when
you have a ::filter alias in the query and then modify the drop-down value
on the dashboard.

**Comment by tokenmathguy** [comment]
I noticed that the tag was updated from 0.9.2 to 0.10.0. Is this something that can be worked into 0.10.0rc? I've got a large batch of users of our instance of re:dash and know of other fellow engineers at my company with their own instances that also cite this as an issue.
