### ISSUE TITLE
Provide autocomplete dropdown while composing queries

### ISSUE THREAD

**Issue by jcox92** [getredash/redash#788]
I'm not sure what the strategy would be here for multiple different kinds of databases, but I'm guessing most SQLs could simply read in the table and field names that are already present on the front-end. Eventually we'd probably want it to be somewhat context-aware so when you type `tablename.` it gives you a dropdown containing just the table's field names.

**Comment by arikfr** [comment]
Have you seen the current implementation (try `Ctrl`+`Space`)?
It's very basic and can definitely be improved (it's not really context aware).

**Comment by arikfr** [comment]
Please reopen if still relevant.
