### ISSUE TITLE
Feature Request: Add 'last active' column to the /users page

### ISSUE THREAD

**Issue by JohnConnell** [getredash/redash#789]
While this can be accomplished with a query, having it on the /users page would make it more accessible to all users including non-technical ones that might only login to view dashboards and high-level pages. It would help promote accountability across some teams and give admins an easy way to view inactive accounts that they might need to disable or delete.

![redash_last_active](https://cloud.githubusercontent.com/assets/2201507/12505465/84a5741a-c0a4-11e5-9de9-e915ccc5232c.png)

**Comment by arikfr** [comment]
Sounds good. We can update this column in the `record_event` background task when we process the events (I think most actions in the app will trigger some kind of event.
