### ISSUE TITLE
/api/queries/{ID}/results.csv returns cached result

### ISSUE THREAD

**Issue by dangub** [getredash/redash#793]
Repro steps:

1. create query with params, e.g. name:

     `select * from users where users.name= "{{name}}"`

2. save, and attempt to retrieve the query like so:

    `/api/queries/{ID}/results.csv?p_name=foo&api_key=XXXXXXXX`

3. Then, change to `p_name=bar`. 
4. Check results

Results: results for `foo`
Expected: results for `bar`

Version: 0.8.1.b1110

**Comment by arikfr** [comment]
Just to clarify, currently the backend doesn't support parameterized queries with the query results API. The way it works, is that the UI merges the params with the query and sends the backend the resulting query. This is why #285 is still open.

The tricky part in implementing this, is that query execution is async and when calling for query result, you might get a job id back that you need to poll until you get results. I might add support for that and leave for the API caller to implement polling.

For parameters support over API, subscribe to #285.

I will keep this open, to fix the behavior you indicated (it should probably return some error).

**Comment by seigel** [comment]
Alright.  Ran into this last night.  Glad it wasn't me. 

On another tack, is there a way to purge the result from the query results table such that it goes back to the effect of "step 2" again?

**Comment by arikfr** [comment]
In #1069 I fixed the wrong caching of semi-random results for parameterized queries and in #1116 I fixed the API call to return a meaningful error.

Closing this now. Support for parameters is already available in the `POST /api/query_results` API call and to know when `GET /api/queries/<id>/results.json` will support it track #285.
