### ISSUE TITLE
Plotly charts missing data points vs highcharts

### ISSUE THREAD

**Issue by spectr** [getredash/redash#796]
Dataset:
[dataset.zip](https://github.com/getredash/redash/files/103253/dataset.zip)

v9.0 and 9.1 Plotly:
![image](https://cloud.githubusercontent.com/assets/303566/12551866/9d078252-c33b-11e5-9d14-28d93e3efa1d.png)

![image](https://cloud.githubusercontent.com/assets/303566/12551877/beb1285e-c33b-11e5-8628-67b91eb5e044.png)

v7.1 Highcharts:
![image](https://cloud.githubusercontent.com/assets/303566/12551899/0400bfb4-c33c-11e5-9d02-842bfe8dbb5e.png)

![image](https://cloud.githubusercontent.com/assets/303566/12551938/4e773974-c33c-11e5-9bc3-becc948c591c.png)

**Comment by shyamgopal** [comment]
May I know what was the "data source" for this data ?

**Comment by spectr** [comment]
Data source was Postgres.

**Comment by shyamgopal** [comment]
1) Thanks @spectr 
2) Missing data points appear in "Table" section, both in Redash v7.1 and v9.0 ?

**Comment by arikfr** [comment]
Fixed in #829 and it will be part of the next release. Here's how it looks with Plot.ly now:

![image](https://cloud.githubusercontent.com/assets/71468/13035528/2667b808-d35b-11e5-8e6c-9606e6fcedeb.png)

Thanks for reporting this, it uncovered a very nasty bug.
