### ISSUE TITLE
Google Analytics as a potential data source

### ISSUE THREAD

**Issue by shishirsharma** [getredash/redash#800]
They have python library. Let me take a look if this is easy thing to do.

**Comment by arikfr** [comment]
This can be really great, and I'm sure many users will love it.

**Comment by arikfr** [comment]
Might  be relevant: https://ga-dev-tools.appspot.com/query-explorer/

**Comment by arikfr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;oCv3pjSw&#x2F;53-google-analytics-data-source"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Google Analytics data source</a>

**Comment by janurag** [comment]
@arikfr  are we working on this one ?   Any progress ?  
Can you give me some timeline for this feature as its one of the crucial feature for me

**Comment by arikfr** [comment]
I'm not aware of anyone working on this.

If it's crucial for you, you might want to invest the time in implementing it or sponsoring someone who will implement it.

**Comment by arikfr** [comment]
Implemented in #1405.
