### ISSUE TITLE
Clicking on "source" of an existing query changes colors of its graphs 

### ISSUE THREAD

**Issue by shyamgopal** [getredash/redash#802]
If I have an existing (old) query with few existing (old) graphs associated with it, and I click on "source" link on that query's page, it removes earlier "columns to colors mappings" of existing graphs. Colors are set randomly.

**Comment by arikfr** [comment]
Does it happen every time or only on first time you switch to source for every query?

**Comment by shyamgopal** [comment]
Every time. 
1) I create a query, add a graph to it, set the graph's "columns to colors mapping". Add the graph to a dashboard.
2) I open this query. Graph shows old color mapping. I click on 'source' of the query, immediately changes color mapping of the graph. I 'edit' the graph , change color mapping to old setting. Save graph.
3) In dashboard, color mapping of this graph looks ok.
4) Again I open the query page, click on 'source'. Immediately, color mapping of the graph is set to some random mapping. I check the dashboard, color mapping has changed there as well.

**Comment by arikfr** [comment]
Thanks, I will take a look.

**Comment by shyamgopal** [comment]
Thanks @arikfr  !
