### ISSUE TITLE
Feature request:  Select/un-select all series in Plotly graphs  

### ISSUE THREAD

**Issue by shyamgopal** [getredash/redash#804]
1) When Redash was using Highcharts library for plotting graphs, one could select/un-select all data series shown in the graph.
2) After moving graphs to Plotly library, this feature is not available.
3) My _cursory_ reading of Plotly shows that this can be done using "legendgroup". Possible ?

**Comment by arikfr** [comment]
Can you point to an example of legendgroups?
Also need to see if Plot.ly supports custom buttons in the menu.

The more details you give the more likely it will happen :-)

**Comment by shyamgopal** [comment]
1) Thanks  @arikfr for responding
2) Following link explains how "legends" can be grouped under "legendgroup". Maybe we can create a "legendgroup" called "All" and put all "legends" under that, so that we can select/un-select all data series. This link gives code snippet in Python, but I _think_ corresponding JS version should exist.
Link:
https://plot.ly/python/legend/#grouped-legends

**Comment by arikfr** [comment]
Judging by their example, once you enable groups all the series act as one. So it's either groups or one by one... Did you see if there is an option to add custom buttons to the toolbar?

**Comment by shyamgopal** [comment]
1) Oh ok, I thought once you un-select a legend-group you can still select individual legends that are part of it. Sorry, my bad.
2) By buttons you mean something like this ? Buttons do not appear in toolbar (modebar) though:
https://plot.ly/javascript/custom-buttons/
Maybe we can have a div below the graph and control legends from there ?

**Comment by arikfr** [comment]
In one of the Plotly upgrades, we got the option to double click on a series in the legend which disabled all the rest of the series.
