### ISSUE TITLE
Update keeps asking for password

### ISSUE THREAD

**Issue by npateman** [getredash/redash#805]
Hi there,

So i'm trying to update redash, after logging onto the box with ssh and a key pair, no password.

```
fab -H localhost -u ubuntu deploy_latest_release
```

that asks for my password, as does

```
fab -H localhost -u ubuntu -i ~/.ssh/authorized_keys deploy_latest_release
```

Now, obviously I have not entered a password when logging in, so regardless, I reset my password using

```
su passwd ubuntu
```

then tested with

```
su ubuntu
```

password works, except fab won't accept it.  I tried omitting username too, and was asked to do the same with root, again, even after changing / testing root password it does not accept it.

Any ideas what's wrong?

**Comment by arikfr** [comment]
The current Fabric script was designed to run on a different host than the Re:dash host, and connect to it. What happens in your case, is that it tries to SSH back into the same machine and hence asking for password.

**Comment by arikfr** [comment]
@npateman did you get it working?

**Comment by eschultze** [comment]
I know it's not the best way, but every time I run fabric from localhost I do:
`sudo nano /etc/ssh/sshd_config` and change `PermitRootLogin` to `yes`
then
`sudo service ssh restart`
after updating repeat the steps changing `PermitRootLogin` to `no`
Oh... and change `localhost` to the corresponding external IP on `fab -H`.

**Comment by npateman** [comment]
sorry for the late reply, lots of things happened and I had to have a new server setup, long story...

**Comment by nacivida** [comment]
I simply ran the steps on my mac, and it worked. But it seems a bit strange that you can't upgrade it on the same machine.
