### ISSUE TITLE
Is there any way to revert back to Highcharts ?

### ISSUE THREAD

**Issue by simzen85** [getredash/redash#807]
I understand that Plot.ly is open-source but is there anyway that I can still use 0.9.x but switch to Highcharts for graph plotting as it has several features that currently missed from Plot.ly implementation ? 

Thanks.

**Comment by shyamgopal** [comment]
Unless there are too many issues, if you list the features that are lacking in Plotly, which you liked in Highcharts, it would be very helpful. Thank you !

**Comment by arikfr** [comment]
While we can bring back the support for HighCharts, I prefer to avoid it because it will mean double the effort in maintenance. 

As @shyamgopal suggested, can you please list the things you miss? Let's see what it will take to close the gap.

**Comment by simzen85** [comment]
@shyamgopal @arikfr for example the tooltip is now different and less useful than before (doesn't show the "date" and values for all the stacked components) https://monosnap.com/file/NGpB6lIyjT44CZVGSHA87GDBBLMglU

I think it's related to this issue https://github.com/getredash/redash/issues/728

**Comment by arikfr** [comment]
For the sake of maintainability we will stick with one chart implementation, which is for now Plot.ly. I encourage you to open specific issues for problems you encounter with Plot.ly -- preferably with screenshots.

As for the tooltip, it has to improve. But it can show you values for all components, if you click on "Compare data on hover" (the button I circled):

![image](https://cloud.githubusercontent.com/assets/71468/13035399/cbada13c-d357-11e5-9307-c42787bed3db.png)
