### ISSUE TITLE
Query edit pane rearrangement

### ISSUE THREAD

**Issue by lance-edmodo** [getredash/redash#817]
Attached is the Hue query entry UI pane. Notice two things:
1) Execute is below rather than above the text window. This means that you type your query, TAB, ENTER to start it. You don't have to leave the keyboard to type in and run a query.
2) The Explain button. This wraps your query with an explain. This is soooo handy with Hive, because Hive is really slow and often all you want to do is check your syntax as you're building a large OLAP query.

I would like to that re:dash adopt one or both of these features. They are both nice-to-haves.

![hue query entry](https://cloud.githubusercontent.com/assets/9205018/12906434/05bd9976-ce95-11e5-86b7-1f9201dbb432.png)

**Comment by arikfr** [comment]
1. I want to redesign the query screen completely, to make it full screen and have better UX for the schema views and visualization editor. In the meantime, did you know that you can use `Cmd/Ctrl+Enter` to execute a query? No need for tabbing out of the query editor or leaving your keyboard :) You can also use `Cmd/Ctrl+S` to save.

2. Will it be useful if the explain returned inside a table, without a dedicated explain view?

**Comment by lance-edmodo** [comment]
1) Ok, good to know.
2) Every database has a different explain format! I don't know how to read
any of them. A "Copy to Clipboard" button would suffice.

**Comment by lance-edmodo** [comment]
I can't use Undo in the query window after trying a query. The personal
query history feature in Hue and Shib is very very handy. It's about the
only thing I really miss in re:dash.

If you haven't seen Shib I've attached a screenshot. It's by a Japanese guy
who co-started Treasure Data here in San Francisco.

**Comment by lance-edmodo** [comment]
About templates: somehow it is a dicey thing to add because of eventual
consistency. To be web-oriented, since it is about URL links: what about
generating a bookmarklet which supplies the link and a pop-up for the
values?

The application here is for that half-a-dozen queries you do over and over
and just want as browser bookmarks. The UI could have a feature to
auto-generate the bookmarklet and a link to open it in a separate window.
To be fancy, maybe a "Copy to Clipboard" or "Add Bookmark" button.

**Comment by arikfr** [comment]
The query page was redesigned in #984.
