### ISSUE TITLE
Support using other databases like MySQL for metadata

### ISSUE THREAD

**Issue by lance-edmodo** [getredash/redash#818]
We're a Mysql shop and have plenty of those. If I want to run re:dash permanently, I'll have to set up to amazon instances running Postgres just for this.

Do you have plans to make it possible to use something besides Postgres for metadata?

**Comment by arikfr** [comment]
Re:dash has very modest requirements (in terms of resources), so you can run it all on a single instance or along with a micro RDS instance.

Anyway, we don't have plans to support additional databases for metadata storage.
