### ISSUE TITLE
Graph option that makes it possible to link into other tools

### ISSUE THREAD

**Issue by Asimov4** [getredash/redash#830]
Would it be possible to create a graph table option that would make it possible to create links based on the values of each row?

Here's what it would look like:

![link builder redash](https://cloud.githubusercontent.com/assets/897911/13036880/1a47e1c0-d328-11e5-8912-22e6b117f175.png)

**Comment by arikfr** [comment]
It's actually already possible, see an example here:
http://demo.redash.io/queries/1210/source

The query is:
```SQL
SELECT '<a href="https://demo.redash.io/dashboard/ipros-demo-sub_user?p_userId=' || CAST(user_id AS VARCHAR) || '>'|| CAST(user_id AS VARCHAR) || '</a>' AS user_Id,
  COUNT(id) AS cnt,
  MAX(created_at ) AS last_creat
FROM queries
GROUP BY 1
ORDER BY 2 DESC
```

Actual syntax might change based depending on the database you use.

I'm closing the issue, but feel free to continue the discussion.

**Comment by Asimov4** [comment]
Perfect! That's exactly what I needed. Thanks :)
