### ISSUE TITLE
Ability to override min/max values for chart axes

### ISSUE THREAD

**Issue by rkells** [getredash/redash#841]
During the move to Plotly, a key feature for controlling axis limits was left out.

eg:
xlim(0, 100): sets the x-axis to between units 0 - 100. 
ylim(0, 1000): sets the y-axis to between units 0 - 1000

This gives the ability to create consistent data ranges, and at times, more realistic depictions of data.

**Comment by arctica** [comment]
I'd second the request for an option to set axis min/max values. Well, I'd be already happy if we could force the min to 0 for Y axis. Right now it bases the min on the minimum of all values which can create very misleading graphs if you have two Y axis - one starting at 0 and the other not.
