### ISSUE TITLE
Can't add Mysql data sources

### ISSUE THREAD

**Issue by npateman** [getredash/redash#845]
Hi there,

I realise I've experienced this previously but never got to the bottom of the issue as I ended up using a different data source type.

Basically I'm trying to add a Mysql data source, upon doing so it just vanishes and does not appear in the list of datasources, it appears in the list of datasources when using the command,

    sudo -u redash bin/run ./manage.py ds list

I can connect to the datasource manually using the mysql command and list the database, but not in redash.  Any ideas what would cause this to happen?

Nick.

**Comment by arikfr** [comment]
Do you see errors in:
1. Browser console?
2. API server log: `/opt/redash/logs/api_error.log`?

**Comment by npateman** [comment]
I have no idea what's happened, but now the datasources are being enumerated as they should have been... I haven't changed anything, just checked the log as requested...

**Comment by arikfr** [comment]
And do you manage to run a query with this data source?

**Comment by npateman** [comment]
Yeah, that's working now too. Cheers, I'm sure this will appear again at some point, but for now it's working, so thanks.
