### ISSUE TITLE
Vagrant dev setup instructions don't work

### ISSUE THREAD

**Issue by cldellow** [getredash/redash#848]
I followed the instructions at http://docs.redash.io/en/latest/dev/vagrant.html

It did not result in a functioning environment. The server started, but upon trying to login with admin/admin, you get a stacktrace - see the full stacktrace at https://gist.github.com/cldellow/34cf5c2088f366f25d97

Step 8 (Apply migrations) is clearly broken:

`export PYTHONPATH=. && find migrations/ -type f  | grep 00 --null | xargs -I file bin/run python file`

It doesn't sort the migrations, so they are applied in whatever order find finds them. I tried again from fresh, but ran:

`export PYTHONPATH=. && find migrations/ -type f  | sort | grep 00 --null | xargs -I file bin/run python file`

to get ordered migrations. This failed with the same stack trace.

I ultimately ended up dropping the DB, recreating it, then populating it via:

```
bin/run ./manage.py database create_tables
bin/run ./manage.py users create --admin --password admin "Admin" "admin"
```

At this point, redash worked as expected. I'm hesitant to submit a PR as I'm not sure what the "right" fix is here.

**Comment by arikfr** [comment]
I think I will update the instructions to drop the tables and recreate them as you did. It's a simpler process and less error prone than running all the migrations.

Thank you for the suggestion.
