### ISSUE TITLE
Embed error - "Module 'redash.renderers' is not available"

### ISSUE THREAD

**Issue by shamsulbuddy** [getredash/redash#851]
While using the embed link , it was failing with the dependency error as below 

"Module 'redash.renderers' is not available"

So as i quick fix I have commented out the line 

https://github.com/getredash/redash/blob/master/rd_ui/app/scripts/embed.js#L7

Now it works perfectly. Just wondering if anybody else is facing this issue.

**Comment by arikfr** [comment]
Thanks. Applied your fix in #853.
