### ISSUE TITLE
Support for Redshift SSL connection

### ISSUE THREAD

**Issue by Asimov4** [getredash/redash#861]
Hi!

We have enabled the recommended SSL connection for our Redshift cluster: http://docs.aws.amazon.com/redshift/latest/mgmt/connecting-ssl-support.html

Here's what our url looks like: `jdbc:redshift://my-redshift.us-east-1.redshift.amazonaws.com:8192/testdb?loglevel=3&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&tcpKeepAlive=true`

We would like to connect redash to our SSL protected cluster but can't find a way to do that.

Related to: http://docs.redash.io/en/latest/datasources.html#postgresql-redshift-greenplum

Any pointer would be appreciated. We could pick up the work to send a pull request.

**Comment by arikfr** [comment]
If I'm not mistaken the default `sslmode` in libpq (the C library we use to connect to PostgreSQL/Redshift) is `prefer`, which means it will try SSL first but will fall back to non SSL if not available.

Either way, if you set your Redshift cluster to require SSL, then it supposed to "just work". Did you try connecting to your Redshift cluster after enabling SSL and it failed?

We should still provide an option to control the SSL mode, but it will be good to know that at least the basic support exists.

**Comment by Asimov4** [comment]
I tested this. I connected redash to a Redshift cluster where `require_ssl` was set to `false` and the query worked.

I then changed the setting to `require_ssl: true` on that cluster and the exact same query returned with this error message: `Error running query: md5 password authentication failed`

**Comment by arikfr** [comment]
I just tested it with my cluster and it worked. 

Maybe version differences? What version of Re:dash are you using? What operating system (and version)?

**Comment by Asimov4** [comment]
Thanks for checking! We're on re:dash 0.9.0 and the operating system is Amazon Linux.

**Comment by Asimov4** [comment]
Nevermind. It did work out of the box. We needed to remove any URL parameters that slipped into the host field: `?loglevel=3&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory&tcpKeepAlive=true`

Thanks!

**Comment by vb3** [comment]
Redash uses pg8000 library. and the default connect used there sets "ssl" to false. 
http://pythonhosted.org/pg8000/dbapi.html#pg8000.connect

You will need to modify redash/query_runner/pg.py to accept ssl parameter and set it for the pg8000.connect()

**Comment by arikfr** [comment]
@vb3 Re:dash uses psycopg2 and not pg8000.
