### ISSUE TITLE
Switch to pip-tools for managing dependencies

### ISSUE THREAD

**Issue by jeffwidman** [getredash/redash#868]
I was looking through the `requirements.txt` files, and I can't tell which python libraries are directly incorporated into this code vs which are listed merely because they're required by other libs.

Would you be open to switching to [`pip-tools`](https://github.com/nvie/pip-tools) for managing these dependancies? I'd be happy to put together a PR...

**Comment by arikfr** [comment]
The only downside I see is that we will have one more file in the root of the repo (`requirements.in`). Other than that it doesn't change much to the usual workflow, right?

**Comment by jeffwidman** [comment]
Not much. The only real downside right now is it doesn't do a great job of handling when a package needs to be installed on one platform but not another (OS X vs Linux for example)... see: https://github.com/nvie/pip-tools/issues/206#issuecomment-190220105

**Comment by arikfr** [comment]
Usually I update the requirements.txt file on my Mac, so I guess the multi platforms issue is not relevant for us.

Let's give pip-tools a try. Worst case, we can always go back to using plain requirements.txt.

**Comment by arikfr** [comment]
I'm in favor of pip-tools, if anyone wants to add it. Closing this issue, as I don't feel we need an issue to track this.
