### ISSUE TITLE
Update to newer version of Flask-Script?

### ISSUE THREAD

**Issue by jeffwidman** [getredash/redash#869]
Any reason you're still using Flask-Script 0.6.6? It's currently at 2.0.5 on Pypi. 

I recently became a collaborator on that project, so if there's something holding you back, I'd like to know about it. 

FYI that I'm hoping to push out a new version with some of the more recent commits later this week... I'm just waiting until I get a chance to update the changelog since it's been neglected for a bit.

**Comment by arikfr** [comment]
No special reason of using 0.6.6, but I was thinking of replacing `Flask-Script` in with `click`. What's the benefit of using Flask-Script aside from a few built in commands?

**Comment by jeffwidman** [comment]
`click` is a better way to go since it's integrated into the latest version of Flask. Supposedly there will be a new flask release soon (https://github.com/mitsuhiko/flask/issues/1575), but I'm not holding my breath. 

Personally, I'm only maintaining Flask-Script in bugfix mode and the original author is too busy to do much on the package. The one nicety that Flask-Script adds is seamless integration with alternative REPLs like ipython, bpython, etc. 

If it were me, I'd switch to using Flask from GitHub rather than Pypi, pin it to a recent commit where the tests pass so you've got some stability, and that way you get `click` for free until there's an actual release.
