### ISSUE TITLE
Schema in Schema Browser does not Update

### ISSUE THREAD

**Issue by jflatter** [getredash/redash#880]
I have added additional permissions to the user in the PosgresSQL connection and the schema browser does not reflect that.

Any way to kick this to refresh? I can only achieve this when I remake the connection after deleting it.

Thanks

**Comment by arikfr** [comment]
The scheme refreshed every 30 minutes. It might be delayed if there are other queries running. 

How long passed since you updated the permissions?

**Comment by jflatter** [comment]
That is helpful. Any way to force it?

**Comment by arikfr** [comment]
You can manually invoke it from the terminal.

I can send instructions tomorrow morning (in ~10hours).

On Wednesday, 2 March 2016, Jacob Flatter <notifications@github.com> wrote:

> That is helpful. Any way to force it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/getredash/redash/issues/880#issuecomment-191438128>.
>


-- 
-- 
Arik Fraimovich

**Comment by arikfr** [comment]
@jflatter please reopen if still relevant.
