### ISSUE TITLE
Embed widget isn't refreshed properly ?

### ISSUE THREAD

**Issue by simzen85** [getredash/redash#881]
I managed to embed my Redash widgets in some other website, however, it's not refreshed according to the refresh frequency. Can you help to check ? Thanks.

**Comment by arikfr** [comment]
When you visit the query inside Re:dash is it refreshed?

**Comment by simzen85** [comment]
@arikfr yes, in Redash it's refreshed correctly

**Comment by arikfr** [comment]
Might be browser caching then. @akariv did you experience anything like that?

Is the place it's embedded in publicly available, so I can inspect the headers it returns?

**Comment by arikfr** [comment]
Please re-open with an example.
