### ISSUE TITLE
Problem With Static URLs on HTTPS in 0.9.1.b1377

### ISSUE THREAD

**Issue by Xangis** [getredash/redash#884]
I updated my Redash instance to 9.9.1.b1377 on a server using HTTPS connections.

Static files stopped loading because the url_for calls in redash/handlers/static.py returned HTTP URLs and the browser blocked mixed secure/insecure content.

I changed lines 51-54 to include the _scheme parameter in the url_for call and everything started working:

    if settings.MULTI_ORG:
        base_href = url_for('index', _external=True, org_slug=current_org.slug, _scheme='https')
    else:
        base_href = url_for('index', _external=True, _scheme='https')

I don't really know Flask, so I can't say how to make that "_scheme" parameter work for both HTTP and HTTPS sites, but that change fixed my issue with loading static files (.css/.png/.js).

**Comment by arikfr** [comment]
I'm assuming you have nginx as a proxy in front of Redash. Did you set it up to set the x-forwarded-proto header (I might have misspelled the name)?

**Comment by Xangis** [comment]
Yes, I'm using nginx.

The setting:
    proxy_set_header X-Forwarded-Proto $scheme;
is exactly what I needed to add.

It looks like that setting may have been optional on my old server (which may have had different nginx defaults) and with an older version of Redash, but it's definitely required now (and I double-checked the docs -- it's in there in the misc SSL section). Thank you.

I guess there's no harm in adding that to the default nginx config for redash since it'll work for both schemes, right?

(... just checked, it looks like it's in 2 of the 4 different setup nginx files in the git repo -- just not in the ubuntu and amazon_linux versions).
