### ISSUE TITLE
Switch docker compose example to using docker >= 1.9 networking style

### ISSUE THREAD

**Issue by jeffwidman** [getredash/redash#890]
per http://container42.com/2015/10/30/docker-networking-reborn/

**Comment by arikfr** [comment]
I'm not sure now is the time to switch to 1.9 only features. Unless Docker 1.9 completely dropped support for links, I think we should keep using them to be friendly for users with older Docker versions.

**Comment by jeffwidman** [comment]
See also discussion in #898
