### ISSUE TITLE
Docker compose example should use new volumes & networking formats

### ISSUE THREAD

**Issue by jeffwidman** [getredash/redash#899]
Need to switch the docker compose example to the new syntax:

1. Volumes should probably be a dedicated data volume, definitely for postgres, unsure about redis and nginx

2. Links is the old format, I think libnetwork/networking is the new format, but I haven't dug into it fully, and unfortunately I can't get the existing `docker-compose-example.yml` file to work so I can't experiment with the new changes.

Details here: https://docs.docker.com/compose/compose-file/#upgrading

**Comment by arikfr** [comment]
As mentioned in https://github.com/getredash/redash/pull/898#issuecomment-193627048 - the new format requires too new versions of Docker engine and Docker compose.

We can revisit the volume definitions though.
