### ISSUE TITLE
Query execution fails if data source name has unicode characters

### ISSUE THREAD

**Issue by arikfr** [getredash/redash#905]
```
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-17: ordinal not in range(128)
  File "celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "redash/tasks.py", line 31, in __call__
    return super(BaseTask, self).__call__(*args, **kwargs)
  File "celery/app/trace.py", line 437, in __protected_call__
    return self.run(*args, **kwargs)
  File "redash/tasks.py", line 292, in execute_query
    with statsd_client.timer('query_runner.{}.{}.run_time'.format(data_source.type, data_source.name)):
```

**Comment by joaoleite** [comment]
If the user name also has ascii characters, the query is also not performed. My name is João and I was able to run a few minutes without anything to get the accent of my name.

:+1:

**Comment by arikfr** [comment]
I'm pretty sure the issue with unicode in user's name was fixed. What
version of Redash do you have?

**Comment by joaoleite** [comment]
I am using the version that was in the docker a few days ago. When it was fixed? What PR? I can see if I find this line.

Thank you

**Comment by joaoleite** [comment]
@arikfr last updated version of the docker image is different from the latest marking the image docker. I think that's why I picked up a version 20 days ago, right?

My version is 0.10.0+b1774 the latest version...

Look: https://hub.docker.com/r/redash/redash/tags/

Through releases you will updating the latest version?

**Comment by arikfr** [comment]
It's [this line](https://github.com/getredash/redash/blob/master/redash/tasks/queries.py#L425), but maybe you have a different issue. Can you share logs of the error?

As for the Docker version: latest tag always marks the latest *stable* version, which is currently `0.10.1` (and was `0.10.0` when you posted your comment). Version 0.11.0 is still in progress.

**Comment by arikfr** [comment]
Apparently this piece of code doesn't exist anymore. Closing.
