### ISSUE TITLE
Pass an object to run_query() instead of a string

### ISSUE THREAD

**Issue by lethalman** [getredash/redash#907]
Currently the signature of `run_query` accepts a single string, which is the query to run.
I find this is quite limiting, in particular I'd like to know the user logged in redash that is performing the query, to apply custom ACL at query time.

I propose to change the parameter to an object, which should be simply serialized across the queues as JSON. So that we can have something like: `{ "query": "the string...", "user": "the user...", ...}`.

This allows further and easier customization of the UI with custom elements that can be passed down to the query runner, other than just a simple string.

Also thanks a lot for this project, it's great and life saving.

EDIT: removed the part of the discussion about the major release... I was confused by the 0.10 thinking it was a new major.

**Comment by lethalman** [comment]
Another possibility to avoid breaking the API is to provide a default method in `BaseQueryRunner`, `run_query_full` which calls `self.run_query(query_object.query)`.

**Comment by arikfr** [comment]
There is no problem with breaking the API, because all the query runners are packaged with the codebase and can be updated to reflect this change.

But I'm not sure if this change should be in the query runners. Maybe this should be done in [`execute_query`](https://github.com/getredash/redash/blob/master/redash/tasks.py#L260) task?

Can you elaborate more on the usage you were planning for this parameter?

**Comment by lethalman** [comment]
Hi, thanks for the reply.

My use case is to pass the user information to the database, so it's possible to apply ACLs:

```
def run_query(self, queryobj):
  self.conn = self.connect_to_db(ds.host, ds.port, queryobj.user, "somepassword")
  self.conn.query(queryobj.query)
```

So, instead of setting user and password in the datasource, pass it through the query runner. That way, the query runner knows the user logged in redash, and it's possible to apply specific ACL to that user at query level.
E.g. one user is able to read all the tables, but another one shouldn't be able to read all the tables of the same data source.

**Comment by arikfr** [comment]
It feels like the usefulness of this is very narrow as it applies to a specific use case, that requires a specific setup most Redash users don't have.

You can still apply different ACLs on a group basis instead of a user. While it's less granular it feels more manageable.

**Comment by arikfr** [comment]
In case it's still relevant,  I ended up implementing this for a bit different reason in #1355.
