### ISSUE TITLE
Dashboard view of stacked bar chart mixes bars and lines

### ISSUE THREAD

**Issue by jasonshah** [getredash/redash#915]
I typically prefer stacked bar charts in my Dashboards. I have 5 Dashboards, and within each, between 3 and 10 stacked bar charts.
Despite the chart being configured as a stacked bar chart, I see quite often that, _only when the chart is in a Dashboard_, a mix of stacked bars and line points. See the attached few screenshots (which are intentionally cropped due to client sensitivity).

![screen shot 2016-03-11 at 2 43 21 pm](https://cloud.githubusercontent.com/assets/24223/13714990/a546b296-e797-11e5-8e6f-dfe2351f8829.png)

![screen shot 2016-03-11 at 2 43 56 pm](https://cloud.githubusercontent.com/assets/24223/13715006/bd9c77d6-e797-11e5-80dd-6190b44df272.png)

However, when I view the same charts in the Query view, the chart correctly renders as a stacked bar chart:

![screen shot 2016-03-11 at 2 44 46 pm](https://cloud.githubusercontent.com/assets/24223/13715018/d4a423d4-e797-11e5-9493-86c043d8b73c.png)

![screen shot 2016-03-11 at 2 45 04 pm](https://cloud.githubusercontent.com/assets/24223/13715023/def6e93e-e797-11e5-9c14-cfb41fdfba22.png)

This isn't universal; probably 30% of my stacked bar charts correctly render as stacked bar charts in the Dashboard view. And it doesn't seem tied to quantity of series or columns; charts that are both lighter and heavier in both series and row data are exhibiting this behavior.

Please let me know what additional data you need to investigate.

(On re:dash 0.9.0+b1363)

**Comment by arikfr** [comment]
It's a bug that was fixed in 0.9.2. Once you upgrade it should be resolved.

(Please reopen if it persists after the upgrade)

**Comment by jasonshah** [comment]
We upgraded to re:dash 0.9.2+b1536, and re-ran the queries. 
It appears to still be occurring.
![screen shot 2016-03-11 at 9 01 26 pm](https://cloud.githubusercontent.com/assets/24223/13720377/9a8d5a5a-e7cc-11e5-8dd6-3ae5bf9b7ad1.png)

**Comment by arikfr** [comment]
@jasonshah the chart you added its screenshot -- when you edit it, what is set as the "Chart Type" at the top of the visualization configuration?

**Comment by jasonshah** [comment]
"Chart". Screenshot of the configuration.

![screen shot 2016-03-12 at 2 56 14 pm](https://cloud.githubusercontent.com/assets/24223/13725270/a3a7a7e4-e862-11e5-827f-690f02f7972c.png)

**Comment by tokenmathguy** [comment]
This looks to be related to: https://github.com/getredash/redash/issues/779

**Comment by arikfr** [comment]
@jasonshah I managed to reproduce this and in my case #991 fixed this. But will keep this open until you get the chance to test on your instance.

I'm *not* recommending upgrading production deployments to 0.10 yet, but it should be stable soon.
