### ISSUE TITLE
Have a test button when adding databases

### ISSUE THREAD

**Issue by seanauriti** [getredash/redash#942]
Have a button when adding databases to test the connection.

**Comment by arikfr** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;PfRuhqjy&#x2F;55-test-connection-button-when-adding-a-data-source"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> &quot;Test Connection&quot; button when adding a data source</a>
