### ISSUE TITLE
When saving database credentials for the first time, when you return, the fields are blank.

### ISSUE THREAD

**Issue by seanauriti** [getredash/redash#943]
This is for the PostgreSQL database setup

**Comment by arikfr** [comment]
What version of Redash do you use?

**Comment by seanauriti** [comment]
0.9.1 from the ami image

**Comment by seanauriti** [comment]
re:dash 0.9.1+b1377

**Comment by arikfr** [comment]
I'm pretty sure this was fixed in 0.9.2. Mind upgrading and reporting if this still happens?
(There are upgrade instructions in the docs)

**Comment by arikfr** [comment]
Please reopen if it happens with 0.9.2. Thanks.
