### ISSUE TITLE
Installing on Ubuntu 14.04 errors

### ISSUE THREAD

**Issue by fire** [getredash/redash#946]
When using the boostrap script, I had to:

*  pip install -U celery[redis]

Due to https://github.com/celery/celery/issues/2903

and 

* sudo apt-get install libffi-dev

on pip install cryptograph

**Comment by arikfr** [comment]
But the issue you linked to is relevant to newer Celery version than what we use -- can you check what version of Celery do you have?

As for `libffi-dev`, the script installs it on [line 154](https://github.com/getredash/redash/blob/master/setup/ubuntu/bootstrap.sh#L154). Was it needed earlier in the script?

**Comment by arikfr** [comment]
I've had a similar issue now, and updating the Redis lib seems to solve it. Thanks for reporting.
