### ISSUE TITLE
have a setting to show date in US format DD/MM/YY

### ISSUE THREAD

**Issue by seanauriti** [getredash/redash#950]

**Comment by arikfr** [comment]
I guess you found the setting?

-- 
Arik Fraimovich

**Comment by seanauriti** [comment]
Yes, thanks!

**Comment by brettlangdon** [comment]
Where is this setting? I can't find anything in the UI for it :(

**Comment by arikfr** [comment]
@brettlangdon https://github.com/getredash/redash/blob/master/redash/settings.py#L206

**Comment by brettlangdon** [comment]
@arikfr thanks!
