### ISSUE TITLE
Supervisor service for redash_server should restart redis if necessary

### ISSUE THREAD

**Issue by yotammanor** [getredash/redash#975]
Hi,

I hope this is relevant, not sure I got it right, but here is what I got:
I was trying to reconfigure my redash supervisor conf files to work better with other supervisor tasks I have, and I had problems spinning the service back up.

After looking in the logs a bit it seems like it was looking for a connection to 127.0.0.1:6379 which was refused. Then I indeed found a redis_6379 service which was down, and once I turned it back on it worked well.

Since this appears to be a dependency for the server to work, there should be some sort of a test to see whether it is up (and turn it on if not).

Thanks, And love your work!

**Comment by arikfr** [comment]
We're no longer using supervisor in the recommended images, so closing this.
