### ISSUE TITLE
Limit number of records returned by a query

### ISSUE THREAD

**Issue by CzechJiri** [getredash/redash#976]
I typically run `SELECT * FROM ...` just to get a peak on the data and in many cases forget to add limit (yeah I know I know....) .

It would be nice if REDASH would have tunable default limit e.g. 10,000 rows (same way most of the desktop tools like TOAD or Navicat have). Not sure if this is easy to do for any data sources, its certainly trivial for postgres (it executes the limit as a last step).

Ideally displayed on the new query page right next to "refresh schedule". This way user knows about it and can easily change it.

**Comment by arikfr** [comment]
Sounds like a good feature, but need some research on how it will work with the different data source types. Also need to make sure not to apply it to non SELECT queries.

**Comment by lbfr** [comment]
Please find below an example:
`SELECT * FROM table LIMIT 5;`

**Comment by shemul** [comment]
any development yet for this feature ?

**Comment by nasmithan** [comment]
We get very high celery CPU load occasionally, which locks up redash. Likely due to users running queries against large datasets without a LIMIT. Zeppelin has a similar feature (Row count limit per datasource, and data length limit as well). Would be great if this was added. We might just build this out when we get some time.

**Comment by ninja-ken** [comment]
try 
set rowcount 10000;
select * FROM table;

**Comment by tonidas** [comment]
The problem with this matter is that the command highly depends on the DB that it's running the query.

@ninja-ken your solution may not work on all data-sources.

@arikfr What about add in the data-source implementation a way to determine the row count limit for itself? That way, redash could call each function of each data-source. Do you think that can work?

**Comment by nihalsharma** [comment]
Hey, anything on this feature request?

**Comment by swiftomkar** [comment]
Hi, Any update on this feature request? This will help us out a lot!

**Comment by nihalsharma** [comment]
I think I will try superset for now. They have this feature and many other features(scheduling etc.) out of the box. Will keep a look on this thread though.
