### ISSUE TITLE
Migrate wiki data to RTD, then kill the wiki (confusing to have two sets of docs)

### ISSUE THREAD

**Issue by jeffwidman** [getredash/redash#981]
Confusing to have two separate sets of docs. 

I suggest migrating wiki data to RTD, then kill the Github wiki. 

If @arikfr approves, I can put together a PR tackling this.

**Comment by arikfr** [comment]
This wiki is already dead: all the pages there have no content (aside from a link to the page that replaced them) and exist only just in case there was some external link there.

I think enough time has passed and nothing links there, so I turned it off.
