### ISSUE TITLE
Dashboard Corrupted

### ISSUE THREAD

**Issue by puneethpotu** [getredash/redash#985]
Hi there was a out of memory on the Redash server so Python/Celery process was killed and restarted the server. After the restart everything seems to be functional except for two dashboards. Two dashboards were corrupted. I add the screenshot of the dashboard which is blank and now i have only 4 Options.
- Enable/Disable Auto refresh
- Edit Dashboard
- Add Widget
- Archive

The user who created this Dashboard lost the delete permissions on this Dashboard too.

Please suggest if there is a way to recover the dashboard.
![screenshot 2016-04-12 08 13 35](https://cloud.githubusercontent.com/assets/8812146/14465251/14788100-0087-11e6-8faf-74706f3a1a17.png)

**Comment by arikfr** [comment]
I'm not sure it's related to the out of memory incident. But can you provide the following details:
1. What version of Redash are you using?
2. Do you see any errors in the browser console when opening this dashboard?
3. Do you see any errors in the server log (`/opt/redash/logs/api_error.log`) when opening this dashboard?

**Comment by arikfr** [comment]
Please reopen (if relevant) with additional details.
