### ISSUE TITLE
Getting duplicates in the search box even 

### ISSUE THREAD

**Issue by ChiragKParmar** [getredash/redash#986]
Even though there is only one query, the query box is showing duplicates when adding query to a dashboard or creating a new alert.

**Comment by AntoineAugusti** [comment]
Seeing this behaviour also http://puu.sh/omMLA/079c209fa1.png

**Comment by arikfr** [comment]
I think it's because of the join with `DataSourceGroup` [here](https://github.com/getredash/redash/blob/master/redash/models.py#L653).
